### ISSUE TITLE
`hub clone <repo>` does not work at hub version 2.2.1

### ISSUE THREAD

**Issue by wkentaro** [github/hub#1007]
`hub clone <owner>/<repo>` does work.
the feature was changed?

```
wkentaro at anaconda in tmp
$ /usr/local/bin/hub --version
git version 1.9.1
hub version 1.12.4
wkentaro at anaconda in tmp
$ /usr/local/bin/hub clone dotfiles hoge
Cloning into 'hoge'...
remote: Counting objects: 3837, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3837 (delta 0), reused 0 (delta 0), pack-reused 3833
Receiving objects: 100% (3837/3837), 1.15 MiB | 309.00 KiB/s, done.
Resolving deltas: 100% (1992/1992), done.
Checking connectivity... done.
wkentaro at anaconda in tmp
$ hub --version
git version 1.9.1
hub version 2.2.1
wkentaro at anaconda in tmp
$ hub clone dotfiles fuga
Cloning into 'fuga'...
fatal: remote error: 
  Repository not found.
wkentaro at anaconda in tmp
$ hub clone wkentaro/dotfiles fuga
Cloning into 'fuga'...
remote: Counting objects: 3837, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3837 (delta 0), reused 0 (delta 0), pack-reused 3833
Receiving objects: 100% (3837/3837), 1.15 MiB | 326.00 KiB/s, done.
Resolving deltas: 100% (1992/1992), done.
Checking connectivity... done.
```

**Comment by mislav** [comment]
Thanks for the report. I can't reproduce this. What is the line that says "wkentaro at anaconda in tmp"?

**Comment by wkentaro** [comment]
that's my prompt.

**Comment by mislav** [comment]
Can you try `hub --noop clone dotfiles fuga`?

**Comment by wkentaro** [comment]
```
% hub --noop clone dotfiles fuga
git clone git://github.com//dotfiles.git fuga
```

**Comment by mislav** [comment]
Ouch that's not right. Your username is missing! What is the output of `cat ~/.config/hub`? Please omit your actual OAuth token.

**Comment by wkentaro** [comment]
```
$ cat ~/.config/hub
---
github.com:
- protocol: https
  oauth_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by mislav** [comment]
That's really weird that your username isn't in there. Can you add it manually?

```
- protocol: https
  user: wkentaro
```

I have no idea how this happen. Did you ever edit the file by hand?

**Comment by wkentaro** [comment]
I think I didn't edit that file, but after below commands::
```
$ mv ~/.config/hub ~/hub

$ hub --noop clone dotfiles fuga
github.com password for wkentaro (never stored): 
git clone git@github.com:wkentaro/dotfiles.git fuga

$ cat ~/.config/hub
github.com:
- user: wkentaro
  oauth_token: c9e691651559fb577105f941475b84993977d0ba
  protocol: https
```
it works.

**Comment by wkentaro** [comment]
I found the reason.
I used hub installed via gem before (1.12.4), and it creates `.config/hub` formatted without `user:` row.
That's why.

**Comment by JeremybellEU** [comment]
Your oauth token is visible in your 2nd comment. Please remove it asap for your own security. You might want to reset github connection?

**Comment by wkentaro** [comment]
oops. thanks @JeremybellEU !

**Comment by mislav** [comment]
The gem is very outdated by now and I don't recommend using. I'm glad that this is not a bug with current version of hub, though. However, I definitely feel this should have failed with a more descriptive error message rather than just proceeding using a blank string for the user.

**Comment by wkentaro** [comment]
Thanks @mislav.
