### ISSUE TITLE
Release undocumented feature

### ISSUE THREAD

**Issue by fpereira1** [github/hub#1011]
I want to publish and list releases via hub. I didn't see any of this functionality in either `hub help` or in the readme file in this project, however, I found the release command in the source code, which is exactly what I want.

https://github.com/github/hub/blob/master/commands/release.go#L20-L31

Is this undocumented feature or am I missing something?

**Comment by mislav** [comment]
Yes, it's undocumented because we're still deciding on its API and arguments list. You can use it right now, however be aware that its format might change in the next release.
