### ISSUE TITLE
hub doesn't work with git.io urls

### ISSUE THREAD

**Issue by mbodomi** [github/hub#1012]
Hi!
Is it possible to implement?
In bash script it's like

``` bash
#!/bin/bash
tmpfile=/tmp/gitio-resolver-$RANDOM
wget $1 --spider 2> $tmpfile
printf your url is: $(cat $tmpfile | grep Location | cut -d' ' -f2)
rm $tmpfile
```

**Comment by mislav** [comment]
It's an interesting idea. I'm sure we would simply implement the URL resolver in Go instead of using `wget`, but thanks for sharing sample implementation. However, where do you expect people would be pasting git.io URLs for hub? I just don't see it.

**Comment by mbodomi** [comment]
One word: gists, they tend to have too long urls.

**Comment by mbodomi** [comment]
(I meant private/secret gists)
Aand: if I get a git.io url for somebody trustworthy why should I use a browser/self-made script to resolve url, if I could just `hub clone` straight ahead?

**Comment by mislav** [comment]
After some consideration, I don't think this is a good fit for hub core. Thank you for suggesting!
