### ISSUE TITLE
Add a search command

### ISSUE THREAD

**Issue by alexchandel** [github/hub#1016]
To search repositories from the command line. For example, `hub search "cargo edit"` [might print out](https://github.com/search?q=cargo+edit&ref=opensearch):
```
killercup/cargo-edit
renzocast/js-table-editor
xSmallDeadGuyx/FTLContinueEditor
linuxgurugamer/WasdEditorCameraContinued
```

The technical term for this would be "awesome".

**Comment by mislav** [comment]
Yeah, that would be awesome! Please follow #833 for updates, though. Thanks!
