### ISSUE TITLE
Cannot get two-factor auth working

### ISSUE THREAD

**Issue by fatso83** [github/hub#1017]
I have 2FA enabled for GitHub, and used one of my backup codes when prompted for my 2FA code. The logon always fails. I had to disable 2FA for it to work.

Log from console
```
$ HUB_VERBOSE=1 hub fork
github.com username: fatso83
github.com password for fatso83 (never stored):
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for carl-erik.kopseng@MWNOOSLMACLT184.makingwaves.no","note_url":"http://hub.github.com/"}

< HTTP 401
< X-GitHub-OTP: required; app
{"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
two-factor authentication code: 25f22-12345
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
> X-GitHub-OTP: 25f22-12345

< HTTP 401
< X-GitHub-OTP: required; app
{"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
warning: invalid two-factor code
two-factor authentication code: ^C
```

**Comment by mislav** [comment]
Hi. Backup codes are only used for the event you get locked out of your account and you don't have your 2FA device (usually a phone) with you. You can't use a backup code in this scenario.

Is there any reason why you couldn't use a 2FA device (such as Google Authenticator or 1Password on an iPhone) to get a proper code for authentication?

**Comment by fatso83** [comment]
Aha, I thought they were more or less interchangeable with the ones from the Google Authenticator app. 

In this case, my phone broke down this weekend, so I have no access to Google Authenticator, but thought I could still use the backup codes.

If the case is not supported, I guess this could be closed.
