### ISSUE TITLE
pull-request command doesn't seem to respect -C parameter

### ISSUE THREAD

**Issue by scpeters** [github/hub#1020]
I've been having trouble creating a pull request for a repository in a different working directory using the `-C` git parameter. For example, my `PWD` is `/tmp` (not a git repository), and I get errors saying:

~~~
$ pwd
/tmp
$ hub -C /tmp/actual_git_repository pull-request
Aborted: not currently on any branch.
~~~

If I `cd` to the `actual_git_repository` then `hub pull-request` works just fine. So it seems like a bug, but I could be doing something wrong.

**Comment by mislav** [comment]
Yeah sounds like a bug. Which version of hub are you using?

**Comment by scpeters** [comment]
I'm using the `hub-linux-amd64-2.2.2.tgz` precompiled linux binary.

Here's the [script I'm using as well](https://bitbucket.org/osrf/release-tools/src/7dccee51fa7e3edd49db42aa9867ef33529ac89c/jenkins-scripts/lib/homebrew_formula_pullrequest.bash?at=homebrew_formula_pr&fileviewer=file-view-default#homebrew_formula_pullrequest.bash-112:132).
