### ISSUE TITLE
git create fails to add remote on fresh repo

### ISSUE THREAD

**Issue by pdilyard** [github/hub#1027]
This may be a problem with git itself, but when I make a new fresh git repo locally and run `git create`, I get: `fatal: remote origin already exists.`. This never used to be the behavior as far as I can remember.

Here's the set of commands I run:
```
$ mkdir new_repo && cd new_repo
$ git init
$ git create
fatal: remote origin already exists.
```
The repository is still successfully created on Github, but I have to manually run the following command for everything to work properly:
```
$ git remote set-url origin git@github.com:pdilyard/dsci40910.git
```

As a side note, when I run `git init` it sets a default remote called `origin`, and I cannot `git remote rm origin`, or `git remote add origin xxxx` (both result in error messages). This wasn't the behavior I ever remember having from git, so maybe I just have some sort of incorrect config or something.

**Comment by mislav** [comment]
Interesting, thanks for reporting. Do you have any idea why an `origin` remote would exist in a freshly `init`d git repo? Which hub version are you running?

**Comment by pdilyard** [comment]
git version 2.6.2
hub version 2.2.1

I have no idea why the origin remote exists, but I can confirm this:
```
~$ mkdir test
~$ cd test
~/test$ git init
Initialized empty Git repository in /Users/pauldilyard/test/.git/
~/test$ git remote
origin
~/test$ git remote -v
origin	
~/test$
```

**Comment by mislav** [comment]
So, the "origin" remote exists by default but has a blank URL. We could change `hub create` to overwrite the "origin" remote if it was blank to begin with. But I don't understand what exactly creates the blank remote.

Do you have repo templates set up? One of:

* the contents of the `GIT_TEMPLATE_DIR` environment variable;
* the init.templateDir configuration variable; or
* the default template directory: `/usr/share/git-core/templates`.

**Comment by pdilyard** [comment]
Here's terminal output of me searching for all those potential config items you listed:
```
$ echo $GIT_TEMPLATE_DIR

$ cat ~/.gitconfig 
[push]
	default = current
[user]
	name = Paul Dilyard
	email = paul.dilyard@gmail.com
[core]
	editor = nano
	autocrlf = false
	filemode = false
[branch]
	autosetuprebase = always
[credential]
	helper = osxkeychain
[alias]
	tree = log --graph --decorate --pretty=oneline --abbrev-commit
	b = branch
	co = checkout
	cob = checkout -b
	up = pull --rebase --prune
	a = add
	cm = commit
	cmm = commit -m
	cma = !git add -A && git commit
	cmam = !git add -A && git commit -m
	s = status
	l = log --oneline
	pl = pull
	plo = pull origin
	ps = push
[remote "origin"]
	fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
$ cat /usr/share/git-core/templates
cat: /usr/share/git-core/templates: No such file or directory
```
I figured out my problem: it's the `[remote "origin"]` configuration I have set up. Commented that out and everything works as expected. I appreciate all the help even though this turned out not to be a hub problem!

**Comment by mislav** [comment]
Ah you had global `remote.origin.fetch` configuration? Yeah, that's probably not the best idea. Glad you figured it out!

**Comment by abhijit113** [comment]
HI , I have the more less same issue.

git push -u origin master
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


 echo $GIT_TEMPLATE_DIR

$ cat ~/.gitconfig
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[user]
        name = abhijit113
        email = abhijitsen113@gmail.com

$ cat /usr/share/git-core/templates
cat: /usr/share/git-core/templates: No such file or directory


Please help
