### ISSUE TITLE
allow hub checkout to checkout a pull request just by number

### ISSUE THREAD

**Issue by jcwilson** [github/hub#1028]
Not sure how this would work, but I think it would be useful to do something like:
`$ hub checkout "#134"` and hub would checkout the underlying branch automatically

I know we can already do this with:
`$ hub checkout https://github.com/github/hub/pull/134`

but i think this could be a useful shortcut

(the quotes around `#134` are because bash interprets `#` as a comment and ignores everything after it)

Until then, I'll make do with this:
```
$ git config --global alias.copr '!f () { url=$(git config --get remote.origin.url); url=${url##*:}; url=${url%.git}; hub checkout https://github.com/$url/pull/$1; }; f'
$ git copr 134

**Comment by mislav** [comment]
This is planned, but I'm not sure about the syntax: https://github.com/github/hub/pull/186#issuecomment-5926991

I'll close this because it's already on our roadmap. Thanks for suggesting!

**Comment by jcwilson** [comment]
thanks! I didn't see that PR
