### ISSUE TITLE
Hub's pull-request does not request a pull on project's default branch

### ISSUE THREAD

**Issue by davidstosik** [github/hub#1029]
Hello,
while I'm on branch `oPD87xHp-workouts-api`, that was branched out from `master`, which is the GitHub project's default branch, and run `hub pull-request`, I get the following.
```
# Requesting a pull to kenzai:production from kenzai:oPD87xHp-workouts-api
```
I would expect the pull request to target `kenzai:master`, am I wrong?

Please note that `production` has been the project's default branch in the past, not anymore (now `master` is).

**Comment by mislav** [comment]
> Please note that `production` has been the project's default branch in the past, not anymore (now `master` is).

That's the key detail; thanks for sharing. The problem is that git (not hub) remembers the default branch from when you first cloned this repo. After you changed the default branch on GitHub, your local git still remembers "production" as the default branch.

To fix, please run:

```
git remote set-head origin master
```

**Comment by davidstosik** [comment]
Thank you very much, this seems to have done the trick!
