### ISSUE TITLE
Cannot fetch issues -> 404

### ISSUE THREAD

**Issue by meierjan** [github/hub#1032]
I am using the following versions on a mac OS X (El Captain) machine. Installed it using home brew.

``` 
hub --version
git version 2.6.2
hub version 2.2.1
```

When I try to do some git commands like `git issue` hub answers with 
```
master ✓ git issue
Error getting issues: Not Found (HTTP 404)
Not Found
```

The same for `git release`. However `git create` and `git browse` (I wondered if the url was just wrong) are working.

Any thoughts on that? How can I debug which url gets requested?

**Comment by mislav** [comment]
You can debug with `HUB_VERBOSE=1 hub ...`. However, note that `issues` and `release` are in development and not documented yet. Their API and implementation will likely change soon.

**Comment by meierjan** [comment]
Thanks for the input. I will have a look

**Comment by mislav** [comment]
@meierjan Any more information on this? Have you tried with hub v2.2.2? Thanks

**Comment by meierjan** [comment]
Okay, it turned out to be not a hub issue. Its more (or less) an github-api issue. I figured out that I misspelled the repo name some time and renamed it (added one single character) - AFTER cloning it. So my `.git/config` file had the old remote url. As there is as a redirection for the git related urls but not for the api calls the api-requests didn't work anymore.

**Comment by mislav** [comment]
Yeah we need to improve our handling or renamed repositories. Thanks for updating!
