### ISSUE TITLE
How to add a PR description to a `hub pull-request` ?

### ISSUE THREAD

**Issue by bbonamin** [github/hub#1033]
Hello,

I'm loving this command line tool. We use it a lot in our CI scripts to automate workflows between git submodules and repositories. So thanks a lot!

I'm trying to add a description to the PR I'm creating using `hub pull-request` without much success. The use case is we update a submodule, and we construct the URL of the Github comparison between the old and new submodule hashes to add it as a description to the PR.

I've tried giving a multine HEREDOC input to `-m`, but it breaks `hub` internally. I've also tried not setting any message at all, but the tool opens $EDITOR and expects a human to write a message manually, which is a no-go for our CI tool (instead of using the last commit's message and extended description as in Github's web interface, as I was expecting)

Is there any other way I could do this?

Thanks again!

**Comment by hkdobrev** [comment]
You could use the `-F` flag on `hub pull-request` similar to `git-commit`. See https://hub.github.com/#work for an example.

**Comment by bbonamin** [comment]
Thank you very much @hkdobrev! That did it!

**Comment by tklo** [comment]
This doesn't work. The entire string is put into PR's headline and description is empty.

At least when I try to do it like that:
```
            export MESSAGE="
              Job $CIRCLE_BUILD_NUM $CIRCLE_BUILD_URL
              Github diff $CIRCLE_COMPARE_URL
              Github PR $CIRCLE_PULL_REQUEST
              User $CIRCLE_USERNAME
              Workflow ID $CIRCLE_WORKFLOW_ID"

            hub pull-request -F- <<< "$MESSAGE"

```

**Comment by mislav** [comment]
The subject and the body need to be separated by a blank line.

```
hub pull-request -F- <<<"THIS IS THE SUBJECT
THIS IS SECOND LINE OF SUBJECT

This is the body.
This is the second line of body.

This will all be body."
```

**Comment by tklo** [comment]
Yup, it works. Thank you very much @mislav !
