### ISSUE TITLE
hub doesn't support custom ssh binary

### ISSUE THREAD

**Issue by mheap** [github/hub#1035]
I'm using [ssh-ident](https://github.com/ccontavalli/ssh-ident) to manage my SSH keys, and have noticed that hub does not respect my current $PATH.

Removing my alias (`eval "$(hub alias -s)"`) and using the `git` binary directly works as expected

**Comment by mislav** [comment]
Thanks for reporting. What fails exactly?

Hub doesn't interact with SSH directly except reading `ssh_config` to detect hostname aliases. I can't imagine that wrapping `git` with `hub` could break SSH somehow.

**Comment by mislav** [comment]
Closing due to lack of info
