### ISSUE TITLE
Single-commit pull request should use the commit message as pull request template

### ISSUE THREAD

**Issue by JensRantil** [github/hub#1037]
This is what Github does and it's definitely a time saver.

**Comment by hkdobrev** [comment]
@JensRantil This is what `hub` does by default for me. If you can reproduce it consistently, this is definitely a bug. Also check if you have a `.git/PULLREQ_EDITMSG` file. This is similar to how `git-commit` works with `.git/COMMIT_EDITMSG`. If you have started a PR with multiple commits, but cancel it, the file could stay there and if you later start another PR it would reuse the file.

**Comment by JensRantil** [comment]
@hkdobrev I'm using version 2.2.2. Is that an old version?

**Comment by hkdobrev** [comment]
@JensRantil No, it's not. 2.2.2 is the latest stable release. Do you actually reproduce it consistently on different repositories?

**Comment by mislav** [comment]
@JensRantil We should be doing this, but if it's not happening then it's a bug. Could you share steps that would help us reproduce this? Also try to share your `git config push.default` setting.

**Comment by JensRantil** [comment]
Worked now. Must have been user error... Apologize for that!

**Comment by JensRantil** [comment]
FYI, figured out what I did wrong; I had not pushed the branch to the remote before creating the pull request.
