### ISSUE TITLE
User with read permission cant pull request

### ISSUE THREAD

**Issue by NettoPassaro** [github/hub#1043]
We have a user with "read" permission only, and uses github desktop for windows (version 3.0.9.0)

When he create a branch, make some changes, and try to pull request this change, two erros popup:

![capturar1](https://cloud.githubusercontent.com/assets/6041449/11559602/72652acc-99a1-11e5-97c2-ffa2836a0de0.PNG)

![capturar2](https://cloud.githubusercontent.com/assets/6041449/11559608/7c8f8132-99a1-11e5-887a-6526bb0bd754.PNG)

**Comment by mislav** [comment]
Hi, sorry that you're having trouble.

You seem to be asking about GitHub for Desktop, but this issue tracker is for a project called "hub" that is a command-line tool for the Terminal. 

Instead, you should submit your question to https://github.com/contact, where you will be helped by helpful GitHub Support staff. Also don't forget to share how did you expect this feature to work, and why was this behavior surprising to you?

Thanks.
