### ISSUE TITLE
pull-request should open existing pull requests with --browse or -m

### ISSUE THREAD

**Issue by arkarkark** [github/hub#1051]
```
hub pull-request --browse -m 'my new feature'
```

fails if there is already a pull request open

but I really wanted that open in my browser (hence the `--browse`)

I think that if the PR already exists and you have `--browse` or `-o`, then open the exiting pr in my browser.

this is similar (but not quite) to https://github.com/github/hub/issues/897
and maybe also related to https://github.com/github/hub/issues/182 (i.e. if you have the option to add it to the clipboard, do it when the pull request already exists too).

**Comment by parkr** [comment]
Right now, I do `hub browse` then click the link to the PR. It's not ideal, but it works.

**Comment by mislav** [comment]
This is effectively what would a `--web` option do proposed in #1005. Closing this in favor of that PR.

It's already on our roadmap that we want to allow browsing of PRs by just their number, or by a branch name, or by current branch.

**Comment by arkarkark** [comment]
I don't think --web will do what I'm asking for here.

What I want to be able to do is regardless of if I have a PR open on this branch or not. I want to be able to do this:

```
hub pull-request --browse -m 'my new feature'
```

If there is NOT a pull request this creates one and opens the browser
If there IS a pull request this ignores my -m command and just opens up the pull request in the browser.

`hub browse` just opens up the current repo  (not even on the current branch!?)
`hub pull-request --web` seems like it will open up the page to create a pull request and type everything in I would usually put on the command line. admittedly if there is already a pull request it'll show me, but I'll have to click to view it.  I just want to be taken to the pull request with a simple hub command.

I don't even think `--web` should be on the `pull-request` command. It's not creating a pull request. it's opening up the compare branches page. (from which you can create a pull request).

Would you consider reopening this please?

**Comment by mislav** [comment]
The `--web` command (or however it will be called in the final phase) will open the current PR directly without the need for clicking on it separately.

You will be able to use the `pull-request` command to either open a new PR in the web view (if not already existing) or view existing one, based on whether one exists for the current branch.

Does this sound alright?

**Comment by arkarkark** [comment]
Will I be able to fill in the title (and description) form elements on the new PR via the `--web` command? that would be very nice.

either way, the more I think about it the more I like the `--web` idea, hopefully it'll turn into less mistaken pr's into master ;)

Thanks for following up.
