### ISSUE TITLE
Option for hub browse: Print url without opening browser

### ISSUE THREAD

**Issue by blha303** [github/hub#1053]
I'd like to be able to share the url for the last commit quickly, but there doesn't appear to currently be a way to simply get the url that's opened by hub browse before it's opened in a browser, to be piped to a clipboard manager. Can this be implemented please?

**Comment by mislav** [comment]
This should do it: `hub browse -u | pbcopy`

Docs:

```
$ hub browse -h
usage: git browse [-u] [[<USER>/]<REPOSITORY>|--] [SUBPAGE]

[...] With "-u", outputs the URL rather than opening the browser.
```

**Comment by blha303** [comment]
Oh, I tried various commands looking for the help function. Thanks.
