### ISSUE TITLE
Add ability to assign a pull-request to someone

### ISSUE THREAD

**Issue by bvirlet** [github/hub#1055]
eg. `git pull-request -a <USERNAME>` would assign the pull-request to USERNAME on GitHub.

**Comment by mislav** [comment]
Assigning a user was added in https://github.com/github/hub/pull/857 but hasn't been released yet. Stay tuned for a future release that includes this!

**Comment by maxf** [comment]
hub 2.2.3 was released on Jan 22nd but still doesn't include pull-request -a
Is there something holding it up?

**Comment by mislav** [comment]
I'm avoiding adding new features within the `2.2.x` series (as one should between patch releases), but this is definitely slated for 2.3.0. The thing holding up the release is not this feature in particular, but some other things that are shaping up that I'm trying to make part of the same release. Stay tuned!

**Comment by dominguezcelada** [comment]
@mislav Is there an easy way to try locally the feature @maxf mentioned?

**Comment by mislav** [comment]
@dominguezcelada Yes: download one of the 2.3.0-prerelease versions https://github.com/github/hub/releases
