### ISSUE TITLE
hub "bad credentials" error

### ISSUE THREAD

**Issue by jsquyres** [github/hub#1056]
I have a user (@wgropp) who is trying to use hub to grab a pull request from a private repository (mpi-forum/mpi-standard) and is consistently failing to do so; hub complains "Error getting pull request: Unauthorized (HTTP 401)" / "Bad credentials" on his OS X laptop.  @wgropp does not currently have 2FA enabled on his github account.

The @wgropp user has "owner" privileges on the mpi-form/mpi-standard repo.

Here's the full output from his session:

```sh
# Remove ~/.config/hub just to ensure that there are no stale hub credentials lying around
qchost237-252:tmp gropp$ rm -f ~/.config/hub

# git username/password are stored in the OS Keychain
qchost237-252:tmp gropp$ git clone https://github.com/mpi-forum/mpi-standard.git
Cloning into 'mpi-standard'...
remote: Counting objects: 4485, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4485 (delta 0), reused 0 (delta 0), pack-reused 4482
Receiving objects: 100% (4485/4485), 64.58 MiB | 14.52 MiB/s, done.
Resolving deltas: 100% (2471/2471), done.
Checking connectivity... done.

# Now try to hub checkout a pull request against this repo
qchost237-252:tmp gropp$ cd mpi-standard/
qchost237-252:mpi-standard gropp$ hub checkout https://github.com/mpi-forum/mpi-standard/pull/5
github.com username: wgropp
github.com password for wgropp (never stored):
Error getting pull request: Unauthorized (HTTP 401)
Bad credentials

# Sad panda
qchost237-252:mpi-standard gropp$
```

What could be going wrong here?  Are there other places hub may have stashed some old/stale credentials?

**Comment by azdavis** [comment]
Spitballing here, but have you checked Keychain Access for a "github.com" entry?
<img width="836" alt="e" src="https://cloud.githubusercontent.com/assets/6496454/12007588/e09932e2-abd8-11e5-9169-959e10096d5b.png">

**Comment by jsquyres** [comment]
@wgropp Can you check your keychain?

**Comment by wgropp** [comment]
I believe that this was user error (mine), compounded by poor documentation.  I had successfully cloned the repository, but had not set up the separate and oddly independent alternative ssh access, and the error message is more than obscure.

**Comment by mislav** [comment]
@jsquyres @wgropp Do you still have this issue?

Could this be possibly a case that @wgropp's email hasn't been verified? API access is limited for accounts that don't have their email address verified.

**Comment by wgropp** [comment]
You can close this issue.
Bill

William Gropp
Director, Parallel Computing Institute
Thomas M. Siebel Chair in Computer Science
Chief Scientist, NCSA
University of Illinois Urbana-Champaign
