### ISSUE TITLE
Trouble running `pull-request` command on OS X.

### ISSUE THREAD

**Issue by mattjmorrison** [github/hub#1058]
I just installed `hub` from homebrew on OS X and I tried running `hub pull-request`. This is the message that I got:

```
└──➤ hub pull-request
github.com username: mattjmorrison
github.com password for mattjmorrison (never stored):
user: Current not implemented on darwin/amd64
```

I'm not sure what I'm doing wrong, but any help would be greatly appreciated.

Here are the versions that I'm working with:

```
└──➤ hub --version
git version 2.6.4
hub version 2.2.2
└──➤ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F1134
```

Thanks!

**Comment by parkr** [comment]
Interesting! It looks like [it's available for darwin](https://golang.org/src/os/user/lookup_unix.go) under the general unix build flag. If you run `brew remove hub && brew install hub --HEAD`, does this fix itself?

**Comment by mattjmorrison** [comment]
@parkr same result.

**Comment by parkr** [comment]
Hm, ok. It works just fine for me on Mac OS X 10.11.2. Perhaps 10.9.5 isn't yet compatible.

Dump [this file](https://gist.github.com/parkr/cecb2406b417360a1ef20) into some go file in its own directory and execute `go run <filename>`. Does it error?

**Comment by mattjmorrison** [comment]
@parkr I get a 404 on that file.

**Comment by parkr** [comment]
@mattjmorrison Sorry about that – please check the link again.

**Comment by mattjmorrison** [comment]
Here is the result:

```
└──➤ go run lookup_user_unix.go
&{501 20 mattjmorrison mattjmorrison /Users/mattjmorrison} <nil>
```

**Comment by parkr** [comment]
If that works, then building from source should produce a binary of hub that works. I defer to mislav & co.

**Comment by mattjmorrison** [comment]
@parkr building from source using these instructions: https://github.com/github/hub#source did seem to correct the problem - apparently it is something with the homebrew dist?

**Comment by parkr** [comment]
@mattjmorrison Perhaps! Glad you got it working. `--HEAD` [should have built from the source](https://github.com/Homebrew/homebrew/blob/e4e15f3c319cc552121347745af275a6b8eed099/Library/Formula/hub.rb#L6), though. Maybe there was a cache or something lying around that was used instead. Hm!

**Comment by mislav** [comment]
@mattjmorrison I'm glad you solved your problem, and sorry for the trouble. I don't know what causes this, but it seems like it's an incompatibility with pre-built binaries that we distribute with each release and OS X 10.9 :unamused: 

Thanks @parkr for help!

**Comment by jingweno** [comment]
The build process [was recently changed](https://github.com/github/hub/pull/922) since 2.2.2. I wonder if it's related to that. One way to find would be to try out the OSX build of [2.2.1](https://github.com/github/hub/releases/tag/v2.2.1) and see if it works for OS X 10.9.5.

**Comment by buley** [comment]
There is at least one other go-enabled projects with a similar bug filed https://github.com/docker/notary/issues/194 (fix: https://github.com/docker/notary/pull/195). Possibly a Go error in finding the home directory on El Cap. Doesn't look like `hub` caching an oath token for anyone here so I'd look for it to be related to the lookup of the Github oauth token config file.

**Comment by buley** [comment]
Per @jingweno's comment, I've verified that the `2.2.1` binary works for me. `brew` ships 2.2.2. Workaround is to use the `2.2.1` Mac binary.

**Comment by mislav** [comment]
We might need to pull in https://github.com/mitchellh/go-homedir as a workaround.

**Comment by jingweno** [comment]
> Per @jingweno's comment, I've verified that the 2.2.1 binary works for me. brew ships 2.2.2. Workaround is to simply download and use the 2.2.1 Mac binary.

This could be a problem with the cross compile script or a miss in Go's cross compile capability. The `2.2.1` builds were compiled natively on different OSes.

**Comment by mislav** [comment]
This is probably the same issue as #781. We will import go-homedir to solve this, but I'm wondering whether there will be other cgo incompatibilities in other code once execution is allowed to proceed past this point.
