### ISSUE TITLE
How to upgrade 'hub' ? 

### ISSUE THREAD

**Issue by VincentSim** [github/hub#1062]
Hi,

Here is my issue: 
I upgrade my ruby version to ruby 2.2.3p173
After that each command : 
```
hub create
```
or
```
brew upgrade hub --HEAD
```
give 
```
rbenv: hub: command not found

The `hub' command exists in these Ruby versions:
  2.1.2

```

**Comment by mislav** [comment]
You should uninstall the "hub" gem:

```sh
RBENV_VERSION=2.1.2 gem uninstall -x hub
rbenv rehash
```

Then, confirm that Homebrew hub is the only installation remaining:

```sh
which -a hub
#=> /usr/local/bin/hub
```

Then you should be good!

**Comment by sergio-2015** [comment]
Hi,
I have quite the same issue : 
- My ruby version is ruby 2.3.1p112
- when I tried the command "hub create" I got the error message : 
rbenv: hub: command not found
The `hub' command exists in these Ruby versions:
  2.2.3
- So I did as said in the anwser above => I uninstalled hub gem with
"RBENV_VERSION=2.2.3 gem uninstall -x hub"
then I did "rbenv rehash"
and finally "which -a hub"
but the result I got was "hub not found"
I started a new terminal but the result is the same..
Is there a solution ?
Thanks
