### ISSUE TITLE
`hub alias` on Windows 10, git bash shell reports "Unknown Shell"

### ISSUE THREAD

**Issue by SaintPeter** [github/hub#1065]
On Windows 10, running the git bash shell, installed hub and attempted to use:
`eval $(hub alias -s)` command

I get the response `Unknown shell`.

Bash Version:
```
$ bash --version
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.
```

I don't know what that command is supposed to output, but I replaced it with `alias git=hub`, which appears to work.

Regardless, not clear why the above is not working.

**Comment by mislav** [comment]
This is the [logic of detecting the current shell](https://github.com/github/hub/blob/35c76bf91dc3d699173599464b9b41cb877ee440/commands/alias.go#L32-L40). Is the `SHELL` environment variable empty?

As a workaround, use `eval "$(hub alias -s bash)"`.

**Comment by SaintPeter** [comment]
Confirmed that the `SHELL` environment variable is not set on windows when using the Git Bash shell.

Doing `hub alias -s bash` produces the proper output.

The error message could be more explicit:
`Unknown Shell: Set SHELL variable or execute with "hub alias -s <shell name>"`
