### ISSUE TITLE
Prune obsolete/missing config after hub-checkout

### ISSUE THREAD

**Issue by blueyed** [github/hub#1069]
After branches / PRs have been merges I get errors from `git-fetch`:

> fatal: Couldn't find remote ref refs/heads/example

This is caused by entries in `.git/config`, which are created through `hub checkout`:

```
[remote "user"]
	url = git@github.com:user/example.git
	fetch = +refs/heads/cosmetic:refs/remotes/user/example
```
and
```
[branch "user-example"]
        remote = user
        merge = refs/heads/example
```

It would be nice if `hub` would provide some method to prune those, maybe by somehow marking them as auto-generated in the config?!

**Comment by mislav** [comment]
Ouch. I definitely want to prevent future versions of `hub checkout` from add this kind of configuration. Instead, they will checkout by fetching `refs/pull/<ID>` from git.

This is already on the roadmap, but I will keep this open until the change is made.

**Comment by blueyed** [comment]
Makes sense, thanks!

Just for reference / inspiration: https://gist.github.com/jhnns/d654d9d6da6d3b749986
