### ISSUE TITLE
Fork creates git@github remote URL, not http remote URL

### ISSUE THREAD

**Issue by noamross** [github/hub#1070]
When I use `hub fork`, the URL of the new remote for my forked repo is set using `git@github.com:...`.  Is there a way to set a config option to use the `https://` URL for the repo, for those who use HTTP instead of SSH authentication?

**Comment by mislav** [comment]
Yes, there is an option:

```
git config --global hub.protocol https
```

This is documented in `man hub`.

**Comment by ches** [comment]
Suddenly `hub fork` seems to be defaulting to `https` remote URLs for me (using 2.2.3)—was that perhaps a change in this release, which mentions new URL handling? In that case, what is the explicit `hub.protocol` value to instead use SSH, is it `ssh`? The documentation doesn't seem to say.

**Comment by mislav** [comment]
@ches There was no change to the default since it was a patch release.

You probably have `hub.protocol` set somewhere. Check with `git config hub.protocol`

**Comment by ches** [comment]
> Check with `git config hub.protocol`

Nada, I did check this before asking :wink:

**Comment by mislav** [comment]
@ches Thanks for looking into. Which command defaults to HTTPS for you?
