### ISSUE TITLE
How can I regenerate ~/.config/hub

### ISSUE THREAD

**Issue by corysimmons** [github/hub#1072]
I think I had a really old config file. I tried deleting it and reinstalling hub in hopes it'd regenerate my config but no dice.

Any ideas? It'd be nice if this were a command `hub reconfig`.

**Comment by parkr** [comment]
Drive-by suggestion as I was looking for this this week: `hub login [-host=github.enterprise.com]`

**Comment by corysimmons** [comment]
Yeah that looks better.

**Comment by corysimmons** [comment]
After looking around for answers for the past 30 minutes, I realized I could simply try to clone anything and hub would ask for username/password to regenerate my config again. :[

:100:

**Comment by corysimmons** [comment]
No idea why it defaults protocol to `https` though.
