### ISSUE TITLE
Could not find 'bundler' (>= 0.a) among 43 total gem(s) (Gem::LoadError)

### ISSUE THREAD

**Issue by weathery** [github/hub#1074]
Gitlab-ce version:8.3.3
CentOS: 6.7 x86_64
$ sudo bundle install --deployment --without development test postgres aws kerberos
/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:318:in `to_specs': Could not find 'bundler' (>= 0.a) among 43 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/git/home/.gem/ruby/2.2.0:/usr/local/lib/ruby/gems/2.2.0', execute `gem env` for more information
        from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:327:in `to_spec'
        from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from /usr/local/bin/bundle:22:in `<main>'

$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.2.0
  - USER INSTALLATION DIRECTORY: /git/home/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /git/home/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.2.0
     - /git/home/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://ruby.taobao.org/"]
  - REMOTE SOURCES:
     - https://ruby.taobao.org/
  - SHELL PATH:
     - /usr/local/bin
     - /bin
     - /usr/bin
     - /usr/local/sbin
     - /usr/sbin
     - /sbin
     - /git/home//bin

**Comment by ioquatix** [comment]
So.. the issue was?
