### ISSUE TITLE
Windows: `git help hub` couldn't find man page (solved manually)

### ISSUE THREAD

**Issue by tajmone** [github/hub#1080]
I've installed hub on Win 7. But typing `git help hub` in Git (for Windows) Bash produced the following error:
```bash
$ git help hub
Launching default browser to display HTML ...
fatal: failed to launch browser for C:\Program Files\Git\mingw64/share/doc/git-doc/github.htm
```
I've solved the problem manually,like this:
1. renamed the `hub.html` file (that comes with hub) into `github.html`, and
2. placed it into the `C:\Program Files\Git\mingw64\share\doc\git-doc\` folder.
After that it worked fine.

But manually placing a file into the Program Files folder is never a good idea in Windows. It asked administrator permissions, and if I were to uninstall Git for Windows, that single html file will probably be left over, with all the folders structure that contains it.

I've looked into hub's `install.bat` file, and it doesn't seem to take care at all about the help file.
It would be nice to have the bat file handle also the help, and possibily with a more elegant solution, and proper naming.

So, my solution was just a workaround to have at least access to some docs, but I am not sure that was the proper approach, or even the proper document that git help should have been looking for.

Also, maybe with the other version of Git for Windows (Git-Scm) this problem doesn't apply.

**Comment by mislav** [comment]
Thanks for sharing your workaround! I'll close this as a duplicate report of #977. `hub help hub` right now is broken both on Windows and Unix. I'm not sure how to solve it yet, but I think that I should install the man page in a predictable location and then reference the file directly instead of relying on the man page  lookup path.
