### ISSUE TITLE
Is the install from source (via go) broken?

### ISSUE THREAD

**Issue by rbose85** [github/hub#1086]
I have pulled down the `golang` docker container (https://hub.docker.com/_/golang/) and run the `go` command to get `hub`. But I keep getting errors :disappointed:  ...

```sh
root@e30ec5a27653:/go# go get github.com/github/hub
# github.com/github/hub/github
src/github.com/github/hub/github/client.go:157: too many arguments in call to api.Commits
src/github.com/github/hub/github/client.go:157: not enough arguments in call to api.Commits(client.requestURL(url)).Patch
src/github.com/github/hub/github/client.go:178: too many arguments in call to api.Gists
src/github.com/github/hub/github/client.go:178: not enough arguments in call to api.Gists(client.requestURL(url)).Raw
src/github.com/github/hub/github/client.go:199: too many arguments in call to api.Repositories
src/github.com/github/hub/github/client.go:199: not enough arguments in call to api.Repositories(client.requestURL(url)).One
src/github.com/github/hub/github/client.go:239: too many arguments in call to api.Repositories
src/github.com/github/hub/github/client.go:239: not enough arguments in call to api.Repositories(client.requestURL(url)).Create
src/github.com/github/hub/github/client.go:382: too many arguments in call to api.Repositories
src/github.com/github/hub/github/client.go:382: not enough arguments in call to api.Repositories(client.requestURL(url)).Create
src/github.com/github/hub/github/client.go:382: too many errors
```

Am I doing something obviously wrong?

**Comment by IWriteThings** [comment]
I am getting the exact same errors.

**Comment by mislav** [comment]
I don't know what causes these exact errors, but we have recently switched to vendored dependencies within the project, making it incompatible with the standard `go get` method of install.

Instead, could you try cloning the project directly and using `script/build` to create the `hub` executable? You will need Go 1.5.

**Comment by rbose85** [comment]
Yup. From the `golang` docker container I was able to follow the build steps in `README.md` to compile from source;

```sh
$ git clone https://github.com/github/hub.git
$ cd hub
$ ./script/build
$ cp hub YOUR_BIN_PATH
```

That all worked fine. I got the `hub` bin compiled.

However, in my team's project we're using CircleCI and have been relying on the `$ go get github.com/github/hub` command to add `hub` to our `ubuntu` docker container. It would be extremely convenient to be able to pull the `hub` binary without the need to clone the repo and compile. Is there an official PPA for the project?

**Comment by mislav** [comment]
> It would be extremely convenient to be able to pull the `hub` binary without the need to clone the repo and compile.

Could you simply download the [precompiled binaries](https://github.com/github/hub/releases)?

**Comment by rbose85** [comment]
Yes, of course. And it's totally awesome that the precompiled binaries are there, and even that this open source project exists. Many thanks for all of that - please don't think me ungrateful. But the advantage of a PPA, or the `go get` command, is that I'm pulling in the latest version of `hub`.

**Comment by mislav** [comment]
I don't know anything about PPAs, so you're welcome to contribute whatever needs to set up a PPA, or maintain one yourself!

**Comment by IWriteThings** [comment]
Can I request a precompiled binary for an ARM server like one ran by scaleways? x86 and x64 don't seem to function for me and my use case and neither the go get nor the create from source are working for me.

http://dave.cheney.net/2012/09/08/an-introduction-to-cross-compilation-with-go

Is cross compilation something you might be able to add for linux/arm folks like myself?

**Comment by mislav** [comment]
[Our cross-compilation matrix is here](https://github.com/github/hub/blob/35905f710a0e7eb29f102d9ded28995f278ce5d2/script/cross-compile#L11-L17).

I guess we could add `linux  arm  Linux ARM 32-bit` and `linux  arm64  Linux ARM 64-bit` to it and that should work. Do you want to open a pull request for this?

You could checkout the "2.2-stable" branch, add the lines there, run `script/cross-compile 2.2.3` and check if the resulting tarballs are valid on an ARM system.

I tried running this on OS X, but it doesn't let me cross-compile for linux ARM for some reason.

**Comment by IWriteThings** [comment]
@mislav I have added a pull request with the updated code. Please review at your leisure.

Thank you for all your help!
Adding support for arm processors #1090

**Comment by mk0x9** [comment]
Can't install through `go get` too. That section should be removed from README probably.
