### ISSUE TITLE
[Question] Did you mean to shrink the README?

### ISSUE THREAD

**Issue by justinhelmer** [github/hub#1092]
There used to be some great examples on there that I constantly used as reference.

Are those days over and it's all `man hub` now?

**Comment by mislav** [comment]
Yes. People used the README too much as documentation and, as a result, they got confused that a feature they've read about in master branch didn't work when they downloaded the latest stable release. So, it's best to use the man page now, especially after the next release when the [man pages will be so much better](https://github.com/github/hub/pull/1087). Of course, some people would like to read about the features of hub and examples on the web, so I'll be working on improving the Pages-powered site.

In the meantime, you can access the content that you're missing on the [currently published man page online](https://hub.github.com/hub.1.html).

**Comment by justinhelmer** [comment]
Thank you for the timely, well-articulated response.
