### ISSUE TITLE
Initial authentication plain text password and failure message

### ISSUE THREAD

**Issue by NZ-Jaybird** [github/hub#1097]
I've edited the below to hide my password.

I just ran the same command again and it worked perfectly without requiring my details, implying that the command actually succeeded in creating the repository the first time, but failed the verification.

Why is the password entry plain text, and any ideas why the authentication failed on the verification step?

```
$ hub create
github.com username: NZ-Jaybird
github.com password for NZ-Jaybird (never stored): ************
Updating origin
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

```
$ hub create
NZ-Jaybird/CJXJD already exists on github.com
origin  git@github.com:NZ-Jaybird/CJXJD.git (fetch)
origin  git@github.com:NZ-Jaybird/CJXJD.git (push)
set remote origin: NZ-Jaybird/CJXJD
```

**Comment by mislav** [comment]
It seems that hub did its job without problems using GitHub API, but the part where it failed was in fetching the repo with git over SSH protocol. So the error isn't really due to hub.

Are you experiencing further errors?

**Comment by riophae** [comment]
the same here

**Comment by mislav** [comment]
@NZ-Jaybird @riophae On which OS did you experience the plain text password prompt, and with which hub version? Thanks

**Comment by hoangnlm** [comment]
same error as @NZ-Jaybird,
hub version 2.2.9,
mac OSX 10.12 Sierra,
Please help to fix! Thanks!

**Comment by mislav** [comment]
@hoangnlm This might be a git+ssh issue rather than a hub issue. Are you able to clone another public repository over SSH protocol, such as `git clone git@github.com:github/hub.git`? If that fails, you first need to set up SSH key authentication for GitHub, or switch to HTTPS protocol if you prefer that with `git config --global hub.protocol https`.

**Comment by mislav** [comment]
Closing due to stale and lack of info
