### ISSUE TITLE
Flag for cloning the repo into the full github owner/repo path

### ISSUE THREAD

**Issue by fuadsaud** [github/hub#1098]
I couldn't find info about this in the docs, nor browsing the source code. I wonder if there's any way of getting hub to behave like this:

```sh
$ cd ~/Code
$ ls
$ git clone [some flag] github/hub
$ ls
github
$ ls github
hub
```

If not, is there any interest in adding some feature like that? I could throw a chance at implementing.

**Comment by mislav** [comment]
It's an interesting feature idea, and has been suggested before, but for now I want to err on the side of leaving the implementation up to the user (via e.g. specialized script on their machine). See https://github.com/github/hub/issues/689#issuecomment-64836779 for related issues.
