### ISSUE TITLE
print resultant url to stdout on successful 'hub create'

### ISSUE THREAD

**Issue by noffle** [github/hub#1111]
I find it extremely helpful that commands like `hub pull-request` output their resultant url to stdout: it would be excellent to see `hub create` do the same.

**Comment by mislav** [comment]
Not a bad idea, but isn't this need already serviced by calling `hub browse -u` subsequently if you need it? I'm reluctant to add new output to `hub create` in case people are using it from scripts and not expecting anything on stdout.

Nice issue number, btw!

**Comment by noffle** [comment]
Thanks for your thoughts, @mislav!

Given your concerns, it may be that the bigger problem is `hub`'s command set does not provide uniform output. Perhaps this is the best thing to address first. It's otherwise unpleasant to push onto users the need to remember to use `hub browse -u` when they create a repo, but **not** when they do a PR.

As for breaking changes, this is exactly what semver is designed to address.
