### ISSUE TITLE
Unable to push with OAuth Token

### ISSUE THREAD

**Issue by Ginja** [github/hub#1117]
I have a CentOS 6.6 box in which I'm trying to hub & git to push to a GHE repo using an OAuth token. I've followed the advice in #293, but I'm still being prompted for a username & password. It seems like hub is completely ignoring any/all settings as it's not working even if I export the credentials as environment variables:

```
$ hub --version
git version 2.7.1
hub version 2.2.3

$ cat ~/.config/hub
---
GHE_SERVER:
- user: USER
  oauth_token: TOKEN

$ env |grep GITHUB
GITHUB_HOST=GHE_SERVER
GITHUB_USER=USER
GITHUB_PASSWORD=TOKEN

$ HUB_VERBOSE=1 hub push origin
## From here on is the output of the above command despite the $ below
$ git config alias.push
$ git push origin
Username for 'https://GHE_SERVER':
```

I can get this to work on my OS X box using the exact same credentials & setup, the only difference is the hub & git version (lower actually, 2.2.2, & 2.3.2 respectively). I can only get it to work if I enter my user's credentials when it prompts on the CentOS box (username, & token for the password).

**Comment by mislav** [comment]
It doesn't seem like this is hub asking you for a password, but rather git itself. You might be trying to push via `https` protocol but don't have any git credential caching set up. Hub itself doesn't do anything for `git push` and thus doesn't need API authentication either.

**Comment by Ginja** [comment]
You're right! Thanks for the clarification. I got it working.

Closing.
