### ISSUE TITLE
Add support to pull-request template like web interface

### ISSUE THREAD

**Issue by rickmak** [github/hub#1118]
Github web interface now will pre-fill the pull-request description with the template named `PULL_REQUEST_TEMPLATE`. `hub pull-request` can do this too if no `-m` or `-F` is supplied.

refs: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by chris-morgan** [comment]
`hub issue create` also for `ISSUE_TEMPLATE`.

**Comment by mislav** [comment]
Good idea to bake this into hub. I could look into whether that would be hard to add to `hub issue` revamp in #1099. Then, the same approach could be adopted for `hub pull-request`.

**Comment by maxmanders** [comment]
Just wanted to express my interest in this issue too - would be a great feature!

**Comment by pwaller** [comment]
:+1: same idea over here too.

**Comment by ptarjan** [comment]
:+1:

**Comment by alexturek** [comment]
Maintainers: https://github.com/github/hub/issues/937 and https://github.com/github/hub/issues/446 are duplicates

**Comment by maxmanders** [comment]
:+1:

**Comment by tconroy** [comment]
Apologies for the old bump, but has this been implemented? Similar to @ptarjan my org has implemented a template policy, but I would prefer to stay in the CLI. :)
