### ISSUE TITLE
How can I add github tags to my pull request

### ISSUE THREAD

**Issue by edenvicary** [github/hub#1124]
I want to fully create the pull request from terminal, how can I set the tag for it from the terminal.

**Comment by mislav** [comment]
Hi, I presume you are talking about "labels" you want to attach to a pull request. In the latest stable release this isn't possible, however in the master branch (yet unreleased version) this feature was added in this form:

```
$ hub pull-request -l "my label,another label"
```

You can build hub from the master branch (Homebrew on OS X: `brew upgrade hub --HEAD`) to get this functionality, or wait until the next release.

**Comment by edenvicary** [comment]
Thanks @mislav

**Comment by jerome-morgado** [comment]
How to do it automatically ? Ex: On PR to develop, auto assign the label ?
