### ISSUE TITLE
build on netbsd

### ISSUE THREAD

**Issue by aerth** [github/hub#1125]
I needed to comment out `"github.com/mattn/go-isatty"` and `return isatty.IsTerminal(f.Fd())` on `ui/ui.go` to make it build.

It works great now.

**Comment by mislav** [comment]
Could you submit a pull request with these fixes? Do you have any idea why commenting out `go-isatty` worked? If you commented it out, how are you able to call `isatty.IsTerminal()`?

**Comment by aerth** [comment]
I just made that function return true

**Comment by mislav** [comment]
Ah I see. It seems that go-isatty isn't compatible with netbsd. I'll open an issue there to let the maintainer know. Do you have specific build errors that you can paste here? It would be helpful. Thanks

**Comment by aerth** [comment]
```/tmp/go/src/github.com/github/hub/ui/ui.go:42: undefined: isatty.IsTerminal```

**Comment by mislav** [comment]
Thanks for the info! I've bumped up go-isatty to latest version which has netbsd support.
