### ISSUE TITLE
id change, how to make hub realise?

### ISSUE THREAD

**Issue by timgp** [github/hub#1128]
Hi, I have a repository with some committed changes, which has already been forked using hub fork. I now need to fork again with another user id (I just got married), but hub persists in remembering my old credentials.

I've cleaned out git config and do not have a ~/.config/.hub file.

**Comment by timpoultney** [comment]
Resolved it, had forgotten about GITHUB_TOKEN in my profile.

**Comment by mislav** [comment]
Glad you solved it! In the future, you can close out a solved issue :wink:
