### ISSUE TITLE
Use markdown file suffix for `.git/PULLREQ_EDITMSG`

### ISSUE THREAD

**Issue by JensRantil** [github/hub#1129]
Idea: Use markdown file suffix for `.git/PULLREQ_EDITMSG`. My `vim` is great at syntax highlighting markdown, but it does that based on the file suffix. A quick fix, that probably would yield syntax highlighting in other editors is to add `.md` suffix to the edit message file.

**Comment by hkdobrev** [comment]
@JensRantil I'm pretty sure Vim (and other editors) could set up specific syntax to activate based on filename. I've done that before, not sure if I've used a plugin. Sublime Text can do this out of the box as well. The file is without an extension to abide the Git conventions. Even if `hub` adds an extension you would have a similar problem with Git-related files and Vim - e.g. the commit message file. However Vim has a nice integration with Git and it supports a special Git syntax for Git commit messages exactly by detecting the filename, not the file extension.

**Comment by JensRantil** [comment]
Fair point! I'll have a look at that, then.
