### ISSUE TITLE
Add small documentation section about optimising $EDITOR for pull requests

### ISSUE THREAD

**Issue by samholmes1337** [github/hub#1131]
If the `$EDITOR` has been set to `vim`, then by default when it opened there are no special features that make it easier to edit a pull request (like with git commit message where it enables line wrapping and spell checking by default).

By adding the following line:

```
autocmd VimEnter PULLREQ_EDITMSG setlocal spell linebreak wrap
```

Vim will now turn on automatic line wrapping and spellcheck for the `pull-request` command. Could something like this perhaps be added to the documentation? I'm happy to do it myself.

**Comment by mislav** [comment]
Excellent idea, but we do perform those [configuration tweaks for vim when opening the editor](https://github.com/github/hub/blob/aa4611dd9add76b1facda9906fcdf8078a2e89e6/github/editor.go#L116-L117) for pull requests. Are you finding that it doesn't work?

**Comment by samholmes1337** [comment]
Thank you for linking this, I was passively wondering where the relevant logic was!

Having said that, I am finding that it doesn't automatically set those parameters. I've just tested it again with the above `autocmd` line removed from my `~/.vimrc`.

I'm on Mac OS X 10.11 running VIM v7.3.

**Comment by mislav** [comment]
What is your editor configuration? `git var GIT_EDITOR`

**Comment by samholmes1337** [comment]
`git var GIT_EDITOR` outputs `vi`.

**Comment by samholmes1337** [comment]
Running the `vi` command directly opens Vim 7.3, however.

**Comment by mislav** [comment]
Hmm. Maybe `vi` mode doesn't support the `-c "set ft..."` invocation style? Could you change it to `core.editor` to `vim`?

**Comment by samholmes1337** [comment]
Huh, that appears to have done the trick. Evidently `vi` doesn't support (or at least carry over) the `vim` configuration flag. Thank you!

**Comment by mislav** [comment]
Thank you for the assistance! :+1:
