### ISSUE TITLE
hub checkout <PR url> fail with private mode

### ISSUE THREAD

**Issue by testerez** [github/hub#1133]
I'm using github entreprise with private mode enabled.
When I use `hub checkout <PR url>`, I get the following error:
```
fatal: remote error: 
  GitHub private mode is enabled. Git protocol is disabled. Use authenticated http or ssh access instead.
```
My workaround is to manually add the remote using `ssh` url

**Comment by mislav** [comment]
Thanks for reporting. Hub shouldn't be using `git:` protocol for adding remotes [if the corresponding repo is private](https://github.com/github/hub/blob/aa4611dd9add76b1facda9906fcdf8078a2e89e6/commands/checkout.go#L101-L102). Which version of hub are you using? Is this issue happening for you still? Is the fork marked as “secret” or “public” in the web interface of your GHE?

**Comment by testerez** [comment]
I just upgraded `hub` from version `2.2.2` to `2.2.3`. I still have the same issue.
I think that the fork is public:
![screen shot 2016-05-03 at 11 17 31 am](https://cloud.githubusercontent.com/assets/815236/14988152/b07c8886-1120-11e6-9fed-e074b0f783b1.png)

But our GHE is configured with [private mode](https://help.github.com/enterprise/2.1/admin/articles/private-mode/)

**Comment by mislav** [comment]
> I think that the fork is public:

Ah, that's the problem. Hub thinks this repo is public (because the API reports it like so), but isn't aware that the entire GHE instance is in private mode.

Hm. Unsure what we can do in this case. I need to think about this.

**Comment by bluepnume** [comment]
Was there any resolution here? I'm seeing this problem with `hub merge` on github enterprise with `hub version 2.2.9`
