### ISSUE TITLE
How to use hub to create pull requests over ssh 

### ISSUE THREAD

**Issue by prongs** [github/hub#1134]
My enterprise github doesn't allow username-password based authentication.

**Comment by TheDoctorsLife** [comment]
Same way you would push commits to github. You need to tell ssh where your key for github is. Putting this in your config for ssh should work.
```
host github.com
 HostName github.com
 IdentityFile ~/.ssh/your_id_rsa_for_github_goes_here
 User git
```
Related issue #611

**Comment by prongs** [comment]
Excuse me for asking the dumb question, but where is the config for ssh? `~/.ssh` doesn't seem to contain anything but public/private keys and `known_hosts`.

**Comment by prongs** [comment]
Searched on the internet and found it to be at `~/.ssh/config`. I added the config like you mentioned but still `hub pull-request` is asking for username and password :(

**Comment by mislav** [comment]
Sorry @prongs, I think @TheDoctorsLife misunderstood your question.

Hub right now can't authenticate against GE instances that don't allow username/password authentication. What you can do, however, is to login to the web interface, go to your Settings, and generate a Personal Access Token from there. Make sure to give it access to manipulate your repos. Then, copy the generated token string and paste it in your `~/.config/hub` file (create it if needed) like so:

```yaml
# ~/.config/hub
example.com:
- user: prongs
  oauth_token: MYTOKEN
  protocol: https
```

**Comment by mislav** [comment]
This will be solved with #225, so please follow that for updates.

**Comment by brycefisher** [comment]
>  What you can do, however, is to login to the web interface, go to your Settings, and generate a Personal Access Token from there. Make sure to give it access to manipulate your repos. Then, copy the generated token string and paste it in your ~/.config/hub

Could this info be added to the README?

**Comment by mislav** [comment]
@brycefisher That's a good suggestion. I'll make sure that this documentation is available somewhere visible in the next release, to make authentication against GHE easier.
