### ISSUE TITLE
pull-request doesn't take default branch into consideration

### ISSUE THREAD

**Issue by mirfilip** [github/hub#1135]
I'm working with a `vendor/package` repo which is hosted on Github Enterprise and has a `myBranch` set as a default branch.

I create a feature branch locally with `git checkout origin/myBranch && git checkout -b feature/myNewFeature`and commit some changes. For simplicity sake, let's assume there is already an `origin/feature/myNewFeature` that is tracked by my local `feature/myNewFeature`.

I can assert that a default branch is properly set by calling API directly:
```
$ curl "https://my.ghe.org/api/v3/repos/vendor/package?access_token=<<token>>" -s| jq '.default_branch'
"myBranch"
```
When I now try `git pull-request` it creates a pull request against `origin/master` (without asking for base branch). I have two questions:
1. Is there a way for `pull-request` command to start with interactive mode that will ask for every piece?
2. (I see this feature is covered)[https://github.com/github/hub/blob/master/features/pull_request.feature#L360] but it doesn't seem to work in my scenario.

**EDIT**: Here is some more info when running with `HUB_VERBOSE=1`:
```
$ env HUB_VERBOSE=1 hub pull-request
$ git config alias.pull-request
$ git rev-parse -q --git-dir
$ git remote -v
$ git config hub.host
$ git config hub.host
$ git config push.default
$ git config hub.host
$ git config hub.host
$ git rev-parse -q --git-path refs/remotes/origin/feature/myNewFeature
$ git config hub.host
$ git rev-list --cherry-pick --right-only --no-merges origin/feature/myNewFeature...
$ git remote -v
$ git config hub.host
$ git rev-list --cherry-pick --right-only --no-merges origin/master...origin/feature/myNewFeature
$ git log --no-color --format=%h (%aN, %ar)%n%w(78,3,3)%s%n%+b --cherry origin/master...origin/feature/myNewFeature
(...)
```

**Comment by mislav** [comment]
Git (not hub) detects what is your default branch when first cloning the repo. When you change the default branch later using GitHub repo settings interface, locally cloned git repos fall out of date.

You can inform a locally cloned git repo of a new default branch by using:

```
git remote set-head origin myBranch
```

**Comment by mirfilip** [comment]
@mislav I see. It indeed was a problem. Thanks!

Just to finish up on my questions:
1. Doing `git pull-request` with no following options / args starts in an interactive mode.
2. You can always do `git remote show origin | grep HEAD` to ensure what @mislav indicated.
