### ISSUE TITLE
Set default arguments in config?

### ISSUE THREAD

**Issue by justincampbell** [github/hub#1140]
I searched the docs and poked around the source for a bit, but I couldn't find the answer for this.

If I wanted `git pull-request` to always have `-o`/`--browse`, is there a way to do that in either `~/.config/hub` or in `.gitconfig`? Or, is my only option to create an alias?

**Comment by lukmdo** [comment]
@justincampbell maybe  one of this will work for you instead: 
- shell alias command instead @justincampbell alias `gpr="git pull-request -o $*"`
- [git alias](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases)  `git config --global alias.pr 'pull-request -o'`

**Comment by justincampbell** [comment]
This worked great, thanks!

```
git config --global alias.pull-request 'pull-request --browse'
```
