### ISSUE TITLE
set-remote not working with corporate github

### ISSUE THREAD

**Issue by ProLoser** [github/hub#1141]
Tried updating the remote and selecting my corporate github. Note that when i review the url, it's the default github

See screenshot:
<img width="682" alt="screen shot 2016-03-10 at 11 38 38 am" src="https://cloud.githubusercontent.com/assets/67395/13681999/b7c1d0ce-e6b4-11e5-962f-96afabb3b53e.png">

**Comment by mislav** [comment]
Ouch, sorry for the trouble. What was the value of `origin` remote before you ran `set-url`? Thanks for reporting!

**Comment by ProLoser** [comment]
Considering this was 2 months ago I don't remember, but is there a reason it should matter?

**Comment by ProLoser** [comment]
<img width="624" alt="screen shot 2016-05-04 at 11 08 15 am" src="https://cloud.githubusercontent.com/assets/67395/15024156/9bb952f8-11e8-11e6-8c7d-c9f8bbc1db92.png">
