### ISSUE TITLE
Adding Github Classroom support to hub?

### ISSUE THREAD

**Issue by sahilshekhawat** [github/hub#1148]
Hi,

We are planning to create a CLI tool for Github Classroom , which will basically be a wrapper over git. It will support cloning multiple repos (i.e. all submissions for an assignment) and working in context of assignment (which contains multiple git repos) including reviewing, submitting etc and we are wondering if we can include our specific features into hub itself and wanted to know what you guys think. 

That way we don't need to start from scratch and users can use a single tool.

**Comment by mislav** [comment]
Hi, thanks for letting me know about your plans! However, the features that you need sound very specific to your use-case and hub was always historically maintained as a general-purpose git+GitHub tool that doesn't implement any specific workflow.

On the other hand, I had a plan to add a `hub api` command to hub that makes it easier to write CLI tools (in bash, for instance) by allowing you to query specific API endpoints while hub takes care of authentication, JSON encoding and JSON parsing. If I'm successful in making this, it might help you write your CLI tool that only uses hub as a lightweight API wrapper.

What do you think?

**Comment by sahilshekhawat** [comment]
I think its will be awesome to have an api otherwise we will be reinventing the wheel. I am available to help, let me know about your plans.
@johndbritton What do you think?

**Comment by johndbritton** [comment]
@sahilshekhawat I think we're going to need an API for Classroom to implement any desktop or CLI tool. Like I said on the other thread, I don't know if Hub is the right place for this, but I wouldn't be opposed to it if they're open to it.

**Comment by mislav** [comment]
Well, to conclude my thoughts about the initial idea for this thread, I don't think hub will be adding any Classroom-specific features, but it can make things easier for CLI API hackers by providing some generic API querying functionality.

The GitHub API will still have to expose the necessary features to enable whatever functionality you need to get this going.

**Comment by mislav** [comment]
Closing this for now since there's nothing actionable yet, but please ping me with future ideas!
