### ISSUE TITLE
Ask before creating a new fork if one already exsists

### ISSUE THREAD

**Issue by TheDoctorsLife** [github/hub#1158]
This way scripts for example wouldn't be given the chance to wreck your PR, because you can just say no to overwriting your existing branch.

**Comment by mislav** [comment]
Hi I don't understand what you're asking here. Could you elaborate more and what workflow do you intend to solve with a proposed change? Maybe with examples?

Sorry for the late reply.

**Comment by TheDoctorsLife** [comment]
When running hub fork when you have a existing forked branch on github, hub just overwrites the github branch, therefore removing any pushed commits.

**Comment by mislav** [comment]
What does it mean that hub just overwrites the github branch? Which branch gets overwritten? `hub fork` doesn't push any commits to a remote and doesn't deal with branches at all. Plus, when your fork already exists, `hub fork` does nothing but ensure that the git remote is set up correctly.

**Comment by mislav** [comment]
@TheDoctorsLife I didn't understand your initial problem; do you perhaps have more information for me to treat this as a bug? I'd really like to fix things if `hub fork` can lead to loss of information. But right now, I can't see how that can happen, since an existing fork on GitHub never gets overwritten by a new one.

**Comment by TheDoctorsLife** [comment]
What I had happening to me, is if I used hub fork it would appear to delete the existing and replace it with the local copy.

**Comment by mislav** [comment]
> it would appear to delete the existing and replace it with the local copy.

Hub can never delete an existing repository on GitHub.com, not even a fork. It doesn't have any functionality that is able to delete or replace a repository. It can only create new ones.

Can you reproduce your problem? Would you share exact steps you've taken so I might try for myself?

**Comment by TheDoctorsLife** [comment]
I tried it out again, (was in a script) and the bug/issue I was experiencing appears to be gone. Closing issue.

**Comment by mislav** [comment]
@TheDoctorsLife Thanks for the update! 👍
