### ISSUE TITLE
Allow Headings In Pull Requests

### ISSUE THREAD

**Issue by maxmanders** [github/hub#1159]
I use `git pull-request` almost exclusively.  Our organisation has recently introduced pull request templates that include headings, e.g. `### Some Heading`.  Until Hub supports these templates, I read the template file in my editor (Vim), edit, and save/submit the PR.  However, since the '#' symbol is interpreted as a comment, the PR that is rendered in the Github UI has eaten the headings, since they begin with leading '#' symbols.  Is this by design?  Is there a way that I can submit a PR body using `git pull-request` that contains headings?

**Comment by maxmanders** [comment]
I've managed to be a bit more successful with my investigating, and found 'core.commentchar' which I've set as ';' in my `~/.gitconfig`.  That should help me work around using '#' headings in PR messages.  Closing this is unnecessary.

**Comment by mislav** [comment]
I'm glad you found the workaround. I would like if it would be possible to author Markdown headings while keeping `core.commentchar` setting at its default, but for now there doesn't seem to be an easy solution.

**Comment by fbartho** [comment]
Any hope of getting this Feature request re-opened? We just added a `PULL_REQUEST_TEMPLATE` in our repo, and it's less effective if our headings disappear when we use hub XD

**Comment by mislav** [comment]
@fbartho The next release of hub will support `core.commentchar auto`, which will work well with Markdown headings.
