### ISSUE TITLE
pull-request does not work

### ISSUE THREAD

**Issue by alexreg** [github/hub#1160]
It tries to do a pull-request for the project corresponding to the current branch, and also ignores `--head` and `--base` arguments.

**Comment by mislav** [comment]
Hi I'm sorry but you'll have to provide more info.

* Which branch were you currently on
* Does the local branch track another remote branch
* How are `git remote -v` set up? You can anonymize the repo names if you need
* What's your hub version
* What did you expect `pull-request` to do, and what was the actual result?

**Comment by alexreg** [comment]
@mislav Sure.
 
> Which branch were you currently on?
I'm on the *alexreg/czmqpp* branch.
> Does the local branch track another remote branch
Local *czmqpp* tracks remote *alexreg/czmqpp*.
> How are git remote -v set up? You can anonymize the repo names if you need
```
alexreg	git@github.com:alexreg/homebrew-core (fetch)
alexreg	git@github.com:alexreg/homebrew-core (push)
origin	https://github.com/Homebrew/homebrew-core (fetch)
origin	https://github.com/Homebrew/homebrew-core (push)
```
> What's your hub version?
```
git version 2.8.1
hub version 2.2.3
```
> What did you expect pull-request to do, and what was the actual result?
The opened `PULLREQ_EDITMSG` file shows the comment
`# Requesting a pull to Homebrew:master from Homebrew:czmqpp`
when I expect it to show
`# Requesting a pull to Homebrew:master from alexreg:czmqpp`.
If I actually try to proceed with the PR, I get some nasty errors:
```
Error creating pull request: Unprocessable Entity (HTTP 422)
Missing field: "head_sha"
Missing field: "base_sha"
No commits between master and czmqpp
```

**Comment by paul-barry-kenzan** [comment]
Results: 2 errors in 2 files

**Comment by mislav** [comment]
@alexreg I see; thanks for all the info! One more thing that I've forgot: what's your `git config push.default`, if any?

**Comment by alexreg** [comment]
No problem. The value of `push.default` is `simple`.

**Comment by mislav** [comment]
While I'm looking into this, you should be able to work around your issue by doing:

```
hub pull-request -h alexreg:czmqpp
```

**Comment by alexreg** [comment]
Thanks!

**Comment by mislav** [comment]
This is caused by the same issue as described in https://github.com/github/hub/issues/877. Please follow other issue for updates. Thanks!
