### ISSUE TITLE
Within bash script, hub pull-request error on echo <github pull request url>

### ISSUE THREAD

**Issue by willfulbard** [github/hub#1163]
I'm in the process of writing a bash script to automate my pull requests, and I'm trying to do the following:

upstream="ARealOrg/arealrepo:master"
$(hub pull-request -F ~/newreq.md -b $upstream)

It always errors out when hub tries `echo <github pull request url>`.  I've tried the above with backticks instead of $(), and it still errors out.  I've tried the command with -o / --browse, and it works fine and doesn't error out, but I don't really want to have it open the browser every time since i'm sometimes ssh'd into my laptop.

If I run the command outside of the bash script, then it runs fine and the echo doesn't cause a problem.  I'm not too experienced with writing bash scripts, so there is a real possibility that I'm the one causing the problem somewhere.

Bug or user error?

Full text of script:

```#!/bin/bash
set -e

echo -e "\033[1;35m----CREATING PULL REQUEST----\033[0m"

echo -e "\033[32mCreating a new pull request template\033[0m"
repodir="$(git rev-parse --show-toplevel)"
`cp -n $repodir/.github/PULL_REQUEST_TEMPLATE.md ~/newreq.md`
vim ~/newreq.md

# Create proper string for pull request
upstream="$(git remote -v | grep '^upstream.*(push)' | sed -E -e 's/^upstream//' -e 's/^[^a-z]//' -e 's/^[^:]+://' -e 's/\.git.+/:master/')"

echo -e "\033[32m####hub pull-request -F ~/newreq.md -b $upstream \033[0m"
$(hub pull-request -F ~/newreq.md -b $upstream)

rm -f ~/newreq.md

echo -e "\033[1;35m####Final status: \033[0m"
git status```

**Comment by willfulbard** [comment]
Oh, right:
git version 2.6.4
hub version 2.2.3

**Comment by buehmann** [comment]
User error, I'm afraid. The line
```
$(hub pull-request -F ~/newreq.md -b $upstream)
```
will execute "hub pull-request" in a sub-shell, capture the output and will try to execute the output (which is the pull-request URL, I suppose) in the current shell, which will fail.

You probably want to get rid of the surrounding $() completely and learn some shell scripting. By the way, your `cp -n ...` line has the same problem but cp's output is empty in this case.

**Comment by willfulbard** [comment]
I see, understand where I went wrong. Thanks for taking the time to answer, I appreciate you pointing me in the right direction, and I'll try to learn some shell scripting.

**Comment by buehmann** [comment]
You're welcome.
