### ISSUE TITLE
~/.config/hub does not work with popen on python

### ISSUE THREAD

**Issue by erictrade** [github/hub#1164]
I am using a toll called weblate, which is using hub to work with the repository.

So, when I first give a command on command line, it asks for my username ans password, and creates a token on ~/.config/hub, as expected. Any other thing I do on command line, it doesn't require my user name or password again.

But, weblate uses popen, on a python script, to call gub. something like this:

```
        process = subprocess.Popen(
            ['hub', 'fork'],
            cwd='path/to/my/repo',
            env=get_clean_env({'GIT_SSH': ssh_file(SSH_WRAPPER)}),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,            
        )
        output, output_err = process.communicate()
        retcode = process.poll()
```

So, when it tries to execute the command, it doesn't find the ~/.config/hub file, because there is no home directory for process, right?

Also, I see there is a environment variable that can be defined, which is HUB_CONFIG, to point to the hub configuration file. But again, there is no way to set a environment variable for a process, right?

Is there a way to define a hub configuration file when running from a popen process? Maybe a global config file which hub will look if it doesn't find a ~/.config/hub file?

Thanks in advance!

**Comment by mislav** [comment]
Sorry for late reply. I'm not sure what you're asking. You seem to be using `get_clean_env` and setting `GIT_SSH` environment variable manually. Can't you use the same approach to set either HOME or `HUB_CONFIG` value too? Anyway, I'm not too familiar with Popen on python, but this is definitely possible. It's also out of scope for this project, which doesn't deal with python at all, so it's your responsibility to perform due diligence. 😉

**Comment by erictrade** [comment]
Hi @mislav! Thank you for your response! I'll try the approach you suggested! Thank you so much!
