### ISSUE TITLE
How do I determine the GitHub username?

### ISSUE THREAD

**Issue by sjackman** [github/hub#1169]
I would like to know the GitHub username to determine the name of the remote created by `fork`. Something like `hub config hub.user` would be helpful. Here's a workaround:
```sh
sed -ne 's/^- user: //p' ~/.config/hub
```

**Comment by mislav** [comment]
Yes, I've experienced this problem too when automating a process using `hub fork`. [Here's how I solved it](https://github.com/rbenv/ruby-build/blob/8cab2ad05918415bd9024548a9811cee9ee01359/script/brew-publish#L47-L48), but it's definitely not pretty.

I'm aware of various `hub fork` usability problems which are being tracked in different open issues such as https://github.com/github/hub/issues/762. I'm closing this one for duplicate for now. Thanks for reporting!

**Comment by sjackman** [comment]
Yes, this issue results in a usability issue with fork. Still I think a command (regardless of the use case) to return the user's GitHub username would be useful.

**Comment by sjackman** [comment]
Thanks for sharing your workaround.

**Comment by mislav** [comment]
> A command (regardless of the use case) to return the user's GitHub username would be useful.

Yes, the idea for that is tracked in #225

**Comment by sjackman** [comment]
Ah, thanks!
