### ISSUE TITLE
Support log --pr

### ISSUE THREAD

**Issue by kompiro** [github/hub#1173]
I'd like to know what the `Pull Request` makes this change in the file like commits.
Because Pull Request contains more information than commits. Their are description, and reviewer comment, and build status, and so on.

Does hub support like this?

My idea is like below: 

```
$ hub log --pr commands/pull_request.go
941379 #1165 Fix copy-pasta
...

```

**Comment by mislav** [comment]
That's a really good suggestion. Right now there is no way to do this using hub, but you could simulate the output by doing a plain bash script (no hub needed):

```sh
#!/bin/bash
set -e

find_pull() {
  git log --merges --ancestry-path --oneline "$1.." | awk '
    /Merge pull request #/ { sub("#", "", $5); print $5 }
  ' | tail -1
}

git log --oneline --no-merges "$@" | while read sha subject; do
  pull_id="$(find_pull "$sha")"
  [ -z "$pull_id" ] || pull_id="#${pull_id}"
  printf "%7s %5s %s\n" "$sha" "$pull_id" "$subject"
done
```

Usage: `git-log-pr commands/pull_request.go`

You might find that this can be slow when there are many commits touching this file. To speed up the command, you can pass a limit to the number of commits returned:

```
git-log-pr -5 commands/pull_request.go
```

**Comment by kompiro** [comment]
Ofcause we can do that by shell script. I know some people implement it by shell script.  so I wrote this feature request. 

Thanks to read my ticket.
