### ISSUE TITLE
allow corporate github pull requests

### ISSUE THREAD

**Issue by erjoalgo** [github/hub#1175]
```
[debian-vm]$ hub pull-request
Aborted: the origin remote doesn't point to a GitHub repository.
[debian-vm]$ ^C
[debian-vm]$ grv
origin	git@github.company.internal:org/repo.git (fetch)
origin	git@github.company.internal:org/repo.git (push)
[debian-vm]$ 
```

instead of checking for the uri, can you check whether the github api endpoints exist at the remote?

**Comment by mislav** [comment]
> instead of checking for the uri, can you check whether the github api endpoints exist at the remote?

That's a solid suggestion. For now, you'll have to whitelist the Enterprise URL as suggested in the documentation:

> ### GitHub Enterprise
By  default,  hub  will  only  work  with  repositories that have remotes which point to github.com. GitHub Enterprise hosts need to be whitelisted to configure hub to treat such remotes same as github.com:
>
>     $ git config --global --add hub.host my.git.org

**Comment by erjoalgo** [comment]
I couldn't find those docs in the main page and there was no man page installed for me (consider making those docs easier to find)

After following those instructions:
```
[debian-vm]$ GITHUB_HOST=github.some.company.com hub create
github.some.company.com username: my-user-name
github.some.company.com password for my-user-name (never stored): 
Error creating repository: Unauthorized (HTTP 401)
Bad credentials
[debian-vm]$ GITHUB_HOST=github.some.company.com hub create
github.some.company.com username: my-user-name
github.some.company.com password for my-user-name (never stored): 
Error creating repository: Forbidden (HTTP 403)
This API can only be accessed with username and password Basic Auth
```

Yet I can manually create using the api:

curl -i https://github.some.company.com/api/v3/user/repos -u user:password -X POST -d '{"name":"my-repo"}'
```

**Comment by mislav** [comment]
I'm glad you solved your problem! Closing this because Enterprise authentication is already something on my radar and getting improved in the next release.
