### ISSUE TITLE
Error HTTP 307

### ISSUE THREAD

**Issue by rubikitch** [github/hub#1178]
I got an error in forking and pull-request.
 $ hub fork
 Error creating fork: Temporary Redirect (HTTP 307)
 Moved Permanently
 $ hub pull-request
 Error creating pull request: Temporary Redirect (HTTP 307)
 Moved Permanently

**Comment by sanmiguel** [comment]
Adding a bit more info from the problem I just hit: this seems to happen when you've renamed a repository and your remote is still pointed at the old name.

**Comment by rubikitch** [comment]
Error happened at milkypostman/melpa repository.
1. Delete my fork
2. cd /tmp; hub clone milkypostman/melpa; cd melpa
3. hub fork
Error creating fork: Temporary Redirect (HTTP 307)
Moved Permanently

**Comment by rubikitch** [comment]
What URL does the redirection point at?
I tryed to figure out it but hub did not have --verbose or --debug option.

**Comment by sanmiguel** [comment]
If you go to https://github.com/milkypostman/melpa it redirects to
https://github.com/melpa/melpa

If you try to do `hub clone melpa/melpa` I'd guess that'll work.

**Comment by rubikitch** [comment]
It works! thank you very much!!
I wish hub continued with redirected URL.
