### ISSUE TITLE
corporate github create issue

### ISSUE THREAD

**Issue by erjoalgo** [github/hub#1180]
```
[debian-vm]$ GITHUB_HOST=github.some.company.com hub create
github.some.company.com username: my-user-name
github.some.company.com password for my-user-name (never stored): #providing password here
Error creating repository: Unauthorized (HTTP 401)
Bad credentials
[debian-vm]$ GITHUB_HOST=github.some.company.com hub create
github.some.company.com username: my-user-name
github.some.company.com password for my-user-name (never stored): #providing oauth token here
Error creating repository: Forbidden (HTTP 403)
This API can only be accessed with username and password Basic Auth
```

Yet I can manually create using the api:

`curl -i https://github.some.company.com/api/v3/user/repos -u user:password -X POST -d '{"name":"my-repo"}'`

**Comment by TheDoctorsLife** [comment]
Try `GITHUB_HOST=github.some.company.com/api/v3`

**Comment by erjoalgo** [comment]
still does not work.

**Comment by erjoalgo** [comment]
I solved the issue by creating a file ~/.hub-config
```
---
github.onugq.vq.com:
- user: 760677060
  oauth_token: 9u224u3gib3c37680c0313sl4p64p741l343kh7w
  protocol: https
```
and pointing to it:

`HUB_CONFIG=~/.hub-config hub create`

**Comment by mislav** [comment]
@erjoalgo Sorry for the trouble! Hub accesses the GitHub Authorizations API initially which (unlike repo creation API) can't be accessed using OAuth token as password; in other words, it needs the real GHE password for your account. If you don't have a password (for instance, using a 3rd-party authentication service to log into GHE), then the workaround you discovered is the only way for now. This will be made simpler in a future release with a specialized command to handle GHE authentication.

**Comment by filler** [comment]
Any reason not to stick your hub-related config bits into `~/.config/hub`?  I believe thats the global default.  I was able to get the following to work: https://gist.github.com/filler/411313daacb52a4a9bd7ea065a55f57d

**Comment by mislav** [comment]
@filler That looks like a good workaround, yes. 👍
