### ISSUE TITLE
git: 'pull-request' is not a git command

### ISSUE THREAD

**Issue by chipoglesby** [github/hub#1183]
I'm running a shell script that will automatically create a pull request for my personal repo. When I run the command: git pull-request -m "Test for $(date +%m-%d-%y)" in terminal, it works fine.

When I execute my script "./testPull" I get this I get this error: git: 'pull-request' is not a git command. See 'git --help'.

I'm not sure why it would run in terminal, but not when included in a script.

**Comment by TheDoctorsLife** [comment]
Its because your shell script doesn't pick up on the alias to hub. The easiest way to fix this is to change your script to use hub rather then git.

**Comment by chipoglesby** [comment]
@TheDoctorsLife thank you, that works perfectly.
