### ISSUE TITLE
feature request: "git config --global hub.protocol https" as default for windows

### ISSUE THREAD

**Issue by JohnML1** [github/hub#1185]
system: windows XP

As a Newbie it took me days to learn:

git push origin master

error message:
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

solution:
git config --global hub.protocol https

Why not set https protocol as default for windows users?

Hub is a great piece of software, thank you!!!!!!!!!!!!!!

**Comment by mislav** [comment]
We will probably make the https protocol the default in the future major version. Thanks for the suggestion! But in the current 2.2.x release series, the default will stay the same for backwards-compatibility.
