### ISSUE TITLE
-l flag for `hub pull request` isn't working

### ISSUE THREAD

**Issue by avivalk** [github/hub#1192]
I'm on hub version 2.2.3 and when I try to add `-l RELEASE` to my `hub pull-request` command, I get an error
`unknown shorthand flag: 'l' in -l`

and the usage message doesn't contain `-l`
```usage: git pull-request [-f] [-m <MESSAGE>|-F <FILE>|-i <ISSUE>|<ISSUE-URL>] [-o] [-b <BASE>] [-h <HEAD>]```

Are labels supported in version 2.2.3?

**Comment by mislav** [comment]
No, sorry; labels are slated to come with 2.3.0 which is due soon!

In the meantime you can try to build hub from the master branch.
