### ISSUE TITLE
hub release create -f

### ISSUE THREAD

**Issue by fpereira1** [github/hub#1193]
Hi

I spent some time today debugging an issue on why the file with contents of my release was not sent to the github release, using this command

    hub release create -f changelog.md "v0.10.23"

It turned out that the first line on my file was empty. Adding the first line with the name of the release fixed the issue.

I am keen to submit a PR to default to something like the first non-empty line as the title as It took me a while to identify what was happening there.

Unless this is already a known issue?

**Comment by mislav** [comment]
Yes this is a known issue. `hub release` was generally a very messy implementation in the current stable version 2.2.3. In the next version of hub, `release` was already rewritten from the ground up and much better. For instance, in the master branch if you omit the release title, the command aborts with:

```
Aborting release due to empty release title
```

So I'm going to close this as resolved and you'll just have to wait until release 2.3.x or build from the master branch 😉 Thanks!
