### ISSUE TITLE
feature request: automatic create repository as private

### ISSUE THREAD

**Issue by greenboxal** [github/hub#1194]
I think that when using `hub create` the repository should be private by default if the organisation/user has private repositories. This can prevent accidental exposure of sensitive code.

At least, there should an option for controlling this behaviour.

**Comment by mislav** [comment]
This was already requested before in the form of [default per-command config](https://github.com/github/hub/issues/964). It's a great idea, and I'm looking into ways to implement this. Once done, you will be able to set the `-p` flag by default every time you `hub create`.

Right now, as a workaround, you can set a git alias:

```
git config --global alias.create "create -p"
```

So now when you run `hub create`, it will become `hub create -p`. The drawback of this approach is that you won't be able to create public repositories this way.

I'm going to close this as a duplicate. Please follow the referenced issue for updates.

**Comment by adamyonk** [comment]
For anyone trying to alias that, it doesn't seem to work with more recent git:
```
adam:~/Code/dotfiles ☂ master
❯ git config --global alias.create "create -p"

adam:~/Code/dotfiles ☂ master
❯ git create test
fatal: recursive alias: create
```

**Comment by mislav** [comment]
@adamyonk Thank you for reporting; this is true. Git doesn't allow aliases that shadow any of the built-in commands. This applies to hub-specific commands as well, such as `create`.
