### ISSUE TITLE
BSOD on compile

### ISSUE THREAD

**Issue by isketerol64** [github/hub#1195]
Hi:

  I downloaded "Go" from the download link and then proceeded to try to build 'hub' using the provided instructions.  I managed to BSOD on running the build script twice.

  I will try this in a virtual machine in my home office so that I don't have issues with my company machine.

  The build environment is a Windows 7 64-bit machine.  McAffee anti-virus is runnin as wel as Checkpoint Security.

Kevin

**Comment by mislav** [comment]
Thanks for reporting and sorry for the trouble! I can't imagine what went wrong.

To clarify: which exact Go version did you download, and what did you run to build hub?

**Comment by mislav** [comment]
Hi @isketerol64, do you maybe have more information for me regarding this issue?

**Comment by isketerol64** [comment]
Hi

  Sorry I haven't had the time to reproduce that issue. I've moved to
Windows 10 on a new laptop.

  Sorry.

IskiE

**Comment by mislav** [comment]
@isketerol64 Thanks for reporting back. No need to apologize! I'm going to close this issue since it doesn't seem like something I can fix. Maybe it was a problem with Go compiler on Windows 7. If the problem comes back and crashes your Windows 10, please reopen this issue so we can look into it again. Thank you!

**Comment by mislav** [comment]
Also, you don't have to compile hub yourself— prebuilt binaries for Windows are [available from the Releases section](https://github.com/github/hub/releases). Try the latest of the 2.3.0-prereleases to get the latest features!
