### ISSUE TITLE
[Feature Request] Hub pull request load description from an already created text file

### ISSUE THREAD

**Issue by onlineth** [github/hub#1202]
Hi, I was wondering if there was a way (or if this could be added as a feature) where when a pull request is executed, an option could be to load a description from a text file already created without having a text-editor pull up. Any ideas?

Example

     hub pull-request -m "Title for PR" -b master --load-description pr_description.txt

**Comment by mislav** [comment]
Yes you can do this!

```
hub pull-request -F pr_description.txt -b master
```

The first line of `pr_description.txt` file should be the PR title (mandatory), then a blank line, and everything that follows will be PR body (optional).

**Comment by onlineth** [comment]
@mislav Great, thanks:)
