### ISSUE TITLE
cannot pull-request [powershell]

### ISSUE THREAD

**Issue by Zougi** [github/hub#1205]
command `git pull-request` can't get pass the authentication prompts on Powershell 5 (PSVersion 5.0.10240.16384)

I run command `git pull-request`, I fill my username when asked, then It asks for my password, I set it, and hit the key enter, nothing. The prompt do not go to the next line and just hangs. After a while I exit this state with `ctrl+c` (sigint)
I then retry the workflow. This time, I can't write my username

```powershell
# $env:GITHUB_HOST="github.enterprise.corp"
# git pull-request
github.enterprise.corp username: MyUserName
github.enterprise.corp password for MyUserName (never stored): # ^C
# git pull-request
github.enterprise.corp username: # ^C
```

**Comment by mislav** [comment]
Thanks for the report and sorry for the trouble! Have you tried the latest version of hub (2.2.3)? See your version with `hub --version`.

**Comment by Zougi** [comment]
Hi I'm on 2.2.0-230-g9fc560
I will try v2.2.3 on a fresh computer

**Comment by Zougi** [comment]
can't reproduce with v2.2.3. I'm closing this. thanks

**Comment by masaeedu** [comment]
@mislav Seeing this issue with Powershell 5.1.14393.206 on Windows 10, hub version 2.2.5, git version 2.10.0.windows.1.

**Comment by mislav** [comment]
@masaeedu Thanks for the detailed info! Can you try the latest release of hub, v2.2.9?

**Comment by Zougi** [comment]
use another editor than vim.
To do that, in `~/.gitconfig` under `[core]` section add an entry `editor = <path to editor>`.
I personnaly use Sublime Text with option -w and [Git](https://packagecontrol.io/packages/Git) package
an overview of my gitconfig file:

```
[core]
	editor = "'C:/Program Files/Sublime Text 3/subl.exe' -w"
```
