### ISSUE TITLE
Hub creating issues instead of pull-requests

### ISSUE THREAD

**Issue by cdrage** [github/hub#1210]
For some odd reason, each time I do a pull-request with hub now, it's creating an issue instead.

If I click on the pull-link that's generated after submitting it, it goes to a /issues/ url and then 404's.

**Comment by nicolaiskogheim** [comment]
> it's creating an issue instead

> it goes to a /issues/ url and then 404's.

Sure it's creating an issue?


Do you find the PR if you replace `issues` with `pulls`?

**Comment by cdrage** [comment]
I'm closing this since it was because of GitHub giong down at that time xD
