### ISSUE TITLE
Printing status URLs on `ci-status` command

### ISSUE THREAD

**Issue by kirs** [github/hub#1211]
Right now `hub ci-status` only prints the actual status (`success/failure/pending`) without links to CI.

@mislav if you think it would be useful to print status URLs as well, I'll be happy to send a PR.

**Comment by mislav** [comment]
That's a good idea! But it was already done in https://github.com/github/hub/pull/999 and will be available in the next release. Try building hub from master and checking out `hub ci-status -v`!

**Comment by kirs** [comment]
Thanks for letting me know!
