### ISSUE TITLE
Enhancement: Use oauth token in push

### ISSUE THREAD

**Issue by cdosborn** [github/hub#1213]
I'm a little weak on the specifics (if this is possible). Since `hub` records your OAuth token, it could prevent entering credentials on for example `hub push $REPO $BRANCH`.

**Comment by cdosborn** [comment]
Step 3 looks relevant in this guide:
https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by mislav** [comment]
Good idea, but the reason why this isn't feasible is outlined in https://github.com/github/hub/issues/1150#issuecomment-214737629. Sorry!
