### ISSUE TITLE
hub-pull-request unable to guess <head> and <base> correctly

### ISSUE THREAD

**Issue by tiennou** [github/hub#1220]
It seems sometimes `hub` gets really confused when choosing what to PR.

My repository remotes are setup by developer name, so `$dev1`, `$dev2`, `$me`, and `$project`. We usually push things we want to get reviewed to `$project` directly, and WIP stuff under our own remotes (`$me`).

So I'm on branch `neat-feature` (which I actually forgot to push), I do `git pull-request`, I'm proposed to PR from `$dev1:neat-feature` to `$dev1:master`, which I would expect to actually fail by telling me that the branch isn't pushed yet (or something, maybe that's not so easy).

I `git push -u $project-name`, then redo `git pull-request`, same proposed base & head.

The only way to get it right is to say `git pull-request -b $project:master -h $me:neat-feature`.

**Comment by tiennou** [comment]
Also, about `-u`, it seems it always selects the first remote from the output of `git remote` as the default remote, without looking at what the config is for`branch.$branch.remote, `branch.$branch.pushRemote`, or `remote.pushDefault`.

**Comment by mislav** [comment]
This is caused by the same issue as described in https://github.com/github/hub/issues/877. Please follow other issue for updates. Thanks!
