### ISSUE TITLE
hub pull-request with Github Enterprise

### ISSUE THREAD

**Issue by dufferzafar** [github/hub#1221]
Does `hub` not support Github Enterprise?

I get the following error while trying to create a pull request:
`Aborted: the origin remote doesn't point to a GitHub repository.`

```
$ git remote -vv
origin	git@git.my.company.com:username/repo.git (fetch)
origin	git@git.my.company.com:username/repo.git (push)
```

**Comment by petey** [comment]
You need to add a hub configuration to your .gitconfig per the docs.

`git config --global --add git.my.company.com`

**Comment by dufferzafar** [comment]
Thanks, it worked! `git config --global --add hub.host git.my.company.com`
