### ISSUE TITLE
use /dev/tty instead of /dev/stdout when prompting for information

### ISSUE THREAD

**Issue by nhooyr** [github/hub#1225]
See neovim/neovim#5211

**Comment by mislav** [comment]
Thanks, that is good advice! I'll have to look into how to implement this change in Go. To clear things up, which prompts from hub are you talking about?

**Comment by nhooyr** [comment]
At the very start, when it asks for the username/password for the token. https://github.com/github/hub/blob/af72087bc7c4f94cf5876b22820fa9e4cf772700/github/config.go#L137-L138

**Comment by nhooyr** [comment]
It's a very simple change. Open `/dev/tty` when prompting, but if you cannot, exit with an error. Do not try and get a prompt from just `stdout`.

**Comment by nhooyr** [comment]
I'll just go ahead and create the PR.

**Comment by mislav** [comment]
[Here's where we use stdin](https://github.com/github/hub/blob/af72087bc7c4f94cf5876b22820fa9e4cf772700/github/config.go#L166) in this context. Go doesn't expose anything like `os.Tty`, but I guess we could just manually open `/dev/tty`. On Windows, I presume this won't be available, so we will continue using `/dev/stdin` there.

There is also interesting mentions of "tty" here https://golang.org/pkg/syscall/#SysProcAttr

Should we also write out the prompt to `/dev/tty` as well, or just read from it?

**Comment by nhooyr** [comment]
Yes, we have to write it out to `/dev/tty` as well.

**Comment by nhooyr** [comment]
Sorry never mind, I've got to do something else. Will not be able to work on the PR.

**Comment by mislav** [comment]
No problem. Thanks for suggesting this in the first place.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
