### ISSUE TITLE
HTTP 201 when running `hub pull-request --browse`

### ISSUE THREAD

**Issue by ilovezfs** [github/hub#1226]
Seems to happen every time (the pull request itself does go through):
```
Error creating pull request: Created (HTTP 201)
Error: Failure while executing: hub pull-request --browse -m clipper\ 0.3
```
This is a regression since hub 2.2.3.

**Comment by ilovezfs** [comment]
Seeing it without the `--browse` as well
```
Error creating pull request: Created (HTTP 201)
Error: Failure while executing: hub pull-request -m cpanminus\ 1.9003
```

**Comment by ilovezfs** [comment]
The regression appears to be caused by 56fce4bc6bf6ebaf1673045e80b1938922a3b436.

**Comment by arbourd** [comment]
I'm getting `422` since updating this morning when calling `pull-request` with or without `--browse`.

```
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

**Comment by ilovezfs** [comment]
```
	if err = checkStatus(200, "creating pull request", res, err); err != nil {
```
should be
```
	if err = checkStatus(201, "creating pull request", res, err); err != nil {
```
here: https://github.com/github/hub/blob/master/github/client.go#L108

**Comment by arbourd** [comment]
hey @ilovezfs, good find! I didn't know you were working on a PR and made as well. To fix the tests I emulated `release.feature`'s testing structure. Never worked with cucumber before.

**Comment by ilovezfs** [comment]
@arbourd you look like you're farther along than I am, so I'm happy to close in favor of yours. Thanks for fixing this.
