### ISSUE TITLE
Fetching non github remotes fails

### ISSUE THREAD

**Issue by dustinleblanc** [github/hub#1227]
Hey there!

I use hub aliased to git like the docs instruct, I just updated hub via brew this morning and doing a fetch with tags fails on non-github remotes (this fetch is to a Pantheon git repository):

```sh
$ git fetch --tags
Aborted: the origin remote doesn't point to a GitHub repository.
$ git --version
git version 2.9.2
hub version 2.2.4
```

**Comment by mislav** [comment]
Thanks for reporting! This is indeed a nasty bug. Fixed in v2.2.5.
