### ISSUE TITLE
hub checkout argument to define the way the remote is added

### ISSUE THREAD

**Issue by kitsunet** [github/hub#1236]
Currently doing `hub checkout https://github.com/user/repo/pulls/123` would add the remote 
`user` with the url `git://github.com/user/repo.git` which for me always fails when trying to push back to that. It would be neat to have an argument to `hub checkout` that allows you to define if the remote is setup as it is now or with
`git@github.com:user/repo.git`
or
`https://github.com/user/repo.git`

That way a user can make it work as needed.

Eg.

`hub checkout --remote [git|ssh|https] https://github.com/user/repo/pulls/123`

**Comment by mislav** [comment]
We're reimplementing `checkout` in https://github.com/github/hub/pull/1235 currently. These are good suggestions! @pcorpet let's explore how we can make pushing back to the PR branch easier if you have write access to the repo where the PR comes from!

**Comment by kitsunet** [comment]
Cool! Thanks for the quick feedback, looking forward to it.
