### ISSUE TITLE
Persist GPG Verified Signed Commit On "Squash and Merge" In PRs

### ISSUE THREAD

**Issue by Sayvai** [github/hub#1241]
On GitHub Enterprise (GHE) v2.7.x, when I make a Pull Request (PR) with a single commit on a feature branch that is signed with a verified GPG signature, and eventually merge this in via the click action on the button labelled _Confirm squash and merge_, the commit is no longer signed with a verified GPG signature. So my question is, **_could GPG signed verified commit(s) status(es) from feature branches please be persisted into the branch it is merging into in the PR squash and merge process?_** At least especially if there is _only one new commit, which is GPG signed_ from a feature branch.

**Comment by mislav** [comment]
Hello! You seem to have a question about the functionality of GitHub itself. This project is called "hub" and is *related* to GitHub, but only as a GitHub API client on the command-line. The "Confirm squash and merge" functionality is not related to this project at all.

Could you write to support@github.com instead? Thanks!

**Comment by Sayvai** [comment]
Got this reply back from GitHub Support on 14th September 2016:

> _We are looking into ways to sign merge and squash-merge commits, as well as commits made through the web interface. The challenge is that we do not want you to upload your private GPG key to GitHub Enterprise, which is required for signing. Your private GPG key should remain secured on your workstation._

> _Most likely, the solution will be for these types of commits to be signed by a GitHub GPG key specific to your GitHub Enterprise server. I do not, however, know when or if this feature will be available in GitHub Enterprise._

I also noticed this recent announcement from GitHub themselves on 26th September 2016 surrounding a new merge option available in Pull Requests (PR) on GitHub.com only; [Rebase and merge](https://github.com/blog/2243-rebase-and-merge-pull-requests), to which i believe **may** resolve this problem. If it does, then i hope the feature will also be released to GitHub Enterprise (GHE) soon!

**Comment by HBelusca** [comment]
Problem still happens even using "Rebase & Merge".

**Comment by nburroni** [comment]
Are there any updates on this matter? I am having the same issue

**Comment by Sayvai** [comment]
There's been no updates on this matter 😞 

I have re-sent an email to support@github.com to chase up on this. I'll post response here, if / when i get a response back. 

For the rest **feel free to do the same**, and even link to this issue, so that more awareness is gained, and eventually potentially prioritised.

**Comment by Sayvai** [comment]
Just got a response from a GitHub representative:

> Keeping the verified status when you squash and merge commits from a Pull Request has been available on GitHub.com for a while now. This feature hasn't yet made it to GitHub Enterprise due to some underlying architecture that differs between the two platforms.
> 
> We had an issue discussing this feature which I'm going to reopen and see if we can get it across the line and into GitHub Enterprise. I can't promise if or when this may make it to GitHub Enterprise however.

So, the feature has been reopened, and hopefully they'll manage to apply the feature to their _GitHub Enterprise_ product like they've done with _GitHub.com_ 🤞 

I'll chase up again in like 2 / 3 months time.

**Comment by lisito** [comment]
Hello! Are there news from this issue?

**Comment by Sayvai** [comment]
@lisito Thanks for the reminder ^^

So i've just chased up, and got the following response from GitHub Support: 

>We are still tracking this as an open issue, and it is being discussed by the relevant teams. However, I am unable to provide any timelines for when we may see this feature be added to GitHub Enterprise. Please feel free to reach out for an update at any point. 

So no real progress yet it seems. Patience for now it will have to be.

**Comment by 5chdn** [comment]
> Keeping the verified status when you squash and merge commits from a Pull Request has been available on GitHub.com for a while now.

However, this only works if the person who hits the squash button is the same as the user who signed the commits in the pull request. Why is that?

If I have a PR, that has full signed commits by developer A, and developer B merges this, it will generate an unsigned merge commit. That's very unfortunate.

**Comment by jakob223** [comment]
@Sayvai any update on this?

**Comment by medikoo** [comment]
> Keeping the verified status when you squash and merge commits from a Pull Request has been available on GitHub.com for a while now.

Unfortunately it's not the case for "Rebase and merge"

**Comment by Sayvai** [comment]
So i've chased up on the ability with persisting the GPG signed commits via the _**Rebase and merge**_ action, and this is the latest response.

> I'll pass your request onto the team to consider. Commit signing wasn't implemented for Rebase merge I'm afraid.
> 
> I can't promise if or when it will be implemented, but your suggestion is definitely in the right hands!

Lets hope this is given some serious consideration, and eventually implemented 🤞

**Comment by gt-novelt** [comment]
@Sayvai any news on this ?

Unfortunately the _rebase and merge_ still don't preserve signature.

**Comment by bluexbyte** [comment]
we are also unable to just regular merge verified gpg commits on github enterprise server 2018.9 when it is enforced via branch protection rules... possibly related but unsure. have openned ticket with github support and will update here. 

Also curious as to if there is a different open issue for tracking this work publically?

------------------------------------------
GITHUB DROP ICE

**Comment by abbec** [comment]
We also run in to this, quite annoying so we have reverted back to merging manually and not using the merge button in the UI. It seems like "rebase and merge" in combination with the requirement that the branch has to be up to date should remove the requirement to even do a rebase and just do a `merge --ff-only`, thus preserving the signing?

**Comment by Sayvai** [comment]
So i've chased up again with _Github Support_, and got some bad news.. 😞 

> Unfortunately I do not have the best news for you.
> 
> I've spoken with our engineering team responsible for the commit signing feature. It's not currently expected that rebased commits from a rebase and merge will be signed.

**Comment by errordeveloper** [comment]
In understand that in principle it is the right thing to do, since GitHub is shouldn't be signing any commits on user's behalf. Albeit, I think they should at least allow rebase+merge with signatures dropped from resulting commits.

**Comment by medikoo** [comment]
> In understand that in principle it is the right thing to do, since GitHub is shouldn't be signing any commits on user's behalf. Albeit, I think they should at least allow rebase+merge with signatures dropped from resulting commits.

If they can sign squash commits I do not understand why rebase commit cannot be signed

**Comment by errordeveloper** [comment]
> If they can sign squash commits I do not understand why rebase commit cannot be signed

@medikoo good point! I've checked it, and they actually use their own key to sign squash commits. I think this is definitely a huge issue with what's meant to be one of the flagship security features. It looks like they just stop short of signing each commit on rebase, which is odd because if I rebase someone's commits locally, those get signed with my key automatically, so it's not like a non-trivial kind of thing to implement.

**Comment by renannprado** [comment]
Gitlab implementation makes totally sense.

Just offer a button which merges the branch as is - it's not true that every time you want to merge a branch you want to squash all your commits.

![image](https://user-images.githubusercontent.com/2359543/97859662-38337000-1d01-11eb-8ad6-f07b5071eb0a.png)

**Comment by adizaimi** [comment]
> Gitlab implementation makes totally sense.
> 
> Just offer a button which merges the branch as is - it's not true that every time you want to merge a branch you want to squash all your commits.
> 
> ![image](https://user-images.githubusercontent.com/2359543/97859662-38337000-1d01-11eb-8ad6-f07b5071eb0a.png)

Merging the branch as is would at least allow me to rebase and squash as much as I want, sign, then push to my branch--the resulting merge should be able to keep my signature.

**Comment by pdesjardins90** [comment]
The year is 2077, github copilot replaced all developers on earth, but still can't persist its signed commit after a rebase merge

**Comment by arminghm** [comment]
Signing the commit in `squash and merge` with a different key would make sense, because there would be a lot of commits signed with different signature belongs to different developers and they all are about to squash in one commit , (in my opinion it would be better that the commit could be signed with the signature of the person who merged the PR).
But definitely all the signatures must be persist in `rebase and merge`.

**Comment by EwoutH** [comment]
Agree this is needed! This issue really should be reopened.

**Comment by pdesjardins90** [comment]
@mislav could you reopen this?

**Comment by yurii-sh** [comment]
issue still appears

**Comment by sdavids** [comment]
GitHub Support:

> Signing commits using the Rebase and Merge options isn't currently possible. This is a feature limitation I'm afraid but our Product Team do have this on our Feature Request list.

> Please rest assured there is an open issue for this, and it remains open until such time as it is resolved. Reopening issues in unrelated repositories isn't going to expedite this I'm afraid.

> I've added your request to our internal tracking issue.

Instead of commenting/voting on this issue you should create a GitHub support ticket to get their internal issue upvoted.

If you have not already done so:

https://support.github.com/contact/bug-report

**Comment by Stephen2** [comment]
Lodged a support ticket :shrug: you never know your luck
