### ISSUE TITLE
Pull request message template is not read from .github when hub pull-request is executed

### ISSUE THREAD

**Issue by gastaldi** [github/hub#1242]
I have a repository containing a `.github/PULL_REQUEST_TEMPLATE.md` file, however that is not used when the pull-request is created by executing `hub pull-request` after pushing it to a remote branch.

**Comment by gastaldi** [comment]
The PR template was created following this guideline: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by iserko** [comment]
@gastaldi are you using the HEAD version of hub? It hasn't been released yet, so you have to use `master` ... `brew install --HEAD hub` if you use homebrew

**Comment by gastaldi** [comment]
@iserko was it updated recently? Last time I tried the master branch was when I opened the issue

**Comment by iserko** [comment]
@gastaldi https://github.com/github/hub/commit/d987f40f8d7572c6bdf555fe3e83a7d6ba281b3d

**Comment by gastaldi** [comment]
My file is all upper cased. It seems this commit tests for lowercased files only?

**Comment by iserko** [comment]
@gastaldi my project has `PULL_REQUEST_TEMPLATE.md` and works fine

**Comment by gastaldi** [comment]
Weird, I tried with the master again and it didn't seem to work. This is the repository I am using: https://github.com/wildfly-swarm/wildfly-swarm

**Comment by gastaldi** [comment]
I am running on Fedora 24 btw

**Comment by iserko** [comment]
@gastaldi oh `hub` must not be reading `.github` ... I have mine in the root of the repo

**Comment by iserko** [comment]
@gastaldi you should reword your issue then :)

**Comment by gastaldi** [comment]
Glad we found the issue :)

**Comment by gastaldi** [comment]
I can confirm that it works when in the root but not when inside `.github`

**Comment by mislav** [comment]
I can't reproduce in either tests or manually. Here's what I have:

```
$ cat .github/PULL_REQUEST_TEMPLATE.md
Hello from template!

Another line.
```

and it works as a template. Granted, I am on OS X and you are on Fedora, so this might be some bizarre filesystem issue?

**Comment by gastaldi** [comment]
@iserko what OS are you using? Have you been able to reproduce it?

**Comment by iserko** [comment]
@gastaldi I don't have a repo with the template in `.github`

**Comment by gastaldi** [comment]
Try this one: https://github.com/wildfly-swarm/wildfly-swarm

Em 9 de set de 2016 07:16, "Igor Serko" <notifications@github.com> escreveu:

**Comment by gastaldi** [comment]
I just tested and it seems that it's working now. Not sure what was caused initially to create this issue.
Closing for now.

**Comment by gastaldi** [comment]
Reopening. I managed to reproduce it if I run `hub pull-request` in a subdirectory of a github-enabled repository.

eg. 
````bash
hub clone wildfly-swarm/wildfly-swarm
cd wildfly-swarm
# Go to subdirectory
cd tools
# Change something
hub pull-request 
# The pull request message from ../.github is not used
cd ..
hub pull-request 
# Now it is used
````

**Comment by mislav** [comment]
Gotcha; thanks for figuring that out. Fix under way.
