### ISSUE TITLE
Hub is using stale PR message

### ISSUE THREAD

**Issue by Saketme** [github/hub#1246]
Hello, I've been seeing a strange issue with hub where it's stuck with an old PR message. No matter what branch I'm trying to send a pull request from, it's always showing that same old PR message. 

**Update:** Uninstalling hub and re-installing didn't fix the issue. And it has also started giving me this error:

Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

**Comment by oddg** [comment]
I am also having this issue.

**Comment by mislav** [comment]
Hi @Saketme, I'm sorry that you're having trouble. Can you try removing the file `.git/PULLREQ_EDITMSG` from your repo and trying again? Does the stale pull request message persist even after you've sucessfully opened a pull request? What OS is this on and which hub version are you using?

**Comment by Saketme** [comment]
So lately this has stopped happening. I'm no longer seeing stale messages and I don't know how to reproduce it. I'll try removing `PULLREQ_EDITMSG` the next it happens. 

Also, the `-a` flag seems to have stopped working for assigning someone to a PR. I know it's not a stable feature, but I just wanted to confirm if I'm doing something wrong?

**Comment by mislav** [comment]
I'm already looking into problems with `-a`. I will make a new prerelease once that's fixed. But if you have no other issues, please close this one. If you do have other issues, please enable debug mode with `HUB_VERBOSE=1 hub ...` and send any info that stands out to you. Thanks!

**Comment by Saketme** [comment]
Sure
