### ISSUE TITLE
cherry-pick fails for commit URL from PR

### ISSUE THREAD

**Issue by blueyed** [github/hub#1249]
Using the URL from a single commit of a PR (e.g. https://github.com/neomake/neomake/pull/560/commits/04073c7987e37195d142b671a768d62d59bd003e) does not work:

```sh
% hub cherry-pick https://github.com/neomake/neomake/pull/560/commits/04073c7987e37195d142b671a768d62d59bd003e
fatal: bad revision 'https://github.com/neomake/neomake/pull/560/commits/04073c7987e37195d142b671a768d62d59bd003e'

% hub --version
git version 2.9.3
hub version 2.3.0-pre3
```

The man page also seems to mention the old method (of adding a remote) still (in case that has changed):
> EXAMPLES
       $ hub cherry-pick https://github.com/jingweno/gh/commit/a319d88#comments
       > git remote add -f --no-tags jingweno git://github.com/jingweno/gh.git
       > git cherry-pick a319d88

       $ hub cherry-pick jingweno@a319d88

Using `hub cherry-pick sebastianbeyer@04073c7987e37195d142b671a768d62d59bd003e` worked.

**Comment by mislav** [comment]
Thanks for the report! I think cherry-pick still tries to add a git remote, although we should fix that the same as we fixed `hub checkout` command.
