### ISSUE TITLE
git 2.10 and `log.showSignature` pollutes `git pull-request`

### ISSUE THREAD

**Issue by jacobbednarz** [github/hub#1254]
Hello!

This morning I updated to git 2.10 and set `log.showSignature` to true
so that I can see signed commit details in `git log` calls. However I
have now noticed that `git pull-request` is being prepopulated with the
signing information at the top too whereas previously, this was just the
commit title and body. 

### Steps to reproduce

- Update to git 2.10
- Run `git config --global log.showSignature true`
- Make changes on a project (`add` & `commit`)
- Run `git pull-request`

### Environment details

- OSX 10.11.6
- git version 2.10.0
- hub version 2.2.3

Thanks!

**Comment by mislav** [comment]
Thanks for reporting! I guess we will need to explicitly disable showSignature in the `git log` call where we fetch commit info for pull-request details.

**Comment by jacobbednarz** [comment]
awesome work! :cake:
