### ISSUE TITLE
can't broswe git issues on private repos 

### ISSUE THREAD

**Issue by ac427** [github/hub#1255]
"hub browse -- issues" opens elinks with error " {"error":"Not Found"} " only on private repos. ? 
I replaced project/repo with foo/bar in below.  I looked at old closed similar issues, but no luck 

```
$ git remote -v
origin	git@github.com:foo/bar.git (fetch)
origin	git@github.com:foo/bar.git (push)

$hub version
git version 2.10.0
hub version 2.2.5
```

I also tried 

```
hub version 2.3.0-pre3
```

**Comment by mislav** [comment]
Thanks for reporting. This is very strange. Where is `{"error":"Not Found"}` displayed; on the command line or in the browser? Did `owner/repo` get renamed on GitHub by any chance? Are you logged in to GitHub and do you have permissions to see this repo? Are issues enabled for `owner/repo`?

**Comment by mislav** [comment]
Also, what is displayed when you `hub browse -u -- issues`?

**Comment by ac427** [comment]
The error was in browser (elinks). I think I should read more documentation.  I was more interested in reading issues in the terminal not browser. 

anyways, i know what the issue is. since i don't have gui browser. hub tried to open in elinks and since I am not logged in to github.com it gave the github default 404 error ( which is error:not found ) for the private repo . 

You can close the issue. Thanks for your response. 

I think hub  doesn't solve what I am looking. It will be nice if I can read issue history with issue number. 
```
$hub issue --help

Usage: hub issue [-a <ASSIGNEE>] [-c <CREATOR>] [-@ <USER] [-s <STATE>] [-f <FORMAT>] [-M <MILESTONE>] [-l <LABELS>] [-t <TIME>]
       hub issue create [-o] [-m <MESSAGE>|-F <FILE>] [-a <USERS>] [-M <MILESTONE>] [-l <LABELS>]
$
```

**Comment by mislav** [comment]
Ah, thanks for the clarification. Unfortunately, `hub issue` command right now can only list issues, but not conversation within a particular issue. That functionality might get added later down the road, but for now, you're going to have to manually use the GitHub API directly.
