### ISSUE TITLE
pull-request: Unprocessable Entity (HTTP 422) Invalid value for "head"

### ISSUE THREAD

**Issue by Mattias-** [github/hub#1258]
Even though everything seems to have been set up correctly with the branches and remotes it seem like the selection of head branch is confused when creating a PR.
I think this is because my username (Mattias-) ends in a hyphen but I have not verified that.
```
$ git branch -vv
* add-py3kwarn 640caee [Mattias-/add-py3kwarn] python: Add py3kwarn maker
  master       ad726be [origin/master] Merge pull request #580 from blueyed/redraw-in-LogMessage

$ hub pull-request
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

$ hub pull-request -h Mattias-:add-py3kwarn
https://github.com/neomake/neomake/pull/595

$ hub --version
git version 2.10.0
hub version 2.2.5
```

**Comment by Mattias-** [comment]
Dupe of https://github.com/github/hub/issues/1256

**Comment by naoisegolden** [comment]
Just for anyone getting here like me: check you didn't forget to push the branch to origin before doing the pull request...

**Comment by mislav** [comment]
@naoisegolden That's a common mistake that even I do from time to time, and the error message returned definitely isn't friendly. I'm working on improving that. Also, the `pull-request --push` flag  is in the works! #1294

**Comment by batisteo** [comment]
> Also, the `pull-request --push` flag is in the works!

Is it?

**Comment by mislav** [comment]
@batisteo Indeed. It was part of a prerelease that went out in February https://github.com/github/hub/releases/tag/v2.3.0-pre9

**Comment by davecarlson** [comment]
Should the messaging not be better for this ? It's not obvious at all that it's failing as the branch is not pushed up
