### ISSUE TITLE
improve docs on am

### ISSUE THREAD

**Issue by tcurdt** [github/hub#1260]
https://hub.github.com/ tells one to use

```
# directly apply all commits from a pull request to the current branch
$ git am -3 https://github.com/github/hub/pull/134
```

but misses out on explaining the `-3`.
I would suggest to use the long form `--3way` in the docs

**Comment by mislav** [comment]
I don't think that's a huge improvement. It's fine if people don't fully understand what `-3` is. It's optional, but yields better results in case of conflicts. It's pretty easy for people to view `git help am` and look up what `-3` is.
