### ISSUE TITLE
Initial 2FA auth prompt misaligned

### ISSUE THREAD

**Issue by mgedmin** [github/hub#1262]
Here's what my terminal looks like when I use `hub fork` for the 1st time:
```
mg@platonas! ~/.vim/bundle/python_open_module [git:master=] $ hub fork
github.com username: mgedmin
github.com password for mgedmin (never stored): 
                                                two-factor authentication code: 758417
Updating mgedmin
From https://github.com/vim-scripts/python_open_module
 * [new branch]      master     -> mgedmin/master
new remote: mgedmin
```

The two-factor authentication code prompt should not be indented that way.

**Comment by mislav** [comment]
Thanks for reporting! I haven't seen that one yet.

1. Have you typed a password or pasted it?
2. Does the password contain characters other than alphanumeric?
3. Which shell?
4. Which terminal emulator?

**Comment by mislav** [comment]
Also, of course: which hub version?

**Comment by mgedmin** [comment]
1. I typed the password
2. The password is alphanumeric
3. bash
4. GNOME Terminal

```
$ hub --version
git version 2.7.4
hub version 2.3.0-pre4
```

(installed today with `go get github.com/github/hub`)

**Comment by mislav** [comment]
Thanks for the extra info!
