### ISSUE TITLE
hub with osxkeychainhelper fails

### ISSUE THREAD

**Issue by scarstens** [github/hub#1278]
https://help.github.com/articles/caching-your-github-password-in-git/
The above works for git and fails for hub

Also not seeing anywhere you could set hub to use the ssh key clones instead of https token authentication

**Comment by mislav** [comment]
Hi, hub and git authenticate in very different ways. Git can use ssh key authentication, while hub can only use OAuth token for the GitHub API over HTTPS. It's explained more here: https://github.com/github/hub/issues/1217#issuecomment-246816520

RIght now the workaround is simple: give hub your GitHub username & password just one time and let it cache the OAuth token so it doesn't have to prompt you again.
