### ISSUE TITLE
Retrieve available issue labels

### ISSUE THREAD

**Issue by vermiculus** [github/hub#1280]
It would be super slick if `hub` could retrieve the current list of labels available for use when creating a repository -- vermiculus/magithub#6 (and other hub-wrapping scripts) could really benefit from this.

**Comment by mislav** [comment]
Good idea! Perhaps an `hub issues labels` subcommand would be in order.

**Comment by vermiculus** [comment]
@mislav I'd like to get my hands dirty with some Go – I've never worked with it before. Are there any license restrictions for contributions to hub?

**Comment by mislav** [comment]
@vermiculus Yes, all contributors have to accept [GitHub's CLA](https://cla.github.com/). When you submit your first pull request, the automated status checks will fail with a link to accept the CLA. It's done by reviewing the agreement and pressing a button. It's easy. When you do that, the status check will start passing.

**Comment by vermiculus** [comment]
In case someone has time before I do (and so I don't forget), it would help greatly if labels were paired with some sort of ID and this ID was usable with `issue --format` as `%L`. Consider the following label setup:

1. `A`
2. `B`
3. `A, B`

Any given issue that lists `%L=A, B` would be ambiguous between 1+2 or just 3.

**Comment by eljobe** [comment]
I propose that we make it a separate command (as opposed to a subcommand of the `issue` command).  My arguments:

* Labels are naturally the children of the repository, not the issue. See: https://developer.github.com/v3/issues/labels/
* You can also use these labels on pull requests.
* As a user, I think of operations like creating a label or modifying a label as separate from operations I perform on issues.

I'm starting work on a branch that implements listing labels for a repository right now. But, I probably won't finish it in the 45 minutes before my next meeting.

**Comment by mislav** [comment]
This was done in #1667.
