### ISSUE TITLE
Support for no_proxy environment variable

### ISSUE THREAD

**Issue by woneill** [github/hub#1281]
It looks like https://github.com/github/hub/blob/master/github/http.go#L171-L193 is reimplementing the proxy logic from net/http/transport.go but it's missing the sections that support setting no_proxy.

**Comment by mislav** [comment]
Good catch! Wanna take a stab at implementing it?

**Comment by woneill** [comment]
Sure! I'll give it a shot since it's been causing a ton of pain for me having to mix proxy settings between git and hub. I'm a newbie at go so might take me a few weeks.

**Comment by mislav** [comment]
@woneill Just out of curiousty: how are you using `http_proxy` and `no_proxy` in your dev environment and at which point does it break in hub?

**Comment by woneill** [comment]
We have a site-wide proxy for all internet access but internal websites can/should be accessed directly. And we have github enterprise setup internally. So when I have HTTP_PROXY=http://proxy and NO_PROXY=.mydomain.com set, 'stock' git access works but anything handled by 'hub' (usually pull request generation) fails until I undefine HTTP_PROXY.

**Comment by woneill** [comment]
BTW, I have the no_proxy code from golang ported over, just trying to figure out a good way to write a cucumber test around it.

**Comment by jmaxxz** [comment]
:+1: on this issue, can not use hub with my local github enterprise without this feature.

**Comment by thale013** [comment]
+1 facing the same issue - `no_proxy` and `NO_PROXY` env vars are being ignored

**Comment by h0nIg** [comment]
+1

**Comment by elovelan** [comment]
[Here's the commit](https://github.com/github/hub/commit/9a7d6fadf80893967e01a1c4525a2e3db1e1b95b) explaining why this was re-implemented. Maybe worth exploring if this is still a concern, and if so, updating [the comment](https://github.com/github/hub/blob/master/github/http.go#L189) so it's a bit more clear why this was done.

**Comment by elovelan** [comment]
@woneill, I'm thinking I might pick this up. Do you have some existing code I can start from?

**Comment by elovelan** [comment]
@mislav, given the support for `github.localhost` introduced in 67ba00ae6653ef37a78f240b158418e727750f2d is the separate proxy implementation introduced in 9a7d6fadf80893967e01a1c4525a2e3db1e1b95b for proxying to `localhost` or a loopback IP support still relevant?

**Comment by mislav** [comment]
@elovelan The support for `github.localhost` was added mostly for Hubbers like me and is not very useful for anyone who doesn't work at GitHub. It has nothing to do with proxy implementation.

If the current support for proxying and related environment variables lacking, PRs welcome!

**Comment by elovelan** [comment]
@mislav, in your commit where you implemented this custom proxy logic, you said the following which seems to reference the exact use case that `github.localhost` is used for:

> Go otherwise respects `HTTP_PROXY` environment variables by default, but special-cases requests made to "localhost" or `127.0.0.1` by disabling proxy for them, which makes me a sad panda since I want to debug the requests hub makes to our local test server.

I'm happy to open a PR with a clarifying comment if there are other use cases you're thinking of for avoiding the proxy logic from Go's stdlib.

**Comment by mislav** [comment]
> you said the following which seems to reference the exact use case for `github.localhost` that you mentioned above

Ah yes, thanks for digging that up. I do a lot of local testing/hacking, some using `localhost` and some using `github.localhost` (they are treated differently on my machine, though).

I haven't touched the proxy-handling code in a while, and I'm unsure if there are any blind spots that we still have, but as I said, if you find anything that's broken/unclear, I'd appreciate PRs. Bonus points if we can remove my proxy hacks in favor of Go stdlib (note that hub still keeps compatibility with Go 1.8)

**Comment by mislav** [comment]
Actually, I'd prefer to _keep_ the implementation of reading proxy-related environment variables in hub just so that we can ensure that hub's proxy handling stays the same across Go versions 1.8–1.11 (and future ones). It would be great if `no_proxy` was respected!

**Comment by spackard** [comment]
+1 on this. hub should respect no_proxy.

**Comment by L4R5** [comment]
+1
