### ISSUE TITLE
Update in Chocolatey request

### ISSUE THREAD

**Issue by Kristinita** [github/hub#1288]
Now via Chocolatey I can download [only 2.2.1 version](https://chocolatey.org/packages/github-hub).

I [wrote issue](https://github.com/twsouthwick/github-hub-chocolatey/issues/1) to maintainer hub on Chocolatey twsouthwick, but he not answers to me [and you](https://github.com/github/hub/issues/794#issuecomment-246472692). Please, assign new maintainer, because hub not upgrade in Chocolatey many times.

Thanks.

**Comment by dougludlow** [comment]
To summarize what I saw in the linked issues, it appears that both the [github-hub](https://chocolatey.org/packages/github-hub) (v2.2.1) and [hub](https://chocolatey.org/packages/hub) (v2.2.5) chocolately packages have both gone stale. Attempts have been made to contact the maintainers (@twsouthwick, @dtgm), but without avail. 

Chocolatey apparently has a [triage process](https://chocolatey.org/docs/package-triage-process#package-is-outdated) for what to do when a package is outdated. They even have a process when a software vendor [wishes to take over the package maintenance](https://chocolatey.org/docs/package-triage-process#i-want-to-take-overhelp-with-package-maintenance-for-my-software).

I'm more than happy to take steps to transfer the maintenance of one of the packages to myself, unless anyone else would like it. The other option would be for the maintainers for github/hub to claim the package and take it over themselves.

**Comment by twsouthwick** [comment]
Hi - just saw this. I've responded to the issue here (https://github.com/twsouthwick/github-hub-chocolatey/issues/1). As stated there, I'm no longer using the tool so I haven't been tracking chocolatey updates. I'd be happy to transfer ownership (Chocolatey as well as the GitHub project for the chocolatey wrapper) to whoever would like to take it

**Comment by Kristinita** [comment]
Now we can download [latest 2.2.9 version](https://chocolatey.org/packages/hub) in Chocolatey. @dougludlow , @mislav , if you all wants maintainers of package together @dtgm, it would be nice) .

Thanks.

**Comment by mislav** [comment]
@twsouthwick Could you transfer the ownership of the package to me and outline the process of upgrading the package version for me so I can hopefully automate it?

**Comment by twsouthwick** [comment]
Sure! It'll have to be tomorrow as I'm out of town right now. I look into the process and let you know.

**Comment by mislav** [comment]
Thanks @twsouthwick!

**Comment by twsouthwick** [comment]
@mislav Are you wanting both the chocolatey package and the GitHub repo for wrapper transferred? I can do both or either. In order to do this, I'll need:

- For the GitHub repo, which org should I transfer it to?
- For chocolatey, I need a username to add as a manager

**Comment by mislav** [comment]
> For the GitHub repo, which org should I transfer it to?

You can add me as a collab on your repo for now so I can see what kind of a wrapper it is. Maybe I can pull that code into this repo so we can shut down the wrapper repo?

> For chocolatey, I need a username to add as a manager

My chocolatey username is "mislav". Thanks!

**Comment by twsouthwick** [comment]
Done. I've added you as a collaborator to the GitHub project and added you as a maintainer for the chocolatey package. Feel free to remove me from the chocolatey maintainer list and pull in any code you need from the GitHub project.

**Comment by mislav** [comment]
@twsouthwick Thanks a ton. I'll look into how all that is set up. Now, if I could only gain access to the "hub" Chocolatey package too, in addition to "github-hub"… But I understand that's beyond your jurisdiction.
