### ISSUE TITLE
Browse is not opening a browser

### ISSUE THREAD

**Issue by shime** [github/hub#1289]
Nothing happens when I run
```
$ hub browse
```
even though I have a remote called *origin*.

```
$ git remote -v
origin  git@github.com:twobucks/bar.git (fetch)
origin  git@github.com:twobucks/bar.git (push)
```

This works though
```
$ open $(hub browse -u)
```

I'm on OSX
```
$ hub --version
git version 2.10.0
hub version 2.2.8
```

**Comment by mislav** [comment]
Thanks for reporting. What is shown when you use `HUB_VERBOSE=1 hub browse`?

**Comment by shime** [comment]
```
$ HUB_VERBOSE=1 hub browse
$ git config alias.browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/master
```

**Comment by mislav** [comment]
That's bizzare. What's your `git var GIT_EDITOR`?

**Comment by shime** [comment]
```
$ git var GIT_EDITOR
nvim
```

**Comment by mislav** [comment]
The HUB_VERBOSE output that you shared shows that hub doesn't even *try* to run nvim. This is the first time I see such a bug. I'm out of ideas.

**Comment by shime** [comment]
I've never used go before and I have no idea why would it try to run `nvim` for `browse`, but it seems like `verboseLog(cmd)` is missing from `[Run()](https://github.com/github/hub/blob/4777bd363058213605ebb292b35ef1a6edb3663c/cmd/cmd.go#L54-L60)`. 

After putting it there I get this

```
$ HUB_VERBOSE=1 ~/bin/hub browse
$ git config alias.browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/master
$ google-chrome-stable https://github.com/github/hu
```

**Comment by mislav** [comment]
> it seems like `verboseLog(cmd)` is missing from `Run()`

Hmm that's true, but `Run()` invokes either `Spawn()` or `Exec()`, which both have `verboseLog()` in them.

What happens if you run `google-chrome-stable https://github.com/github/hub` directly?

**Comment by shime** [comment]
Yeah, running that command is what causing the problem. 

```
$ google-chrome-stable https://github.com/github/hub
-bash: google-chrome-stable: command not found
```

No idea what's setting `$BROWSER` to `google-chrome-stable`.

**Comment by shime** [comment]
Found where it's being set. Thanks for helping me debug it!

**Comment by mislav** [comment]
Oh, I'm dumb. I fixed the problem of failed command not being shown on stderr in f507de0596d2f0d7cc028a4f3185ef139d492e26, but that's only in master (and 2.3.0-pre4 release) but not in 2.2-stable. I should probably packport it.

**Comment by shime** [comment]
Good idea. I was debugging this on master, though. Looks like [this is why](https://github.com/github/hub/blob/4777bd363058213605ebb292b35ef1a6edb3663c/cmd/cmd.go#L78) it didn't log anything in verbose mode.

**Comment by mislav** [comment]
It seems there are still 2 bugs existing on master:

1. The command fails, but nothing is displayed on stderr;
2. The command is not logged in HUB_VERBOSE mode.

I'll try to fix this soon. Thanks for debugging with me!
