### ISSUE TITLE
Unclear how to install man pages from source

### ISSUE THREAD

**Issue by nex3** [github/hub#1291]
The README doesn't include any information about how to install hub's man files when installing from source, nor does it mention that that's necessary to make `git help` properly display help for hub's commands.

**Comment by mislav** [comment]
Yes, that's something I haven't worked out yet. Precompiled releases for tagged versions include an installer script that install the man pages under the installation prefix such as `/usr/local`, but there is no such thing when installing from source.

Perhaps there should be a `make install` command?

**Comment by nex3** [comment]
I certainly looked for `make install` when I was trying to figure this out.
