### ISSUE TITLE
[2.3.0-pre6] (found cause) nil pointer dereference on `hub checkout`

### ISSUE THREAD

**Issue by mcornella** [github/hub#1293]
I was running `git checkout https://github.com/robbyrussell/oh-my-zsh/pull/3007`, where PR 3007
is from an unavailable fork. I found the issue on lines 98 and 99 of `commands/checkout.go`:

https://github.com/github/hub/blob/4777bd3/commands/checkout.go#L98-L99

where you're using `pullRequest.Head.Ref` as well as `remote.Name` which are probably nil in
this instance (in [2.2.8 there's a check for that](https://github.com/github/hub/blob/v2.2.8/commands/checkout.go#L83-L87)).

The thing is, rather than checking if they are null and throwing an error if that's the case,
we can just use the following command from [this GitHub guide](https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally):

```
$ git fetch origin pull/ID/head:BRANCHNAME
```

Where ID is the PR number and branchname can be anything. If the source fork is not available,
branchname could be `pr-ID` or just fetch it onto FETCH_HEAD and checkout that afterwards.

Below is the crash report from hub:

------

Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x8d8460, 0xc820010150)
	/home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:443 +0x4e9
github.com/github/hub/commands.transformCheckoutArgs(0xc8200c02c0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/checkout.go:94 +0x11e3
github.com/github/hub/commands.checkout(0xc07e20, 0xc8200c02c0)
	/tmp/go/src/github.com/github/hub/commands/checkout.go:34 +0x30
github.com/github/hub/commands.(*Command).Call(0xc07e20, 0xc8200c02c0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/commands.go:45 +0x188
github.com/github/hub/commands.(*Runner).Call(0xc820011700, 0xc07e20, 0xc8200c02c0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:109 +0x5e
github.com/github/hub/commands.(*Runner).Execute(0xc820011700, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:97 +0x221
main.main()
	/home/travis/gopath/src/github.com/github/hub/main.go:14 +0x50

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.9.3
hub version 2.3.0-pre6
```

**Comment by mislav** [comment]
Thanks for reporting! This is indeed something that I have overlooked when reimplementing the commmand for the 2.3.x series.

**Comment by mcornella** [comment]
Awesome! Ping me if you need help testing. I'll read the contribution guide and try to solve it myself once I have a moment; I've been looking for an excuse to try the Go language :smile:

**Comment by mislav** [comment]
@mcornella Thanks for the interest, but no need right now! I've already made a fix. Will push soon.

**Comment by mcornella** [comment]
Wow you're fast! Thanks! Closing then, you've got this under control :wink:
