### ISSUE TITLE
Compare branches across forks

### ISSUE THREAD

**Issue by masaeedu** [github/hub#1295]
It would be great to have a way to compare branches among forks. Github already provides the necessary REST API to do this: see for example https://github.com/octocat/linguist/compare/master...octo-org:new-docs-file-branch.

It's possible this is already supported but I couldn't discover it from the CLI help. I started with the following setup:

```
git clone foo/bar
cd bar
git fetch someone
```

and tried: 

```
git compare origin/master someone/foo
```

which 404s. I also tried:

```
git checkout foo
git compare master
```

Which is very close, but unfortunately ends up comparing the `master` branch of both repositories instead of the `master` branch of origin with the `foo` branch of the fork.

**Comment by mislav** [comment]
Have you tried `hub compare master...someone:foo`?

**Comment by masaeedu** [comment]
@mislav Just tried that, looks like it works!
