### ISSUE TITLE
Support ability to browser list of pull requests or a single pull request

### ISSUE THREAD

**Issue by leandro** [github/hub#1301]
I couldn't find any existing Issue related to this request, so I created one.

**Comment by mislav** [comment]
Hi, is this about opening these pages in a web browser?

Browsing the list of pull requests is possibe with `hub browse -- pulls`, while individual pull request can be navigated to using `hub browse -- pull/42` if you have its number. If you don't have its number, we're discussing the option of browsing to the PR of the current branch here: https://github.com/github/hub/issues/1107

Mind if I close your issue as duplicate?

**Comment by leandro** [comment]
Hi. Yes it is.

I did realize that before opening this issue. I just wanted to keep things inside my terminal, instead of jumping in the browser to see them. I thought that was something open to discussion, but apparently it's something that has been discussed and decided already (in favor of opening PRs in the browser). So, if that's the case, please go ahead and close it.

**Comment by mislav** [comment]
Listing PRs in the terminal is also planned soon 😉 Closing as duplicate. Thanks for writing in!

**Comment by leandro** [comment]
That's awesome. Thank you.
