### ISSUE TITLE
List pull requests again

### ISSUE THREAD

**Issue by vermiculus** [github/hub#1303]
#1232 mentions the need for a command to list out pull requests (taken away by 8563e678d2f3cfc8d1bcc4ed3f38f7226c5d5012, probably for semantic reasons), but I thought I'd reiterate the need here.

Related to vermiculus/magithub#44.

**Comment by akshatgoel** [comment]
@mislav I am looking to work on this issue. Here is my current understanding of the issue:
Currently hub only has commands to create a PR but not list them. We should be able to list PRs as we do with issues right now (as added by the commit).

Proposal:
I am thinking of moving current pull-request behavior to sub-command create to maintain parity with issue as well as to make listing (which is stateless operation compared to create) as default.

What do you think?

**Comment by mislav** [comment]
@akshatgoel That's a good plan. How do you envision this command and its subcommands to be called?

**Comment by timja-kainos** [comment]
Alternatively `hub ls pull-request`?

**Comment by vermiculus** [comment]
Even if there could be an option to skip [this section of code](https://github.com/github/hub/blob/master/commands/issue.go#L243), that would be sufficient:

```
for _, issue := range issues {
	if issue.PullRequest != nil {
		continue
	}
	ui.Printf(formatIssue(issue, flagIssueFormat, colorize))
}
```

**Comment by vermiculus** [comment]
@mislav If such a flag was added this week, do you have an estimate on when the change would make it into a release?

In other words, any idea when `2.3.0-pre9` will be tagged?

**Comment by mislav** [comment]
I could tag another prerelease after that. Thank you!
