### ISSUE TITLE
hub fork fails with "Not a git directory"

### ISSUE THREAD

**Issue by rdotdk** [github/hub#1307]
Hi,

I'm able to clone github repo, commit to my github repo using hub without any issues. 
But when i try ``` hub fork github/hub ``` it fails with ``` fatal: Not a git repository ```. 

``` hub version ``` shows
``` shell
git version 2.1.4
hub version 2.3.0-pre8
```
I'm using ``` 32 bit Debian GNU/Linux 8.5 (jessie) ``` if that helps.

I've also tried by setting the verbose flag,
``` shell
~/devel$ HUB_VERBOSE=1 hub fork github/hub
$ git config alias.fork
$ git rev-parse -q --git-dir
fatal: Not a git repository
```

Do i need to configure anything else for forking a repo? what are the steps to fork a repo? I would be happy if you could point me towards any documentation (sorry, i couldn't find any). So my knowledge is only restricted with whatever help the hub command showed me.

Thanks,
Hari

**Comment by rdotdk** [comment]
btw, thanks for making this tool :)

**Comment by rdotdk** [comment]
looks like we need to clone the git repo before we can fork the repo. Found the command usage at https://hub.github.com. Closing the issue.

**Comment by mislav** [comment]
@rdotdk I totally understand how you got confused about the `hub fork` command. Plenty of people expected that they can fork a repo directly on GitHub and clone that instead. I'm thinking of supporting an argument given to `fork` to specify the repo name.

**Comment by rdotdk** [comment]
@mislav that'll be very useful. Also I think the commands and examples should be easily accessible. It took me a while to find the example at hub.github.com

**Comment by mislav** [comment]
The documentation given by `hub help fork` mentions that you're working the
"current project". I'm gonna try to make the documentation clearer and more
accessible.

**Comment by rdotdk** [comment]
I only did hub with no arguments to check out what arguments are available and jumped on trying hub fork. I didn't look at hub help fork. I have become lazy by all those  github projects that have extensive examples either in the Readme or in the wiki.

**Comment by rdotdk** [comment]
I'm willing to help out with documentation :)
