### ISSUE TITLE
Hub broken on El Capitan?

### ISSUE THREAD

**Issue by nik-john** [github/hub#1311]
I'm trying to install Hub on El Capitan but see the following error:

```
brew install hub
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
go: This formula either does not compile or function as expected on OS X
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

_I do understand that the log recommends PRs over Issues, but I don't currently possess the skillsets for that._

Is there a work-around for this?

**Comment by mislav** [comment]
I'm not sure what's the issue with our Homebrew formula on El Capitan. That message definitely doesn't come from hub. Have you upgraded Homebrew to latest?

The alternative is to download one of our precompiled binaries available on the Releases section of this repo. The 2.2.x series is the stablest, while 2.3.0-prerelease series has cool new features worth trying out.

**Comment by nik-john** [comment]
@mislav Turns out there was a bug in Homebrew:


> ### Update Bug
> 
> If Homebrew was updated on Aug 10-11th 2016 and brew update always says Already up-to-date. you need to run:
> ```
> cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
> ```

So every time I updated brew, it was saying `Already up to date`.

Once I followed this process, and _actually_ updated brew, hub installed fine. So this seems to be an issue that exists on Homebrew 0.9.9

Thanks for your help. Closing this.
