### ISSUE TITLE
Check if config location is writeable before authenticating

### ISSUE THREAD

**Issue by goostleek** [github/hub#1314]
### 1. Clone this repo

```
$ git clone https://github.com/github/hub
Cloning into 'hub'...
remote: Counting objects: 13524, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 13524 (delta 20), reused 0 (delta 0), pack-reused 13489
Receiving objects: 100% (13524/13524), 3.57 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (8530/8530), done.
```
### 2. Make a fork

```
$ cd hub
$ hub fork
github.com username: <user.name>
github.com password for <user.name> (never stored):
Error forking repository: Unprocessable Entity (HTTP 422)
Duplicate value for "description"
```

**Comment by mislav** [comment]
Thanks for reporting! I think this is an error with authentication, not forking operation itself. You can specify `HUB_VERBOSE=1 hub fork` to opt into verbose mode so you can see the HTTP traffic being sent/received. I think this failed on creating an OAuth token. Are you using the latest version of hub?

**Comment by goostleek** [comment]
```
$ hub --version
git version 2.10.1.windows.1
hub version 2.2.9
```

and verbosed `hub fork` command

```
$ HUB_VERBOSE=1 hub fork
$ git config alias.fork
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
github.com username: [REDACTED]
github.com password for [REDACTED] (never stored):
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 2","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 3","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 4","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 5","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 6","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 7","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 8","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for makl@makl 9","note_url":"http://hub.github.com/"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
Error forking repository: Unprocessable Entity (HTTP 422)
Duplicate value for "description"
```

**Comment by mislav** [comment]
Is it possible that you have many existing tokens named "hub for makl@makl ..."? Please check https://github.com/settings/tokens and delete them unless any of these hub tokens are being used on other machines where you also use hub. Then try authentication again. Sorry for the hassle!

**Comment by goostleek** [comment]
Yes, that was the case. After deleting the tokens the problem has gone. Thank you :)

**Comment by mislav** [comment]
Thanks for the update! Hub could still have handled this better, though. Any idea how you accummulated so many hub tokens for this machine?

**Comment by goostleek** [comment]
The command `hub fork` cannot be successfully completed and I retried it many times. That may be the reason I have accumulated so many tokens IMHO.
```
$ hub fork
github.com username: [REDACTED]
github.com password for [REDACTED] (never stored):
mkdir Z:: The system cannot find the path specified.
```
The problem is with the missing `Z:` drive. I know this is not a _hub_ issue but my local environment misconfiguration but maybe you will be able to help me. Let me give you some insight into the case first. The `Z:` drive was my home drive during hub installation. The drive no longer exists and I can understand  hub complains about it. I wanted to fix it by reinstalling the _hub_ after removing its config file I found at `~/.config/hub` but the problem persists. I guess there are some other configuration files I should have also removed but I don't know which ones. Any suggestions how can I resolve the issue to force _hub_ to pick my new home drive?

**Comment by mislav** [comment]
@goostleek You're absolutely right that the missing `Z:` drive could have led to you accummulating too many generated tokens. Hub generated a token for you each time but was never able to save it to disk.

This is [how hub discovers your home directory](https://github.com/github/hub/blob/95be4466968d3711bef7cd1cf0538cfe8e111f6c/vendor/github.com/mitchellh/go-homedir/homedir.go#L121-L125) on Windows. Maybe you could take a look at those environment variables for start?

**Comment by goostleek** [comment]
Thanks, that was very helpful. All I had to do to fix this was updating `HOMEDRIVE` and `HOMEPATH` environment variables. However, it wasn't easy as this variables are managed by a domain controller and was restored to the old values each time I was logged to my company's network. I had to apply [the permanent solution](http://superuser.com/a/483902/513312).

**Comment by mislav** [comment]
I'm glad you solved it. I'm going to keep this issue open until a make a change to hub that first checks if it can write into the config file before authenticating. That way, the error about missing `Z:` would be reported to you before hub even asked you for username/password and exchanged it for an OAuth token. This will avoid the case where these unsaved tokens can accummulate in your acccount.

**Comment by akshatgoel** [comment]
Hi. I am new to the project and it looks like a beginner bug. Will it be OK I pick this up?

I started with the investigation and found that only github/config:PromptForHost calls the save for config file. That looks like a good place to put the test to see if file is writable. We can start with loading the current config file and saving it again. If it fails in that, we can be sure that we will not be able to write new information on the same.

Does that make sense? Can I pick this up?

**Comment by mislav** [comment]
@akshatgoel You're absolutely welcome to try and fix this.

You are correct that `Save()` is basically only called from `PromptForHost()`, so that's a good place to start a fix. I think the following code could be used for writeability check:

```go
CheckWriteable(filename string) error {
	err := os.MkdirAll(filepath.Dir(filename), 0771)
	if err != nil {
		return err
	}

	w, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
	if err != nil {
		return err
	}
	w.Close()
	return nil
}
```

This will create an empty file and the directory structure leading up to it if it's successful, but that should be fine since we're going to write to this file with the new config anyway.

Keep in mind the following.

* The check for config file writeability should _only_ happen if we will try to save the config file with updated information during this execution. It should never happen if no config has changed. Hub should be usable with a read-only config file *until* the point something tries to change the config.
* The check for writeability should happen _before_ any prompts to the user, such as for username and password.

**Comment by akshatgoel** [comment]
I thought about overwriting the file too but I am wary about the cases when user don't want to overwrite the config file. Consider the case with existing code : 
1. I run "hub fork".
2. Realise this is not the command, I want. I get username prompt. I quit the program. No harm done.

However, if we overwrite the file, I won't be able to go back to my original config file.

I am not sure if this is a valid case but this was the reason I didn't want to overwrite the current config file.

**Comment by mislav** [comment]
> I am not sure if this is a valid case but this was the reason I didn't want to overwrite the current config file.

You're absolutely right. That's why I crafted the `OpenFile()` call in my example with flags that avoid overwriting the file if it exists.

**Comment by akshatgoel** [comment]
@mislav Is there a coverage tracker for the project? I don't see one in build targets and documentation is a bit lacking.

Based on what I found in config_service_test, I have added happy case test for the new code. I am not sure on the coverage guidelines.

**Comment by mislav** [comment]
@akshatgoel There is some code coverage attempt of mine in https://github.com/github/hub/pull/1267 but you shouldn't worry about it now. Mostly lean on the tests in `features/authentication.feature` and add a new scenario for when the file or the directory for the configuration is not writeable.

**Comment by akshatgoel** [comment]
@mislav `hub create` is used in authentication.feature to check authentication. When authentication fails, none of the values are written to the file "../home/.config/hub" and tests check that the file is not present. However, for the case in hand, we need to be sure that we will be able to write to config file before we ask for any credentials. Thus, we create an empty file before asking for credentials, which fails the tests.

I am updating the tests to check that the file is empty but I am not sure if this is the right approach. Thoughts?
