### ISSUE TITLE
Allow setting default reviewers for a pull request. 

### ISSUE THREAD

**Issue by snowe2010** [github/hub#1319]
Currently I use github much more for contributing to repositories that have very small teams where the same people review every pull request. It would be nice to be able to set a list of default maintainers using a config file or even a command line parameter so that I have no need to actually go to the web interface to add them.

**Comment by mislav** [comment]
How do you add reviewers using the web interface and what would you expect hub to do instead?

**Comment by snowe2010** [comment]
I go to the PR in question, and on the right side I choose assignees, and select the reviewers I want. I would like hub to have a config file or parameter, where you can specify the username or email of the people to add as "Assignees"/reviewers. Hub would then create the PR with those people assigned.

**Comment by mislav** [comment]
@snowe2010 Ah I see; you would add them as assignees.

In the 2.3.0-prerelease versions (grab the latest one from Releases section), `hub pull-request` supports the `-a` option to add assignees as a comma-separated list of usernames.

Hub won't offer any functionality to add default assignees, since it can't know who those people are, and I don't think there will be a configuration option for this either. However, you can wrap your own script that determines who the assignees should be and calls `hub pull-request -a foo,bar`. I hope that solves the problem for you!

**Comment by snowe2010** [comment]
Fantastic, thank you very much. So there won't be any sort of config file for hub in the future? Like a per repo config?

**Comment by mislav** [comment]
Yes I'm planning to add per-repo config in the future. I suppose it will be possible to add default flags for any command, such as `pull-request`. With that mechanism you will be able to configure default assignees. But, once you configure default flags for `pull-request`, you will not be able to create a pull request without those flags, i.e. create a pull request *without* assigning those people.

**Comment by snowe2010** [comment]
Ah yes, I don't think that would be a problem for my team, as we are small and every member is assigned to every pull request mostly, but I see how it could be a problem for others.

**Comment by qinglucich** [comment]
It is a useful feature for each user. It should be configurable per user per repo.

**Comment by MoxyMayhem** [comment]
@mislav Just wondering you have added the pre-repo config?

**Comment by mislav** [comment]
@MoxyMayhem Not yet. Perhaps you could use a wrapper script for now that would invoke `hub pull-request -r user1,user2`?

**Comment by erin-docs** [comment]
+1

**Comment by AshokKaitake** [comment]
@mislav Is automatic default reviewers assigned to pull request functionality feature added?
