### ISSUE TITLE
Add another keyword for closing issues in commit comments

### ISSUE THREAD

**Issue by eyalroz** [github/hub#1321]
It would be nice if GitHub supported "resolves issue #xyz" and "resolve issue #xyz" in addition to close/closes/closed/fixes/fixed, which are the [currently supported keywords](https://github.com/blog/1386-closing-issues-via-commit-messages) for that.

**Comment by mislav** [comment]
Hi, I'm not sure what you wanted so send a feature request for, but it sounds like you wanted to propose a feature for GitHub.com website. This project is about a `hub` command-line tool that ties in with git and does not represent the GitHub.com website nor its functionality.

For GitHub.com itself, you could always write to support@github.com, but I think that the current close/closes/closed/fixes/fixed keywords will remain the same so they can be used unchanged for both issues and pull requests.
