### ISSUE TITLE
Add ability to delete a release

### ISSUE THREAD

**Issue by wesbland** [github/hub#1326]
I have a workflow where I automatically create a new nightly release every night in order to easily distribute tarballs/rpms to internal testers. I don't really want to keep all the old releases around on the release page (I do keep the tags, but they don't clutter things up as much).

While I can create releases all day with the `hub release` command, I can't delete old ones. Can we get this added?

**Comment by GabLeRoux** [comment]
@mislav Can we have a review on this? It would be quite handy to be able to delete releases from command line. :+1:

**Comment by mislav** [comment]
@wesbland Sorry for no reply. The changeset looks good. Please feel welcome to submit a PR for this!

**Comment by wesbland** [comment]
There is a PR already. 😄 It was linked above, but maybe it got confusing because of the links below.

https://github.com/github/hub/issues/1327
