### ISSUE TITLE
"Aborted: the origin remote doesn't point to a GitHub repository." but it does

### ISSUE THREAD

**Issue by thockin** [github/hub#1328]
```
thockin@freakshow2 kubernetes /$ hub pull-request
Aborted: the origin remote doesn't point to a GitHub repository.

thockin@freakshow2 kubernetes /$ git remote -v | grep origin
origin	git@github.com:thockin/kubernetes.git (fetch)
origin	git@github.com:thockin/kubernetes.git (push)
```

**Comment by mislav** [comment]
Is there an "upstream" or "github" remote with a non-GitHub URL?

**Comment by thockin** [comment]
```
$ get remote -v
origin git@github.com:thockin/kubernetes.git (fetch)
origin git@github.com:thockin/kubernetes.git (push)
origin-https https://github.com/thockin/kubernetes.git (fetch)
origin-https https://github.com/thockin/kubernetes.git (push)
upstream https://github.com/kubernetes/kubernetes.git (fetch)
upstream dont_push_to_upstream_you_dolt (push)
```

The error says it is looking for `origin`.  That is correct. If it is
looking for something else, it should maybe say so.  We all do this because
we have accidentally pushed to master and almost lost days of work.

**Comment by mislav** [comment]
Yes, the error message is wrong. It was actually looking at "upstream" since that takes precedence over "origin". It assumes that you want to submit a pull request to `kubernetes/kubernetes`. You can change the base of the pull request to another fork via the `-b` parameter.

I think handling of invalid push URLs for remotes got handled at some point. Please try the latest 2.2.x version.

**Comment by thockin** [comment]
This was from `go get` ...

I will try -b

**Comment by mislav** [comment]
[This code in hub](https://github.com/github/hub/blob/490887a02add44d4451dd8fdbc40147461c7c51c/github/remote.go#L86-L98) suggests that parsing pushurl should guard against it not being a URL. However, this might be broken. If you are running a version from master, then something is obviously broken in this approach. Please give us more details via `hub version`.

**Comment by thockin** [comment]
Hmm, it looks like I ran afoul of `go get` not updating if something is
already present.  Forcing an update does seem better.  I don't have a PR to
push just now, but I will try when I do.

**Comment by mislav** [comment]
You can do `hub --noop pull-request -h whatever`. It will exercise the whole logic of the `pull-request` command, including editing the message, but will never actually POST anything due to the `--noop` flag.

**Comment by thockin** [comment]
Looks like it works.  Sorry for the noise!

**Comment by mislav** [comment]
No worries! Thanks for checking.

**Comment by destatez** [comment]
I'm trying to dig through this chain, but I am missing the bottom line. I am just trying to use the hub Issue features but get the same error message. The output from a git remote -v is:
origin	https://git.door43.org/unfoldingWord/en_ugl (fetch)
origin	https://git.door43.org/unfoldingWord/en_ugl (push)

There is no **upstream** defined and I even removed my **myfork** from the remotes to make sure that that wasn't the issue. Last time I checked the web address was pointing to a github repository. I'm doing all kinds of pulls, adds, commits, and pushes against it.

**Comment by mislav** [comment]
@destatez Have you tried `hub config --global --add hub.host git.door43.org`? That's a prerequisite one-time operation for new Enterprise hosts

**Comment by destatez** [comment]
Mislav

When I do the hub config ....  and then a hub issues I get the message:
error Provider not suppoerted: door43

From talking with our support folk, this is not a pure github repository,
but one they have modified for their other processing. I think that I am
out of luck with using hub for this.

Thanks for the input, though.

Dave
