### ISSUE TITLE
Disable 'git browse' asking for credentials

### ISSUE THREAD

**Issue by spvkgn** [github/hub#1334]
Is there a way to disable asking for username and password?
````
$ git browse
github.com username: 
github.com password for  (never stored):

**Comment by akshatgoel** [comment]
There was another issue regarding the question but I can't find the same.

As per that issue, rationale behind asking for credentials in `browse` is that most of hub commands require Github authentication. If opening a URL is the only command you wish to use, a small wrapper script may serve the purpose better.

**Comment by mislav** [comment]
@spvkgn No. The way hub does most of its operations is that it uses the GitHub API to fetch information about repositories. If you want to use hub command, you'll have to give it access to GitHub API by providing your authentication details.

Alternatively, if you don't want to authenticate one time with your username/password, you can generate a Personal Access Token yourself and configure GITHUB_TOKEN environment variable with that token.
