### ISSUE TITLE
Support for template inside .github directory

### ISSUE THREAD

**Issue by hugobessaa** [github/hub#1335]
As in the [Issue and Pull Request templates][templates-blogpost] blogpost:

[templates-blogpost]: https://github.com/blog/2111-issue-and-pull-request-templates

> If you're worried about the added clutter in the root directory of your project, we also added support for a .github/ folder.

Opening a pull request with `hub` in a project that has `PULL_REQUEST_TEMPLATE.md` file inside `.github` directory on the root of the project does not pre-fill the pull request message.

Templates work as expected in the web interface for opening Pull Requests.

**Comment by mislav** [comment]
@hugobessaa Check your `hub version`. Is it at least 2.3.x?

**Comment by hugobessaa** [comment]
I'm sorry for that. Escaped to me that this feature is only available in 2.3.x. Also read some code and could not find `.github` lookup.

I will test with 2.3.x

**Comment by lanej** [comment]
worked for me after installing HEAD
