### ISSUE TITLE
The pull-request help doesn't show what -o does 

### ISSUE THREAD

**Issue by ericbrandwein** [github/hub#1336]
Entering in the command line `hub pull-request --help` shows that there is a `-o` option, but it doesn't say what it does. What does it do?

**Comment by mislav** [comment]
`hub help pull-request` will tell you more.

**Comment by ericbrandwein** [comment]
No it doesn't, it tells me the same as `hub pull-request --help`. I saw that you changed it already in the `pull_request.go` file though, so nevermind 😬

**Comment by mislav** [comment]
Ah, I'm sorry. You're right. I forgot that the behavior was like that in the 2.2.x version. I've been using the 2.3.x prerelease version for a long time already, where documentation is vastly improved.

The `-o` flag opens the new PR in the web browser. In the 2.3.x prerelease version, there are also flags `-c` to put the URL to the clipboard instead, and `-a`, `-M`, `-l` to defined assignees, milestones, and labels respectively.
