### ISSUE TITLE
pull-request repeatedly hitting 404

### ISSUE THREAD

**Issue by RichardLitt** [github/hub#1346]
At some point in the last few weeks, `git pull-request` broke, and I am not sure why. 

```sh
> git pull-request 
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/RichardLitt/university-of-remainia exists?
```

Yes, I am sure that it exists. 

```
origin	git@github.com:RichardLitt/university-of-remainia.git (fetch)
origin	git@github.com:RichardLitt/university-of-remainia.git (push)
```

I've tried reinstalling hub using homebrew, but the issue remains. Any ideas?

**Comment by mislav** [comment]
I'm sorry that you're having trouble. Using `HUB_VERBOSE=1 hub pull-request` you can get a verbose HTTP log of all that's happening. Maybe that will shed some light on the subject.

Is it possible that you revoked the Personal Access Token that hub has stored in `~/.config/hub`?

Also, which hub version?

**Comment by mislav** [comment]
Can you upgrade hub and try again?

**Comment by RichardLitt** [comment]
Uh...

```
🐕  hub --version
git version 2.3.0
hub version 2.2.0
21:34 ~/src/university-of-remainia (feat/added-sidebar) 🐕  brew upgrade hub
Error: hub 2.2.9 already installed
```

This is weird. Why isn't hub using the right version?

**Comment by mislav** [comment]
@RichardLitt You probably have two hubs.

**Comment by RichardLitt** [comment]
Ok. You were right. Removed both versions. 

```sh
06:38 ~ 🐕  hub
-bash: hub: command not found
06:38 ~ 🐕  brew install hub
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
agda                          ffmpeg ✔                      mpv

==> Downloading https://homebrew.bintray.com/bottles/hub-2.2.9.el_capitan.bottle.tar.gz
Already downloaded: /Users/richard/Library/Caches/Homebrew/hub-2.2.9.el_capitan.bottle.tar.gz
==> Pouring hub-2.2.9.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/hub/2.2.9: 10 files, 9M
06:39 ~ 🐕  cd src/university-of-remainia/
06:39 ~/src/university-of-remainia (feat/added-sidebar) 🐕  git pull-request 
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/RichardLitt/university-of-remainia exists?
06:39 ~/src/university-of-remainia (feat/added-sidebar) 🐕  hub --version
git version 2.3.0
hub version 2.2.9
```

Still getting the issue. :/

**Comment by mislav** [comment]
That's really weird. A token you generated with the "repo" scope should do the trick.

Where did you put the generated token? And, if you pasted it into `~/.config/hub` file manually, can you also ensure that you don't have a GITHUB_TOKEN set by the environment?

**Comment by RichardLitt** [comment]
That was it; I had another token for a different program using GITHUB_TOKEN. I now have it working. Thank you!

**Comment by mislav** [comment]
Glad to hear!

**Comment by RichardLitt** [comment]
@mislav Thank you. I opened a PR to document this somewhere; may not be the best place, but it seemed fitting.
