### ISSUE TITLE
Allow edits from maintainers

### ISSUE THREAD

**Issue by galeksandrp** [github/hub#1349]
Checkbox not enabled when creating PR from hub.

**Comment by trevor-vaughan** [comment]
This is really causing a hiccup in my CLI workflow. Does anyone know where in the API this can be enabled? I took a look but couldn't find anything.

**Comment by mislav** [comment]
Sorry folks, this feature is not yet exposed in GitHub API. I'm interested in having the option (on by default?) once it's possible.

**Comment by travi** [comment]
my vote would be off by default since i'd rather others send PRs to my branch than push directly to them. that workflow preserves the safety needed to force push to your own branch

**Comment by vitorgalvao** [comment]
> my vote would be off by default since i'd rather others send PRs to my branch than push directly to them. that workflow preserves the safety needed to force push to your own branch

Github has it on by default. Since this is a CLI tool geared in large part specifically for github, it should do whatever the website does by default.

**Comment by travi** [comment]
That's true, but it's also targeted at power users that are more likely to force push. Seems like at least worth being configurable in the `hub` section of `~/.gitconfig`

**Comment by trevor-vaughan** [comment]
I would vote for on by default and configurable.

**Comment by ilovezfs** [comment]
The default seems to have recently changed from off to on. It would be nice to be able to configure this because that was pretty surprising to see the behavior change overnight with no way to control except through the GUI after the fact.

**Comment by mislav** [comment]
I agree that this should be configurable. I also agree that the default should be whatever is the default in the web UI, which is "on". I'll check with my colleagues whether there is a plan to expose this through the API.

**Comment by galeksandrp** [comment]
Currently "Allow edits from maintainers" is set by GitHub when pushing with `hub`.

**Comment by xenohunter** [comment]
I'm too for a setting which would make the default state of that checkbox configurable.

**Comment by galeksandrp** [comment]
Present in API https://developer.github.com/v3/pulls/#update-a-pull-request

**Comment by mislav** [comment]
https://github.com/github/hub/pull/2168
