### ISSUE TITLE
Allow for an alternate delimiter when checking out a PR

### ISSUE THREAD

**Issue by trevor-vaughan** [github/hub#1350]
Hub has been great to work with, but my username has a hyphen in it which makes differentiating between where my username ends and the PR ID starts quite difficult.

If I could do something like `GIT_PR_DELIMITER='___'` before I ran `hub checkout PR_URL`, it would be VERY useful.

**Comment by mislav** [comment]
Hi, thanks for writing in! Could you elaborate in more detail about what hub generates and why is it difficult for you to extract the PR ID? Thanks!

**Comment by trevor-vaughan** [comment]
Sure.

If I run the command `hub checkout https://github.com/trevor-vaughan/<reponame>/pull/<pull_id>` I get the following branch name `trevor-vaughan-<pull_id>`.

Now, if I want to use this name to figure out what the username is so that I can push back to it, I don't really have a good way of doing so.

It's possible that I'm using `hub` incorrectly, but I'm mirroring functionality that I had when using `git-review` with Gerrit.

The aliases that I'm using are as follows:

<pre>
rd = "!f() { if [ -z $1 ]; then echo 'Must pass pull number' && exit 1; fi; origin_url=`git config --get remote.origin.url`; if [ -z \"${origin_url}\" ]; then url=`git config --get remote.upstream.url`; else url=$origin_url; fi; reponame=`basename $url`; hub checkout https://github.com/simp/${reponame}/pull/$1; }; f"

rf = "!f() { curbr=`git rev-parse --abbrev-ref HEAD`; user=`echo \"$curbr\" | cut -f1 -d'-'`; branch=`echo \"$curbr\" | cut -f2- -d'-'`; if [ -z $user ]; then echo \"Invalid user in $curbr\" && exit 1; fi; if [ -z $branch ]; then echo \"Invalid branch in $curbr\" && exit 1; fi; git remote rm $user 2>/dev/null || true; hub remote add -p $user; git push $user HEAD:$branch; git checkout $branch && git branch -D $curbr; }; f;"
</pre>

Usage:
1. `git rd <pr_number>` -> Downloads the PR
1. Hack on Stuff
1. `git rf` -> Pushes the PR and cleans up the local branch

If there's a better way of doing this, I'm certainly open to it!

**Comment by mislav** [comment]
Thanks for the explaining. I see the problem.

However, I will suggest a workaround that only work in a specific case. Am I right in assuming that `trevor-vaughan/<reponame>/pull/<pull_id>` is your own repository, and the PR in question is a same-repository pull-request (meaning: not coming from another fork)? Then you can try the updated `hub checkout` command in the 2.3.0-prerelease version (available as downloads from Releases section). The updated command will, instead of naming the new branch `trevor-vaughan-...`, name the branch with the same name as the head of the pull request, meaning that simply doing `git push origin HEAD` after doing changes will update the head branch and thus the PR in question.

Does this cover your use case?

**Comment by trevor-vaughan** [comment]
@mislav Thanks for the feedback. I was just using my account as an example. I have several accounts that I regularly update with a '-' in the name.

I just tried the new 2.3.0-prerelease and it doesn't help given that other users also have '-' in their usernames. Fundamentally, I just need some character(s) that either a) I can set myself or b) can't show in a GitHub username.

It looks like changing the middle character to (--) instead of just (-) would actually solve the problem nicely (until GitHub allows '--' in usernames).

**Comment by trevor-vaughan** [comment]
Quick follow up. I just validated this by changing line 119 in commands/checkout.go from `"%s-%s"` to `"%s--%s"` and it worked a champ for ensuring that things are cleanly separable.

**Comment by mislav** [comment]
Is it an option for you to specify your own branch name instead of having one generated for you? E.g.

```
hub checkout <PR-URL> my-branch-name
```

**Comment by trevor-vaughan** [comment]
Not really. I don't know anything about the branch that I'm cloning since hub masks it all away from me. If I tried to do that, I'd basically start rewriting hub.

**Comment by mislav** [comment]
`hub checkout` no longer prefixes the name of the branch with the user's name. The branch name is identical to that in the `head` of the pull request: https://github.com/github/hub/blob/08004b921836a3fa8ae6054ab273cdbf6da39f8c/features/checkout.feature#L31-L34
