### ISSUE TITLE
Update github.com/inconshreveable/go-update

### ISSUE THREAD

**Issue by kevinburke** [github/hub#1351]
The version of go-update in this repo is out of date, and refers to a package (go-update/download) that doesn't exist in the master version of that project. 

This causes problems for people that are revendoring; for example https://github.com/Shyp/go-git/blob/master/git.go#L153-L156 imports github.com/github/hub/commands as a library, and an upstream package main wants to use its own vendor directory. This means we have to manually set in place an older version of that package.

I think it'd be easier for everyone if the go-update API's used in this package were updated to the latest version and the included dependency was also updated.

**Comment by kevinburke** [comment]
Furthermore I'm not sure that the code that's present in vendor/github.com/inconshreveable/go-update points at an actual commit. It imports github.com/kardianos/osext, but the closest commit to the one in this repo (https://github.com/inconshreveable/go-update/commit/276093003334bfddde2b1759b864b7c59f38b55e) points at bitbucket.org/kardianos/osext. Needless to say, this causes problems.

**Comment by mislav** [comment]
I've been wanting to 🔥 that functionality because it's dead code right now. Done in d400838ecf7653923713b4c3a84dd625c5b5ce7a

That also gets rid of the dependency.
