### ISSUE TITLE
Add instructions on how to vendor

### ISSUE THREAD

**Issue by kevinburke** [github/hub#1352]
Right now it's not clear how the vendor directory was constructed or how to update a dependency that's present there. I checked the README, the vendor directory, the top level of the project and CONTRIBUTING.md.

**Comment by mislav** [comment]
That's a good point. I've constructed the `vendor/` directory manually. I agree that we should ship a script that updates a certain dependency, or switch to a tool that does this for us.

**Comment by kevinburke** [comment]
Hi @mislav, any updates here, or is that still the procedure?

**Comment by mislav** [comment]
No, sorry; I haven't updated the vendored dependencies much (they work ok!) and the process is still manual. If you have better suggestions, please explain so here! I'd love to improve this process, but I don't want to switch to a tool that might be an overkill such as godep.
