### ISSUE TITLE
Allow using GUI editor

### ISSUE THREAD

**Issue by svnpenn** [github/hub#1354]
~~~
$ GIT_EDITOR=notepad hub pull-request
error using text editor for pull request message
~~~

this is a workaround, but not ideal, as it requires having changed the registry to map Notepad to unknown files types:

~~~sh
 GIT_EDITOR='cygstart -w' hub pull-request
~~~

**Comment by svnpenn** [comment]
It looks like the problem is that hub is feeding text through STDIN, rather than just opening a file:

~~~
$ GIT_EDITOR=grep hub pull-request

$ grep: (standard input): Input/output error
~~~

**Comment by svnpenn** [comment]
It looks like the problem is only if the path has spaces in it:

~~~
$ GIT_EDITOR=C:/Notepad2 hub pull-request
Aborting due to empty pull request title

$ GIT_EDITOR='C:/Program Files/Notepad2/Notepad2' hub pull-request
error using text editor for pull request message
~~~

**Comment by svnpenn** [comment]
https://github.com/github/hub/issues/721

**Comment by svnpenn** [comment]
I found a workaround:

~~~
$ GIT_EDITOR='"C:/Program Files/Notepad2/Notepad2"' hub pull-request
Aborting due to empty pull request title
~~~

**Comment by svnpenn** [comment]
https://github.com/github/hub/issues/835

**Comment by svnpenn** [comment]
Note - error is not triggered when using `--issue` option

**Comment by mislav** [comment]
Your workaround is correct. What do you expect hub to fix here?

**Comment by svnpenn** [comment]
@mislav `notepad2` is on my PATH. Why is hub expanding `notepad2` to the full path, then improperly splitting said path? hub should:

- either dont expand notepad2 path - not needed because notepad2 on the PATH already
- if hub is going to expand the editor path, at least do it in a sane way that doesnt break on spaces

**Comment by mislav** [comment]
`set GIT_EDITOR=Notepad2` should work when Notepad2 is in your PATH. I've just tested it an it works.

Alternatively, if the program is not in your PATH, you will have to specify the full path to the program, and if the path contains spaces, you will have to double quote the path. This behavior is consistent with how git itself uses the GIT_EDITOR value for operations such as `commit`.

**Comment by svnpenn** [comment]
@mislav I found the source of the trouble. My PATH looks like this:

~~~
/usr/local/bin:/usr/bin
~~~

and Notepad.exe is here:

~~~
C:\Program Files\Notepad2
~~~

and I symlinked it like this:

~~~
ln -s "$PROGRAMFILES"/notepad2/notepad2 /usr/local/bin
~~~

This allows me to open Notepad2 from the command line, but not work with Hub. To
fix, the .exe must be added:

~~~
ln -s "$PROGRAMFILES"/notepad2/notepad2.exe /usr/local/bin
~~~

**Comment by mislav** [comment]
I'm glad you solved it! I'm closing this one out since I don't think there is anything I need to fix in hub.

**Comment by mislav** [comment]
@harmnot Either set `GIT_EDITOR=nvim` environment variable in your shell or set `git config --global core.editor nvim`.
