### ISSUE TITLE
Listing Github details for contributors between two tags

### ISSUE THREAD

**Issue by danielbachhuber** [github/hub#1355]
One of the steps in WP-CLI's release process is to run `./utils/contrib-list` ([ref](https://github.com/wp-cli/wp-cli/blob/master/utils/contrib-list)) to produce a list of contributors between two tags (or an existing tag and master). The end result is something like this:

![image](https://cloud.githubusercontent.com/assets/36432/20928653/b4f75480-bb7b-11e6-8c00-5f5838d9ff17.png)

However, the script is broken-ish right now. I've been meaning to fix it, but thought it might make a good contribution to `hub` instead. Something you'd consider a PR for?

**Comment by mislav** [comment]
It's an interesting case but I don't think it belogs in hub core right now. A list of people's names is easily available through `git log`. I guess the complex part of this script would be mapping the email addresses to GitHub account handles?

**Comment by danielbachhuber** [comment]
> I guess the complex part of this script would be mapping their email addresses to GitHub account handles?

Right — doing some amount of authenticated Github.com API request to fetch these details.

**Comment by mislav** [comment]
Here's a simple bash function that converts an email to a GitHub handle:

```sh
find_user() {
  curl -fsSL "https://api.github.com/search/users?q=in:email%20$1" | \
    grep '"login":' | cut -d'"' -f4
}

handle="$(find_user "mislav.marohnic@gmail.com")"
echo $handle #=> "mislav"
```

It will yield blank output if a user couldn't be found. In such cases, the person's full name from git log should be used instead of GitHub handle.

**Comment by sinisterstuf** [comment]
If this isn't going to happen, should we consider this issue closed then?

**Comment by danielbachhuber** [comment]
For this comfortable with PHP, here's what I ended up implementing for WP-CLI: https://github.com/wp-cli/wp-cli/blob/master/utils/contrib-list.php
