### ISSUE TITLE
Support passing in reviewers when creating a pull request

### ISSUE THREAD

**Issue by JordonPhillips** [github/hub#1358]
The concept of [reviewers](https://github.com/blog/2291-introducing-review-requests) was added to the frontend today. It would be great to be able to specify those on the command line when creating the pr.

**Comment by mislav** [comment]
Good idea, but the feature is not yet available through the GitHub API.

**Comment by dkpalmer** [comment]
Possibly available now via https://developer.github.com/v3/pulls/review_requests/#create-a-review-request ?

**Comment by hkdobrev** [comment]
> The Pull Request Review API is currently available for developers to preview. During the preview period, the API may change without advance notice. Please see the blog post for full details.
> 
> To access the API during the preview period, you must provide a custom media type in the Accept header:
> 
> `application/vnd.github.black-cat-preview+json`

Does that mean only access tokens from developers in the early access program would be able to use this API or everybody will be if they provide this media type?

**Comment by mislav** [comment]
Oh nice. That means hub only needs to set this `Accept` header and everything will work. This is not related to the Early Access program.

So, what would be the API for requesting reviewers through hub?

**Comment by hkdobrev** [comment]
@mislav I would imagine a flag to the `pull-request` command similar to assignees would be welcome.

**Comment by mislav** [comment]
Hmm how about:

```
	-r, --reviewer <USERS>
		A comma-separated list of GitHub handles to request a reviews from.
```

**Comment by julien51** [comment]
Any idea why this not working with 2.2.9?

```
git pull-request -r benwerd
unknown shorthand flag: 'r' in -r
```

```
$ git --version
git version 2.2.1
hub version 2.2.9
```

Thanks!

**Comment by harmnot** [comment]
is for `-r` need using his username ? or email ? could I do space also ??

**Comment by mislav** [comment]
@harmnot `hub pull-request -r user1,user2,user3`

Just usernames, no spaces, no emails.

**Comment by harmnot** [comment]
I see, is hub pull-request as merge request like on Gitlab ? because I want to merge request from my branch to Dev, what is that command for it ?

**Comment by mislav** [comment]
Yes, a Pull Request is basically a merge request. https://help.github.com/en/articles/about-pull-requests

I'm not sure what exactly you're trying to do, but this might help: https://hub.github.com/hub-pull-request.1.html

**Comment by harmnot** [comment]
I get error do this : `hub pull-request --base gitlab<username>:development --head gitlab<username>:mybranchnow -a gitlab<username>`

the error is something like this: 
`Aborted: could not find any git remote pointing to a GitHub repository`

**Comment by mislav** [comment]
@harmnot It sounds like you are using GitLab for your repository. The hub project only works with GitHub.

**Comment by harmnot** [comment]
hmm I see, how can I use pull-request on gitlab? is that possible ?

**Comment by mislav** [comment]
@harmnot Perhaps possible with another tool, but not this one.
