### ISSUE TITLE
pull-request: Add -l label option like hub issue

### ISSUE THREAD

**Issue by sjackman** [github/hub#1361]
The `hub issue` command takes a -l option to specify a label for this new issue. Please add the same label option to `hub pull-request`.

**Comment by mislav** [comment]
Already done: https://github.com/github/hub/releases/tag/v2.3.0-pre3. Please grab the latest of the prereleases.

**Comment by sjackman** [comment]
Any hope for a stable release of hub 2.3.0? Thanks again for this terribly useful tool.

**Comment by mislav** [comment]
I'll try to roll out hub 2.3.0 soon, but in the meantime you'll be fine if you install one of the prereleases from the Releases section or just build from master.

**Comment by sjackman** [comment]
Yes, I've tested the prereleases, and it works brilliantly, but I can't roll out the programmatic use of this feature in my tool until the feature's made it into a stable release, because I assume that users of my tool have a stable release of `hub` installed using `brew install hub`.
