### ISSUE TITLE
issue and pull-request: Add assignees option [feature request]

### ISSUE THREAD

**Issue by sjackman** [github/hub#1362]
Please consider adding an option to specify the assignees to the `hub issue` and `hub pull-request` commands.

**Comment by mislav** [comment]
OK; this was done in August: https://github.com/github/hub/releases/tag/v2.3.0-pre3

**Comment by sjackman** [comment]
Great. Thanks!
Homebrew has `hub` 2.2.9 and have a policy of not upgrading users to prereleases by default. Is a stable release of `hub` imminent?

**Comment by mislav** [comment]
Not imminent but I'll try to speed it up.

You can do `brew upgrade hub --HEAD` to install from master.

**Comment by sjackman** [comment]
Thanks, Mislav. I see that there's also `brew install --devel hub`
Thanks again for `hub`. It's very useful.
