### ISSUE TITLE
hub 2.2.9 for Linux 64-bit is not broken

### ISSUE THREAD

**Issue by Craphtex** [github/hub#1364]
Installing and subsequently running `hub` using the [hub 2.2.9 for Linux 64-bit](https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz) yields the following error.
`bash: /usr/local/bin/hub: cannot execute binary file: Exec format error`

Working solution is to downgrade to version 2.2.8.

Running Ubuntu 16.04 LTS.

**Comment by mislav** [comment]
Thanks for reporting! This is indeed worrisome. The only thing that might have changed between these builds is the Go version used for cross-compiling them. It's surprising that an newer Go version would make a botched Linux build when an older version created it properly.

**Comment by kynan** [comment]
@Craphtex you should fix the this issue title: it *is* broken ;)

**Comment by deivid-rodriguez** [comment]
Weird... I'm using the 64-bit release on 16.04 and didn't run into this issue. Maybe you have a 32 bits machine?

**Comment by kynan** [comment]
@deivid-rodriguez Indeed, 2.2.9 wfm too (16.04).
@Craphtex corrupt download?
@mislav I think this can be closed.

**Comment by mislav** [comment]
Yes, this could be due to corrupt download. I haven't got similar reports. I will close until there is more information. Thank you everyone!
