### ISSUE TITLE
Nuget 3.5 rtm restore failure in Jenkins

### ISSUE THREAD

**Issue by irfspy** [github/hub#1365]
Hi,

The build in Jenkins in failing due to Nuget Restore failure.

error MSB3073: The command ""D:\NuGet\v3.5.0-rtm\NuGet.exe" restore "..\Demo.sln" -MSBuildVersion 14 -NonInteractive" exited with code 1.

In solution project.json is used with wild cards to get the latest version of nuget package. Also here in project file nuget cache is implemented.

**Comment by mislav** [comment]
Are you perhaps commenting on the wrong project? I don't see how any of what you've described applies to this project, which is called "hub" and is a command-line tool that wraps the `git` version control tool.

**Comment by irfspy** [comment]
Oh sorry, I will remove it from here.
