### ISSUE TITLE
hub checkout using HTTPS should not ask for password

### ISSUE THREAD

**Issue by stevenroose** [github/hub#1366]
When checking out a PR in a public repository, hub asks for a password. It should be possible to do this without doing so.

**Comment by mislav** [comment]
Hub needs to authenticate with GitHub API for the first time you use it, be it against a private or a public repo. Yes technically it should be possible to check out a PR in a public repo without a password, but sooner or later you're going to bump into a case where authentication is absolutely needed, so in hub I've decided to ask for password right away so you don't have to worry about it later. You only need to do it once. https://github.com/github/hub/issues/1334#issuecomment-258839895
