### ISSUE TITLE
pull-request looks for PULL_REQUEST_TEMPLATE.md in $PWD

### ISSUE THREAD

**Issue by sjackman** [github/hub#1367]
`hub pull-request` looks for `PULL_REQUEST_TEMPLATE.md` in the current working directory and fails to find it when run in a subdirectory. `hub` should instead look in the project root directory, which can be found using`git rev-parse --show-toplevel`.

**Comment by mislav** [comment]
This was fixed in 1a3a934714a37fa05f9920daf9b7a00186321502! It will be in the next (pre)release.

**Comment by sjackman** [comment]
Thanks, Mislav. I'm keenly looking forward to the next stable release of `hub`. So many new useful features.
