### ISSUE TITLE
pull-request command no longer re-using commit title/body

### ISSUE THREAD

**Issue by jviotti** [github/hub#1371]
Previously, when I ran `hub pull-request` on a branch that only contained a single commit, my editor would pop up with the commit title and body, however I suddenly get just a blank file.

Has something changed recently? Is there a way I can preserve this behaviour?

In case nothing changed from hub's side, could this be caused by these recent changes to my GitHub account:

- Enabled 2FA
- As a consequence, I'm not using HTTPS remotes anymore

**Comment by jviotti** [comment]
The following command solved the issue:

```sh
git branch --set-upstream-to=origin/master master
```

Thanks a lot anyway!

**Comment by adjohnson916** [comment]
@jviotti I'm having the same issue. Setting upstream isn't fixing it.
