### ISSUE TITLE
View remote in browser

### ISSUE THREAD

**Issue by DancingQuanta** [github/hub#1373]
Can `git browse` be used to open the url of a remote?

For example after forking a project from within the local repo, the local repo will have a remote with my username as a name pointing to that fork and if I want to view my fork in browser I like to execute
```
git browse REMOTE
```
where `REMOTE` is the name of the remote,
While
```
git browse
```
just open the origin.

**Comment by mislav** [comment]
No, you can't specify a remote name right now. There was some discussion about adding a global `--remote` flag that would allow you to explicitly specify a git remote for any hub command.

**Comment by DancingQuanta** [comment]
Why global? I am thinking about specifying a remote within a context of a hub command so that I could choose a remote to use without touching global settings.
Can you reference this discussion you mentioned please?

**Comment by mislav** [comment]
By "global", I meant a global flag (example usage: `git browse --remote REMOTE`) and not a global setting. It would still be per-invocation.

A global flag would benefit subcommands other than just `browse`. Context: https://github.com/github/hub/issues/1297

**Comment by DancingQuanta** [comment]
Didn't check that there was a pull request already #1342.
Closing as this issue was already raised elsewhere and in process of being addressed
