### ISSUE TITLE
Should be able to push to remote/branch created by `hub checkout <PR URL>`

### ISSUE THREAD

**Issue by jfirebaugh** [github/hub#1376]
For pull requests contributed with the "Allow edits from maintainers" option enabled, I find myself wanting to perform the following workflow:

```
hub checkout <PR URL>
<make changes, commit>
git push
```

It would be nice if this "just worked": successfully pushed to the PR branch in the contributor's fork. Instead, the following error occurs:

```
fatal: remote error: 
  You can't push to git://github.com/<contributor>/<repo>.git
  Use https://github.com/<contributor>/<repo>.git
```

**Comment by jfirebaugh** [comment]
It looks like two things need to be different from the current default configuration created by `hub checkout` for this to work:

* The URL for the remote needs to be `git@github.com:<contributor>/<repo>.git`, rather than `git://github.com/<contributor>/<repo>.git`.
* Either the local branch needs to be named `<branch>`, rather than `<contributor>-<branch>`, or `hub checkout` needs to set the upstream of the branch to `<contributor>/<branch>`. Otherwise `git push` tries to push to the upstream `<contributor>/<contributor>-<branch>`, which will be rejected with a permission denied error.

**Comment by mislav** [comment]
@jfirebaugh I agree that this should be configurable, and your reasoning is sound. I'll see what we can do about this, since right now I'm not sure if the "allow edits from maintainers" bit for a specific PR can be read through the API. If not, we can't tell which branches you have permissions to push to.

Related: https://github.com/github/hub/issues/1349

**Comment by hjanuschka** [comment]
i would love to see this implemented.

**Comment by jfirebaugh** [comment]
This doesn't seem to be working in 2.3.0-pre9. I tried it with [this PR](https://github.com/mapbox/mapbox-gl-js/pull/4459), and received the following error when attempting to push:

```
~/Development/mapbox-gl-js $ git push
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 601 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:huaruiwu/mapbox-gl-js.git
 ! [remote rejected]   huaruiwu-flyto-worldcopies -> huaruiwu-flyto-worldcopies (permission denied)
error: failed to push some refs to 'git@github.com:huaruiwu/mapbox-gl-js.git'
```

**Comment by jfirebaugh** [comment]
Note that I have `push.default` set to `current`. With `push.default` set to the git default of `simple`, I get the following error instead:

```
~/Development/mapbox-gl-js $ git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push git@github.com:huaruiwu/mapbox-gl-js.git HEAD:flyto-worldcopies

To push to the branch of the same name on the remote, use

    git push git@github.com:huaruiwu/mapbox-gl-js.git huaruiwu-flyto-worldcopies

```

**Comment by jfirebaugh** [comment]
We'd like `git push` to push to the upstream branch specified by the `branch.*.merge` option, regardless of the value of `push.default` or the fact that the name of that upstream branch does not match the local branch name. (This is the behavior of the `upstream` value for `push.default`.)

However, I cannot find a git option that would allow this. The closest is `remote.*.push`, but that would set a default refspec for all branches of the remote. We need something like `branch.*.push`, which does not exist.

In light of this, would you consider changing the naming convention that hub uses for the branch? If the branch had the same name as it does in the remote, the `current`, `simple`, or `upstream` behaviors for `push.default` would all do the right thing.
