### ISSUE TITLE
Difference from `git`

### ISSUE THREAD

**Issue by flux627** [github/hub#1378]
Since all of `git`'s functionality is included in `$ man hub`, I'm having a hard time seeing at-a-glance all of what this gem enhances. Is there an easy way to see this anywhere?

**Comment by seanr** [comment]
If you run hub help, it will show you:

```
These GitHub commands are provided by hub:

   pull-request   Open a pull request on GitHub
   fork           Make a fork of a remote repository on GitHub and add as remote
   create         Create this repository on GitHub and add GitHub as origin
   browse         Open a GitHub page in the default browser
   compare        Open a compare page on GitHub
   release        List or create releases (beta)
   issue          List or create issues (beta)
   ci-status      Show the CI status of a commit
```

**Comment by mislav** [comment]
@flux627 `man hub` (same as `hub help hub`; [seen online here](https://hub.github.com/hub.1.html)) does actually document in detail all extensions that hub provides over `git`. Apart from listing all the custom commands mentioned above, it also documents extensions to existing git commands, such as `git clone` and `git checkout`.
