### ISSUE TITLE
hub create ORG/PROJECT creates under user ORG

### ISSUE THREAD

**Issue by erjoalgo** [github/hub#1380]
$ hub create my-org/my-project
origin  user@example.com.ge.com:my-org/my-project.git (fetch)
origin  user@example.com.ge.com:my-org/my-project.git (push)
created repository: my-user/my-project

$ git push origin master 
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ git remote -vv
origin  user@example.com.ge.com:my-org/my-project.git (fetch)
origin  user@example.com.ge.com:my-org/my-project.git (push)

**Comment by mislav** [comment]
Thanks for reporting. Which hub version are you using? Check with `hub version`

**Comment by erjoalgo** [comment]
```
$ hub version
git version 2.1.4
hub version 2.2.0-228-g525ee53
```

I'll try pulling a later version

**Comment by erjoalgo** [comment]
I can confirm this is fixed in 

```
git version 2.1.4
hub version 2.3.0-pre8
```

Thanks
