### ISSUE TITLE
Can't use with GH Enterprise

### ISSUE THREAD

**Issue by TomDunham** [github/hub#1381]
Hi I can't seem to use `hub` with Github Enterprise.

```
% hub --noop pull-request       
Aborted: the origin remote doesn't point to a GitHub repository.
```

I have whitelisted my GHE hostname

```
% hub config --get-all hub.host
myco-github.com
```

I do not have an `upstream`, or any weird urls at all

```
% hub remote -vv            
origin	git@myco-github.com:myco/chef-repo.git (fetch)
origin	git@myco-github.com:myco/chef-repo.git (push)
```

I've tried being a bit more explicit about which host I want

``` 
% GITHUB_HOST=myco-github.com hub --noop pull-request
Aborted: the origin remote doesn't point to a GitHub repository.
```

I'm on GHE 2.7, and these client versions (installed with `brew install hub`)
```
% hub --version
git version 2.8.4 (Apple Git-73)
hub version 2.2.9
```

WRT #952, I don't have `hub.protocol` set at all (`git config --get-all hub.protocol` responds with no lines). 

I can't find any `--verbose` flag that will let me know what string `hub` is looking at.

**Comment by mislav** [comment]
Thanks for sharing all this info. Everything seems to be set up correctly on your end; most importantly the `hub.host` config. I'm not sure what fails.

The debug mode is entered by setting the environment variable `HUB_VERBOSE=1`, but it might not help you here.

Does your actual domain name (that you anonymized with `myco-github.com`) have a dash in it? Maybe the dash character is a problem somewhere.

**Comment by TomDunham** [comment]
Thanks for the quick reply. Yes my really-real domain name has a dash in it (`myco` is replaced by a string of near-identical length that would match `[a-z]`, that is the only change).

I tried `HUB_VERBOSE`, just for the fun of it:
```
HUB_VERBOSE=1 hub --noop pull-request
$ git config alias.pull-request
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
Aborted: the origin remote doesn't point to a GitHub repository.
```

**Comment by mislav** [comment]
I just realized our string comparison for host name might be case-sensitive, when in fact it should not be. Can you check if there are any capital letters in the hostname of either the git remote configuration or the `git config --get-all hub.host` list?

**Comment by TomDunham** [comment]
Nope, no capital letters anywhere.

**Comment by mislav** [comment]
@TomDunham Do you have any `HostName` aliases in your `~/.ssh/config`? Thanks for your patience

**Comment by timja-kainos** [comment]
@mislav I'm having the same problem.

I do have `HostName` aliases in my `~/.ssh/config`

Our deployment has an nginx in front of GHE on a different VM 
To make ssh work we're using this config:

```
Host git.<company-domain>
HostName gitssh.<company-domain>
User git
ProxyCommand ssh -q bastion.<company-domain> -W %h:%p
```

Our GHE is also running over http not sure if that's a problem or not.


```
 HUB_VERBOSE=1 hub pull-request
$ git config alias.pull-request
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
Aborted: the origin remote doesn't point to a GitHub repository.
```

**Comment by mislav** [comment]
@timja-kainos @TomDunham If you have `HostName` in your ssh config, then you have to ensure that whatever is whitelisted in `hub.host` matches the finally expanded host name after ssh aliases have been processed. In your case, you need to whitelist `git config --global --add hub.host gitssh.<company-domain>`.

**Comment by timja-kainos** [comment]
@mislav Can it be configured to go over http?
When I added the config it asked me for my credentials but then tried to use port 443.
Our deployment is using http 👎

**Comment by mislav** [comment]
@timja-kainos Yes but for now you'll need to edit `~/.hub/config` directly to add:

```
YOUR.HOSTNAME:
- user: timja-kainos
  protocol: http
```

**Comment by timja-kainos** [comment]
@mislav Can I configure a different url for it to use instead?

Port 80 for GHE isn't available directly only by going through the reverse proxy

**Comment by mislav** [comment]
No I don't think that's possible right now. You could do a workaround by manually opening an SSH tunnel to forward the port 80 of your GHE instance to your local port `localhost:8080` or something. Then you can configure hub to pretend that `localhost:8080` is your GHE.

I don't know how hub should or could handle this better. If you or your coworkers have any ideas, let me know.

**Comment by timja-kainos** [comment]
I can't think of a nice way to do that

An easier way for this case to be handled would be for ssh access use the ssh config but not http(s) api calls then just use the hostname in the git remote config and don't resolve the different one from the ssh config.
Or allow the GHE api url to be overridden

**Comment by mislav** [comment]
@timja-kainos I'm not sure if I follow your thinking exactly, but from hub's perspective, the only thing it really needs is a hostname (with optionally port name) to communicate with the GHE API over HTTP. However, the main problem in your case might be that the git remote URL used for git operations is going to have a different hostname than what would be used for GHE API. Before, hub assumed that these hostnames would be identical.

Your idea to somehow allow GHE API url to be overriden might be the key here. Something like:

```yaml
gitssh.<company-domain>:
- user: YOUR-USER
  url: http://localhost:8080
```

**Comment by timja-kainos** [comment]
In my case the git remote url is the same as the API url

but ssh config override the ssh hostname to be something else which ssh actually uses.

Does that make sense.

Yeah that would be perfect

**Comment by TomDunham** [comment]
Hi Mislav, sorry for the delay.

I do have `HostName` in my ssh config, but the alias expands to the `myco-github.com` address I have already added to `hub.host`.

I'm pretty sure that there's nothing odd happening with the alias expansion as I see lines like this if I run `ssh -vT git@myco-github.com`:

```
debug1: Authenticating to myco-github.com:22 as 'git'
...
debug1: Host 'myco-github.com' is known and matches the ... host key.
```

(That command exits with the expected `You've successfully authenticated, but GitHub does not provide shell access.`).

**Comment by mislav** [comment]
> I do have `HostName` in my ssh config, but the alias expands to the `myco-github.com` address I have already added to `hub.host`.

Hub still might be getting confused about some of that. The safest way would be to whitelist both aliased and resolved hostnames. E.g. if your ssh config is:

```
Host My-Alias.com
  HostName Resolved.com
```

Then add both:

```
git config --global --add hub.host My-Alias.com
git config --global --add hub.host Resolved.com
```

**Comment by mislav** [comment]
Closing this with the assumption that it's no longer an issue
