### ISSUE TITLE
Read from hub’s config file?

### ISSUE THREAD

**Issue by vitorgalvao** [github/hub#1384]
When I ran `hub config --get github.user` I though I was reading from `~/.config/hub`, but am in fact reading from `~/.gitconfig`.

I’ve tried a few commands, and nothing worked for this purpose. Is there a command to read directly from hub’s configuration, or do I need to `grep` it?

**Comment by mislav** [comment]
You will need to grep it for now. Here's how to reliably extract it:

```sh
awk '/user:/{print $(NF)}' ~/.config/hub | head -1
```

In future there will be a command to read hub's configuration (#225), but one doesn't exist yet.
