### ISSUE TITLE
cannot open browser when executing `hub pull-request --browse` with emacsclient

### ISSUE THREAD

**Issue by shigemk2** [github/hub#1385]
## Environment 

- Mac
    - Mac OS Sierra
    - git version 2.10.1 (Apple Git-78)
    - hub version 2.2.9

- Linux
    - Ubuntu 16.10
    - git version 2.9.3
    - hub version 2.2.0-416

- editor: emacsclient

## Overview

I couldn't open browser when executing `hub pull-request --browse` after creating a pull-request.
I expected to open pull request page I created, but I could open Emacs.
I found this problem on MacOS Sierra, but I also found this problem on Ubuntu.

I think it is because git.core.editor is `emacsclient`.

**Comment by mislav** [comment]
> I couldn't open browser when executing `hub pull-request --browse` after creating a pull-request.

What happened instead when you ran that command?

Protip: you could use `HUB_VERBOSE=1 hub pull-request --browse` to see extra debugging information.

The `--browse` option shouldn't be affected at all by your `core.editor` configuration. They are separate operations. First, the text editor opens so you can write the title and the body of your pull request. Then, the pull request is created using GitHub API. Finally, the `--browse` option causes the web browser to open with the URL of the just-created pull request. On macOS, this gets executed:

```
open https://github.com/YOURNAME/PROJECT/pull/123
```

**Comment by shigemk2** [comment]
I could open text editor instead when I ran `hub pull-request --browse` even if  the Pull Request exists.

It was `HUB_VERBOSE=1 hub pull-request --browse` on Ubuntu 16.10.

```sh
$ git rev-list --cherry-pick --right-only --no-merges origin/topic-branch...
$ git remote -v
$ git remote -v
$ git rev-list --cherry-pick --right-only --no-merges upstream/master...origin/topic-branch
$ git rev-parse --show-toplevel
$ git config core.commentchar
$ git var GIT_EDITOR
$ git config core.commentchar
$ emacsclient /path/to/github-repo/.git/PULLREQ_EDITMSG
```

**Comment by mislav** [comment]
Oh, so you're saying that the pull request for this branch already exists, and you expected its web page to open immediately, but instead your text editor opened?

The `hub pull-request` command is not yet aware of existing pull requests. It will open a text editor every time because it thinks you want to create a new pull request.

I do want to make `pull-request` aware of existing pull requests. This will likely get addressed at the same time as https://github.com/github/hub/issues/688. Does this answer your questions?

**Comment by shigemk2** [comment]
Thank you for your reply.

It can be my answer.
