### ISSUE TITLE
pull-request command: add option or posarg to specify remote 

### ISSUE THREAD

**Issue by szdavid92** [github/hub#1387]
I would like to open a pull-request to a remote else than origin.
Currently this is not possible with the `pull-request` command.
I think it would make sense to add an option or positional argument 
to the `pull-request` command so the user can specify it.

**Comment by mislav** [comment]
Thanks for the suggestion! We are already planning adding a global `--remote` flag to any hub command (including `pull-request`), so this will be possible after that feature lands: https://github.com/github/hub/issues/1297

Closing as an open issue for this already exists.
