### ISSUE TITLE
Question: Is there a way to generate a manifesto from nested folders containing git repos

### ISSUE THREAD

**Issue by reimertz** [github/hub#1390]
I currently migrate to using icloud drive for backuping, combining symlinks combined with the feature of files/folders ending with .`nosync` won't get synced.

My idea was to have a folder structure where everything being externally stored and version controlled, would be in these `.nosync` folders. I got this

```
- 3d
- illustrations
- movies
- music
- pictures
- presentations
- repos.nosync
  - repo 1
  - repo 2
  - ...
- school
- services.nosync
- work
  - company 1
    - docs
    - invoices
    - repos.nosync
      - repo 1
      - repo 2
      - ...
  - ...
```

Everything is working and the one thing I would have to do on a new computer is to symlink these folders into `~/`, but there's one caveat: I would have to both remember and manually `git clone` each individual repo in my `.nosync` folders.

So my question is, is there a easy way to generate/update a manifesto for all my repos that I then could combine with `hub` to automagically clone all repos?

**Comment by mislav** [comment]
> So my question is, is there a easy way to generate/update a manifesto for all my repos that I then could combine with `hub` to automagically clone all repos?

This should be easy to do with a simple bash script. You might not even need hub.

But before I can hint you towards a solution: from which data would this "manifesto" be generated from? Would it be a list of all your repos on GitHub, or a list of all your repos currently cloned on an existing machine?

**Comment by reimertz** [comment]
I think I'd prefer to always have my current cloned repos stored in this "manifesto".

I agree that a simple bash script would the best solution if there isn't any tools available to automate this process.

**Comment by mislav** [comment]
This script will generate a list of all repos currently cloned under a directory. Use it like e.g. `list-repos ~` to find all the repos cloned under your home directory:

```sh
#!/bin/bash
set -e

root="$(cd "${1?}" && pwd)"
find "$root" -type d -name .git | grep -vE '/(vendor|tmp)/' | \
  while read git_dir; do
    repo="$(git --git-dir="$git_dir" remote -v | grep -oE 'github.com[:/][^/]+/[^/ ]+' | head -1)"
    [ -n "$repo" ] || continue
    repo="${repo:11}"
    clone_dir="${git_dir#$root/}"
    printf "%s\t%s\n" "${clone_dir%/.git}" "${repo%.git}"
  done
```

This script will consume that data and clone all repos listed in it to a location of your choice. Use it like: `cat mylist.txt | clone-repos ~/repos.nosync`

```sh
#!/bin/bash
set -e

IFS=$'\t'
while read dir repo; do
  clone_dir="$1/$dir"
  echo mkdir -p "$clone_dir"
  echo git clone https://github.com/$repo.git "$clone_dir"
done
```

I believe this is enough to be a good starting point for you. This is not something that is suitable for implementing in hub core.
