### ISSUE TITLE
Can't get `hub issue --browse` to work

### ISSUE THREAD

**Issue by jcansdale** [github/hub#1391]
I was hoping to open an issue in the default browser. The  `hup issue --browse` command doesn't seem to do anything. How is this supposed to work?

```
        -o, --browse
                Open the new issue in a web browser.
```

It would be great if I could: `hup issue #777` or `hup issue -o 777`

Any chance this could be added? 😄

**Comment by mislav** [comment]
"Open the **new** issue in a web browser."—it's supposed to open an issue that you've just created from the command-line using `hub issue create`. This command is not supposed to be used for existing issues.

However, you can open an issue if you know its number with: `hub browse -- issues/777`.

**Comment by jcansdale** [comment]
Hi @mislav,

Thanks for the quick response. 😄 I didn't realize about the `hub browse -- issues/777` syntax.
`hub browse -- issues/777`

Any chance we could get `hub browse #777` to work? Using `-- issues/777` just seems a little verbose/harder to remember.

**Comment by mislav** [comment]
> Any chance we could get `hub browse #777` to work?

No, because `#` is a start of a comment in bash:

```sh
$ echo hub browse #777
hub browse
```

The command would never receive "777".

**Comment by jcansdale** [comment]
Fair point. 😉 

How about simply `hub browse 777` as a shortcut for `hub browse -- issues/777`?

I thought there might be some problems differentiating issues and PRs, but it turns that it will automatically redirect to a PR. For example: ```https://github.com/github/hub/pull/1389``` will redirect back to this issue.

**Comment by mislav** [comment]
That's a good point about the automatic redirect!

A simpler `browse` command is definitely planned. Something like `hub open <whatever>` should be able to differentiate whether `whatever` was a issue/PR number, a commit SHA, a branch name, etc. See "retire browse command" in https://github.com/github/hub/issues/1232
