### ISSUE TITLE
use https protocol instead of git protocol for public and keeping ssh for private

### ISSUE THREAD

**Issue by nhooyr** [github/hub#1392]
From the manpage:

```
              If the repository is private or the current user has push access to the repository, hub
              will  use  the ssh protocol for cloning. Use -p to select the ssh protocol uncondition-
              ally. HTTPS protocol can be used instead by setting "hub.protocol" (see CONFIGURATION).
```

If the repository or private or the current user has push access to the repository, I want to use the SSH protocol. However, if the repository is not private or I do not have push access, I want to only then use the HTTPS protocol.

I want to use ssh when I have access because it means I don't have to ever type my password on my server, it can just use my ssh agent to authenticate. But if I dont need access, I'd rather use the HTTPS protocol so that I don't always have to authenticate but still want a secure protocol.

**Comment by mislav** [comment]
Your reasoning makes sense, but this is not yet possible with hub.

I guess the `hub.protocol` option needs to be split into two configurable options: the preferred protocol for private/push access, and the preferred protocol for everything else.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
