### ISSUE TITLE
[bug] Github 2FA with Google Authenticator fails

### ISSUE THREAD

**Issue by tslevi-unbounce** [github/hub#1398]
I have to fall back on my sms backup. I've reset about 4 times, and each time it tells me on the next login attempt I'm entering the wrong code.

**Comment by mislav** [comment]
I'm sorry that you're having trouble. Just to be clear: when hub asks you for 2FA code, you tried using one from Google Authenticator, the same one that would work if you were logging in to the website, but hub doesn't accept it?

What is your `hub version`? Have you tried upgrading to latest `2.2.x` or `2.3.x` version?

**Comment by tslevi-unbounce** [comment]
Sorry, no this is trying to log into the website. Am I in the wrong place?

**Comment by mislav** [comment]
Yes, you could be asking in the wrong place. This is the bug tracker for a project called "hub" which is a program for inside the terminal. It's related to GitHub, but is separate from GitHub website.

If you have problems logging into the GitHub website, please reach out to support@github.com and they will help you promptly! If you are able to log in using the fallback SMS number, then you can head to your user settings https://github.com/settings/two_factor_authentication/configure and try to reconfigure 2FA device again to match your Google Authenticator.
