### ISSUE TITLE
Data dump for consumers

### ISSUE THREAD

**Issue by vermiculus** [github/hub#1407]
It would be super awesome if hub just had a 'data dump' mode that pulled everything in as few requests as possible; this would greatly help consumers of that information (like Magithub 😉).

**Comment by mislav** [comment]
I always wanted hub to also become a lower-level tool for scripts to interface with.

What data would you imagine this to dump?

**Comment by vermiculus** [comment]
The most common for me would be issues, pulls, labels, and CI status, but I guess what I'm really after is API middleware: something the user can trust to handle authentication but allows direct access to the API.

For brainstorming, what kind of higher-level scripts do you dream about? Any real solution should certainly be based on more use cases than mine 😄

**Comment by mislav** [comment]
I don't know what the use-cases might be, but plenty of hub commands could be a use-case for a consumer of a lower-level tool that provides this information. I want hub to be a utility that script authors can rely on for handling authentication, caching, and massaging of data, and that can deliver data in either line-based format (for shell scripts) or JSON (for more sophisticated scripts).

**Comment by mislav** [comment]
I would like us to construct this functionality using [GitHub GraphQL API](https://developer.github.com/early-access/graphql/). Over time, the rest of hub should switch internally into using the same API, until we entirely switch away from API v3 over the longer period.

The first order of business would be constructing a prototype. We would need a Go library that is capable of making GraphQL queries, and figure out how to do authentication.

**Comment by vermiculus** [comment]
Neat! For reference, [there are a couple such libraries already out there](http://graphql.org/code/#go).

**Comment by mislav** [comment]
There is a `hub api` command now! https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016
