### ISSUE TITLE
Downgrading hub causes repo where hub previously worked to show no issues

### ISSUE THREAD

**Issue by dakrone** [github/hub#1410]
I was using hub 2.3.0-pre8 in a repo to list issues (it worked fine), however, then I downgraded to hub 2.2.9 so that the `issues` command would still list pull requests, but now it appears that no issues are listed at all.

```
~/es/elasticsearch λ hub version
git version 2.9.3
hub version 2.2.9
~/es/elasticsearch λ hub issue
~/es/elasticsearch λ 
```

Is there a cache or something that needs to be removed so that hub downgrades successfully?

**Comment by mislav** [comment]
No, there is no cache and there should be no issue with downgrading. Possibly a connectivity issue? Try `HUB_VERBOSE=1 hub issue`

**Comment by dakrone** [comment]
That found it:

```
~/es/elasticsearch:unit-test-bulk2 Ϟ λ HUB_VERBOSE=1 hub issue
$ git config alias.issue
$ git rev-parse -q --git-dir
$ git rev-parse --symbolic-full-name unit-test-bulk2@{upstream}
$ git remote -v
$ git config --get-all hub.host
> GET https://api.github.com/repos/dakrone/elasticsearch/issues
> Authorization: token [REDACTED]
< HTTP 200
[]
```

The issue is that it will only grab issues based on the branch you're on, so if I happen to be on a branch in my local fork, there are no issues or pull requests.

Is this expected? If it is, I'm happy to close this issue, I just want to know.

**Comment by mislav** [comment]
Hmm, I'd like to this of this as a bug. Usually, all issues/PRs for a project go to the canonical (main) repo. Most of the cases, it doesn't make sense to list issues/PRs for a fork.

I wonder how does 2.3.0 behave in the same scenario?

**Comment by dakrone** [comment]
> I wonder how does 2.3.0 behave in the same scenario?

2.3.0-pre8 does _not_ have this bug, but unfortunately I cannot use it due to https://github.com/github/hub/issues/1303 (related https://github.com/github/hub/commit/8563e678d2f3cfc8d1bcc4ed3f38f7226c5d5012)

**Comment by mislav** [comment]
Closing because this is fixed in master branch:


* `hub issue` now has an option to include pull requests in the listing,
* `hub pr list` is now a dedicated command to only list pull requests,
* The upstream project is picked correctly in 2.3.0 prereleases.
