### ISSUE TITLE
Listing all public repositories of a github user/organization

### ISSUE THREAD

**Issue by cbcoutinho** [github/hub#1419]
I really enjoy using hub, this is such a great tool.

I was wondering if it's possible to use hub to list all the github repos associated with a particular user - either through a command or autocompletion at the command line. I use bash on Linux if that makes a difference.

Cheers,
C

**Comment by mislav** [comment]
Hi, thanks for writing in with a feature idea.

Listing repositories isn't something that most git users will perform on the command-line. It seems that this would be more suited for a generic "data dump" command that could output raw data from the API for script consumption: https://github.com/github/hub/issues/1407

Once that is done, we could tweak our shell completion scripts to autocomplete `hub clone github/hu` to `github/hubot` (or offer choices if there are multiple matches), but this is a long way down the road from now, and I'm not sure when we could get to that.

I'm going to close this as a duplicate. This will be possible when we have a generic API command for fetching arbitrary data.

**Comment by tfcat** [comment]
Think this would still be a really good feature to have! Feels out-of-place to be able to create and delete repositories from the command line, but not view them. Doing this using the generic API command becomes less trivial when you want to view private repositories. 

Still hope to see this feature one day!

**Comment by mislav** [comment]
Until then, fetching all your repositories can be done with `hub api`:

```sh
repos() {
  local user="${1?}"
  shift 1
  paginate hub api -t graphql -f user="$user" "$@" -f query='
    query($user: String!, $per_page: Int = 100, $after: String) {
      user(login: $user) {
        repositories(first: $per_page, after: $after) {
          nodes {
            nameWithOwner
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
  '
}

paginate() {
  local output cursor
  output="$("$@")"
  cursor="$(awk '/\.hasNextPage/ { has_next=$2 } /\.endCursor/ { if (has_next=="true") print $2 }' <<<"$output")"
  printf "%s\n" "$output"
  [ -z "$cursor" ] || paginate "$@" -f after="$cursor"
}

repos "tfcat"
```

**Comment by gko** [comment]
In case you want to show repositories of local user(that was logged in via hub):
```bash
repos() {
  local user="${1?}"
  shift 1
  paginate hub api -t graphql -f user="$user" "$@" -f query='
    query($user: String!, $per_page: Int = 100, $after: String) {
      user(login: $user) {
        repositories(first: $per_page, after: $after) {
          nodes {
            nameWithOwner
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
  '
}

paginate() {
  local output cursor
  output="$("$@")"
  cursor="$(awk '/\.hasNextPage/ { has_next=$2 } /\.endCursor/ { if (has_next=="true") print $2 }' <<<"$output")"
  printf "%s\n" "$output"
  [ -z "$cursor" ] || paginate "$@" -f after="$cursor"
}

user() {
  hub api --flat user | grep .login | awk '/.login/ {print $2}'
}

repos "$(user)" | awk '/\.nameWithOwner\t/ { print $2 }'
```

**Comment by cesarnorena** [comment]
I use this to list my repositories `hub api -X GET /user/repos | jq -r '.[] .name'`

**Comment by cbcoutinho** [comment]
Great find @cesarnorena - thanks!

**Comment by mislav** [comment]
A more efficient way to list _all_ repositories _owned_ by you:

```sh
 hub api --paginate -XGET user/repos -f affiliation=owner -f per_page=100 | jq -r '.[].name'
```

Explanation:
- uses`--paginate` to fetch all pages of results
- uses `per_page=100` to ensure the minimum amount of HTTP requests are necessary
- uses the `affiliation` filter to exclude repositories you have access to but are not the owner of
