### ISSUE TITLE
color issues with vim

### ISSUE THREAD

**Issue by sfahlberg** [github/hub#1420]
Hi there,
I use neovim and it looks like you are using vim from bin. is there a way to make sure you use `nvim` instead of `vi`? I've tried re-aliasing and that doesn't seem to work

**Comment by sfahlberg** [comment]
nevermind, I just set `GIT_EDITOR` to nvim which did the trick. you might want to add that to the docs

**Comment by mislav** [comment]
hub uses the same editor configuration as git does. Therefore, setting `GIT_EDITOR` is the proper solution for configuring the text editor. I don't think this needs documentation because it's not specific to hub.
