### ISSUE TITLE
hub doesn't work with custom domains like github.{my_company}.com

### ISSUE THREAD

**Issue by codyc4321** [github/hub#1421]
Hi, hub only works for pull-request when your repo is literally at github.com, but not for github.{my_company}.com

This makes it unusable for my purpose but it seems like a great item. I looked into the source but am not familiar with Go, the issue seems near to:

```
func (r *GitHubRepo) MainRemote() (remote *Remote, err error) {
	r.loadRemotes()

	if len(r.remotes) > 0 {
		remote = &r.remotes[0]
	}

	if remote == nil {
		err = fmt.Errorf("Can't find git remote origin")
	}

	return
}
```

The error message I get is `Aborted: the origin remote doesn't point to a GitHub repository.`

Thank you

**Comment by mickeybr** [comment]
Have you tried this? `GITHUB_HOST=git@github.{my_company}.com hub <command>`

**Comment by arbourd** [comment]
Is this a dup of #1381?

**Comment by mislav** [comment]
@codyc4321 In order to use hub with GitHub Enterprise, for now you need to whitelist domains in your git configuration as documented in https://hub.github.com/hub.1.html

```
git config --global --add hub.host github.mycompany.org
```

**Comment by gibffe** [comment]
I went through the chain of issues and ended up here. Can't get `hub` working in my env, please help.

```
> git version
git version 2.10.1 (Apple Git-78)
hub version 2.5.1
```
> git remote -v
origin	https://github.snei.sony.com/SNEI/nav-aws-infra.git (fetch)
origin	https://github.snei.sony.com/SNEI/nav-aws-infra.git (push)
```

```
> hub config --get-all hub.host
github.sie.sony.com
```

```
> hub --noop pull-request
Aborted: the origin remote doesn't point to a GitHub repository.
```

I do not have ~/.ssh/config

any ideas ?
