### ISSUE TITLE
error using text editor for pull request message

### ISSUE THREAD

**Issue by imaki-broadsoft** [github/hub#1432]
I know this issue has been discussed and even resolved earlier, but I am using latest hub version 2.3.0-pre9 and still having this issue. Other info:

OS: Windows 8.1
My .gitconfig has the following (among other things):
[core]
	editor = vim

I have tried setting values to GIT_EDITOR environment variable as suggested in #881 but that does not help.
hub pull-request works fine with -m option (without opening an editor).
git commit works fine with and without -m option (opens the editor just fine when that option is not given).

**Comment by mislav** [comment]
@imaki-broadsoft I'm sorry this is giving you trouble. If `git commit` works fine, then it's a bug that the editor in `hub pull-request` fails to open. What is the exact error message? Can you tell us where on your system `vim` is installed? What environment do you run `hub` commands in: git bash, Cygwin, cmd.exe, Powershell, other?

**Comment by imaki-broadsoft** [comment]
Mislav, thanks for the reply.

The exact error message is: "error using text editor for pull request message". I am using cmd.exe and I must use it because other tools that I need work only with it. I also tried git bash and it actually opened vim editor after having first complained this:
E303: Unable to open swap file for "<LOCAL PATH HIDDEN>\PULLREQ_EDITMSG" [noeol][unix] 6L, 228C

I don't know where vim is installed in my system but I searched for vim.exe with File Explorer and copied the latest (by date) match into my Windows user's Documents folder (I selected this folder to make sure it is writable, just in case it would matter) and then specified the whole absolute path to that file in my .gitconfig. In making this I made sure not to have spaces in the path and noticed that the delimiters in the path must be forward slashes as having backslashes in .gitconfig will make the whole git system fail. But still, after all this I still get the same error message from hub pull-request.

**Comment by mislav** [comment]
Thank you for looking into this. It's true that we have some bugs with text editor on Windows that I don't really know how to solve yet. If you enable debug mode, hub should output the exact command it tries to open the vim text editor with. Can you try that out and see what shows up?

```
SET HUB_VERBOSE=1
hub pull-request ...
```

**Comment by imaki-broadsoft** [comment]
Thank you for that tip. With the help of it I found out that the problem was a dll file that could not be found. When I added the path of that dll file in my PATH environment variable, hub pull-request started to work. Thank you!

**Comment by eromoe** [comment]
I am using git bash , meet this error too

**Comment by cschladetsch** [comment]
I have the same issue.

```
λ hub issue create
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git rev-parse --show-toplevel
$ git var GIT_EDITOR
$ git config core.commentchar
$ vi C:\Users\chris\work\.git\ISSUE_EDITMSG
error using text editor for issue message
```

I am a vi user, I even touched `vi C:\Users\chris\work\.git\ISSUE_EDITMSG`

Any tips?

**Comment by mislav** [comment]
@cschladetsch Can you try with `EDITOR=/usr/bin/vi hub issue create`?

Also, does running `vi C:\Users\chris\work\.git\ISSUE_EDITMSG` manually work, provided that the file exists?

**Comment by mederel** [comment]
I am facing the same problem in Git bash under windows 10.

Testing with `HUB_VERBOSE=1 EDITOR=/usr/bin/vim git pull-request` I have still the error, with this last  line:

```
$ C:/Program Files/Git/usr/bin/vim D:\git_clones\myproject\.git\PULLREQ_EDITMSG
error using text editor for pull request message
```

Take the command as is and executing it in the Git Bash command line I get (as can be expected cause of the whitespace):

```
bash: C:/Program: No such file or directory
```

Putting double quotes around the command vi, the file path is still incorrect as \ is recognized as an escape symbol (typically \n is a newline). When putting double quotes around that one as well, then vi opens the right way, with an empty file.

Is hub forgetting to put double quotes or to escape properly strange commande of the command line? Is it just a limitation there is no solution to?

**Comment by mederel** [comment]
It seems putting this for EDITOR variable seems to at least open vi:

```
EDITOR="\"C:/Program Files/Git/usr/bin/vim\""
```

But then I get some strange swap stuff from vim:

```
E303: Unable to open swap file for "D:\git_clones\praxis\myproject\.git\PULLREQ_EDITMSG", recovery impossible
```

**Comment by mislav** [comment]
@mederel Thank you for sharing!

If you are going to list full path to the editor in your EDITOR config, and that path has spaces, then the path indeed needs to be quoted like in your workaround (even though it looks awkward).

**Comment by mederel** [comment]
@mislav no problem, you're welcome.

But that was not enough, after edition I lost the whole contents because of an empty title (though I think I filled it appropriately). I will have to test again, on a less public repository.

**Comment by vikmn** [comment]
Is there a resolution for this issue? I still seem to get the message  on the pull request command in windows.What am i missing?

**Comment by Trim21** [comment]
> Is there a resolution for this issue? I still seem to get the message on the pull request command in windows.What am i missing?

I guess this is because `hub` call vim with windows path seprator `\`.

You can try something like ` vim ".vim\\a"`, this will got same issue about swap file creation
