### ISSUE TITLE
hub pull-request should create a pull-request to the default branch

### ISSUE THREAD

**Issue by mesaugat** [github/hub#1436]
I have set a default branch different from `master` on my GitHub repository. Now, when I create a pull-request using `hub pull-request` it always creates a pull-request to the master branch.

It would be nice if `hub pull-request` would create a pull-request to the default branch and not master if the user has set a different default branch for the repository. This way we don't have to edit the pull-request and change the base branch from the GitHub UI or do `hub pull-request -b <branch-name>` every time.

**Comment by arbourd** [comment]
`hub` gets the default branch from the repos `refs/remotes/origin/HEAD` in the `.git` folder. This is  set to the default branch when you close the repository. Simply update `HEAD` and it should work from now on :)

I believe this issue should be closed.

**Comment by mesaugat** [comment]
I think I've tried doing that. I'll try updating my HEAD again and close the issue if that's the case.

**Comment by arbourd** [comment]
I can confirm it works for me with:
```
git version 2.12.0
hub version 2.2.9
```

**Comment by mesaugat** [comment]
Ok, I still have HEAD set to master. I changed it something else, it should work now. Thank you.
