### ISSUE TITLE
Problem with /usr/bin/env: “bash\r”

### ISSUE THREAD

**Issue by wellington1993** [github/hub#1438]
Hi,

on try:
`bash script/build -o ~/bin/hub`

I get:

> /usr/bin/env: “bash\r”: Arquivo ou diretório não encontrado

I think this is problem with Git crlf config but I not sure about this. 
Anyone has any idea about this problem.

Thanks.

**Comment by mislav** [comment]
@wellington1993 I'm sorry you're having trouble! Have you checked our help article https://help.github.com/articles/dealing-with-line-endings/#platform-windows to see if it helps? Which platform are you on?

**Comment by wellington1993** [comment]
Hi @mislav,

My Plataform information:

`Linux wellington-Inspiron-3647 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

and

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```

**Comment by wellington1993** [comment]
Hi,

I solved the problem with the suggested documentation: https://help.github.com/articles/dealing-with-line-endings/#platform-windows

Thanks! (y)
