### ISSUE TITLE
git pull-request command only use "https" protocol

### ISSUE THREAD

**Issue by osmanager** [github/hub#1441]
Hello,
I think a feature for configuring ssl is need 
I use GHE. And my host server don't use the ssl.
In my environment, a "git pull-request" command don't work.

When run "git pull-request" command. A host URL is automatically made including https. And there is no config options that can change https to http.

I fix under line from https to http and it work!
[config.go#L75](https://github.com/github/hub/blob/master/github/config.go#L75)

How about my opinion?

Thank you

**Comment by mislav** [comment]
There is a hidden feature of hub that allows you to use "http" protocol without changing the source code. Just configure your Enterprise host like this in your `~/.config/hub`:

```
git.example.com:
- user: mislav
  oauth_token: MYTOKEN
  protocol: http
```

Notice the `protocol` parameter. This needs to be added.
