### ISSUE TITLE
Passwordless hub pull-request

### ISSUE THREAD

**Issue by atodorov** [github/hub#1442]
Hi folks,
I'd like to be able to create PRs without password (maybe using an API token) for use in automated environment. 

All users in the organization have 2 factor authentication enabled so hard-coding a particular username/password combo will not work. How do I authenticate using an API token ? Please point me to RTFM if any. Thanks.

**Comment by keith** [comment]
You can use the `GITHUB_TOKEN` env var for this. See `man hub` for more info. The token that you provide here must have the `repo` GitHub permission.

**Comment by mislav** [comment]
@keith is right. @atodorov please see https://hub.github.com/hub.1.html or `hub help hub`.
