### ISSUE TITLE
Aborted: the origin remote doesn't point to a GitHub repository.

### ISSUE THREAD

**Issue by mayank023** [github/hub#1445]
i cloned my repository and try executing **hub pull-request**
$ hub pull-request -b strategy_master
Aborted: the origin remote doesn't point to a GitHub repository.
$ git remote -v
origin	git@github.xxxx.com:xxx-services/yyy-server.git (fetch)
origin	git@github.xxxx.com:xxx-services/yyy.git (push)

i do not have any upstream and github remote set.

Help me here

**Comment by phodge** [comment]
I'm also getting this issue trying to open a PR on an enterprise github.

    $ hub --version
    git version 2.11.0 (Apple Git-81)
    hub version 2.2.9

**Comment by phodge** [comment]
@mayank023: This is mentioned in the [hub man page](https://hub.github.com/hub.1.html)

> By default, hub will only work with repositories that have remotes which point to github.com. GitHub Enterprise hosts need to be whitelisted to configure hub to treat such remotes same as github.com:
>     $ git config --global --add hub.host my.git.org

**Comment by mislav** [comment]
@phodge Thanks for pointing that out! @mayank023, if you're connecting to GitHub Enterprise, the hostname will need to be whitelisted as per documentation.

**Comment by DKKS** [comment]
@mislav I have enterprise github hosted internally  - github.xxx.xxx.xxx.com.
I'm trying to automate the process of creating the pull requests using:

$ hub pull-request develop ./
Aborted: the origin remote doesn't point to a GitHub repository. 

How do I use the hub-pull-request with my github server?

Please advise.

Thanks,
DKS

**Comment by mislav** [comment]
@DKKS: `git config --global --add hub.host github.xxx.xxx.xxx.com`

See https://hub.github.com/hub.1.html

**Comment by sujodey** [comment]
I am trying to perform a pull request to the repository which resides in BitBucket but I am getting an error

Error: Error creating pull request: Not Found (HTTP 404)

I tried performing git config --global --add hub.host bitbucket.org
but still the error persist.

Please help

**Comment by mislav** [comment]
@sujodey Hub is only made for GitHub repositories and does not support other platforms such as BitBucket; sorry.

**Comment by ghasemikasra39** [comment]
> @sujodey Hub is only made for GitHub repositories and does not support other platforms such as BitBucket; sorry.

No support even for gitlab ?!
