### ISSUE TITLE
request: ability to fork to organization on GitHub

### ISSUE THREAD

**Issue by RichardLitt** [github/hub#1452]
I would like to be able to run this:

```
hub fork --org=mtnnr
```

And have it fork not on my username, but to the @mntnr organization, or any other organization I have access to.

**Comment by mislav** [comment]
This is already available in the latest prerelease: https://github.com/github/hub/commit/cdd7a65e05e33a346c4cffb9130d88cfc9e18ff1

**Comment by RichardLitt** [comment]
Fantastic. Thank you.
