### ISSUE TITLE
hub fork doesn't add remote if fork exists

### ISSUE THREAD

**Issue by ahmetb** [github/hub#1454]
```
$ git remote -v
origin	git://github.com/kubernetes/community.git (fetch)
origin	git://github.com/kubernetes/community.git (push)
$ hub fork
Error creating fork: ahmetb/community already exists on github.com
$ git remote -v
origin	git://github.com/kubernetes/community.git (fetch)
origin	git://github.com/kubernetes/community.git (push)
```

I think if the fork already exists, `hub fork` can still add my remote (just like what happens when fork operation is successful).

**Comment by mislav** [comment]
You tried to fork `kubernetes/community`, but `ahmetb/community` is a fork of `GoogleCloudPlatform/community`. Hub detected that these are unrelated projects. If they were related, hub _would_ add the git remote. [See related tests](https://github.com/github/hub/blob/a7e5d48a7e980cff6768676c7769326d349a5cd1/features/fork.feature#L108-L133).

It's a limitation of the API that forks can't be configured to be named differently right now. You will have to use the web interface as a workaround. https://github.com/github/hub/issues/697
