### ISSUE TITLE
push HEAD~<some number>

### ISSUE THREAD

**Issue by brianjmurrell** [github/hub#1458]
With `git push` (i.e. to gerrit) I can push less than the full stack of patches I have using something like `git push origin HEAD~4:refs/for/branch`.  This is useful if I don't want to push the top 4 patches, say, because they are just being used locally, or they are a WIP, etc.

`hub` doesn't seem to do be able to do that when I push to a branch in my fork, before creating a PR, say.  Or maybe I am just not grokking how to do that with `hub`.

**Comment by mislav** [comment]
What exact problem are you having? Hub doesn't try to add any additional functionality or hijack said `git push` command. It would simply forward `git push origin HEAD~4:refs/for/branch` to git unchanged.

What did you expect to happen, and what happened instead? Does the same happen if you use the prefix `command git ...` in your shell (i.e. skipping hub)? What is the exact error message that you're getting?

**Comment by brianjmurrell** [comment]
Hrm.  I reported this long enough ago now that I don't recall what the outcome was and how it differed from what I expected.

Let me answer your questions when I once again need to be able to do this and see why it's not working.

**Comment by mislav** [comment]
@brianjmurrell Okay. Since there is no evidence or sufficient info to believe that there is a bug, I will go ahead and close this to clear out the backlog, but if you encounter this again, please feel free to reopen and submit a new issue with more info. Thank you!
