### ISSUE TITLE
hub pr command conflicts with git-extras

### ISSUE THREAD

**Issue by dsifford** [github/hub#1464]
Hi there,

Not sure what can be done here, but currently the `hub pr` command conflicts with the `pr` command for [git-extras](https://github.com/tj/git-extras/), which is arguably a bit more feature-packed and user friendly in its current form. 

Could hub maybe just adopt the same workflow as git-extras?

Thanks for considering! 😄

**Comment by mislav** [comment]
Thanks for reporting! I'm not sure what the right solution for these conflicts would be. However, the way I'm currently using hub is _without_ it being aliased as `git`. Therefore, if I want access to any hub commands, I need to prefix them with `hub` instead of `git`. Is this an acceptable solution?

Related: #153

**Comment by dsifford** [comment]
Hey @mislav!

Forgot about this one. I actually came up with my own solution for this that has worked just fine for me by simply creating a wrapper script that calls either `git` or `hub` depending on the command....

```sh
# ~/.bashrc

# Stub out "hub" when its commands conflict with better "git-extras" commands
hub-stub-conflicting-commands() {
    case "$1" in
        alias|fork|pr)
            /usr/bin/env git "$@"
            ;;
        browse)
            # Fix for random error that always shows up but doesn't actually matter
            /usr/bin/env hub "$@" 2>/dev/null
            ;;
        *)
            /usr/bin/env hub "$@"
    esac
}
alias git='hub-stub-conflicting-commands'
```

I'm good to call this one "resolved" if you are 😄

**Comment by mislav** [comment]
Nice wrapper; thanks for sharing!

I'm going to close this one out because there is a similar issue still open.
