### ISSUE TITLE
to hub or ghi (or both)

### ISSUE THREAD

**Issue by eljobe** [github/hub#1466]
I was seriously considering picking up the work of maintaining https://github.com/stephencelis/ghi from @stephencelis and @AlexChesters as they are currently too busy to keep the project humming along.

But, then I noticed that hub (a tool that seems to be under more active development) is beginning to add a feature set which is in competition with (though, markedly behind) the features ghi currently offers.

So, now, I'm considering just spending my time contributing to hub to endow it with all the shiney issue, milestone, label, assignee management features that ghi currently has and just never looking back.

Currently, I think the "release" and "issue" commands in hub are considered (beta.) I just want to make sure that this team is committed to adding a rich set of features around issue, release, milestone, and label management in hub before I offer my spare time to making improvements in those areas.

Let me know and I'll get started soon.

**Comment by mislav** [comment]
Hi @eljobe. If you check out the master branch, you will notice that `hub issue` (now considered a "stable" API) and `hub pull-request` have a lot of features for sorting, assignees, reviewers, labels, etc. What are some other features that you think would belong to hub?

I'd welcome PRs for features after we briefly discuss each feature and decide that it's a good fit for command-line and that it's feasible that it can be implemented.

Also see https://github.com/github/hub/issues/1232

**Comment by eljobe** [comment]
I'm happy to close this issue. I'm just diving into adding the support for the commands I'm missing. But, basically, it's the ability to:
  * [list](https://github.com/github/hub/issues/1280), create, and modify labels
  * list, [create](https://github.com/github/hub/issues/1343), and modify milestones
  * better support for the display of labels on terminals that support 256-bit colors

**Comment by mislav** [comment]
Thanks for sharing your ideas! I'm gonna close this one out in favor of the currently open issues/PRs that you've linked to.
