### ISSUE TITLE
`make test-all` failing with 12 Failures

### ISSUE THREAD

**Issue by eljobe** [github/hub#1468]
I'm on Mac OS X

```
$> git --version
git version 2.8.1
hub version 2.2.9
$> tmux -V
tmux 2.4
$> ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$> go version
go version go1.8.1 darwin/amd64
```

When I run `make test-all` I get:
https://pastebin.com/JYb376id

**Comment by eljobe** [comment]
It turns out that this was due to three different classes of test failures. I was able to solve two of them, but the third one is currently above my level of understanding of the cucumber scenarios:

## Failing Fish Shell Tests
It turns out that the Fish Shell tests were failing because I didn't have the fish shell installed on my Mac. I installed it and discovered that one of the test assertions is not quite correct. So, I fixed it and filed #1471 

I *think* we should file a separate issue though that would just cause a set of scenarios to be skipped if they cannot succeed on the given environment instead of having them fail. It is annoying to have to ensure that these lesser-used shells' tests pass if I want to run any of the completion tests.

## Failing Bash Shell Tests
This one was a huge time-sink. It turns out that whatever distribution of git I'm using on my Mac, it installed its completion scripts in `${GIT_PREFIX}/contrib/completion`instead of any of the places you would expect it to be installed.

I fixed the failures and added some exception-handling to make the problem faster to diagnose in case someone has an even more strange git distribution than mine in the future. See: #1472 

## Failing Scenario: Redirect to another host is not followed

I'm still not sure what's going on here. The output of the failing scenario is:
```
expected: "Error creating pull request: Temporary Redirect (HTTP 307)\nRefused to follow redirect to https://disney.com/mouse\n"
     got: "Error creating pull request: invalid character '<' looking for beginning of value (HTTP 404)\nAre you sure that github.com/mislav/coral exists?\n"
```

I'll see if I can figure out where that last one is coming from, but first a little dinner.

**Comment by eljobe** [comment]
The last test failure (Redirect to another host is not followed) is definitely something specific to my environment on my Mac. I've checked out the project on a linux machine and the test passes.

So, now I'm wondering what is different between my Mac and Linux boxes that could be causing just this one scenario to fail. I'd really appreciate any pointers anyone could give me about what could be different.

**Comment by mislav** [comment]
@eljobe Go changed their redirect behavior in 1.8. The project is expected to be built with Go 1.6. However, if you build it with newer Go, it will be fine for the most part: it's just that this one test will fail.

**Comment by eljobe** [comment]
@mislav, thanks for the pointer. That definitely seems to be the crux of the issue.

It seems that minimally, we should update the README.md to say that you need Go >= 1.6 < 1.8 to build the project.

But, I'm also curious what would be involved in migrating the whole project to Go 1.8? I guess, if this is the only test that's failing, it's probably a matter of just updating that part of our code. Should I take a crack at it?

**Comment by mislav** [comment]
It should be very easy to upgrade to Go 1.8 and I welcome you to try it. However, we would have to get rid of our redirect hacks:

1. The [`CheckRedirect` handler](https://github.com/github/hub/blob/6d695a80b1c38034698ad049f58fca2d5d55cbeb/github/http.go#L157-L170) could probably go away. It was necessary in older Go versions, but Go 1.8 seems to handle redirects better.

2. The [manual 307 redirect](https://github.com/github/hub/blob/6d695a80b1c38034698ad049f58fca2d5d55cbeb/github/http.go#L250-L257) could go away, as Go 1.8 should hopefully repeat a POST request to a new location after a 307.

3. The [specialized error message "refused to follow redirect"](https://github.com/github/hub/blob/6d695a80b1c38034698ad049f58fca2d5d55cbeb/github/client.go#L775-L778) could probably go away. Let's have Go follow all redirects, even to other domains. From what I can see in Go 1.8 mechanism for repeating request headers, it won't ever send an `Authorization` header to a different domain, preventing the leaking of credentials to a 3rd party. 👍

**Comment by eljobe** [comment]
@mislav Thanks for the pointers on upgrading the project to go1.8.1

Take a look at #1475 to see what I did.

**Comment by mislav** [comment]
Thanks for all your pull requests! Closing this in favor of those.
