### ISSUE TITLE
xdg-open is deprecated under gnome 3.24

### ISSUE THREAD

**Issue by toddself** [github/hub#1473]
`xdg-open` has been deprecated in favor of [`gio`](https://developer.gnome.org/gio/stable/) in GNOME.

```
09:10:12 /home/.../src/comparator:timing
↳ hub browse
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.

09:10:16 /home/.../src/comparator:timing
↳ [3248:3312:0509/091016.632518:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.

09:10:19 /home/.../src/comparator:timing
↳ pacman -Q hub
hub 2.2.9-1
09:10:23 /home/.../src/comparator:timing
↳ pacman -Q gnome-desktop
gnome-desktop 1:3.24.1-1
09:10:29 /home/.../src/comparator:timing
↳ uname -a
Linux moe 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
```

**Comment by flying-sheep** [comment]
Ah, let's just wait it out. They'll deprecate gio and switch to something else again soon anyway.

xdg-open is the standard. It works everywhere and should be used by everything that wants to work on more than one desktop environment

**Comment by flying-sheep** [comment]
Actually this is a xdg-open bug (probably caused by gnome breaking some interface again)

https://bugs.freedesktop.org/show_bug.cgi?id=100862

Please don't use gio, people not using gnome don't have it (while everyone has xdg-open, and xdg-open tries to use gio, but the bug makes it fail)

**Comment by toddself** [comment]
I'm totally happy to close this issue and abandon the pull request -- arch has fixed this bug and it no longer warns that the tool has been deprecated.

Sorry for the confusion!

**Comment by flying-sheep** [comment]
thanks for contributing!

hmm, gfvs-open should be patched to say its name in that error message. “this tool” obviously causes trouble

**Comment by timofonic** [comment]
Any news?

**Comment by sethgoldin** [comment]
Hey @flying-sheep, please excuse the newbie question, but how might I get `xdg-utils-1.1.2` or later onto CentOS 7.6.1810? I'm only seeing `xdg-utils-1.1.0-0.17.20120809git.el7.noarch.rpm` right now: http://mirror.centos.org/centos/7/os/x86_64/Packages/

**Comment by flying-sheep** [comment]
No idea, CentOS seems to only have the older version. You could file a bug: https://bugs.centos.org/
