### ISSUE TITLE
System-Wide Shell Configuration Affects Bash Completion Tests

### ISSUE THREAD

**Issue by eljobe** [github/hub#1477]
On a linux box I typically use for development, I noticed that the bash_completion.feature was failing with some unexpected text that talked about how sudo works.

It turns out that on that system, there were some lines in /etc/bash.bashrc which would print out the message if the current user was allowed to sudo and hadn't yet performed a sudo command (as recorded by the presence of a dot file in the home directory of the user.)

Since we give the user a "clean" `HOME` each time we run the script, this message was showing up at the top of the shell session before the prompt (i.e. `$ `)

In the implementation of various `tmux_` methods in ruby, there is an implicit assumption that the first line of output in the tmux pane will be the active prompt line for the user. Obviously, this assumption was violated on my testing box, but I imagine it is the kind of thing that might be pretty common among our fellow developers.

Can we consider enhancing our tests to parse the tmux_pane content and discard everything before the last command prompt?

**Comment by mislav** [comment]
Thanks for reporting! Yes, it would be ideal if the test suite was independent of system-wide configuration. Pull requests welcome.
