### ISSUE TITLE
Remote add -p not work with hub.protocol = https

### ISSUE THREAD

**Issue by wkentaro** [github/hub#1478]
I can't set ssh protocol for remote even if specifying `-p` option explicitly with `hub.protocol = https`.
For me, this is an unexpected. Is this a bug or expected behavior?

```
% hub --version
git version 1.9.1
hub version 2.2.9
```

```
# .gitconfig
[hub]
	protocol = https
```

```bash
% hub remote -v    
origin  https://github.com/jsk-ros-pkg/jsk_recognition.git (fetch)
origin  https://github.com/jsk-ros-pkg/jsk_recognition.git (push)

% echo $GITHUB_USER
wkentaro

% hub remote add -p wkentaro

% hub remote -v             
origin  https://github.com/jsk-ros-pkg/jsk_recognition.git (fetch)
origin  https://github.com/jsk-ros-pkg/jsk_recognition.git (push)
wkentaro        https://github.com/wkentaro/jsk_recognition.git (fetch)
wkentaro        https://github.com/wkentaro/jsk_recognition.git (push)
```

Of cource it works if I removed the config of `hub.protocol` from my `.gitconfig`, but what I want to do is setting `https` as the default and `ssh` with explicit specification.
This is because I want to use `ssh` my local PCs, but don't want to use `ssh` on servers or shared PCs because the sshkey is usually not registered to GitHub.

**Comment by mislav** [comment]
I'm sorry this was unclear. The `-p` never meant "use SSH protocol". It meant "use a writeable protocol" (as opposed to `git:` protocol). In the case then HTTPS is the default, `-p` does nothing and is deprecated. See https://github.com/github/hub/issues/1270#issuecomment-247323843

The solution for you is to do `HUB_PROTOCOL=ssh hub remote add wkentaro`.

**Comment by wpcarro** [comment]
This is unexpected behavior for me as well and the documentation seems to be at odds with what you're saying above. RE docs for `git clone [-p]`:

> Use -p to select the ssh protocol unconditionally.

Is there a way to configure hub to default to the `ssh` protocol? I've tried...

`$ git config --global hub.protocol ssh`

...but that still prompts for my GH creds.

I'm not sure what I'm missing here. I've even tried...

`$ HUB_PROTOCOL=ssh git clone 'user/repo'`

...and this also prompts me for my GH creds. Any pointers would be helpful.

**Comment by mislav** [comment]
@wpcarro Is this the first time you use a hub command, by any chance? On first use, hub (not git) will ask you for your GitHub username and password so it can use the GitHub API. This happens before the repository has even started to be cloned, so it has nothing to do with git's own transport. You only have to do this once.

After that, `HUB_PROTOCOL=ssh git clone user/repo` should definitely use the `ssh` protocol for clone operation, provided that you run a fairly up-to-date version of hub.
