### ISSUE TITLE
Upload File Type Bug on Attach files

### ISSUE THREAD

**Issue by kenijey** [github/hub#1479]
It says "We don't support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or *ZIP*." when i'm trying to upload a .ZIP file. I even tried changing the .zip to .ZIP in my file.

**Comment by mislav** [comment]
Sorry you're having trouble. First I need to understand more about when this error happens. Does this happen on the GitHub.com website when you're creating/editing Releases, or does this happen when you run `hub release create/edit` from the terminal, using the "hub" project?

This issue tracker is just for `hub` on the command-line. General questions about the GitHub.com site should be sent do support@github.com

**Comment by igitur** [comment]
I experience here on Github.com - right here on the issues page. Just tried to upload a small .zip file:

![image](https://user-images.githubusercontent.com/145854/27542600-025535a2-5a88-11e7-829d-0c786a446e2e.png)

**Comment by igitur** [comment]
Request:
```
POST /upload/policies/assets HTTP/1.1
Host: github.com
Connection: keep-alive
Content-Length: 641
Origin: https://github.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
content-type: multipart/form-data; boundary=----WebKitFormBoundaryTNmRh9pcmuKLVKmx
accept: application/json
x-requested-with: XMLHttpRequest
Referer: https://github.com/github/hub/issues/1479
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.8,en-ZA;q=0.6,en-US;q=0.4
Cookie: REMOVED

------WebKitFormBoundaryTNmRh9pcmuKLVKmx
Content-Disposition: form-data; name="name"

freemono.zip
------WebKitFormBoundaryTNmRh9pcmuKLVKmx
Content-Disposition: form-data; name="size"

17385
------WebKitFormBoundaryTNmRh9pcmuKLVKmx
Content-Disposition: form-data; name="content_type"


------WebKitFormBoundaryTNmRh9pcmuKLVKmx
Content-Disposition: form-data; name="authenticity_token"

<removed>
------WebKitFormBoundaryTNmRh9pcmuKLVKmx
Content-Disposition: form-data; name="repository_id"

401025
------WebKitFormBoundaryTNmRh9pcmuKLVKmx--
```

Response:
```
HTTP/1.1 422 Unprocessable Entity
Server: GitHub.com
Date: Mon, 26 Jun 2017 13:57:27 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 422 Unprocessable Entity
Cache-Control: no-cache
Vary: X-PJAX
X-UA-Compatible: IE=Edge,chrome=1
Set-Cookie: REMOVED
Set-Cookie: REMOVED
Set-Cookie: REMOVED
X-Request-Id: f66acff19350be5ccc7f2cc30f2632d2
X-Runtime: 0.135300
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Public-Key-Pins: max-age=5184000; REMOVED
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-rack: 0.138264
X-GitHub-Request-Id: 4463:07F8:5CD9629:8AACE2C:595112C2

{"errors":[{"resource":"RepositoryFile","code":"custom","field":"content_type","message":"content_type is not included in the list"},{"resource":"RepositoryFile","code":"custom","field":"name","message":"name has a file extension that does not match the content type"}]}
```

**Comment by mislav** [comment]
I see. Thank you for all this information! This is really useful.

This looks like a bug on GitHub.com. In the future, such bugs are better reported to support@github.com instead of here. This issue tracker is for a project called "hub" that is a utility that is used on the command-line (in the terminal) and is completely separate from GitHub.com website.

However, now that you've provided us with all this information, I'm going to copy it to our internal issue tracker myself, so you don't have to separately write to support@github.com.

I'd like to ask you for one last piece of information: could you provide us with the actual `.zip` file that fails to upload? If that file contains sensitive information, could you create a new one that doesn't contain anything sensitive, but still fails to upload? If you can't attach the file in this thread due to this bug, then please send it to mislav@github.com

**Comment by igitur** [comment]
I tried to upload a local copy of https://github.com/yaronn/blessed-contrib/blob/master/docs/fonts/freemono.zip

**Comment by mislav** [comment]
@igitur From what I'm seeing, even though its extension is `.zip`, this file is actually a HTML file. Is that correct? That could explain why the server didn't want to accept it, since it only accepts actual `.zip` files that represent a compressed archive format.

**Comment by igitur** [comment]
Arrrgh... My apologies. That was a poor example. And some back luck on my side for choosing that one.

Here is another one (a real .zip file):
https://github.com/paulcbetts/mvvmlight/raw/master/Installer/InstallItems/GalaSoft.MvvmLight.Templates/ProjectTemplates/WPF/Mvvm.WPF.zip

If you'd like the HTTP transaction for this one, let me know.

**Comment by kenijey** [comment]
and also, can you add .log support? it would be EXTREMELY helpful for reporting issues. many of the programs has .log output format of logging, we are using it very often and we've tried from making the .log extension to .txt. please help it, thanks.

**Comment by mislav** [comment]
There is a known issue that `.zip` files cannot be uploaded to GitHub if WinRAR is installed. The presence of WinRAR on the Windows system messes up the `content-type` sent with the request, and the server rejects the file. Could you check for the presence of WinRAR on your system? Unless it is necessary, can you uninstall it and try again?

@kenijey How would you imagine `.log` support for GitHub.com the website? What would be included in the log?

**Comment by kenijey** [comment]
@mislav simply, logs? for example this:
[fml-client-latest.log.txt](https://github.com/github/hub/files/1102637/fml-client-latest.log.txt)
 i just added the .txt extension at the end of the file name by Windows.
we can attach .txt files, but .log files.

**Comment by mislav** [comment]
@kenijey Ah I see. That's a valid point. We'll consider supporting it for upload. For now, you'll need to keep adding the `.txt` extension.

Closing because this issue tracker is not appropriate for tracking GitHub.com website issues, and because the `.zip` problem on Windows is already being tracked internally.

**Comment by igitur** [comment]
@mislav I don't have WinRAR installed. I do have 7-zip installed, if that's relevant. I'm happy to continue this via the emails you mentioned above, if you wish.

**Comment by HannanAkbar** [comment]
Is it fixed? I'm facing the same issue.

**Comment by FailedShack** [comment]
Just had this issue as well. Had to wait for it to upload only to be rejected.

**Comment by rodriguez7612** [comment]
[Copy of at_radarMar_2019.txt](https://github.com/github/hub/files/3366078/Copy.of.at_radarMar_2019.txt)
Bug

**Comment by fireattack** [comment]
I followed the steps at https://github.com/github/hub/issues/1479#issuecomment-401191548

The form data has it as "video/zip".
I do have Winrar installed.

Is there any chance to fix this issue without asking the user to uninstall WinRar (it is essential for my workflow since I use their RR.)

Thanks!

**Comment by karna419** [comment]
Issue persists for me. In request header `Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryi8ZTnCtxJk80BAWu
`. In Form Data section `Content-Type: image/jpeg`. I am getting a Bad Request 400 error while uploading an image from mac.

**Comment by pkeir** [comment]
When I drag a file from my Ubuntu `/tmp` directory, the message is `This file is empty. Try again with a file that's not empty.`.

**Comment by sergyv** [comment]
I still have this problem

**Comment by kamalsahu0001** [comment]
[dump.zip](https://github.com/github/hub/files/7494312/dump.zip)
[log.zip](https://github.com/github/hub/files/7494314/log.zip)
[proc.zip](https://github.com/github/hub/files/7494316/proc.zip)
[sai.zip](https://github.com/github/hub/files/7494319/sai.zip)
[warmboot.zip](https://github.com/github/hub/files/7494321/warmboot.zip)

**Comment by kamalsahu0001** [comment]
Giving error "is not included in the list" error while trying to upload the TS zip file, so uploaded individual folders.

**Comment by kamalsahu0001** [comment]
[sonic_dump_sonic_20211108_051740.tar.gz](https://github.com/github/hub/files/7494458/sonic_dump_sonic_20211108_051740.tar.gz)

**Comment by gardotd426** [comment]
I'm getting this same issue with a tar.gz file.

**Comment by ahsf** [comment]
> Giving error "is not included in the list" error while trying to upload the TS zip file, so uploaded individual folders.

same here

**Comment by obviousaurus** [comment]
I'm getting this same issue when I compress an MP3 file

**Comment by fabrizioschiano** [comment]
I am having the same issue when trying to attach a txt file.

**Comment by crliu95** [comment]
I am having the uploading issue, which shows "is not included in the list" under the dialog box after I try to upload the zip file.

**Comment by dlech** [comment]
> I am having the uploading issue, which shows "is not included in the list" under the dialog box after I try to upload the zip file.

I see the same error message, but looking at the response in the web developer tools, the error is actually because of the size. I was trying to upload a file larger than 10MB. The error message is just wrong.

**Comment by jf-london** [comment]
As above - I've tried to attach a .gz or .zip file generated on Linux of a simple tree of about 8 files, totalling no more than 1.5 meg compressed with standard (shell) tar, and zip or gzip. Neither will upload from a late firefox version with no funny plugins or whatever. I receive the same response as others above "Something went really wrong..."

**Comment by cponder** [comment]
I'm having the same problems:
```
is not included in the list
```
It looks like this message is not formed correctly, what is the "" that's not included in what list?
Also, is there another upload channel that we can use here?

**Comment by GalGreenfield** [comment]
> I'm having the same problems:
> 
> ```
> is not included in the list
> ```
> 
> It looks like this message is not formed correctly, what is the "" that's not included in what list? Also, is there another upload channel that we can use here?

I have the same issue.

**Comment by Daksh777** [comment]
I have the same issue as well

**Comment by ishikmat** [comment]
I encountered the same problem `is not included in the list`. 
but, I realized it cause by file size in my case.


>The maximum file size is:
10MB for images and gifs
10MB for videos uploaded to a repository owned by a user or organization on a free GitHub plan
100MB for videos uploaded to a repository owned by a user or organization on a paid GitHub plan
25MB for all other files

**Comment by ishikmat** [comment]
from f12 debugmode,
we can see error in you case,
if you stop below line as debug mode.

assets/app/assets/modules/github/upload/batch-upload.ts

line:213
`const trimSizeErrorMessage = (message: string) => {
  return message.startsWith('size') ? message.substring(5) : message
}`


message returned as
`"size is not included in the list"`
but, above line:213,
by substring method, then "size " are excluded
`"is not included in the list"`

### error code
Failed to load resource: the server responded with a status of 422 ()

**Comment by JohnGurin** [comment]
Cannot attach `.tgz` file in the comment. The same `.tar.gz` works

**Comment by JohnSmith25** [comment]
I cannot upload zip files either when I make a zip file on linux.

**Comment by wblangdon** [comment]
Ok I can see a need for file upload size limits, but it would be simpler to remove all restrictions on file type.
Bill
