### ISSUE TITLE
Resetting credentials isn't obvious

### ISSUE THREAD

**Issue by joncalhoun** [github/hub#1484]
It took some digging to realize that if I wanted to delete my existing credentials (they were invalid) so that hub would work again I needed to delete the `~/.config/hub` file. 

It would be nice if this were either:

1. Documented better, or
2. A command in hub (eg `hub logout`)

**Comment by mislav** [comment]
Sorry for the trouble! This will be made better after ideas in #225 ship. I'm aware of the various authentication troubles that people run into and I'd like this to be easier, too.
