### ISSUE TITLE
Parse assignees from pull request and assign

### ISSUE THREAD

**Issue by ssorallen** [github/hub#1485]
Currently I create pull requests with `hub pull-request` and then open the PR on github.com to assign them. Hub could parse well-formatted Assignees and assign without going to the web interface.

Currently the first line is the title and the rest of the body is the description when using `hub pull-request`. It could append supported values and attempt to parse them like the following:

```
Foo bar baz

This is a foo bar baz commit message

Assignees:
# Requesting a pull to foo:master from foo:bar
#                                                                                                                                                       
# Write a message for this pull request. The first block                                                                                                
# of text is the title and the rest is the description.                                                                                                 
#                                                                                                                                                       
# Changes:                    
#
# abc (Foo Bar, 1 day ago)
#    Foo bar baz
```

If "Assignees:" is present, it could parse the text following it (up until a line break) as a comma-separated list of GitHub user names and assign the PR via [POST /issues/:number/assignees](https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue). This could be generalized to more attributes like Labels and Projects.

**Comment by mblair** [comment]
@ssorallen I'm not sure if this is in a released version yet, but `hub pull-request` supports the `-a` option for specifying assignees on the command line:

https://github.com/github/hub/blob/master/commands/pull_request.go#L63

**Comment by ssorallen** [comment]
@mblair I don't have that version yet, but that's great! Thanks for pointing that out.

**Comment by ssorallen** [comment]
I'll close this since it seems like a largely similar feature is already complete.
