### ISSUE TITLE
oauth with ~/.config/hub not working

### ISSUE THREAD

**Issue by adibPlaybuzz** [github/hub#1488]
I created an oauth token (github web settings) - however hub pull-request still asks for my credentials.
is it related to the fact that my remote origin configured with ssh (not https)?

**Comment by glukki** [comment]
Had the same problem. Changing remote to git protocol solved it.

**Comment by spott** [comment]
@glukki:

It seems to fix it *sometimes*, but not always.

**Comment by mislav** [comment]
@adibPlaybuzz Make sure that you're on the latest version of hub, and that your `~/.config/hub` looks like this:

```yaml
github.com:
- user: mislav
  oauth_token: PASTE_YOUR_TOKEN_HERE
  protocol: https
```

You should not be asked for authentication past that point.

Also note that hub authentication is completely separate from git authentication (which can be done either over SSH or HTTPS). Even though authentication for git cloning/pushing is already set up on your machine, you still need to complete hub authentication additionally.

**Comment by spott** [comment]
@mislav I'm using hub version 2.2.9 (from home-brew), and my `~/.config/hub` looks like that.

>complete hub authentication additionally.

What is "hub authentication".  Are you referring to authenticating with GitHub for issues and such and with Git for push/pull etc?

**Comment by mislav** [comment]
@spott Then hub authentication should be all configured for you and ready to go.

Are you connecting to GitHub Enterprise instance by any chance? What are the exact errors that you're getting?

**Comment by moofish32** [comment]
This helped me resolve my issue with the config file. Suggest we close this as the bug appears to be user error.

**Comment by JavierJincheng** [comment]
> @adibPlaybuzz Make sure that you're on the latest version of hub, and that your `~/.config/hub` looks like this:
> 
> ```yaml
> github.com:
> - user: mislav
>   oauth_token: PASTE_YOUR_TOKEN_HERE
>   protocol: https
> ```
> 
> You should not be asked for authentication past that point.
> 
> Also note that hub authentication is completely separate from git authentication (which can be done either over SSH or HTTPS). Even though authentication for git cloning/pushing is already set up on your machine, you still need to complete hub authentication additionally.

Thanks. 
When I follow this `~/.config/hub`
```yaml
 github.com:
 - user: mislav
   oauth_token: PASTE_YOUR_TOKEN_HERE
   protocol: https
```
It works. Please do not miss the `-`.
PS: I use the GitHub enterprise(github.org.com)

**Comment by dmitryrn** [comment]
I did not find an example of `~/.config/hub` at [docs](https://hub.github.com/hub.1.html) and was forced to googling about how to properly use `oauth token` with `hub`. Maybe add so info about it to the docs?
