### ISSUE TITLE
`hub fork` fails if fork (and remote) already exists

### ISSUE THREAD

**Issue by jasonkarns** [github/hub#1499]
While attempting to replicate the issue I _thought_ I was seeing for https://github.com/github/hub/issues/1411#issuecomment-311148349, I uncovered a teeny quirk with how `hub fork` behaves for existing forks.

- If fork does not exist: `hub fork` creates the fork on github, adds the remote for the new fork, and fetches. Returns 0 status.

- If fork exists but remote doesn't: `hub fork` adds the remote for the fork and fetches. Returns 0 status.

- If fork exists and remote exists: `hub fork` errors out with `fatal: remote jasonkarns already exists`

Given that forking an already-forked repo safely adds the fork as a remote, I'd _kinda_ expect the last scenario to just trigger a fetch. That is, I'd expect all three scenarios above to result in a local clone with: 

1. named remote for the fork
3. remote recently fetched
4. successful return code

Right now, only the first two scenarios do this. (The third just needs to do a fetch and exit cleanly.)

I have a hard time describing the second scenario above (fork exists, but remote doesn't), but it's like a partially-idempotent command. If the third scenario were implemented as requested, the `hub fork` command would be fully idempotent.

**Comment by mislav** [comment]
What you're describing makes sense. I'd accept a PR that makes the command idempotent, since it's already half-idempotent.

**Comment by e-beach** [comment]
It's odd that version 2.3.10 of hub behaves slightly differently than the release version. In this case, the pre-release version does not show an error message, but does exit with an error status.
```
# both fork and remote already exist

$ hub-2.3.10 fork
$ echo $?
128
$ hub-2.2.9 fork
fatal: remote e-beach already exists.
$ echo $?
128
```

**Comment by e-beach** [comment]
The change in behavior occurs in d937d287037b9a24022e16337ea5e06ffdc726ab. It looks like the change to console file descriptors in that commit is somehow broken.

**Comment by jasonkarns** [comment]
woot!, thanks @e-beach
