### ISSUE TITLE
Could 'pr checkout' use a more meaningful name for the newly created branch?

### ISSUE THREAD

**Issue by njsmith** [github/hub#1500]
`pr checkout` is awesome! But... if I do `hub pr checkout 123`, then I get a local branch named like `ORIGINALSUBMITTER-THEIRBRANCHNAME`. And as a maintainer, neither of these strings are particularly meaningful to me, and don't make it easy to find this branch later. I would prefer if the local branch were named like `pr-123`, or perhaps `pr-123-ORIGINALSUBMITTER-THEIRBRANCHNAME` if you want to keep that information around.

**Comment by mislav** [comment]
Thank you for the praise! You can specify the branch name yourself by passing in an extra parameter: `hub pr checkout 123 my-branch-name`. However, if you want to specify some kind of template as default, for instance `pr-{num}-{owner}-{branch}`, that's still not possible. Do you think such a feature would be useful?

Here's the thing about default branch names: I was thinking of changing the default from `{owner}-{branch}` to just `{branch}`. This won't make the branch any easier to find among your other local branches, but it would allow you, as a maintainer, to push new commits to somebody's branch in their fork (this level of access is enabled by default when people create new PRs via the web interface) by simply doing `git push`. This is being discussed in https://github.com/github/hub/issues/1495#issuecomment-310065377. What do you think about this?

**Comment by njsmith** [comment]
Responded in #1495

**Comment by mislav** [comment]
Closing this in favor of the larger conversation in the referenced ticket. Thanks for participating!
