### ISSUE TITLE
Windows Go install

### ISSUE THREAD

**Issue by ofek** [github/hub#1504]
I'm not too familiar with Go's tooling. When I do `go get github.com/github/hub` it says `go\src\github.com\github\hub\commands\apply.go:8:2: found packages github (branch.go) and commands (reset_console_windows.go) in C:\Users\Ofek\go\src\github.com\github\hub\github`.

**Comment by kitsuphat2528** [comment]
Ok

**Comment by ofek** [comment]
Fixed by #1505
