### ISSUE TITLE
git's commentChar=auto option is not handled well 

### ISSUE THREAD

**Issue by mareksuscak** [github/hub#1512]
Here's a comment generated by running `hub pull-request`:

![image](https://user-images.githubusercontent.com/613647/28341145-a6d7fcfe-6c12-11e7-887b-c866e86d47e4.png)

**Comment by mislav** [comment]
Thank you for reporting! I didn't know about `auto` being a special value. From git documentation:

> If set to "auto", git-commit would select a character that is not the beginning character of any line in existing commit messages.

We need to somehow implement this to restore compatibility.

**Comment by e-beach** [comment]
I was looking into this issue, and I noticed that `hub` will not apply changes to `~/.gitconfig` immediately. I.e., I change the `commentChar` in gitconfig, make the `hub pull-request` command a couple of times, but the comment character only changes after a few issues of the command. Is this desired behavior?

**Comment by e-beach** [comment]
By the way I've started working on this. I'm currently looking at the Git implementation of selecting the character, so we match, I hope to have a PR this week.

I guess we implement by parsing `git rev-list --no-merges HEAD` and looking for a comment char that isn't used.

**Comment by mareksuscak** [comment]
@e-beach 

Check this out: https://github.com/git/git/blob/117ddefdb4dfd9b40ae60967a7327754d8ce7a87/builtin/commit.c#L631

Seems like they generate a commit message (empty or using a template) incl. the remarks and the diff. All that is stored in the `sb` var. Then they go through the list of candidate comment chars (`#;@!$%^&|:`) and look for a line break immediately followed by a given comment char. Then they change the comment line char accordingly to the results of the algorithm.
