### ISSUE TITLE
Pull Request - Invalid Option `-c`

### ISSUE THREAD

**Issue by cocotutch** [github/hub#1513]
In your `pull-request.go` file detailing the possible usage of the `pull-request` command, there is detailed a `-c, --copy` parameter which is said to output the resulting pull-request URL to `pbcopy`/aka the clipboard.

I have attempted to use this to no avail. It has either been deprecated, or is not yet implemented. I suggest the documentation get updated to reflect this. 👍

**Comment by mislav** [comment]
You're looking at `pull-request.go` from the latest master branch. This is not guaranteed to correspond to the latest stable released version. In fact, the state of the master branch is only packaged up as a pre-release version, available from the Releases page. If you grab those precompiled binaries, you will have the `-c` flag.
