### ISSUE TITLE
Build fails on linux when install has windows line endings.

### ISSUE THREAD

**Issue by HarrySarson** [github/hub#1514]
I am running Bash on Windows and cloned the hub repo with windows line endings as I stored it in the windows part of my hard drive.

When I ran `make` the script failed with an non intuitive error message which I tracked down to the presence of `\r`'s in the ./script/build file (and also in other files).

Running `dos2unix` solved the problem but I thought it worth flagging up as I don't think this is a work flow unique to me.

It may be worth adding a catch for this and producing a more helpful error message.

**stack trace:**

```
$ make install prefix=/usr/local                                          
script/build: line 9: $'\r': command not found                            
: invalid optionne 10: set: -                                             
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]      
script/build: line 11: $'\r': command not found                           
script/build: line 14: $'\r': command not found                           
script/build: line 15: syntax error near unexpected token `$'{\r''        
'cript/build: line 15: `setup_gopath() {                                  
script/build -o bin/hub                                                   
script/build: line 9: $'\r': command not found                            
: invalid optionne 10: set: -                                             
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]      
script/build: line 11: $'\r': command not found                           
script/build: line 14: $'\r': command not found                           
script/build: line 15: syntax error near unexpected token `$'{\r''        
'cript/build: line 15: `setup_gopath() {                                  
make: *** [bin/hub] Error 2                                               

```

**Comment by mislav** [comment]
This has some up before. However, I don't know how to fix it. Bash scripts shouldn't have windows line endings. Do you have any suggestion how to detect this?

**Comment by HarrySarson** [comment]
hmm, I had a similar issue in another repository and did some more digging.

You can overwrite the users `core.autocrlf` settings for a repository in the `.gitattribute` file. Moreover you can do so by matching against patterns. Therefore, all the `*.sh` files could be set to use the linux line endings regardless of the users global settings.

I can't conceive of any user expecting to have windows line endings in a bash script file and it would allow the repository to build when people - like me - clone with silly settings.

**Comment by mislav** [comment]
Would you submit a PR that adds a `.gitattribute` file instead of changing our build scripts?

**Comment by HarrySarson** [comment]
Yep, can do :) will be Tuesday evening probably.

**Comment by mislav** [comment]
Thank you for https://github.com/github/hub/pull/1557!

**Comment by yubing24** [comment]
It could be file encoding. Windows encodes the new line character differently from Linux. I converted file encoding to ASCII and things would work again.
