### ISSUE TITLE
Unable to assign multiple users to PR (v. 2.3.0-pre10-9)

### ISSUE THREAD

**Issue by hjdarnel** [github/hub#1515]
Currently unable to assign multiple users to a review using Hub. My PR command is follows:
`git pull-request -a user1, user2, user3, user4, user5 -b develop`

Only user 1 is assigned to the PR, which is created successfully. Am I misformatting my command?

Thanks.

**Comment by mislav** [comment]
The documentation says:

```
	-a, --assign <USERS>
		A comma-separated list of GitHub handles to assign to this pull request.
```

So, the `-a` flag accepts a single argument which is a comma-separated list of usernames. When it says "comma-separated", it means just a comma, not a comma plus space.

When you passed `-a user1, user2, user3, user4, user5` to hub, you basically only passed `user1,` as the value of the `-a` parameter, and `user2, user3, user4, user5` were treated as separate arguments that simply got ignored. This is just how word-splitting in a shell like bash works.

The correct way is to pass `-a user1,user2,user3,user4,user5`, or to specify `-a` multiple times: `-a user1 -a user2 -a ...`.
