### ISSUE TITLE
--show-pulls and/or --include-pulls are unknown

### ISSUE THREAD

**Issue by NKjoep** [github/hub#1527]
Given: 

```
$ hub --version
git version 2.13.2
hub version 2.2.9
```

when calling `hub issue --show-pulls` or `hub issue --include-pulls` I get:

```
unknown flag: --show-pulls  # or include-pulls
usage: git issue
```

What am I doing wrong? Thanks

**Comment by e-beach** [comment]
You need to use hub 2.3.0-pre9 https://github.com/github/hub/releases/tag/v2.3.0-pre9.

**Comment by NKjoep** [comment]
Aww! I couldn't find that information anywhere :) thank you!

**Comment by mislav** [comment]
Thanks @e-beach! @NKjoep: you can close your own issue once it's resolved.
