### ISSUE TITLE
Tab completion for branch name prints "warning: ignoring broken ref"

### ISSUE THREAD

**Issue by jasonkarns** [github/hub#1534]
Attempting to tab-complete the base branch name:

```bash
hub pull-request -o -b or<TAB>
```
results in:
```bash
hub pull-request -o -b orwarning: ignoring broken ref refs/remotes/origin/HEAD
```

```
$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
[snip]
$ hub --version
git version 2.13.3
hub version 2.2.9
```

**Comment by e-beach** [comment]
Are you sure that this is an issue with hub? This can also happen with git, as in https://stackoverflow.com/questions/34990734/how-to-fix-warning-ignoring-ref-with-broken-name-in-git.
I would suspect this is a git problem as I don't believe `hub pr` is a command in that version of hub.

**Comment by jasonkarns** [comment]
I have an alias of `pr` to `pull-request`. (editing original post now, to avoid confusion) It's possible that the warning message is coming from git, but only the authors of hub would know. The command I'm invoking is `hub`, so the issue starts here.
