### ISSUE TITLE
Error creating pull request: Unauthorized (HTTP 401) with GitHub Enterprise

### ISSUE THREAD

**Issue by denizsokullu** [github/hub#1539]
Hi,

I don't know what password I should be using for the authentication when I am under an enterprise. I tried my company account password(of course didn't work), and I also tried a PAT(personal access token) but that also didn't work. What should I be doing?

Thanks

Edit:My company uses SAML authentication.

**Comment by ipince** [comment]
@denizsokullu 
Did you get this to work?

I'm seeing the following error:
```
Error creating pull request: Forbidden (HTTP 403)
Resource protected by organization SAML enforcement. You must grant your personal token access to this organization.
```
when running `hub pull-request`.

I've already authenticated my ssh key with SSO. For example, I can `git push` to a branch in my organization's repo with no problem.  I don't understand why `hub` doesn't work.

**Comment by mislav** [comment]
@ipince If you go to `https://YOURDOMAIN/settings/tokens`, you should see a view like this where you can grant the token access to specific orgs:

<img width="775" alt="screen shot 2018-10-02 at 9 59 52 am" src="https://user-images.githubusercontent.com/887/46364224-151dca00-c62a-11e8-9828-459dd0240a60.png">

If that doesn't work, please give us more information about which steps you tried and your GHE version. Thank you!

**Comment by denizsokullu** [comment]
Thanks so much for replying, I had this fixed. @mislav the solution is exactly yours. Thanks again.

**Comment by ipince** [comment]
Thanks for replying, @mislav .

I have already done what you suggested, but `hub` still doesn't work.

How can I find out which ssh key `hub` is trying to use? Maybe it's using the wrong one.

BTW:
```
git push
```
does work. Initially, it didn't, but after enabling my key for SSO (as you indicated above), it worked.

But `hub` does not. This is what leads me to believe that maybe `hub` is using a different ssh key...

**Comment by ipince** [comment]
```
$ hub --version
git version 2.9.3 (Apple Git-75)
hub version 2.2.9
```

**Comment by ipince** [comment]
Ah, my bad.

I had authorized my *ssh key*, not my *personal token*.

It works now, thanks!
