### ISSUE TITLE
`hub pull-request` should allow a different default branch to be set

### ISSUE THREAD

**Issue by wagenet** [github/hub#154]
Right now it's hardcoded to default to "master".

https://github.com/defunkt/hub/blob/master/lib/hub/commands.rb#L118
https://github.com/defunkt/hub/blob/master/lib/hub/context.rb#L149

**Comment by danielcompton** [comment]
For future searchers (as this is top of Google), to set the correct branch:

```
git remote set-head origin <new-branch>
```

**Comment by chris-fa** [comment]
Or you can run `git remote set-head origin -a` to have it automatically determine what's the correct base branch.

**Comment by csaska** [comment]
This doesn't seem to work when I create the pull-request from a worktree; however, if I switch back to the original clone, the command works perfectly.

**Comment by csaska** [comment]
This doesn't seem to work when I create the pull-request from a worktree; however, if I switch back to the original clone, the command works perfectly.

From the worktree, I see the following:
```json
{"base":"master","head":"pHWChip:feature/colt_testing","maintainer_can_modify":true,"title":"Testing"}
```

From the original clone, I see the following:

```json
{"base":"core_master","head":"pHWChip:feature/colt-testing-2","maintainer_can_modify":true,"title":"Testing"}
```
