### ISSUE TITLE
Cannot delete Issues or silently delete comments

### ISSUE THREAD

**Issue by moeiscool** [github/hub#1540]
I am the repo owner of the link posted below. As you can see users are posting in the issues when I gave the guideline they shouldn't unless it's a bug with the software.

There is no delete button for the thread and there is no way to silently delete spam comments. Attempting to do any of this leaves the owner or collaborator looking as if they are attempting to hide something.

I am simply trying to maintain my project. Please let me know how I can delete the thread. I don't want to turn off the Issues section but it's either that or leave github...

https://github.com/moeiscool/Shinobi/issues/261

**Comment by e-beach** [comment]
Are you looking to report an issue in the GitHub web interface itself? This repository is for a command-line client to GitHub.

**Comment by moeiscool** [comment]
my apologies :sweat_smile: i do what I want to stop. Yes it is about the interface, I will keep digging hopefully I strike gold soon.

**Comment by mislav** [comment]
Thanks @e-beach. @moeiscool: GitHub tries to combat spam as best as possible. Sometimes it takes a little bit until someone's account is flagged as spam and those threads removed. It helps if you navigate to someone's user account on GitHub and use the link to report them for spam.

If you have future questions or concerns about GitHub, please write to support@github.com. Thank you!
