### ISSUE TITLE
Error despite being authenticated - remote: Invalid username or password

### ISSUE THREAD

**Issue by Ateo88** [github/hub#1543]
Hi all,

Been having trouble fetching my private repositories since last week, despite being authenticated. The following error occurs:
git -c diff.mnemonicprefix=false -c core.quotepath=false fetch origin
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gaziagames/hero-royale-client/'
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gaziagames/hero-royale-client/'
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gaziagames/hero-royale-client/'
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gaziagames/hero-royale-client/'

This doesn't usually happen. I'm not too familiar with GitHub (as I'm a game artist), but everything including my username and password checks out under the Options menu. Is there something I am missing here?

**Comment by mislav** [comment]
Hi @Ateo88, I'm sorry that you're having trouble.

You are asking at the wrong place. This is a project called "hub" which is a command-line tool that wraps `git`. Unless you've ever installed something called "hub", my guess is that you're having trouble with having ordinary git fetching code from GitHub, and if so, you should ask on the official GitHub support channel by writing to support@github.com.

When writing to them, please also tell them your `git config credential.helper` value (if any), and include information about the OS that you're using and how did you set up authentication with GitHub in the first place (if you remember). It often helps to clear out any saved/cached passwords and authenticate again with your latest GitHub username and password.

Good luck!
