### ISSUE TITLE
Issue with own PRs for CODEOWNER

### ISSUE THREAD

**Issue by sandiprb** [github/hub#1546]
Scenario:
It doesn't allow editors to merge my pull request w/o CODEOWNER (in the case, it's me) approval, it also doesn't let me approve since I've raised the PR :confused:

**Comment by mislav** [comment]
@sandiprb Hi, it sounds like you have an a problem with GitHub itself, and this is an issue tracker for a command-line tool called "hub". For GitHub-related issues, please write to support@github.com

**Comment by sandiprb** [comment]
@mislav  yes connected with them on the given email. My bad, posted it here, sorry to bother.
Thanks :smile:
