### ISSUE TITLE
HUB_VERBOSE environment variable is undocumeneted

### ISSUE THREAD

**Issue by e-beach** [github/hub#1551]
The HUB_VERBOSE environment variable, which causes network requests and git commands executed by hub to be logged to stdout, is useful for both contributors and end-users. For contributors, it is obviously useful for debugging, but it is also useful for users who want to understand the commands that hub executes, especially when hub behaves unexpectedly.

I was only able to discover this variable by looking through commands.go:

https://github.com/github/hub/blob/a45f4573a32e346d7046b47657263cd17cb60c9e/cmd/cmd.go#L111-L119

Would it be appropriate to document it in the contributing guide?

**Comment by mislav** [comment]
Yes it would absolutely be useful to document it both in the contributing guide and the man page. Thank you for suggesting

**Comment by coleGillespie** [comment]
it is still a bit confusing in the documentation. i was not sure what to set it to. it looks like i can set it to anything other than empty string. i spent more time that i should have trying to figure that out.
