### ISSUE TITLE
How can I pull request without fork original project?

### ISSUE THREAD

**Issue by eromoe** [github/hub#1553]
Document doesn't say I have to fork first, but it looks like need.

A lot of tutorials , examples are like 

http://sangsoonam.github.io/2017/02/01/create-pull-request-hub.html

```
❯ git co -b feature_branch
# Modify the code
❯ git add .
❯ git commit
❯ git push  (can not push)
# Create a pull request using hub
❯ git pull-request
```

If do as this would get

```
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```
I think it is due to permission problem
https://github.com/github/hub/issues/1258
https://github.com/github/hub/issues/1518

-------------------

I want to say, the normal scene I make pull request is when I see some project has bug and it is easy to fix.
If only change one file, I'd like to edit on web(it is convenient to pull-request just one file).  When there are several files, it become complex.  I have to fork the project,  clone it , make edit,  go to webpage make pull request, then I tend to delete the fork.

What I love to is :

1.  clone  a project ( I don't have permission )
2. make change
3. hub pull-request

Can I use hub to do such thing? if not,  would you add this feature?

**Comment by mislav** [comment]
You can't open a pull request without forking the original project.

The way it works on the GitHub web interface is that, when you edit someone else's file in a browser, GitHub automatically creates your fork in the background.

With hub, you have to use `hub fork` before using `hub pull-request`. This is [outlined in the docs](https://hub.github.com/):

```sh
# Example workflow for contributing to a project:
$ git clone github/hub
$ cd hub
# create a topic branch
$ git checkout -b feature
# ( making changes ... )
$ git commit -m "done with feature"

# It's time to fork the repo!
$ git fork
# (forking repo on GitHub...)
# git remote add YOUR_USER git://github.com/YOUR_USER/hub.git

# push the changes to your new remote
$ git push YOUR_USER feature
# open a pull request for the topic branch you've just pushed
$ git pull-request
# (opens a text editor for your pull request message)
```

In the future, hub might auto-create a fork for you, but for now, you have to invoke one extra command yourself.

**Comment by mislav** [comment]
@masaeedu You can of course create a PR for your own repo. You don't need to create a fork. You just need to create a new branch:

```sh
# in your project's directory:
git checkout -b my-feature
git commit -m "my new feature"
git push -u origin HEAD

hub pull-request # creates a PR with `my-feature` as head branch
```

**Comment by muescha** [comment]
@mislav i think your code snipped should updated with:

```diff
 # Example workflow for contributing to a project:
 $ git clone github/hub
 $ cd hub
 # create a topic branch
 $ git checkout -b feature
 # ( making changes ... )
 $ git commit -m "done with feature"
 
 # It's time to fork the repo!
-$ git fork
+$ hub fork
 # (forking repo on GitHub...)
 # git remote add YOUR_USER git://github.com/YOUR_USER/hub.git

 # push the changes to your new remote
 $ git push YOUR_USER feature
 # open a pull request for the topic branch you've just pushed
-$ git pull-request
+$ hub pull-request
 # (opens a text editor for your pull request message)
```

**Comment by akashverma** [comment]
> You can't open a pull request without forking the original project.
This was a much needed comment as I had been trying to raise a PR in my own repository. But I hadn’t forked it. Hence just wasn’t getting an option to open a PR although my commit contained changes in the existing file.

So it means if we wanna open a PR on github then we have to have a fork of the original repo. 
Note:- I have also used. GitLab and I guess the same is not the case there. please correct me if I'm wrong. Thanks.

**Comment by tv42** [comment]
I would make more drive-by contributions for simple things if it didn't mean littering my account.

**Comment by marcone** [comment]
> I would make more drive-by contributions for simple things if it didn't mean littering my account.

This. Even just being able to create a pull request by uploading a patch file would be good.

**Comment by lawrence-dol** [comment]
Another hearty yeah and amen! here -- I would make many more small contributions to OS if I could simply pull down the repo, branch and make a pull request without forking a copy into my own account, or do the equivalent online.

Would it not also avoid the confusion caused by dozens of forks on dead project trying to determine if someone else has taken it over, if forks only occurred to actually fork the project instead of needing one to contribute to an existing project. Surely it would save a sh!t-ton of disk space and activity for GitHub too?

**Comment by eobet** [comment]
I have to add to this as an artist, not a coder (because this came up on a Google search), it's super confusing to have to fork first.

Not only that, but when I wanted to contribute more than one thing, seems I have to make more forks? It's too advanced for me and it drives me away from contributing.
