### ISSUE TITLE
Label colors don't render even close to correctly in Terminal.app

### ISSUE THREAD

**Issue by eljobe** [github/hub#1560]
With the `hub isssue -l config` command, the output looks like this:
![image](https://user-images.githubusercontent.com/679924/30003688-b3dcbcd6-90c1-11e7-8851-3f05b403b1bb.png)

The same repo with `ghi list --label config` looks like this:
![image](https://user-images.githubusercontent.com/679924/30003702-eea17f96-90c1-11e7-84a0-ddb1ba1fc259.png)

**Comment by eljobe** [comment]
So, on doing a bit more research, it looks like Terminal.app doesn't support 24bit color. `ghi` just converts any label colors which aren't in the 256 color palette into one that is in that palette.

Unfortunately, it is not possible to detect if the terminal supports 24bit color or not. So, we either have to ask users to set some environment variable or configuration variable to tell hub that they want to use 24bit color, or we have to similarly change whatever color we get from the label's hex color into one in the 256 color palette.

Or, we could just assume that every terminal is supports 24bit color and carry on like that's true.  Thoughts on how best to proceed?

**Comment by eljobe** [comment]
Okay. So, now I'm thinking of starting a project just to write a golang version of [supports-color](https://github.com/chalk/supports-color/blob/master/index.js) from the world of `node.js` doesn't seem like it should be too terribly difficult, and it would allow us to make a smarter decision about how to display colors in `hub` and other go command-line tools.

**Comment by mislav** [comment]
> So, now I'm thinking of starting a project just to write a golang version of [supports-color](https://github.com/chalk/supports-color/blob/master/index.js) from the world of `node.js`

Sounds good! I wouldn't mind if a simpler check for iTerm vs. Terminal.app was inlined in this project for the purpose of converting 256 colors into "simple" ones.
