### ISSUE TITLE
Website design update

### ISSUE THREAD

**Issue by JasonEtco** [github/hub#1564]
Hey folks 👋 

The GitHub design visual language has evolved so much since `hub` was first created, and I think that [the public website](https://hub.github.com) deserves some love. I'm sure that people come to the site and think "Hey this doesn't look very legit" or "How can I trust this, it doesn't even look like GitHub."

I'd like to give it some attention and pull in [Primer](https://github.com/primer/primer-css) for some added GitHubb-y-ness. I believe the repo for the site itself is private; is there a reason for that? Or, if I'm wrong, then I'm having trouble finding the relevant files in this repo.

**Comment by mislav** [comment]
You're welcome to take a stab at making the website better! I like the idea of using Primer for "GitHubbyness".

The repo for the site isn't private— [you're looking at it](https://github.com/github/hub/tree/gh-pages).

**Comment by JasonEtco** [comment]
Ah, I didn't check the `gh-pages` branch. In that case, I'll make it happen 👍

**Comment by hkdobrev** [comment]
> "Hey this doesn't look very legit" or "How can I trust this, it doesn't even look like GitHub."

@mislav I think the repo URL should also be changed to https as it already redirects there.

**Comment by mislav** [comment]
Closing in favor of the referenced PR.
