### ISSUE TITLE
Feature Request > Ability to get download count on individual files in a repo 

### ISSUE THREAD

**Issue by mitchellkrogza** [github/hub#1567]
It would be great to have a feature to be able to track how many times a particular file in a repo is downloaded. I know this can be done on counting releases downloads but I have a repo where a single .conf file gets pulled daily by users using an update script for the project. Being able to see how many times a day/week/month this file is being requested would be a great way to show live users on the project.

**Comment by mislav** [comment]
Hi @mitchellkrogza, it sounds like you have a feature request for GitHub.com itself, not for the `hub` command-line utility that this project and issue tracker is about. You should instead send such requests directly to GitHub Support at support@github.com, not to this repo. This project is only about the command-line utility called `hub`. Thank you!

**Comment by mitchellkrogza** [comment]
Thanks @mislav I will email them but I think I figured out a way to track this through my own update script. Will see if I can follow that avenue first to track these downloads. Thanks for your help.

**Comment by Akash-L** [comment]
@mitchellkrogza 
can you please tell how you were able to do ?
