### ISSUE TITLE
SHA256 mismatch when brew installing --devel

### ISSUE THREAD

**Issue by jcjl013** [github/hub#1568]
I successfully installed hub 2.3.0-pre10 with `brew install --devel hub` on Friday, Sep 8, 2017. But starting yesterday Monday, Sep 11, I get a hash mismatch when I removed hub, cleared the cache, and ran brew install again.

Error: SHA256 mismatch
Expected: 9b4764dc2647bc0c14de2bd386e6f428f002d93baf01059d994e1cfa928483fc
Actual: 4096b95aea46f674e91ff0d83f86d876958024a02c50ffb1e3a4aac3e0536fc5

I tried updating brew but still no good. Reproduced this with my colleagues. 

Please advise, thanks!

**Comment by Seariyu** [comment]
I'm getting a similar mismatch for 2.2.3

Expected: f8a43df60b2efd95c70054324e73f27c3b253ec1c4969de8ea6c514669c688ed
Actual: 5c05344b69af39d04f1a208a736bd57c555905ff80238e4f20ad00ea409520e2
Archive: /opt/boxen/cache/homebrew/hub-2.2.3.tar.gz

**Comment by mbartmann** [comment]
I have the same problem with 2.2.9

Expected: b3cf227e38a34a56e37b7705a60bec258cea52174d8e030b559f74af647a70d6
Actual: b3f949c4500288a18ed68c38755962c9571c9e10063fb77583a19d0fcca5ecdf
Archive: /opt/boxen/cache/homebrew/hub-2.2.9.tar.gz

**Comment by mislav** [comment]
Fixed in homebrew/homebrew-core@252feb2c4b38d155db8c9f6a10d9a6dec55013a4 homebrew/homebrew-core@4e6eba41b3a7ab1bf28a6e9ceb17604669b72b37. More information: https://github.com/Homebrew/homebrew-core/issues/18044
