### ISSUE TITLE
Markdown headers parsed as comments by hub

### ISSUE THREAD

**Issue by shalecraig** [github/hub#1575]
Hub interprets the markdown headings in the template which start with a '#' character as being a comment, stripping them out of the resulting PR, leading to semi incomprehensible PRs.

e.g.:

```markdown
# in .github/PULL_REQUEST_TEMPLATE.md

<!-- it's not clear in GH's markdown syntax, but there are leading spaces in the line below this one -->
## Description
<!-- please put a justification here -->

## Reviewers
<!-- please @-whomever's your reviewer here -->
```

The PR created by `hub` strips the `## Description` and `## Reviewers tag`, making the PR description harder to understand.

**Comment by mislav** [comment]
Thanks for reporting! This is already being discussed in https://github.com/github/hub/issues/1377
