### ISSUE TITLE
Integration with Github's Pull Request Templates

### ISSUE THREAD

**Issue by kusamakura** [github/hub#1577]
Though #1187 already offers PR template functionality, I was surprised to see that `hub` doesn't automatically look for templates as specified in [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

Edit: Sorry, the code seems to suggest that this is supported. Am I missing something? I'm using Hub 2.2.9 on OS X 10.12.6, and I have a `.github` directory with a file called `PULL_REQUEST_TEMPLATE.md`, but it doesn't get picked up when I run `hub pull-request`.

**Comment by mislav** [comment]
This hasn't been yet released as a stable release, but you can pick up one of the prereleases from the Releases page, or use Homebrew: `brew upgrade hub --devel`.

**Comment by kusamakura** [comment]
My bad. Thanks for the prompt response.

– P
