### ISSUE TITLE
Go 1.8 or higher is needed to install, but README says 1.7.3 is ok

### ISSUE THREAD

**Issue by strk** [github/hub#1583]
It'd be great if the project could be built with 1.7, as reported in the README, but instead upon running `make install` an error is raised saying you need Go 1.8+

Either fix the README or (better) the Makefile ?

**Comment by patheticpat** [comment]
You probably misread. The README says you need **git 1.7.3** or newer and **Go 1.8+**.

**Comment by strk** [comment]
Evidently misread, sorry for the noise.
It would be great if I could build the project it on a popular system
like Ubuntu 17.04 (or older), but this ticket is clearly invalid.

**Comment by patheticpat** [comment]
Well, installing a more recent version of Go is really simple (just unpack an archive, update your PATH, and you're good to go).

**Comment by strk** [comment]
installing what the distribution gives you is simpler:

    apt-get install golang-go

what you are saying requires

   1) Find the download url
   2) Decide where to unpack
   3) Decide how to make your PATH changes stick

Lots of stress, for what benefit ? What is it that
a web API client needs that cannot be done in Go 1.6 ?

**Comment by patheticpat** [comment]
> Lots of stress, for what benefit ? What is it that
> a web API client needs that cannot be done in Go 1.6 ?

See commit 71fa8dad8faef67599a744df969375ada9694e2c for details.

And if you absolutely can't be bothered to install a recent Go version yourself, Ubuntu 17.04 even has Go 1.8 packages.

**Comment by mislav** [comment]
Thanks @patheticpat. It's true that this project needs at least Go 1.8.
