### ISSUE TITLE
hub compare does not work when head is detached, even if a full range is specified

### ISSUE THREAD

**Issue by netvl** [github/hub#1584]
The following sequence of commands make `hub` fail:
```
$ git checkout --detach
HEAD is now at 978a908... <redacted>
$ hub compare release..master
Aborted: not currently on any branch.
```
This would be understandable if I would have omitted the upper boundary, in which case according to `--help` the current branch would be used, but I would expect it to work correctly when full ranges are specified.

**Comment by mislav** [comment]
Thanks for reporting!
