### ISSUE TITLE
pull-request not honoring PULL_REQUEST_TEMPLATE.md under .github

### ISSUE THREAD

**Issue by sfdye** [github/hub#1594]
It seems that `hub pull-request` does not honor the `PULL_REQUEST_TEMPLATE.md` under the `.github` directory. Is this an known issue? Else I will would like to submit this as an feature request.

**Comment by mislav** [comment]
This is available from the latest prereleases https://github.com/github/hub/releases/tag/v2.3.0-pre1. Grab the latest binary to gain access to this and some other new features.
