### ISSUE TITLE
hub doesn't pass editor options to vi

### ISSUE THREAD

**Issue by patheticpat** [github/hub#1602]
I just stumbled across this regex that detects if the users editor is some variant of vi:
https://github.com/github/hub/blob/cbcc349e39c359ea2bd1f3f0d2ad56463750a905/github/editor.go#L114
Unless I am missing something obvious, shouldn't this rather be something like
```golang
r := regexp.MustCompile(`\b(?:[gm]?vim|vi)\b`)
```
in order to also match vi, but not gvi or mvi?

**Comment by mislav** [comment]
You're right. The `[m]` expression makes no sense since it would only ever match the literal `m` character. Maybe this was supposed to be `(m)?`? Care to submit a PR for this?

**Comment by patheticpat** [comment]
Sure.
