### ISSUE TITLE
Post https://<my_github_enterprise_url>/api/v3/authorizations: EOF

### ISSUE THREAD

**Issue by lee-tunnicliffe** [github/hub#1605]
Can anyone help me with this error? 

```
$ hub pull-request
<my_github_enterprise_url> username: <username>
<my_github_enterprise_url> password for <username> (never stored): 
Post https://<my_github_enterprise_url>/api/v3/authorizations: EOF
```

**Comment by mislav** [comment]
This looks like a network problem while connecting to your GitHub Enterprise instance. Can you `curl https://<my_github_enterprise_url>/api/v3/authorizations` to see if you get any HTTP response at all? What is your GHE version?

**Comment by lee-tunnicliffe** [comment]
I ended up fixing this but I'm not 100% sure how. I think it was because I had two hosts in my config and one of them was wrong :/. Thanks anyway.
