### ISSUE TITLE
Markdown headers in PULL_REQUEST_TEMPLATE treated like comments

### ISSUE THREAD

**Issue by paul** [github/hub#1610]
We have a `.github/PULL_REQUEST_TEMPLATE.md` file which contains Markdown headers:

```mkd
PR Title

## Purpose 

Describe the PR here

```

When using the `pull-request` command, those headers get stripped out, because the CLI tool things those are comments similar to the commit list appended to the bottom of the template ("Requesting a pull to ..."):

```mkd
PR title

Describe the PR here
```

![selection_010](https://user-images.githubusercontent.com/184/32081642-ebe21d8e-ba73-11e7-864b-3789fc612777.png)

**Comment by mislav** [comment]
Thanks for writing in! This is already being discussed in https://github.com/github/hub/issues/1377 with some solutions proposed.
