### ISSUE TITLE
Cannot go get this repository: error: object 9ef2af57366f63deb751b92a8ca630fe598b10f0: zeroPaddedFilemode: contains zero-padded file modes

### ISSUE THREAD

**Issue by jhford** [github/hub#1611]
thinkpad-w530:~/taskcluster/aws-provisioner $ go get github.com/github/hub
# cd .; git clone https://github.com/github/hub /home/jhford/go/src/github.com/github/hub
Cloning into '/home/jhford/go/src/github.com/github/hub'...
error: object 9ef2af57366f63deb751b92a8ca630fe598b10f0: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
package github.com/github/hub: exit status 128

**Comment by mislav** [comment]
Sorry for the inconvenience. See https://github.com/github/hub/issues/1404
