### ISSUE TITLE
Github Enterprise using ssh?

### ISSUE THREAD

**Issue by ENG618** [github/hub#1612]
I was trying to use some of the extra feature like `git issue` and `git browse` but when I do so in a GHE repo it asks for username and password; however, my GHE account is restricted to only shh access.  Is there a way to utilize this, or am I setting this up incorrectly?

I added my GHE host name with `git config --global --add hub.host github.COMPANY.com`

which added it to the **.gitconfig** as: 

```
[hub]
  host = github.COMPANY.com
```

**Comment by cbcoutinho** [comment]
Is that the first time you used hub? When I first used hub I had to log in (including two factor authentication). That was only for using hub, not cloning the repo, for which I also use ssh.

I'm not sure if that applies to GHE

**Comment by ENG618** [comment]
Yes, this is the first time using hub.  WIth my GHE account though we do not have the option for basic auth...it is routed through SSO so whatever credentials I put in fail.

**Comment by mislav** [comment]
Try generating a Personal Access Token from your GitHub Enterprise settings (web interface) and adding something like this to your `~/.config/hub`:

```
yourdomain.com:
- user: eng618
  oauth_token: YOURTOKEN
  protocol: https
```

Sorry that this is inconvenient. We will be working on trying to make this more convenient: #225

**Comment by ENG618** [comment]
thanks @mislav that is good enough for me
