### ISSUE TITLE
[Bug] Wrong commit recognition of the tag

### ISSUE THREAD

**Issue by sebres** [github/hub#1613]
### Issue:
If you target a **tag** (e. g. by selecting in the select-box "Branch") on the project main page (e. g. "\<\> Code"), you'll see a wrong commit as "Latest commit".

For example: https://github.com/fail2ban/fail2ban/tree/0.10.1 shows as the latest commit [b698a749029af2c216268aa29a1228f21e87bfb7](https://github.com/fail2ban/fail2ban/commit/b698a749029af2c216268aa29a1228f21e87bfb7), but actually [351abeb4ff77dfca4049e7401553900b46e8db40](https://github.com/fail2ban/fail2ban/commit/351abeb4ff77dfca4049e7401553900b46e8db40) is the latest commit of tag 0.10.1.

This results in **wrong content of each file** belonging this tag.
E.g. view of [README.md](https://github.com/fail2ban/fail2ban/blob/0.10.1/README.md) or [ChangeLog](https://github.com/fail2ban/fail2ban/blob/0.10.1/ChangeLog) show the obsolete content.

### Observed behavior:
You don't see the last commit of the release tag, and therefore each link points to obsolete content of any file within...

### Expected behavior:
You see the current commit of the tags, as well as the current content of the files within the tag.

**Comment by szepeviktor** [comment]
Maybe the preferred way would be

1. emailing support@github.com
1. and https://github.com/isaacs/github/issues

**Comment by sebres** [comment]
1. Already done.
2. Hmm... If you take a look at the [main-page](https://github.com/isaacs/github) you'll see "This is not the actual repository for the GitHub website."... Why it should be better place for it?

**Comment by szepeviktor** [comment]
As this repo is of a CLI tool.
That one is the only one that lists GitHub bugs.

**Comment by sebres** [comment]
Done - https://github.com/isaacs/github/issues/1109
