### ISSUE TITLE
remote created by "hub fetch" is not pushable

### ISSUE THREAD

**Issue by ahmetb** [github/hub#1614]
When I `hub fetch` someone else's fork I get this remote (note the format difference):

```
$ git remote -v
maguro	git://github.com/maguro/govvv.git (fetch)
maguro	git://github.com/maguro/govvv.git (push)
origin	git@github.com:ahmetb/govvv.git (fetch)
origin	git@github.com:ahmetb/govvv.git (push)
```
(origin is me, maguro is theirs)

Now when I `hub push maguro HEAD`, I get:

```
fatal: remote error:
  You can't push to git://github.com/maguro/govvv.git
  Use https://github.com/maguro/govvv.git
```

So I have to
```
git remote rm maguro
git remote add maguro git@github.com:maguro/govvv.git
```

now `hub push maguro HEAD` works. 

I this is an inconvenience.

**Comment by jpfairbanks** [comment]
It looks like it boils down to this function:
https://github.com/github/hub/blob/55dec7d39266648eaa7a43f68b770833f53cff5f/github/project.go#L65

```go
func (p *Project) GitURL(name, owner string, isSSH bool) (url string) {
	if name == "" {
		name = p.Name
	}
	if owner == "" {
		owner = p.Owner
	}

	host := rawHost(p.Host)

	if preferredProtocol() == "https" {
		url = fmt.Sprintf("https://%s/%s/%s.git", host, owner, name)
	} else if isSSH || preferredProtocol() == "ssh" {
		url = fmt.Sprintf("git@%s:%s/%s.git", host, owner, name)
	} else {
		url = fmt.Sprintf("git://%s/%s/%s.git", host, owner, name)
	}

	return url
}
```
A viable work around sounds like setting preferredProtocol to `https` or `ssh`
Based on this definition of `preferredProtocol` you can set the protocol with

```golang
func preferredProtocol() string {
	userProtocol := os.Getenv("HUB_PROTOCOL")
	if userProtocol == "" {
		userProtocol, _ = git.Config("hub.protocol")
	}
	return userProtocol
}
```

For a single session:
`export HUB_PROTOCOL="ssh"`

or

Permanently:
`git config --global hub.protocol ssh`

**Comment by ahmetb** [comment]
> `git config --global hub.protocol ssh`

seems like a great solution, thanks! I was getting very annoyed by my forks being created as https.
