### ISSUE TITLE
Setup fails with 2Fac

### ISSUE THREAD

**Issue by Cypher1** [github/hub#1615]
Just tried to setup hub (from the debian package).
I receive the following:
```
 git-hub setup                                                
GitHub username [cypher]: cypher1
GitHub password (will not be stored): 
Looking for GitHub authorization token...
Error: GitHub error: Must specify two-factor authentication OTP code.
```

Why doesn't Hub ask for two-factor auth?
Can it be made to do so?

I found some other issues relating to 2Fac but they were either very old or didn't seem related. If I missed something I'd love to know.
Thanks

**Comment by Hemable1** [comment]
a

**Comment by mislav** [comment]
Hello, this project is called `hub`, not `git-hub`, and does not have a `git-hub setup` command. I'm not sure where the issue tracker for the project you were using it.

Debian package names do not necessarily correspond to GitHub project names.
