### ISSUE TITLE
pull-request command uses the wrong remote

### ISSUE THREAD

**Issue by Crell** [github/hub#1618]
Per the documentation for `hub pull-request`:

```
Opens  a  pull  request on GitHub for the project that the "origin" remote points to.
```

However, if I have multiple remotes in my repository then it I get the following error:

```
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "base"
Invalid value for "head"
```

By using verbose mode, I've determined that it is trying to send the PR against the remote named `upstream` rather than the one named `origin`.  (Rather, it's POSTing to the repository that I have named `origin`.)  This seems wrong...

If I simply remove the `remote` repository then the request complete successfully and the PR is created.  Of course, removing a remote just to be able to make a PR seems like a poor workaround.

Is there a switch or toggle I'm missing, or is this a straight up bug?

**Comment by mareksuscak** [comment]
If you're on a stable release I'd highly recommend giving [prerelease](https://github.com/github/hub/#installation) a try. For me it works fine and submits pull requests to the `origin` repo.

Consider providing more details about your environment when submitting PRs.

**Comment by mislav** [comment]
`upstream` takes precedence over `origin` because that's what the majority of hub users requested over time.

To choose a base branch from another repository, use:

```
hub pull-request -b <owner>:master
```

**Comment by Crell** [comment]
... Oh.  So `upstream` is a magic branch name as well as `origin`, when using `hub`?

**Comment by mislav** [comment]
> So `upstream` is a magic branch name as well as `origin`

No, "upstream" is a magic _remote_ name (not branch name), as well as "github" and "origin" (in that order).

**Comment by Crell** [comment]
I misspoke, you're right.  I follow now.  Thanks.

**Comment by gnoireaux** [comment]
> verbose mode

@Crell 
How did you get the `verbose mode`?

**Comment by mislav** [comment]
@gnoireaux `HUB_VERBOSE=1 hub <command> [<args...>]`

(see `hub help hub`)
