### ISSUE TITLE
Set base repo when making a pull request

### ISSUE THREAD

**Issue by BuddyLReno** [github/hub#1622]
I don't see any documentation around this so I assume you can't do it yet. I'd like to be able to pass an option to the `pull-request` command to set what the base branch is.

**Comment by danielleallopez** [comment]
@BuddyLReno Maybe you mean the flag `-b`? As in:

> (myBranch) $ hub pull-request -b develop

**Comment by mislav** [comment]
Thank you @danielleallopez. That is the correct solution.
