### ISSUE TITLE
Unable to clone private repository to azure vm

### ISSUE THREAD

**Issue by Banani-Rath** [github/hub#1624]
Unable to clone repo with following issue

read data remaining
* stopped the pause stream!
* Closing connection 0
fatal: unable to access 'https://github.com/MicrosoftDocs/azure-docs-pr/': transfer closed with outstanding read data remaining

**Comment by openpublishoperation** [comment]
Can we get a update here?

**Comment by angelsdon81** [comment]
sorry

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
