### ISSUE TITLE
pull-request with spaced comma separated value

### ISSUE THREAD

**Issue by seoklee** [github/hub#1626]
I have been using hub v2.3.0-pre10, and noticed this

```
hub pull-request -m "pull request message" -a abc,def 
```

This makes a PR as expected; it will create a PR with asignees of `abc` and `def`. 

However, if I make PR with this command. (Notice the space after the comma)
``` 
hub pull-request -m "pull request message" -a abc, def 
```
It will create a PR with asignee of 'abc'. This is also the case with `-r` flag as well

**Comment by mislav** [comment]
This is expected. When you pass these arguments in bash: `-a abc, def` to _any_ command, that command will receive these arguments:

1. `-a`
2. `abc,`
3. `def`

With typical command-line flags parsing, (2) is assumed to be the value for (1), and (3) is considered to be a separate argument completely independent of `-a`.

In short, spaces between commas are not supported.
