### ISSUE TITLE
Feature request: add fork as remote

### ISSUE THREAD

**Issue by cbcoutinho** [github/hub#1627]
Is it possible for hub to access the github.com api and search for all forks of a project?

Adding remotes is already a simple task in git, but currently to set up a fork as a remote you need to track it down using the github.com website and then manually add it as a remote using the full command `git remote add <name> <url>`

For example, let's say that I fork hub manually using github.com. Would it be possible to do something similar to how hub clone overrides git clone as follows:

```bash
hub remote add <user> # hub would be the assumed project name
```

It would even be cool if it had some error detection and warned if there was no public  project by the name of hub in that user's account 

If this isn't possible, and I wanted to add it to hub in the form of a pr, where should I start looking in the source?

**Comment by mislav** [comment]
This is already supported:

```sh
hub remote add <user>
# results in: hub remote add <user> git://github.com/<user>/hub.git
```

It doesn't check if `<user>` did fork hub, though, but I don't think that is necessary. If you're adding a certain user as a remote, that means that you already know that user has made changes that you want to fetch from their repo.
