### ISSUE TITLE
hub pull-request -i flag overwrites commits

### ISSUE THREAD

**Issue by cbcoutinho** [github/hub#1628]
I realize that `hub pull-request` is deprecated, but I accidentally wrote over someone's commit in a project repository.

not sure what there is to do about that now.

**Comment by JoesaDmercado** [comment]
Hello World

**Comment by mislav** [comment]
I'm sorry you had a problem. The `pull-request -i` command is indeed deprecated, but it doesn't do anything other than converting an issue to a PR based on a branch that you specify. It doesn't change anything in the git repo, and it doesn't have the power to eliminate git commits from your repository either.

I'm not sure what happened, but the only way of “overwriting” git commits in your repo is if you had done `git push --force`.

**Comment by cbcoutinho** [comment]
Hi @mislav thanks for the explanation. I apologize for misrepresenting the issue - what happened was that I wrote over an _issue_ in a separate repo, not a commit.

**Comment by mislav** [comment]
@cbcoutinho Thanks for following up. If I understand, you wrote over an issue in a repo that is different from the one you were operating on when you wanted to create a PR?

**Comment by cbcoutinho** [comment]
No not exactly, I originally created an issue on a repository that I don't
have write access to. I wanted to make the change so I forked it, committed
my change to my fork and then created a pull request on the original
repository with the '-i' flag. The number I supplied was the issue number
that I created. This converted my 'issue' into the pull-request I was
trying to create.

I think it makes more sense to get an error like 'an issue or pull-request
already exists at that number', but instead it just had just overwritten
the issue. Luckily it was my own issue, but maybe it's possible to
overwrite other people's issues - I haven't tried that yet.

**Comment by mislav** [comment]
> I wanted to make the change so I forked it, committed my change to my fork and then created a pull request on the original repository with the '-i' flag. The number I supplied was the issue number that I created. This converted my 'issue' into the pull-request I was trying to create.

This is literally what the `-i` flag does. It converts an issue (usually your own) to a pull request. The original issue is then gone.
