### ISSUE TITLE
Error when using `hub create` with the -p flag

### ISSUE THREAD

**Issue by ItsPugle** [github/hub#1631]
(First thing: I'm not an experienced developer. In fact, I feel bad for suggesting that I am even a developer - I'm learning, but I'm not there yet.)

Whenever I try to use `$ hub create (Repository Name) -p`, I get this error: `Post https://api.github.com/user/repos: dial tcp: lookup api.github.com: no such host`, yet when I use `$ hub create (Repository Name)` without the `-p` flag, it creates the Repository and updates the `origin` remote.

I'm not sure if I've actually used the command with `-p` before, so I can't relate this to a recent change. Bad memory struggles.

 - I've got GitHub Premium (is that what it's called?) through the Student Developer Pack
 - I'm using `git version 2.15.0` and `hub version 2.2.9`
 - I'm on a MacBook Air 2013, `macOS 10.13.1`

Any pointers?

**Comment by pauloancheta** [comment]
I tried a few things to make sure that it works, looks like the error might be because you are not authenticated?

These are the commands that I tried to run:
```
$ hub create new-private-repo -p
created repository: pauloancheta/my-new-private-repo

$hub create hello world -p
created repository: pauloancheta/hello

$ hub create (hello world) -p
zsh: unknown file attribute: h

$ hub create "Hello World" -p
created repository: pauloancheta/Hello-World
```

**Comment by ItsPugle** [comment]
It's working now! I think it might have been something with a bloop with the GitHub API 😄
