### ISSUE TITLE
Hub create impossible 

### ISSUE THREAD

**Issue by Matthias74** [github/hub#1632]
Hello,

I have a problem when I want to create a repo on Github from shell:
$ hub create
I have this response => Post https://api.github.com/user/repos: dial tcp 192.3X.XX.XXX:XXX: i/o timeout

My ssh are ok. 

Do you Know what happens?

thanks,

Matt

**Comment by pauloancheta** [comment]
I just tested this and wasn't able to recreate the error. I tried to use `hub create` in an empty folder where I had just run `git init`. `hub` created a repo on my account and updated my remote. It might be because your internet was slow? Just a theory.

**Comment by Matthias74** [comment]
Yes maybe, i works now. 

Matthias VITTE
tel: 0688833732

**Comment by Dmitry1007** [comment]
I have the same exact issue.
My internet connection is great. 
have been using Hub for years now...
Any ideas?

**Comment by Dmitry1007** [comment]
Nevermind. I solved it! 
First I tried updating hub by running: `brew upgrade hub`
Realized my Xcode version was outdated.
Updated Xcode through the App Store(simplest way)
ran `brew upgrade hub` again
and now it works!

**Comment by jfrederick** [comment]
I also had this problem, after upgrading to Mac OS High Sierra. Upgrading hub fixed it.

**Comment by Matthias74** [comment]
I did brew upgrade hub and it works now. I didn't accept the licence of Xcode, it's why I couldn't upgrade hub before.

**Comment by mislav** [comment]
@Matthias74 In the future, please close your own issue when your problem solved itself!
