### ISSUE TITLE
Add 'team reviewers' using -r

### ISSUE THREAD

**Issue by johnofcamas** [github/hub#1633]
It is not currently possible to add team reviewers to a pull request via the `-r` switch.

**Comment by axos88** [comment]
+1

**Comment by pauloancheta** [comment]
Can I take a stab at adding this functionality?

**Comment by axos88** [comment]
@pauloancheta Did you implement this in the end? I would also love to see this happen.

**Comment by tedmdelacruz** [comment]
Is this working? I tried `hub pull-request ... -r <org_name>/<team_name>` but it didn't work. I'm using version`2.3.0-pre10`
