### ISSUE TITLE
Be able to easily mass move repositories to another user or organization accounts

### ISSUE THREAD

**Issue by timofonic** [github/hub#1634]
Hello.

I really like GitHub, really. I think it's a great place to share and look other's people code!

Maybe it's my OCD, but I like to fork every project I'm interested in. Unfortunately, this mania made me have an unsustainable mess: 500+ plus +170 projects in timofonic + TimofonicJunkRoom.
 
I'm currently moving lots of forks to organization accounts, but I only found [this](https://gist.github.com/oriolgual/a5ac8139120d06b51b16b902c324d530) Selenium script to more or less automatize the task.

Despite the lack of an ideal solution, it's far from being an ideal solution and moving projects is still a very time consuming task. I would prefer a MidnightCommander-like UI, it would be a lot easier.

I suggested it in [issue 841](https://github.com/sindresorhus/refined-github/issues/841) of the [refined-github](https://github.com/sindresorhus/refined-github) project too.

I also wrote about this in [issue 277](https://github.com/dear-github/dear-github/issues/277) at [dear-github](https://github.com/dear-github/dear-github/) repository, a place I consider GitHub company members should look at for interesting feedback too.

Kind regards.

**Comment by mislav** [comment]
Hey! It would be cool if this feature existed, but the scope of this feature would be too large to maintain within this project. Therefore, I don't see this appearing on our feature roadmap anytime soon.
