### ISSUE TITLE
Check it out

### ISSUE THREAD

**Issue by ashanaakh** [github/hub#1635]
I've created __the best cli for github__ https://github.com/ashanaakh/gitius. Check it out! 😉

**Comment by AlexTes** [comment]
Drawing attention like this is disruptive 😞 . Please edit your title to be less aggressively grabbing for attention @ashanaakh  😓 .

**Comment by ashanaakh** [comment]
@AlexTes don't be angry, I just have fun :wink:

**Comment by AlexTes** [comment]
I'm not angry 😉 , you should have fun!
Thanks for changing it! This way your issue doesn't get preferential treatment 😄 .

**Comment by mislav** [comment]
Please don't use issue trackers to promote your personal projects.
