### ISSUE TITLE
hub doesn't respect the .github/PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by brennantaylor** [github/hub#1638]
When opening a new PR it doesn't use the repo's `PULL_REQUEST_TEMPLATE.md`

**Comment by dwijnand** [comment]
Duplicate of #1594.

**Comment by brennantaylor** [comment]
Sorry, I promise I did a search for this. I don't think I looked at closed issues.

Tested on 2.3-pre10 from `brew --devel`, working as expected thanks.
