### ISSUE TITLE
Pull Requests: Consider using base branch by default instead of master

### ISSUE THREAD

**Issue by DwordPtr** [github/hub#1641]
Consider making `hub pull-request` pull into the remotes version of that branch if it exists.

For instance: If I run `hub pull-request` with `dev` checked out. It's more likely that I want to pull into dev than master. 
Given that some org/user names run long this could cut down on typing.

**Comment by mislav** [comment]
Hi, I'm not sure what you're asking. When you're on a branch called `dev` and the same branch is pushed to a remote, `hub pull-request` will assume that `dev` is the **head** branch, _not_ the base branch. The base branch is always the "default" branch of the repository: usually `master`, sometimes `develop`, determined via `git rev-parse --symbolic-full-name origin`.

Can you explain more the behavior that you were expecting, and why were you expecting it? Is `dev` the “default” branch of your repository? What did you expect to be the head branch when you used `hub pull-request`?

**Comment by DwordPtr** [comment]
I'm sorry I had completely forgotten about this. Rereading this I have no idea what I was thinking and don't remember how to replicate. There's also a good chance I was mistaken. I'll go ahead and close.
