### ISSUE TITLE
2FA never gets sent to my Mobile number.

### ISSUE THREAD

**Issue by andela-oaboluwarin** [github/hub#1642]
The two-factor authentication code never gets sent to a friend's mobile number despite repeated attempts, and she is now locked out of GitHub. She did not download the recovery codes when she did the setup for 2FA so there's no way for recovery.

She has previously received auth codes from GitHub just after the initial setup, so there's no question of a wrong phone number supplied. 

The account name is `andela-fojuri`. Please advise.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
