### ISSUE TITLE
Downloaded amd64 version does not run in an amd64 alpine container running on CoreOS.

### ISSUE THREAD

**Issue by omar-nahhas** [github/hub#1645]
I am downloading hub (https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz) on a running a container on a COREOS operating system. The container is based on alpine:3.6. 

When trying to execute the downloaded binary I get a "file not found" error. If I download the 32bits version of the binary, it runs fine.

I have researched the issue and the most probable cause explained in this link:
https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host

**Comment by tinnightcap** [comment]
I ran into the same issue. Following the solution from that stackoverflow post, I managed to get this working. Please note that I am not a go developer and there might be a fancy go method for doing this build instead of this bash/git clone pattern

```
FROM alpine:3.6 AS build-hub
RUN apk add --no-cache \
    bash \
    go=1.8.4-r0 \
    libc-dev=0.7.1-r \
    git=2.13.5-r0
WORKDIR /app
RUN ["/bin/bash", "-c", "set -o pipefail \
    && git clone https://github.com/github/hub.git \
    && cd hub \
    && git fetch --tags \
    && git checkout v2.2.9 \
    && ./script/build " ]

FROM alpine:3.6
WORKDIR /app
COPY --from=build-hub /app/hub/bin/hub /app/hub
CMD [ "/app/hub" ]
```

Hope this helps :)

**Comment by mislav** [comment]
Thanks for the instructions, @tinnightcap.

@omar-nahhas You can try some of the newer prereleases on our Releases page, but if no 64-bit binaries work on your platform, then you will just have to compile hub yourself.
