### ISSUE TITLE
serialport permission denied / prebuild-install

### ISSUE THREAD

**Issue by barbarian264** [github/hub#1647]
When deploying my app I get a message on serialport and it says prebuild-install || node-gyp and then it says prebuild-install: permission denied. I believe this is making my app not work correctly regarding the serialport. PLEASE HELP.

**Comment by mislav** [comment]
Hi, I believe you have opened an issue on the wrong repository. This project is for a command-line utility called `hub` and has nothing to do with deploying apps, "serialport", nor node-gyp.
