### ISSUE TITLE
Aborting a pull-request creation still creates the commit

### ISSUE THREAD

**Issue by axos88** [github/hub#1649]
Repro:

  1. `git pull-request -b development -o`
  2. When the editor comes up, exit without saving

Expected:

The pull request creation is aborted due to a missing message

Actual:
 
The pull request is created, with the default message that I think is the last commit message in case there is only one commit.

**Comment by mislav** [comment]
Hi thanks for reporting! This is being currently tracked as #1428. Closing this as duplicate
