### ISSUE TITLE
hub refuses to fork an archived repo

### ISSUE THREAD

**Issue by sambrightman** [github/hub#1655]
I get this:

```
Error creating fork: Forbidden (HTTP 403)
Repository was archived so is read-only.
```

when I `hub fork`. Forking an archived repo should be (and _is_ - via web) possible.

**Comment by sambrightman** [comment]
Additionally, using `hub fork` on an already-forked repo usually works as a shortcut to add the remote and fetch. For an archived repo it says:

```
Error creating fork: sambrightman/sphinxcontrib-emacs already exists on github.com
```

**Comment by mislav** [comment]
Thanks for reporting! Forking an archived repo via the API was broken at the time that you reported this bug. It has since then been fixed, and you should be able to fork archived repos via hub now. ✨
