### ISSUE TITLE
How to pre-configure `hub` for the users of our GitHub OAuth application?

### ISSUE THREAD

**Issue by jankeromnes** [github/hub#1668]
Hello!

We run [janitor.technology](https://janitor.technology), a developer cloud service that makes it easy to contribute to well-known open source projects like Firefox, Servo, Chromium, Thunderbird, Discourse, [etc](https://janitor.technology/projects/). It works by letting you quickly spawn Docker containers that are fully pre-configured for developing a given software project, and since most of the projects we support are hosted on GitHub, all Janitor containers come with `hub` conveniently [pre-installed](https://github.com/JanitorTechnology/dockerfiles/blob/475d85ea3c2c6a2a0c31c41f6daad4b7d7eadba9/ubuntu-dev/ubuntu-dev.dockerfile#L122-L129).

Today, when a Janitor user want to submit a pull request, we tell them to run `hub fork` in their container, which signs them in to GitHub and generates a Personal Access Token, and then they need to manually create a `~/.netrc` configuration file (by copy/pasting their PAT from `~/.config/hub`, as explained in [this gist](https://gist.github.com/notriddle/6c232ed0691dc77cc8a3adc10b4e2aaf#file-readme-md)).

However, this is very tedious to do manually for every new container you create, so we would like to fully automate developer authentication by pre-configuring `hub` for each user in each of their containers.

We already have Janitor registered as a GitHub OAuth application (i.e. users can enable Janitor's "GitHub integration" by "Signing in with GitHub", which generates a GitHub OAuth token for that user, allowing Janitor to use the GitHub API on behalf of the user), and we're hoping to use that API access to generate Personal Access Tokens for `hub`.

1. Can we use the GitHub API to generate Personal Access Tokens for our users?
2. If yes, which scopes and API handlers do we need to use? If no, how else can we generate PATs for our users?
3. Can we limit the scope of the generated Personal Access Tokens? (Ideally, for security reasons in shared infrastructure, we'd love PATs to only be able to open pull requests, but not merge arbitrary code).
4. Can we limit the lifetime or expire Personal Access Tokens? (We'd love to periodically rotate our user's PATs, so that if our infra is compromised and tokens are stolen, they're not harmful for very long).

Thanks for an amazing CLI tool! I look forward to making `hub` ultra-convenient for our users.

**Comment by mislav** [comment]
> It works by letting you quickly spawn Docker containers that are fully pre-configured for developing a given software project

That sounds really cool :) 

> We already have Janitor registered as a GitHub OAuth application (i.e. users can enable Janitor's "GitHub integration" by "Signing in with GitHub", which generates a GitHub OAuth token for that user

It sounds like you already have a token for each user that, theoretically, can be used to create pull requests on behalf of that user, at least until they revoke Janitor from their approved apps list.

The scopes for the token need to be `repo`. There's currently no way to create an API token that can open pull requests but not merge them.

The only thing that would be required to configure hub at this point would be to somehow set the `GITHUB_TOKEN` environment variable within the container. This could be done in a global or a per-user `bashrc` (given that bash is the default login shell for the container). If `GITHUB_TOKEN` exists, it will be used for all API requests coming from `hub` without the need for the user to supply their username/password, even if `~/.config/hub` doesn't exist within the container at all.

You could put the same token inside the user's `~/.netrc` file as well.

However, **be careful and transparent** with your users. People typically like to share containers. If someone isn't aware that their GitHub API token is embeded within a container and they pass on that container to others, they've just compromised their account.

**Comment by mislav** [comment]
[Read here for a background on an incident](https://blog.travis-ci.com/2017-05-08-security-advisory) that happened when GitHub tokens leaked from Travis CI. You definitely don't want to find yourself mitigating this kind of incident.

For more information about programatically creating PATs using the GitHub API, see https://developer.github.com/v3/oauth_authorizations/

Does this answer all of your questions?

**Comment by jankeromnes** [comment]
> That sounds really cool :)

Thanks! 😄 

> It sounds like you already have a token for each user that, theoretically, can be used to create pull requests on behalf of that user, at least until they revoke Janitor from their approved apps list. I don't think there's a reason to create a separate Personal Access Token (PAT is just a fancy name for OAuth token).

This was just to separate concerns, e.g. one token that Janitor uses to authenticate and learn more about its users (e.g. real name, emails, public SSH keys) and another token that is responsible for sending Pull Requests from containers (this token should be rotated more often). But maybe it doesn't make sense, and we should just include the user's single Janitor OAuth token in all their configuration files and containers?

> The scopes for the token need to be `repo`. There's currently no way to create an API token that can open pull requests but not merge them.

Thanks! The fact that we can't prevent arbitrary merges is unfortunate, but I guess more and more projects have a protected `master` branch (with no direct pushes, and only a few people are allowed to merge PRs, but first they need to pass tests / linting / code review) so hopefully stolen `repo` tokens won't actually be able to cause direct damage to important repositories.

> The only thing that would be required to configure hub at this point would be to somehow set the `GITHUB_TOKEN` environment variable within the container. This could be done in a global or a per-user `bashrc` (given that bash is the default login shell for the container). If `GITHUB_TOKEN` exists, it will be used for all API requests coming from `hub` without the need for the user to supply their username/password, even if `~/.config/hub` doesn't exist within the container at all.
> 
> You could put the same token inside the user's `~/.netrc` file as well.

Cool, thanks! We do have automated container configurations (i.e. `~/.bashrc` and any other user-specific file), so it will be easy to template a token into `~/.config/hub` or set the `GITHUB_TOKEN` variable in `~/.bashrc` (although we don't template that file yet), and `~/.netrc` too.

> However, **be careful and transparent** with your users. People typically like to share containers. If someone isn't aware that their GitHub API token is embeded within a container and they pass on that container to others, they've just compromised their account.

Great point! We do want to be careful and transparent with our users about the fact that their containers include sensitive tokens. Container sharing isn't possible on Janitor today (we auto-configure and host developer containers ourselves, and authenticate users to only grant access to container owners), but we'd like to implement some kind of port-specific sharing feature (see https://github.com/JanitorTechnology/janitor/issues/182) so there we should be very clear about what risks sharing a container implies.

> For more information about programatically creating PATs using the GitHub API, see https://developer.github.com/v3/oauth_authorizations/

1. So if I want to generate a PAT for a user, I just `POST` to https://api.github.com/authorizations/ with my `client_id`, `client_secret` and `scope=repo`, authenticating via Basic Authentication with `<username>:<janitor_token>`, and get back a `repo`-scoped PAT with its authorization ID?
2. I suppose that for this to work, the original `janitor_token` also needs the `repo` scope? Any other scope needed, e.g. `authorizations`?
3. To revoke the generated PAT, I just `DELETE` https://api.github.com/authorizations/:id and that's it?

Thanks again for your very helpful replies! 👍

**Comment by mislav** [comment]
> This was just to separate concerns, e.g. one token that Janitor uses to authenticate and learn more about its users (e.g. real name, emails, public SSH keys) and another token that is responsible for sending Pull Requests from containers (this token should be rotated more often).

It's better that you include the user's original Janitor token because that token will then be tied to Janitor's OAuth application. When a user is done using Janitor, they can simply revoke access to Janitor in their approved applications list on GitHub.

Also, you can't programatically create OAuth tokens for your users because the OAuth Authorizations API only supports Basic Authentication with real username/password/2FA token.

Again, be very careful when bundling users' OAuth tokens in the containers! A much better idea would be to generate some kind of Janitor token and bundle that instead. Then, scripts to open pull request could use the Janitor token to hit a Janitor server, which would then pull the user's OAuth token on file and use that to communicate with GitHub API.

Proxying all GitHub API operations through your servers, instead of bundling a tool like `hub` to do pull requests, makes it possible to exercise tighter security protocols and rotate tokens as often as you'd like.

**Comment by jankeromnes** [comment]
> It's better that you include the user's original Janitor token because that token will then be tied to Janitor's OAuth application. When a user is done using Janitor, they can simply revoke access to Janitor in their approved applications list on GitHub.

Thanks a lot for your advice, this does seem like the sanest approach here.

I also see the following advantages to Janitor OAuth app tokens over `hub`'s default Personal Access Tokens:

- `hub` can be pre-configured automatically, with no extra set-up step required before developers can use it in their containers
- If there is ever a major security incident, a Janitor OAuth app admin can revoke all tokens in one click
- Janitor OAuth tokens can be restricted to the `public_repo` scope, instead of having `hub`'s PAT default `repo` scope

> Proxying all GitHub API operations through your servers, instead of bundling a tool like `hub` to do pull requests, makes it possible to exercise tighter security protocols and rotate tokens as often as you'd like.

Thanks, this is an interesting idea to improve security even more, but I'm afraid it isn't practical for our system as we'd need to basically re-implement `hub` in containers and proxy all pull-request creation calls within our service (and maintain that forever in order to follow any hub or GitHub API changes).

I'm hoping that a combination of clear UI (e.g. "Warning: These tokens are dangerous, you can revoke them at any time here: https://github.com/settings/applications"), limited scope (just `public_repo` instead of `repo` and other powerful scopes) and protected `master` branches on most important repositories will lead to a design that's both convenient and safe enough.
