### ISSUE TITLE
Organization default?

### ISSUE THREAD

**Issue by michaelpporter** [github/hub#1669]
I do my main work for the organization not my private account. Is there a way to set and organization as the default for the create function?

**Comment by mislav** [comment]
This is not possible right now. See https://github.com/github/hub/issues/1194#issuecomment-246820044 for a discussion around a similar request. The feature to add default per-command configuration is planned and might be present in the 3.0 release, but until then you will have to work around this by creating your own alias or shell function.

**Comment by ssbarnea** [comment]
Why is this bug closed as is clearly valid, well defined and not a duplicate?

I think this should be implemented as a list of names to look for, one that by default would contain only your own username.

I usually work with 4-5 organizations and I could add a preference like:

organizations = ssbarnea,openstack,openstack-infra,redhat-openstack,pycontribs

This means that when I will do `hub clone foo`, it will try to find where foo repository exists and clone the first found one.

**Comment by mislav** [comment]
@ssbarnea See https://github.com/github/hub/issues/366

**Comment by ssbarnea** [comment]
Mentioned feature will not work for LOTs of users which are not member of the organizations and they are likely never to become members.

Still, these users should be able clone from these repos using the short syntax. These two issues are linked but clearly not duplicate. I am inclined to believe this one should ne fixed before the other one, which would count as having a dynamic default value for this one (in case user does not configure it).

**Comment by KyleC69** [comment]
I realize this is an old feature request, has this been implemented in a work around or some other way? All the open repos I work on are part of an organization and not my personal account. I work in both vscode and Rider and I find it a pain to have to search for the repos. Is there some git setting that I can add so that all requests are directed toward my org and not my personal account? @mislav @ssbarnea
