### ISSUE TITLE
Doesn't appear to work for me

### ISSUE THREAD

**Issue by aexmachina** [github/hub#1670]
I'm on a fresh Mac, trying to use hub (in Fish or bash) and nothing works :(

```
$ brew install hub
$ hub clone github/hub
Get git://api.github.com/repos/github/hub: unsupported protocol scheme "git"
$ # hmmn, okay
$ bash
$ hub clone github/hub
$ Get git://api.github.com/repos/github/hub: unsupported protocol scheme "git"
$ # hmmn, okay
$ cd factory-girl/
$ git remote -v
origin	git@github.com:aexmachina/factory-girl.git (fetch)
origin	git@github.com:aexmachina/factory-girl.git (push)
$ hub browse
The file /Users/simonwade/dev/factory-girl/git:/github.com/aexmachina/factory-girl does not exist.
```

**Comment by mislav** [comment]
@aexmachina Thanks for reporting!

1. What is your `git version`?
2. Can you try the latest prerelease version? `brew upgrade hub --devel`

**Comment by aexmachina** [comment]
```
$ git version
git version 2.14.3 (Apple Git-98)
$ brew upgrade hub --devel
==> Upgrading 1 outdated package, with result:
hub 2.3.0-pre10
==> Upgrading hub
Error: /usr/local/opt/go not present or broken
Please reinstall go. Sorry :(
```

**Comment by mislav** [comment]
Do you have `HUB_TEST_HOST` set in your environment? See `env | grep ^HUB_`

**Comment by aexmachina** [comment]
I do not.​

**Comment by mislav** [comment]
@aexmachina Do you have something in your `~/.ssh/config`that pertains to `github.com` or `api.github.com`?

**Comment by aexmachina** [comment]
Yes I do:

```
$ cat ~/.config/hub
---
github.com:
- protocol: git
  user: aexmachina
  oauth_token: ...
```

**Comment by aexmachina** [comment]
Removing the `- protocol: git` line has fixed the problem 😄 👍 Thanks!

**Comment by mislav** [comment]
Glad you solve it! How did you end up with `protocol: git`? Only `http` and `https` values are allowed here

**Comment by aexmachina** [comment]
No idea. I certainly didn't intend to.

-- 
Simon Wade - Chief Technical Officer
*jtribe* - love your apps
13/243 Collins Street, Melbourne VIC 3000
simon@jtribe.com.au | +61 422 777 262 <+61422777262> | http://jtribe.com.au
