### ISSUE TITLE
Support github templates for PRs, issues

### ISSUE THREAD

**Issue by petemounce** [github/hub#1673]
It's possible to create templates for new

* [pull requests (docs)](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
* [issues (docs)](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

It would be great if `hub pull-request` would use these if they are present.

**Comment by mislav** [comment]
The newest prereleases (see Releases section) already have support for templates. Soon to be made into a stable release.

**Comment by petemounce** [comment]
Brilliant; thanks!
