### ISSUE TITLE
Trace/breakpoint trap

### ISSUE THREAD

**Issue by ccwillia** [github/hub#1678]
This version of hub i was using stopped working with error "Trace/breakpoint trap"

https://github.com/github/hub/releases/download/v2.2.9/hub-linux-386-2.2.9.tgz

/opt/hub # hub 
Trace/breakpoint trap

**Comment by ccwillia** [comment]
I switch to v2.3.0-pre10 which seems to work 

https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-386-2.3.0-pre10.tgz

**Comment by mislav** [comment]
Thanks for letting us know! I'm glad that the latest prerelease works. Soon there will be new binaries built for the stable release and you shouln't have a problem anymore.
