### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Naco6** [github/hub#1679]
i have this error when i push in master

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:master
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Naco6/minigames.git/'
Pushing to https://github.com/Naco6/minigames.git

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the platform. This issue tracker is for a command-line utility called `hub`, not GitHub itself. For reporting bugs and requesting features for GitHub, please email support@github.com. Thank you!
