### ISSUE TITLE
Add https://hub.github.com/ documentation so contributors can edit

### ISSUE THREAD

**Issue by joshunger** [github/hub#1680]
It would be helpful if you could add https://hub.github.com/ documentation so contributors can edit.  I can't find it using the following search https://github.com/search?q=%22Using+GitHub+for+work%22&type=Code&utf8=%E2%9C%93.

Would it be possible to add under "Using GitHub for work" the following text -

```my.example.org:
- user: your_username
  protocol: http
```

Is there a way to make `hub.protocol` when set to http work so this isn't necessary? I just spent a long time debugging this issue and this might help other people. 😭

**Comment by mislav** [comment]
The site is in the `gh-pages` branch of this repository: https://github.com/github/hub/blob/gh-pages/index.html

Sorry you had lost so much time! The `protocol: http` option is only settable manually using a text editor. We plan to make this easier in the future (#225), but for now, docs contributions would be welcome.
