### ISSUE TITLE
Cannot `hub fork` to a previously used repository name

### ISSUE THREAD

**Issue by l29ah** [github/hub#1685]
I want to fork a repo named `plugins`. I had `l29ah/plugins`, so i had renamed my repo to `mpv-plugins` first, but i still can't
```
‰ hub fork
Error creating fork: l29ah/plugins already exists on github.com
```

**Comment by mislav** [comment]
Thanks for reporting and sorry for the inconvenience. This is now fixed in master, but you'll have to manually fork this repo until this is released. (You can also build a new version from master)
