### ISSUE TITLE
Edit existing issues

### ISSUE THREAD

**Issue by alphaCTzo7G** [github/hub#1686]
Hi all,

Is it possible to edit existing issues in a repo?

I checked the manpage and `hub issue --help`, but there is no information about editing a existing issue. 

I know there are other tools https://github.com/node-gh/gh, https://github.com/stephencelis/ghi, which can do this.

Perhaps these could be merged into `hub`, instead of replicating their work..

**Comment by mislav** [comment]
See https://github.com/github/hub/issues/893#issuecomment-368439928
