### ISSUE TITLE
`hub create` does not work correctly for julia repos (ending up in ".jl")

### ISSUE THREAD

**Issue by essenciary** [github/hub#1687]
It sets the origins with the `.jl` suffix but creates the repo without the `.jl` suffix: 

```
$ hub create
github.com username: essenciary
github.com password for essenciary (never stored):
origin	https://github.com/essenciary/IssueReporter.jl.git (fetch)
origin	https://github.com/essenciary/IssueReporter.jl.git (push)
created repository: essenciary/IssueReporter

$ git push origin master
remote: Repository not found.
fatal: repository 'https://github.com/essenciary/IssueReporter.jl.git/' not found
```

**Comment by mislav** [comment]
I can't reproduce with the latest version of hub. Which version are you using? Can you try the latest release from the Releases page?

**Comment by essenciary** [comment]
Installed through `brew`. 
```
$ hub --version
git version 2.14.3 (Apple Git-98)
hub version 2.2.9
```

Sure, I'll give the latest release a try.

**Comment by essenciary** [comment]
The behavior seems to be the same, except with less output on the latest (pre) release. It may be that this is the expected behavior - but it breaks things when looking from Julia's side. What I mean by that is that when I run a Julia utility the following happens: 
```
julia> PkgDev.generate("TestPkg", "MIT")
INFO: Initializing TestPkg repo: /Users/adrian/.julia/v0.6/TestPkg
INFO: Origin: https://github.com/essenciary/TestPkg.jl.git
INFO: Generating LICENSE.md
INFO: Generating README.md
INFO: Generating src/TestPkg.jl
INFO: Generating test/runtests.jl
INFO: Generating REQUIRE
INFO: Generating .gitignore
INFO: Generating .travis.yml
INFO: Generating appveyor.yml
INFO: Generating .codecov.yml
INFO: Committing TestPkg generated files
```

Looking at the above input I actually believe that the problem lays with Julia: the repo is initialized as "TestPkg" but the origin is set to "TestPkg.jl.git". And `hub` creates a repo called "TestPkg" like the name of the repo. Which is correct. So the culprit would be the wrong origin.
