### ISSUE TITLE
[Feature Idea] `release` command to draft/submit a new release

### ISSUE THREAD

**Issue by fbartho** [github/hub#1688]
## Command:
`hub release [flags] [SHA|COMMIT_REFERENCE|BRANCH_NAME]`

## Options:
- `--draft`
- `-m, --message = "commit message"` -- if not supplied, opens your `EDITOR` like git commit. 
- `--tag=v0.2.0` uses git to tag the resolved-SHA -- potentially attaches the release details to the git tag as annotations?
- `--existing=draft_name` References an existing draft

## Open questions:
- File / Tar Attachments?

**Comment by mislav** [comment]
This has already existed for a while in prereleases (see Releases section of this project):

```
$ hub help release

NAME
       hub-release - Manage GitHub releases.

SYNOPSIS
       hub release [--include-drafts] [--exclude-prereleases]
       hub release show TAG
       hub release create [-dpoc] [-a FILE] [-m MESSAGE|-F FILE] [-t TARGET] TAG
       hub release edit [options] TAG
       hub release delete TAG
```

**Comment by fbartho** [comment]
@mislav I looked at: https://hub.github.com/hub.1.html -- and that doesn't have anything about this?

**Comment by fbartho** [comment]
Oh! You said  in `prereleases` gotcha. Huh, 2.3.0 pre-release 10 is 6 months old. -- Is there any hope for getting that to stable in the future?

**Comment by salmanulfarzy** [comment]
You can follow the roadmap to `hub v2.3` at https://github.com/github/hub/projects/1?fullscreen=true. 

If you want to install the pre-release, Try `homebrew install hub --devel`. If you want the bleeding edge from repo try `homebrew install hub --head`.
