### ISSUE TITLE
Branch to Branch Compare: Compares to Master Instead

### ISSUE THREAD

**Issue by gojimmypi** [github/hub#1691]
When comparing two different branches in the web UI, the actual compare is between Branch and Master.

I've setup an example here:

https://github.com/gojimmypi/CompareCheck/blob/master/README.md

![gitcompare](https://user-images.githubusercontent.com/13059545/36938324-c3039a12-1ed4-11e8-8bae-e1d8cc6c30ef.PNG)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!

**Comment by gojimmypi** [comment]
Hi @mislav and thank you for the clarification. I did contact GitHub.com support & they responded with an informative confirmation that branch-to-branch compares are not very intuitive, See:

https://github.community/t5/How-to-use-Git-and-GitHub/Branch-to-Branch-Compare-Compares-to-Master-Instead/m-p/4677#M1527

**Comment by gojimmypi** [comment]
fwiw in GitHub Desktop:

> In 1.2, we introduced the ability to compare one branch to another and merge

See https://blog.github.com/2018-09-12-github-desktop-1-4/

However it looks like branch-to-branch compares not working in web interface.
