### ISSUE TITLE
Dependency has nested dependency graph

### ISSUE THREAD

**Issue by YoginthS** [github/hub#1692]
Dependency has nested dependency graph, I posted the issue here because there is no official repo for GitHub related Issues.

![screenshot](https://user-images.githubusercontent.com/36839013/36975266-935abe2c-209f-11e8-9a05-4cbf99ffc8f7.png)

**Comment by salmanulfarzy** [comment]
@YoginthS as you pointed, This is not the place for GitHub related issues. Would be better if you forwarded it to [GitHub support](https://github.com/contact)
