### ISSUE TITLE
Add github MFA support

### ISSUE THREAD

**Issue by vpoluyaktov** [github/hub#1696]
See issue #965. Last comment was made 2005. Nowadays many users have MFA enabled for their accounts (https://help.github.com/articles/about-two-factor-authentication/). For many software companies it's mandatory security policy to use MFA.

It looks like it's a time to add MFA support to hub otherwise it's useless:

`hub create -p -d "AdonisJS API" a_company/node-api

Error creating repository: Forbidden (HTTP 403)
This API can only be accessed with username and password Basic Auth
`

**Comment by mislav** [comment]
See my answer in https://github.com/github/hub/issues/965#issuecomment-126527025

You should use your username and **real** password for GitHub. You will be asked for your 2FA token, and your password will never be stored.
