### ISSUE TITLE
`hub compare` doesn't handle range as documented

### ISSUE THREAD

**Issue by lilyball** [github/hub#1697]
The documentation for `hub compare` says

> If a range with two dots ("a..b") is given,
> it will be transformed into one with three dots. If <START> is omitted,
> GitHub will compare against the base branch (the default is "master").
> If <END> is omitted, GitHub compare view is opened for the current branch.

This largely doesn't appear to be correct. The issues I see:

* `hub compare release..kballard/mybranch` does not transform into 3 dots, it leaves it as 2 dots, and the GitHub UI opens a comparison against `master` instead.
* `hub compare release...` does not default the end to the current branch but instead opens a comparison for `release` against an unspecified branch.
* `hub compare ...kballard/mybranch` doesn't work either, it opens a comparison where the base branch is unspecified.

About the only part of this description that is correct is if both <START> *and* <END> are omitted, it compares the base branch against the current one.

Tested with hub version 2.2.9.

**Comment by kballard** [comment]
I hope this doesn't need to be said, but the correct behavior here is to match the documentation, not to update the documentation to match the current behavior, because the current behavior is not useful whereas the documented behavior would be quite useful.

**Comment by mislav** [comment]
Thanks for reporting! These are all valid points.

FWIW, `..` is replaced with `...` when "simple" branch names are compared. In your case, this did not happen because your branch name contains a slash. We could add slash to the list of allowed characters in branch names.

**Comment by kballard** [comment]
You definitely should do that, but please also fix the other issues. The most important of the issues I mentioned is the ability to write `hub compare release...` and have it compare `release` against the current branch.
