### ISSUE TITLE
http to https for the links from this project

### ISSUE THREAD

**Issue by etisdew** [github/hub#1709]
This would be a very easy fix for someone.

**Comment by etisdew** [comment]
This is in regards to the first link anyone gets from the project page, across the board of the github organization repositories. It would require a contributor at the very least.

**Comment by mislav** [comment]
Hi, I'm not sure which links are you referring to. Can you be more specific? What needs to be changed to what?

**Comment by etisdew** [comment]
Looks like someone got it. :)
