### ISSUE TITLE
github enterprise 401 bad credentials

### ISSUE THREAD

**Issue by username-is-already-taken2** [github/hub#1710]
Hi there

I'm new to hub and I'm trying to get it working against my github enterprise appliance.

I've followed the man page for setting `hub.host` to the hostname of my appliance & I've set `hub.protocol` to `https`

I created a personal access token and set that value to the environment var `GITHUB_TOKEN`

Yet when I run my `hub create` command it still attemps to auth me to github.com

![image](https://user-images.githubusercontent.com/13700297/38237832-2aaac650-3720-11e8-80eb-0746f32b196b.png)

Anyone able to give me a steer 

I'm running  
```
git version 2.16.2.windows.1
hub version 2.2.9
```
on windows 10.

Thanks

Gary

**Comment by mislav** [comment]
Hi, when running `hub create` and `hub clone` (i.e. commands that are not in a context of an existing git repo that has remote configuration already set up), hub doesn't really know whether you intend to communicate with `github.com` or with your Enterprise instance. It defaults to `github.com`. If you want to default to your enterprise host, you should set `HUB_HOST` environment variable. From the man page:

```
The default host for commands like init and clone is still github.com, but this can be affected
with the GITHUB_HOST environment  variable:

    $ GITHUB_HOST=my.git.org git clone myproject
```
