### ISSUE TITLE
Why trim spaces in readContentsFromFile at github/template.go

### ISSUE THREAD

**Issue by siquare** [github/hub#1714]
When I use the template which starts by a header character `#`, it will be ignored because the line which starts by `#` is recognized as comment in this command. Hence, I usually put space before `#` to avoid this behavior. However, because of the trimming for the first line which consists `#`, this line will be considered as comment. My question is why does this command trim first spaces of the template. Can I fix this issue?

## Example

**Original template**

```
 # Description <!-- all lines starts by a space -->

 # Related PRs

 # Todos
```

**Processed template**

```
# Description <!-- first space was trimmed so this line will be recognized as comment -->

 # Related PRs

 # Todos
```

## Source Location

https://github.com/github/hub/blob/master/github/template.go#L62

```
func readContentsFromFile(filename string) (contents string, err error) {
	content, err := ioutil.ReadFile(filename)
	if err != nil {
		return
	}

	contents = strings.Replace(string(content), "\r\n", "\n", -1)
	contents = strings.TrimSpace(contents)
	return
}
```

**Comment by siquare** [comment]
@mislav Thanks!

**Comment by mislav** [comment]
@siquare Thank you for reporting! ✨
