### ISSUE TITLE
Feature request: ability to change active branch from command line

### ISSUE THREAD

**Issue by alphaCTzo7G** [github/hub#1716]
I was trying to rename a remote Github branch. The procedure for that is to 

1. create a clone of the branch locally, 
2. change the name of the local branch, 
3. push it to Github, 
4. change the active branch of the GIthub repo 
5. delete the remote branch. 

I can do all of the above, except for #4, from the command line.

I understand that repos on Github are bare repos. In bare repos, I can switch the active branch using `symbolic-ref (https://stackoverflow.com/a/3302018/4752883, https://feeding.cloud.geek.nz/posts/setting-default-git-branch-in-bare/).

However, this works only if I have direct access to the repo. If I dont have access to the repo, such as for GITHUB repos, I have to do this from the Web UI.

Looking at the hub interface, it seems currently this is not possible. It would be great, if this could be implemented.

Or is there any other plugin that I dont know of, which can switch the active branch of a github repo from the command line?

**Comment by mislav** [comment]
No sorry, `hub` cannot change the "active" (I'm guessing you meant "default") branch on a remote repo from the command-line. You will have to do that manually.
