### ISSUE TITLE
`hub pull-request` does not use the Github pull request template

### ISSUE THREAD

**Issue by hovissimo** [github/hub#1717]
We have a PR template in `.github/PULL_REQUEST_TEMPLATE.md` that needs to be filled out by contributors before submitting a PR.

This template is respected in the Github browser UI, but not by hub.

I've tried using `hub pull-request -F .github/PULL_REQUEST_TEMPLATE.md` but that submits the PR without giving the opportunity to edit the template.

**Comment by hovissimo** [comment]
Inspecting the source code, it definitely seems the hub is trying to do the right thing here.  I'm afraid I don't know go or how it handles case sensitivity in filenames.  I tried renaming my template to `pull_request_template.md` and it still doesn't work.  /shrug

**Comment by franek** [comment]
See https://github.com/github/hub/issues/1594#issuecomment-336526427
@hovissimo I think you can close your issue ;)

**Comment by mislav** [comment]
Thanks for reporting. The case-insensitive match for template path was added in 12b388b5d41160b6307bd8cc7a5ec51be2a2634b. This shouldn't be an issue in master branch anymore and in the next release. Please reopen if you've found otherwise!

**Comment by hovissimo** [comment]
Confirmed working as expected in 2.3.0
