### ISSUE TITLE
hub pull-request: Remove the "Signed-off-by: NAME <email@email.foo)" line

### ISSUE THREAD

**Issue by ahmetb** [github/hub#1724]
I frequently use `git commit -S && git push my-fork && hub pull-request` flow.

However the `hub pull-request` command copies all of the commit message to the pull request message editor. This includes the line like:

        Signed-off-by: Ahmet Alp Balkan <ahmetb@example.com>

And since my email is in there, it accidentally leaks to the PR description every now and then which makes it more susceptible to spam.

Would you be OK with having code that excludes the `^Signed-off-by\:` lines from the suggested PR description? I believe the PR description only goes to the GitHub UI and doesn't have much to do with the actual commit object.

**Comment by ahmetb** [comment]
Pinging for interest.

**Comment by mislav** [comment]
This is a good suggestion. Thanks for bringing this up!

Not sure when I can get to this, but PRs welcome in the meantime.
