### ISSUE TITLE
Feature request: allow to organize a pull request in a custom order to make code reviews easier

### ISSUE THREAD

**Issue by noam-arad** [github/hub#1725]
In our workflow we open a pull request on github and then like to go over it for a code review.
It would help if we can define a different order of files than the one given so the developer can set a logical code review that fits their flow.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!

**Comment by noam-arad** [comment]
Thanks for the clarification.
Will do
