### ISSUE TITLE
Failed to perform hub pull-request 

### ISSUE THREAD

**Issue by iceyuki91** [github/hub#1726]
Hi Hub Team, 

When I run the commands below why it returning "Requires authentication"? 
I am the owner of the organization and the repository. This is in enterprise GitHub. 

hubPRReqeustSample (upgrade)$ hub pull-request -m "testing pull request" -b dmo -h upgrade
github.hpe.com username: yuki-tang
github.hpe.com password for yuki-tang (never stored):
Error creating pull request: Unauthorized (HTTP 401)
Requires authentication

$ hub version
git version 2.17.0.windows.1
hub version 2.2.9

Please help me.... thanks.. 

Best regards,
Yuki Tang

**Comment by mislav** [comment]
Does your Enterprise instance allow logging in via username and password, or does it have additional log in steps?

You can try adding this to your `~/.config/hub`:

```yml
github.hpe.com:
- user: yuki-tang
  oauth_token: YOUR_PERSONAL_ACCESS_TOKEN
  protocol: https
```

The personal access token you can generate from your Setttings through the web interface.
