### ISSUE TITLE
Add SSHFP records to DNS

### ISSUE THREAD

**Issue by foxycode** [github/hub#1728]
It would be great if you could add `SSHFP` records to your DNS. In these days, it's pretty normal to use `VerifyHostKeyDNS yes` in SSH client, so no more manual confirmations of host key fingerprint is necessary.

```
The authenticity of host 'bitbucket.org (104.192.143.1)' can't be established.
RSA key fingerprint is 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40.
No matching host key fingerprint found in DNS.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
