### ISSUE TITLE
When I want to make new angular app using angular-cli it gaves me following error.

### ISSUE THREAD

**Issue by MalikYousaf512** [github/hub#1736]
gyp verb build dir attempting to create "build" dir: /home/malik/Desktop/angular-app/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/malik/Desktop/angular-app/node_modules/node-sass/build'
gyp ERR! System Linux 4.13.0-39-generic
gyp ERR! command "/usr/bin/node" "/home/malik/Desktop/angular-app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/malik/Desktop/angular-app/node_modules/node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/malik/.npm/_logs/2018-05-04T14_39_57_279Z-debug.log
Package install failed, see above.

**Comment by salmanulfarzy** [comment]
How is this related to `hub` ? You should report it to the relevant repository.

**Comment by mislav** [comment]
This doesn't seem to be related to the project called `hub` that this issue tracker is for.
