### ISSUE TITLE
Can't use `hub fork` command outside of my terminal

### ISSUE THREAD

**Issue by nikitavoloboev** [github/hub#1739]
I have an issue where if I try to use `hub fork` command not from my terminal but from [another environment](https://forum.keyboardmaestro.com/t/cant-use-hub-fork-command-in-km-and-cant-debug-why/10343) I get access denied error.

I am not sure what I should source or do to make the error go away. I checked and I don't even have `~/.config/hub` config file.

However this `hub fork` command works when run from my terminal.

What is it that I should source or do to make this command work and not throw this error:

```bash
github.com username: github.com password for  (never stored): Error forking repository: Unauthorized (HTTP 401)
Requires authentication
```

**Comment by mislav** [comment]
hub commands such as `hub fork` don't necessarily need to be run while attached to a terminal, but they do need some environment variables, such as `HOME` to find your `$HOME/.config/hub` configuration file where OAuth token is stored. Alternatively you can ensure that `GITHUB_TOKEN` is set, if you don't want to rely on having `$HOME/.config/hub` file. When `GITHUB_TOKEN` is detected, its value is used as the OAuth token and you're never prompted for username/password.
