### ISSUE TITLE
hub pull-request - omit open the editor if -F or -m is used

### ISSUE THREAD

**Issue by szuecs** [github/hub#1741]
I would like to have a non-interactive script that creates GH PRs and hub always opens the editor no matter what flags you pass. -F or -m should both ommit the editor workflow in my opinion.

I had no luck in using the usual workarounds unsetting $VISUAL or $EDITOR in a non-interactive script or try hack around with /edv/stdin. hub is not very unix like :(

    export EDITOR=""
    export VISUAL=""
    echo "a title\n\nsome body.." >/tmp/msg
    hub pull-request -b base -h myhead -F /tmp/msg
    hint: Waiting for your editor to close the file... fatal: cannot run : No such file or directory
    error: unable to start editor ''
    Not committing merge; use 'git commit' to complete the merge.

**Comment by mislav** [comment]
The editor is not opened when `-m` or `-F` are passed and [we have tests that verify this](https://github.com/github/hub/blob/846f9944cd7b150f4b6e0f08aefb5b51b94419b7/features/pull_request.feature#L312-L330). In fact, to force open the editor in those cases, you have to additionally pass `--edit`.

How these arguments are handled and how the editor is opened has been significantly tweaked in the master branch of these repositories. You might have better luck building hub from master branch or installing the latest prerelease from the Releases section. A new stable release is coming soon.
