### ISSUE TITLE
hub open

### ISSUE THREAD

**Issue by mohsen1** [github/hub#1745]
Add a new command for opening browser with Github Repo URL

**Comment by johnaoss** [comment]
`git browse` already does this!

**Comment by mohsen1** [comment]
Just learned about `git web--browse`. It's super confusing to configure. Something like [open](https://www.npmjs.com/package/open) that just works is more appreciated for hub.

**Comment by johnaoss** [comment]
@mohsen1 apologies for being unclear! Hub has it's own custom version of this command, which just works.

Info ehre: https://hub.github.com/hub.1.html
