### ISSUE TITLE
User experience 

### ISSUE THREAD

**Issue by mhenni** [github/hub#1746]
When I am in the homepage and click on « explore », the menu burger icon changes its location fron left to right. Perhaps, it will be better to keep the same location (left) for the entire user journey. [iPhone : Safari]

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
