### ISSUE TITLE
Flags given to hub stash aren't passed through to git stash

### ISSUE THREAD

**Issue by ViKomprenas** [github/hub#1750]
Self-explanatory.

**Comment by mislav** [comment]
Can you please elaborate, with maybe an example?

hub doesn't affect any `stash` functionality, so any arguments passed to `hub stash` should be forwarded unmodified to `git stash`.

**Comment by ViKomprenas** [comment]
They should be, but they weren't. I'm not entirely sure how to give an example, given that `stash`'s output doesn't change by flags, but you should be able to replicate it pretty easily. Make changes to two files, add one, and use `--keep-index`; if it works, the added changes should be left intact, but in my experience they weren't.

**Comment by mislav** [comment]
I can't replicate this. Are you using the latest version of hub?

Using `HUB_VERBOSE` I can see that the argumens are fowarded to `git stash`:

```
$ HUB_VERBOSE=1 hub stash --keep-index
$ git config alias.stash
$ git stash --keep-index
Saved working directory and index state WIP on master: 87d54b1 Avoid unnecessary trim space from issue/PR templates
```

**Comment by ViKomprenas** [comment]
It works now. I swear it didn't before, but I'll close nonetheless, unless it happens again.
