### ISSUE TITLE
Publish a Snap

### ISSUE THREAD

**Issue by mhalano** [github/hub#1754]
I think would be nice to have a Snap (https://snapcraft.io/store) with automatic update.

**Comment by mislav** [comment]
It would be nice! Any takers?

**Comment by mislav** [comment]
On the other hand, it doesn't seem to me that Snap is appropriate for command-line applications. How would `hub` invoked from a command line inside a Docker container access the files in the current git repository?

Please reopen if you have more concrete ideas (and perhaps willingness) to set up a snap.

**Comment by mhalano** [comment]
@mislav 
Snaps aren't Docker containers. Has some mechanisms to limit access to some system resources, but you can allow access for things like home directory, some devices and so on. In the worst case it's possible to install hub Snap using "--classic" option to install with full access.

**Comment by mhalano** [comment]
Please reopen this bug if my explanation was satisfied.

**Comment by mislav** [comment]
@mhalano Can you link to some examples of snaps that are CLI applications or developer tools and not a standalone app like those featured in the store?

Is there some documentation as to what is appropriate or not appropriate to package as a snap?

**Comment by mhalano** [comment]
@mislav 
Here two examples CLI apps packaged as Snaps:
https://snapcraft.io/kubectl
https://snapcraft.io/bw
Here a tutorial to create a simple Snap: https://docs.snapcraft.io/build-snaps/your-first-snap
I don't think there is a documentation about what is appropriate, but CLI tools seems good candidates because the fast pace of updates.

**Comment by anthonyfok** [comment]
There is also

* https://snapcraft.io/hugo, Hugo static website generator (https://gohugo.io/), a CLI application written in Go, is also available as a Snap, thanks to Canonical developer @dholbach who first contributed a working snapcraft.yaml to us in September 2016.

So, yes, both CLI and GUI applications are perfect for Snaps.

**Comment by mislav** [comment]
@mhalano @anthonyfok Interesting! https://github.com/gohugoio/hugo/blob/master/snapcraft.yaml

**Comment by mislav** [comment]
https://github.com/github/hub/pull/1968
