### ISSUE TITLE
Does hub pull-request support --open?

### ISSUE THREAD

**Issue by dwijnand** [github/hub#1755]
The [v2.3.0](https://github.com/github/hub/releases/tag/v2.3.0) release notes state that:

> `hub pull-request` now supports `--push` and `--open` flags to push the head branch to the remote and open the resulting PR in a web browser, respectively.

However when I run it I get:

```
$ git pull-request --open
unknown flag: --open

Usage: hub pull-request [-focp] [-b <BASE>] [-h <HEAD>] [-r <REVIEWERS> ] [-a <ASSIGNEES>] [-M <MILESTONE>] [-l <LABELS>]
       hub pull-request -m <MESSAGE>
       hub pull-request -F <FILE> [--edit]
       hub pull-request -i <ISSUE>
```

I don't think the release notes are referring to `-o`/`--browse` as that's been there since v1.12.0 4 years ago. https://github.com/github/hub/commit/ea741028e75c9db571c7c179042a21b4f921d66b

So what are the release notes referring to?

**Comment by mislav** [comment]
Good point; this was a mixup in my head when I was compiling release notes. I was having the `-o` flag in my mind and expanded it to `--open`, and forgot that this flag was already around for a long time. I'm going to remove it from release notes. Thank you!
