### ISSUE TITLE
"cannot find the path specified" doing `pull-request` on windows

### ISSUE THREAD

**Issue by ssfrr** [github/hub#1759]
When I try to create a pull request in windows with `hub pull-request` (using either MSYS2 or powershell) I get the error:

```
open /c/Users/sfr/.julia/v0.6/DSP: The system cannot find the path specified.
```

I have a [full strace output](https://gist.github.com/ssfrr/721592ae04feb5f75955db6cdaf16803) if that's useful.

The fact that I get the same error when running from Powershell seems to indicate that it's somehow tapping into the MSYS system to get the directory, even when run from Powershell. Any ideas where this unixy path is coming from? My guess is that `hub` is getting the unix path from somewhere and then handing it to a windows `open` call that doesn't understand it. Looking at the `strace` output it does look like sometimes the path is getting coverted to the windows format, but maybe there's somewhere where it isn't.

**Comment by mislav** [comment]
Thank you for reporting.

1. Which `hub version` are you using? How did you install it?
2. Were there any arguments passed to `hub pull-request`?
2. Does the `/c/Users/sfr/.julia/v0.6/DSP` directory have any connection to your current directory/repo?
3. What is your `git var GIT_EDITOR`?

**Comment by mislav** [comment]
Closing this due to lack of info.
