### ISSUE TITLE
Creating a pull request without confirming the commit message

### ISSUE THREAD

**Issue by mvdan** [github/hub#1760]
I very often create PRs with a single commit, and the way that `hub pull-request` takes the commit message as the PR title and body is great.

However, it also opens my editor, presumably so that I can confirm that I am happy with the message. I'd like to be able to skip that somehow.

I don't mind exactly how that happens. Maybe it should never happen for single-commit PRs. Or maybe there's a magic `EDITOR` env var I could use to stop it. Or maybe I should be using a hacky workaround with the `-m` option.

**Comment by mislav** [comment]
See https://github.com/github/hub/pull/1734

**Comment by mvdan** [comment]
Thanks! I missed that in my search.
