### ISSUE TITLE
Lookup a Pull Request Diff & Number by Branch Name

### ISSUE THREAD

**Issue by michaelbutler** [github/hub#1762]
Hi, I have a specific use case that 1. I'm not sure if `hub` can handle, and 2. if it's even in the "spirit" of what `hub` does.

Let's say I have a very shallow code checkout of a repo, just depth=1 (I might even only have the code itself, no `.git` data), and I have the Repo name, Org name, access token, and branch name.  Can I use `hub` to query the github API to find a pull request that matches this branch name? And thus print that pull request number and pull request diff. I'm currently doing this manually with a utility that hits the API for pull requests, searching by that branch name. 

If `hub` doesn't have this, would you accept a pull request for this or does it go against/outside what it was designed for?

Thank you.

**Comment by mislav** [comment]
Within that project's local git checkout, as long as the "origin" remote points to the correct GitHub repo, you can do this:

```sh
head_branch="OWNER:BRANCH"
remote="origin"

pull_info="$(hub pr list -L1 --format='%I:%B' --head="$head_branch")"
if [ -z "$pull_info" ]; then
  echo "pull request matching branch '$head_branch' not found" >&2
  exit 1
fi

pull_id="${pull_info%:*}"
pull_base="${pull_info#*:}"

echo "found PR #$pull_id"
git fetch -q "$remote" "+refs/heads/$pull_base:refs/remotes/$remote/$pull_base" "+refs/pull/$pull_id/head:refs/pr/$pull_id"
git diff "$remote/$pull_base"..."refs/pr/$pull_id"
```
