### ISSUE TITLE
Feature request: cherry-pick by hash from anywhere without adding remote

### ISSUE THREAD

**Issue by Pr0methean** [github/hub#1763]
It'd be handy if Hub would wrap commands such as `cherry-pick` and `diff` so that, when they referred to a commit hash that wasn't found in the repo or in any remote, all public Github repos were searched for the hash and it was fetched from the first one that matched. Then one wouldn't have to copy and paste both a repo URL and a hash, or add a remote that was only being used once. Isn't the theory behind using commit hashes that they are globally unique?

Maybe this could also work with private repos for logged-in users; that would be handy for large teams.

**Comment by mislav** [comment]
Hi, thank you for the feature idea. I don't fully understand the use-case. The feature of cherry-picking URLs in hub came from the idea that, if you're browsing GitHub and see a commit (possibly from a fork) that you would like to apply locally, you could just copy/paste the URL and hub would take care of it automatically. There are no new leftover git remotes after a `hub cherry-pick` operation.

While your idea is certainly possible (GitHub search can find commits by SHA), I don't understand how you might have ended up with a SHA from another repo, but not have its full URL. Also, SHAs are [not globally unique](https://stackoverflow.com/a/34764586).

**Comment by Pr0methean** [comment]
I'm talking about full hashes, not prefixes (which I'm sure would at least have to be longer than the 8 hexdigits GitHub usually shows). Full hashes will almost certainly never collide, until an attack is found that gets past Git's SHAtter detection, at which point GitHub will have to replace SHA1 anyway.

**Comment by mislav** [comment]
@Pr0methean And how would a person obtain full SHAs to paste to a `cherry-pick` or `diff` command, but not obtain the URL of the repository that they came from?

I'm just not convinced that this feature would be useful enough to warrant being mantained.

**Comment by mislav** [comment]
Closing as something that I don't see as a good fit for hub core. Thank you for suggesting!
