### ISSUE TITLE
`hub release` can no longer attach whole folders

### ISSUE THREAD

**Issue by shekibobo** [github/hub#1769]
Part of my release script includes the line:

```bash
hub release create -a app/apks/all-*/ -m "Release v$1" v$1;
```

It worked fine when uploading multiple files inside the directory as of May 29th, but as of at least June 5th, I get the error:

```bash
Attaching release asset `app/apks/all-20300-v0.2.3.0-0-g1acfeac20a/'...
Error uploading release asset: Post https://uploads.github.com/repos/myorg/my-project/releases/000000000/assets?name=all-20300-v0.2.3.0-0-g1acfeac20a: read app/apks/all-20300-v0.2.3.0-0-g1acfeac20a/: is a directory
```

This was never a problem in the past, and by using a folder as the `-a` argument it would upload each file in that folder as part of the release process.

Haven't looked it over in detail, but it appears #1095 is probably where this change happened.

**Comment by mislav** [comment]
Sorry for the breakage! Is it an option for you to make a script that wraps `hub release` and lists all the attached files individually by doing `-a <file1> -a <file2> -a ...`? I've intentionally removed the directory feature in favor of listing all attached files explicitly.

**Comment by shekibobo** [comment]
I might be able to, the script is just a bunch of commands `&&`'d together, so it'll take a little more effort to do it.

**Comment by mislav** [comment]
This script should suffice with bash 3.2:

```sh
tag_name="v$1"
asset_dir="./pkg"

assets=()
for f in "$asset_dir"/*; do [ -f "$f" ] && assets+=(-a "$f"); done

hub release create "${assets[@]}" -m "Release $tag_name" "$tag_name"
```

Attaching whole directories likely won't be making a comeback since we encourage setting human-readable labels for assets in form of `-a "path/to/file.tgz#My Label"`, and that is only possible if there is one `-a` entry per file.
