### ISSUE TITLE
hub pull-request -i <number> throws error

### ISSUE THREAD

**Issue by borice** [github/hub#1770]
I wanted to [convert an issue into a pull request](https://opensoul.org/2012/11/09/convert-a-github-issue-into-a-pull-request/) and tried
```
$ hub pull-request -i 741
Error creating pull request: Unprocessable Entity (HTTP 422)
Not allowed to change field "issue"
```

I am properly authenticated and `hub` command otherwise works well.
Any ideas?

here's the output of `git remote -v`, and my current branch is `replaceRoot-op` which is tracking the same branch in my fork.
```
$ git remote -v
borice	git@github.com:borice/ReactiveMongo.git (fetch)
borice	git@github.com:borice/ReactiveMongo.git (push)
origin	git://github.com/ReactiveMongo/ReactiveMongo.git (fetch)
origin	git://github.com/ReactiveMongo/ReactiveMongo.git (push)
```

Thank you.

**Comment by mislav** [comment]
It looks like https://github.com/ReactiveMongo/ReactiveMongo/issues/741 is a closed issue that does not belong to you. I think you can only convert issues that are open and belong to you. Anyway, converting an issue to a PR request is deprecated and might not work in the future.
