### ISSUE TITLE
Avoid to pass `--cmd` to non-vim-s vi-s

### ISSUE THREAD

**Issue by iamleot** [github/hub#1772]
Hello to the entire hub community,
AFAIK not every `vi`-s support the `--cmd` option and the current arguments
appended in [openTextEditor()](https://github.com/github/hub/blob/0ef312ec03553ba858da74fed2b4b98e50769cca/github/editor.go#L130).

At least with [vi(1)](http://man.NetBSD.org/cgi-bin/man-cgi?vi+1) on NetBSD doing `hub pull-request` fails with:

````
% hub pull-request
vi: unknown option -- -
usage: ex [-eFRrSsv] [-c command] [-t tag] [-w size] [file ...]
usage: vi [-eFlRrSv] [-c command] [-t tag] [-w size] [file ...]
error using text editor for pull request message
````

At the moment we've patched that in the [pkgsrc](https://www.pkgsrc.org/) [net/hub](https://pkgsrc.se/net/hub) package changing the regular expression in [openTextEditor()](https://github.com/github/hub/blob/0ef312ec03553ba858da74fed2b4b98e50769cca/github/editor.go#L132) to not match `vi` (i.e. `\b(?:[gm]?vim)(?:\.exe)?$`).

Could such patch be acceptable?
Please let me know and I will try to fill a pull request if needed.

Thank you!

**Comment by mislav** [comment]
We would accept a patch to stop matching `vi` and just match `vim` instead! Thank you
