### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by mike011** [github/hub#1774]
When my team creates a pull-request it uses a .github/PULL_REQUEST_TEMPLATE. Is there a way to use hub to use the template?

**Comment by mislav** [comment]
Yes, if you use the latest version of hub and do `hub pull-request` without passing the `-m` or `-F` parameters, the text editor will open and the pull request template will be used.

**Comment by mike011** [comment]
Thank you so much, I've upgraded and tried it out and it's exactly what I'm looking for.
