### ISSUE TITLE
`hub pull-request` fails with an obscure error if the branch hasn't been pushed

### ISSUE THREAD

**Issue by vcarl** [github/hub#1776]
Per #1715 the error message received when the branch hasn't been pushed does not make it clear what the problem is. It seems the error message comes from [line 356](https://github.com/github/hub/blob/master/commands/pull_request.go#L356). I'm not familiar enough to know offhand if this error handling might be triggered by something other than a branch that hasn't been pushed, but changing it to 

`Invalid value for "head", did you push your branch to the remote?`

would be very helpful. I'm happy to change the error if that's all that's needed, but I'm not very comfortable in Go.

**Comment by mxplusb** [comment]
I have also ran into this error before and it led me here. Not a great UX.

**Comment by mislav** [comment]
This was fixed in https://github.com/github/hub/pull/2062
