### ISSUE TITLE
CONTRIBUTING.md: Instruction on signing the GitHub CLA now obsolete?

### ISSUE THREAD

**Issue by anthonyfok** [github/hub#1781]
In CONTRIBUTING.md, the following paragraph, originally written in 2015, seems outdated:

> ```markdown
> We will also require you to sign the [GitHub Contributor License Agreement](https://cla.github.com/)
> after you submit your first pull request to this project. The link to sign the
> agreement will be presented to you in the web interface of the pull request.
> ```

But https://cla.github.com/ now shows a 404 page, and there is no link to sign the CLA on the pull request web page.

I then found a similar issue at github/choosealicense.com#576

Thanks!

**Comment by mislav** [comment]
Thank you!
