### ISSUE TITLE
[Feature request] Allow configuring which remote is used

### ISSUE THREAD

**Issue by KTAtkinson** [github/hub#1785]
No most of my repositories I have no remote called 'origin' this seems to break most of hubs functionality. It would be really nice if the remote used were configurable.

Note, this is related to [this](https://github.com/github/hub/issues/1784) issue where errors are inconsistent it the case where a remote named `origin` is not defined.

**Comment by mislav** [comment]
Related: https://github.com/github/hub/pull/1342#issuecomment-261551166

**Comment by mislav** [comment]
Cleaning up as duplicate
