### ISSUE TITLE
Auto-completion stop to work with Git version 2.18.0

### ISSUE THREAD

**Issue by arturoherrero** [github/hub#1792]
I use macOS and Homebrew to install/update Git and hub.

After upgrade Git (`brew upgrade git`) from version `2.17.1` to `2.18.0` the auto-completion of the GitHub commands provided by hub (`browse`, `ci-status`, `compare`, etc...) stop to work in Bash.

Previous configuration with auto-completion working:
```
$ git --version
git version 2.17.1
hub version 2.4.0
```

Current configuration with auto-completion not working:
```
$ git --version
git version 2.18.0
hub version 2.4.0
```

I was able to reproduce the error in two different machines.

**Comment by mislav** [comment]
Thank you for reporting! I can see the same.

**Comment by davishmcclurg** [comment]
@mislav I'm still having this issue using hub 2.5.0:

```
$ hub version
git version 2.18.0
hub version 2.5.0
$ cat ~/.bash_profile
source /usr/local/etc/bash_completion.d/git-completion.bash
source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
```

**Comment by mislav** [comment]
@davishmcclurg Unfortunately, the new workaround in hub 2.5.0 will only work when hub is aliased as `git`, even if the command invoked is `hub`. This is sub-optimal and PRs to improve this are welcome.

```sh
# without alias
$ hub p
pull      push

$ alias git=hub
$ hub p
pr        pull           pull-request   push
```

**Comment by davishmcclurg** [comment]
Ok, that works. Thanks @mislav!

**Comment by mislav** [comment]
Gonna reopen this until alias is no longer needed

**Comment by engnakagawa** [comment]
I did set ```alias git=hub```.
But, zsh compiletoin is not work. 

Environment

```
❯ brew info zsh-completion
zsh-completions: stable 0.27.0, HEAD

❯ hub --version
git version 2.18.0
hub version 2.5.0
```

**Comment by apjanke** [comment]
> Should I talk about zsh-completion here?

zsh-completion is not relevant. But whether you have the Git-provided `_git` completion or the `_zsh`-provided one is. What is your zsh `$fpath` value, and is `/usr/local/share/zsh/site-functions/_zsh` present, and if so, what does it point to?

hub folks: what do you think about extending `hub --version` to examine its zsh environment and print an indication of which source of `_zsh` completion functions it's working with?

**Comment by ushuz** [comment]
Alias stops working for me recently.

**Comment by arturoherrero** [comment]
Same here @ushuz
```
$ git --version
git version 2.22.0
hub version 2.12.0
```

**Comment by mislav** [comment]
I get this with hub 2.12.0 and bash 3.2 on macOS:

```console
$ alias git=hub
$ hub pu
pull           pull-request   push
```

@ushuz @arturoherrero Could you provide more information about your shell, OS, and how you installed hub and shell completions? Thanks

**Comment by mislav** [comment]
Ah I see it now when I upgrade to git 2.22:

```console
$ hub pu
pull   push
```

git must have changed something *again* in how they organize their shell completions. I think it's too risky that we build on top of their completion script, but then again I have no other ideas on how to hook into git's completions to inject extra hub stuff.

**Comment by yasuoza** [comment]
Hotfix

```
alias __git=hub
```

FYI: https://github.com/git/git/blob/7c20df8/contrib/completion/git-completion.bash#L1029

**Comment by mgabeler-lee-6rs** [comment]
@yasuoza I suspect that will break some use cases because: https://github.com/git/git/blob/7c20df8/contrib/completion/git-completion.bash#L90

**Comment by knightofiam** [comment]
Just in case this saves anyone time - these tips may seem obvious, but so many people including myself are struggling to get this working.

1. The alias workaround must occur before the sourcing of any `git-completion` script (e.g., in `~/.bash_profile`).

2. In your excitement, don't forget to `source ~/.bash_profile` (or whatever your shell config file is), or open a new terminal window before testing it out.

3. With the alias workaround, you don't need anything like this:
```
if [ -f $(brew --prefix)/etc/bash_completion.d/hub.bash_completion.sh ]; then
  . $(brew --prefix)/etc/bash_completion.d/hub.bash_completion.sh
fi
```

@mislav Any update on #1995?

**Comment by radiospiel** [comment]
Neither works here. This is macOS 11.4 on a Silicon M1 machine.

This is with home-brew in /opt/homebrew, and with 

```
0:00 ~ > hub version
git version 2.31.1
hub version refs/heads/master
0:00 ~ >

**Comment by radiospiel** [comment]
Also doesn't work with the very latest git version on home-brew (2.32.0). I accidentally also discovered that running `hub`, even without any arguments and any attempt to autocomplete, kills my iTerm session, when both `__git` and `git` are aliased to `hub`.

**Comment by aquadesk** [comment]
```
hub --version
git version 2.32.1 (Apple Git-133)
hub version refs/heads/master
```

I have this
```
alias git=hub
```

when I tab on this 
```
git [cursor]
```

it gives

```
git (eval):1: command not found: _hub
(eval):1: command not found: _hub
(eval):1: command not found: _hub
```

I don't know how to fix it

I am using mac os silicon M1
