### ISSUE TITLE
Removing Sensitive Information from Github Issue Edit History

### ISSUE THREAD

**Issue by IRobL** [github/hub#1796]
Now that GitHub is a Microsoft product and has introduced an edit history, how can I remove sensitive elements of my issue comment that contain sensitive information?

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!

**Comment by IRobL** [comment]
Oh thanks, I hadn't realized.  You all do great work on this command, btw!
