### ISSUE TITLE
Open the page to create the pull request on GitHub

### ISSUE THREAD

**Issue by dylan-chong** [github/hub#1803]
When I use the `hub pull-request` command, I have to enter my username and password. This removes the convenience of having the command in the first place.

Is there a way to simply open the new pull request page on GitHub in the browser? And also is there a way to select which browser gets opened?

**Comment by mislav** [comment]
> When I use the `hub pull-request` command, I have to enter my username and password.

It's only required once. After that, username and password is exchanged for a token that's stored locally and you're never prompted for username and password again.

> Is there a way to simply open the new pull request page on GitHub in the browser?

Yes, without `hub` it would be something like:

```
# push the current branch
git push -u origin HEAD

# on macOS, use open
open https://github.com/OWNER/REPO/pull/BRANCH

# to select a browser
open -a Safari https://...
```

I don't know what's the equivalent of `open` on other platforms.
