### ISSUE TITLE
Guarding pull-request -> issue conversion

### ISSUE THREAD

**Issue by imranolas** [github/hub#1806]
Could I request messaging or a prompt when using the `-i` flag on creating pull requests? I mistakenly expected a reference to the issue and was surprised when the issue was converted with no way to revert.

**Comment by mislav** [comment]
I'm sorry this has happened to you. The documenation is pretty clear: “Convert issue to a pull request.” It also says that it's deprecated. There will be no prompt, but this feature might get removed soon.
