### ISSUE TITLE
Filtering Issues by Creator

### ISSUE THREAD

**Issue by igbanam** [github/hub#1807]
Could hub filter the issues by the person who created the issue?

So a `--author igbanam` should filter all the issues I created?

There are other spin-offs from this …like

- filter based on time created
- filter on the issues which a user is subscribed to
- do all these filtering for PRs too

**Comment by mislav** [comment]
This isn't supported yet! Implementation ideas, contributions welcome.

In the meantime:

```
hub issue --format='%au %<(8)%i %t%n' | grep ^igbanam
```

**Comment by igbanam** [comment]
I do not know Go. If I did, I'd have built this out.

**Comment by igbanam** [comment]
Actually, reading through the code shows this feature already exists

```
hub issue -c igbanam
hub issue -@ igbanam
```

there's also an `--include-pulls` to include PRs

**Comment by igbanam** [comment]
There's no filtering with the PR command, but you can use `--include-pulls` to get this done

Well done team!
