### ISSUE TITLE
Is there a way to use hub with github:enterprise?

### ISSUE THREAD

**Issue by boiler23** [github/hub#181]
Hello, I would like to use hub with github:enterprise.
Is it possible?
Actually, I only need to replace github.com with my corporate github URL.

**Comment by fangmobile** [comment]
is there a way to change the default to my enterprise git?
the current default is ok for my own mac , but on my work mac I only do enterprise
typing it every time is a pain.

**Comment by mislav** [comment]
@fangmobile You could add `export GITHUB_HOST=my.git.org` to your `.bash_profile` or whatever the shell configuration file you're using.
