### ISSUE TITLE
hub clone does not document used protocol

### ISSUE THREAD

**Issue by p-mongo** [github/hub#1813]
https://hub.github.com/hub-clone.1.html says nothing about which protocol (git/https/ssh) is used by hub by default, or how to make it use another protocol. Specifically:

1. `hub clone my-repo` appears to always use ssh, even if I don't have ssh keys configured, and fails in the latter case even if my-repo is public.
2. `hub clone p-mongo/my-repo` still uses ssh. I need to give a full `hub clone https://github.com/p-mongo/my-repo` to make it use https at which point there's no benefit to hub over git.
3. It seems that if I have push access to the repo, it's cloned via ssh, otherwise it's cloned via git. The documentation does not state this.

**Comment by p-mongo** [comment]
It wasn't obvious to me from looking at clone man page that hub man page had protocol information.

**Comment by mislav** [comment]
Many hub commands respect the same protocol-choosing logic, including `hub clone`. Therefore we can't just cover it in `clone` documentation, but maybe it's a good idea to at least mention reading this section in `hub(1)`. Will keep this in mind, thank you!

**Comment by p-mongo** [comment]
Thanks!
