### ISSUE TITLE
List PRs by author and merged state

### ISSUE THREAD

**Issue by DennisSchiefer** [github/hub#1815]
I would love to see the `hub pr list` functionality expanded. In particular, I am looking for the following:

- filter PRs by author
- retrieve PRs by time (currently it seems only the last X PRs are listed)
- filter PRs by whether it was merged into master or just closed

I am currently using hub 2.5.0, git 2.18.0

**Comment by mislav** [comment]
1. Filtering by author was requested before, but it's not supported by the [current API endpoint](https://developer.github.com/v3/pulls/#list-pull-requests) that we use. We would have to switch to using the Search functionality instead. Two workarounds are listed here: https://github.com/github/hub/issues/1807#issuecomment-404326750

2. <q>Retrieve PRs by time</q> – what do you mean by this?  We support these options:
	```
	-o, --sort <SORT_KEY>
		Sort displayed issues by "created" (default), "updated", "popularity", or "long-running".

	-^ --sort-ascending
		Sort by ascending dates instead of descending.
	```

    <q>it seems only the last X PRs are listed</q> – all PRs are listed unless you pass the `-L|--limit` parameter.

3. <q>filter PRs by whether it was merged</q> – again, our API endpoint doesn't seem to accept the `--state merged` parameter the same way it supports `--state closed`.

**Comment by DennisSchiefer** [comment]
1. I see. Then I'll have to stay with grep. I just thought that it would be more efficient if Github was able to do the filtering.

2. My bad. I believe I know what went wrong. Your default is to only list open PRs, correct? That had me confused. Then I'll change my ask: Is there a way to get any PR? As a workaround I can always run the command multiple times, once for each state, though.

3. Too bad. Let's hope that Github exposes that functionality eventually.

**Comment by mislav** [comment]
> 2\. Is there a way to get any PR?

`hub pr list --state all`

**Comment by indigoviolet** [comment]
Is it possible to get the *tail* of the list with `-L` passed in? I would have expected that `--sort-ascending --limit` would do that, but it appears that the limit is applied before the sort.

**Comment by mislav** [comment]
@indigoviolet Does `hub pr list -^ -L 5` not work?

**Comment by indigoviolet** [comment]
@mislav --sort-ascending does nothing when combined with limit  
```
❯ hub pr list -s closed -L 10 -o updated --sort-ascending
      #7  dockerize
     #24  Ak/begin integration of legacy code
     #30  Ak/messages and threads
     #11  Use browserify
     #12  React
     #13  Agent can update an entry for a user.
     #15  Agent can see a list of tags in the first column [#96715672]
     #14  Auto update entry form 96617096
     #17  Filter entries by tags 96716034
     #16  Tag entry 96715828

~/fin/fin-core-beta vi-required-default-pref-fields ⇡
❯ hub pr list -s closed -L 10 -o updated
      #7  dockerize
     #24  Ak/begin integration of legacy code
     #30  Ak/messages and threads
     #11  Use browserify
     #12  React
     #13  Agent can update an entry for a user.
     #15  Agent can see a list of tags in the first column [#96715672]
     #14  Auto update entry form 96617096
     #17  Filter entries by tags 96716034
     #16  Tag entry 96715828
```

**Comment by mislav** [comment]
@indigoviolet Ah I see. The output of the 1st command is correct (PRs were sorted by last updated date, ascending), but the output of the 2nd command was incorrect. I have pushed the fix to the master branch.

**Comment by itaranto** [comment]
Great! I'm looking forward to use this feature!

**Comment by mislav** [comment]
* `--state merged` is now supported
* Listing PRs by author is still not supported, but now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3

For example, using search functionality in GraphQL:

```sh
hub api -t graphql -f q="author:mislav repo:github/hub is:pr" -f query='
  query($q: String!, $n: Int = 10, $after: String) {
    search(query:$q, type: ISSUE, first: $n, after: $after) {
      edges {
        node {
          ...on PullRequest {
            url
            state
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
'
```
