### ISSUE TITLE
pull-request pass credentials from cmd

### ISSUE THREAD

**Issue by bmihaescu** [github/hub#1829]
Hi,

Is there a way to pass the username and password for the github repo from the cmd ?

Something like this 
hub pull-request -m "merge into master" -b master -h staging -user USERNAME -pass PASSWORD

Or to get them from a file 

Thanks

**Comment by mislav** [comment]
https://hub.github.com/hub.1.html:
```
GITHUB_USER=bmihaescu GITHUB_PASSWORD=*** hub pull-request ...
```

You only have to supply username/password once, after which your token is saved to `~/.config/hub`.

Alternatively, you can also supply `GITHUB_TOKEN` (a Personal Access Token), which avoids saving to and reading from `~/.config/hub` altogether.
