### ISSUE TITLE
Issue template cached unexpectedly in github website

### ISSUE THREAD

**Issue by adolli** [github/hub#1833]
I am sorry for that I cannot find a proper repo to open this issue. Close it if disturbs.

How to reproduce:
1. choose one template and delete all its contents.

![image](https://user-images.githubusercontent.com/8390109/44087384-462d5ae2-9ff2-11e8-910c-215aaf9f7453.png)

2. go back to any other pages or refresh if u wish.
1. no matter choosing any templates, there is no contents in it.

![image](https://user-images.githubusercontent.com/8390109/44085593-9af5ab70-9fec-11e8-8b45-df4354da265c.png)

![image](https://user-images.githubusercontent.com/8390109/44085655-c4073c86-9fec-11e8-8dd1-209f5f8462ba.png)

It's ok for me to clear my browser cache.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
