### ISSUE TITLE
Error requesting reviewer: json: cannot unmarshal string into Go struct field errorInfo.errors of type github.fieldError

### ISSUE THREAD

**Issue by pedrohc** [github/hub#1840]
$ hub pull-request -r cve-list
Error requesting reviewer: json: cannot unmarshal string into Go struct field errorInfo.errors of type github.fieldError (HTTP 422)

The pull-request was still created though, but the error makes automation hiccup.

**Comment by mislav** [comment]
Thank you for reporting!

1. Which `hub version` is this with?
2. Is the repository on github.com or GitHub Enterprise? If so, which GHE version?
3. If you use `HUB_VERBOSE=1 hub pull-request -r ...`, can you see what was the final response from the server and share it with us?

**Comment by pedrohc** [comment]
1.
$ hub --version
git version 2.14.4
hub version 2.5.0

2.
Its on github.com.

3.
$ HUB_VERBOSE=1 hub pull-request -r user
[...]
< HTTP 422
{"message":"Validation Failed","errors":["Could not add requested reviewers to pull request."],"documentation_url":"https://developer.github.com/v3/pulls/review_requests/#create-a-review-request"}
Error requesting reviewer: json: cannot unmarshal string into Go struct field errorInfo.errors of type github.fieldError (HTTP 422)

Ps. The reviewer got added to the PR anyway.
This is how its being requested: 
{"reviewers":["user"],"team_reviewers":[]}

**Comment by pedrohc** [comment]
Sorry, I couldn't test in any of those scenarios. The only example I have is requesting one (the same) reviewer.

I'm currently using without -r, which on the repo side gets a default reviewer assigned and don't throw any errors.
