### ISSUE TITLE
Can't post issue in mobile view

### ISSUE THREAD

**Issue by haseebpvt** [github/hub#1841]
I'm using latest version of Chrome in Android phone. The 'New Issue' button is not displaying when using mobile version of github

**Comment by salmanulfarzy** [comment]
I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you @salmanulfarzy!

Tip: the “New issue” button in mobile looks like a ➕icon in the navigation bar.

**Comment by haseebpvt** [comment]
Thank You for the information @salmanulfarzy and @mislav
