### ISSUE TITLE
`hub create` fails to update tracking information for the current branch; makes `git pull` fail

### ISSUE THREAD

**Issue by 9999years** [github/hub#1848]
When I create a repository with `git create`, hub fails to “update tracking information for the current branch”.

Suggested fix: When I run `git create`, update tracking information for the current branch by accomplishing whatever `git branch --set-upstream-to=origin/master master` accomplishes.

Example:

    $ mkdir test
    $ cd test
    $ git init
    Initialized empty Git repository in C:/Users/arvensis/Documents/projects/test/.git/
    $ git create
    Updating origin
    created repository: 9999years/test
    $ git pull
    There is no tracking information for the current branch.
    Please specify which branch you want to merge with.
    See git-pull(1) for details.
    
        git pull <remote> <branch>
    
    If you wish to set tracking information for this branch you can do so with:
    
        git branch --set-upstream-to=origin/<branch> master

**Comment by mislav** [comment]
I don't think this is something that hub needs to address.

When you did `git init`, you initialized an empty git repository. There are no local branches, therefore there is nothing to apply a command such as `git branch --set-upstream-to=origin/master master` or `git pull`.

Note that the remote repository created by `hub create` is also empty, i.e. has no branches. If you used the web interface to create some git commits in the meantime, then the correct approach to check out the master branch for the first time is:

```
git fetch origin master && git checkout master
```

After that, tracking information will be set and you will be able to `git push/pull` without arguments.
