### ISSUE TITLE
Can't link issue to a project in the issue screen

### ISSUE THREAD

**Issue by misha1235000** [github/hub#1862]
### The problem description: (Read the Edit part)
> While creating a new issue, and trying to link this issue to a project, it doesn't give you to do that. (It wont update the project assigned to the issue)

### EDIT:
It does link the issue to the project, only if you click on the text itself.
If you click on the side of the rectangle, then it shows up like you chose it. (with a check)
But it actually doesn't really choose it.

Thank you.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
