### ISSUE TITLE
hub merge PULLREQ-URL not working properly

### ISSUE THREAD

**Issue by JerryGoyal** [github/hub#1863]
`hub merge https://github.com/some_user/some-repo/pull/16724` is not working as expected. from console logs it looks fine:
```
From https://github.com/some_user/some-repo
 * branch                refs/pull/16724/head -> FETCH_HEAD
Auto-merging some_file.txt
Merge made by the 'recursive' strategy.
 some_file.txt | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```
but when I go to PR page it shows that it's still open.

**Comment by mislav** [comment]
Thank you for reporting! The command is working as intended, but the documentation wasn't very clear. I've improved the documentation a bit.
