### ISSUE TITLE
hub-pull-request(1) lacks EXAMPLES section

### ISSUE THREAD

**Issue by RalphCorderoy** [github/hub#1866]
I'm used to clicking GitHub's _Click Pull Request_ button when viewing a branch I've just created on a fork of another's repo. I'd prefer to use the shell and have installed hub 2.5.0-1 on Arch Linux. hub-pull-request(1) doesn't have an EXAMPLES section, like some of the other pages, so it's hard to know what should be specified to duplicate this common action.

**Comment by mislav** [comment]
Thank you for suggesting
