### ISSUE TITLE
Add ability to assign project to pull request

### ISSUE THREAD

**Issue by kirtangajjar** [github/hub#1867]
As we could assign milestone to `pull-request` using `-M` flag, it would be great if I would be able to assign projects to PRs while creating them.

Also if someone could guide me, I can also try to contribute this feature.

**Comment by mislav** [comment]
Duplicate of https://github.com/github/hub/issues/1858

You're welcome to try making this change! The existing code in `commands/pull_request.go` related to assignees/reviewers should guide you.
