### ISSUE TITLE
hub issue behavior

### ISSUE THREAD

**Issue by digitalnoise** [github/hub#1872]
`hub issue` on a forked repo lists all issues on the upstream master, instead of the locally forked repo.

**Comment by mislav** [comment]
Yes this is intended behavior. Have you expected otherwise? If hub's behavior was different here, how would people access the list of issues on the upstream repo?

**Comment by digitalnoise** [comment]
But how would people access the list of issues on the fork itself?  Projects are forked for various reasons, and changes to a specific fork could create issues specific to that fork, but hub doesn't offer any way to access those issues - only on the upstream.

**Comment by mislav** [comment]
That's true, hub doesn't offer any way to access issues on other repos. That's why a flag such as `--remote` could solve this problem. Closing in favor of #1342
