### ISSUE TITLE
Missing documentation around setting assignee

### ISSUE THREAD

**Issue by robcresswell** [github/hub#1874]
There appears to be the ability to set an assignee, introduced over 2 years ago here: https://github.com/github/hub/commit/cdc37ec99eaca5cab78c325ab986bd888c058c24

I can't find anything in the docs to reference this though. Could documentation please be a prerequisite to a feature being "complete"? Even the tests just refer to `<USER>` without any indication of what "USER" is; a username? a full name / email combo as is used in commit messages?

**Comment by mislav** [comment]
`-a`/`--assign` is a comma-separated list of GitHub handles (usernames) to assign to a pull request. See `hub help pull-request` or https://hub.github.com/hub-pull-request.1.html
