### ISSUE TITLE
Saved reply while creating pull request, the shortcut binding takes longer

### ISSUE THREAD

**Issue by VishmayS** [github/hub#1876]
A minor ux issue observered.
For using saved reply using keyboard while creating pull request, the shortcut binding takes longer for loading the reply.
after ctrl+.
ctrl+1
ctrl+2
ctrl+3
etc..

this ctrl+no shortcut is also a used shortcut of chrome which leads to first tab.
So if i try to use the ctrl+.  ctrl+1 combination too fast, it leads me to first tab

so if you perform shortcut binding on for at least blocking ctrl 1,2,3,.. a few from changing tab on "ctrl+."  keyboard event instead of  after loading saved replies, it will be great.
I can use shortcut multiple times when loading take time to load reply only if i'll be on same page

Thanks

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
