### ISSUE TITLE
hub bash completion does not work anymore.

### ISSUE THREAD

**Issue by bellatoris** [github/hub#1879]
### Current Version
```
$ hub --version
git version 2.19.0
hub version 2.5.1
```
### Problem
After this commit git/git@3301d36b29467a05107340e4d9688ebf74335021, a couple of bash functions are removed. (e.g., `__git_commands()` , `__git_list_all_commands()`). 

And hub's bash completion uses `__git_list_all_commands()` now. So hub's bash completions does not work. 

```sh
# in hub.bash_completion.sh

if declare -F _git > /dev/null && ! declare -F __git_list_all_commands_without_hub > /dev/null; then
  # Duplicate and rename the 'list_all_commands' function
  eval "$(declare -f __git_list_all_commands | \
        sed 's/__git_list_all_commands/__git_list_all_commands_without_hub/')"

  __git_list_all_commands() {
    cat <<-EOF
alias
pull-request
pr
issue
release
fork
create
delete
browse
compare
ci-status
sync
EOF
    __git_list_all_commands_without_hub
  }
```

**Comment by mislav** [comment]
Thank you for reporting! See https://github.com/github/hub/issues/1792#issuecomment-403413131

**Comment by bellatoris** [comment]
Thank you!
