### ISSUE TITLE
editting a tagged release always failed at "Unable to find release with tag name `1.3.0'"

### ISSUE THREAD

**Issue by bergwolf** [github/hub#1881]
`hub release edit` claims that it cannot find the tagged release however `hub release show` is able to find it.

```
$hub release edit -a /home/bergwolf/workplace/golang/src/github.com/kata-containers/packaging/release/kata-static-1.3.0-x86_64.tar.xz 1.3.0
Unable to find release with tag name `1.3.0'
$hub release show --show-downloads 1.3.0
Kata Containers 1.3.0

## Downloads

https://api.github.com/repos/kata-containers/runtime/zipball/1.3.0
https://api.github.com/repos/kata-containers/runtime/tarball/1.3.0
```

**Comment by mislav** [comment]
Thanks for reporting!

Could you use `HUB_VERBOSE=1 hub release edit ...` to enable debugging info and check HTTP traffic and report if anything weird stands out?

**Comment by mislav** [comment]
Ah I think I get what's going on. You have multiple git remotes for this repo, and some point to forks. Fixing

**Comment by mislav** [comment]
Fixed in master. To work around your issue until next hub release, either remove other git remotes (unless they're necessary) or change to a branch that has its upstream configuration pointed at the `kata-containers/runtime` repo

**Comment by bergwolf** [comment]
Thanks @mislav ! I confirm it works by changing to a branch that has its upstream pointed at `kata-containers/runtime` repo.
