### ISSUE TITLE
Choose remote to use in `hub issue` and similar commands

### ISSUE THREAD

**Issue by drozdziak1** [github/hub#1882]
# Problem
I have a remote naming workflow I like to use where `origin` is not the upstream repo, and because of that `hub issue` only shows things relevant to my fork which I use as `origin` for arguably compelling reasons (safer force pushes thanks to the stock branch tracking behavior and no remote juggling required when cloning upstream before forking on GitHub)

# Solution ideas
* Add a command-line option for specifying the remote
* Add an env for this so that people can change the behavior permanently

I think both would be nice to have. I'll happily learn your view on this.

**Comment by drozdziak1** [comment]
@mislav Wow, that is quick! Good to know there's a way around my problem, but opinionated naming like that doesn't really cut it for me :( 

Even GitHub itself doesn't require anyone to do anything like this, so why would `hub` need to? Plus git itself has always been team "more than way to do something".

**Comment by drozdziak1** [comment]
Oh, and I call my upstreams `prod` because less typing.

**Comment by drozdziak1** [comment]
Okay, there seems to be a whole different problem with remotes, so my particular case kinda lost its base. `hub` doesn't seem to like SSH remotes anyway and I use keyless SSH auth so that I don't have to trust TLS certs.

**Comment by drozdziak1** [comment]
`git  remote -v`
```plain
jkilpatr	git@github.com:jkilpatr/althea_rs (fetch)
jkilpatr	git@github.com:jkilpatr/althea_rs (push)
kindiana	git@github.com:kingoflolz/althea_rs.git (fetch)
kindiana	git@github.com:kingoflolz/althea_rs.git (push)
origin	git@github.com:drozdziak1/althea_rs.git (fetch)
origin	git@github.com:drozdziak1/althea_rs.git (push)
prod	git@github.com:althea-mesh/althea_rs (fetch)
prod	git@github.com:althea-mesh/althea_rs (push)
upstream	git@github.com/althea-mesh/althea_rs.git (fetch)
upstream	git@github.com/althea-mesh/althea_rs.git (push)
```

**Comment by drozdziak1** [comment]
Crisis averted, it was just the missing `.git`, pushes/pulls would work though. I guess I'll just add a redundant `upstream` remote from now on. But I'd very much appreciate if you guys would consider adding this. Thank you for your time.

**Comment by mislav** [comment]
We're considering adding a flag to specify a remote per-command, and perhaps a system-wide configuration as well either via environment variable or config file #1342

But until then, using this workaround should be best.
