### ISSUE TITLE
Unable to connect to github.com

### ISSUE THREAD

**Issue by gigaga** [github/hub#1884]
Hi support,

Currently, I've a connection error when I try to clone a github repo. I've an error "unable to connect to github.com".

    $ git clone github/hub
    Cloning into 'hub'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.113]: errno=Invalid argument
    github.com[1: 192.30.253.112]: errno=Invalid argument

I'm under Windows and I use hub version 2.5.1

    $ git version
    git version 2.18.0.windows.1
    hub version 2.5.1

Best regards,

**Comment by mislav** [comment]
Sorry, this sounds like a network error and not something that is caused or can be fixed by hub.

BTW, you might want to upgrade hub to its latest version (see the Releases section).
