### ISSUE TITLE
Rebase pull request branch onto target branch

### ISSUE THREAD

**Issue by janpio** [github/hub#1885]
### Motivation

Both as a contributor and a committer and maintainer of Open Source projects I frequently need to make sure my or a Pull Request creator's branch are up to date with the PR target branch (mostly `master`).

This is mostly necessary to get tests passing: The fork / PR branch could have been created from a commit that had failing tests at the time, or the tests started failing in the meantime because of environment changes which need a commit to be fixed. So we have a (probably good) PR sitting there with failing tests, and updating the PR branch would fix that. 

[I know both situations point to a deeper problem that should/could be fixed, but it's the reality now and I have >50 PRs with this state waiting and am looking for a solution]

### Current solution

One way to achieve this is to rebase the PR branch:

a) For contributor's PR branches the usual process is to ask them to please rebase their PR branch - which might or might not help. Quite often you have to explain what rebasing is, how it works etc. This can be _very_ time consuming.  
b) For my own branches I can just check them out, rebase and force-push.  
c) If the contributor [allows changes to the pull request branch created from a fork](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) I can also check the PR branch out, rebase and force-push myself as if it was my own branch.

### Suggested solution

It would be nice if a CLI command existed that would automate b) and c):

```
hub pr rebase https://github.com/github/hub/pull/134
```

This clones the fork and switches to the PR branch, adds the upstream and then rebases the PR branch onto the target branch (mostly `master`). If there are no problems, the updated fork PR branch can then be force pushed. 

The PR will rerun its tests that will e.g. succeed because of the new upstream changes pulled in 🥇 

Does something like this exist already or is this a valid feature request?

---

This feature request might be similar to the seconds point of https://github.com/github/hub/issues/1047.
An external bot exists that can be used in a similar way: https://github.com/chrisledet/rebasebot

**Comment by mislav** [comment]
Thanks for the detailed feature request! Closing this in favor of #1886 because the feature requests are very similar, and we could easily consolidate the discussion about both in a single thread.
