### ISSUE TITLE
Merge PR target branch into PR branch

### ISSUE THREAD

**Issue by janpio** [github/hub#1886]
Very similar request to https://github.com/github/hub/issues/1885, just with `merge` instead of `rebase`:

> ### Motivation
> 
> Both as a contributor and a committer and maintainer of Open Source projects I frequently need to make sure my or a Pull Request creator's branch are up to date with the PR target branch (mostly master).
> 
> This is mostly necessary to get tests passing: The fork / PR branch could have been created from a commit that had failing tests at the time, or the tests started failing in the meantime because of environment changes which need a commit to be fixed. So we have a (probably good) PR sitting there with failing tests, and updating the PR branch would fix that.
> 
> [I know both situations point to a deeper problem that should/could be fixed, but it's the reality now and I have >50 PRs with this state waiting and am looking for a solution]

### Current solution

One way to achieve this is to merge the target branch into the PR branch:

a) One way is to ask contributors to merge the upstream branch into their fork's PR branch. Unfortunately this can be problematic, as user's don't know or are scared about merges. Giving instructions takes a lot of time, that could be spent reviewing and merging other PRs.
b) An alternative is to create a PR on the PR branch which merges the upstream branch into their fork branch. This can all be done using the GitHub UI, so no local checkout necessary: https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/ But it requires the user to actually notice and merge the Pull Request into their branch - until then the PR is still blocked.
c) For my own branches, I can of course just go ahead and merge upstream and push.
d) If the contributor [allows changes to the pull request branch created from a fork](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) I can also check the PR branch out, merge and push myself as if it was my own branch.

### Suggested solution

It would be nice if a CLI command existed that would automate b) and c):

```
hub pr merge https://github.com/github/hub/pull/134
```

This clones the fork and switches to the PR branch, adds the upstream and then merges upstream into the PR branch. If there are no problems, the updated fork PR branch can then simply be pushed. 

The PR will rerun its tests that will e.g. succeed because of the new upstream changes merged in 🥇 

Does something like this exist already or is this a valid feature request?

#### Comparison to https://github.com/github/hub/issues/1885

In comparison to #1885, this doesn't need a force push to get the changes onto GitHub. This might be beneficial, as you are potentially working on somebody else's branch which could of course lead to problems if they continue working without pulling all changes first.

The disadvantage of course is the merge commit and all the unrelated commits appearing in the PR you modified. This will merge cleanly, but I think GitHub UI will still show them. Correct?

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3

Thank you for suggesting!
