### ISSUE TITLE
`hub sync` (or `hub release`) could sync tags

### ISSUE THREAD

**Issue by erikhuizinga** [github/hub#1891]
Feature request:

`hub sync` currently runs `git fetch --prune --quiet --progress` on the default remote. It would be very useful if `sync` would also fetch new tags (or GitHub releases) with `git fetch --tags`.

This makes sense, because `hub help sync` describes `sync` as: 'Fetch git objects from upstream and update branches.' Therefore I'd expect it to sync tags as well, because those are Git objects. Tags can be created on GitHub (either as just a tag or as a release), so I'd want `hub sync` to fetch those for me so I can work with them locally after a sync.

Alternatively, `hub release` could somehow fetch all tags from the remote. However, I think it's more logical to put all tag fetching behaviour under `sync` instead of `release`, because not every Git tag is a release on GitHub.

**Comment by mislav** [comment]
I see `hub sync` only as a command to sync local branches. It was never meant to do anything outside of that, and therefore fetching tags falls outside of its scope. “Fetch git objects from upstream and update branches” meant to say that those git objects are branch-related.
