### ISSUE TITLE
Strips out header formatting as comments

### ISSUE THREAD

**Issue by fatso83** [github/hub#1894]
The pull request templates used in most of the open source projects I contribute to contain some degree of formatting, such as [this one from SinonJS](https://raw.githubusercontent.com/sinonjs/sinon/master/.github/PULL_REQUEST_TEMPLATE.md).

But using the normal `# Header1`, `## Header 2` formatting doesn't go very well with Hub's `pull-request` command, as it strips out all lines starting with `#`. I think this should be fixed, somehow, as it is unfortunate to have valid markdown syntax that overlaps with Hub's chosen comment identifier.

My mind might fail me, but I thought this used to work (sometime prior to 2.3)?

**Comment by salmanulfarzy** [comment]
Duplicate of #1377

**Comment by fatso83** [comment]
True.
