### ISSUE TITLE
Right place for feature request for github issues overview?

### ISSUE THREAD

**Issue by flddr** [github/hub#1895]
Hi,

i am just interested in a little feature for github issues. If you watch an repo for example, it's sometimes a little bit hard to open all issues and look who has answered at last position.

So, acutally, the issue table looks like:
**headline title**
_#issue number openend on x.y. by name_

I would like to see last contribute, like:
**headline title**
_#issue number openend on x.y. by name, last contribution: name2_

This would be very helpfull :)

I mean here:

![screenshot_2018-10-10-10-55-48](https://user-images.githubusercontent.com/42785945/46724891-4118fb00-cc7b-11e8-9fe1-8a6c43220c72.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!

**Comment by flddr** [comment]
Sorry, yes, right - i did not found and hub looks like
