### ISSUE TITLE
protocal setting's not working

### ISSUE THREAD

**Issue by wayou** [github/hub#1898]
```bash
$ git version
git version 2.19.0
hub version 2.5.1

$ cat ~/.config/hub
github.com:
- user: wayou
  oauth_token: ***
  protocol: https
```
I've set the protocal via `git config --global hub.protocol https` but it still clone with ssh.

**Comment by mislav** [comment]
From https://hub.github.com/hub.1.html

> If you prefer the HTTPS protocol for git operations, you can configure hub to generate all URLs with `https:` instead of `git:` or `ssh:`:
>
>     $ git config --global hub.protocol https

The `protocol` option in `~/.config/hub` is not meant for this; it's meant as API protocol GitHub Enterprise instances (not likely something that you need right now).

**Comment by wayou** [comment]
found a solution by forcing the git to use https:

```bash
$ git config --global url."https://github.com".insteadOf git://github.com
```
