### ISSUE TITLE
hub --version redundant line

### ISSUE THREAD

**Issue by tomgs** [github/hub#1901]
Running on Mac OSX, running `git` version 2.17.1 (Apple Git-112) and `hub` version 2.5.1, I get the redundant second line when doing `hub --version`:

```
hub --version
$ git version
git version 2.17.1 (Apple Git-112)
hub version 2.5.1
````

In pictures:

![smartreceiptslibrary_ _-bash_ _101x31](https://user-images.githubusercontent.com/8835035/46974852-cb26f080-d0cd-11e8-9be8-d09738aaf9b6.png)

**Comment by mislav** [comment]
Do you have `HUB_VERBOSE` set in your environment by any chance? That value should only be used for debugging, not to be always on.

**Comment by tomgs** [comment]
@mislav It is not set right now:

**Comment by tomgs** [comment]
Oh, I checked in the wrong terminal window. It is set, sorry about that!
