### ISSUE TITLE
Feature request: Generate github url of file 

### ISSUE THREAD

**Issue by cbcoutinho** [github/hub#1904]
I'm curious if it's possible to generate a url to github.com of a certain file from the commandline (including the commit hash).

Let's say I clone this project and what to share a url to `cmd/cmd.go` at the current commit, I was thinking something like:

```shell
$ hub url cmd/cmd.go
https://github.com/github/hub/blob/1b0be12b0dde1d5dd8d7c45ff5af2cd88a97748b/cmd/cmd.go
```

Is this possible and/or useful?

**Comment by mislav** [comment]
Right now this is possible with:

```
hub browse -u -- blob/$(git rev-parse --short HEAD)/cmd/cmd.go
```

It's a bit manual, but does the trick. Is this acceptable to you?

In the future there might be a `hub open` command that supersedes `browse` in a way that it will make it easier to jump to a specific file or git SHA.

**Comment by cbcoutinho** [comment]
Howdy mislav,

This works fine - it's a bit clunky but it gets the job done.

I'm not really interested in opening the link a browser, I just wanted to generate a url.

Thanks again

**Comment by mislav** [comment]
@fadookie These are great! Thanks for sharing

**Comment by fadookie** [comment]
Here's another one I made today: `browse-pr` to open any PRs from current branch on same repo (normally what I want to do)
```
[alias]
    browse-pr = !hub pr list -h "$(git rev-parse --abbrev-ref HEAD)" -f '%U%n' | xargs open
```
On non-mac platforms you can just remove `|xargs open` or replace `open` with whatever command you use to open a web browser to a specific URL.

**Comment by mislav** [comment]
@fadookie On the latest hub release you can also just do this: `hub pr show` 😉
