### ISSUE TITLE
pull a cloned repos.

### ISSUE THREAD

**Issue by AM-77** [github/hub#1914]
clone a repo >> make your changes >> pull request to the original repo.
is it possible.

**Comment by mislav** [comment]
I'm not sure what your exact workflow is, but your question is more a question about git than about hub. You could use `hub` like this:

```sh
hub clone original/repo -o upstream

git checkout -b new-branch
# ... make your changes ...
git commit

hub fork --remote-name=origin

git push -u origin HEAD
hub pull-request
```

Going to close this because it looks like a usage question rather than a bug report.
