### ISSUE TITLE
potential conda support

### ISSUE THREAD

**Issue by stas00** [github/hub#1921]
Someone requested to make a conda package for hub, which I did in this branch:
https://github.com/stas00/hub/blob/conda-build/conda-recipe/README.md

[conda](https://anaconda.org) is one of the 2 main python package repositories which supports non-python projects too. It's much more convenient to run `conda install hub` on any platform and just have it work, rather than giving different instructions for different platforms. I think that's why some people desire to have `hub` on conda.

I'm not sure you'd like to maintain another set of binary packages, so I have not submitted a PR. If you'd like to have the instrumentation in the main repository regardless whether you'd like to release the conda version of the packages or not, let me know and I will submit a PR then.

Otherwise, you can close this ticket, and it'll be just here to guide those, who may look for a conda package, to my branch. 

Thank you.

**Comment by mislav** [comment]
Hi, thank you for bringing this to our attention!

I had no awareness of conda prior to this, but in general we don't maintain scripts that package up hub for other platforms/package managers (with the exception of scripts that generate binaries for our Releases section). We leave this up to the community.

Is there a way you can maintain the conda package for hub external to this repository?

**Comment by stas00** [comment]
Thank you for your follow up, @mislav. 

Yes, I expected this to be the case - it makes total sense.

I don't use hub myself, so I won't be a good candidate for that. If someone here stumbles upon this thread and would like to do that, they are welcome to do so.

So let's close this for now and leave it in the issues to be discovered if need be.
