### ISSUE TITLE
Feature request: Search my own repositories on GitHub

### ISSUE THREAD

**Issue by yousan** [github/hub#1925]
Hi.

# Requested Changes
Add `hub search <keyword>` command to search repos that I have permissions.

```
$ hub search hub
https://github.com/github/hub/
```

```
$ hub search --ssh hub
git@github.com:github/hub.git
```

Then I can easy to clone repos into local.

```
$ git clone $(hub search hub)
```

Thanks.

**Comment by mislav** [comment]
That's a good idea!

Closing as duplicate of #833
