### ISSUE TITLE
Warn about an unpushed branch when opening a pull-request

### ISSUE THREAD

**Issue by gibfahn** [github/hub#1930]
I think this was previously the behaviour (before the change from `#` to `>8` for the `PULLREQ_EDITMSG`).

Basically I'd like to see the commit messages in the text by default, so I can easily move them above the line if I want. Having the default Pull Request template text there as well also makes sense, maybe template above the scissors by default and commit messages below would make sense.

Basically something like this:

```diff
+<Github PR template>

# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

-<Github PR template>

+<commit messages>
```

Swapping "commit messages" and "Github PR template" would be fine too I guess.

**Comment by mislav** [comment]
We have a test that verifies that the changes are included below the "scissors" line: https://github.com/github/hub/blob/2c564f6fad4ea6d88ffcf898df664b860f846a5b/features/pull_request.feature#L281-L287

What is not working for you, exactly?

**Comment by gibfahn** [comment]
So I run the following:

```console
$ hub --version
git version 2.19.1
hub version 2.6.0

$ git fetch --all
Fetching up
Fetching fork

$ git log up/master...@
  commit b1404[...] (HEAD -> dockerfile)
  Author:     Gibson Fahnestock <gib@[...]>
  AuthorDate: Thu Nov 1 18:17:37 2018 +0000
  Commit:     Gibson Fahnestock <gib@[...]>
  CommitDate: Thu Nov 1 18:21:10 2018 +0000
  
      Add docs for [...]
      
      These are [...]
      
      Refs: [...]

$ hub pull-request -b <upstream-org>:master -o
```

then I get:

```bash

# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

Requesting a pull to <upstream-org>:master from gibson-fahnestock:dockerfile

Write a message for this pull request. The first block
of text is the title and the rest is the description.
```

**Comment by gibfahn** [comment]
Actually, it looks like the issue is that I didn't push to my fork, there's no upstream remote specified here:

```console
$ git status
On branch dockerfile_package_version_and_tag
nothing to commit, working tree clean
```

I didn't specify `-f`, so that check does fail after I save my PR Message:

```console
$ hub pull-request -b pie:master -o
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

but that check would make more sense if it happened before the Pull Request message is created right? 

If I `git push -u fork` then delete PR message and rerun, then I get the commit showing up as expected.

That way I'd see my commit messages in my Pull Request message.

**Comment by mislav** [comment]
> Actually, it looks like the issue is that I didn't push to my fork

Yes, that could explain your problem.

So far this is expected behavior. I don't follow: what do you expect hub to do in this case? Are you reporting a bug? In what way would you imagine to see hub's functionality changed? Thank you

**Comment by gibfahn** [comment]
>>but that check would make more sense if it happened before the Pull Request message is created right? That way I'd see my commit messages in my Pull Request message.

>In what way would you imagine to see hub's functionality changed?

I would like hub to check whether I've pushed to my fork before opening `PULLREQ_EDITMSG` in my editor.

**Comment by gibfahn** [comment]
>Thanks for taking time to explain this!

Thanks for helping me work out what the actual issue was.

If I can provide any more info let me know.

**Comment by dbosk** [comment]
Git has a configuration for submodules that ensures that when you push a repo, it also pushes any submodules that have unpushed commits (to ensure that all commits needed are available).

A similar configuration would be useful for Hub in this case. Say `git config [--global] hub.pull-request.push true` will make Hub automatically push any unpushed commits on the branch when opening a pull-request.

**Comment by dbosk** [comment]
A comment on the format suggested at the top:

It would be better to keep the PR template below the >% line. Also that Hub puts the suggested title below the >% line (not the case in 2.9.0). That way Hub would be more aligned with Git behaviour, which also aborts if the message is empty --- which it would be if one simply exits the editor without touching the file. (Currently, an immediate exit would still open a PR, not sure if deleting the title before exiting would cause an abort or not.)
