### ISSUE TITLE
Hub exits randomly with no errors, just exit code 1

### ISSUE THREAD

**Issue by aidangoettsch** [github/hub#1933]
Happens on pretty much every command, except help, shown here with git status.
```
aidan  /mnt/d/Code/repo   master  git status   
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
 aidan  /mnt/d/Code/repo  git status
 ✘ aidan  /mnt/d/Code/repo  ➦ 12e6836  git status
 ✘ aidan  /mnt/d/Code/repo   master  git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
 aidan  /mnt/d/Code/repo   master  git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
aidan  /mnt/d/Code/repo  git status
 ✘ aidan  /mnt/d/Code/repo  ➦ 12e6836  echo $?   
1
```
The custom prompt is also running git status every time, and it should show `master` all the time, but seems to fall back to a commit hash or no output at all.

I'm using WSL, but this occurs on a Mac as well. However, it only seems to happen in zsh.

**Comment by mislav** [comment]
The problem with WSL is known and, so far, I don't think there's anything to do in hub's source code to work around that. (I'd welcome to be proven wrong!) https://github.com/github/hub/issues/1871#issuecomment-420762466

However, if the exact same error ocurrs on macOS as well, then this is a larger issue than just with WSL. Can you tell us more about the macOS version and hub version that this fails on, how does the error look like in the console, and how did you install hub? Thank you!

**Comment by aidangoettsch** [comment]
I did double check, looks like it does actually work perfectly on my Mac. I did remember having some weird issues, but it was something else, not this exact problem. Looks like this is a dupe of #1871 then.
