### ISSUE TITLE
Aborted: the origin remote doesn't point to a GitHub repository.

### ISSUE THREAD

**Issue by gnumoksha** [github/hub#1936]
Scenario: As a user, I want to list all open pull requests on my private repository hosted on github.com, but when I run `hub pr list` inside my local repository cloned with git I got an error that is not true.

```
$ hub pr list
Aborted: the origin remote doesn't point to a GitHub repository.

$ git remote -v
origin  git@github.com:company/app.git (fetch)
origin  git@github.com:company/app.git (push)

$ hub --version
git version 2.19.1
hub version 2.6.0
```

**Comment by gnumoksha** [comment]
#### Steps to reproduce

* Add the following into the ~/.ssh/config
```
Host github.com
	Hostname %h
	User git
	IdentityFile ~/.ssh/yourKey
	IdentitiesOnly yes
```
* Run `hub pr list`

#### Workaround
Do not use `%h` in `Hostname`.

#### Considerations
Please, note that the config sample was simplified. The use of %h is because I use this configuration for more than one git server (i.e. github and gitlab).

Anyway, I think `hub` must check `origin` value provided by git, not the connection address.

**Comment by mislav** [comment]
Thank you for reporting!

I didn't know of `%h` token having a special value in `HostName` before.

**Comment by gnumoksha** [comment]
@mislav Do you not think it is a kind of bug on hub?

**Comment by mislav** [comment]
@gnumoksha I do. That's why I already fixed it in `master` the same day you've reported it 😉
