### ISSUE TITLE
TestTransformRemoteArgs fails when using tag archives

### ISSUE THREAD

**Issue by kyrias** [github/hub#1937]
The `TestTransformRemoteArgs` test in `github.com/github/hub/commands` fails when it is not located inside a git repository, making it fail with no error message when running the test suite from the automatically generated tag tarballs.

```
=== RUN   TestTransformRemoteArgs
FAIL	github.com/github/hub/commands	0.049s
```

**Comment by mislav** [comment]
Thank you for reporting!
