### ISSUE TITLE
hiveserver2.py get_summary What do we need to satisfy 

### ISSUE THREAD

**Issue by zhangyikun1005** [github/hub#1946]
I use sqldbx with username aml_user ;
excute select * from tableName;
return results;
I use IDE with username aml_user;
excute select * from tableName;
have a error:
hiveServer2Error: user aml_user is not authorized to access the runtime profile or excution summary;

**Comment by mislav** [comment]
Sorry, this looks like a general programming question, not a bug report about a project called `hub`. This is not a forum to ask general programming questions in.

**Comment by zhangyikun1005** [comment]
I,m sorry.
