### ISSUE TITLE
Feature req: open existing issue in browser

### ISSUE THREAD

**Issue by rpdelaney** [github/hub#1948]
`hub issue create -o` opens the newly created issue in the default browser. But there doesn't seem to be a way to open an existing issue.

I'd suggest `hub issue open <number>` but any syntax that seems reasonable is fine with me.

**Comment by mislav** [comment]
Right now you can use `hub browse -- issues/1948`.

In the future there might be a `hub open` (or similarly named) command that will make it a little bit easier (less typing) to open issues, commits, etc.

Hope this helps!

**Comment by rpdelaney** [comment]
No need, that is exactly what I needed. Thank you!
