### ISSUE TITLE
Incompatible with git 2.20.0

### ISSUE THREAD

**Issue by xu-cheng** [github/hub#1963]
## My system config
```
$ git --version
git version 2.20.0
hub version 2.6.0
```

## The problem

After upgraded to git 2.20.0, running `hub <alias>` would freeze the command line prompt.

```
$ \git st # running git directly is fine
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ hub st # running hub results to hang up
^C
```

## The cause

Running `ps aux | grep git` shows that the hub is stuck at running `git help -a`. The related codes are:

https://github.com/github/hub/blob/f4252d55ecfa76aa4db50458faab4a269dada014/git/git.go#L359-L374

Running `git help -a` manually, I found that since 2.20.0 git starts using page (e.g. `less`) to display help message.  As a result, it causes hub hang up when it invokes `git help -a` in the codes mentioned above.

**Comment by buehmann** [comment]
I doubt that the pager is an issue (which would only be launched when connected to a terminal), but this change in `help -a` output:

https://github.com/git/git/blob/5d826e972970a784bd7a7bdf587512510097b8c7/Documentation/RelNotes/2.20.0.txt#L17-L18

**Comment by xu-cheng** [comment]
> I doubt that the pager is an issue (which should only be launched when connected to a terminal)

That is exactly what happens. It launches pager even stdout is not a tty. I can reproduce it by `git help -a | cat`. I have sent a bug report on this to git mailing list.

**Comment by jacobbednarz** [comment]
@xu-cheng @buehmann This was due to [a change in git 2.20.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.20.0.txt#L17-L18) that I have restored the functionality within #1964. I don't think it's a bug with Git itself but the command `hub` was relying on to parse built in methods. Give the PR a whirl and let me know if it doesn't fix it for you.

**Comment by mislav** [comment]
> It launches pager even stdout is not a tty.

That is definitely a bug in git. Even if `git help -a` output format changed, I don't see why it should ever block indefinitely. No code in hub around parsing this output seems to be blocking.

@xu-cheng Thank you for reporting! @jacobbednarz thank you for the fix!
