### ISSUE TITLE
gitconfig alias causes hub to consume all system memory, then crash

### ISSUE THREAD

**Issue by eli-schwartz** [github/hub#1965]
I have the following alias in my gitconfig
```
[alias]
    list-remote-branches = "!f() { git for-each-ref --format=\":%(refname:strip=3)\" \"refs/remotes/$1/**\" | grep -v :maste222r; }; f"
```

If it is there, then running `hub log` will sit there consuming more and more memory until it eventually crashes. When I delete this alias, `hub log` works fine.

Unsure why this alias matters at all, given hub shouldn't be trying to use it...

**Comment by mislav** [comment]
You likely have git 2.20+.Please upgrade to the latest version of hub (2.6.1).

**Comment by eli-schwartz** [comment]
Huh, I've just noticed my Arch Linux package for hub is indeed out of date. Bumping the version results in a much better behaved hub binary indeed. Sorry for the bother.

(Also, the relevant #1964 claims that it simply hangs, but I was definitely getting runaway memory spikes.)
