### ISSUE TITLE
private repo raw file token cannot be deleted, changed or created

### ISSUE THREAD

**Issue by peterbosalliandercom** [github/hub#1969]
The raw link to the specific file in a repo consist of a token which cannot be created, changed or deleted in any way. It would be important for security reasons to be able to do crud functions on that token. Is there any way that this is possible? The use case hereafter is that we would like to read (read-only) specific config files for CICD purposes. Now this raw link with token is forever active and never expires until the file is deleted.

**Comment by peterbosalliandercom** [comment]
wrong issue log sorry...

**Comment by yashaka** [comment]
> The raw link to the specific file in a repo consist of a token which cannot be created, changed or deleted in any way.
> Now this raw link with token is forever active and never expires until the file is deleted.

@peterbosalliandercom 
Do you know, where can I read how these tokens work? Do they really never expire? Is there any way to control them?

Actually I am interested in "they never expire" unless I ask for that by intent...
