### ISSUE TITLE
How to update a pull request ?

### ISSUE THREAD

**Issue by snaewe** [github/hub#198]
How can I update a pull request after I did `git commit --amend` ?

**Comment by kernelOfTruth** [comment]
@mislav that is extremely useful (force-push support). Thank you !

**Comment by dpino** [comment]
What if you accidentally have removed the remote branch that is linked to the PR? Is it possible to fetch the PR and link it to a new remote on your fork, so the PR can be updated? Asking for a friend...

**Comment by dpino** [comment]
I reply here myself for future reference. 

When sending a PR, on the PR's comments there's a message at the bottom that says something like:

_Add more commits by pushing to the <branch> branch on <remote>/<branch>._

So to update a PR, even if you have removed the original remote branch out of which the PR was created, you just need to:

* Fetch the PR (`git fetch pull/<id>/head:branchname` and  `git checkout branchname`).
* Add new commits, amend, rebase, do whatever you like.
* Push or push force (git push <remote> +<branch>).

And after that the PR will be automagically updated :)

**Comment by mislav** [comment]
@dpino Thanks for the tip!

**Comment by knmnyn** [comment]
<img width="345" alt="990301-cochairs" src="https://cloud.githubusercontent.com/assets/217067/19216800/902a816e-8dfd-11e6-9197-5c6b2ac03fc3.png">

This file needs to be added to the images/ subdir in the site.  It was in the original PR but has gone missing again...

**Comment by danihodovic** [comment]
Is it possible to update the PR title or description using hub?

**Comment by mislav** [comment]
@danihodovic Not at the moment.

**Comment by DavitVosk** [comment]
After creating your "Pull Request" you can update it with just pushing new commits to your branch from where your "Pull Request" was created.

**Comment by danihodovic** [comment]
> After creating your "Pull Request" you can update it with just pushing new commits to your branch from where your "Pull Request" was created.

I was talking about updating the description.

**Comment by carlossless** [comment]
The possibility to update the PR description, labels, milestones etc. with the same `pull-request` would greatly improve my workflow when using `hub`. Big :+1: to seeing this in the future.

**Comment by tmbutterworth** [comment]
Is their a way to do a push to a PR from Fork using the web interface?

**Comment by mislav** [comment]
@tmbutterworth No, you have to use the `git` comand-line (or another git tool that can push to remotes) to push new commits to update a PR.

**Comment by mislav** [comment]
@tmbutterworth You're right: being able to do this via the web interface would be useful in a variety of scenarios. However, note that this issue tracker is not for GitHub.com nor its web interface. This project and issue tracker is for a command-line tool called `hub`, which can be interfaced with only from the command-line environment such as the terminal.

To propose features to GitHub.com, please write to support@github.com

**Comment by Blackjacx** [comment]
> Is it possible to update the PR title or description using hub?

We also would highly appreciate this 👍

**Comment by chaolyang** [comment]
> Is it possible to update the PR title or description using hub?

I'm new to `hub` and used to use arcanist which has this feature. Hopefully this will be available with `hub` soon.

**Comment by 2fasc** [comment]
For starters: If you use the graphical interface you can choose to close the pull request commit to the branch you want to be pulled and reopen it after.

**Comment by qc1iu** [comment]
> I reply here myself for future reference.
> 
> When sending a PR, on the PR's comments there's a message at the bottom that says something like:
> 
> _Add more commits by pushing to the 'branchname' branch on 'remote'/'branch'._
> 
> So to update a PR, even if you have removed the original remote branch out of which the PR was created, you just need to:
> 
> * Fetch the PR (`git fetch pull/<id>/head:branchname` and  `git checkout branchname`).
> * Add new commits, amend, rebase, do whatever you like.
> * Push or push force (`git push remote +branch`).
> 
> And after that the PR will be automagically updated :)

After the step 3, there only created a new branch but the PR not update as expected...

**Comment by alessandroAmedei** [comment]
> I reply here myself for future reference.
> 
> When sending a PR, on the PR's comments there's a message at the bottom that says something like:
> 
> _Add more commits by pushing to the 'branchname' branch on 'remote'/'branch'._
> 
> So to update a PR, even if you have removed the original remote branch out of which the PR was created, you just need to:
> 
> * Fetch the PR (`git fetch pull/<id>/head:branchname` and  `git checkout branchname`).
> * Add new commits, amend, rebase, do whatever you like.
> * Push or push force (`git push remote +branch`).
> 
> And after that the PR will be automagically updated :)

<id> of what?

**Comment by yisselda** [comment]
@alessandroAmedei id is the number of the PR, in the following example it would be 93:
<img src="https://user-images.githubusercontent.com/29551766/80897000-5ffa3a80-8cc2-11ea-9b85-fb039adfd874.png" width="500">

**Comment by ycollet** [comment]
I pushed an update of this PR on my fork:
https://github.com/ycollet/lmms/tree/jcak_master

I just don't know how to push this change on this PR ...

**Comment by SamanthaToet** [comment]
Had this happen to me today - one fix was to log out and log back in. When I logged back in, the commits were then added to the PR. 🤷

**Comment by dsims** [comment]
> Had this happen to me today - one fix was to log out and log back in. When I logged back in, the commits were then added to the PR. 🤷

I had the same issue, except I did a hard browser refresh. Github is doing some aggressive caching it seems.

**Comment by anushkabishnoi** [comment]
Can I create another pull request without code changes? 
(The repo I'm contributing to is asking me to use a signed commit, and re-submit the pr)
