### ISSUE TITLE
Feature Request: add all forks as remotes

### ISSUE THREAD

**Issue by apjanke** [github/hub#1985]
Here's an idea for a feature: a `hub remote add --all-forks` option that has hub search the fork tree, and add remotes for *all* the repos in the fork tree, using the appropriate `<username>` names. This could be useful for project maintainers to track how things are going with all of their contributors.

I see the addition of individual forks was discussed [here](https://github.com/github/hub/issues/1627), but I think this variant goes above and beyond that.

Do you think this would be useful? Or is it more of a silly stunt?

I haven't tried this out myself because I don't have a good tool to do it with.

**Comment by mislav** [comment]
Hi thank you for the feature idea!

We tend to avoid adding features to hub that we don't think will see much use (reminder that each feature we have to maintain for years to come!). Your example use-case makes sense, but after the remotes have been added, what sort of additional tools would the maintainers use to track progress from these forks? Also, what if I use the `--all-forks` command for this repo and add 1,447 additional git remotes, most of which would be pretty useless to me?

**Comment by apjanke** [comment]
I think progress tracking on the branches could be done with regular git tools, like SourceTree or GitUp, since forks are likely to have branches or commits, but typically don't have PRs or Issues of their own, right?

We'd need a 'prune' tool to get rid of unwanted forks. Maybe something like `hub remote remove --unused-forks` which would remove all forks for which there is not a local branch tracking a branch on them?

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3

Thank you for suggesting!
