### ISSUE TITLE
GIT CHECKOUT ISSUE

### ISSUE THREAD

**Issue by alecgarza96** [github/hub#1998]
Trying to perform `git checkout` to set up EOS developer environment but system keeps aborting

![image](https://user-images.githubusercontent.com/43724421/50657452-28f40780-0f5c-11e9-83d5-d735d7d7500c.png)
![image](https://user-images.githubusercontent.com/43724421/50657472-390be700-0f5c-11e9-8f14-dd0725f76a3a.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!

It looks like here you need to do `git clean -fdx libraries` before running `git checkout ...`. Note, however, that this will **delete** all the listed files. Good luck!
