### ISSUE TITLE
Command to validate IP address

### ISSUE THREAD

**Issue by Boruch-Baum** [github/hub#2001]
Github [occasionally changes its IP address(es)](https://help.github.com/articles/about-github-s-ip-addresses/), which can arouse the concern that the updated DNS resolution is invalid or a hijack. In such cases, (happened to me a few hours ago), attempting to ssh warns me that the host is unknown (when it should be already in the known_hosts file), and Firefox warns me about an invalid certificate. The recommendation [here](https://help.github.com/articles/about-github-s-ip-addresses/), as pointed out to me by a github support person just a few minutes ago, seems to be use the API and a CIDR calculator to validate the address ( api.github.com resolves to a different IPV4 than github.com, and presumably won't change).

It occurred to me that this would be a natural feature for this project.

**Comment by Boruch-Baum** [comment]
Here's a bash script illustrating the functionality I'm proposing for this proposed `hub` feature:

```
#!/bin/bash
# github_valid_addresses
help="${0##*/}
  Query the github api for the site's up-to-date valid ip addresses.
  Requires: bash, curl, jq, ipcalc
  Takes no parameters"

[ -n "$1" ] \
&& { printf "$help\n\n" ; exit ; }

list=( $(curl -s https://api.github.com/meta \
         | jq -r '.git | @sh ' \
         | tr -d "\'" ) )
for addr in ${list[*]} ; do
  ipcalc -nb $addr \
  | awk '/Address/{a=$2}
         /HostMin/{b=$2}
         /HostMax/{c=$2}
         END{if (b && c) print b" - "c; print a}'
done
```

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3

For example:

```sh
$ hub api --cache 3600 -t meta | awk '/^\.git\./ { print $2 }'
192.30.252.0/22
185.199.108.0/22
140.82.112.0/20
13.229.188.59/32
13.250.177.223/32
18.194.104.89/32
18.195.85.27/32
35.159.8.160/32
52.74.223.119/32
```

Thank you for suggesting!
