### ISSUE TITLE
Support for changing personal status on github

### ISSUE THREAD

**Issue by alexanderwise** [github/hub#2002]
Given the recent rollout of personal statuses in github, it would be useful to interact with that feature outside of the web ui. hub is the perfect place to make that api call.

**Comment by mislav** [comment]
It's a nice idea, but GitHub doesn't have an API to interact with user statuses. Until that API exists, there is nothing that hub can interact with to make this happen.

Closing until we can revisit this in the future. Thank you for writing in!
