### ISSUE TITLE
`--push` doesn't work for new PRs unless you also supply an `-m` flag

### ISSUE THREAD

**Issue by jezhou** [github/hub#2003]
When I call `hub pull-request --push`, it opens up an editor (vim, in my case), and when I save and close the editor, I'm expecting it to push my branch and then make a pull request. 

However, what I'm finding is that if I haven't pushed my branch yet, I will get a 422 Unprocessable Entity. 

Curiously, If I `hub pull-request --push -m "My PR Title"`, the command successfully works.

**Comment by mislav** [comment]
@jezhou Hi thank you for reporting!

1. Which `hub version` do you have? Does it go away after an upgrade to latest?
1. What is your `git var GIT_EDITOR`
2. Does this happen every time?

**Comment by jezhou** [comment]
Hi @mislav 😄 

1. My hub version is `2.7.0`. I ran `brew upgrade hub` before trying this out
2. git var GIT_EDITOR is `vim` right now
3. It's been happening every time so far, but I've only been making PRs into private repositories

**Comment by mislav** [comment]
1. What is the exact error message that gets shown to you when a 422 occurs?
2. Do you have `HUB_RETRY_TIMEOUT` set in your environment by any chance?

**Comment by jezhou** [comment]
Sorry for not responding –– I've retried this recently and it seems like it works now. Not sure what I did differently (maybe a hard restart of my computer...?) but I'll close this for now and update if I figure it out. Thanks again 😄

**Comment by felixjb** [comment]
I am having the same problem. Curiously, I am also working with private repositories.

Also, sometimes it fails to identify the base to compare the code with.
