### ISSUE TITLE
Non-latin relative wiki markdown header links does not working

### ISSUE THREAD

**Issue by pavelsr** [github/hub#2005]
Though this issue isn't related to hub, it strongly requires attention of Github team.

If you try to get link to markdown header, which is non-English, it will not work

Please check examples

https://github.com/pavelsr/latin-issue/blob/master/index.md#foo - working
https://github.com/pavelsr/latin-issue/blob/master/index.md#Привет-мир - not working

Originally this bug was found here https://github.com/ekalinin/github-markdown-toc/issues/55

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
