### ISSUE TITLE
There is no clear indicator after granting an org at oauth screen

### ISSUE THREAD

**Issue by stellarmagnet** [github/hub#2014]
(NOTE - this has nothing to do with hub. I have no clue where to log Github bugs)

i click the "grant" button and nothing changes to indicate the organization has been granted 

Except the action *does work*  - as the next time i come to this screen it has green check

![image](https://user-images.githubusercontent.com/2584493/51578239-b0ed7300-1e71-11e9-8a98-c2f76c5f7768.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
