### ISSUE TITLE
existdb is not responding: System maintenance task reported error: this IndexWriter is closed 

### ISSUE THREAD

**Issue by sbhusala** [github/hub#2015]
Dear Team,

We have observed that, existdb data base was not responding with for the queries/search from application.
Please find the attached logs for the same. 
[exist.20190115000317.log](https://github.com/github/hub/files/2791505/exist.20190115000317.log)

Can you please check and let us know what caused for this behavior ?

Regards,
Srinu B

**Comment by mislav** [comment]
Sorry, this is an issue tracker for a command-line utility called `hub`, which has nothing to do with existdb.
