### ISSUE TITLE
`ci-status -v` lists checks in arbitrary order

### ISSUE THREAD

**Issue by allanlewis** [github/hub#2021]
`hub ci-status -v` lists the checks in an apparently arbitrary order. If I do `watch hub ci-status -v` then the order changes on each refresh. I'd expect the checks to be sorted by status - "failed" followed by "in progress" followed by "succeeded" - then alphabetically, but any consistent ordering would be OK.

```
➜ hub --version
git version 2.20.1
hub version 2.6.0
```

**Comment by mislav** [comment]
Thank you for reporting!
