### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nsartor** [github/hub#2022]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x721880, 0x9e9860)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/panic.go:513 +0x1c7
github.com/github/hub/github.(*Client).absolute(0xc0000880c0, 0xc0001d4de0, 0x29, 0x29)
	/home/travis/gopath/src/github.com/github/hub/github/client.go:925 +0xaa
github.com/github/hub/github.(*Client).apiClient(0xc0000880c0, 0x0)
	/home/travis/gopath/src/github.com/github/hub/github/client.go:911 +0x120
github.com/github/hub/github.(*Client).simpleApi(0xc0000880c0, 0x8, 0xc000053150, 0x1)
	/home/travis/gopath/src/github.com/github/hub/github/client.go:901 +0x61
github.com/github/hub/github.(*Client).CurrentUser(0xc0000880c0, 0xc0000880c0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/github/hub/github/client.go:798 +0x36
github.com/github/hub/github.(*Config).PromptForHost(0xc000058fc0, 0xc000086240, 0x29, 0xa12c38, 0x7da060, 0xa12c38)
	/home/travis/gopath/src/github.com/github/hub/github/config.go:82 +0x133
github.com/github/hub/github.(*Config).DefaultHost(0xc000058fc0, 0x18, 0xc0001e21b4, 0x4)
	/home/travis/gopath/src/github.com/github/hub/github/config.go:314 +0xec
github.com/github/hub/commands.create(0x9ef740, 0xc0000ce4d0)
	/home/travis/gopath/src/github.com/github/hub/commands/create.go:97 +0xcc
github.com/github/hub/commands.(*Command).Call(0x9ef740, 0xc0000ce4d0, 0xc000103b01, 0x1f0000c000092300)
	/home/travis/gopath/src/github.com/github/hub/commands/commands.go:45 +0x12d
github.com/github/hub/commands.(*Runner).Call(0xc000052d80, 0x9ef740, 0xc0000ce4d0, 0x6, 0xc000092390, 0xc000002180, 0xc0000540f0)
	/home/travis/gopath/src/github.com/github/hub/commands/runner.go:115 +0x40
github.com/github/hub/commands.(*Runner).Execute(0xc000052d80, 0x7982f8, 0xc000085f88, 0x405477, 0xc000050058)
	/home/travis/gopath/src/github.com/github/hub/commands/runner.go:100 +0x3b6
main.main()
	/home/travis/gopath/src/github.com/github/hub/main.go:16 +0x58

```

Runtime:

```
GOOS: windows
GOARCH: amd64
```

Version:

```
git version 2.20.0.windows.1
hub version 2.7.1
```

**Comment by mislav** [comment]
Thank you for the report!

Can you check the state of your GITHUB_HOST environment variable and report back? It should be a hostname in the format of `example.com` or `my.example.com:8080` and it shouldn't start with `https://` or anything like that.

If it's a valid hostname that you configured, then this is a bug. In either case, hub shouldn't crash like this and instead should print a helpful error message of what went wrong.

**Comment by nsartor** [comment]
Sorry for the long delay - I probably had https:// in my github host.
I've been trying to get it to work on windows with GHE with no luck. I keep getting "bad credentials"
I have $env:GITHUB_HOST set to github.mycompany.com
Here's what I'm seeing:

> $ hub pull-request
> $ git rev-parse -q --git-dir
> $ git remote -v
> $ git config --get-all hub.host
> GET https://github.COMPANY.com/api/v3/user
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
> HTTP 401
> {"message":"Bad credentials","documentation_url":"https://developer.github.com/enterprise/2.15/v3"}
> Error getting current user: Unauthorized (HTTP 401)
> Bad credentials

I do not have a c:\users\my.account\.config\hub file right now (though i've tried that too).

thank you

**Comment by mislav** [comment]
@nsartor It looks like hub is trying to use the cached token (either in `~/.config/hub` or from GITHUB_TOKEN environment variable), and that token is not valid for `github.COMPANY.com`, therefore 401 is thrown.

You could try to work around this by logging into your GHE web interface, go to `/settings/tokens`, generate a new Personal Access Token, and then pasting it into `~/.config/hub`:

```yaml
github.COMPANY.com:
- user: nsartor
  oauth_token: PASTEDTOKEN
  protocol: https
```

**Comment by nsartor** [comment]
>  or from **GITHUB_TOKEN** environment variable

That was it!
I set that up for some unrelated project that calls the GHE api! I'll re-write that code to use a different variable.
Thank you for your help @mislav
