### ISSUE TITLE
Ability to create remotes that aren't named origin

### ISSUE THREAD

**Issue by pgierz** [github/hub#2025]
Hi guys,

The hub plugin makes my life *much* easier, thanks!!
A feature request: when I use hub create, the remote name is automatically set to origin. While this is certainly a fine default, would there be an easy way to add a command line option for something else? e.g. work, private

This was apparently already asked before, but I can't seem to tell how it was solved.
See also:
#158 #381

Cheers,
Paul

**Comment by mislav** [comment]
There is `hub fork --remote-name work`, for example. Maybe the same flag could exist for `hub create`?

Until then, you can create a script that runs `hub create && git remote rename origin work`

**Comment by pgierz** [comment]
@mislav do you know where this needs to be done? I'd be happy to give this a try but I don't have an overview of the codebase...

**Comment by mislav** [comment]
@pgierz This is where "origin" is hardcoded within the `create` command: https://github.com/github/hub/blob/08004b921836a3fa8ae6054ab273cdbf6da39f8c/commands/create.go#L131

This is how the `fork` command reads the optional `--remote-name` flag: https://github.com/github/hub/blob/08004b921836a3fa8ae6054ab273cdbf6da39f8c/commands/fork.go#L67-L69
