### ISSUE TITLE
hub api to take a raw JSON body

### ISSUE THREAD

**Issue by mlk** [github/hub#2028]
I'd like to be able to interact with [branch protection API](https://developer.github.com/v3/repos/branches/#update-branch-protection). However using the current API it does not look like it supports sending arrays for example.

I'd like a way of just sending a pre-formed JSON body to the API.
i.e.
```

hub api --raw-body '{ "enforce_admins": false, "required_pull_request_reviews": { "dismissal_restrictions": null, "dismiss_stale_reviews": false, "require_code_owner_reviews": false, "required_approving_review_count": 1 } , "restrictions": null, "required_status_checks": { "status": false, "context": [] }  }' -X PUT repos/{owner}/{repo}/branches/master/protection
```

**Comment by mislav** [comment]
Thanks for writing in. Yes, unfortunately we don't support passing array/object fields yet. Your idea to pass raw body in is sound. In addition, I'd like to also support passing array/objects with `--field`, but I don't have an idea yet of how the syntax would look like. 🤔

**Comment by fsouza** [comment]
@mislav I _just_ opened this PR (coincidence, really lol): https://github.com/github/hub/pull/2029

But after reading this issue, I believe that supporting raw JSON fields (in addition to raw JSON body) may be a better solution?

**Comment by mlk** [comment]
Awesome work. Thank you.
