### ISSUE TITLE
Attach release file and ignore edit release message

### ISSUE THREAD

**Issue by andresochoas** [github/hub#2030]
I want to attach files to a release from bash script but when I run `hub release edit $RELEASE_TAG -a $FILE_PATH` hub always forces to edit release message in vi/vim.

Can you parametrize that does not require the editing of the message? This would facilitate the use of hub in scripts

**Comment by mislav** [comment]
From `hub help release`:

> To re-use existing title and body unchanged, pass `-m ""`.

But I agree, this is not optimal. Maybe this will change in a future release. Thanks for writing in!
