### ISSUE TITLE
Label backgrounds continue to the end of the line

### ISSUE THREAD

**Issue by robbieaverill** [github/hub#2032]
Version: latest head

![image](https://user-images.githubusercontent.com/5170590/52398008-8bdf3e00-2ac8-11e9-8a2c-3bb0f1c31201.png)

The `change/patch` label continues to the end of the line.

Follow on from #1960 

Repository in question is https://github.com/silverstripe/silverstripe-ckan-registry

```
$ env | grep TERM
TERM_PROGRAM=Apple_Terminal
LESS_TERMCAP_md=
TERM=xterm-256color
TERM_PROGRAM_VERSION=421.1
TERM_SESSION_ID=C37002D6-1512-4444-9183-B3099C312366
```

**Comment by mislav** [comment]
Thank you for reporting. Is this similar or the same as https://github.com/github/hub/issues/1559?

I don't know what we can do in this case.

**Comment by robbieaverill** [comment]
Yep looks like it, thanks for the reference
