### ISSUE TITLE
Personal News Feed Load Repositories Limitation

### ISSUE THREAD

**Issue by Celestial-intelligence** [github/hub#2033]
OK MicroSoft, why did you restrict loading personal news feed in timeline by 15 days? i don't like this limitation and didn't find additional way to load more by watching project's source code. i need to load more and i do believe i am not alone at this need. pls give me any solution

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. Thank you!
