### ISSUE TITLE
Do not want to change the navigator image on modifying tile sources.

### ISSUE THREAD

**Issue by VenkateshwarRaoB** [github/hub#2035]
Hi,

On modifying/changing  the tilesources/viewer.world.resetItems() , want to keep the original navigator image as it is i.e the navigator image which was at the time of loading the image.

**Comment by mislav** [comment]
Hi, I don't know what your question is about, but it's definitely not about a command line utility called `hub`, for which this place is an issue tracker for. Please find a more appropriate place to ask questions for your framework or library that you're using.

**Comment by VenkateshwarRaoB** [comment]
Hi mislav,
sorry for the inconvenience.
