### ISSUE TITLE
Make `hub help` behave more in line with `git help` (open in pager)

### ISSUE THREAD

**Issue by dbosk** [github/hub#2037]
`git help` currently opens the associated man-page for the command: e.g. `git help clone` is equivalent to `man git-clone`. (This opens the man-page with a pager, e.g. `less`.)

`git help issue` (with `hub alias -s`) simply prints the help text to stdout. That's a long text so one must resort to `git help issue | less`. It would be nice if hub also used a pager (if output is to a terminal) for its help texts. With the current behaviour the help text is sometimes presented with a pager (git native stuff) and sometimes without (hub stuff).

**Comment by mislav** [comment]
Hi thank you for reporting! Which OS and shell type are you seeing this behavior in, and which version of hub are you using?

**Comment by dbosk** [comment]
An up-to-date Ubuntu 18.04.2 LTS.

```
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

$ hub version
git version 2.20.1
hub version 2.7.0
```

I installed it through the Debian package:

  https://tracker.debian.org/pkg/hub

I see now that it's a bit behind.

**Comment by mislav** [comment]
@dbosk Yes, packages might be behind, depending on who is maintaining them. Can you download the latest version from our Releases page?

**Comment by dbosk** [comment]
Installed hub 2.9.0 for Linux 64-bit. Works perfectly, sorry for the 
noise.
