### ISSUE TITLE
Allow explicit --color flag in hub issue command

### ISSUE THREAD

**Issue by dsifford** [github/hub#2041]
Hi there,

This seems like it would be a fairly straightforward adjustment and I would totally do it if I wasn't so perplexed by the oddities of go and gopath and how the heck to contribute and test.

Anyway, what I'd suggest is that an explicit `--color` flag should be added to the `hub issue` command to allow explicit color output even when piped. This is useful particularly for me because I'd like to pipe to [fzf](https://github.com/junegunn/fzf) and use that to select an issue.

Here's the line that would need adjusting:

https://github.com/github/hub/blob/28ebb7ceaf868520025758aafd63f386bf19dc32/commands/issue.go#L288-L291

Thanks for considering.

**Comment by dsifford** [comment]
Thanks a lot for implementing this @mislav!

Totally nit-picking here, but what's the rationale for indenting the issues list output? It's tough to manually un-indent with sed for processing while also maintaining these beautiful color escape sequences.

Any chance I can convince you to not indent the output in the first place?

Thanks for considering 😊

**Comment by mislav** [comment]
> but what's the rationale for indenting the issues list output?

It might not be immediately apparent, but because issue IDs are variable width (depending on the number of digits), we pad them with spaces on the left so that they become right-aligned and, as a consequence, have all issue titles be vertically aligned as well.

> It's tough to manually un-indent with sed for processing while also maintaining these beautiful color escape sequences.

If you're passing down output to another program, you should be using `--format` to define your own machine-readable format, e.g.

```sh
hub issue -L20 --color --format='%sC%i%Creset %t%n'
```

**Comment by dsifford** [comment]
> It might not be immediately apparent, but because issue IDs are variable width (depending on the number of digits), we pad them with spaces on the left so that they become right-aligned and, as a consequence, have all issue titles be vertically aligned as well.

Aha... Nope, hadn't thought of that. 

> If you're passing down output to another program, you should be using --format to define your own machine-readable format, e.g.

Ooh, fancy. That solves my issue completely :+1: 

Thanks again!
