### ISSUE TITLE
Is it possible to locally checkout an open PR given only URL?

### ISSUE THREAD

**Issue by nikitavoloboev** [github/hub#2048]
I have an URL of the open PR like `https://github.com/nikitavoloboev/markdown-parser/pull/13`. 

Is it possible to in one command to locally checkout that PR? Basically do this:

```
git checkout -b johnletey-pr/extend-parser master
git pull https://github.com/johnletey/markdown-parser.git pr/extend-parser
```

Without me having to type all of it as I find it annoying copying these two lines every time.

Thank you.

**Comment by nikitavoloboev** [comment]
Something like `hub local checkout https://github.com/nikitavoloboev/markdown-parser/pull/13` would be perfect.

**Comment by mislav** [comment]
Yes! From `hub help hub-checkout`:

```
hub checkout <URL> [<BRANCH>]
```

The `<BRANCH>` name to check out to is optional and defaults to the head branch of the PR.
