### ISSUE TITLE
Allow command to be run to save/load personal access token.

### ISSUE THREAD

**Issue by idcmp** [github/hub#2049]
As a SSO user of GHE, I use my SSO workflow to authenticate to GHE's website, and I have an SSH key which I use for doing normal Git operations. My SSH is protected through various mechanisms.

In order to make use of `hub` I need to create a personal access token and store it on my local machine.

I would like to be able to store this token in a mechanism that I prefer, and then fetch it when needed.

You can imagine:

```
$ hub action-that-requires-credentials --oauth-token-cli=/usr/local/bin/hub-oauth-token-cli
Your name: idcmp
Password: ...

$ cat ~/.config/hub
github.example.com:
- user: idcmp
  oauth_token_cli: /usr/local/bin/hub-oauth-token-cli
  protocol: https
```
Possibly the usage would be:

```
$ /usr/local/bin/hub-oauth-token-cli save github.example.com idcmp ab0cad0e0f0a234
$ /usr/local/bin/hub-oauth-token-cli load github.example.com idcmp
ab0cad0e0f0a234
```

**Comment by mislav** [comment]
That's a good idea! Maybe we could even re-use git's credential helper by default.

However, this isn't the first time features related to this were suggested, so I'm going to close this in favor of #1912 #1217 #889 #225. Thank you for writing in!
