### ISSUE TITLE
Is there any way to open the projects board of a repo?

### ISSUE THREAD

**Issue by fr3fou** [github/hub#2053]
Something like
```sh
hub browse github/hub projects
```
Should open [this](https://github.com/github/hub/projects) or even something like this
```sh
hub browse github/hub projects/roadmap
```
which should open [this](https://github.com/github/hub/projects/1)

**Comment by fr3fou** [comment]
nvm, this actually works, I was just doing
```sh
hub browse github/hub project
```
rather than
```sh
hub browse github/hub projects
```
which was not opening anything, sorry for the inconvenience.

What about the other idea though - opening a specific project board? Is something like that possible?

**Comment by mislav** [comment]
To open a specific project board:

```
hub browse github/hub projects/1
```

or, in the currently checked-out repository:

```
hub browse -- projects/1
```

You will have to know the project board ID, though.
