### ISSUE TITLE
fish shell completion installation instructions are incorrect

### ISSUE THREAD

**Issue by selik** [github/hub#2054]
Currently, the instructions reference `etc/hub.fish_completion`, but this file appears to be in the `share` folder.

```
2019-Feb-21 16:46:49 ><> tree /usr/local/Cellar/hub/2.9.0/
...
├── etc
│   └── bash_completion.d
│       └── hub.bash_completion.sh
└── share
    ├── fish
    │   └── vendor_completions.d
    │       └── hub.fish
...
```

**Comment by mislav** [comment]
If you are using Homebrew, then the manual completion installation instructions don't apply to you. The documentation already indicates this.

I'm not sure what's the official way to set up fish with Homebrew, but see `/usr/local/share/fish/config.fish` for pointers.

Please let us know when you resolve it!

**Comment by selik** [comment]
> If you are using Homebrew, then the manual completion installation instructions don't apply to you. The documentation already indicates this.

The docs seem to say that for bash shell with Homebrew, but not for fish shell.

**Comment by mislav** [comment]
I've pushed a clarification to the docs. For zsh + Homebrew, no extra steps should be needed after `brew install hub`.
