### ISSUE TITLE
[Feature request] Allow anonymous user to send issue without account

### ISSUE THREAD

**Issue by xsellier** [github/hub#2060]
Hello,

I'm the solo developer of City Game Studio (Steam game), and I want to use a github repository as a bugreporter/feature suggestions. However, to create an issue/post a suggestion, you need to create an account on github first.

To me, it would be better if we can send issue without having any account.
About spammers, add a captcha before everysingle operation.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
