### ISSUE TITLE
Add ability to get list of milestones from 'hub issue' command

### ISSUE THREAD

**Issue by galak** [github/hub#2063]
In the same way that issue can get a list of labels, there should be the ability to get a list of milestones.

**Comment by mislav** [comment]
Hi thank you for your feature request! The ability to list, create, and edit milestones is not on our roadmap yet, but in the meantime, you can use `hub api` to achieve what you need.

```sh
milestones() {
  hub api --cache 3600 graphql -f query='
    {
      repository(owner: "{owner}", name: "{repo}") {
        milestones(first: 100, states: OPEN, orderBy: {field:CREATED_AT, direction:DESC}) {
          edges {
            node {
              title
              number
            }
          }
        }
      }
    }
  ' | jq -r '.data.repository.milestones.edges[].node | [.number,.title] | @tsv'
}
```

**Comment by mlewand** [comment]
Somewhat related, but more general feature request for milestone handling in #2106.

**Comment by mislav** [comment]
I'm closing this in favor of the larger scope conversation about milestone features in the aforementioned thread.
