### ISSUE TITLE
add ability to specify "not" label or milestone

### ISSUE THREAD

**Issue by galak** [github/hub#2064]
In the github search for an issue, one can do something like "-label:bug" to show all issues that do NOT have the label 'bug'.  We should have some means to do this with the hub issue command.

**Comment by mislav** [comment]
That's not a bad idea, but we're limited to what [the API for issues](https://developer.github.com/v3/issues/#list-issues-for-a-repository) can query, and there's no way to exclude labels or milestones. We would have to switch to using the Search API for that, which would entail significant refactoring.

Until this is possible in hub core, you can use the `hub api` command to manually query the Search API. The recommended way is to do it via GraphQL so you can select just the fields that you need. Example:

```sh
search-issues() {
  hub api --cache 3600 graphql -f q="${1?}" -f query='
    query($q: String!, $per_page: Int = 100, $after: String) {
      search(query: $q, type: ISSUE, first: $per_page, after: $after) {
        edges {
          node {
            ...on Issue {
              number
              title
            }
            ...on PullRequest {
              number
              title
            }
            ...on Labelable {
              labels(first: 10) {
                edges {
                  node {
                    name
                  }
                }
              }
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  ' | jq -r '
    .data.search.edges[].node
    | [.number, .title, ([.labels.edges[].node.name] | join(","))]
    | join("\t")
  '
}

search-issues 'repo:github/hub is:open sort:created-desc -label:feature'
#=> outputs fields separated by tabs: issue number, title, comma-separated labels
```
