### ISSUE TITLE
Use hub Command in jenkins Free style job

### ISSUE THREAD

**Issue by Raghu7997** [github/hub#2065]
I want to automate the Open pull request in GitHub, so i'm creating a free style job in Jenkins which build my code and after successfully build it open a pull request on Github. for Open pull request i'm using "hub pull-request -h branch -m "message" " but when I run the job it's asking me for the credentials as then terminate the job

help me how I'm fix this problem

**Comment by mislav** [comment]
1. Generate a Personal Access Token (also known as OAuth token) that your CI job will be using https://github.com/settings/tokens;
2. Make that token available in your CI job under the `GITHUB_TOKEN` environment variable.

This will avoid asking you for any authentication information. See `hub help hub` for more information
