### ISSUE TITLE
change the base of an existing PR

### ISSUE THREAD

**Issue by brianjmurrell** [github/hub#2076]
Just as you can use the `-b <base_branch>` argument to `hub pull-request` when creating a PR, it would be useful to be able to change the base branch on an existing PR.

This is useful in the workflow where you have stacked a few PRs on top of each other and are now landing them, but want to land from the bottom of the stack up, so that each PR is landed separately rather than landing from the top down where you just keep merging one PR into another until you finally merge one large PR into the base branch.

For the desired workflow, one needs to land the first PR (let say, to **master** for the example), then merge **origin/master** into the second PR, then set the base branch of that PR to **master** and land that.  Rinse repeat, until the whole stack is landed.

Having to keep going back to the GitHub website to do that base branch change is tedious and goes completely against the goal of `hub` (IMHO).

**Comment by mislav** [comment]
Thanks for writing in! This is planned as part of the feature to update pull requests #1523

**Comment by brianjmurrell** [comment]
Excellent!
