### ISSUE TITLE
feature request: search commit

### ISSUE THREAD

**Issue by dhanyn10** [github/hub#2078]
in my repository, i've 100+ commits. for some reason i need to search some specific commit. i still remember some word from commit message so i hope there's any features to find which commit i need. so in future i dont need to come in every page that showing the commit history and read every commit message.

**Comment by dhanyn10** [comment]
im sorry to write this feature request here.

**Comment by mislav** [comment]
Hello! Using the GitHub web interface, you can search commits in a repository like so: https://github.com/github/hub/search?q=clarify&type=Commits

This feature is not available in `hub`, but you can use `git log --grep=<word>` to search for commits that contain a specific word in the locally cloned repository.
