### ISSUE TITLE
Cloning not working as protocol is unsupported

### ISSUE THREAD

**Issue by SirWindfield** [github/hub#2081]
Hey!

I'm on a fresh Arch Linux installation and cannot get `hub` to work properly. I changed `hub.protocol` to `ssh` and even passed the environment variable `HUB_PROTOCOL` but `hub` still insists on using `git:` as the protocol to clone repositories.

Running `hub clone someuser/somerepo` returns this error:
```
Error getting repository info: Get git://api.github.com/repos/someuser/somerepo: unsupported protocol scheme "git"
```

Is there something I am missing? I remember that it worked on my last setup for sure.

**Comment by mislav** [comment]
Hi there, can you try the latest hub version for this? https://github.com/github/hub/releases

BTW, the git/ssh protocol is default (you don't have to set anything special for it). Public repos will be cloned over `git:` and private repos (or those you have write access to) will be cloned over `ssh:`.

However, `Get git://api.github.com` is just wrong because the API should only ever be accessed over `https:`, therefore I suspect you have an outdated `hub version`.

**Comment by SirWindfield** [comment]
Hi!

I checked my local version of `hub` and it seems to be the latest.
```
git version 2.21.0
hub version 2.10.0
```

I also tried out the Github release too though, as I use the Arch release from the community repository.
I get the exact same error when trying to clone via the `<username>/<reponame>` shorthand.

**Comment by mislav** [comment]
Can you check `~/.config/hub` and see if there is the `protocol` setting there? It should be missing or be `https` for API requests

**Comment by SirWindfield** [comment]
Haha thanks! The protocol was actually set to `git`. Strange, as I re-installed Arch Linux from scratch and didn't tinker around at all with hub until two days ago when I noticed that cloning didn't work. 

Thanks for helping me out.
Cheers!

**Comment by mislav** [comment]
@SirWindfield Glad you solved it! Do you have an idea what might have set `git` as a value there? Values other than `https` and `http` aren't supported there

**Comment by SirWindfield** [comment]
I have no idea. It was a completely new fresh system. I ran `pacman -S hub` to get the latest version of hub and wanted to clone my dotfiles via `hub clone SirWindfield/dotfiles` but that failed with the error message I posted above. I had to enter my credentials though.
