### ISSUE TITLE
Extend log sub-command so that commits can list information of original pull requests 

### ISSUE THREAD

**Issue by DennisSchiefer** [github/hub#2086]
Connect commits in a repository to their pull-requests so that a `hub log` can also show information of the original pull-request like labels, tests passed, ...

**Comment by mislav** [comment]
Hi this is not a bad idea, but hitting the GitHub API for every individual commit would be slow, and therefore it's not very likely that we will be eveer wrapping and expanding `git log` output from within hub. Check out this issue for explanation of how you can look up pull requests based on a commit manually https://github.com/github/hub/issues/854#issuecomment-457859395
