### ISSUE TITLE
What's `NameRe` pattern in aid of?

### ISSUE THREAD

**Issue by kyoh** [github/hub#2087]
https://github.com/github/hub/blob/master/commands/commands.go#L12

This pattern equals to `..*`.
What is this pattern in aid of?

**Comment by mislav** [comment]
This pattern equals to `[\w.][\w.-]*`, where `.` is the literal period character (it doesn't have any special meaning inside `[]`).

However, now that you've made me inspect the regexp more closely, I've noticed that it disallows repositories starting with a `-` character, whereas those are allowed on GitHub, so I will amend the pattern accordingly.

**Comment by kyoh86** [comment]
@mislav 
Thank you for your responce. It's my misunderstanding 😳

By the way, `OwnerRe` is desirable to be stricter like below.

```
OwnerRe := `[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*` // GitHub does not allow double-hyphens in user name.
```

https://github.com/github/hub/blob/master/commands/commands.go#L13

**Comment by mislav** [comment]
@kyoh86 Thank you for pointing that out! For now, allowing double-hyphens is not a big deal, even if GitHub disallows them, since we only use the pattern to recognize `repository` or `owner/repository` arguments on the command-line.
