### ISSUE TITLE
list users repos (public/private)

### ISSUE THREAD

**Issue by nelsonov** [github/hub#2089]
Is there a way with hub to list the repos of a user?  Can the same be done for private repos, assuming proper authentication?

I frequently forget the names of my repos and there don't seem to be any convenient ways to get a list from the cli.

**Comment by mislav** [comment]
There's no built-in way yet (and this is not on our roadmap either) but it can be accomplished via `hub api` manual calls. Example: https://github.com/github/hub/issues/1419#issuecomment-473861104
