### ISSUE TITLE
importing project from gitlab takes more than 15+ hrs and still importing 

### ISSUE THREAD

**Issue by Vishnu05** [github/hub#2092]
![Annotation 2019-03-25 064451](https://user-images.githubusercontent.com/32086222/54889264-bbf06e00-4ec9-11e9-8342-934b56540570.jpg)

**Comment by vitalkanev** [comment]
This repository is used for a help with the *hub* command line utility. For a help with *GitHub.com*, [contact support](https://github.com/contact).

**Comment by mislav** [comment]
Thank you @vitalkanev.
