### ISSUE TITLE
Output disappears when piping

### ISSUE THREAD

**Issue by morganwahl** [github/hub#2094]
I'm trying to use a list of PR labels in a shell script (bash). When I invoke `hub` to get the labels using the `%L` format, the labels are output. When I pipe its output to another command, all it outputs is a newline.

Example:

```bash
(dev1) morgan@morgan-zbook-774:~/Development/dev1$ hub pr list -h mw/test.sh-full-suite -f "%L%n" 
Has Migration, Maintenance Window
(dev1) morgan@morgan-zbook-774:~/Development/dev1$ hub pr list -h mw/test.sh-full-suite -f "%L%n" | cat

(dev1) morgan@morgan-zbook-774:~/Development/dev1$
```

Where `mw/test.sh-full-suite` is the name of a branch and `Has Migration, Maintenance Window` are two labels.

**Comment by mislav** [comment]
Good catch; thank you! I've opened a PR to fix this.
