### ISSUE TITLE
`hub` does NOT handle `--git-dir` and `--work-tree` properly

### ISSUE THREAD

**Issue by sarpik** [github/hub#2095]
Hello,

### Runing `--git-dir` and `--work-tree` with normal (non-aliased) git works as expected:

```bash
alias git=git
git --git-dir=$HOME --work-tree=$HOME
```

shows the default `git --help` output

### And running the same options with `hub` does NOT work properly:

```bash
hub --git-dir=$HOME --work-tree=$HOME
```

shows 
```console
git: '' is not a git command. See 'git --help'.

The most similar commands are
    add
    bisect
    branch
    <...>
   show
   status
   tag
```

expected behaviour:
the default message of `hub` (`hub --help`)

---

## Why does it matter?

Well,  it's an inconsistency. `hub` should give the same output as git (this is why I'm submitting this issue).

To fix this, you'd need to make `hub` give the `hub --help` message when called with `--git-dir` and `--work-tree` instead of giving the error / command suggestion message.

> It would be smart to test out other options to make sure that they don't produce the same error / unexpected behaviour as these ones! I just happened to notice them, but there might be more inconsistency when treating options.

That's it!

---

## Some context and why I care

I have a dotfile tracking setup [as explained in the arch wiki](https://wiki.archlinux.org/index.php/Dotfiles)

Short explanation:

I have a `$HOME/.dotfiles` BARE git repository
I have an `alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' ` which allows me to track my dotfiles without making my $HOME a git repository.

I would like to replace `/usr/bin/git` with `/usr/bin/hub`.

Here comes the problem - if I just run `config` - instead of getting the default git's output, I get the error message as explained above. I don't like that:D
I cannot append a `--help` to the `config` alias - then the alias becomes useless.

---

## More details

Running 
```bash
HUB_VERBOSE=1 hub --git-dir=/home/kipras/.dotfiles/ --work-tree=/home/kipras
```

gives
```console
$ git --git-dir=/home/kipras/.dotfiles/ --work-tree=/home/kipras config alias.
$ git --git-dir=/home/kipras/.dotfiles/ --work-tree=/home/kipras
git: '' is not a git command. See 'git --help'.

The most similar commands are
    add
    bisect
    branch
    checkout
    clone
    commit
    diff
    fetch
    grep
    init
    log
    merge
    mv
    pull
    push
    rebase
    reset
    rm
    show
    status
    tag
```

Also related: https://github.com/github/hub/issues/1199

**Comment by mislav** [comment]
Thank you for reporting! I've opened a PR to fix this.

I think that if you use hub with `--git-dir=` or `--work-tree=` more, you might find more breakage. Please do report when such a thing occurs. The thing is, we do forward `--git-dir=...`, `--work-tree=`, `-c <config>`, `-C <dir>` and similar to underlying git calls, but we don't respect them in hub's own operations. Sometimes that doesn't matter, but [sometimes it does](https://github.com/github/hub/issues/2058). I hope to improve this in the future!

**Comment by sarpik** [comment]
Thank you for responding and fixing this so quickly @mislav! If I encounter any other related issues I'll be sure to report them too! Have a nice day:)
