### ISSUE TITLE
Unable to create normal pull request

### ISSUE THREAD

**Issue by mk0x9** [github/hub#2099]
I'm trying to create pull request and draft pull requests aren't enabled for my repo. I don't pass `-d` flag to the hub.

```
$ git pull-request
Waiting for Emacs...
Error creating pull request: Unprocessable Entity (HTTP 422)
Draft pull requests are not supported in this repository.
$ git version
git version 2.20.1 (Apple Git-117)
hub version 2.11.0
```

**Comment by nickgravgaard** [comment]
I have the same problem. It looks like the header is always set regardless of the new --draft flag. See https://github.com/github/hub/commit/b207e803589624a56daaaa54bc4f8a8af62d1aa2

**Comment by mislav** [comment]
Thanks you for reporting! This looks like a bug with GitHub API. Working on it!

**Comment by mk0x9** [comment]
In the meantime you can install v2.10.1 with homebrew:

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/5bccd9380e0b68e1d967eff99ced1bb7024abeb2/Formula/hub.rb
$ brew pin hub
```

Don't forget to unpin it later.

**Comment by mislav** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/38488 with a hub version bump

**Comment by sgallagher** [comment]
@mislav I see that you tagged 2.11.1 in git but haven't done a formal release. Is that forthcoming or should those of us who are packaging for distros just pull this patch atop 2.11.0?

**Comment by mislav** [comment]
@sgallagher https://github.com/github/hub/releases/tag/v2.11.1
