### ISSUE TITLE
`hub api` pagination issues on listing comments

### ISSUE THREAD

**Issue by jpigree** [github/hub#2100]
Hi. I use Hub (version 2.10.0) a lot for my CI/CD script however, I have a strange behavior lately.

I use this command to retrieve all the issue comments from a Pull Request:
```hub api  "repos/<org>/<repo>/issues/<pr number>/comments```

It works most of the time but on one particular PR, it does not retrieve all comments. This PR has 57 comments. I tried getting the github API with "curl" and it confirmed what I thought. It is a pagination issue. Without a "per_page" defined, I have the exact same list of comments returned that hub. 

I searched the "hub" documentation to find a way to specify the HTTP parameter "per_page" and "page" to influence pagination but couldn't find any.

Are all the hub requests using default pagination? Is there a way to pass HTTP parameters through the cli interface?

I will use curl instead of hub until this is fixed. 

Thanks

**Comment by mislav** [comment]
Hello, thank you for trying out `hub api`!

This command makes plain API requests and is very similar to curl. It currently doesn't handle any aspects of pagination, which means that you will have to do it yourself.

Passing `per_page` or any other parameter is easy:

```
hub api -i 'repos/<org>/<repo>/issues/<pr number>/comments?per_page=100'

# or, alternatively:
hub api -i -XGET repos/<org>/<repo>/issues/<pr number>/comments -F per_page=100 -F any_other_argument=any_value
```

Notice I've added `-i` which includes HTTP response headers in the output. If there is ever a next page of results, the URL to fetch it will be present in the `Link` header. You can parse out the header, extract the "next" link, use that with the next `hub api <next-url>`, and repeat until you've fetched all pages of results.

Alternatively, you can use the GraphQL API and use cursor pagination. Here's a full-featured example of how you would do it for fetching comments: https://gist.github.com/mislav/63c8e9f130020fe66b0947916022614d

**Comment by jpigree** [comment]
I thought I tried the `hub api -i 'repos/<org>/<repo>/issues/<pr>/comments?per_page=100'` command but I didn't. It works really well. :)

I think my main problem was that I couldn't make sense of the documentation especially of the  '-F'. I thought this was for POST requests only. There is a sentence saying that with -XGET it changes behavior but without describing it. It maybe obvious but I didn't understood it at the time.

Anyway, with your examples and your explanations, it is really clear now.

Thank you very much @mislav.

**Comment by mislav** [comment]
The documentation says:

> Use `-XGET` to force serializing fields into the query string for the GET request instead of JSON body of the POST request.

I'm sorry if this wasn't clear! I welcome any pull requests that improve the documentation ❤️
