### ISSUE TITLE
Does hub pull-request support ssh now?

### ISSUE THREAD

**Issue by h00130372** [github/hub#2105]

**Comment by h00130372** [comment]
Wonder to know whether hub pull-request support ssh in latest release?

**Comment by mislav** [comment]
Hub commands like `hub issue` and `hub pull-request` all make HTTPS requests to the GitHub API, and our API is only accessible over HTTPS. Therefore, **SSH is not supported in any of these commands**. SSH is only supported in git protocol when cloning/pushing/pulling, but this is all regular git functionality that is completely separate from hub.

More information here: https://github.com/github/hub/issues/1644#issuecomment-359002547

**Comment by h00130372** [comment]
Ok, thank you very much.
