### ISSUE TITLE
Relevant Open Graph image for repositories

### ISSUE THREAD

**Issue by Canop** [github/hub#2109]
Link overviews based on Open Graph meta data are everywhere and are now an essential part of navigating.

GitHub correctly serves OG data for link to users. But links to repositories are much more interesting.

Here's how a link to a repository looks like today in a random application:

![link preview](https://miaou.dystroy.org/file-host/1c6cfac5be902a8144ecd53a.png)

The problem here is that the image provided for GitHub repositories (and issues, PR, etc.) is the avatar of the repository owner, which makes zero sense.

Such a preview is made by many tools everywhere and is based on the same meta data than for any other site/article.

We need a way to specify what's the relevant illustration for a repository (for example a conventional file in the repository itself) , just like we already specify the description, and this image should be served in the relevant meta tag:

     <meta property="og:image" content="https://some/path/to/the/repository/illustration?s=400&amp;v=4" />

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
