### ISSUE TITLE
rpm distribution

### ISSUE THREAD

**Issue by azinger-sailthru** [github/hub#2112]
Would it be possible to support an rpm distribution of hub?

**Comment by mislav** [comment]
Sure, it's possible! But I have no experience creating rpm distributions and I likely won't be the person who does it. Most packaged distributions are done by people other than the original project's maintainers. There's nothing stopping anyone from creating and maintaining an rpm distribution for hub!

If you feel like this answers your questions, please close the issue. Thank you

**Comment by larsks** [comment]
I just wanted to confirm that packaging for Fedora is typically handled by contributors to Fedora, not by upstream software authors.  If you want to create an RPM distribution for `hub`, you could do that yourself.  A good starting point is [this document](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers).

**Comment by mislav** [comment]
@larsks Thank you. Going to close this issue since anyone is already able and welcome to package and submit hub to their distro of choice.
