### ISSUE TITLE
Gist upload 

### ISSUE THREAD

**Issue by gokceneraslan** [github/hub#2116]
It'd be great to be able to upload a file as public or private Gist using hub. When used together with nbviewer it'd be a super convenient way to share Jupyter notebooks.

**Comment by us** [comment]
Good idea! 

Please give a `future` label.

**Comment by mislav** [comment]
You can already relatively easily create a gist using `hub api`. The only tricky part is that the JSON payload needs to be manually constructed. In this example I do that with jq:

```sh
gist() {
  local filename
  local public=false
  if [ "${1:-}" = "--public" ]; then
    public=true
    shift 1
  fi
  filename="${1?}"
  jq -nR --arg filename "$filename" --argjson public "$public" '
    {"files":{($filename):{"content":input}},public:$public}
  ' "$filename" | hub api gists --input - | jq -r '.html_url'
}

gist myfile.txt
gist --public myfile.txt
```

Creating or editing gists is not anywhere near on our roadmap for hub so I'm going to close this for now.

**Comment by theduke** [comment]
Shame, this would be really useful functionality.
