### ISSUE TITLE
cloning private repositories

### ISSUE THREAD

**Issue by luxerama** [github/hub#212]
Hi,

Should I be able to clone private repositories with:

```
git clone orgname/reponame
```

Because when I try that atm I am getting the following error:

```
Cloning into 'reponame'...
fatal: remote error: 
  Repository not found.
```

I can successfully use features like `git pull-request`

These are the versions I use (hub is installed via brew):

```
$ git version                                                         [ruby-1.9.3-p194]
> git version 1.7.9
> hub version 1.10.1
```

**Comment by Masar92** [comment]
If I try this command git clone -p orgname/reponame , the output is unknown switch 'p'.
I'm new in githup , the repository is private and the URL is correct

**Comment by mislav** [comment]
@Masar92 This issue tracker is for a specific project called `hub`, not for git and GitHub in general. Many people alias `hub` as `git`, and thus get extra features when they perform commands like `git clone`. However, if you never installed hub, then you can still clone private repositories normally like so:

```sh
# using HTTPS:
git clone https://github.com/orgname/reponame.git

# using SSH:
git clone git@github.com:orgname/reponame.git
```

**Comment by divya-kanak** [comment]
`git clone https://myusername:mygithubpassword@github.com/myusername/project.git`

When you are using private repo you need to pass on username and password like above.
