### ISSUE TITLE
hub clone yields `cd: too many arguments`

### ISSUE THREAD

**Issue by vict0rsch** [github/hub#2123]
Here is the error I get:

```
$ hub clone cc-ai/floods-frontend
cd: too many arguments
```

**Comment by mislav** [comment]
Thank you for reporting! 

1. Which `hub version` do you have? Does it still happen with the lastest version?
2. Can you do `HUB_VERBOSE=1 hub clone ...` and see if there's anything that stands out in the output?

**Comment by RajatVaryani** [comment]
@mislav This is not happening in the latest version. A quick suggestion about adding a note while raising an issue if the latest version of the hub is used. Wdyt?

**Comment by vict0rsch** [comment]
My bad some debugging showed I had a command conflict with another script. Everything is fine on my end eventually
