### ISSUE TITLE
Uploading Avatar

### ISSUE THREAD

**Issue by ukor** [github/hub#2125]
There seems to be an issue with uploading an avatar. When I try changing my avatar, nothing happens after picking a file.

- No progress bar to indicate upload progress.
- No error message if something goes wrong

I think it will be really helpful to know what is happening when uploading avatars.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!

Regarding this issue: when reporting this problem to Support, please include any JavaScript console errors that might have appeared in your browser! In Chrome, these can be found in View > Developer > JavaScript Console.
