### ISSUE TITLE
[Feature] Convert a draft pull request to a non-draft pull request

### ISSUE THREAD

**Issue by mxstbr** [github/hub#2126]
Based on #2038, once one has a draft pull request it would be cool to have a way to turn it into a non-draft pull request! Maybe by running `hub pull-request` again without the draft flag?

**Comment by mislav** [comment]
Good question! This should be possible once we implement updating pull requests https://github.com/github/hub/issues/1523. No such work has started yet, however.

**Comment by stwr667** [comment]
> Based on #2038, once one has a draft pull request it would be cool to have a way to turn it into a non-draft pull request! Maybe by running `hub pull-request` again without the draft flag?

FYI you can do it now by clicking on the "Ready for Review" button at the bottom of the page.

**Comment by mislav** [comment]
Also something you can try from the command-line with `hub api`: https://github.com/github/hub/issues/2312#issuecomment-544626863 /@mxstbr
