### ISSUE TITLE
Suggestion: Add a label for each supported platform

### ISSUE THREAD

**Issue by peteraritchie** [github/hub#2129]
Add a label for each supported platform and add labels to issues that are platform-specific

**Comment by mislav** [comment]
Good idea, but I don't have a list of each supported platforms. Basically, hub runs on any platform that Go programs can run, and that is _a lot_ of them. Also, we usually don't have issues specific to a platform (e.g. we don't have issues specific to Linux or macOS) unless it's Windows. Should we then add a "windows" label?

**Comment by mislav** [comment]
Closing because I'm not sure what is actionable for me from this issue.
