### ISSUE TITLE
For repositories that user has write access to, set correct URL

### ISSUE THREAD

**Issue by eproxus** [github/hub#213]
Cloning a repository which the user has write access to should produce the following url instead:

```
url = git@github.com:USER/REPO.git
```

in `.git/config` instead of:

```
url = git://github.com/garazdawi/alm.git
```

so that the user can do a push directly with seeing the following:

```
$git push
fatal: remote error: 
  You can't push to git://github.com/USER/REPO.git
  Use git@github.com:USER/REPO.git
```

**Comment by alhaj1** [comment]
You can't push to git://github.com/alhaj1/cmsc202.git
  Use https://github.com/alhaj1/cmsc202.git
what should I do
