### ISSUE TITLE
WAZUH FIM IDENTITY DETECTION AND CORRUPT WAZUH REPORT 

### ISSUE THREAD

**Issue by DavidEbuka23** [github/hub#2137]
Hello Community,

I want to achieve having wazuh FIM report to tell us who carried the change and the time he carried the change and not the email timestamp.

Would be grateful if this can be achieved.

Any luck, please?

**Comment by mislav** [comment]
Hi, I'm not sure what this is about, but it doesn't sound like it's related to this project called "hub". If you wanted to write to GitHub Support, please write to support@github.com
