### ISSUE TITLE
"hub issue show" throws error: unknown subcommand show

### ISSUE THREAD

**Issue by petermbenjamin** [github/hub#2144]
## Problem

The man pages for `hub` shows

```
NAME
       hub-issue - Manage GitHub Issues for the current repository.

SYNOPSIS
       ...
       hub issue show [-f FORMAT] NUMBER
       ...

COMMANDS
       ...
       show
           Show an existing issue specified by NUMBER.
       ...
```

However:

```
$ hub issue show 1
error: Unknown subcommand: show
```

## Expected

Expected `hub` to show content of the issue specified.

## Actual

Error message: `error: Unknown subcommand: show`

## Debug Info

```
$ hub version
git version 2.21.0
hub version 2.5.1
```

## Additional Info

![Screen Shot 2019-05-23 at 6 40 38 PM](https://user-images.githubusercontent.com/6811830/58296938-aa70f880-7d8a-11e9-9797-c7f5cdc6f432.png)

**Comment by mislav** [comment]
`hub issue show` was added to hub 2.6.0 more than 6 months ago. You have an outdated version of hub, but somehow you have man pages for a newer version of hub. You might have duplicate installations on your system. Check with `which -a hub`.

Solution: remove duplicate installations from your system and upgrade to the latest version of hub.
