### ISSUE TITLE
Browse PR by number

### ISSUE THREAD

**Issue by whatsadebugger** [github/hub#2148]
ability to quickly open a pr in the browser.
```
hub browse pr 1400
hub browse pr <- current branch's pr maybe?
```
alternatively this functionality can be added to the pr sub command.

`hub pr browse PR#`

the latter might be better because it would match the user experience of hub pr checkout PR#.

I would love to add this feature myself if possible.

**Comment by mislav** [comment]
Take a look at https://github.com/github/hub/pull/2141. Perhaps you can extend that approach to implement `hub pr show 1400`? Without the PR number, the command would show the PR associated with the current branch.

**Comment by ashemesh** [comment]
I thought about implementing this as well, @whatsadebugger write to me if you want me to do it or if your already doing this

**Comment by whatsadebugger** [comment]
Sorry was out on vacation i will try to crack at this tonight in my spare time. Should have a pr by this weekend.

**Comment by whatsadebugger** [comment]
@ashemesh go ahead and incorporate this into your PR. Don't want to duplicate that function and cause conflicts. Sorry for delaying.

**Comment by mislav** [comment]
Done in https://github.com/github/hub/pull/2141 thank you!
