### ISSUE TITLE
hub create ignoring GITHUB_HOST

### ISSUE THREAD

**Issue by ericdriggs** [github/hub#2150]
$ git config --global --add hub.host github.mycompany.com
$ GITHUB_HOST=github.mycompany.com
$ echo $GITHUB_HOST
github.mycompany.com
$ hub init
$ hub create
github.com username: 

Expected: "github.mycompany.com username:"
Actual: "github username:"

**Comment by ericdriggs** [comment]
$ hub --version
git version 2.20.1 (Apple Git-117)
hub version 2.11.2

**Comment by mislav** [comment]
You did `GITHUB_HOST=github.mycompany.com` in your shell, but you did not `export` it:

```sh
export GITHUB_HOST=github.mycompany.com
```

Without `export`, the value is not available to sub-processes, including `hub`.

**Comment by ericdriggs** [comment]
PEBKAC. tyvm
