### ISSUE TITLE
`create` prints an error message with a literal \n in it:

### ISSUE THREAD

**Issue by aryairani** [github/hub#2162]
```
$ hub create aryairani/hubtest
A git remote named "origin" already exists and is set to push to 'ssh://git@github.com/aryairani/tmp.git'.\nhttps://github.com/aryairani/hubtest
```
I assume it's supposed to be an actual line break instead of actually printing `\n`. :)

I don't know golang, so I won't attempt to mess with it, but:

I'm guessing [this multiline string](https://github.com/github/hub/blob/28ebb7ceaf868520025758aafd63f386bf19dc32/features/create.feature#L142) shouldn't include a `\n`, and guessing lines 287 and 312 shouldn't either.

And, at the end of [this line](https://github.com/github/hub/blob/28ebb7ceaf868520025758aafd63f386bf19dc32/commands/create.go#L139), I'm guessing `\n` doesn't escape in backticks, so it should be added some other way, e.g. by appending a normal `"\n"` string.

**Comment by mislav** [comment]
Nice catch; thank you!
