### ISSUE TITLE
Can't solve the issue with the carthage on mac os

### ISSUE THREAD

**Issue by jillverberg** [github/hub#2167]
I've installed the latest version of carthage (0.33.0) and got this message in the terminal:
*** Fetching vk-ios-sdk
*** Checking out vk-ios-sdk at "1.4.6"
*** xcodebuild output can be found in /var/folders/n8/8fy5fd9x3dq3w98p7cx20sxh0000gn/T/carthage-xcodebuild.87m5B5.log
*** Skipped downloading vk-ios-sdk.framework binary due to the error:
	"Bad credentials"
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/ulia/Desktop/VKauth/Carthage/Checkouts/vk-ios-sdk/VK-ios-sdk.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 1:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

If someone already faced this issue, please, help to solve it. Really appreciate your help!

**Comment by mislav** [comment]
Hi, it seems like you're having a problem with a project called Carthage. This issue tracker is for a project called "hub", which is a command-line app written in Go and has nothing to do with Carthage. You might need to look for another place to ask your question; thank you!
