### ISSUE TITLE
Add "hub init <org>/<template repo>" or equivalent to initialize a template repo

### ISSUE THREAD

**Issue by bnb** [github/hub#2171]
Now that [template repos](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) are a thing, it would be absolutely stellar if we could initialize local repositories with GitHub template repositories.

The CLI could look something like this:

```bash
hub init bnb/tempplate
hub init github/starter
hub init nodejs/module-base
```

Alternatively, the `clone` command could just do this by default if you're cloning a template repo.

Thank you for the awesome CLI – it makes my work with git much smoother ❤️

**Comment by mislav** [comment]
https://github.com/github/hub/issues/2163#issuecomment-501324918
