### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sam-hart-swanson** [github/hub#2176]
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x13609c0, 0x168cb20)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/github/hub/github.(*Project).SameAs(0xc00006c2c0, 0x0, 0xc)
	github/project.go:26 +0x55
github.com/github/hub/commands.pullRequest(0x1692a60, 0xc000138300)
	commands/pull_request.go:170 +0x3dbb
github.com/github/hub/commands.(*Command).Call(0x1692a60, 0xc000138300, 0xc0000ba570, 0x1)
	commands/commands.go:45 +0x7f
github.com/github/hub/commands.callRunnableCommand(0x1692a60, 0xc000138300, 0x7ffeefbff3dc, 0xc)
	commands/runner.go:78 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc0000ae048, 0xc0000b4000, 0x7, 0x7, 0xc0000ddf88, 0xc000086058)
	commands/runner.go:61 +0x3ee
main.main()
	main.go:17 +0x71

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.17.2 (Apple Git-113)
hub version 2.12.0
```

**Comment by mislav** [comment]
Thank you for reporting! I would like to know a bit more about your branch & remote configuration that led to this error so I can debug more effectively. Can you tell me:

1. The output of `git rev-parse --symbolic-full-name @{upstream}` while on the branch where you tried `hub pull-request` from. Does it follow the format `refs/remotes/REMOTE/BRANCH`?

2. `git remote get-url --all REMOTE`, where "REMOTE" is the same one that the branch from step (1) was connected to;

3. Any other git setup that you can provide.

If any of this info is sensitive, feel free to anonymize it (replace branch/remote names with placeholders). Thank you!

**Comment by sam-hart-swanson** [comment]
> Thank you for reporting! I would like to know a bit more about your branch & remote configuration that led to this error so I can debug more effectively. Can you tell me:
> 
>     1. The output of `git rev-parse --symbolic-full-name @{upstream}` while on the branch where you tried `hub pull-request` from. Does it follow the format `refs/remotes/REMOTE/BRANCH`?
> 
>     2. `git remote get-url --all REMOTE`, where "REMOTE" is the same one that the branch from step (1) was connected to;
> 
>     3. Any other git setup that you can provide.
> 
> 
> If any of this info is sensitive, feel free to anonymize it (replace branch/remote names with placeholders). Thank you!

Thanks for the response. I discovered the source of my problem was the fact that my remote origin was linked to a local repo server and not github! Entirely my fault, but I'm sure you'd like to look into the crash.

1) refs/remotes/origin/some-branch

2) ssh://git@private.server.com/path/to/repo.git

After setting the upstream of my branch to github correctly, I was successfully able to open a PR via Hub.

**Comment by mislav** [comment]
Thank you for the extra info. I still can't really tell where the crash is coming from. Can you also share with us:

1. `git config --get-regexp "branch.$(git rev-parse --abbrev-ref HEAD).*"`
2. `git config push.default`
3. At the time of crash, what was the state of `upstream`, `origin`, and `github` remotes, if there were more than just one?

Feel free to keep anonimizing info, thank you

**Comment by mislav** [comment]
BTW are you passing `-h` or `--head` to the `hub pull-request` command by any chance?

**Comment by sam-hart-swanson** [comment]
1. ```﻿$ git config --get-regexp "branch.$(git rev-parse --abbrev-ref HEAD).*"
branch.feat/123-some-branch.remote github
branch.feat/123-some-branch.merge refs/heads/feat/123-some-branch```

2. This returns no result

3. `github` -> git@github.com:github.com:***/repo.git
`origin` -> ssh://git@private.server.com/path/to/repo.git

The crash happens when my upstream is set to either origin or github
Here is the output of `git branch -vv` with my remote set to `github`:
```* feat/123-some-branch     c689423 [github/feat/123-some-branch] A Commit Message```

Here is the `hub` command that was being run:
`hub pull-request -b <non-master base branch> -c -o --no-edit` - however, the crash seems to occur with every combination of flags I've tried.

Also, I don't know if it's important, I apologize if it is, but in my first response, I listed `refs/remotes/origin/some-branch` as the output of `git rev-parse --symbolic-full-name @{upstream}`, but a closer representation of that output is `refs/remotes/origin/feat/123-some-branch`.

**Comment by mislav** [comment]
@sam-hart-swanson Thank you so much for the detailed info. Is the double `github.com` in `github -> git@github.com:github.com:***/repo.git` a typo that happened when anonymizing?

**Comment by mislav** [comment]
Also, does a `.git/refs/remotes/origin/feat/123-some-branch` file exist? Note that I'm interested in that file in the `origin` remote, not the `github` remote.

Thank you! I think I'm close to reproducing this

**Comment by sam-hart-swanson** [comment]
@mislav Sorry, yes, that was a typo. The remote looks like `git@github.com:****/repo.git`. I've edited my original comment to reflect that.

Also, yes, the file `.git/refs/remotes/origin/feat/123-some-branch` does exist, as I had pushed the branch to both remotes.
