### ISSUE TITLE
[Feature Request] display/select column(s)

### ISSUE THREAD

**Issue by KerryPoe-asti** [github/hub#2177]
When viewing an issue, from the panel to the right, if exists, display the column where the issue resides. Also, give the ability to specify/change the column.
1. From the projects board, when a card is selected, it would be nice to have the column chooser appear on the side pop-out window, but not crucial. I currently have eight columns in two projects and it is a pain to drag and drop an issue from one column to another when they are not being displayed on one screen.
1. From the issue (Full Details), in the **Set Column** pop-up window, the list should be populated with the current columns in the project. See attached mock-up.
1. From the **Issues** screen,  like the Milestone, have the specified _ColumnName_ appear in the second row for each issue.
1. From the **Issues** screen, it would be nice to sort/filter by column, but not crucial.

![Image1](https://user-images.githubusercontent.com/46503820/60012259-7c146080-9649-11e9-8f94-2d721f707906.png)

![Image2](https://user-images.githubusercontent.com/46503820/60013522-ab789c80-964c-11e9-810b-fd8e290dc0b6.png)

**Comment by kandice1978** [comment]
In got this

**Comment by mislav** [comment]
Hi, thank you for the elaborate feature request. I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
