### ISSUE TITLE
pull-request --no-edit uses the wrong commit message

### ISSUE THREAD

**Issue by worc** [github/hub#2179]
i'm not sure how to reproduce this bug, but sometimes pull-request uses the wrong commit message. in one case i had two commits on a topic branch and instead of using the head commit, hub used the first commit. in other cases i think i'm switching branches and pull-request is using the last message from the previous branch and not the latest message from the current branch.

word-of-mouth seems to be that this is a known issue? but i haven't seen anything in the issues backlog here.

any known workarounds?

**Comment by mislav** [comment]
> in one case i had two commits on a topic branch and instead of using the head commit, hub used the first commit.

The documentation states:

```
	--no-edit
		Use the message from the first commit on the branch as pull request title
		and description without opening a text editor.
```

> in other cases i think i'm switching branches and pull-request is using the last message from the previous branch

Did the previous attempt of `hub pull-request` fail? In that case, hub preserves the pull request message and tries to re-use it on the next `hub pull-request` invocation. It is not aware that you have switched branches in the meantime.

**Comment by worc** [comment]
generally, shouldn't the "first" commit just be the head? and is that the local head or the remote?

>Did the previous attempt of hub pull-request fail? In that case, hub preserves the pull request message and tries to re-use it on the next hub pull-request invocation. It is not aware that you have switched branches in the meantime.

that sounds right-ish, i messed up the syntax on a message once and then ran into the wrong message in the pull request. so far though i haven't found the right way to break a message to get the wrong commit message. 

also, there seems to be a related bug where a pull-request goes through even if you abandon the editor which is different than git itself which will bail if you don't write out changes.

**Comment by mislav** [comment]
> generally, shouldn't the "first" commit just be the head?

I'm sorry, the docs are not clear about this. The "first" commit is the first commit on your head branch, which is also usually chronologically the _oldest_ commit (not the newest one).

> so far though i haven't found the right way to break a message to get the wrong commit message.

I'm interested in what wasn't clear about that?

> there seems to be a related bug where a pull-request goes through even if you abandon the editor

How do you abandon the text editor? Exit without saving any changes? Maybe this was already reported as https://github.com/github/hub/issues/1428, pending fix

**Comment by worc** [comment]
yeah that's the one. 

anyways, since i can't find the way that i broke no-edit i'm going to close this

**Comment by evert** [comment]
> Did the previous attempt of hub pull-request fail? In that case, hub preserves the pull request message and tries to re-use it on the next hub pull-request invocation. It is not aware that you have switched branches in the meantime.

How can I make it forget?  I keep getting an older commit message.
