### ISSUE TITLE
Attention Required

### ISSUE THREAD

**Issue by harissiddiqui** [github/hub#2180]
@azhard4int
Getting error while adding to Assignment as a collaborator. The given link does not seem to work properly. See attached image.

https://classroom.github.com/a/0TyY107l

![Attention    @@@Required](https://user-images.githubusercontent.com/26088763/60387610-3c250180-9abf-11e9-98af-8a2a1bf75155.PNG)

**Comment by azhard4int** [comment]
@harissiddiqui Can you please try checking it now.

**Comment by mislav** [comment]
Hi, this is an issue tracker for a command-line tool called `hub`, and your issue seems to be with GitHub Classroom. I'm going to close this one and ask you to go to https://github.com/education/classroom/issues instead. Thank you!
