### ISSUE TITLE
Does `pr list` show the number of comments correctly?

### ISSUE THREAD

**Issue by eedrah** [github/hub#2182]
Hi, when I run the following command on a repository with PRs that have comments, I don't get anything:

`hub pr list --format '%NC'`
gives `0` or a multiple of `0`, depending on how many pull requests the repo has.

I'm running `hub version 2.12.1`

**Comment by mislav** [comment]
Oops, good catch! We've adopted `%NC` from `hub issue`, but it seems like the [API endpoint that returns pull requests](https://developer.github.com/v3/pulls/#list-pull-requests) doesn't include the `comments` number in the response.

We will likely remove `%NC` from `hub pr list`. In the meantime, you can use `hub issue --include-pulls --format '%NC%n'`, but that will include issues as well.
