### ISSUE TITLE
Open a pull request when not on a branch locally

### ISSUE THREAD

**Issue by larsks** [github/hub#2183]
Currently, if the local working directory is in a detached state, attempting to open a pull request using `hub` fails with:

```
Aborted: not currently on any branch.
```

It seems it ought to be possible to open a pull request in this situation by explicitly setting both `--base` and `--head`, in which case `hub` should have all the information it needs.

The use case is a situation [like this](https://wchargin.github.io/posts/managing-dependent-pull-requests/) in which I am trying to work around GitHub's abysmal support for dependent pull requests. I would like to be able to automate the process of opening pull requests  when iterating through a stack of changes with `git rebase -i`.

**Comment by mislav** [comment]
@larsks Is this even with hub 2.12? https://github.com/github/hub/releases/tag/v2.12.0

**Comment by larsks** [comment]
Looks like I'm actually running 2.11.1 locally.  Let me update and try again.

**Comment by mislav** [comment]
Please reopen if it doesn't.

**Comment by larsks** [comment]
Looks like 2.12 explicitly supports this behavior :).  Thanks!
