### ISSUE TITLE
On github Tabs, if click multiple time it will stuck on loading

### ISSUE THREAD

**Issue by ashifa454** [github/hub#2187]
![image](https://user-images.githubusercontent.com/13622867/60864023-052db900-a240-11e9-9efd-cc2365a1d415.png)

Steps to reproduce it.
- open github.com
- switch between tabs code and issues or any of the one, and click multiple time.
- loading bar on the tab will be stuck while all clicks are resolved.

Possible solution,
Prevent Multiple Clicks
or 
Serve on Latest click.

**Comment by ashifa454** [comment]
sorry for issuing here, I didn't any official place to post this issue.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
