### ISSUE TITLE
Event for merging a pull request located in another repository

### ISSUE THREAD

**Issue by MartykQ** [github/hub#2188]
Is there a way to get a pull request located in another repository via api?

I would like to have pull requests, which are located in another repository, to trigger an issue event: merged in my working repository api/v3/repos/myRepo/issue/:issueID/events

**Comment by mislav** [comment]
Sorry, I'm not entirely sure what your use-case is about, but it doesn't look like it's about changing `hub` functionality. This project and issue tracker is about the command-line tool. Any changes to GitHub notifications (like triggering extra “issue: merged” events) or to the GitHub API will have to be taken with GitHub Support: https://github.com/contact. If you write them, please explain to them your use case and needs in more detail. Thank you!
