### ISSUE TITLE
how to run all hub commands with ssh protocol?

### ISSUE THREAD

**Issue by tddschn** [github/hub#2189]
Quoted from hub(1) manpage:
```
HUB_PROTOCOL
           Use one of "https|ssh|git" as preferred protocol for git
           clone/push.
```
It seems that `ssh` can only be used for clone or push commands.

So is it possible to use `ssh` to identify the user and run other command like `hub create`?

**Comment by mislav** [comment]
Short answer: no. The GitHub API is only accessible over HTTPS.

Long answer: https://github.com/github/hub/issues/1644#issuecomment-359002547

**Comment by tddschn** [comment]
Thank you!
