### ISSUE TITLE
Show the project boards

### ISSUE THREAD

**Issue by XVilka** [github/hub#2194]
Similar to the `hub issue list` and `hub pr list`, but for a selected project. Can be even similarly split into columns, like for the standard project templates.

Also relevant [`hub milestone`](https://github.com/github/hub/issues/2106) suggestion.

**Comment by mislav** [comment]
Sorry, but project board management was already requested but is nowhere near being planned on our roadmap. The web UI of managing project boards is so much superior to doing it in the terminal that we don't have any plans to provide these features through hub.
