### ISSUE TITLE
Test Nive

### ISSUE THREAD

**Issue by NiveeG** [github/hub#2200]
Teste execution file attached 
[TE_ACTiefwerkt_Uitleners_S01_RR 829738.xlsx](https://github.com/github/hub/files/3413475/TE_ACTiefwerkt_Uitleners_S01_RR.829738.xlsx)

**Comment by mislav** [comment]
Not sure what you are asking about, but this is an issue tracker for a Go project for a command-line tool called `hub`. It doesn't seem that your question is related to our project.
