### ISSUE TITLE
select quantity for each items selected in many to many field

### ISSUE THREAD

**Issue by HunarTechie** [github/hub#2202]
i'm working on an restaurant ordering system , when someone order more than one product with different quantities for each product ,the customer be able to select its quantities !
it may order 3 Pizza with 2 sandwich , how to let the customer to define the quantities of each product , and then calculate with its prices    
there are no registration option (all customers are anonymous)
> models.py
> class Restaurant(models.Model):
>     name = models.CharField(max_length=50)
>     price = models.PositiveIntegerField(default=1)
> 
> 
>     def __str__(self):
>         return self.name
> 
> class Topping(models.Model):
>     name = models.CharField(max_length=50)
>     product_names = models.ManyToManyField(Restaurant, blank=True)
>     quantity = models.PositiveIntegerField(default=1)
> @property
>     def total(self):  
>         return self.product_names.aggregate(Sum('price'))['price__sum'] 

total price of orders , for one product for example : one pizza with one sandwich however they order more than one pizza and sandwich

I expected to provide a quantity field for each selected items : pizza : 3 , sandwich:2 , then calculate them (3*pizza price , 2*sandwich price)

i think its the same as subquery in sql , but i dont know to implement it in django 
thanks for answering !

**Comment by jrief** [comment]
You can use the CartModifiers and add all the logic for price calculation there.
You should not fiddle around with SQL yourself and there is no need for a subquery.

**Comment by mislav** [comment]
Not sure what you are asking about, but this is an issue tracker for a Go project for a command-line tool called `hub`. It doesn't seem that your question is related to our project.
