### ISSUE TITLE
Deployment command

### ISSUE THREAD

**Issue by Noah-Huppert** [github/hub#2203]
The [deployment API](https://developer.github.com/v3/repos/deployments) would be great as a Hub command.

Use case:

User sets up continuous integration pipeline which runs:

- Setup GitHub deployment:
  ```
  deployment_id=$(hub deployment create -ref "$CI_REF")
  hub deployment-status create -deployment "$deployment_id" -state in_progress
  ```
- Do deploy, can be any command...
  Update deployment status when deploy completes.
  ```
  deployment_status=success
  if ! deploy_cmd; then
    deployment_status=failure
  fi
  hub deployment-status -deployment "$deployment_id" -state success
  ```

Commands: 

- `deployment`
  - `list [-sha <SHA>] [-ref <REF>] [-task <TASK>] [-environment <ENV>]`
  - `get -deployment <DEPLOY_ID>`
  - `create -ref <REF> [-task <TASK>] [-auto_merge] [-required-contexts <REQ_CTX>] [-payload <PAYLOAD>] [-environment <ENV>] [-description <DESC>]`
- `deployment-status`
  - `list -deployment <DEPLOY_ID>`
  - `get -deployment <DEPLOY_ID> -status <STATUS_ID>`
  - `create -deployment <DEPLOY_ID> -state <STATE> [-target-url <TGT_URL>] [-log_url <LOG_URL>] [-description <DESC>] [-environment <ENV>] [-environment-url <ENV_URL>] [-auto-inactive]`

**Comment by mislav** [comment]
Thank you for the excellent feature request, but covering the Deployments API over a range of hub subcommands is not on our roadmap and I don't see us having the resources to create and maintain it anytime soon.

I find it much better to use `hub api` manually to access the Deployments API:

```sh
deployment_id="$(hub api 'repos/{owner}/{repo}/deployments' -f ref="$CI_REF" | jq -r .id)"
hub api "repos/{owner}/{repo}/deployments/$deployment_id/statuses" -f state=in_progress
```

See https://github.com/mislav/hub-api-utils for more inspiration. Let us know how it goes! ✨
