### ISSUE TITLE
Unconditional break in clone.go:85

### ISSUE THREAD

**Issue by muesli** [github/hub#2209]
While reviewing the codebase a bit I discovered an unconditional `break` in `commands/clone.go` at line 85.

Should this be moved up into the if-condition above or is the entire loop redundant?

**Comment by mislav** [comment]
Good find, but the code is correct! We only want to process the first positional argument and ignore the rest.

The block could alternatively be converted into an `if` instead of a `for..break`, but not much would be gained in terms of readability.
