### ISSUE TITLE
Username / password fails with for private repos with "remote: Invalid username or password." after enabling multi-factor authentication

### ISSUE THREAD

**Issue by saatwick** [github/hub#2212]

**Comment by mislav** [comment]
After enabling 2FA, using your GitHub password as the "password" value when cloning/pushing/pulling with git won't work anymore. This error message is expected. You will need to generate a Personal Access Token for git use: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

> Once you have a token, you can enter it instead of your password when performing Git operations over HTTPS.

But watch out for:

> If you are not prompted for your username and password, your credentials may be cached on your computer. You can update your credentials in the Keychain to replace your old password with the token.

Good luck!
