### ISSUE TITLE
question: how to browse a specific issue if you have it's tag number

### ISSUE THREAD

**Issue by rugwirobaker** [github/hub#2215]
**need**
I want to know if there is a `hub browse --issues` flag to would help me open a specif issue in the current repository ounce I have a tag number `ex:#3453` after running `hub issue`

**proposal**
Perhaps we could add a sub command to `hub issue` that opens up an issue given it's number
something like: `hub issue browse <issue-number>`

**Comment by mislav** [comment]
`hub browse -- issues/3453`
