### ISSUE TITLE
"Authentication Failed" error too generic command line with 2fa

### ISSUE THREAD

**Issue by JimTheMan** [github/hub#2220]
Basically, everything that happened in this issue happened to me:
https://github.com/github/hub/issues/822

It would be nice if the error message from me trying to push was something like, "you need to use ssh keys since you have 2fa enabled!" instead of me having to see a super generic "Authentication failed" error, be sad, google for a while, and try a bunch of random things involving metal drums and clay pots.

**Comment by mislav** [comment]
I'm sorry you had a bad experience setting up `git` (or `hub`) with GitHub.

It was on our roadmap for a while to improve the experience around authenticating: #225. I will close this issue in favor of the long-outstanding issue. Please have patience until we find the time and resources to improve the experience around this.
