### ISSUE TITLE
Isolated SPFx webparts are not loading in Microsoft Teams Desktop App

### ISSUE THREAD

**Issue by ArunRajiv** [github/hub#2224]
Hi Team,

We created an isolated web part ( Just vanilla hello world web part ) and tried to load it in Microsoft teams. It worked pretty much fine in the **Teams** web version but not in the **Teams** desktop version. It just loads blank.

![image](https://user-images.githubusercontent.com/19972139/62943161-76d8c400-bdf7-11e9-95b1-9aa23a7fa5fc.png)

Here is the screenshot of fiddler trace and how web part is loading in teams (both web and desktop version).

**Web Version**
![image](https://user-images.githubusercontent.com/19972139/62943110-5b6db900-bdf7-11e9-9d99-6cfaf890a400.png)

**Desktop Version**

![image](https://user-images.githubusercontent.com/19972139/62943210-92dc6580-bdf7-11e9-91fb-9cbfa6a61d3b.png)

**Fiddler Trace:**
**Teams Desktop (vs) Web**
![image](https://user-images.githubusercontent.com/19972139/62943295-c0c1aa00-bdf7-11e9-9793-572a34b744cc.png)

**Comment by viethungdaniel1996** [comment]
We created an isolated web part ( Just vanilla hello world web part ) and tried to load it in Microsoft teams. It worked pretty much fine in the Teams web version but not in the Teams desktop version. It just loads blank
asdasdasdasdasd

**Comment by ArunRajiv** [comment]
reported in wrong repository
