### ISSUE TITLE
general gist support

### ISSUE THREAD

**Issue by jaymzh** [github/hub#2226]
I know one can do janky jq stuff as mentioned in https://github.com/github/hub/issues/2116 but it'd be great to be able to create and grab gists nicely and easily with `hub` directly:

```
cat myfile | hub gist --public
hub gist [gist_url] > myfile
``

**Comment by mislav** [comment]
You could also use https://github.com/mislav/hub-api-utils/blob/master/bin/hub-gist.

From my comment on https://github.com/github/hub/issues/2116#issuecomment-485529449:

> Creating or editing gists is not anywhere near on our roadmap for hub so I'm going to close this for now.

**Comment by jaymzh** [comment]
@mislav - your example does not work, when you run it you get

```
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}
```

However the JSON looks like what the documentation claims it should look like. :/

**Comment by mislav** [comment]
@jaymzh I just ran my `hub-gist` command linked above and it works. Can you check that your hub token has "gist" among scopes? https://github.com/settings/tokens

**Comment by jaymzh** [comment]
@mislav - ah I didn't know that was a thing. I added gist, and now I get:

```
$ /tmp/hub-gist /etc/hosts
{"message":"Validation Failed","errors":[{"resource":"Gist","code":"invalid","field":"files"},{"resource":"Gist","code":"custom","field":"Whoops,","message":"Whoops, files can't contain malformed path components."}],"documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}
```

**Comment by jaymzh** [comment]
Not sure why `hub-gist` doesn't work, but I've sent a PR to add nice gist support to hub directly that now works with both creation and retrieval of gists: https://github.com/github/hub/pull/2269
