### ISSUE TITLE
Allow pull-request to specify the remote.

### ISSUE THREAD

**Issue by Daenyth** [github/hub#223]
Currently you can only use pull-request on the "origin" repository, but if your workflow has you pushing to your own fork and issuing a pull request from there, rather than a request from inside the main repository, this is annoying. In order to get it to do what I want I have to delete my origin remote, add a new origin remote with the git url from my upstream remote, use pull-request, then delete & re-add the origin remote with my git url.

Having an option to specify a remote to use would be far better.

**Comment by antialias** [comment]
@mislav after some experimentation, it seems to me that "owner" refers to the github username, not the name given to the remote in the repo from which the hub command is being run.
