### ISSUE TITLE
hub should respect git aliases

### ISSUE THREAD

**Issue by kojiromike** [github/hub#2231]
Hi, I have an alias:

```
$ command git help pr
'pr' is aliased to 'pull-request'
```

This worked great until the recent update to `hub` introduced the new `pr` command, which is different from `pull-request`. That is addressed in #1536, however, I would like my alias to continue working as it had in the past. Unfortunately, `hub` seems to shadow all git commands, even if they're configured aliases. I think that local user configuration should take precedence over `hub`.

Thank you for your consideration of this issue.

**Comment by mislav** [comment]
Your `pr` alias won't be possible anymore, sorry: https://github.com/github/hub/issues/1536#issuecomment-393251381. This is core git behavior.
