### ISSUE TITLE
Sync command inconsistent branch quoting

### ISSUE THREAD

**Issue by JPry** [github/hub#2233]
I've noticed that the `sync` command has inconsistent quotes when displaying warnings about certain branches. For example, I got this output:

```
git sync
warning: `issue_173' seems to contain unpushed commits
```

Note that the branch is preceded by a backtick and followed by a single quote. I believe that the types of quotes should be the same before and after the branch name.

Here's one of the relevant portions of the code:

https://github.com/github/hub/blob/3edbd86fab2028aa997eb51a812d14afe1899f05/commands/sync.go#L116-L118

For consistency with Git itself, I think single quotes should be used. Here's the output from `git checkout`, which uses single quotes around the branch name:

```
Switched to branch 'issue_173'
Your branch is ahead of 'origin/issue_173' by 3 commits.
  (use "git push" to publish your local commits)
```

**Comment by mislav** [comment]
Good catch! I agree that we should strive to match git's formatting.
