### ISSUE TITLE
pull-request - no title in editor when using PR templates, PR title displays content

### ISSUE THREAD

**Issue by zalew** [github/hub#2242]
When I have PR templates set up, in the `hub pull-request` editor, the commit title doesn't appear, blank line followed by template contents. If I don't write the title, the whole template lands as a one line string in the title.
```
$ hub --version                                                                   
git version 2.20.1
hub version 2.7.0
```

**Comment by zalew** [comment]
I'd expect it takes the actual existing title of the change, which is the commit message, just like it behaves here using the web UI, instead of overwriting it. How weird is that.

I will check a newer version.

**Comment by mislav** [comment]
@zalew If hub behaves significantly differently than the GitHub web UI, then we usually treat it as a bug. Let's investigate this further.

You mentioned “takes the actual existing title of the change, which is the commit message”. You haven't mentioned this expectation in your original message; you have only mentioned the template. Does your branch for the pull request contain only one commit, and you have expected this commit subject & message be reused for the pull request title & body? Did this not happen? How did you expect the PR template to be applied in relation to this? More information would be useful, thank you.

**Comment by mislav** [comment]
Closing due to lack of info in the meantime. Hope your issue was resolved!
