### ISSUE TITLE
WSL - hub [command] throws error open /home/[username]/.config/hub: permission denied

### ISSUE THREAD

**Issue by jordanstudioroot** [github/hub#2246]
**Error:**
open /home/[username]/.config/hub: permission denied

git version 2.17.1
hub version 2.12.3
Windows Subsystem For Linux - Ubuntu 18.04.2 LTS

**Troubleshooting**
Looks like .config/hub is never created. Tried creating the file manually and editing its permissions but the same error is thrown when executing any hub [command].

Initially installed hub with linuxbrew. Tried uninstalling and reinstalling the compiled executable to bin and the error persists.

![error](https://user-images.githubusercontent.com/44789812/63873246-e072d980-c984-11e9-8c28-5a8d9155b972.JPG)

**Comment by mislav** [comment]
Hi thank you for reporting. This isn't the first WSL bug we had, but is certainly odd. Can you share with us permissions for `~/.config` and `~/.config/hub` if they exist at the time that this error is thrown?

I'm assuming that the error comes from here but I'm not sure: https://github.com/github/hub/blob/2fa955aed2a1132bfadaf871e86265a21d88408e/github/config.go#L369

**Comment by mislav** [comment]
@jordanstudioroot Is this still an issue? Otherwise, I would close it since we haven't got similar reports and I would assume that this is some problem with WSL rather than a problem in our project.

**Comment by jordanstudioroot** [comment]
Sorry for the delay on the reply. I didn't know id get notified via email. I haven't tried this since then so I sort of gave up on using this method to do what I was trying to do. It is fine if you want to close the ticket or I am happy to try some more troubleshooting if you have any suggestions.

-Jordan

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mislav** [comment]
Thanks for the update. I'm going to close this until this proves to be a problem for someone again. This is mostly likely a bug with WSL.

**Comment by smalhot9464** [comment]
Hi I am facing same issue.

Command : hub pull-request -b master -h mybranch

Output : 
open /Users/<myusername>/.config/hub: permission denied
