### ISSUE TITLE
hub release download - filtering and list

### ISSUE THREAD

**Issue by vibou** [github/hub#2251]
It would be great to add some functionalities to the `hub release download` command:
`--list-only` list the different assets attached to the release
`--include` a glob pattern to filter in assets to download
`--exclude` a glob pattern to filter out assets to download

By default, all assets are downloaded. When there is one asset per architecture, it is useless to download them all.

**Comment by shouze** [comment]
related to https://github.com/github/hub/pull/1103

**Comment by vibou** [comment]
I just found out that the command "show" also has an option --show-downloads. So you can use it like so: 

`hub release show --show-downloads (hub release -L 1) | grep -e 'YOUR_REGEX' | xargs wget -q  `

This command is a workaround. It seems to me that having it on download would be more intuitive.

**Comment by mislav** [comment]
You can also programatically list downloads like so:

```
$ hub release show v2.12.3 --format '%as%n'
https://github.com/github/hub/releases/download/v2.12.3/hub-darwin-amd64-2.12.3.tgz     hub 2.12.3 for macOS
https://github.com/github/hub/releases/download/v2.12.3/hub-freebsd-386-2.12.3.tgz      hub 2.12.3 for FreeBSD 32-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-freebsd-amd64-2.12.3.tgz    hub 2.12.3 for FreeBSD 64-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-linux-386-2.12.3.tgz        hub 2.12.3 for Linux 32-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz      hub 2.12.3 for Linux 64-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-linux-arm-2.12.3.tgz        hub 2.12.3 for Linux ARM 32-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-linux-arm64-2.12.3.tgz      hub 2.12.3 for Linux ARM 64-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-windows-386-2.12.3.zip      hub 2.12.3 for Windows 32-bit
https://github.com/github/hub/releases/download/v2.12.3/hub-windows-amd64-2.12.3.zip    hub 2.12.3 for Windows 64-bit
```

Then you can filter that list on your end and select only the downloads that you want. I find this method to be preferred for scripting and I'm not yet decided whether it would be worthwhile to maintain extra flags such as `--include` or `--exclude`. I will keep this open until a decision is made.

Thank you for the suggestion!

**Comment by vibou** [comment]
It's even more needed when you have a private repository. It gets really tricky to download only one asset. You are obliged to use the GitHub API and you can't use hub at all since you don't have the assets id listed.

see https://gist.github.com/maxim/6e15aa45ba010ab030c4

**Comment by tomlazar** [comment]
@mislav mind if I take a look at implementing those three new flags?

**Comment by mislav** [comment]
@tomlazar Certainly!

Since `--list-only` is already available by other means, I would be open to accepting an implementation of `--include` (I don't see much value in `--exclude`). @vibou Has a good point about downloading private assets being a pain when we only have their URL— hub should make all that be easier.
