### ISSUE TITLE
Issues to authentication using ssh key or token

### ISSUE THREAD

**Issue by moliv0** [github/hub#2262]
Hi Guys. 
I use Enterprise GitHub, the regular user authentication does not work.
I have git config --global --add hub.host github.XXXX.com
I have also set git config --global hub.protocol ssh
but the it keep me asking the password to authenticate.
I would like to know if there are any way to force the ssh key or token to connect?

Thanks

**Comment by mislav** [comment]
Hub requires your GitHub username/password on first run to authenticate. This is separate from ssh authentication on git push/pull https://github.com/github/hub/issues/1644#issuecomment-359002547

A way to side-step this for your Enterprise instance would be to append this to `~/.config/hub`:

```yml
github.XXXX.com:
- user: YOURUSER
  oauth_token: PERSONALTOKEN
```

where "PERSONALTOKEN" would be the value of your Personal Access Token that you can generate in the web interface by going to `https://github.XXXXX.com/settings/tokens`
