### ISSUE TITLE
ChromeDriver 77, Unable to Invoke the Chrome Browser Selenium 

### ISSUE THREAD

**Issue by maddysk3** [github/hub#2271]
- System Configuration: Windows 10 
- Chrome Driver - Version 77.0.3865.40
- Chrome Browser - Version 77.0.3865.75
Executing test through Eclipse Java

Chrome Browser updated the latest version and thus the tests are not executing -
ERROR -FAILED session not created: This version of ChromeDriver only supports Chrome version 75
Chrome Browser - Version 77.0.3865.75 Chrome Driver - Version 77.0.3865.40

Exception message 
[1568745898.346][WARNING]: Timed out connecting to Chrome, retrying...
Sep 18, 2019 12:14:58 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: invalid argument
 (Session info: chrome=77.0.3865.75)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-MJBTG76S', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 77.0.3865.75, chrome: {chromedriverVersion: 77.0.3865.40 (f484704e052e0..., userDataDir: C:\Users\Maddy\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:51393}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 63a66d3c047a11b734478755dde35c13

Expected: Test should execute succesfully. Win 7 and Mac it is working fine with the same browser and driver combination

**Comment by mislav** [comment]
This is an issue tracker for a project called "hub". We do not use Selenium of Chrome in our tests, sorry!
