### ISSUE TITLE
Use default branch as base when not specified

### ISSUE THREAD

**Issue by grav** [github/hub#2273]
Wouldn't it make sense to pick default branch (as per repo settings) as base, when no base is specified via `-b` option?

This is also what Github picks, if I push to a new branch and create a pull request via the web interface.

**Comment by mislav** [comment]
This is what hub currently tries to do, yes. https://github.com/github/hub/blob/7496b3dab3b0a82338474ccd5549cee79d3478a0/features/pull_request.feature#L605-L617

Does it not work? Could you check whether `git symbolic-ref refs/remotes/origin/HEAD` matches the default branch of your GitHub repo? Thank you

**Comment by mislav** [comment]
Closing because the question has been answered. If hub doesn't work as it was supposed to, then this is a bug, and to help me debug it please include more information about your case. Thank you!

**Comment by grav** [comment]
Oh sorry for not coming back to you. I don't have the repo at hand any more, so cannot check.
