### ISSUE TITLE
cloud asset api in GCP creates duplicate fields

### ISSUE THREAD

**Issue by deepakmalpote** [github/hub#2275]
Hi

I have been trying to export asset metadata to GCS. The idea is to export the asset metadata generated into bigquery and then visualize in Data Studio.

However whenever I use the cloud asset API (either using curl or 'gcloud asset export' command), the generated raw json data file contains two duplicate fields, 'IPProtocol' and 'ipProtocol'.

Due to this when I try to export this data into bigquery (either by bq mk or bq load command) it gives me follwing error.

$ bq mk inventory_dataset.2019_09_20_11_00_00 schema.json 
BigQuery error in mk operation: Field resource.data.allowed.ipProtocol already exists in schema

Is this a bug or I am doing anything wrong?

I am using a bigquery-schema-generator tool for generating schema.(https://pypi.org/project/bigquery-schema-generator/) 

Please help.

**Comment by mislav** [comment]
Hi, this is an issue tracker for a command-line tool called "hub". It has nothing to do with "GCS", bigquery, or metadata. I think you should look for a more appropriate place to ask your question. Good luck!
