### ISSUE TITLE
Requires Authentication Error - but never prompted for credentials

### ISSUE THREAD

**Issue by KyleMit** [github/hub#2276]
Just installed hub using chocolatey on Windows, and I get an error as soon as a I try to execute any commands

When I run the following command 

```bash
HUB_VERBOSE=1 hub issue
```

I get the following output

```bash
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
github.com username: email@gmail.com
github.com password for email@gmail.com (never stored):
> POST  https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
{"note":"hub for KyleMit@SurfaceWhoa","note_url":"https://hub.github.com/","scopes":["repo"]}
< HTTP 401
{"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"}
Requires authentication
```

![example](https://user-images.githubusercontent.com/4307307/65392104-e5863700-dd3e-11e9-9a92-c119706edcf6.png)

According to the docs on [GitHub OAuth authentication](https://hub.github.com/hub.1.html#github-oauth-authentication), II should be prompted for username/password, but after I enter the username, the auth immediately fails and never prompts for a password

I tried to delete `~/.config/hub`, but it doesn't exist.

**How can I prompt for / reset authentication?**

### Environment

_OS Name_: Microsoft Windows 10 Pro
_Version_: 10.0.18980 Build 18980

### Similar Issues

#579 Cannot get past authentication
#965 This API can only be accessed with username and password Basic Auth" on create or pull-request
#1672 This API can only be accessed with username and password Basic Auth" on create or pull-request 
#1067 hub complains "Unauthorized (HTTP 401)" and "Bad credentials
#1486 `hub checkout` asks for username and password

**Comment by jtawil777** [comment]
Same issue here. I too installed using Choco on Windows 10. I can run git pull with no problems. "git pull-request" asks for a username and then immediately says "Error creating pull request: Unauthorized (HTTP 401)" Requires authentication. I even set these two environmental variables. Same error.

GITHUB_USER
The GitHub username of the actor of GitHub API operations.

GITHUB_PASSWORD
The GitHub password used to exchange user credentials for an OAuth token that gets stored in hub configuration. If not set, it may be interactively prompted for on first run.

**Comment by mislav** [comment]
Thank you for reporting!

1. What is your `hub version`?
2. Can you try the precompiled [Windows build from here](https://github.com/github/hub/releases/tag/v2.12.6) instead of the Choco version?

@jtawil777 If you've correctly set GITHUB_USER and GITHUB_PASSWORD in your environment, then hub wouldn't ask you for neither username nor password (it would instead get the values from environment variables). How did you set these variables and what are you using as your shell?

@KyleMit Does setting `GITHUB_PASSWORD=<password>` in your environment work around getting prompted for password on your end?

**Comment by mislav** [comment]
Pushing another release that may fix the issue https://github.com/github/hub/releases/tag/v2.12.7

Sorry for the trouble!

**Comment by KyleMit** [comment]
Yep, v2.12.7 fixed the issue!! 🎉 

I updated the original comment with the `hub version` as well which was on v2.12.6

Thanks so much!

**Comment by massich** [comment]
Just for completeness.
faced the same issue installing `hub` from conda-forge

```sh
$ hub --version
git version 2.7.4
hub version 2.12.3
```
