### ISSUE TITLE
can no longer open a PR

### ISSUE THREAD

**Issue by ggascoigne** [github/hub#2277]
This worked until pretty recently, but suddenly stopped.

We have a github enterprise server, and I suspect that something changed in it's configuration but I can't work out what, any help so that I can work through this would be appreciated.

`hub pr list` works just fine.

```bash
$ hub pull-request -b master -o
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.... exists?
```

the path listed exists, and `hub browse` will happily open the right project page.

```bash
$ hub --version
git version 2.22.0
hub version 2.12.3
```

**Comment by mislav** [comment]
@ggascoigne This sounds like something changed on the server. You can use `HUB_VERBOSE=1 hub pull-request ...` to run the command in verbose mode and see more information about server responses. It seems like your Enterprise server thinks that this repository no longer exists? Perhaps it has been removed, renamed? Anyway, let us know what you find. You can copy-paste information to this thread, but be sure to first scrub away any sensitive information pertaining to your business. Thank you!

**Comment by ggascoigne** [comment]
I suspect that the relevant bit is:

```txt
$ code --wait --new-window /Users/ggp/dev/tw-git/saas-ui/.git/PULLREQ_EDITMSG
> POST https://github...com/api/v3/repos/tw-devops/ui/pulls
> Authorization: token [REDACTED]
> Accept: application/vnd.github.shadow-cat-preview+json;charset=utf-8
{"base":"master","body":"Enable table filtering in production.","head":"tw-devops:connect-perms","maintainer_can_modify":true,"title":"remove the tableFeatures flag"}
< HTTP 404
{"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.17/v3/pulls/#create-a-pull-request"}
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.scm.tripwire.com/tw-devops/ui exists?
```

**Comment by mislav** [comment]
That's helpful, thanks. But I fear that I don't have access to your Enterprise instance to be able to check if `tw-devops/ui` repository exists there and that you have access to it. If it does exist and your user has access, can you check your token that's stored in either `GITHUB_TOKEN` environment variable or the `~/.config/hub` file? Perhaps you could also try generating a new one in `github.COMPANY.com/settings/tokens`. Let us know what you find!

**Comment by ggascoigne** [comment]
That was it, created a new token and it’s all working again.

Maybe update the error message to suggest that as an alternative cause of
the problem?

Thank you for your help.

**Comment by mislav** [comment]
An improved handling of outdated or otherwise invalid tokens is already planned. Thank you for your feedback!
