### ISSUE TITLE
Github Package Registry Integration

### ISSUE THREAD

**Issue by IncPlusPlus** [github/hub#2279]
Hi there. I just found hub and I think it's a really cool tool that I plan on using within GitHub Actions. Part of what I want to be able to do is publish to the GitHub Package Registry. Would interaction with the registry be possible through an additional command? I poked around through the issues and PRs here and I didn't seem to find any previous mention of this.

**Comment by mislav** [comment]
No, this wasn't planned. What kind of GPR interaction would you envision hub to have? Is it something that you could feasibly implement manually using `hub api`?

**Comment by IncPlusPlus** [comment]
I'd have to poke around for a while. Maybe it could be done with `hub api`.
That's a good idea. I'll give it a shot if I get the chance.

**Comment by mislav** [comment]
I would be inclined to close this unless you have some specific feature to suggest for hub. Interaction with GitHub API is available through `hub api` (this can be useful within Actions) and publishing to Package Registry is already available using supported package tools such as `npm publish` or `gem push`. https://help.github.com/en/articles/about-github-package-registry#supported-clients-and-formats

**Comment by IncPlusPlus** [comment]
No worries. Feel free to close this.
