### ISSUE TITLE
hub release -F <FILE>

### ISSUE THREAD

**Issue by OmgImAlexis** [github/hub#2281]
Is there an example file to show the format this accepts?

I've tried a few different ways and I keep getting the whole file as the title.

**Comment by mislav** [comment]
When reading the release title and description from a file like this:

```
hub release create -F myfile.txt
```

The formatting rules follow the same logic [as for `--message`](https://hub.github.com/hub-release.1.html):
> The text up to the first blank line in \<MESSAGE> is treated as the release title, and the rest is used as release description in Markdown format.

Therefore, all you need is **one blank line between the title and the body**. Example:

```
This is my release title
This is also part of the title.

Release body starts here.
It can span several lines.

As well as several paragraphs.
This is also release body.
```

**Comment by sinisterstuf** [comment]
The formatting rules are documented under --message and the manual page entry for -F refers to the rules for --message. Is there another piece of documentation that should updated/improved regarding this or is this issue closeable?

**Comment by mislav** [comment]
@sinisterstuf Thanks for checking. I think we can close this since https://github.com/github/hub/commit/4813e859ae10d7561043f47a517fd7c5aeb821b3
