### ISSUE TITLE
https_proxy isn't honored

### ISSUE THREAD

**Issue by jsoref** [github/hub#2285]
https://askubuntu.com/questions/228530/updating-http-proxy-environment-variable

There used to be support for `https_proxy`(see #180).
It looks like the rewrite from Ruby to Go lost it.

There's some complicated code that looks for `http_proxy` and `HTTP_PROXY` (Windows compatibility?)

But this is totally wrong.

The way `http_proxy` and `https_proxy` are supposed to work is that one sets an `https_proxy` variable to define the url that UAs should use to connect to `https` urls, and one sets the `http_proxy` variable to define the url that UAs should use to connect to `http` urls. The github api is only available via https, which means that the variable that should matter is `https_proxy`.

**Comment by jsoref** [comment]
Beyond this, the code has this odd comment:
https://github.com/github/hub/blob/d0e9e009ffc537c656a6cb8ec5cc132be5e4b8df/github/http.go#L200

It may have been true at some distant time in the past, but the golang codebase appears to have been rewritten considerably since then, which argues in favor of reconsidering this apparent fork (I spent time last week trying to trace the history and gave up).

**Comment by mislav** [comment]
Well spotted. How does this look for you? https://github.com/github/hub/pull/2286

We would basically revert to the Go approach, but in a way that the implementation is consistent no matter the Go version used.

**Comment by jsoref** [comment]
Seems like the right direction, but you're going to need some release notes, because your changes are going to bite people relying on your non-standard settings.

**Comment by mislav** [comment]
That's a good point, and the primary reason why I didn't include this in the yesterday's patch release. I will bump up the minor release number for this.
