### ISSUE TITLE
Cannot execute GraphQL queries on GitHub Enterprise Server with hub api

### ISSUE THREAD

**Issue by swinton** [github/hub#2287]
Thanks for this great tool! ✨ 

I'm able to execute REST API requests using `hub api` against GitHub Enterprise Server:

```
GITHUB_HOST=git.acme.org hub api user
```

Unfortunately, GraphQL requests don't seem to work:

```
GITHUB_HOST=git.acme.org hub api graphql -F query=@query.graphql
```

I receive the error:

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/enterprise/2.18/v3"
}
```

I'm using `hub` version 2.12.7.

**Comment by mislav** [comment]
> Unfortunately, GraphQL requests don't seem to work:

Thanks for reporting. This is a bug. Hub is trying to POST to `git.acme.org/api/v3/graphql`, whereas it should be posting to `git.acme.org/api/graphql`.

I will fix this soon. In the meantime, you can use this as workaround:

```
GITHUB_HOST=git.acme.org hub api /api/graphql ...
```

This style of invocation will work on GHE; unfortunately it's not portable back to dotcom.
