### ISSUE TITLE
Enable github pages `/docs` folder in master branch

### ISSUE THREAD

**Issue by anishmittal2020** [github/hub#2302]
Is it possible to enable github pages, if  `/docs` folder in master branch is present, from commandline?

**Comment by mislav** [comment]
Yes. To [enable a pages site](https://developer.github.com/v3/repos/pages/#enable-a-pages-site) from `/docs` in master:

```sh
echo '{"source":{"path":"/docs","branch":"master"}}' | \
  hub api -H 'accept: application/vnd.github.switcheroo-preview+json' \
    repos/{owner}/{repo}/pages
```

Do disable them:

```sh
hub api -H 'accept: application/vnd.github.switcheroo-preview+json' -XDELETE \
  repos/{owner}/{repo}/pages
```

The placeholders `{owner}` and `{repo}` will be substituted with information about the current repo, if you're in its folder. Or, you can supply your own values explicitly.
