### ISSUE TITLE
hub ignores hub.host

### ISSUE THREAD

**Issue by wwalker** [github/hub#2303]
hub is ignoring my hub.host in ~/.gitconfig:

```
wwalker@polonium:~/git $ hub version
git version 2.21.0
hub version 2.12.4
wwalker@polonium:~/git $ grep -A3 '\[hub]' ~/.gitconfig
[hub]
        protocol = ssh
        host = github.redacted.com

wwalker@polonium:~/git $ hub clone ops
github.com username: 
wwalker@polonium:~/git $ cat ~/.config/hub
cat: /home/wwalker/.config/hub: No such file or directory
```
If I manually create the .config/hub file, it honors that one.
```
wwalker@polonium:~/git $ vim ~/.config/hub
wwalker@polonium:~/git $ hub clone ops
Cloning into 'ops'...
```

**Comment by mislav** [comment]
Thanks for detailing your use use! 

It's a bit of a mess right now, but `git config hub.host` just whitelists the _recognized_ GitHub hosts, but doesn't default to any of them specifically. The `hub clone ops` operation will still default to cloning from `https://github.com/USER/ops`.

You can override the default host with the GITHUB_HOST environment variable:

```
GITHUB_HOST=github.redacted.com hub clone ops
```

See `hub help hub` for more infor.
