### ISSUE TITLE
Why does it ask my Github credentials in order to clone a repo?

### ISSUE THREAD

**Issue by lflucasferreira** [github/hub#2304]
Well, I don't know why this tool asks for my credentials when I try cloning a repository. Could you please, tell the reason. Thank you in advance.

**Comment by mislav** [comment]
Good question! See https://github.com/github/hub/issues/1839 and https://github.com/github/hub/issues/1644#issuecomment-359002547.

**TL;DR;** hub asks for API credentials on first run, stores the token afterwards so you never have to do it again. It does so for `clone` command too, even though it's not stricly necessary for cloning a public repo. We can improve that in the future. But for now, you shouldn't be concerned that something very wrong is happening.
