### ISSUE TITLE
hub does not expand `~` while reading gitconfig's editor

### ISSUE THREAD

**Issue by nhed** [github/hub#2307]
While `git` seems to have no problem with this editor wrapper script, specified as relative path to my home dir `~` (when I made the commit just now), `hub` does not seem to expand `~`.

```
HUB_VERBOSE=1 hub pull-request
...
$ git var GIT_EDITOR
$ git config core.commentchar
$ ~/bin/gitedit /home/nhed/Projects/xxxxxx/.git/PULLREQ_EDITMSG
error using text editor for pull request message
```

For test I replaced with absolute path (which won't work for me as i'm sharing a gitconfig across machines with different home dir path)

priority: low

**Comment by mislav** [comment]
Thank you for reporting. This is similar to https://github.com/github/hub/issues/1482 and will be fixed by https://github.com/github/hub/pull/2214.

In the meantime you can try using `$HOME` instead of `~` to have a portable solution.
