### ISSUE TITLE
"error using text editor for pull request message"

### ISSUE THREAD

**Issue by ZhangMingShuo** [github/hub#2309]
Hi! When I pull request with "**hub pull-request**", this error "**error using text editor for pull request message**" happens!  So, Can I _pull request_ on command line with "**hub**"?

**Comment by ZhangMingShuo** [comment]
> Hi! When I pull request with "**hub pull-request**", this error "**error using text editor for pull request message**" happens! So, Can I _pull request_ on command line with "**hub**"?

My machine environment:
git version 2.21.0.windows.1
hub version 2.12.8

**Comment by mislav** [comment]
Hi, you need to configure your git settings to specify a text editor that will open when you run `hub pull-request`.

You can see your current editor with `git config core.editor`

If it lists an editor you're unfamiliar with, see here to find out how to change that setting to an editor you prefer: https://help.github.com/en/articles/associating-text-editors-with-git
