### ISSUE TITLE
zsh completion is semi-broken

### ISSUE THREAD

**Issue by teoljungberg** [github/hub#231]
I have this in my _.zshrc_

``` zsh
eval "$(hub alias -s)"
```
- `hub` is installed via homebrew
- zsh completion is installed to _/usr/local/share/zsh/site-functions_

the hub commands like pull-request, browse etc doesn't get completed

Ideas @mislav ?

**Comment by BBonifield** [comment]
I'm an oh-my-zsh user, but the above mentioned fix to add the hub oh-my-zsh plugin didn't work for me.  I was able to resolve this by adding `fpath=('/usr/local/share/zsh/site-functions' $fpath)` to my .zshrc above `ZSH=...`.
