### ISSUE TITLE
hub pull-request should trim or string replace `Co-authored-by` and `Signed-off-by` footer fields from PR description

### ISSUE THREAD

**Issue by dnwe** [github/hub#2311]
Currently, if you have created one or more commits with [multiple authors](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) and then use `hub pull-request ...` to submit a PR for the changes, the Co-author-by: fields are included in the description, but do not render cleanly in Markdown due to the e-mail addresses being automatically replaced with mailto hrefs. 

e.g., Co-authored-by: NAME <email@example.com>

It is probably preferable not to include e-mail addresses in PR descriptions anyway, so it seems like it'd be best to just exclude them from the extracted PR description? This also applies to `Signed-off-by:` declarations.

**Comment by mislav** [comment]
Thanks for taking the time to write this down! This is a good idea. We already strip `signed-off-by` line when there is only 1 commit in the PR https://github.com/github/hub/blob/afdd78510c0a39389c9c5fecd9823d7438cd032b/commands/pull_request.go#L289-L290 but we can go even further by stripping out both `signed-off-by` and `co-authored-by` in all cases.
