### ISSUE TITLE
Feature: Change Draft PR to Ready for Review

### ISSUE THREAD

**Issue by phifa** [github/hub#2312]
Currently we can only create a pr / draft pr, but not set it to review.

**Comment by mislav** [comment]
Here's a way could script marking a PR identified via NUMBER as non-draft ("ready for review"):

```
hub api -H 'accept: application/vnd.github.shadow-cat-preview+json' \
  -XPATCH repos/{owner}/{repo}/pulls/NUMBER -F draft=false
```

This is untested. Let us know if it works! More full-featured hub commands to update various fields in pull requests, including draft status, are tracked in https://github.com/github/hub/issues/1523

**Comment by vlerenc** [comment]
Thanks, but the above isn't working @mislav. I can change fields like the title with `hub`, the v3 ReST API, and the v4 GraphQL API, but I have no clue how to `convert-to-draft` or `ready-for-review` a PR. I see the GitHub web UI calling backend functions named this way, but neither the API docs show me how to change the draft status nor would the `hub` allow to do that (the above call seems to explore the generic API call feature anyhow, so this doesn't come as a surprise, but I tried it nevertheless/just in case).

Do you or does anybody know how to tweak the draft status of a GitHub PR programmatically?
