### ISSUE TITLE
Support project when creating PR's

### ISSUE THREAD

**Issue by ianaya89** [github/hub#2320]
Hey, I could not find information related to GitHub Projects with hub. 
So just opening this issue to check if it is supported or not. 

Is it possible to set GitHub project when creating a PR using hub? If it is not, is there a workaround for that using the `hub api`?

Thanks!

**Comment by mislav** [comment]
Tracked in https://github.com/github/hub/issues/1858. Thank you!

> If it is not, is there a workaround for that using the `hub api`?

https://github.com/mislav/hub-api-utils/blob/master/bin/hub-pr-project
