### ISSUE TITLE
Electron Pacakging Issue - Operation not permitted, lstat error

### ISSUE THREAD

**Issue by aruntech89** [github/hub#2324]
Dear All,

I am New to Electron and we are using
"electron": "^6.0.7",
"electron-packager": "^14.0.6"

**Requirement:**
We are building a desktop application using Electron & Python as business to provide productivity tools to support users.

**Error on Packaging**

PERM: operation not permitted, lstat **_'C:\Users\arun\AppData\Local\Temp\electron-download-wlbgwx\electron-v6.0.7-win32-x64.zip'_**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 build-win32: `electron-packager ./ --appname=UtilityTool --build-version=1.0.0 --download.cacheRoot=C:/Users/arun/AppData/Local/electron/Cache --no-asar --no-prune --platform=win32 --arch=x64 --icon=./images/UtilityTool.png --out ./dist/elenpm --overwrite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 build-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arun\AppData\Roaming\npm-cache\_logs\2019-10-24T06_17_59_536Z-debug.log

Note: We used electron download to download the binary files but still the packager is not pointing to cache folder. It is generating random temp folders

**Comment by mislav** [comment]
Hi, I think you are posting in the wrong project. This is an issue tracker for a command-line tool called "hub", which is written in Go and has no ties to Electron.

Perhaps you wanted to post in the Electron issue tracker?
