### ISSUE TITLE
ci-status without local repo

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [github/hub#2344]
Currently I am trying to retrieve `ci-status` from a repo.

Looking at the code, it seems like it enforces a local repo clone!? Could someone please explain why that is?
AFAIK the ci-status is not directly linked to the git graph and thus should work fine without a local clone (which takes time).

The problem is made worse by the fact that cloning is non-trivial in a containerized environment (Kubernetes).
I was hoping that `hub clone` would do the trick in combination with `GITHUB_TOKEN` but it seems like I missed the point of `hub clone`.

**Comment by mislav** [comment]
You are correct in your observations—hub was primarily designed to be run from the context of a git repo.

This requirement makes less sense for commands such as `ci-status`, I agree. We are considering adding a `--repo=OWNER/REPO` flag to all commands so that you may run them without having to clone or cd into anything. Please follow for updates https://github.com/github/hub/issues/2338

In the meantime, you can work around this by initializing an empty repository, no need to clone anything:

```sh
git init 
git remote add origin "https://github.com/OWNER/REPO"
hub ci-status ...
```

It's a bit clumsy but it's cheap and will work well.

**Comment by AndreasBergmeier6176** [comment]
> It might look a bit clumsy but it's cheap (resource-wise) and will work well.

Not really. It is a private repo. So I would have to setup a whole ssh setup inside the Container. Which seems like pure overkill.

For now I work around this with:

```
hub api repos/$GITHUB_REPOSITORY/commits/master/status | jq -r .state
```

**Comment by mislav** [comment]
> It is a private repo. So I would have to setup a whole ssh setup inside the Container. Which seems like pure overkill.

Hub does all its API operations over HTTPS, not SSH. As my workaround above doesn't involve any cloning whatsoever, you don't need to set up SSH. You only need to provide hub with a GITHUB_TOKEN that has access to your private repo.

**Comment by AndreasBergmeier6176** [comment]
> Hub does all its API operations over HTTPS, not SSH. As my workaround above doesn't involve any cloning whatsoever (adding the git remote is only so that hub can pick up the repository URL), you don't need to set up SSH. You only need to provide hub with a GITHUB_TOKEN that has access to your private repo.

If you look at my example, I want to get the status of _master_. In your empty local clone, it cannot lookup master and thus complains: `Aborted: no revision could be determined from 'master'`

**Comment by mislav** [comment]
Ah sorry, you're right. `hub ci-status` does try to de-reference arguments passed using the local git repo.

Your `hub api` workaround is better. 🙇
