### ISSUE TITLE
`hub  pull-request` ignores title and message in PULLREQ_EDITMSG

### ISSUE THREAD

**Issue by bill-auger** [github/hub#2351]
using hub v2.12.8-1
possibly related to: #1066 #2305

i opened [this pull request](https://github.com/calamares/calamares/pull/1266) using the hub program - it was successful; but the title and comment that i supplied did not appear on the website - the PR title became the git commit message and the comment is empty - similar to ticket #1066, though that one describes supplying the title and message via CLI args - in this case, i replaced the defaults in PULLREQ_EDITMSG using a text editor

this was the PULLREQ_EDITMSG:

```
housekeeping - calamares style
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

apply calamares style to src/modules/users/UsersPage.cpp

just 'cause
```

**Comment by mislav** [comment]
To clarify: did you expect this description to appear in your PR message?

> apply calamares style to src/modules/users/UsersPage.cpp
>
> just 'cause

And if so, my next question is: did you read this part?
```
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
```

The way PULLREQ_EDITMSG are supposed to be authored is this:

```
housekeeping - calamares style

apply calamares style to src/modules/users/UsersPage.cpp

just 'cause
# ------------------------ >8 ------------------------
# ...
```

**Comment by bill-auger** [comment]
ok my bad - ty :)
