### ISSUE TITLE
No documentation for hub gist

### ISSUE THREAD

**Issue by doronbehar** [github/hub#2352]
`hub gist --help` fails with:

```
No manual entry for hub-gist
exit status 16
```

No big deal, but kind of confusing for first starters. cc @jaymzh .

**Comment by jaymzh** [comment]
Huh. I checked out the merge commit and it works there. And no other commits mention gist. I guess I'll git bisect and see where the help broke. :(

**Comment by jaymzh** [comment]
@mislav it looks like your commit 8b5f6fe6ac5abc4027a559195cfcd5b8abe57fba broke it, though I don't see how.

**Comment by jaymzh** [comment]
Oh, I take that back. I was doing a `make; ./bin/hub --help gist` for each bisect, and at that build, you pass off to `man`, and since I hadn't done an *install*, of course `man` didn't know about it. I"ll bisect again. :/

**Comment by jaymzh** [comment]
@doronbehar - works for me on `master`... my guess is whatever packaging you're using isn't including the `share/man/man1/hub-gist.1.txt` file.

Are you perhaps using something like `snap` or `flatpak`? I poked at a snap of this on Ubuntu, and *no* help works anymore, because of @mislav 's PR, plus the fact that these things are self-contained and thus can't drop off man pages:

```
$ hub help pull-request
No manual entry for hub-pull-request
exit status 16
$ hub --help pull-request
No manual entry for hub-pull-request
exit status 16
$ hub pull-request --help
No manual entry for hub-pull-request
exit status 16
$ hub pr --help
No manual entry for hub-pr
exit status 16
```

**Comment by raphinesse** [comment]
I'm using the snap version on Ubuntu and can confirm that no help works anymore.

**Comment by mislav** [comment]
Thank you for these reports. I did change the `hub help` (and `hub <command> --help`) logic quite recently.

Hub searches for `hub-<command>.1` manpage in your system's MANPATH plus the following location: `../share/man/man1/` relative to the `hub` executable; e.g. `/usr/local/share/man/man1/` for `/usr/local/bin/hub`.

Can you verify that you have man pages in that location? If not, which method of installation did you use? If from a 3rd-party package (anything other than Homebrew), can you verify with the maintainer that they are including man pages? Thank you.

**Comment by raphinesse** [comment]
@mislav I'm running hub 2.13.0 on Ubuntu 19.04, installed as recommended in the [README](https://github.com/github/hub#installation) via `snap install hub --classic`.

```
$ which hub
/snap/bin/hub

$ ls /snap/share
ls: cannot access '/snap/share': No such file or directory

$ echo $MANPATH 
~/.npm-packages/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man

$ hub help gist
No manual entry for hub-pull-request
exit status 16
```

No entries for `hub` in any of the `MANPATH` directories either.

**Comment by doronbehar** [comment]
My bad. I tried to get ahead of my distro's update and run `go install` in the git repo but I didn't imagine `hub help` looks for manual pages which (naturally) are not in my `$MANPATH` when it's just the executable from `$GOPATH/bin/`. Anyway, sorry for the false alarm and thanks for responding.

**Comment by mislav** [comment]
@doronbehar If you wanted to install hub from the git repo, you can run `PREFIX=/usr/local make install` and that will install both the binary and the help pages.

**Comment by felicianotech** [comment]
This was an issue caused by a change in hub code as well as how the snap was built. It has been fixed in the snap: https://github.com/felicianotech/hub-snap/issues/25
