### ISSUE TITLE
Hub release create throwing a 404 error

### ISSUE THREAD

**Issue by AzizAlimov** [github/hub#2362]
**Command attempted:**
hub release create -a {FILEPATH} -m "$TAG_NAME" $TAG_NAME

**What happened:**

Throwing a 404 error when attempting to use hub release create. In response to the GET request I get a HTTP 200 response so I'm not sure why it's behaving this way

**More info:**

$ git rev-parse -q --git-dir

$ git remote -v

$ git config --get-all hub.host

> GET http://{GITHUBENTERPRISE}/api/v3/user

> Authorization: token [REDACTED]

> Accept: application/vnd.github.v3+json;charset=utf-8

< HTTP 200

{Redacted for privacy}

> POST http://{GITHUBENTERPRISE}/api/v3/repos/aalimov/testifier/releases

> Authorization: token [REDACTED]

> Accept: application/vnd.github.v3+json;charset=utf-8

{"name":"v1.1.46","tag_name":"v1.1.46","target_commitish":"","body":"","draft":false,"prerelease":false,"assets":null,"tarball_url":"","zipball_url":"","html_url":"","upload_url":"","url":"","
created_at":"0001-01-01T00:00:00Z","published_at":"0001-01-01T00:00:00Z"}

< HTTP 404

{"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.16/v3/repos/releases/#create-a-release"}

Error creating release: Not Found (HTTP 404)

Not Found

**Comment by mislav** [comment]
Hey, sorry you're having trouble, and thank you for the info.

It looks like hub is using a token from GITHUB_TOKEN environment variable. Can you verify that that token is connected to a user that has access to the `aalimov/testifier` repo? Often, permission problems result in 404 getting returned as a result.

**Comment by AzizAlimov** [comment]
My bad, it was a permission problem (didn't expect it to throw a 404)
