### ISSUE TITLE
Older versions of Git fail to #rev_list silently

### ISSUE THREAD

**Issue by Peeja** [github/hub#237]
I had Git 1.7.4.1 and couldn't get `git pull-request` to give me a default PR message.  I tracked it down to `#rev_list` using `--right-only`, which doesn't exist in that version of Git.

Since Git is returning a non-zero status, it would be nice to have some sort of error or warning that would point me to trouble with Git.

**Comment by mislav** [comment]
I'm not sure what's our minimum required git version anymore, but time has passed since this was reported, and people now generally have newer git versions that support `--right-only`. Nobody has complained about this since, so I'm going to go ahead and close this out.
