### ISSUE TITLE
hub pull-request not properly assigning to teams

### ISSUE THREAD

**Issue by ghirsch1** [github/hub#2382]
**Command attempted:**

I tried `hub pull-request -r Clever/teams-testing` and `hub pull-request -r teams-testing`

For reference, `teams-testing` is a team within an organization named `Clever`

**What happened:**

Assigning PRs to teams does not seem to be working. I'm not sure if this is intended to work, but it seems like it should.

When I used `Clever/teams-testing` I saw
`Error creating pull request: Unprocessable Entity (HTTP 422)
Could not resolve to a node with the global id of '****'.`

When I used `teams-testing` there were no errors, but the team was not actually assigned to the PR.

**Comment by mislav** [comment]
Thanks for reporting!

1. Is the current repository also owned by an organization called "Clever"
2. Does the `teams-testing` team have access to this repository
3. Can you assign the same team from web UI?
4. Is this github.com or GHE
5. What is your `hub version`?

**Comment by ghirsch1** [comment]
Hi mislav, thanks for responding! I just tried testing this locally and it actually does assign things correctly (which I didn't even think to try, sorry about that).

I am still having this issue when running the command via a GitHub workflow, though I'm not sure why there would be any difference, as it is using the same version of hub that I have locally (2.13.0).

I've answered the questions you asked below, but if it would be better to close this and reopen something in a workflows/actions repo, I'm happy to do that too.

1. yes
2. yes
3. yes
4. I'm not sure, how would I tell?
5. 2.13.0

**Comment by mislav** [comment]
> 4\. I'm not sure, how would I tell?

Ah, if it's within a GitHub workflow, then it's definitely GitHub.com (not GitHub Enterprise).

> I've answered the questions you asked below, but if it would be better to close this and reopen something in a workflows/actions repo, I'm happy to do that too.

Yes, please do that. When you provide information for them, tell them that [hub uses this endpoint](https://developer.github.com/v3/pulls/review_requests/#create-a-review-request) and that for some reason it works locally but not in the context of an action.

**Comment by ghirsch1** [comment]
Closing this, thanks!
