### ISSUE TITLE
Tag transformation in MkmTools import

### ISSUE THREAD

**Issue by s-hadz** [github/hub#2383]
Do you know if there's is a way to convert the column "Tag" from Delver's Lens export (.csv) to Mkmtool's integration as column "Comment" to export to Mkm ?

**The problem I'm trying to solve:**

**How I imagine hub could expose this functionality:**

Thanks for your help

**Comment by mislav** [comment]
Hi, this is an issue tracker for a command-line project called "hub". It has nothing to do with mkmtool or CSV or Delver's lens. Perhaps you will want to ask your question elsewhere.
