### ISSUE TITLE
exec: "absolute\\path\\to\\hub.exe.exe": file does not exist

### ISSUE THREAD

**Issue by zmni** [github/hub#2384]
**Command attempted:**
`git help <hub-command>`

**What happened:**
I set `git` as an alias for `hub` with `Set-Alias -Name git -Value "absolute\path\to\hub.exe"`. And it works. But only the above command caused this problem.

**More info:**

1. Put `Set-Alias -Name git -Value "absolute\path\to\hub.exe"` in your PowerShell profile.
2. Reload `$PROFILE` and run `git help <hub-command>`

```
Windows 8.1 x64
git version 2.22.0.windows.1
hub version 2.13.0
```

**Comment by mislav** [comment]
This works for me:

```ps1
Set-Alias -Name git -Value "C:\Users\Mislav\AppData\Local\GitHubCLI\bin\hub.exe"

git help fork
```

Can you paste the exact `git help ...` command you've ran and the error message? You can scrub sensitive directory names from the path if needed

**Comment by zmni** [comment]
![mI43J8DUDX](https://user-images.githubusercontent.com/841523/70508118-55e36e00-1b60-11ea-9ab0-94c84d2981ed.gif)

This is what I put in my `$PROFILE`:
```powershell
Set-Alias -Name git -Value "$env:Bin\github\bin\hub.exe"
```

**Comment by mislav** [comment]
Thank you! You've helped me find the bug. 🙇
