### ISSUE TITLE
Next.js - Few Links do not work in production & all links work in development

### ISSUE THREAD

**Issue by waqaar145** [github/hub#2385]
I have built a Next.js & Express.js  application that works fine in development but in production there are few links in navigation bar and at some other places that do not work. And also after built I get some 404 like these. Here are few 
`https://example.com/_next/static/uskRfKy1t9bdwHxqyX7Ct/pages/question.js net::ERR_ABORTED 404 (Not Found)`
`GET https://example.com/_next/static/uskRfKy1t9bdwHxqyX7Ct/pages/profile.js net::ERR_ABORTED 404 (Not Found)`

I have 3 links in navigation bar Home, Questions, Notifications. Home & Questions link do not work when I am on certain page, but Notification link do work from each page. I do not understand why this is happening.

`
<Button className={classes.button}><Link href='/index' as="/"><a className={classes.link}>Home</a></Link></Button>
<Button className={classes.button}><Link href='/questions' as="/questions"><a className={classes.link}>Questions</a></Link></Button>
<Button className={classes.button}><Link href='/notifications'><a className={classes.link}>Notifications</a></Link></Button>
`
I have tried different things to make it work but I could not succeed. 
Everything works in development

Next.js - 9.1.4

**Comment by mislav** [comment]
Sorry, this is an issue for a command-line tool called "hub" written in Go and has nothing to do with Next.js or Express.
