### ISSUE TITLE
Accounting Dimension issue while cancelling Purchase or sales invoice for rounding off

### ISSUE THREAD

**Issue by kfcspl** [github/hub#2420]
We have activated accounting dimensions of branch and locations and made Mandatory for Profit & Loss matters, however faced issues while cancelling Purchase invoices with attached error screen and showing Accounting Dimension of branch not selected for  rounding off.
![error screen](https://user-images.githubusercontent.com/52742315/70890278-ac422800-200a-11ea-82d4-2832f8af7141.jpeg)

**Comment by mislav** [comment]
Sorry, this is an issue tracker for a command-line tool called "hub", and it looks like you have a problem with something that is completely unrelated. I don't know which software you're having issues with, but it's not this one, and you should find a more appropriate forum to ask your question.
