### ISSUE TITLE
Pokemon sword

### ISSUE THREAD

**Issue by AE89** [github/hub#2425]
**The problem I'm trying to solve:**

the icon 'pan-down-symbolic-ltr'
Ryujinx:11972): Gtk-WARNING **: 21:28:19.249: Could not find the icon 'pan-down-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(Ryujinx:11972): Gtk-WARNING **: 21:28:19.281: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

**Comment by mislav** [comment]
https://github.com/github/hub/issues/2421#issuecomment-566178407
