### ISSUE TITLE
bcrypt in node and mongo

### ISSUE THREAD

**Issue by ankitkm418** [github/hub#2429]
// Import contact model
User = require('./userModel');
VendorDetail = require('./vendorDetailModel');

var otpGenerator = require('otp-generator');

var bcrypt = require('bcryptjs');
var password = 'Passwords';

exports.signup = function(req, res) {

    var user = new User();
    var otp = otpGenerator.generate(6, { digits: true, alphabets: false, upperCase: false, specialChars: false });

    bcrypt.genSalt(10, function(err, salt) {
        if (err) {
            throw err
        } else {
            bcrypt.hash(req.body.password, salt, function(err, hash) {
                if (err) {
                    throw err
                } else {
                    console.log(hash)
                }
            })
        }
    })
    user.username = req.body.username;
    user.type = req.body.type;
    user.password = req.body.password;
    user.otp = otp;

    // save the signup and check for errors
    user.save(function(err) {
        if (err)
            res.json(err);
        else {
            res.json({

                message: 'New signup created!',
                data: user
            });
        }
    });
};

this is my code i trying to bcrypt it, the password in bcrypted and bcrypted password show in console but bcrypted password is not store in the mongodb

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
