### ISSUE TITLE
Add .zstd downloads for archives?

### ISSUE THREAD

**Issue by SRGOM** [github/hub#2436]
(For github, not just `hub`).

They say you shouldn't look a "git" horse in the mouth but would you guys be kind enough to add an option to download a `zstd` in the archive repo download URL?

e.g. in addition to (or replacement of) https://github.com/USER/REPO/archive/${sha}.tar.gz

I'd also like https://github.com/USER/REPO/archive/${sha}.tar.zstd

Arch Linux maintainers claim that the decompression times reduce to a twelfth with almost negligible size increases (less than a percent) (with the compression parameter 20)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
