### ISSUE TITLE
Allow multiple SSO orgs with github.com

### ISSUE THREAD

**Issue by robkinyon-roivant** [github/hub#2441]
**The problem I'm trying to solve:**

I have been granted access to multiple private Github organizations, all of which are protected by SSO using Okta. With Okta-to-Okta trust, I have two Okta tiles for Github, one for org1 and one for org2. I have logged into org1 and created a personal access token and enabled SSO for it.

I am now trying to clone a repository in org2. As far as I can tell, I cannot use the same token because it is tied to the SSO for org1. So, let's say I generate a second token and use it for org2. At this point, which token is hub going to use? In `.config/hub`, the token is selected based on the domain, but that's going to be "github.com" for both orgs. Is there a way to select which token to use based on "github.com/org1" vs "github.com/org2"?

**How I imagine hub could expose this functionality:**
`.config/hub` allows selection of token based on org as well as domain.

**Comment by robkinyon-roivant** [comment]
Apparently, I can enable a token for SSO with multiple organizations. The GitHub UI is unfortunate in that the dropdown says "Disable SSO" even though you now get to a button that says "Enable for org2"

**Comment by mislav** [comment]
> The GitHub UI is unfortunate in that the dropdown says "Disable SSO"

I can see how this is definitely confusing. Glad you figured it out, though!
