### ISSUE TITLE
Support setting project when creating a new issue

### ISSUE THREAD

**Issue by alfredvaa** [github/hub#2444]
**The problem I'm trying to solve:**

Creating an issue by `hub issue -m "My issue" -l label -p v1` should add the issue to project v1. I guess there is no flag at this moment for specifying a project when creating a new issue, it would be nice to have.

**How I imagine hub could expose this functionality:**

`hub issue -m "My issue" -l label -p v1`

**Comment by mislav** [comment]
Agreed that this would be a useful feature. It was requested before https://github.com/github/hub/issues/1595 https://github.com/github/hub/issues/1858, so I'm going to close this out in favor of existing feature requests.

Also see an example script of how you can accomplish adding an issue to a project manually via `hub api`, which is available today: https://github.com/mislav/hub-api-utils/blob/master/bin/hub-pr-project
