### ISSUE TITLE
Support custom SSH hosts

### ISSUE THREAD

**Issue by bl-mklein** [github/hub#2447]
Hello!

I'm trying to set up my `~/.config/hub` to use custom SSH hosts, but no success:

I've two different Github accounts: one personal (`foo`) and one professional (`bar`).

Thus, I have the following setup on `~/.ssh/config`:

```
# Personal GitHub account
Host foo
  AddKeysToAgent yes
  UseKeychain yes
  HostName github.com
  User git
  IdentityFile ~/.ssh/foo/id_rsa

# Blacklane GitHub account
Host bar
  AddKeysToAgent yes
  UseKeychain yes
  HostName github.com
  User git
  IdentityFile ~/.ssh/bar/id_rsa
```

And the Git remote for my repositories use the custom hosts, for example:

```
origin	git@foo:mauricioklein/my-repo.git (fetch)
origin	git@foo:mauricioklein/my-repo.git (push)

origin	git@bar:mauricioklein/my-other-repo.git (fetch)
origin	git@bar:mauricioklein/my-other-repo.git (push)
```

My question is:
How can I set up Hub to use a similar setup?
I can only manage to have a single rule for `github.com` on `~/.config/hub`, but of course it doesn't work, because the last used profile will overwrite the previous.

Any idea?

Thanks in advance for any support!

**Comment by mislav** [comment]
Hi thanks for the detailed feature request! This is not yet possible with hub, but was already requested before, so I'm going to close this in favor of #1934

What you can manually do in the meantime to work around your multi-user case is to swap the value of the `HUB_CONFIG` environment variable based on the criteria that you define in your shell. The default location is `$HOME/.config/hub`. 

Using something like direnv, you can create an `.envrc` file within a project to set it to an alternate location, e.g. for all blacklane projects you can do:
```
export HUB_CONFIG="$HOME/.config/hub-blacklane"
```
so whenever you `cd` into one of these projects, hub will use an alternate configuration file which can contain a different username/token combo than the main config file.

**Comment by mislav** [comment]
Note that my above hack won't work for `hub clone OWNER/REPO` or `hub remote add myremote OWNER/REPO`.

While hub does support parsing out git remotes such as `git@bar:mauricioklein/my-other-repo.git` and finding out what `bar` means by scanning your SSH config, it doesn't let you `hub clone mauricioklein/my-other-repo` and have such SSH url configured for the "origin" remote. Therefore you will have to `git clone git@bar:mauricioklein/my-other-repo.git`.

**Comment by bl-mklein** [comment]
Thanks for the detailed feedback @mislav !
I'll subscribe for the original request and will use your workaround in the meantime 👍
