### ISSUE TITLE
French history facts for webtrees

### ISSUE THREAD

**Issue by AndreasRauhut** [github/hub#2452]
Please add the french history facts module to the next release.
I hope it's OK.

[FrenchMonarchsPresidents.zip](https://github.com/github/hub/files/4104763/FrenchMonarchsPresidents.zip)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
