### ISSUE TITLE
PAYPAL CHECKOUT NOT WORKING WHILE SANDBOX TESTING AND ALSO ERROR TOKENIZING IN BRAINTREE

### ISSUE THREAD

**Issue by abhizeet007** [github/hub#2456]
![D](https://user-images.githubusercontent.com/50789510/73274862-4a313100-420c-11ea-8697-b3a8ce7df036.jpeg)

**Comment by mislav** [comment]
THIS ISSUE TRACKER IS FOR A COMMAND-LINE TOOL CALLED "HUB" WHICH IS WRITTEN IN GO AND HAS NOTHING TO DO WITH PAYPAL. YOUR QUESTION SEEMS UNRELATED TO THIS PROJECT, AND YOU SHOULD FIND A MORE APPROPRIATE FORUM TO ASK IT IN. THANK YOU
