### ISSUE TITLE
Win-client behaving incorrectly with SMB

### ISSUE THREAD

**Issue by Shravan4043** [github/hub#2464]
Hi team,

I am from Netapp & here we are seeing two issues for which we need your help in getting to the root-cause.
Behavior-1: When trying to do a CIFS mount from win-client using IP address, we are seeing that the client is requesting for Kerberos authentication, while the expectation is to always try with NTLM authentication. Why is this happening, please correct me.

Bahavior 2: When a win-client is sending Kerberos ticket that is encrypted with a key(password) that the server is unable to decrypt because of key-mismatch, Server returns KRB5KRB_AP_ERR_MODIFIED to the client. In such a scenario the expectation from our end is that win-client should not be caching this invalid kerberos ticket, but the client is going ahead & caching the invalid kerberos ticket. Why is this happening?

We have seen this behavior across win-client 2k3 with SMB1 & SMB2 versions. We need your help in understanding the root-cause for both these cases & also the right-fix to prevent this from happening again.
Please let me know if you are looking for any details in this regard.
If this is not the right team to respond, please forward this query to the appropriate group.

Thanks,
Shravan
Netapp-India

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
