### ISSUE TITLE
Push to Pull Request

### ISSUE THREAD

**Issue by VasekPurchart** [github/hub#2467]
**The problem I'm trying to solve:**

When I checkout a PR, I do it almost always in order to work with the PR further, either I want to make some changes or most often only rebase it.

Currently when I want to push the changes back I have to find out the repo URL and branch name and construct something like:

```
git push git@github.com:fork/my-project branch-name
``` 

Or at least this is the only way I know currently to do it (without other tools).

**How I imagine hub could expose this functionality:**

I hoped that there would be a

```
hub pr push
```

command I could call. Ideally without having to specify the issue number again since I am already in the branch. But I am not sure if this is stored somewhere in the repo (since I cannot see it). What I am proposing in #2466 could help with this.

There would probably also have to be an `-f` option like with the normal push (since the common rebase usecase)

---

This is in fact what I hoped this project would solve for me when I saw it. And what I was looking for on https://hub.github.com/ in `Designed for open-source maintainers`

**Comment by mislav** [comment]
> Currently when I want to push the changes back I have to find out the repo URL and branch name and construct something like:

You should be able to just do `git push` without arguments. `hub pr checkout` makes it simple to push back to the PR, even those that are coming from forks.

**Comment by Duc56789** [comment]
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by jpfeuffer** [comment]
Same problem here: @wkentaro Did you find any workaround?
