### ISSUE TITLE
"Deploy Keys" management

### ISSUE THREAD

**Issue by mrzacarias** [github/hub#2468]
**The problem I'm trying to solve:**
I'm working with some GitOps solutions and some of them require that a Deploy Key is created on GitHub. Would be great if I could use hub to manage deploy keys from the command line, instead of needing to use GH UI for that.

**How I imagine hub could expose this functionality:**
`hub deploy-key list`
`hub deploy-key create <KEY-NAME> <PUB KEY>`
`hub deploy-key delete <KEY-NAME>`

**Comment by mislav** [comment]
Is this something you could pull of via `hub api`?

```sh
# get deploy keys:
hub api 'repos/{owner}/{repo}/keys'
# add a deploy key from file:
hub api 'repos/{owner}/{repo}/keys' -F key=@myfile.txt
```

It's unlikely that we will add functionality around this in hub core, as it would probably see little daily use.
