### ISSUE TITLE
Make it obvious that most users can't assign labels

### ISSUE THREAD

**Issue by rlayton6** [github/hub#2474]
**Needs to be more obvious that most users can not assign a label to their issue.**
It wastes people's time when they look for this expected feature and it isn't present.

**Remove the labels section until labels have been assigned, and/or show the gear icon in a disabled state:**
A message explicitly stating that users don't assign labels to their issues would also be helpful.

**Comment by mislav** [comment]
Hi, I believe this is a suggestion for GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!

BTW your suggestions are spot on 👍
