### ISSUE TITLE
snap installation on ubuntu requires sudo

### ISSUE THREAD

**Issue by yuanfang-chen** [github/hub#2475]
Top-level README needs to be updated.  According to https://snapcraft.io/install/hub/ubuntu, installation via snap requires sudo.

**Comment by felicianotech** [comment]
I can confirm. Opening a PR.

**Comment by anonymouse64** [comment]
Just as an FYI, you don't have to use `sudo` to run snap commands if log into an Ubuntu One account/Launchpad account with `snap login ...`
