### ISSUE TITLE
Hub Api Fails with `git: 'api' is not a git command. See 'git --help'.`

### ISSUE THREAD

**Issue by nicovigil1** [github/hub#2476]
**Command attempted:**
`hub api user`
`hub api --flat users/octocat/repos`

**What happened:**
`git: 'api' is not a git command. See 'git --help'.`

**More info:**
Tried both the gem and Homebrew versions on mac osx
```
git version 2.22.0
hub version 1.12.4
```

Any and all help is appreciated

**Comment by mislav** [comment]
Hi, thanks for reporting; this is really weird! The `api` command was available since hub 2.8. I don't understand why this doesn't work for you. Do you have any git aliases in `~/.gitconfig` that might affect this?

**Comment by mislav** [comment]
Ah I see. Your version of hub is out-of-date. Please upgrade to a newer one!

**Comment by nicovigil1** [comment]
Oh shoot - forgot to reply back here with my fix. It turns out the version of hub on RubyGems is out of date. Is the `Hub` gem currently deprecated?

**Comment by mislav** [comment]
@nicovigil1 Yes, the `hub` ruby gem is some 5 years out of date 🙈

**Comment by cbaenziger** [comment]
This behavior holds true for the [Ubuntu 20.04 package](https://packages.ubuntu.com/search?keywords=hub) too as 20.04 has Hub version 2.7.0.
