### ISSUE TITLE
Create new repo with default settings

### ISSUE THREAD

**Issue by nitrocode** [github/hub#2477]
**The problem I'm trying to solve:**

Trying to create a new repo with auto deletion of merged branched set to True and various other settings. doesn't seem to be a way to do this accept by using a custom python script.

**How I imagine hub could expose this functionality:**

Ideally, I'd like to set default new repo settings in a yaml file and run the tool using the file with an input for the name in our enterprise account and it should just work.

Thanks for a great tool

**Comment by mislav** [comment]
You can do this via `hub api`:

```
hub create
hub api -XPATCH 'repos/{owner}/{repo}' -F delete_branch_on_merge=true
```

It's a bit manual, but it does the trick! Creating repos from a yaml file is a bit too specific for this project, so I think it's best implemented in your hands.
