### ISSUE TITLE
Automatically Merged PR

### ISSUE THREAD

**Issue by nikul-serpentcs** [github/hub#2481]
I have a 2 branch in my repo.
1. `master`
2. `master_dev` (Branch Created base on `master`)

I added code and created a new PR base on `master_dev`,  **PR No. 1**
merge message like: wants to merge 11 commits into `master` from `master_dev`

my friend changed code in the main `master` branch.
whenever I created new PR to saving `master` branch commit in my `master_dev` branch  **PR No. 2**
merge message like: wants to merge 3 commits into `master_dev` from `master`

But That time conflict code in 1 file, So I `resolve conflict` and click on `Make resolve` button.
after merged my **PR No. 2** then automatically merged my main  **PR No. 1**

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
