### ISSUE TITLE
Jupyter notebook Title

### ISSUE THREAD

**Issue by MatteoSerafino** [github/hub#2483]
**Command attempted:**

**What happened:**

**More info:**

**Comment by MatteoSerafino** [comment]
Hi all, I can not visualize the title of my notebook jupyter anymore. The bottom View/Toggle header does not work.  Any idea?

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please visit https://github.com/contact. Thank you!
