### ISSUE TITLE
Git Push failing when 2FA is enabled -

### ISSUE THREAD

**Issue by Raghuveer-Yadav-Gadula** [github/hub#2488]
I have enabled 2FA - two factor authentication for git hub names with the soften app .
the git push gets failed with the error as follows: ----
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/------------

**Comment by mislav** [comment]
1. Create a Personal Access Token for use with cloning and pushing: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
2. Use that token instead of your password when you get prompted for username + password.

**Comment by Raghuveer-Yadav-Gadula** [comment]
Yeah this work around works , but it would have been better if it is something like “custom password set by user , followed by soft token number “ .

Any future plans on the same in this regard?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mislav** [comment]
> Any future plans on the same in this regard?

No; generating the Personal Access Token is right now the main way to authenticate for git clone/push when your account has 2FA enabled. This is because (to my knowledge) git itself doesn't have any mechanism of interactively asking your for your 2FA code.

**Comment by Raghuveer-Yadav-Gadula** [comment]
Thanks for the follow up

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sei1122** [comment]
I used the access token but push still failed. Any idea?

**Comment by andreimotin** [comment]
> 1. Create a Personal Access Token for use with cloning and pushing: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
> 2. Use that token instead of your password when you get prompted for username + password on git push.

I did this, but every time I get this:
```
user@192 cpython % git push origin feature/extend-multiple
Username for 'https://github.com': andreimotin
Password for 'https://andreimotin@github.com': 
remote: Permission to python/cpython.git denied to andreimotin.
fatal: unable to access 'https://github.com/python/cpython.git/': The requested URL returned error: 403```
