### ISSUE TITLE
[Windows] How do you uninstall this?

### ISSUE THREAD

**Issue by iamthekings5** [github/hub#2490]
**Command attempted:**
hub sync

**What happened:
I installed the windows 64 bit version and decided to uninstall this software, but there doesn't seem to be an uninstall option. I have tried uninstalling Git but the commands still seem to run, though some understandably return an error. How do I fully uninstall this?

**More info:**
hub-windows-amd64-2.14.1, Windows 10 64 bit

**Comment by z-t-y** [comment]
How do you install hub?

**Comment by z-t-y** [comment]
If you install it with chocolatey, then you can simply 
C:\Windows\System32> choco uninstall hub

**Comment by iamthekings5** [comment]
I installed using the windows 64 bit package, any idea on how to uninstall if i used that method?

**Comment by z-t-y** [comment]
Delete It

Sent from Mail for Windows 10

**Comment by mislav** [comment]
We have no uninstaller right now, sorry. You will have to manually delete the files under `%LOCALAPPDATA%\GitHubCLI` (typically under the `Program Files` directory)

**Comment by iamthekings5** [comment]
Thanks! That solved it :-)

**Comment by iamthequeen4** [comment]
d
