### ISSUE TITLE
Display members of organization first in search select form

### ISSUE THREAD

**Issue by nrukavkov** [github/hub#2492]
Hello. It would be great to see my colleagues in the search form first instead of all GitHub users. For example, I want to add my colleague to some Team. I guess it is sensible to show similar accounts in my organization first. And then show all GitHub users.

This problem also increase the time of searching for my colleagues. Because I need to write a full name to find out them.

**Comment by sshakirova** [comment]
+

**Comment by lady-guga** [comment]
+1

**Comment by beylkhanovdamir** [comment]
+1

**Comment by mislav** [comment]
That's a great suggestion. However, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, go to https://github.com/contact or visit https://github.community. Thank you!
