### ISSUE TITLE
Display Name (Name and Surname) into organization instead accountname

### ISSUE THREAD

**Issue by nrukavkov** [github/hub#2493]
We have a huge team and seeing account_names instead real Name and Surname is a big problem for us.

It would be great if you release option in an organization which allows administrators or users to change a view of GitHub user names. 

Example: instead of this one
![kZz4S30tSfeZM6zUaw2IkA](https://user-images.githubusercontent.com/54890287/75878136-30e25c80-5e2a-11ea-9852-df0c9e041bcb.png)

I want to see a field **Name** in **Public Profile** 
![JwqGxs8XQJ2b3SA-5O0FcQ](https://user-images.githubusercontent.com/54890287/75878435-9f271f00-5e2a-11ea-8cfb-57a4e2ae4ded.png)

**Case1:** I want to take a screenshot and send some department without describing who is who on the screenshot.
 
**Case2:** If I want to start a dialog in Slack with somebody I don't need to have a mouseover to the account name. I can start conversation immediately.

**Comment by mislav** [comment]
Hi, this is also a great suggestion. But like with the previous issue, I believe this is a question about GitHub.com, the website. This project and issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
