### ISSUE TITLE
Is there a way, where issues in a repository can be highlighted as priority

### ISSUE THREAD

**Issue by Asma123-code** [github/hub#2498]
I would like issues, example aging issues to have red color when i open a git hub repository, i am not talking about the labels, the repository already has labels, what i need is in case issue in the repo has crossed a time period it should be red/pink in color.

How is this  possible, could you please guide.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community.

Anyway, what you're describing could be done with GitHub Actions. Here is an example action to label/auto-close issues after they have reached some age: https://github.com/actions/stale.
