### ISSUE TITLE
i try much time to solve but i'm losse anyone help me out.

### ISSUE THREAD

**Issue by shahbajk28** [github/hub#2499]
Xcode build done.                                           123.3s
	path: satisfied (Path is satisfied), interface: en1
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001176eb27e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00000001144c1b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001176eb0bc +[NSException raise:format:] + 188
	3   Runner                              0x000000010fa9395a +[FIRApp configure] + 138
	4   Runner                              0x000000010fa3a10f $s6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 143
	5   Runner                              0x000000010fa3a4a4 $s6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 21<…>

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
