### ISSUE TITLE
Can't run codeception functional tests on Laravel 7+

### ISSUE THREAD

**Issue by Max-S-upper** [github/hub#2503]
**Command attempted:**
php vendor/bin/codecept run

**What happened:**
I run a codecept functional test on Laravel v7.2.1 and get the following error:
![image](https://user-images.githubusercontent.com/35345762/77195156-dd3e6700-6ae9-11ea-9f51-c90c8e934bc9.png)

I've tried running it on the 5 and 6 Laravel versions and it works perfectly, so the problem must be in the codeception functional tests and Laravel v7+ incompatibility.
In all cases Laravel projects were empty (skeletons).

**More info:**
my codecept functional test:
![image](https://user-images.githubusercontent.com/35345762/77196619-63f44380-6aec-11ea-89b9-9cd643a0d2d0.png)

functional.suite.yml:
![image](https://user-images.githubusercontent.com/35345762/77195691-b5033800-6aea-11ea-9114-81ac04cee103.png)

acceptance.suite.yml:
![image](https://user-images.githubusercontent.com/35345762/77195654-a9177600-6aea-11ea-8074-3358eb28c5c5.png)

composer.json requirements:
![image](https://user-images.githubusercontent.com/35345762/77195962-2d69f900-6aeb-11ea-8096-4fb2aebb5145.png)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
