### ISSUE TITLE
Can't run codeception functional tests on Laravel v7+

### ISSUE THREAD

**Issue by Max-S-upper** [github/hub#2507]
**Command attempted:**
php vendor/bin/codecept run

**What happened:**
I run a codecept functional test on Laravel v7.2.1 and get the following error:
![image](https://user-images.githubusercontent.com/35345762/77251534-82c31900-6c57-11ea-9cc0-f6e760d31de9.png)

I've tried running it on the 5 and 6 Laravel versions and it works perfectly, so the problem must be in the codeception functional tests and Laravel v7+ incompatibility.
In all cases Laravel projects were empty (skeletons).

**More info:**
my codecept functional test:
image
![image](https://user-images.githubusercontent.com/35345762/77251553-9a9a9d00-6c57-11ea-8562-2093682989d5.png)

functional.suite.yml:
image
![image](https://user-images.githubusercontent.com/35345762/77251554-9f5f5100-6c57-11ea-9ff2-fd035ed44298.png)

acceptance.suite.yml:
image
![image](https://user-images.githubusercontent.com/35345762/77251557-a4bc9b80-6c57-11ea-8ed1-e3bc74d1e59e.png)

composer.json requirements:
image
![image](https://user-images.githubusercontent.com/35345762/77251558-a8502280-6c57-11ea-8d73-62b1fd02c903.png)

**Comment by mislav** [comment]
Hi, please read carefully: https://github.com/github/hub/issues/2503#issuecomment-602047151
