### ISSUE TITLE
Draft Pull Requests, Projects, and Request Review

### ISSUE THREAD

**Issue by stephendb** [github/hub#2510]
Projects are very useful but there is at least one automation option that is missing. I can't separate pull requests that are ready for review from those that are in work automatically onto separate columns. For project management it is very useful to know if a pull request is being worked on or if it is in the review process at a glance. As it stands a pull request that is ready for review or not both get lumped into In Progress since there is no distinction until a change request is made by a reviewer.

In the current system the easiest improvement would be to create an automation option for the Draft Pull Request feature so we can isolate draft pull requests from regular pull requests. This would indicate whether something was ready for review.

Essentially, I expect lots of people would like to have columns like:
To Do, In Progress, In Review, Done
Being able to isolate draft pull requests into in progress would allow me to then have only ready for review pull requests in In Review.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
