### ISSUE TITLE
Files in a commit do not appear in a pull request

### ISSUE THREAD

**Issue by CLIRResearch** [github/hub#2516]
I have a commit made to a branch.  When I tried to create a pull-request, the commit and related files were not in the pull-request.  If I go to my branch there are zero changes that show up.  If I look at history, the commit exists.  

Is it possible to manually add a commit to a pull-request?  

I have been using Git for about 8 months - I am still not used to the ambiguous and confusing syntax.

**Comment by mislav** [comment]
Hi, this sounds like more of a GitHub usage question than a bug report with `hub pull-request`, so I'm going to add my tips and close this pre-emptively.

It's possible to keep adding commits to a pull request as long as the pull request is open. You just have to push to the head branch of the pull request.

Every pull request has a base branch and a head branch:
- base branch: the branch into which the pull request will eventually get merged (usually "master")
- head branch: the branch that contains the commits for a pull request

So if the head branch for a PR is called, for example, `patch-1`, you can add more commits to a pull request like so:

```
# assuming the git remote is named "origin"
git push origin HEAD:patch-1
```

Good luck!

**Comment by bartlomiejkaczmarczyk** [comment]
I had the same situation.
I've made cherry pick of last commit to the same branch, then `git commit --allow-empty` then `:wq!` to close terminal and save changes . And git push again. Works well (you will see 2 comiits, last one empty)
