### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/github/hub/v2

### ISSUE THREAD

**Issue by KateGo520** [github/hub#2517]
I want to import the version v2.14.2 of github.com/github/hub.
First, I did this：
### What did you do?

```
go get github.com/github/hub
```

### What did you expect to see?

Correctly download latest version

### What did you see instead?

```
go: finding github.com/github/hub v2.11.2+incompatible
go: downloading github.com/github/hub v2.11.2+incompatible
go: extracting github.com/github/hub v2.11.2+incompatible
go: finding github.com/mattn/go-isatty v0.0.12
go: downloading github.com/golang/crypto v0.0.0-20190829043050-9756ffdc2472
go: finding github.com/kballard/go-shellquote latest
go: finding github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: extracting github.com/golang/crypto v0.0.0-20190829043050-9756ffdc2472
go: extracting github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: finding gopkg.in/yaml.v2 v2.2.8
go: finding github.com/mattn/go-colorable v0.1.6
go: finding github.com/atotto/clipboard v0.1.2
go: downloading github.com/atotto/clipboard v0.1.2
go: extracting github.com/atotto/clipboard v0.1.2
```

Old version (v2.11.2) is pulled.

Then, I try like this:

### What did you do?

```
go get github.com/github/hub@v2.14.2
```

### What did you expect to see?

Correctly download v2.14.2.

### What did you see instead?

```
go: finding github.com/github/hub v2.14.2
go: finding github.com/github/hub v2.14.2
go get github.com/github/hub@v2.14.2: github.com/github/hub@v2.14.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

It looks like the module path in go.mod isn't correct:
https://github.com/github/hub/blob/v2.14.2/go.mod#L1

```
module github.com/github/hub
```

According to https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

Because the version is >= v2, I believe you need to have the major version at the end of the module path in your module directive in your go.mod file，like this:

```
module github.com/github/hub/v2
```

Related issue: [golang/go#35732](https://github.com/golang/go/issues/35732)

**Comment by KateGo520** [comment]
@mislav  @kfcampbell

**Comment by mislav** [comment]
Thanks for the heads-up! I think `/v2` would make sense. We discussed it briefly in https://github.com/github/hub/pull/2138#discussion_r284286819 and you are welcome to send a PR.

However, note that if you are importing our code in your own project, this repository hosts a CLI app written in Go, not a collection of reusable libraries—even though after adding `/v2`, nothing is stopping you from importing this into your app. Because we don't maintain anything in this repo as a library, we don't uphold a compatibility promise either. We might move/rename methods while we're still at v2.

Which part of this project are you aiming to import?

BTW I've just tried `go get github.com/github/hub` with go 1.14 and it correctly downloaded and compiled hub 2.14.2. 😕

**Comment by KateGo520** [comment]
I  tried go get github.com/github/hub with go 1.14, still not work.

```
go version
go version go1.14.2 windows/amd64
go get github.com/github/hub
go: github.com/github/hub upgrade => v2.11.2+incompatible
go: finding module for package github.com/mattn/go-isatty
go: finding module for package github.com/mattn/go-colorable
go: finding module for package gopkg.in/yaml.v2
go: finding module for package github.com/atotto/clipboard
go: finding module for package github.com/BurntSushi/toml
go: finding module for package github.com/mitchellh/go-homedir
go: finding module for package github.com/kballard/go-shellquote
go: found github.com/atotto/clipboard in github.com/atotto/clipboard v0.1.2
go: found github.com/kballard/go-shellquote in github.com/kballard/go-shellquote
 v0.0.0-20180428030007-95032a82bc51
go: found github.com/BurntSushi/toml in github.com/BurntSushi/toml v0.3.1
go: found github.com/mitchellh/go-homedir in github.com/mitchellh/go-homedir v1.
1.0
go: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.2.8
go: found github.com/mattn/go-colorable in github.com/mattn/go-colorable v0.1.6
go: found github.com/mattn/go-isatty in github.com/mattn/go-isatty v0.0.12
```

**Comment by novas0x2a** [comment]
> Which part of this project are you aiming to import?

So, for us, we're not using it as a library, we're using the [`tools.go`](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) convention to pull hub in as a dep (replacing our older hacked-together convention). Obviously, gomod doesn't really have a way to declare a distinction between api compat and cmdline compat (kind of unfortunate) but we work around that by paying attention when we run `go get -u` :D

**Comment by KateGo520** [comment]
Thank you for your change. That helps a lot.
I'm not the only one who uses "github.com/github/hub" as a library.
I found 22 other repos in github.com who uses "github.com/github/hub" as a library and uses module.
https://github.com/search?q=%22github.com%2Fgithub%2Fhub%22+extension%3Amod&type=Code

**Comment by KateGo520** [comment]
I‘m sorry.It still not work well.
I think you need to tag this commit (e50cc02)[https://github.com/github/hub/commit/e50cc02b1d4085928ef35302c3853f7be6d0923f] with the version (v2.14.3 or others), not just commit to the master.

```
>go get github.com/github/hub@v2.14.2
go: finding github.com/github/hub v2.14.2
go: finding github.com/github/hub v2.14.2
go get github.com/github/hub@v2.14.2: github.com/github/hub@v2.14.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

> go get github.com/github/hub@e50cc02
go: finding github.com/github/hub e50cc02
go: finding github.com/github/hub e50cc02
go get github.com/github/hub@e50cc02: github.com/github/hub@v1.12.3-0.20200418155404-e50cc02b1d40: invalid version: go.mod has post-v1 module path "github.com/github/hub/v2" at revision e50cc02b1d40

> go get github.com/github/hub/v2
go get github.com/github/hub/v2: module github.com/github/hub@upgrade found (v2.11.2+incompatible), but does not contain package github.com/github/hub/v2

> go get github.com/github/hub/v2@e50cc02
go: finding github.com e50cc02
go: finding github.com/github/hub/v2 e50cc02
go: finding github.com/github e50cc02
go: finding github.com/github/hub e50cc02
go: downloading github.com/github/hub/v2 v2.14.3-0.20200418155404-e50cc02b1d40
go: extracting github.com/github/hub/v2 v2.14.3-0.20200418155404-e50cc02b1d40
```

**Comment by mislav** [comment]
@KateGo520 We will release at our own schedule. Until then, are you able to use `github.com/github/hub/v2@e50cc02` to solve your case?

**Comment by KateGo520** [comment]
Yes, it solve my problem for now, I look forward to your release.
