### ISSUE TITLE
cannot import flask from flask

### ISSUE THREAD

**Issue by RexAgarwal** [github/hub#2523]
* Serving Flask app "ap.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "ap", an ImportError was raised:

Traceback (most recent call last):
  File "/mnt/c/project0/project0/FLASK_PROJECT/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/mnt/c/project0/project0/FLASK_PROJECT/ap.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (/mnt/c/project0/project0/FLASK_PROJECT/venv/lib/python3.8/site-packages/flask/__init__.py)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
