### ISSUE TITLE
 connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by bigmonte** [github/hub#2525]
**Command attempted:**
`hub create -p`

git version 2.26.2.windows.1
hub version 2.14.2 (https://chocolatey.org/packages/hub)

**What happened:**
Post https://api.github.com/authorizations: dial tcp 140.82.118.6:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

**More info:**
- It worked fine not long time ago, I use hub for more than 1y with no problems
- I manage all my repos with SSH

Also I hear about this hub in `~/.config/hub` and tried using:

```
github.com:
  user: bigmonte
  oauth_token: GEN_TOKEN
```

Same error. I had never heard about that file until I search about similar issues.

**Comment by mislav** [comment]
@bigmonte Does this happen every time?

It looks like it's related to your system or network. I'm not sure how we could solve this from the hub codebase?

**Comment by bigmonte** [comment]
> 
> 
> @bigmonte Does this happen every time?
> 
> It looks like it's related to your system or network. I'm not sure how we could solve this from the hub codebase?

You're probably right.
Its odd but the issue doesn't happen anymore.
