### ISSUE TITLE
Solr 7.5 Autoscaling history API

### ISSUE THREAD

**Issue by sujithms** [github/hub#2529]
I am using Solr version 7.5. I was asked to capture all the autoscaling events of Solr like the event start time,end time, status..etc. I know they provide these information via the autoscaling history API i.e "http://localhost:8983/solr/admin/autoscaling/history". I had to manually create a collection named ".system" in Solr to get this API functioning. This link https://lucene.apache.org/solr/guide/7_5/blob-store-api.html was followed.

However, there is a weird behavior that I am observing now. This autoscaling history API is not updating the events after a certain point.I am no longer able to view any of the autoscaling events that occurred past this. I tried to delete the ".system" collection and recreated it again. The new autoscaling events were captured but again it stopped after a certain period. Any idea why this is happening. Advise is greatly appreciated.

**Comment by pglenda1967** [comment]
Can i remove it

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
