### ISSUE TITLE
Solr Autoscaling policy for ADDREPLICA is not functioning in Metric Based Triggers

### ISSUE THREAD

**Issue by sujithms** [github/hub#2531]
I am using Solr version 7.5. The Autoscaling policy for ADDREPLICA is not functioning in Metric Based Triggers in this version. The "preferredOperation" was given "ADDREPLICA" for a sample metric trigger and it wasnt functioning. However, the operation MOVEREPLICA was working as expected. Any idea why this is happening? Any help is appreciated.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
