### ISSUE TITLE
Approval Requests actions on IC General Journal - D365 Business Central

### ISSUE THREAD

**Issue by PravinDangar** [github/hub#2533]
I enabled General Journal batch approval workflow and Now I am trying to post IC General Journal transactions. System is asking me to send approval request as workflow is enable and Approval is required. But There is not action on "Inter-company General Journal" to send approval request (as we have on General Journal).

So, My thoughts for the same is :
Either 
Allow to Post IC General Journal even if Workflow is enabled
OR
Provide actions on IC General Journal to process approval requests.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
