### ISSUE TITLE
Retain Quick Setup details in Code tab after source code added.

### ISSUE THREAD

**Issue by Clojurius** [github/hub#2535]
Retain Quick Setup details is useful not only for getting start but also be useful as quick reference in future. 
For example, I setup the first time and add some code, this useful Quick Setup  is no longer available. However if this is retained,  and if someone want to use it, just find it easy to go to Code tab to access it since it is where it is available initially.

Understand that it may look weird to add Quick Setup alongside source code, but it can be added as a button  that when click will Show the Quick Setup details.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/25784630/81443188-8aa73000-91a7-11ea-8d0e-82474f67c5cb.png">

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
