### ISSUE TITLE
please help me java programmers. i want to capitalize 5th,10th,15th,.... character of a string 

### ISSUE THREAD

**Issue by Mamad79sdg** [github/hub#2536]
import java.util.*;
public class String5thChar 
{

    public static void main(String[] args) 
    {
        Scanner input=new Scanner(System.in);
        
        String text = input.nextLine();

              char[] arr = text.toCharArray();
              int count=0;
              for(int i=4;i<=arr.length;i=i+5)
              {

                  arr[i] = Character.toUpperCase(arr[i]);
                  String str = new String(arr);
                  int a=((arr.length)/5)+((arr.length)%5);
                  if(count!=a-1)
                  {
                      
                  } 
                  else 
                  {
                      System.out.println(str);
                      break;
                  }
               count++;
              }
    }
}

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
