### ISSUE TITLE
Signing APK in Azure Devops

### ISSUE THREAD

**Issue by jasonlq007** [github/hub#2537]
I have been trying to make devops build of android apk and my pipeline fails in Signing and aligning Apk Stage.

I am getting the following error

##[error]Error: No matching files were found with search pattern: D:\a\1\s***.apk

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
