### ISSUE TITLE
Associate a specific role to added user

### ISSUE THREAD

**Issue by fabrizioschiano** [github/hub#2538]
I am not sure that this does not exist already in hub but I could not find it. 

**The problem I'm trying to solve:**

I am new to hub and I am adding some users to a repository with the following command
`hub api -X PUT <REPOURL>/"$user"`

**How I imagine hub could expose this functionality:**
I would like to be able also to specify the user's role _Read, Write, Admin etc._
I imagine something like that
`hub api -X PUT --role read <REPOURL>/"$user"`

**Comment by mislav** [comment]
You want this invocation:
```sh
hub api -X PUT repos/:owner/:repo/collaborators/:username -f permission=pull
```

See https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
