### ISSUE TITLE
Connect VL53L0X sensor to MT3620

### ISSUE THREAD

**Issue by millena7** [github/hub#2539]
Hi,

I'm starting to use Azure Sphere MT3620 and I have some doubts.

(1) How could I implement the VL53L0X [Datasheet_VL53L0X.pdf](https://github.com/github/hub/files/4623513/Datasheet_VL53L0X.pdf)
 sensor with MT3620? I already saw the I2C example but this is specific to LSM6DSO accelerometer and I didn't undertand what I need to change.

(2) Is it really necessary to use FTDI Friend to see the output from MT3620 as explained in this page: https://docs.microsoft.com/en-us/azure-sphere/install/development-environment-windows#set-up-hardware-to-display-output?

(3) Could I use micropython to develop my project? If this is possible. Do you have examples using this language?

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
