### ISSUE TITLE
Problem with eeglab, today

### ISSUE THREAD

**Issue by greenehh** [github/hub#2540]
-The only thing that is new is that I downloaded and installed Python, last night.  I've also tried reinstalling eeglab, today.   I'm using Matlab2020A.

eeglab: options file is C:\Users\Harold\eeg_options.m
Retrieving plugin versions from server...
Retreiving download statistics...
Index exceeds the number of array elements (32).

Error in plugin_getweb (line 63)
    plugin(iRow).downloads = stats{2}(iRow);

Error in eeglab (line 914)
        pluginTmp = plugin_getweb('', pluginlist, 'newlist');

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
