### ISSUE TITLE
edited htaccess 

### ISSUE THREAD

**Issue by levani854** [github/hub#2545]
Hi. i edited htaccess code in wordpress yoast plugin.  My website has gone, internal error 500.
and now i get error 522.
trying to connect server via ftp client but it shows up error too. i use winscp. how can i get to htaccess file and recover. why i can t connect to server?
hosting digital ocean ubuntu droplet.

![1](https://user-images.githubusercontent.com/63841739/82308765-4c91e380-99d3-11ea-9a1a-4723b0e0a082.png)
![2](https://user-images.githubusercontent.com/63841739/82308771-4e5ba700-99d3-11ea-874d-7eafa2a94ea3.jpeg)
![1Untitled](https://user-images.githubusercontent.com/63841739/82308772-4e5ba700-99d3-11ea-806c-0f3b9044f495.png)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
