### ISSUE TITLE
how to share apk file in my flutter app (sending app itself)

### ISSUE THREAD

**Issue by Rezayzdni** [github/hub#2546]
I'm using flutter platform and i want to implement an option in my app  in order to share the app(apk file)  itself using share methods.
how can i do that?

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.

**Comment by jishnuraj-generals** [comment]
> I'm using flutter platform and i want to implement an option in my app in order to share the app(apk file) itself using share methods.
> how can i do that?

Hello there I am having the same trouble. As this is not the right place to discus about this issue, if you had asked this question in any other community like stackoverflow then can you please share its link?
Thank youo
