### ISSUE TITLE
Topic Search

### ISSUE THREAD

**Issue by rainmaker6** [github/hub#2551]
Whenever we go through topic section and choose one option for information and return to the topic tab the page get reloads and dosen't save the past state ie. We need to scroll down again to find the topic where we left.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
