### ISSUE TITLE
hub pull-request assuming the wrong branch

### ISSUE THREAD

**Issue by wasims1** [github/hub#2554]
**Command attempted:**
hub pull-request 

**What happened:**
it is assuming the wrong branches. i have a local branch just pushed to 'origin', i confirmed that it's set to track the remote branch. i do hub pull-request and it shows me the wrong branch... I read in the forums about the same issue happening to other but it was suggested to ensure local branch is tracking by doing a push & track remote branch... i'm still getting the wrong branches despite that... 

Any definitive solution? this is a wonderful tool; and this has ruined it for me...

**More info:**

**Comment by simms11** [comment]
The set-upstream command is used to track changes between your remote branch and your local branch:
 git  --set-upstream <remoteBranch> <Localbranch>

#to view your current remote branch:
$ git remote -v
Displays:
> origin  https://github.com/OWNER/REPOSITORY.git (fetch)
> origin  https://github.com/OWNER/REPOSITORY.git (push)
> destination  https://github.com/FORKER/REPOSITORY.git (fetch)
> destination  https://github.com/FORKER/REPOSITORY.git (push)

#to remove your origin branch:
$ git remote rm destination

# Set a new remote
$ git remote add origin https://github.com/user/repo.git

**Comment by mislav** [comment]
@wasims1 Sorry for the bad experience!

You may explicitly specify the head and base branches like so:

```
hub pull-request --base main -head mybranch
```
