### ISSUE TITLE
completion for bash does not complete `hub pull-request`

### ISSUE THREAD

**Issue by Self-Perfection** [github/hub#2555]
**Command attempted:**
Typed `hub pull-<Tab>`

**What happened:**
Command is not completed

**More info:**
Arch linux
```
$ hub --version
git version 2.26.2
hub version 2.14.2
```

**Comment by mislav** [comment]
Sorry for the trouble! I think bash completions are broken unless you `alias git=hub` https://github.com/github/hub/issues/1792
