### ISSUE TITLE
The unit is below the required distance.

### ISSUE THREAD

**Issue by ilyapishchulin** [github/hub#2556]
**Command attempted:**
Scroll in PR.

**What happened:**
The block leaves extra distance.

**More info:**
Safari Version 13.0.5 (15608.5.11)
<img width="1414" alt="Снимок экрана 2020-06-02 в 14 57 40" src="https://user-images.githubusercontent.com/45998835/83517377-7540cf80-a4e1-11ea-9d54-4dd8259ac895.png">

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
