### ISSUE TITLE
~/.config/hub file missing

### ISSUE THREAD

**Issue by gobater** [github/hub#2558]
I have just downloaded and tested Hub.
I have configured my github host according to the documentation and tried a simple command.

```
$ hub pr list
github.myorganization.net username: gobater
github.myorganization.net password for gobater (never stored): ******
Must authenticate to access this API.
```

after that, I would expect as stated in the documentation that my username would be stored in the config file `~/.config/hub`. However, the file has not been created.

```
$ ls -l ~/.config
total 0
drwxr-xr-x 0 Q296039 1049089 0 Nov 25  2019 git
```

Basically I am willing to know the format of the file to store my github token there (instead of providing it via environment variable) but I have not been able to find any documentation on the config file.

I have also tried to set the environment variable HUB_CONFIG, but it does not help. The file is emply after executing the command.

I am using hub in windows.
```
$ hub version
git version 2.26.1.windows.1
hub version 2.14.2
```

**Comment by gobater** [comment]
Thanks to https://github.com/github/hub/issues/1488 I found out how to solve my issue. However, there is still a bug since the file has not been created/updated

**Comment by mislav** [comment]
@gobater This line of output makes me think that the authentication was not successful:
```
Must authenticate to access this API.
```

When authentication is not successful, no token will be stored in `~/.config/hub`.

Anyway, I think you've found the format of `~/.config/hub` by now, so I'm going to close this out. 🙇
