### ISSUE TITLE
[Spring-boot] Maven build failure in petclinic app

### ISSUE THREAD

**Issue by ankita2807** [github/hub#2559]
While building maven project,build is failing.
Attached the error log for reference
[build-failure-error.txt](https://github.com/github/hub/files/4729604/build-failure-error.txt)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
