### ISSUE TITLE
Make install not working in ubuntu  WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by Donaldpherman** [github/hub#2561]
Hi, can I get some help with my install issue?

Thanks,

~/downloads/hub$ make install
script/build -o bin/hub
main.go:10:2: cannot find package "github.com/github/hub/v2/commands" in any of:
        /usr/lib/go-1.10/src/github.com/github/hub/v2/commands (from $GOROOT)
        /home/donaldpherman/go/src/github.com/github/hub/v2/commands (from $GOPATH)
main.go:11:2: cannot find package "github.com/github/hub/v2/github" in any of:
        /usr/lib/go-1.10/src/github.com/github/hub/v2/github (from $GOROOT)
        /home/donaldpherman/go/src/github.com/github/hub/v2/github (from $GOPATH)
main.go:12:2: cannot find package "github.com/github/hub/v2/ui" in any of:
        /usr/lib/go-1.10/src/github.com/github/hub/v2/ui (from $GOROOT)
        /home/donaldpherman/go/src/github.com/github/hub/v2/ui (from $GOPATH)
Makefile:51: recipe for target 'bin/hub' failed
make: *** [bin/hub] Error 1

**Comment by mislav** [comment]
Per our installation instructions, you need at least Go 1.11 to build hub.
