### ISSUE TITLE
Search sort should support grouping by repository

### ISSUE THREAD

**Issue by mP1** [github/hub#2570]
**The problem I'm trying to solve:**

Currently the sort dropdown only has 3 values: 

![image](https://user-images.githubusercontent.com/726970/85912426-c2f5f100-b86f-11ea-944d-697bd56f8772.png)

**How I imagine hub could expose this functionality:**

I would like an extra option to sort by repository, thus grouping all the matches from repos together. I am using the Search to find packages and would like to grasp an idea of which of my projects use that package so i can do some refactoring etc.

Eg java package x.y.z currently gives a lot of matches but stuff isnt grouped so i would have to visit all N matches to record the repos (projects) they belong too, basically manually doing the group by thing. I need this across many of my projects and since theres lots (somewhere around possibly 50) this seemed like something useful for me and others with the same idea.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
