### ISSUE TITLE
Is there an easy way to Switch account?

### ISSUE THREAD

**Issue by codeitlikemiley** [github/hub#2572]
Is there a better way to do when creating multiple repo with multiple user
 
i keep getting this error
``` 
Error creating repository: Not Found (HTTP 404)
Not Found
```

only the first github account would work and all the organization on it...

i hope there is an easy way to switch an account 

like hub auth-switch

FYI 

My ssh config is properly configure , and i can do the normal stuff like pushing and pulling no trouble

only when creating a new repo is that im facing it

im using ssh protocol by default...

Can someone sugguest me an easier way of doing this...

SO i wont need to go to each github account login then logout

then create new repo

**Comment by mislav** [comment]
Hi, there is currently no functionality to easily switch users. You can hack something up yourself:
1. Have two authentication tokens (belonging to separate users) available, then swap the value of GITHUB_TOKEN environment variable around in your shell to switch between users;
2. Store two separate authentication tokens in separate config files (see `~/.config/hub`), then swap the value of HUB_CONFIG when you want hub to use an alternate config file.
