### ISSUE TITLE
Github created a wrong, empty commit when I resolved a conflict.

### ISSUE THREAD

**Issue by NinoM4ster** [github/hub#2573]
I don't know what the hell just happened.

I went to merge a feature branch into the master branch, and after resolving the two conflicts, github created a weird commit, with zero files changed, called "Merge branch 'master' into attendant-registering", which makes zero sense, as the PR was for merging attendant-registering **into** master.

And I also had something similarly weird happen a while ago. I went to resolve a conflict, just like today.. I resolved it, and committed it, but github replaced the entire file, like I changed every single line. except I didn't.

It shouldn't really matter as it's a personal, private project.. but imagine if I was working for a big company and such a mess happened? that wouldn't be cool.

**Comment by vaporyhumo** [comment]
That's just a regular merge commit. You should take a look at git's documentation. https://git-scm.com/docs/git-merge

**Comment by vaporyhumo** [comment]
If you'd like to not have those commits, you should adopt a workflow based on rebasing.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
