### ISSUE TITLE
piiiiiidddddd=0resources1/synth.sh: 15: ../bin/festival: Permission denied

### ISSUE THREAD

**Issue by aryanboss** [github/hub#2575]
**Command attempted:**
perl synth_text.pl "hello"

**What happened:**
piiiiiidddddd=0resources1/synth.sh: 15: ../bin/festival: Permission denied

**More info:**
perl synth_text.pl "hello"
The story to be synthesized is: hello
The output syllable file is: 
The words are : 
Local date and time Sat Jul  4 15:05:35 2020
piiiiiidddddd=0resources1/synth.sh: 15: ../bin/festival: Permission denied
mv: cannot stat 'parser/prompt-utt/test.utt': No such file or directory
Phone "i" not member of PhoneSet "radio"
Phone i not in phone set radio
Phone "i" not member of PhoneSet "radio"
Phone i not in phone set radio
Phone "i" not member of PhoneSet "radio"
Phone i not in phone set radio
Phone "ii" not member of PhoneSet "radio"
Phone ii not in phone set radio
Phone "ii" not member of PhoneSet "radio"
Phone ii not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "sx" not member of PhoneSet "radio"
Phone sx not in phone set radio
Phone "sx" not member of PhoneSet "radio"
Phone sx not in phone set radio
Phone "sx" not member of PhoneSet "radio"
Phone sx not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "bh" not member of PhoneSet "radio"
Phone bh not in phone set radio
Phone "bh" not member of PhoneSet "radio"
Phone bh not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "i" not member of PhoneSet "radio"
Phone i not in phone set radio
Phone "i" not member of PhoneSet "radio"
Phone i not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "ii" not member of PhoneSet "radio"
Phone ii not in phone set radio
Phone "ii" not member of PhoneSet "radio"
Phone ii not in phone set radio
Phone "ee" not member of PhoneSet "radio"
Phone ee not in phone set radio
Phone "ee" not member of PhoneSet "radio"
Phone ee not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "a" not member of PhoneSet "radio"
Phone a not in phone set radio
Phone "h" not member of PhoneSet "radio"
Phone h not in phone set radio
Phone "h" not member of PhoneSet "radio"
Phone h not in phone set radio
Phone "h" not member of PhoneSet "radio"
Phone h not in phone set radio
Phone "h" not member of PhoneSet "radio"
Phone h not in phone set radio
Phone "h" not member of PhoneSet "radio"
Phone h not in phone set radio
/bin/sh: 10: gawk: not found
/bin/sh: 11: gawk: not found
make: *** [Makefile:188: label] Error 127
cut: labels/full/test.lab: No such file or directory
resources1/synth.sh: 28: ./bin/hts_engine: not found
rm: cannot remove 'gen/hts_engine/*.raw': No such file or directory
rm: cannot remove 'pranaw.txt': No such file or directory

at0# Extracting monophone and fullcontext labels from utterance files
mkdir -p labels/mono
mkdir -p labels/full
for utt in utts/*.utt; do \
	base=`basename ${utt} .utt`; \
	if [ -s ${utt} ]; then \
		/home/aryan/Downloads/festival/examples/dumpfeats    -eval     scripts/extra_feats.scm \
				-relation Segment \
				-feats    scripts/label.feats \
				-output   tmp \
				${utt}; \
	fi; \
	gawk -f scripts/label-full.awk tmp > labels/full/${base}.lab; \
	gawk -f scripts/label-mono.awk tmp > labels/mono/${base}.lab; \
done

at1mv: cannot stat 'resources1/test.wav': No such file or directory
normalize-audio: file out/*.wav: No such file or directory
normalize-audio: no files!
Cannot open file out/*.wav as tokenstream
Wave load: can't open file "out/*.wav"
Cannot recognize file format or cannot access file: "out/*.wav"
play WARN alsa: can't encode 0-bit Unknown or not applicable
play FAIL formats: can't open input file `out.wav': No such file or directory

**Comment by aryanboss** [comment]
How to solve permission denied issue ?

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
