### ISSUE TITLE
hub api doesn't use the correct endpoint for enterprise hosts

### ISSUE THREAD

**Issue by benknoble** [github/hub#2576]
**Command attempted:**

```bash
GITHUB_HOST=$WORK_GITHUB hub api --method POST /repos/some-owner/some-repo/forks
```

**What happened:**

The request was erroneously made to `$WORK_GITHUB/repos/...` and not `$WORK_GITHUB/api/v3/repos/...`, causing it to fail. I discovered this by setting `HUB_VERBOSE` after seeing the failure.

I was able to work around the issue (https://github.com/benknoble/Dotfiles/blob/d26cc54eac0a3fd511fdf762cf3cab90e4e580ef/links/bin/git-fork-repo#L41), but it's ugly. After browsing, I thought hub had fixed this (https://github.com/github/hub/blob/e50cc02b1d4085928ef35302c3853f7be6d0923f/github/client.go#L1057), but it appears not.

**More info:**

```
# hub version
git version 2.27.0
hub version 2.14.2
# archey

                 ###                   
               ####                    
               ###                    Distro: OS X 10.15.5
       #######    #######             Kernel: Darwin
     ######################            
    #####################             Shell: /usr/local/bin/zsh
    ####################              Terminal: tmux-256color 
    ####################              CPU: Intel Core i9-9980HK CPU @ 2.40GHz
    #####################             Memory: 16 GB
     ######################            
      ####################             
        ################               
         ####     #####               
```

You can probably use the `GET` method on that endpoint for easier reproduction.

**Comment by mislav** [comment]
@benknoble The trick is to avoid using the leading slash. So instead of:
```sh
# no!
hub api /repos/...
```
you would do
```sh
# yesss
hub api repos/...
```

The leading slash is a mechanism for explicitly requesting a resource from the "root" of a domain.
