### ISSUE TITLE
Mobile Metamask Browser problem 

### ISSUE THREAD

**Issue by surya321123** [github/hub#2578]
**Command attempted:**
Mobile Metamask Browser problem  Jquery Issues

**What happened:**
In **Mobile Metamask Browser** Jquery validation required working fine, but in **SubmitHandler** not working,  But Chrome and other browsers is working fine

**More info:**
Need solution for the problem

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
