### ISSUE TITLE
`hub clone` dose not work well

### ISSUE THREAD

**Issue by Freakwill** [github/hub#2584]
**Command attempted:**
`hub clone somerepo` 

**What happened:**
did not work, and displayed the permission error

**More info:**
Under macOS

I like the clt, since it help me shorten the commands, but it dose not work well recently. I don't know the reason.

`git clone https://github.com/Me/somerepo`  OK
`hub clone https://github.com/Me/somerepo`  OK
but
`hub clone Me/somerepo`  dose not work
`hub clone somerepo`  dose not work

and shows the following error
```
cloning to 'life-log'...
Enter passphrase for key '/Users/william/.ssh/id_rsa':
git@github.com: Permission denied (publickey).
fatal: can not read the remote repo.

Check the permission of accession and the existence of repo.
```

**Comment by zzulu** [comment]
hub's clone command use `git/SSH` protocol by default, so you have to check your public SSH keys are added to `Settings > SSH and GPG keys`, or SSH passphrase is correct.

If you want to change default protocol to HTTPS, use this command.
```bash
$ git config --global hub.protocol https
```
