### ISSUE TITLE
MakeMeAdmin Suggestion

### ISSUE THREAD

**Issue by Rushil2468** [github/hub#2586]
MakeMeAdmin is great plugin but if u arnt opped and are let's say Mod rank and if I change to let's say Member rank then u can go back to Mod rank unless u have the perms to setgroup or the Member rank has perms to go to Mod rank(which is dumb). 
What I wish is that the base group is remembered and it will allow one to go back to Mod rank or alternatively it can be that the perms of the mod rank stay just the display shows Member.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
