### ISSUE TITLE
hub release prerelease options

### ISSUE THREAD

**Issue by rogerluan** [github/hub#2590]
**Command attempted:**

Tests:
`hub release edit --draft=false --prerelease -m "" v1.0.0` `--prerelease` option doesn't work.
`hub release edit --draft=false -p -m "" v1.0.0` `-p` option works.
`hub release create --draft=false -p -m "sample" v1.0.0` `-p` option works.
`hub release create --draft=false --prerelease -m "sample" v1.0.0` `--prerelease` option doesn't work.
`hub release create --draft=false --prerelease=true -m "sample" v1.0.0` `--prerelease` option works.

**What happened:**

Looks like the `--prerelease` option is a boolean option. The problem is that it defaults to false when `=true` is not provided, unlikely the draft flag that defaults to true if you omit its value.

**More info:**

Examples:
`-p` assumes `--prerelease=true` (as expected)
`--prerelease=true` assumes `--prerelease=true` (as expected)
`--prerelease=false` assumes `--prerelease=false` (as expected)
omitting this flag assumes `--prerelease=false` (as expected)
`--prerelease` assumes `--prerelease=false` (❌)

Oppose to the behavior seen with the draft flag:
`-d` assumes `--draft=true` (as expected)
`--draft=true` assumes `--draft=true` (as expected)
`--draft=false` assumes `--draft=false` (as expected)
omitting this flag assumes `--draft=false` (as expected)
`--draft` assumes `--draft=true` (as expected)

**Comment by mislav** [comment]
Thank you for reporting! It looks like there is a bug with parsing boolean flag values where one has value and another doesn't (e.g. `--draft=false --prerelease`).

For now you may work around your issue by using `-p` or by passing `--draft=false` after all other boolean flags. 🙇

**Comment by rogerluan** [comment]
Ahh, got it! So if I don't pass `--draft=false`, and pass only `--prerelease`, it should work. Nice catch! I couldn't come up with an explanation to the issue before haha

I tested it and confirmed that that is the current behavior.

Yup, I've worked around this issue by adding explicit value to the boolean flag (i.e. `--prerelease=true`) 👍
