### ISSUE TITLE
hub release create: mkdir H:: The system cannot find the path specified

### ISSUE THREAD

**Issue by LoaderB0T** [github/hub#2594]
**Command attempted:**
hub release create 0.1.3 --draft --commitish 5d8f1a76753a6fe9c42ecee3c5f8e7e075504715 -m "message"

**What happened:**
I receive the error message:
`mkdir H:: The system cannot find the path specified.`

**More info:**
git version 2.28.0.windows.1
hub version 2.14.2
Windows 10 1903
Setting HUB_VERBOSE=1 does not provide additional information.
The tag 0.1.3 exists in the repository. (You can find the repo [here](https://github.com/awdware/gah))

Am I missing something? I don't even have a drive "H" or any drive other than "C". I tried setting "CF_HOME" and "HOMEDRIVE" to "C:\tmp" and "C" respectively, without knowing what I'm doing, but nothing changed.

Any ideas?

**Comment by mislav** [comment]
Hi, thank you for reporting!

Can you check all of these environment variables: HOME, HOMEDRIVE, HOMEPATH, USERPROFILE

If nothing else works, can you generate a Personal Access Token at https://github.com/settings/tokens and pass it as `GITHUB_TOKEN=**** hub release ...` and see if that circumvents the issue? This is not meant to be a permanent solution; just a debugging technique to narrow this down.

**Comment by LoaderB0T** [comment]
Thanks for the reply, setting the `USERPROFILE` var seems to have fixed the issue.

**Comment by JenCrawford** [comment]
Hi,
I'm getting this same issue. 
I have no environment variables set for: HOME, HOMEDRIVE, HOMEPATH, USERPROFILE - what are they meant to be?
(both installed myself and via chocolaty)

Setting GITHUB_TOKEN does nothing.
