### ISSUE TITLE
Trying to get the Status code from browser network Tab

### ISSUE THREAD

**Issue by lmk07** [github/hub#2595]
Hi buddy, 
               i'm trying to get the details from the browser network tab, like Name, Type ,Status Code etc. im using Javascript to fetch.  im able to get the resource name using performance.getEntries("resource"). but not able to get the status code. need a help from u guys. Thanks in advance.
![Capture](https://user-images.githubusercontent.com/66107540/90328141-c8da9980-dfb7-11ea-8228-75cdf1f7d404.JPG)

**Comment by jadsonjakus** [comment]
Hi, sorry but I'm not able to used languages I'm new in programming and
study just python and java only.
Goodluck with your work.

Em dom, 16 de ago de 2020 03:29, lmk07 <notifications@github.com> escreveu:

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
