### ISSUE TITLE
During code review of pull request some lines of code were not visible.

### ISSUE THREAD

**Issue by NavneetBarwal** [github/hub#2596]
**Command attempted:**
git push --force was the last command executed.

**What happened:**
When I am reviewing the code on github for a pull request i was not able to see complete changes done in commit for which pull request is generated . But i can see the changes if i checkout the branch of the pull request freshly from remote.
This is some serious issue as i could have missed the changes which were required to get reviewed. It can be seen that git is not showing the code between line number **33231 to 33282** as attached in the screenshot.

**More info:**
Ubuntu 16.0.4 LTS.
![githubissue](https://user-images.githubusercontent.com/32388136/90676016-eab67380-e278-11ea-8603-0f8ae7fd7218.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!

**Comment by NavneetBarwal** [comment]
ok thank you for your answer.
