### ISSUE TITLE
Converting 2D grid to 3D objects in Revit

### ISSUE THREAD

**Issue by LJNorcon** [github/hub#2599]
Hey geeks,
wondeirng if anyone used FME or Dynmo to convert 2D ceiling grids to 3D objects?
The idea is to create grid objects and cut the ceiling plates by grid objects and number them.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
