### ISSUE TITLE
Merge by pr number in hub-merge

### ISSUE THREAD

**Issue by ajdubovoy** [github/hub#2600]
**The problem I'm trying to solve:**
I frequently use `hub-merge` to merge pull requests, as I find it more convenient than going into the web interface. Currently `hub-merge` requires you give it the whole URL of a pull request in order to run the merge. I imagine it would not be difficult to also allow to merge by pull request number, which would be a much simpler UX.

**How I imagine hub could expose this functionality:**
Existing: `hub merge https://github.com/jingweno/gh/pull/73`
Proposed: `hub merge --pull 73`
Alternative: `hub merge -pr 73`
(Unfortunately, `-p` is already used by `git-merge`, so that wouldn't be a viable solution for those who alias `hub` and `git`)

**Comment by mislav** [comment]
In the current master branch you can already do `hub pr merge 73` to merge a PR by its number: https://github.com/github/hub/pull/2280

This feature is unreleased, but will be present in the next release. Stay tuned!
