### ISSUE TITLE
To call the hook at the time of git merge message.

### ISSUE THREAD

**Issue by Meet116** [github/hub#2603]
I want to restrict the GitHub merge message with no leading special character. Is there is any hook we can call at the time of git merge ?

**Comment by mislav** [comment]
If you are talking about the `hub merge <URL>` command: this calls `git merge` internally and you can read `git help githooks` for information about how to set up a `pre-merge-commit` hook. A git hook needs to be set up individually for every local clone of the repository.

If you are talking about the Merge button functionality in GitHub.com web interface, then no; there is no hook that can be configured there.
