### ISSUE TITLE
Missing scan barcode camera in sales invoice

### ISSUE THREAD

**Issue by Revathi1230** [github/hub#2608]
`
![Scan barcode](https://user-images.githubusercontent.com/70802934/92304101-b640f800-ef98-11ea-98e7-82d706135ab8.png)
**Command` attempted:**

**What happened:**
There is a no scan barcode camera in sales invoice.

**More info:**
Frappe & ERPNext Version 13.0.0 Beta.1

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
