### ISSUE TITLE
Not able to edit label with Firefox browser

### ISSUE THREAD

**Issue by zemian** [github/hub#2611]
Hi, I have FF 80.0.1 (64-bit) running on MacOS. When I tried editing a Label in a Project, the "edit" link does nothing. But when I used a Chrome browser, the edit form appeared. Is this a known issue?

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!

**Comment by zemian** [comment]
Oh okay, sorry about that. I will check again. Thanks.
