### ISSUE TITLE
Search for issue by criteria

### ISSUE THREAD

**Issue by ScottChapman** [github/hub#2614]
**The problem I'm trying to solve:**
Need to be able to find issues that meet specific criteria. Specifically by title, using regexp

**How I imagine hub could expose this functionality:**
Should be able to list issues with title that match a specific regexp

**Comment by mislav** [comment]
Sorry, searching titles by regexp is not available through hub nor by GitHub API. It is not likely that we can add this feature.

However, you can list all open issues in a repository and search the titles by regexp in your own script:
```sh
# list a maximum of 9999 open issues by printing issue number + title
$ hub issue -f '%I %t%n' -L9999
```
