### ISSUE TITLE
Cannot create a PR: Cannot read property 'insertAdjacentElement' of null

### ISSUE THREAD

**Issue by malithmcr** [github/hub#2615]
Not sure if I'm reporting thisin the right place but when i trying to create a PR I get this console error.

<img width="858" alt="Screenshot 2020-09-22 at 18 52 07" src="https://user-images.githubusercontent.com/4549859/93912965-bcf39d00-fd04-11ea-80be-c3e450d5d18c.png">

also the Create Pull Request button is disabled. This works after refreshing few times

<img width="834" alt="Screenshot 2020-09-22 at 18 50 56" src="https://user-images.githubusercontent.com/4549859/93913037-ce3ca980-fd04-11ea-88bb-3dc43bed2ed3.png">

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
