### ISSUE TITLE
Have an option to Choose from one or more github accounts or a login feature and a logout feature

### ISSUE THREAD

**Issue by aravindjaimon** [github/hub#2621]
I use two GitHub accounts in my system when I do hub create the hub is creating in the repo in my work account. to switch between them I need to remove the hub file and then re-auth. is there a fix for it already?

**Comment by mislav** [comment]
@aravindjaimon In the past I've had interest in supporting multiple GitHub accounts in hub https://github.com/github/hub/issues/1300#issuecomment-252871423, but nowadays I don't think that I would have time to develop such a feature. It's simply too complex, and very few people would use it.

I would be open to receive PRs for this, though. But in the interest in closing duplicate issues, please follow the other thread in the meantime. 🙇
