### ISSUE TITLE
Serious problem

### ISSUE THREAD

**Issue by Aniket41** [github/hub#2624]
![Screenshot_2020-10-02-00-54-21-18_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/72198393/94854581-c25e8f00-044a-11eb-8c51-7e7a66c0544a.jpg)
**The problem I'm trying to solve:**

**How I imagine hub could expose this functionality:**

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
