### ISSUE TITLE
How to display the data from the api response in flutter if its not in array format

### ISSUE THREAD

**Issue by jaganpsjaganps** [github/hub#2627]
**The problem I'm trying to solve:**

I have problem in displaying the response data in flutter and i am not able to display it without list format
**How I imagine hub could expose this functionality:**

{"code":200,"status":"success","data":{"idstudent_parent":"ddsbh","father_name":"scs JOHN","father_mobile":"s","fatheas"car_occupation":"BUSINESS","f_edu":"Graduate","mother_name":"RcscUBYczsczscMARIAAcscMMA SAMUEL","mother_mobile":"s","massacaother_occupation":"HOME MAKER","m_edu":"Graduate","annual_income":"0","landline_number":"sacscas","is_status":"0","sms_mobile":"scas99","f_email":"a@gwdasmail.com","m_email":"dadas@gmail.com","notification_email":"awfwafca@gmail.com","f_res_addr":"FLAT NO A2, GRACE PALAC","m_res_addr":"NA","f_office_addr":"ADDAX LOGISTICS , , NETTOR","m_office_addr":"NA","user_type":"parent","user_role":"parent","curr_date":"2020-10-02","curr_time":"18:13:27 PM"}}

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
