### ISSUE TITLE
Woocommercce product data table is not working

### ISSUE THREAD

**Issue by Tagor123** [github/hub#2628]
Hello there. Please help me.

I am developing a WordPress woo commerce site. and some some days product data table is not working . data table is showing here: https://prnt.sc/utwcpn  in the sidebar of thew edit page. but is is not the correct place to show the product data table. also i have added short description, and in the edit page, short description is not showing. I can not understand what is the problem. But it was fine about 10 days ago. all was working fine. and i didn't change anything or didn't do any code etc. 

**Note**: i have disabled all plugin, disabled the existing theme and added default theme. but nothing is working. so it is not theme or plugin conflict issue. :(

Please help me as soon as possible. I am in huge trouble.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
