### ISSUE TITLE
The folders....

### ISSUE THREAD

**Issue by Oct4viosZ** [github/hub#2629]
I know this with gambiarras(Technical Resoures) like these:
<p>
- "/" in the file name;
<p>
-Import from git;
<p>
it is possible to create folders inside the git-hub, but it could be better
<p>
So my request is, please could you really create a decent system for creating folders for Git-hub users.
<p>
Please put a button, a real interface, I know that the Absence of this functionality is not of great Issue, but it could be better
<p>
<p>
-Oct4viosZ-

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
