### ISSUE TITLE
Kube-hunter

### ISSUE THREAD

**Issue by varshabhijeet** [github/hub#2635]
I have installed kube-hunter on gke cluster ,but when i hit command kube-hunter and select option 1 ,in that i  have put ip of node which getting from from kubectl get nodes -o wide .Then it gives error cluster not found. If create pod and checked logs of kube-hunter that method works fine .
![image](https://user-images.githubusercontent.com/47491842/95954402-e04bcc80-0e18-11eb-9d05-9be00781867f.png)
![image](https://user-images.githubusercontent.com/47491842/95954432-eb066180-0e18-11eb-8897-5e7ad022c52b.png)
![image](https://user-images.githubusercontent.com/47491842/95954450-f5286000-0e18-11eb-85e2-d488a48a7d73.png)
![image](https://user-images.githubusercontent.com/47491842/95954476-ffe2f500-0e18-11eb-8a13-02ca18058d9e.png)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
