### ISSUE TITLE
hi i want to how i can disenable my onstepcontinue button after my users have mark their vote on  steprequired3 on flutter

### ISSUE THREAD

**Issue by Eden-shisso** [github/hub#2640]
@override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Consumer<VoteState>(builder: (builder, voteState, child) {
              return Container(
                child: Column(
                  children: <Widget>[
                    if (voteState.voteList == null)
                      Container(
                        color: Colors.lightBlue,
                        child: Center(
                          child: Loading(
                              indicator: BallPulseIndicator(), size: 100.0),
                        ),
                      ),
                    if (voteState.voteList != null)
                      Expanded(
                        child: Stepper(
                          type: StepperType.horizontal,
                          currentStep: _currentStep,
                          steps: [
                            getStep(
                              title: 'Choose',
                              child: VoteListWidget(),
                              isActive: true,
                            ),
                            getStep(
                              title: 'Vote',
                              child: VoteWidget(),
                              isActive: _currentStep >= 1 ? true : false,
                            ),
                          ],
                          onStepCancel: () {
                            if (_currentStep <= 0) {
                              voteState.activeVote = null;
                            } else if (_currentStep <= 1) {
                              voteState.selectedOptionInActiveVote = null;
                            }

                            setState(() {
                              _currentStep =
                              (_currentStep - 1) < 0 ? 0 : _currentStep - 1;
                            });
                          },
                          onStepContinue: () {
                            if (_currentStep == 0) {
                              if (step2Required(voteState)) {
                                setState(() {
                                  _currentStep = (_currentStep + 1) > 2
                                      ? 2
                                      : _currentStep + 1;
                                });
                              } else {
                                showSnackBar(
                                    context, 'Please select a vote first!');
                              }
                            } else if (_currentStep == 1) {
                              if (step3Required(voteState)) {
                                // submit vote
                                markMyVote(voteState);

                                // Go To Result Screen
                                Navigator.pushReplacementNamed(
                                    context, '/result');
                              } else {
                                showSnackBar(context, 'Please mark your vote!');
                              }
                            }
                          },
                        ),
                      ),
                  ],
                ),
              );
            })),
      ),
    );
  }

  bool step2Required(VoteState voteState) {
    if (voteState.activeVote == null) {
      return false;
    }

    return true;
  }

  bool step3Required(VoteState voteState) {
    if (voteState.selectedOptionInActiveVote == null) {
      return false;
    }
    return true;
  }

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
