### ISSUE TITLE
Pull Requests contain already merged commits

### ISSUE THREAD

**Issue by djmilosev** [github/hub#2641]
Hi, is there a way to force the Pull Requests in Github to display only the commits that are to be merged and not the ones that have already been merged?

I'm using the workflow with 3 branches which is described in more details below:

 **Sandbox** 
- Created a feature branch from sandbox
- Made the changes on a feature branch
- Created a pull request against sandbox 
- Merged the changes to sandbox

  **Dev**
-  Created a feature branch from dev 
- Created the pull request to merge feature-sandbox to feature-dev 
- Created a pull request from feature-dev against dev 
- Merged the changes to dev  

**Master** 
- Created a feature branch from master
-  Created the pull request to merge feature-dev to feature-master
-  Created a pull request from feature-master against master
-  Merged the changes to dev  

Result: Pull Requests created from one feature branch to another (for example feature-sandbox to feature-dev) contains the previously merged commits.

Examples:
https://github.com/djmilosev/git-workflow/pull/7
https://github.com/djmilosev/git-workflow/pull/9

Expected behavior is that the PRs doesn't contain already merged commits.

Github repository can be found at the link below:
https://github.com/djmilosev/git-workflow

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
