### ISSUE TITLE
cant push

### ISSUE THREAD

**Issue by kr14official** [github/hub#2642]
**Command attempted:**
git push origin

**What happened:**
Username for 'https://github.com': kr14official
Password for 'https://kr14official@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kr14official/kr14-V.2.0.git/'

**More info:**

**Comment by mislav** [comment]
Please see https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use for instructions how to set up git to authenticate with GitHub servers for clone/push operations.
