### ISSUE TITLE
Jupyter problem 

### ISSUE THREAD

**Issue by Dramakidd** [github/hub#2649]
Hello, im new to programming and i have tried installing jupyter editor. However, after i enter the `jupyter notebook` command in cmd to start it , i click on new and select "Python 3" to start a code, i get a big text saying 500 : Internal Server Error. I'd appreciate it if anyone could help, and if you need more info i'll try my best to provide it.

**Comment by mislav** [comment]
Hi, this issue tracker is for a command-line tool called "hub" which is written in Go and has nothing to do with Python nor Jupyter notebooks. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
