### ISSUE TITLE
The readme mentions "Go 1.11+" for Go version.

### ISSUE THREAD

**Issue by ret394** [github/hub#2650]
The readme mentions "Go 1.11+" for Go version.

Which version of Go is the minimum version?
Which version of Go is the maximum version?

To avoid another issue in this single repo for a simple, short question. 
Which version of make is the minimum version?
Which version of make is the maximum version?

---

Reference
1 https://github.com/github/hub/issues/2616
2 Too much spam about create a new issue in some repos on Github. Maybe even in https://github.com/github. Please fix. 🙏

thanks ret394

**Comment by ret394** [comment]
And thanks for not being careless enough to disable blank, no template issues. Appreciate the huge favour.

Another issue to fix if it's in https://github.com/github. I mean the repos as in repositories.

This comment is verbose due to Github's extremely competent support staff.
---

hiding as it's simpler to read. Just click show.

**Comment by mislav** [comment]
> Which version of Go is the minimum version?

It's Go 1.11+, like our documentation mentions.

> Which version of Go is the maximum version?

There is no maximum Go version. Until today, there was a bug that prevents compiling with Go 1.15, but that was accidental and it's fixed now in the main branch.

> Which version of make is the minimum version?
> Which version of make is the maximum version?

I don't know which versions of `make` are compatible, but in my experience, any GNU make will do.

Closing since I hope your questions have been answered! 🙇

**Comment by ret394** [comment]
>If response is too bad, stop

**Comment by ret394** [comment]
mislav's site

>Follow my hot takes and pretty pictures

hot takes? bruh! you jus parrot stuff and try to fit in. To avoid being hunted by your peers. Don't you? 

I used to be scared to death too. But, like, being scared is overrated.
