### ISSUE TITLE
The incorrect function name of the commit message.

### ISSUE THREAD

**Issue by fpb1386** [github/hub#2662]
The unexpected error of incorrect function name in the commit message.

As an example,
https://github.com/torvalds/linux/commit/2e90ca68b0d2f5548804f22f0dd61145516171e3 
The actual modified function is static void set_fdc(int drive), but the reported function name is static void reset_fdc_info(int mode). 

Another example:
https://github.com/torvalds/linux/commit/d0cb50185ae942b03c4327be322055d622dc79f6
The actual modified function is static int may_create_in_sticky(umode_t dir_mode, kuid_t dir_uid, but the reported function name isstatic int may_linkat(struct path *link).

**Comment by mislav** [comment]
Hi, good catch! But, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
