### ISSUE TITLE
hub create not working - HTTP 404 error

### ISSUE THREAD

**Issue by seanpoconnell** [github/hub#2663]
Hi,

I am having trouble using the command 'hub create' in the cmd to create a repository on Github.
I entered this in the cmd to see the verbose log: HUB_VERBOSE=1 hub create
This is the error I receive:

POST https://api.github.com/authorizations
Authorization: Basic [REDACTED]
{"scopes": ["repo"], "note": "hub for sean@DESKTOP-KV2J8CG", "note_url": "http://hub.github.com/"}
< HTTP 404
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Error creating repository: Not Found (HTTP 404)

These are the system versions:
windows running Linux bash, ubuntu version: 20.04.1
git version: 2.25.1
hub version: 1.12.4

**Comment by mislav** [comment]
Please see https://github.com/github/hub/issues/2655#issuecomment-735836048
