### ISSUE TITLE
Hub create returns Error creating repository: Not Found (HTTP 404) on MacOS

### ISSUE THREAD

**Issue by dogaruemiliano** [github/hub#2667]
**Command attempted:**

`HUB_VERBOSE=1 hub create`

**What happened:**

For password I use a token from <a href="https://github.com/settings/tokens">github.com/settings/tokens</a>
But got a `404 Error`. I tried reinstalling hub, but got the same result. I even factory reseted my PC in the hope it would fix it. 
I also tried github password or the passphrase used for the file generated from the first command in the **more info** section (below), but these return a `401 Error: Bad Credentials`
```
github.com username: dogaruemiliano
github.com password for dogaruemiliano (never stored): 
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes": ["repo"], "note": "hub for emilianodogaru@192-168-0-111.rdsnet.ro", "note_url": "http://hub.github.com/"}
< HTTP 404
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
```
**More info:**

This are the steps I did previous to this problem (from a tutorial)

```bash
mkdir -p ~/.ssh && ssh-keygen -t ed25519 -o -a 100 -f ~/.ssh/id_ed25519 -C "dogaru.emiliano@gmail.com"
```
I was prompted for a passphrase, typed one and pressed enter.

Then I gave my **public** key to GitHub.

```bash
cat ~/.ssh/id_ed25519.pub
```

>\- Copy that text from `ssh` to the end of your email address  
>\- Go to [github.com/settings/ssh](https://github.com/settings/ssh)  
>\- Click on `Add SSH key`  
>\- Fill in the Title with your computer name  
>\- Paste the **Key**  
>\- Finish by clicking on the **Add key** green button.

To check that this step is completed, in the terminal I execute:

```bash
ssh -T git@github.com
```
And get this output:
```
# Hi --------! You've successfully authenticated, but GitHub does not provide shell access
```

Steps from <a href="https://github.com/lewagon/setup/blob/master/macOS.md">this setup tutorial </a>

**Versions**
macOS 11.0.1 (20B50)
git version 2.24.3 (Apple Git-128)
hub version 1.12.4

PS: It might be a bug or I don't know how to use it. I am not experienced with the setup, we only did it once at the beginning of thee bootcamp. I changed my PC and had to do it on my own. Thank you for reading this!

**Comment by mislav** [comment]
Sorry that you're having trouble! For now, the solution is to manually generate a Personal Access Token online to replace the password: https://github.com/github/hub/issues/2655
