### ISSUE TITLE
Does not install on Darwin ARM64 via "brew install hub" w/ Darwin ARM64 version of brew

### ISSUE THREAD

**Issue by mchzimm** [github/hub#2668]
**Command attempted:**
`brew install hub`

**What happened:**
`Building Go cmd/dist using /private/tmp/go-20201210-61415-3ju0m1/go/gobootstrap. ()
./make.bash: line 181: 61464 Segmentation fault: 11  GOROOT="$GOROOT_BOOTSTRAP" GOOS="" GOARCH="" GO111MODULE=off "$GOROOT_BOOTSTRAP/bin/go" build -o cmd/dist/dist ./cmd/dist`

**More info:**
Go(lang) is already compiled and installed for Darwin ARM64 and functioning correctly.

**Comment by iEgit** [comment]
same for me with `brew install hub `

**Comment by mislav** [comment]
Thanks for the report, but `build -o cmd/dist/dist ./cmd/dist` does not appear in hub's build formula, therefore the segfault originates somewhere else in Homebrew.
