### ISSUE TITLE
Insights not highlighting

### ISSUE THREAD

**Issue by pineapplefan1234YT** [github/hub#2669]
**What happened:**
On the Insights page on a repository, the Insights tab is highlighted, but it isn't on the community page only

**Expected:**
The insights page should be highlighted while on insights

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
