### ISSUE TITLE
Are github discussions supported?

### ISSUE THREAD

**Issue by markfirmware** [github/hub#2680]
Particularly opening a discussion with a message.

**Comment by markfirmware** [comment]
Does anyone know if github discussions has an api?

**Comment by mislav** [comment]
Thanks for asking! There's no Discussions API that I'm aware of yet, and Discussions will not be supported in hub core. It's a feature that I feel better belongs in graphical mode (such as on the web) than in the CLI.

**Comment by SoltauFintel** [comment]
Deleting an empty discussions board takes long and results in an unicorn error. At the end it works, but it takes much time.
