### ISSUE TITLE
Review: viewed files bug

### ISSUE THREAD

**Issue by miiu96** [github/hub#2681]
**What happened:**

![image](https://user-images.githubusercontent.com/50499646/103284568-3e358c80-49e4-11eb-9817-a3ceaa07062f.png)

**More info:**

**Comment by miiu96** [comment]
I just did a review and I saw the count of viewed files is negative.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
