### ISSUE TITLE
Webhook 502 error

### ISSUE THREAD

**Issue by sumanth05** [github/hub#2687]
Iam adding webhook for my Jenkins build

Getting 502 error

![IMG_20210105_173045__01](https://user-images.githubusercontent.com/55985114/103671969-a3b7e900-4fa1-11eb-83e4-0726bcafcde0.jpg)
![IMG_20210105_173453__01](https://user-images.githubusercontent.com/55985114/103672177-f85b6400-4fa1-11eb-99df-cc5ee76eb78d.jpg)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
