### ISSUE TITLE
Clicking 'Resolve Conversation' deletes the currently typed comment

### ISSUE THREAD

**Issue by lacymorrow** [github/hub#2688]
**Command attempted:**
In a PR, when a user has commented in a review:
Typing a comment and clicking 'Resolve Conversation' should send the comment, then resolve the conversation.

**What happened:**
The comment is deleted and the conversation resolved.

![image](https://user-images.githubusercontent.com/1311301/103710831-d8f51480-4f6a-11eb-958b-72987677572a.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
