### ISSUE TITLE
What is conv3d_deepnetA_sport1m_iter_1900000?

### ISSUE THREAD

**Issue by Qasimster** [github/hub#2693]
I want to know that what is conv3d_deepnetA_sport1m_iter_1900000. What kind of pre trained model is it? 
Is it a CNN pre trained model. I am just confused. Kindly help

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
