### ISSUE TITLE
Pavlovia does not sync the changes brought to stroop.psyexp file

### ISSUE THREAD

**Issue by mursalayobi** [github/hub#2694]
Hi there,

I am new to Psychopy and Pavlovia; I have used the stroop.psyexp from pavovia and brought changes to it on the builder view in Pscyhopy. However, when I sync it to pavlovia and ran it, pavlovia does not show the chnages brought but only shows the first version of the experiment.

Please let me know what should be done to see the changes on pavlovia; the sync option does not help solving the problem.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
