### ISSUE TITLE
Push succeeded even though login failed.

### ISSUE THREAD

**Issue by Zalarian** [github/hub#2696]
This happened when pushing to a new private repo. The repo was init on the site and then the remote was added via the command line.

**Command attempted:**

git push -u origin main

**What happened:**

I have the GUI installed so after running the command in VS Code's terminal, a login window appeared. I typed in my username wrong which I didn't realize until after I hit enter. The login window disappeared and the terminal got populated with "Logon failed, use ctrl+c to cancel basic credential prompt." and then the regular text associated with a push. I checked my repo on the website and sure enough, it went through.

**More info:**

git version 2.16.2.windows.1

Windows 10 Pro version 10.0.18363 build 18363

"
C:\obfuscated>git push -u origin main
Logon failed, use ctrl+c to cancel basic credential prompt.
Counting objects: 24, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (24/24), 14.49 KiB | 1.61 MiB/s, done.
Total 24 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), done.
To https://obfuscated.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
"

**Comment by mislav** [comment]
Hi, your scenario doesn't seem related to this project at all, since hub doesn't handle `git push` nor git authentication.

You will have to check how HTTPS authentication is set up for you locally. Running `git config --get-regexp credential` might give you a hint.
