### ISSUE TITLE
Bettercap: Cannot set rfmon for this handle AWUS1900

### ISSUE THREAD

**Issue by lluchyluck** [github/hub#2699]
**Command attempted:**
bettercap --iface (in my case wlan0)
When inside bettercap: wifi.recon on

**What happened:**
[err] error while setting interface wlan0 in monitor mode: Cannot set rfmon for this handle

**More info:**
Im using an awus1900 with 88xxau driver, 5.9.0-kali5-amd64.
I dont know whats happening, the driver is ok, monitor mode when enabled with airmon-ng works, but when bettercap tries to enable it shows that msg, i suppose  that the issue is with the bettercap software.
Any ideas??

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
