### ISSUE TITLE
hub 2.7.0 installed on WSL does not authenticate with git-credential-manager

### ISSUE THREAD

**Issue by mloskot** [github/hub#2701]
**Command attempted:**

```
cd ~/boost/libs/gil
git switch develop
git pull origin develop
hub pr list
```

**What happened:**

```
$ hub pr list
github.com username:
```

I'm using `git` on Ubuntu on WSL and it is configured to use the `git-credential-manager.exe`

```
$ git config --get credential.helper
/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe
```

and all Git commands, including push, work fine.

Apparently, `hub` does not use the credentials cached by the Git credential manager.

**More info:**

I'm using Ubuntu 20.04 on WSL on Windows 10.
Git and Hub installed from the Ubuntu packages. 

```
$ hub version
git version 2.30.0
hub version 2.7.0
```

I do realise this is an ancient version of hub, but apparently that is what Ubuntu users are supposed to install as per https://github.com/github/hub/pull/2697

**Comment by FelipeF1198** [comment]
Ttttt

**Comment by mloskot** [comment]
It's the ancient hub version issue, see https://github.com/github/hub/pull/2697#issuecomment-768565653
