### ISSUE TITLE
error: instruction requires: fullfp16

### ISSUE THREAD

**Issue by intwxw** [github/hub#2706]
Macos build ios arm64 static library 

// CMakeLists.txt
--target_compile_options(${LIB_NAME} PRIVATE -march=armv8.2-a+fp16

error: instruction requires: fullfp16
    fmla v16.8h, v1.8h, v24.8h
    ^
 error: instruction requires: fullfp16
    fmla v17.8h, v1.8h, v25.8h
    ^
error: instruction requires: fullfp16
    fmla v18.8h, v1.8h, v26.8h
    ^
error: instruction requires: fullfp16
    fmla v19.8h, v1.8h, v27.8h
    ^
error: instruction requires: fullfp16
    fmla v20.8h, v1.8h, v28.8h
    ^
......

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
