### ISSUE TITLE
[Flatlist in Flatlist] VirtualizedList: You have a large list that is slow to update

### ISSUE THREAD

**Issue by CozmaCatalin** [github/hub#2707]
I have an array of promotions that I render first time using Flatlist and each promotion component is a drop-down menu that show my products , and for render this products I use another Flatlist , so I have a Flatlist inside Flatlist. The problem is that I have this warning : VirtualizedList: You have a large list that is slow to update . I want to mention that all components are React.PureComponent. 

    renderProduct = ({ item, index }) => {
        const { seeProduct, isConnected } = this.props;
        return (
            <ProductContainer
                [...]
            />
        );
    };

    renderItem = ({ item, index }) => {
        const { isOpened } = this.state;
        return (
            <View key={index}>
                [...]
                {isOpened[index] ? (
                    <FlatList
                        data={item.promotions}
                        renderItem={this.renderProduct}
                        initialNumToRender={5}
                        keyExtractor={(item, index) => String(index)}
                        style={styles.flatList}
                    />
                ) : null}
            </View>
        );
    };
    render() {
        const { promotions } = this.props;
        return (
            <FlatList
                data={promotions}
                renderItem={this.renderItem}
                keyExtractor={(item, index) => String(index)}
                style={styles.flatList}
            />
        );
    }

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
