### ISSUE TITLE
can't load en_core_web_sm-2.2.0 package

### ISSUE THREAD

**Issue by HGamalElDin** [github/hub#2711]
**Command attempted:**
I installed en_core_web_sm-2.2.0 package through 
`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
`

**What happened:**
while loading sub-modules of en_core_web_sm-2.2.0 by:
```
import en_core_web_sm 
self.model = en_core_web_sm.load(disable=["tagger", "ner", "parser", "textcat"])
```
i got this error:
> OSError: [E053] Could not read config.cfg from C:\Users\HG\AppData\Roaming\Python\Python38\site-packages\en_core_web_sm\en_core_web_sm-2.2.0\config.cfg

**More nfo:**
Python: 3.8.5

**Comment by cranedroesch** [comment]
I'm having the same problem.  Python 3.6 through the following dockerfile:

```
FROM tensorflow/tensorflow:latest-gpu-jupyter
RUN pip install pandas numpy spacy scispacy scikit-learn scipy configargparse gensim sqlalchemy pymssql pyyaml
RUN python -m spacy download en_core_web_sm
RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.3.0/en_core_sci_md-0.3.0.tar.gz
WORKDIR /usr/src/app
COPY . .
CMD ["dockertest.py"]
ENTRYPOINT ["python"]
```

Then when I run my script, I get 
```
OSError: [E053] Could not read config.cfg from /usr/local/lib/python3.6/dist-packages/en_core_sci_md/en_core_sci_md-0.3.0/config.cfg
```

The TF docker image uses python 3.6, as you can see from the error.

**Comment by HebaGamalElDin** [comment]
> I'm having the same problem. Python 3.6 through the following dockerfile:
> 
> ```
> FROM tensorflow/tensorflow:latest-gpu-jupyter
> RUN pip install pandas numpy spacy scispacy scikit-learn scipy configargparse gensim sqlalchemy pymssql pyyaml
> RUN python -m spacy download en_core_web_sm
> RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.3.0/en_core_sci_md-0.3.0.tar.gz
> WORKDIR /usr/src/app
> COPY . .
> CMD ["dockertest.py"]
> ENTRYPOINT ["python"]
> ```
> 
> Then when I run my script,
> 
> ```
> import spacy
> ...
> self.sci_nlp = spacy.load("en_core_sci_md", disable=['tagger', 'ner'])
> ```
> 
> I get
> 
> ```
> OSError: [E053] Could not read config.cfg from /usr/local/lib/python3.6/dist-packages/en_core_sci_md/en_core_sci_md-0.3.0/config.cfg
> ```

Creating new env with python=3.7 and installing it through
`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz`
Solved the problem for me.

**Comment by cranedroesch** [comment]
I was able to workaround by downgrading spacy to 2.3.5.  In the dockerfile, in my case.

**Comment by gitclem** [comment]
This stupid trick doesn't work:

`touch config.cfg`

I get the error:

`ValueError: [E985] Can't load model from config file: no [nlp] section found.`

So my guess is that the config file is really needed but someone forgot to make it part of the library.

I'm trying to figure out what is supposed to go into this file....

**Comment by UmerTariq1** [comment]
same issue while loading a spacy custom NER model. Code was working till a few days ago.
loading the model the standard way by calling  spacy.load(MODEL_PATH). I am working on colab.
  
============================== Info about spaCy ==============================
spaCy version    3.0.1                         
Location         /usr/local/lib/python3.6/dist-packages/spacy
Platform         Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python version   3.6.9                         
Pipelines        en_core_web_sm (3.0.0)

**Comment by mislav** [comment]
Hi folks, it's nice that you all are sharing solutions and advice… but this is an issue tracker for a command-line tool called `hub` that is written in Go and has nothing to do with Python. Since I have no clue what any of you are talking about and cannot possibly help, I will close this, and advise you to take this issue to a more appropriate forum. 🙇

**Comment by bharath-kumarn** [comment]
use spacy==2.3.2
 thats issue with spacy version

change the spacy version to 2.3.2

**Comment by bharath-kumarn** [comment]
pip install nltk

pip install spacy==2.3.5

pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz

**Comment by chinmay002** [comment]
downgraded spacy to 2.3.5 , worked

**Comment by PradhyumnaJakate** [comment]
![image](https://user-images.githubusercontent.com/95515338/162883961-2c70ea36-3b02-4d42-83a6-39a42aee3326.png)

Hello
getting this error 
any solutions?

tried above mentioned solutions but no luck
