### ISSUE TITLE
P is Not Near To H3

### ISSUE THREAD

**Issue by MarwanWaleed2010** [github/hub#2712]
Could you please help me to fix this code

P is not near to H3 or H2 my skills

Here is the code

Html:
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>PSD2HTML[1]</title>
        <link rel="stylesheet" type="text/css" href="style.css">
    </head>
    <body>

        

        <div class="header"> 
            <div class="slider">
                <div class="container">
                    <div class="intro">
                        <h2>Web &amp; Graphic Designer</h2>
                        <button>Learn More</button>
                    </div>
                </div>
            </div>
            <div class="navbar">
                <div class="container">
                    <h2>el<span>zero</span></h2>
                    <ul>
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Skills</a></li>
                        <li><a href="#">Resume</a></li>
                        <li><a href="#">Testemonial</a></li>
                        <li><a href="#">Portofolio</a></li>
                        <li><a href="#">Contact Me</a></li>
                    </ul>
                </div>
            </div>
        </div>

        
        
        

        <div class="features">
            <div class="container"> 
                <div class="feat">
                    <h2>Values</h2>
                    <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
                    iudicabit nam,te usu virtue placerat.
                    Purto brute disputando cu est,eam disputando cu est</p>

                </div>
                <div class="feat">
                    <h2>Goals</h2>
                    <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
                    iudicabit nam,te usu virtue placerat.
                    Purto brute disputando cu est,eam disputando cu est</p>

                </div>
                <div class="feat">
                    <h2>Hobbies</h2>
                    <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
                    iudicabit nam,te usu virtue placerat.
                    Purto brute disputando cu est,eam disputando cu est</p>

                </div>
            </div>
        </div>

        

        
        
        <div class="about-me">
            <div class="container">
                <div class="image">
                    <img src="pp.jpg" alt="test">
                </div>
                <div class="info">                  
                    <h2>About Me</h2>
                    <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum ne periculis molestiae pri.</p>
                    <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est.</p>
                    <div class="hobbies">
                       
                         
                        
                        <div class="content"> 
                            
                        

                            <div class="icon">
                                <img src="111.jpg" alt="">
                            </div> 

                            
                            
                               

                            <div class="text">
                             <h3>Web Design</h3>
                             <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
                            </div>
                            
                            
                            
                        </div>

                            

                         
                        
                        <div class="content"> 
                            
                        

                            <div class="icon">
                                <img src="111.jpg" alt="">
                            </div> 

                            
                            
                               

                            <div class="text">
                             <h3>Graphics Design</h3>
                             <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
                            </div>
                            
                            
                        
                        </div>

                            

                         
                        
                        <div class="content"> 
                            
                        

                            <div class="icon">
                                <img src="111.jpg" alt="">
                            </div> 

                            
                            
                               

                            <div class="text">
                             <h3>Online Marketing</h3>
                             <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
                            </div>
                            
                            
                            
                        </div>

                            

                         
                        
                        <div class="content"> 
                            
                        

                            <div class="icon">
                                <img src="111.jpg" alt="">
                            </div> 

                            
                            
                               

                            <div class="text" height:30px;>
                             <h3>SEO</h3>
                             <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
                            </div>

                            
                        </div>    
                            
                       </div>
                   </div>    
               </div>
            </div>
        </div>

        
        
        

        <div class="my-skills">
            <div class="container">
                
                <div class="skills">
                    <h2>My Skills</h2>
                    <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,
                       te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est,te usu virtue placerat.Purto
                       eam dicam soluta ei.Vel dicam vivendo accusata ei,cum ne periculis molestiae pri.</p>
                    <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est.</p>
                    <button>Contact Me</button>
                </div>
                <div class="progress">
                    <div class="technique">
                        <h3>PHOTOSHOP</h3>
                        <div>
                            <span style="width:600%"></span>
                        </div>
                        <h3>ILLUSTRATOR</h3>
                        <div>
                            <span style="width:570%"></span>
                        </div>
                        <h3>HTML/CSS</h3>
                        <div>
                            <span style="width:600%"></span>
                        </div>
                        <h3>PHP/MYSQL</h3>
                        <div>
                            <span style="width:450%"></span>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    
    

    

    <div class="resume">
        <div class="container">
            <h2><span>Resume</span></h2>
            <p>Lorem ipsum dolor sit amet,ea doming epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est</p>
            <button>DOWNLOAD RESUME</button>
        </div>
    </div>
    
    

    

    <div class="my-education">
        <div class="container">
            <div class="main">
                <h2>My Education</h2>
                <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. 

Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est.</p>
            </div>
            <div class="exp">
                Some Exp
            </div>
            <div class="clearfix"></div>
            <hr>
            <div class="main">
                <h2>Work experience</h2>
                <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. 

Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est.</p>
            </div>
            <div class="exp">
            Some Exp
            </div>
        </div>
    </div>

    

    

    <div class="testmonial">
        <div class="container">
            <p>“Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam.”</p>
            <h3>John Stone</h3>
        </div>
    </div>
    
    

    

    <div class="portfolio">
        <div class="container">
            <h2>Portfolio</h2>
            <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. </p>
            <div class="our-work">
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
                <div><img src="http://placehold.it/350/333"></div>
            </div>
        </div>
    </div>
    
    

    

    <div class="contact">
        <div class="container">
            <div class="info">
                <h2>Contact Me</h2>
                <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei.</p>
            </div>
            <div class="form">
               Form
            </div>
        </div>
    </div>
    
    

    
    
    <div class="footer">
        <div class="container">
            Copyright &copy; 2014 focal
        </div>
    </div>

    

    </body>
</html>`

Css:
`/* Start Main Rulez */

body {
	background-color:#DDD
}

.container {
	width:1170px;
	margin:auto
}

.clearfix {clear:both;}

/* End Main Rulez */

/* Start Header */

.header .slider {
	background-image:url("slider.png");
	-webkit-background-size:cover; /* CSS3 */
	-moz-background-size:cover; /* CSS3 */
	-o-background-size:cover; /* CSS3 */
	background-size:cover; /* CSS3 */
	height:600px;
}

.header .slider .intro {

    padding-top:200px;
    text-align:center;
    color:#FFF
}

.header .slider .intro h2 {
    margin:0 auto;
    font-size:50px;
    border-top:4px solid #FFF;
    border-bottom:4px solid #FFF;
    padding:5px 0;
}

.header .slider .intro button {
	background:none;
	width:200px;
    margin-top:10px;
    font-size:24px;
    color:#FFFFFF;
    border:2px solid #FFFFFF;
    font-weight:bold;
    padding:10px 30px
}

.header .navbar {
	background-color:#252F31;
	overflow:hidden;
	text-transform:uppercase;
}

.header .navbar h2 {float:left;}

.header .navbar h2 span {color:#2ecc71}

.header .navbar ul {
	list-style:none;
	padding-left:0;
	overflow:hidden;
	float:right;
}

.header .navbar ul li {float:left;color:#FFFFFF;padding:10px}

.header .navbar ul li a {
	color:#FFFFFF;
    text-decoration:none;
}
.header .navbar ul li.active,
.header .navbar ul li a:hover {
    color:#30B576;
}

/* End Header */

/* Start Features */

.features {
	overflow:hidden
}

.features .feat {
	float:left;
	width:33.33333%;
	height:150px;
    
}

.features .feat h2 {}

.features .feat p {
	line-height:1.7;
	color:#888
}

/* End features */

/* Start About Me */

.about-me {
     background-color:#F2F2F2;
     overflow:hidden 
}

.about-me .image {
	float:left;
	width:40%
}

.about-me .image img {width:100%}

.about-me .info {
	float:left;
	width:60%
}

.about-me .info h2 {
	color:#555;
}

.about-me .info > p {
	margin:0 0 10px 40px
}

.about-me .info p:last-of-type {
	margin-top:30px;
}

.about-me .info p {
	line-height:1.6;
	color:#666
}

.about-me .info .hobbies {
	overflow:hidden;
	margin:40px 0 0 40px
}

.about-me .info .hobbies > .content {
	float:left;
	overflow:hidden;
	width:50%
}

.about-me .info .hobbies .content h3 {
	color:#555
    height:30px
}

.about-me .info .hobbies .content .icon {
	float:left;
	width:60px;
   	height:30px
}

.about-me .info .hobbies .content .icon img {
	max-width:100%
}

.about-me .info .hobbies .content .text {
	float:left;
	width:269px;
}

/* End About Me */

/* Start My Skills */

.my-skills {
	padding-top:10px;
	padding-bottom:1000px;
}

.my-skills .skills,
.my-skills .progress {
    width:50%
    height:0%;
    float:left;
}

.my-skills .skills h2 {
	color:#555;
}

.my-skills .skills > p {
	margin:0 0 10px 40px
	line-height:1.6;
	color:#666
}

.my-skills .skills p:last-of-type {
	margin-top:30px;
}

.my-skills .skills button {
	background:none;
	border:3px solid #2DCC70;
	padding:10px 30px;
	color:#2DCC70;
	margin-top:20px;
}

.my-skills .progress .technique {margin-left:1000px;}

.my-skills .progress .technique h3 {
	float:left;
	color:#555;
}

.my-skills .progress .technique div {
	padding-top:50px;
	background-color:#f3f3f3
	height:25px;
}

.my-skills .progress .technique div span {
	background-color:#2DCC70;
	width:1000px;
	height:55px;
	display:block;
}

.my-skills .progress .technique {margin-left:1000px;}

.my-skills .progress .technique h3 {
	float:left;
	color:#555;
}

.my-skills .progress .technique div {
	padding-top:50px;
	background-color:#4e4a4c
	height:105px;
}

.my-skills .progress .technique div span {
	background-color:#2DCC70;
	width:1000px;
	height:55px;
	display:block;
}

/* End My Skills */

/* Start Resume */

.resume {
	background-color:#F2F2F2;
	padding-top:30px;
	padding-bottom:30px;
	text-align:center
}

.resume .container button {
	background:none;
	border:3px solid #2DCC70;
	padding:10px 30px;
	color:#2DCC70;
	margin-top:20px;
}

/* End Resume */

/* Start My Education */

.my-education {
	padding-top:30px;
	padding-bottom:30px;
	overflow:hidden
}

/* End My Education */

/* Start Testmonials */

.testmonial {
	background-color:#F2F2F2;
	padding-top:30px;
	padding-bottom:30px;
	text-align:center
}

/*End Testmonials */

/* Start Portfolio */

.portfolio{
	padding-top:30px;
	padding-bottom:30px;
    text-align:center;
}

.portfolio .our-work{
	overflow:hidden
}

.portfolio .our-work > div {
	float:left;
	width:33.333333%;
	margin-bottom:15px
}

.portfolio .our-work > div img {width:92% margin:10px}
/* End portfolio */

/* Start Contact Me */

.contact {
	background-color:#252F31
}

.contact {
	    overflow:hidden;
}

.contact h2 {color:#FFF}

.contact p {color:#000000}

.contact .info,
.contact .form {
	width:50%
	float:left;
}

/* End Contact Me */

/* Start Footer */

.footer {
	background-color:#191E22;
	color:#000000
	padding:20px 0;
	text-align:center;
}
/* End Footer */`

Fix the problem of my Skills

**Comment by MarwanWaleed2010** [comment]
> Could you please help me to fix this code
> 
> P is not near to H3 or H2 my skills
> 
> Here is the code
> 
> Html:
> `
> 
> <title>PSD2HTML[1]</title>
> ```
>     
> 
>     <div class="header"> 
>         <div class="slider">
>             <div class="container">
>                 <div class="intro">
>                     <h2>Web &amp; Graphic Designer</h2>
>                     <button>Learn More</button>
>                 </div>
>             </div>
>         </div>
>         <div class="navbar">
>             <div class="container">
>                 <h2>el<span>zero</span></h2>
>                 <ul>
>                     <li class="active"><a href="#">Home</a></li>
>                     <li><a href="#">About Us</a></li>
>                     <li><a href="#">Skills</a></li>
>                     <li><a href="#">Resume</a></li>
>                     <li><a href="#">Testemonial</a></li>
>                     <li><a href="#">Portofolio</a></li>
>                     <li><a href="#">Contact Me</a></li>
>                 </ul>
>             </div>
>         </div>
>     </div>
> 
>     
>     
>     
> 
>     <div class="features">
>         <div class="container"> 
>             <div class="feat">
>                 <h2>Values</h2>
>                 <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
>                 iudicabit nam,te usu virtue placerat.
>                 Purto brute disputando cu est,eam disputando cu est</p>
> 
>             </div>
>             <div class="feat">
>                 <h2>Goals</h2>
>                 <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
>                 iudicabit nam,te usu virtue placerat.
>                 Purto brute disputando cu est,eam disputando cu est</p>
> 
>             </div>
>             <div class="feat">
>                 <h2>Hobbies</h2>
>                 <p>Lorem ipsum dolor sit amet,ea doming epicuri untill
>                 iudicabit nam,te usu virtue placerat.
>                 Purto brute disputando cu est,eam disputando cu est</p>
> 
>             </div>
>         </div>
>     </div>
> 
>     
> 
>     
>     
>     <div class="about-me">
>         <div class="container">
>             <div class="image">
>                 <img src="pp.jpg" alt="test">
>             </div>
>             <div class="info">                  
>                 <h2>About Me</h2>
>                 <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum ne periculis molestiae pri.</p>
>                 <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est.</p>
>                 <div class="hobbies">
>                    
>                      
>                     
>                     <div class="content"> 
>                         
>                     
> 
>                         <div class="icon">
>                             <img src="111.jpg" alt="">
>                         </div> 
> 
>                         
>                         
>                            
> 
>                         <div class="text">
>                          <h3>Web Design</h3>
>                          <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
>                         </div>
>                         
>                         
>                         
>                     </div>
> 
>                         
> 
>                      
>                     
>                     <div class="content"> 
>                         
>                     
> 
>                         <div class="icon">
>                             <img src="111.jpg" alt="">
>                         </div> 
> 
>                         
>                         
>                            
> 
>                         <div class="text">
>                          <h3>Graphics Design</h3>
>                          <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
>                         </div>
>                         
>                         
>                     
>                     </div>
> 
>                         
> 
>                      
>                     
>                     <div class="content"> 
>                         
>                     
> 
>                         <div class="icon">
>                             <img src="111.jpg" alt="">
>                         </div> 
> 
>                         
>                         
>                            
> 
>                         <div class="text">
>                          <h3>Online Marketing</h3>
>                          <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
>                         </div>
>                         
>                         
>                         
>                     </div>
> 
>                         
> 
>                      
>                     
>                     <div class="content"> 
>                         
>                     
> 
>                         <div class="icon">
>                             <img src="111.jpg" alt="">
>                         </div> 
> 
>                         
>                         
>                            
> 
>                         <div class="text" height:30px;>
>                          <h3>SEO</h3>
>                          <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est eam dicam soluta ei.Vel dicam vivendo accusata ei,cum </p>
>                         </div>
> 
>                         
>                     </div>    
>                         
>                    </div>
>                </div>    
>            </div>
>         </div>
>     </div>
> 
>     
>     
>     
> 
>     <div class="my-skills">
>         <div class="container">
>             
>             <div class="skills">
>                 <h2>My Skills</h2>
>                 <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,
>                    te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est,te usu virtue placerat.Purto
>                    eam dicam soluta ei.Vel dicam vivendo accusata ei,cum ne periculis molestiae pri.</p>
>                 <p>Lorem ipsum dolor sit amet,ea doming untill epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est.</p>
>                 <button>Contact Me</button>
>             </div>
>             <div class="progress">
>                 <div class="technique">
>                     <h3>PHOTOSHOP</h3>
>                     <div>
>                         <span style="width:600%"></span>
>                     </div>
>                     <h3>ILLUSTRATOR</h3>
>                     <div>
>                         <span style="width:570%"></span>
>                     </div>
>                     <h3>HTML/CSS</h3>
>                     <div>
>                         <span style="width:600%"></span>
>                     </div>
>                     <h3>PHP/MYSQL</h3>
>                     <div>
>                         <span style="width:450%"></span>
>                     </div>
>                 </div>
>         </div>
>     </div>
> </div>
> 
> 
> 
> 
> 
> <div class="resume">
>     <div class="container">
>         <h2><span>Resume</span></h2>
>         <p>Lorem ipsum dolor sit amet,ea doming epicuri iudicabit nam,te usu virtue placerat.Purto brute disputando cu est,eam disputando cu est</p>
>         <button>DOWNLOAD RESUME</button>
>     </div>
> </div>
> 
> 
> 
> 
> 
> <div class="my-education">
>     <div class="container">
>         <div class="main">
>             <h2>My Education</h2>
>             <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. 
> ```
> 
> Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est.
> 
> 
> 
> 
> Some Exp
> 
> 
> 
> 
> ## Work experience
> 
> Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri.
> 
> Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est.
> 
> 
> 
> 
> Some Exp
> 
> 
> ```
> 
> 
> 
> 
> <div class="testmonial">
>     <div class="container">
>         <p>“Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam.”</p>
>         <h3>John Stone</h3>
>     </div>
> </div>
> 
> 
> 
> 
> 
> <div class="portfolio">
>     <div class="container">
>         <h2>Portfolio</h2>
>         <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei, cum ne periculis molestiae pri. </p>
>         <div class="our-work">
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>             <div><img src="http://placehold.it/350/333"></div>
>         </div>
>     </div>
> </div>
> 
> 
> 
> 
> 
> <div class="contact">
>     <div class="container">
>         <div class="info">
>             <h2>Contact Me</h2>
>             <p>Lorem ipsum dolor sit amet, ea doming epicuri iudicabit nam, te usu virtute placerat. Purto brute disputando cu est, eam dicam soluta ei. Vel dicam vivendo accusata ei.</p>
>         </div>
>         <div class="form">
>            Form
>         </div>
>     </div>
> </div>
> 
> 
> 
> 
> 
> <div class="footer">
>     <div class="container">
>         Copyright &copy; 2014 focal
>     </div>
> </div>
> 
> 
> 
> </body>
> ```
> 
> `
> Css:
> `/* Start Main Rulez */
> 
> body {
> background-color:#DDD
> }
> 
> .container {
> width:1170px;
> margin:auto
> }
> 
> .clearfix {clear:both;}
> 
> /* End Main Rulez */
> 
> /* Start Header */
> 
> .header .slider {
> background-image:url("slider.png");
> -webkit-background-size:cover; /* CSS3 _/ -moz-background-size:cover; /_ CSS3 _/ -o-background-size:cover; /_ CSS3 _/ background-size:cover; /_ CSS3 */
> height:600px;
> }
> 
> .header .slider .intro {
> 
> ```
> padding-top:200px;
> text-align:center;
> color:#FFF
> ```
> 
> }
> 
> .header .slider .intro h2 {
> margin:0 auto;
> font-size:50px;
> border-top:4px solid #FFF;
> border-bottom:4px solid #FFF;
> padding:5px 0;
> }
> 
> .header .slider .intro button {
> background:none;
> width:200px;
> margin-top:10px;
> font-size:24px;
> color:#FFFFFF;
> border:2px solid #FFFFFF;
> font-weight:bold;
> padding:10px 30px
> }
> 
> .header .navbar {
> background-color:#252F31;
> overflow:hidden;
> text-transform:uppercase;
> }
> 
> .header .navbar h2 {float:left;}
> 
> .header .navbar h2 span {color:#2ecc71}
> 
> .header .navbar ul {
> list-style:none;
> padding-left:0;
> overflow:hidden;
> float:right;
> }
> 
> .header .navbar ul li {float:left;color:#FFFFFF;padding:10px}
> 
> .header .navbar ul li a {
> color:#FFFFFF;
> text-decoration:none;
> }
> .header .navbar ul li.active,
> .header .navbar ul li a:hover {
> color:#30B576;
> }
> 
> /* End Header */
> 
> /* Start Features */
> 
> .features {
> overflow:hidden
> }
> 
> .features .feat {
> float:left;
> width:33.33333%;
> height:150px;
> 
> }
> 
> .features .feat h2 {}
> 
> .features .feat p {
> line-height:1.7;
> color:#888
> }
> 
> /* End features */
> 
> /* Start About Me */
> 
> .about-me {
> background-color:#F2F2F2;
> overflow:hidden
> }
> 
> .about-me .image {
> float:left;
> width:40%
> }
> 
> .about-me .image img {width:100%}
> 
> .about-me .info {
> float:left;
> width:60%
> }
> 
> .about-me .info h2 {
> color:#555;
> }
> 
> .about-me .info > p {
> margin:0 0 10px 40px
> }
> 
> .about-me .info p:last-of-type {
> margin-top:30px;
> }
> 
> .about-me .info p {
> line-height:1.6;
> color:#666
> }
> 
> .about-me .info .hobbies {
> overflow:hidden;
> margin:40px 0 0 40px
> }
> 
> .about-me .info .hobbies > .content {
> float:left;
> overflow:hidden;
> width:50%
> }
> 
> .about-me .info .hobbies .content h3 {
> color:#555
> height:30px
> }
> 
> .about-me .info .hobbies .content .icon {
> float:left;
> width:60px;
> height:30px
> }
> 
> .about-me .info .hobbies .content .icon img {
> max-width:100%
> }
> 
> .about-me .info .hobbies .content .text {
> float:left;
> width:269px;
> }
> 
> /* End About Me */
> 
> /* Start My Skills */
> 
> .my-skills {
> padding-top:10px;
> padding-bottom:1000px;
> }
> 
> .my-skills .skills,
> .my-skills .progress {
> width:50%
> height:0%;
> float:left;
> }
> 
> .my-skills .skills h2 {
> color:#555;
> }
> 
> .my-skills .skills > p {
> margin:0 0 10px 40px
> line-height:1.6;
> color:#666
> }
> 
> .my-skills .skills p:last-of-type {
> margin-top:30px;
> }
> 
> .my-skills .skills button {
> background:none;
> border:3px solid #2DCC70;
> padding:10px 30px;
> color:#2DCC70;
> margin-top:20px;
> }
> 
> .my-skills .progress .technique {margin-left:1000px;}
> 
> .my-skills .progress .technique h3 {
> float:left;
> color:#555;
> }
> 
> .my-skills .progress .technique div {
> padding-top:50px;
> background-color:#f3f3f3
> height:25px;
> }
> 
> .my-skills .progress .technique div span {
> background-color:#2DCC70;
> width:1000px;
> height:55px;
> display:block;
> }
> 
> .my-skills .progress .technique {margin-left:1000px;}
> 
> .my-skills .progress .technique h3 {
> float:left;
> color:#555;
> }
> 
> .my-skills .progress .technique div {
> padding-top:50px;
> background-color:#4e4a4c
> height:105px;
> }
> 
> .my-skills .progress .technique div span {
> background-color:#2DCC70;
> width:1000px;
> height:55px;
> display:block;
> }
> 
> /* End My Skills */
> 
> /* Start Resume */
> 
> .resume {
> background-color:#F2F2F2;
> padding-top:30px;
> padding-bottom:30px;
> text-align:center
> }
> 
> .resume .container button {
> background:none;
> border:3px solid #2DCC70;
> padding:10px 30px;
> color:#2DCC70;
> margin-top:20px;
> }
> 
> /* End Resume */
> 
> /* Start My Education */
> 
> .my-education {
> padding-top:30px;
> padding-bottom:30px;
> overflow:hidden
> }
> 
> /* End My Education */
> 
> /* Start Testmonials */
> 
> .testmonial {
> background-color:#F2F2F2;
> padding-top:30px;
> padding-bottom:30px;
> text-align:center
> }
> 
> /*End Testmonials */
> 
> /* Start Portfolio */
> 
> .portfolio{
> padding-top:30px;
> padding-bottom:30px;
> text-align:center;
> }
> 
> .portfolio .our-work{
> overflow:hidden
> }
> 
> .portfolio .our-work > div {
> float:left;
> width:33.333333%;
> margin-bottom:15px
> }
> 
> .portfolio .our-work > div img {width:92% margin:10px}
> /* End portfolio */
> 
> /* Start Contact Me */
> 
> .contact {
> background-color:#252F31
> }
> 
> .contact {
> overflow:hidden;
> }
> 
> .contact h2 {color:#FFF}
> 
> .contact p {color:#000000}
> 
> .contact .info,
> .contact .form {
> width:50%
> float:left;
> }
> 
> /* End Contact Me */
> 
> /* Start Footer */
> 
> .footer {
> background-color:#191E22;
> color:#000000
> padding:20px 0;
> text-align:center;
> }
> /* End Footer */`
> 
> could you please help me in my Skills

**Comment by CrandellWS** [comment]
huh? i think you may be barking up the wrong tree but i could be wrong

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
