### ISSUE TITLE
git push failing for a topic_name 

### ISSUE THREAD

**Issue by vabbarap** [github/hub#2713]
Followed these steps:
1)git clone "https://review.trustedfirmware.org/TF-A/trusted-firmware-a" ATF_dcc_timeout_fix
cd ATF_dcc_timeout_fix
2)git checkout -b dcc_console remotes/origin/integration
3)Updated changes
4) git push origin HEAD:refs/for/integration/dcc_console
 ! [remote rejected]     HEAD -> refs/for/integration/dcc_console (branch integration/dcc_console not found)
error: failed to push some refs to 'https://review.trustedfirmware.org/TF-A/trusted-firmware-a'

Getting error saying as branch dcc_console is not found.
But when i run git branch able to see the branch * dcc_console as active.

I was following the same steps before and it was working, not sure what has changed.

I pushed the topic name branch "dcc_console" couple of times.
https://review.trustedfirmware.org/q/topic:%22dcc_console%22

I followed these steps https://developer.trustedfirmware.org/w/tf_a/gerrit-getting-started/

Could you please help to resolve this.

**Comment by mislav** [comment]
Hi, it seems like you have a problem with Gerrit. This issue tracker is for the project called `hub` that is meant to work with the GitHub platform.
