### ISSUE TITLE
Version displays incorrectly of hub in terminal

### ISSUE THREAD

**Issue by JamieCropley** [github/hub#2716]
**Command attempted:**
`brew install hub` then
`hub version`

**What happened:**
Was meant to give version number instead it outputs:
`git version 2.24.3 (Apple Git-128)`
`hub version refs/heads/master`

**More info:**
As above. OS version is Mac OS Big Sur 11.2.2, brew is also latest version as I ran brew update and upgrade before installing. This is on m1 Mac with latest version of brew

If this is not an actual issue, feel free to close, but if you could explain why it displays refs/heads/master and not the version number, that would be great.

**Comment by mislav** [comment]
Thanks for letting me know! 

It's likely due to this https://github.com/github/hub/commit/46d12a8d7beaacd48961d2434884caa153822610. I've naively made that change, forgetting that hub might get built in an environment that sets GITHUB_REF unrelated to hub, such as Homebrew Action runs that build bottles.

**Comment by Some-T** [comment]
Ah great! Many thanks. So I presume that will change on the next push / update of the brew formulae?

**Comment by mislav** [comment]
@Some-T Yes, I will make sure that the bug goes away on the next  release. 👍

**Comment by rudolfs** [comment]
I'm also running into this issue.

```
~ » hub --version
git version 2.29.2
hub version refs/heads/master

~ » brew info hub
hub: stable 2.14.2 (bottled), HEAD
Add GitHub support to git on the command-line
https://hub.github.com/
/usr/local/Cellar/hub/2.14.2 (64 files, 8.9MB) *
  Poured from bottle on 2021-04-08 at 15:41:32
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/hub.rb
License: MIT
==> Dependencies
Build: go ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 3,824 (30 days), 11,923 (90 days), 58,705 (365 days)
install-on-request: 3,733 (30 days), 11,588 (90 days), 55,926 (365 days)
build-error: 0 (30 days)
```

**Comment by Some-T** [comment]
> I'm also running into this issue.
> 
> ```
> ~ » hub --version
> git version 2.29.2
> hub version refs/heads/master
> 
> ~ » brew info hub
> hub: stable 2.14.2 (bottled), HEAD
> Add GitHub support to git on the command-line
> https://hub.github.com/
> /usr/local/Cellar/hub/2.14.2 (64 files, 8.9MB) *
>   Poured from bottle on 2021-04-08 at 15:41:32
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/hub.rb
> License: MIT
> ==> Dependencies
> Build: go ✘
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Caveats
> zsh completions have been installed to:
>   /usr/local/share/zsh/site-functions
> ==> Analytics
> install: 3,824 (30 days), 11,923 (90 days), 58,705 (365 days)
> install-on-request: 3,733 (30 days), 11,588 (90 days), 55,926 (365 days)
> build-error: 0 (30 days)
> ```

I been using it all month without issues, if yours is working I would not worry.

**Comment by SatyaSaiSrijaGottimukkala** [comment]
same issue

(base) ~:$ hub version
git version 2.35.0
hub version refs/heads/master

**Comment by Some-T** [comment]
I stopped using this ages ago, I recommend trying out Github CLI it works way smoother.

**Comment by zenspider** [comment]
poke

**Comment by JamieCropley** [comment]
Why Poke? literally adds nothing. They said it will be fixed, I think the focus is more on GitHub CLI these days if anything.
