### ISSUE TITLE
i can't run the game in engine after name change

### ISSUE THREAD

**Issue by submariwastaken1time** [github/hub#2717]
**Command attempted:**
pressing play

**What happened:**
the game window doesn't show

**More info:**
steps to reproduce: 
#1. rename a working game project
#2. open that project then run the game in the editor
OS: windows

**Comment by mislav** [comment]
/
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
