### ISSUE TITLE
Dark mode not working in Github Trending page

### ISSUE THREAD

**Issue by DanielRamosAcosta** [github/hub#2721]
I've enabled the dark mode at my profile and I see the whole Github site in dark:

![image](https://user-images.githubusercontent.com/11427028/110106829-1119a780-7da2-11eb-92e6-311fb4f1a0a2.png)

...excepting for the trending page:

![image](https://user-images.githubusercontent.com/11427028/110106782-ffd09b00-7da1-11eb-8a83-0e702729b1e3.png)

Cheers! 😄

**Comment by CrandellWS** [comment]
I think there might be a better place for you to post this...

Have a look here: https://github.com/github/feedback/discussions

**Comment by DanielRamosAcosta** [comment]
But... is an issue right? Dark mode is working in the whole website excepting the trending page... But I'll move it if you think so 👍

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!

**Comment by DanielRamosAcosta** [comment]
Oh I see, thanks @mislav
