### ISSUE TITLE
Profile bio change does not appear

### ISSUE THREAD

**Issue by EmirBoyaci** [github/hub#2723]
**Command attempted:**
Profile bio change does not appear if I don't refresh page.

**What happened:**
I've changed my bio today and I found that changed bio is not showing after press "save" button.

https://user-images.githubusercontent.com/59085992/110238571-621ccd80-7f53-11eb-8210-dee846c08ed9.mp4

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
