### ISSUE TITLE
Getting memory leak for flutter web

### ISSUE THREAD

**Issue by SarathSk50** [github/hub#2734]
Im working in flutter web application.I tested memory leak for my web application.But I got memory leak from JSArrayBufferData  variable.So I have created simple sample which contains single button to check whether its too leaking memory.
I got memory leak from that simple sample too.I have attached images for your reference.Kindly give me suggestions to resolve this memory leak.
![Screenshot (6)](https://user-images.githubusercontent.com/74715300/111870797-c5274f00-89ac-11eb-8dfc-bd4d818421b5.png)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
