### ISSUE TITLE
elasticsearch speed comparison issue with sql

### ISSUE THREAD

**Issue by celalpoyraz** [github/hub#2736]
I compare the speed of Sql with ElasticSearch. I have 1.5 million data. But sql query runs faster than elastic search. I don't understand the problem. Why is the word like query coming faster in sql?

My code for Sql

public static List<Sales> GetAllRecords(string itemType)
        {
            List<Sales> salesReports = new List<Sales>();

            string sqlQuery = String.Format(@"SELECT * FROM dbo.Sales  where Region like '%{0}%'", itemType);
            using (SqlConnection connection = new SqlConnection(CONNECTION_STRING))
            {
                var result = connection.Query<Sales>(sqlQuery);
                foreach (var item in result)
                {
                    Sales global = new Sales()
                    {
                        Region = item.Region,
                        Country = item.Country,
                        Item_Type=item.Item_Type,
                        Order_Date=item.Order_Date,
                        Order_ID = item.Order_ID,
                        Order_Priority=item.Order_Priority,
                        Sales_Channel=item.Sales_Channel,
                        Ship_Date = item.Ship_Date,
                        Total_Cost=item.Total_Cost,
                        Total_Profit=item.Total_Profit,
                        Total_Revenue=item.Total_Revenue,
                        Units_Sold=item.Units_Sold,
                        Unit_Cost=item.Unit_Cost,
                        Unit_Price = item.Unit_Price
                    };
                    salesReports.Add(global);
                   
                }
                return result.ToList();
            }
        }

My code for ElasticSearch. I search the data that I indexed before with elasticsearch here.

  public static List<Sales> ConfigureES(string inputText)
            {
                List<Sales> salesReports = new List<Sales>();

                // 1. Connection URL's elastic search
                var listOfUrls = new Uri[]
                {
                    // here we can set multple connectionn URL's...
                     new Uri("http://localhost:9200/")
                };
    
                StaticConnectionPool connPool = new StaticConnectionPool(listOfUrls);
                ConnectionSettings connSett = new ConnectionSettings(connPool);
                ElasticClient eClient = new ElasticClient(connSett);
    
                //  var see = eClient.DeleteIndex(INDEX_NAME);
    
                // check the connection health
                var checkClusterHealth = eClient.ClusterHealth();
                if (checkClusterHealth.ApiCall.Success && checkClusterHealth.IsValid)
                {
                    // 2. check the index exist or not 
                    var checkResult = eClient.IndexExists(INDEX_NAME);
                    if (!checkResult.Exists)
                    {
                        // Raise error to Index not avaliable
                    }
                    // Search particular text field 
                    var searchResponse = eClient.Search<Sales>(s => 
                   s.Index(INDEX_NAME).From(0).Size(5000).Scroll("10m")
                   .Query(q => q.Match(m => m.Field(f => f.Region).Query(inputText))));
    
                    //var results = eClient.Scroll<Salesreport>("10m", searchResponse.ScrollId);
                    while (searchResponse.Documents.Any())
                    {
                        var res = searchResponse.Documents;
                        var sds = res.Cast<Sales>();
                        salesReports.AddRange(sds);
                        searchResponse = eClient.Scroll<Sales>("10m", searchResponse.ScrollId);
                    }
                }
                else
                {
                    // fail log the exception further use
                    var exception = checkClusterHealth.OriginalException.ToString();
                    var debugException = checkClusterHealth.DebugInformation.ToString();
                }
    
                return salesReports;
            }

**Comment by radiospiel** [comment]
@celalpoyraz a) I am pretty sure that this question is posted in the wrong repo. This is about `hub`, an extension to the `git` command line tool. But b) why are you expecting a SQL query to be slower than an Elasticsearchquery? In the end they both select data by a condition, and while Elasticsearch is always(?) properly configured to handle a "starts with word XX" query, a SQL database can be as well, and in that case I would expect both to be on par. (Note that your SQL command exhibits a SQL injection bug.)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
