### ISSUE TITLE
undefined method `retrieve_by_shopify_domain' for #<Class:0x00007fa6f1b428d8> Did you mean? retrieve_connection

### ISSUE THREAD

**Issue by arhumali07** [github/hub#2738]
NoMethodError in ShopifyApp::CallbackController#callback

getting some issue regarding shopify callback. I am trying to install a local app. when i click on install app it just give me this error. Advance apologies for formatting the problem here this bad. newbie here. 

attaching picture of error 
<img width="1278" alt="Screenshot 2021-04-07 at 4 55 45 AM" src="https://user-images.githubusercontent.com/41928489/113825681-b86f6d00-979a-11eb-8f96-22f1091cffa9.png">

My shopify_app.rb is below:

ShopifyApp.configure do |config|
  config.application_name = "#{ENV['app_name_in_store']}"
  config.api_key = "#{ENV['shopify_app_key']}"
  config.secret = "#{ENV['shopify_secret']}"
  config.scope = "#{ENV['app_current_permissions']}"
  config.embedded_app = true
  config.after_authenticate_job = false
  config.api_version = '2021-01'
  config.shop_session_repository = Shop 
  config.allow_jwt_authentication = true
  config.webhooks = [
    {topic: 'app/uninstalled', address: "#{ENV['currenthost']}/notification/app_uninstalled", format: 'json'},
    ]
end

my Gemfile.lock is 
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.5)
      actionpack (= 5.2.5)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.5)
      actionpack (= 5.2.5)
      actionview (= 5.2.5)
      activejob (= 5.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.5)
      actionview (= 5.2.5)
      activesupport (= 5.2.5)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.5)
      activesupport (= 5.2.5)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.5)
      activesupport (= 5.2.5)
      globalid (>= 0.3.6)
    activemodel (5.2.5)
      activesupport (= 5.2.5)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (5.2.5)
      activemodel (= 5.2.5)
      activesupport (= 5.2.5)
      arel (>= 9.0)
    activeresource (5.1.1)
      activemodel (>= 5.0, < 7)
      activemodel-serializers-xml (~> 1.0)
      activesupport (>= 5.0, < 7)
    activestorage (5.2.5)
      actionpack (= 5.2.5)
      activerecord (= 5.2.5)
      marcel (~> 1.0.0)
    activesupport (5.2.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    aws-eventstream (1.1.1)
    aws-partitions (1.441.0)
    aws-sdk-core (3.113.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.43.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.93.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.3)
      aws-eventstream (~> 1, >= 1.0.2)
    bindex (0.8.1)
    bootsnap (1.7.3)
      msgpack (~> 1.0)
    browser_sniffer (1.2.2)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    carrierwave (2.2.1)
      activemodel (>= 5.0.0)
      activesupport (>= 5.0.0)
      addressable (~> 2.6)
      image_processing (~> 1.1)
      marcel (~> 1.0.0)
      mini_mime (>= 0.1.3)
      ssrf_filter (~> 1.0)
    childprocess (3.0.0)
    chromedriver-helper (2.1.1)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.8)
    crass (1.0.6)
    delayed-web (0.4.9)
      rails (>= 3.2.13)
    delayed_job (4.1.9)
      activesupport (>= 3.0, < 6.2)
    delayed_job_active_record (4.1.6)
      activerecord (>= 3.0, < 6.2)
      delayed_job (>= 3.0, < 5)
    dotenv (2.7.6)
    dotenv-rails (2.7.6)
      dotenv (= 2.7.6)
      railties (>= 3.2)
    erubi (1.10.0)
    excon (0.79.0)
    execjs (2.7.0)
    faraday (1.3.0)
      faraday-net_http (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords
    faraday-net_http (1.0.1)
    ffi (1.15.0)
    figaro (1.2.0)
      thor (>= 0.14.0, < 2)
    fog-aws (3.10.0)
      fog-core (~> 2.1)
      fog-json (~> 1.1)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (2.2.3)
      builder
      excon (~> 0.71)
      formatador (~> 0.2)
      mime-types
    fog-json (1.2.0)
      fog-core
      multi_json (~> 1.10)
    fog-xml (0.1.3)
      fog-core
      nokogiri (>= 1.5.11, < 2.0.0)
    font-awesome-rails (4.7.0.7)
      railties (>= 3.2, < 7)
    formatador (0.2.5)
    gibbon (3.4.0)
      faraday (>= 0.16.0)
      multi_json (>= 1.11.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    graphql (1.12.6)
    graphql-client (0.16.0)
      activesupport (>= 3.0)
      graphql (~> 1.8)
    hashie (4.1.0)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    image_processing (1.12.1)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    impressionist (1.6.1)
      nokogiri (~> 1)
    io-like (0.3.1)
    ipaddress (0.8.3)
    iso (0.4.0)
      i18n
    jbuilder (2.11.2)
      activesupport (>= 5.0.0)
    jmespath (1.4.0)
    jquery-minicolors-rails (2.2.6.2)
      jquery-rails
      rails (>= 3.2.8)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-timepicker-rails (1.11.10)
      railties (>= 3.1.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    jwt (2.2.2)
    kaminari (1.2.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.1)
      kaminari-activerecord (= 1.2.1)
      kaminari-core (= 1.2.1)
    kaminari-actionview (1.2.1)
      actionview
      kaminari-core (= 1.2.1)
    kaminari-activerecord (1.2.1)
      activerecord
      kaminari-core (= 1.2.1)
    kaminari-core (1.2.1)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.9.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.0225)
    mini_magick (4.11.0)
    mini_mime (1.1.0)
    mini_portile2 (2.5.0)
    minitest (5.14.4)
    msgpack (1.4.2)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    nio4r (2.5.7)
    nokogiri (1.11.2)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    oauth2 (1.4.7)
      faraday (>= 0.8, < 2.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.9.1)
      hashie (>= 3.4.6)
      rack (>= 1.6.2, < 3)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    omniauth-shopify-oauth2 (2.2.3)
      activesupport
      omniauth-oauth2 (~> 1.5.0)
    pg (0.18.4)
    polaris_view_helpers (1.0.0)
      rails (> 5.1.1)
    public_suffix (4.0.6)
    puma (3.12.6)
    racc (1.5.2)
    rack (2.2.3)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.5)
      actioncable (= 5.2.5)
      actionmailer (= 5.2.5)
      actionpack (= 5.2.5)
      actionview (= 5.2.5)
      activejob (= 5.2.5)
      activemodel (= 5.2.5)
      activerecord (= 5.2.5)
      activestorage (= 5.2.5)
      activesupport (= 5.2.5)
      bundler (>= 1.3.0)
      railties (= 5.2.5)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    rails-i18n (5.1.3)
      i18n (>= 0.7, < 2)
      railties (>= 5.0, < 6)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_db (2.3.1)
      activerecord
      kaminari
      rails (>= 5.0.0)
      ransack (>= 2.3.2)
      simple_form (>= 5.0.1)
      terminal-table
    rails_same_site_cookie (0.1.8)
      rack (>= 1.5)
      user_agent_parser (~> 2.5)
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (5.2.5)
      actionpack (= 5.2.5)
      activesupport (= 5.2.5)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.3)
    ransack (2.4.2)
      activerecord (>= 5.2.4)
      activesupport (>= 5.2.4)
      i18n
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rb-readline (0.5.5)
    redirect_safely (1.0.0)
      activemodel
    regexp_parser (2.1.1)
    ruby-vips (2.1.0)
      ffi (~> 1.12)
    ruby2_keywords (0.0.4)
    ruby_dep (1.5.0)
    rubyzip (2.3.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.1.0)
      railties (>= 5.2.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    sentry-raven (3.1.2)
      faraday (>= 1.0)
    shopify_api (9.4.1)
      activeresource (>= 4.1.0, < 6.0.0)
      graphql-client
      rack
    shopify_app (17.2.1)
      browser_sniffer (~> 1.2.2)
      jwt (~> 2.2.1)
      omniauth-shopify-oauth2 (~> 2.2.2)
      rails (> 5.2.1, < 6.2)
      redirect_safely (~> 1.0)
      shopify_api (~> 9.4)
    simple_form (5.1.0)
      actionpack (>= 5.2)
      activemodel (>= 5.2)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    ssrf_filter (1.0.7)
    terminal-table (3.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thor (1.1.0)
    thread_safe (0.3.6)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.7.0)
    user_agent_parser (2.7.0)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    will_paginate (3.1.8)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk-s3
  bootsnap (>= 1.1.0)
  byebug
  capybara (>= 2.15)
  carrierwave (~> 2.0)
  chromedriver-helper
  coffee-rails (~> 4.2)
  delayed-web
  delayed_job_active_record
  dotenv-rails
  figaro
  fog-aws
  font-awesome-rails
  gibbon
  graphql-client
  impressionist (~> 1.6.1)
  iso
  jbuilder (~> 2.5)
  jquery-minicolors-rails
  jquery-rails
  jquery-timepicker-rails
  jquery-ui-rails
  listen (>= 3.0.5, < 3.2)
  mini_magick
  pg (= 0.18.4)
  polaris_view_helpers
  puma (~> 3.11)
  rack-cors
  rails (~> 5.2.3)
  rails-i18n (~> 5.1)
  rails_12factor
  rails_db
  rails_same_site_cookie
  rb-readline
  sass-rails (~> 5.0)
  selenium-webdriver
  sentry-raven
  shopify_api
  shopify_app
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  will_paginate (~> 3.1.0)

BUNDLED WITH
   2.1.4

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
