### ISSUE TITLE
Problem with upgrading Kubernetes images

### ISSUE THREAD

**Issue by KolodziejczykDenis** [github/hub#2745]
**Command attempted:**

**What happened:**

Hi, I need to update Kubernetes to version 19.9. In the documentation I found the current version of the images:
Images:
rancher/coredns-coredns:1.6.9
rancher/klipper-helm:v0.4.3
rancher/klipper-lb:v0.1.2
rancher/library-busybox:1.31.1
rancher/library-traefik:1.7.19
rancher/local-path-provisioner:v0.0.14
rancher/metrics-server:v0.3.6
rancher/pause:3.1

Also I added rancher/k3d-tools:v4.4.1(I've also tried with 4.3.0 and 4.0.0 versions) and now while im building app on Jenkins following problem occurs:

14:47:58  ++ k3d image import --verbose rancher/k3d-tools:v4.4.1 rancher/coredns-coredns:1.6.9 rancher/klipper-helm:v0.4.3 rancher/klipper-lb:v0.1.2 rancher/library-busybox:1.31.1 rancher/library-traefik:1.7.19 rancher/local-path-provisioner:v0.0.14 rancher/metrics-server:v0.3.6 rancher/pause:3.1 calico/pod2daemon-flexvol:v3.15.0 calico/node:v3.15.0 calico/cni:v3.15.0 calico/kube-controllers:v3.15.0 k8s.gcr.io/pause:3.1 -c dev
14:47:58  DEBU[0000] Selected runtime is 'docker.Docker' on GOOS 'linux/amd64' 
14:47:58  DEBU[0000] Importing image(s) [[rancher/k3d-tools:v4.4.1 rancher/coredns-coredns:1.6.9 rancher/klipper-helm:v0.4.3 rancher/klipper-lb:v0.1.2 rancher/library-busybox:1.31.1 rancher/library-traefik:1.7.19 rancher/local-path-provisioner:v0.0.14 rancher/metrics-server:v0.3.6 rancher/pause:3.1 calico/pod2daemon-flexvol:v3.15.0 calico/node:v3.15.0 calico/cni:v3.15.0 calico/kube-controllers:v3.15.0 k8s.gcr.io/pause:3.1]] from runtime [{}] into cluster(s) [[{Name:dev Network:{Name: External:false} Token: Nodes:[] InitNode:<nil> ExternalDatastore:<nil> KubeAPI:<nil> ServerLoadBalancer:<nil> ImageVolume:}]]... 
14:47:58  INFO[0000] Importing image(s) into cluster 'dev'        
14:47:58  DEBU[0000] Selected image 'rancher/k3d-tools:v4.4.1' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/coredns-coredns:1.6.9' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/klipper-helm:v0.4.3' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/klipper-lb:v0.1.2' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/library-busybox:1.31.1' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/library-traefik:1.7.19' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/local-path-provisioner:v0.0.14' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/metrics-server:v0.3.6' found in runtime 
14:47:58  DEBU[0000] Selected image 'rancher/pause:3.1' found in runtime 
14:47:58  DEBU[0000] Selected image 'calico/pod2daemon-flexvol:v3.15.0' found in runtime 
14:47:58  DEBU[0000] Selected image 'calico/node:v3.15.0' found in runtime 
14:47:58  DEBU[0000] Selected image 'calico/cni:v3.15.0' found in runtime 
14:47:58  DEBU[0000] Selected image 'calico/kube-controllers:v3.15.0' found in runtime 
14:47:58  DEBU[0000] Selected image 'k8s.gcr.io/pause:3.1' found in runtime 
14:47:58  DEBU[0000] Attaching to cluster's image volume 'k3d-dev-images' 
14:47:58  INFO[0000] Starting k3d-tools node...                   
14:47:58  DEBU[0000] Created container k3d-dev-tools (ID: 37f0f2f7177d6cb966e00eeef73d1722dc29b7042cf8a36008e7837e93af5b02) 
14:47:58  DEBU[0000] Node k3d-dev-tools Start Time: 2021-04-16 12:47:57.995929918 +0000 UTC m=+0.259438510 
14:47:58  INFO[0000] Starting Node 'k3d-dev-tools'                
14:47:59  INFO[0001] Saving 14 image(s) from runtime...           
14:47:59  DEBU[0001] Executing command '[./k3d-tools save-image -d /k3d/images/k3d-dev-images-20210416124759.tar rancher/k3d-tools:v4.4.1 rancher/coredns-coredns:1.6.9 rancher/klipper-helm:v0.4.3 rancher/klipper-lb:v0.1.2 rancher/library-busybox:1.31.1 rancher/library-traefik:1.7.19 rancher/local-path-provisioner:v0.0.14 rancher/metrics-server:v0.3.6 rancher/pause:3.1 calico/pod2daemon-flexvol:v3.15.0 calico/node:v3.15.0 calico/cni:v3.15.0 calico/kube-controllers:v3.15.0 k8s.gcr.io/pause:3.1]' in node 'k3d-dev-tools' 
14:48:00  ERRO[0002] Failed to save image(s) in tools container for cluster 'dev' 
14:48:00  ERRO[0002] Failed to import image(s) into cluster 'dev': Exec process in node 'k3d-dev-tools' failed with exit code '1' 
14:48:00  WARN[0002] At least one error occured while trying to import the image(s) into the selected cluster(s) 

**More info:**

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
