### ISSUE TITLE
Repository upload unexpectedly halts on 0kb file.

### ISSUE THREAD

**Issue by StephanLuis** [github/hub#2754]
**Command attempted:**

In github web interface, the drag and drop file upload halts on 0KB files.

**What happened:**

No further files upload, no error message.

**More info:**

github.com, 26/04/2021, chrome on windows 10

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
