### ISSUE TITLE
Source File Finder shortcut `t` no longer works

### ISSUE THREAD

**Issue by joakime** [github/hub#2760]
**Command attempted:**
The <kbd>t</kbd> keyboard shortcut to find files in a source code browsing view is no longer working.

**What happened:**
It used to work, as little as a few days ago.
Verified that it's still a listed keyboard shortcut at https://docs.github.com/en/github/getting-started-with-github/keyboard-shortcuts
Which lists <kbd>t</kbd> as Source Code Browsing > Activates File Finder

**More info:**
Linux, on latest Chrome.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
