### ISSUE TITLE
CI with clang-9 started to fail in all builds (including previously passing ones)

### ISSUE THREAD

**Issue by FrancescoBorzi** [github/hub#2765]
I've described this problem here: https://stackoverflow.com/questions/67537679/clang9-steady-clocknow-causing-timeout-the-monitored-command-dumped-core

You can find all details in that StackOverflow question.

Given that it is failing also in builds that previously were passing, I'm pretty sure it is not a failure in my app but somewhere in the dependencies we install in the GitHub CI build

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
