### ISSUE TITLE
Bulk transfer issues from one repo to the other

### ISSUE THREAD

**Issue by deshetti** [github/hub#2774]
**The problem I'm trying to solve:**
We are trying to merge a few repositories into a monorepo and want to move all the issues from these repositories to the new repo. We are using hub to migrate the issues but it only lets us transfer one issue at a time. Also, it doesn't allow transferring closed issues. We are having to mark the issues as `open` and then `close` them after the transfer to the new repository.

**How I imagine hub could expose this functionality:**
Currently, it is only possible to transfer one issue at a time the `hub issue transfer` command. It would be great if there is a way to migrate all the issues instead of specifying one issue number at a time. By maybe a flag like `--all` which migrates all the issues to the target repository.

Also, allow transfer of closed issues

**Comment by benomatis** [comment]
Just a slight note that this would NOT list all issues, it would only list 30 (the default limit). If you wanted to list all issues, you'd also have to set the `-L, --limit int` flag, see https://cli.github.com/manual/gh_help_reference#gh-issue-list-flags

**Comment by joreg** [comment]
note to self: this is the exact wording of the bulk command that worked for me in a linux bash:
`for i in `gh issue list -s all -L 9999 | awk '{print $1}'`; do gh issue transfer $i foo/bar; echo "$i transferreed"; done`

**Comment by mscottford** [comment]
To avoid errors caused by API limits, I added a `sleep 2` to each iteration:

```
for i in `gh issue list -s all -L 9999 | awk '{print $1}'`; do gh issue transfer $i foo/bar; echo "$i transferred"; sleep 2; done
```
