### ISSUE TITLE
[BUG] Layout width change on scroll

### ISSUE THREAD

**Issue by eduayme** [github/hub#2775]
**Command attempted:**
Scroll down on homepage

**What happened:**
The layout changes on small scroll

**More info:**
MacBook Pro 13', Brave browser Versión 1.25.68 Chromium: 91.0.4472.77

**Behaviour video:**
https://user-images.githubusercontent.com/26260104/120467839-da532d80-c3a0-11eb-9a04-4d6601fbaf44.mp4

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
