### ISSUE TITLE
Default branch and default pull request target as separate things

### ISSUE THREAD

**Issue by j-d-carmichael** [github/hub#2785]
**The problem I'm trying to solve:**
When we set the default to main.. then all PRs default to go into main.
This is a problem as we adhere to gitflow, so PRs normally come from a feature and should always go into develop.

When we set the default to develop, now all PRs auto pick develop to merge into.. however.. at the same time.. now the gitapp keeps saying " main had recent pushes 34 minutes ago [compare and pull request]"... but this is also completely wrong. 

**How I imagine hub could expose this functionality:**
A new setting, different to the default branch. 
You can select a default branch that github defaults to when you create merge requests.

**Comment by ymc9** [comment]
This is a very useful feature and so commonly needed.

**Comment by mislav** [comment]
Hi, this seems to be asking for a new GitHub.com feature, not necessarily for a feature scoped to the hub CLI.

Right now, GitHub.com always defaults to opening the PRs against the default branch (e.g. `main`) for the repository. To suggest that there could be a repository-level setting for the default base of new PRs specifically (separate from the default branch setting), please propose it at https://github.community/
