### ISSUE TITLE
Using curl on git bash, can't connect using https

### ISSUE THREAD

**Issue by LlewellynJones** [github/hub#2786]
'm getting this error when trying to connect to a remote server using curl on git bash:

curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I tried downloading the server's certificate file using

$ openssl s_client -connect :443

And configured git to use the cert file:
$ git config --global --list
http.sslcainfo=D:/certs/cert.pem

But that didn't fix the issue.

I tried:

git config --global http.sslBackend schannel

That didn't work either.

Is there a bug with the latest version of git?

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
