### ISSUE TITLE
GitHub Branch naming standard 

### ISSUE THREAD

**Issue by awscloudarch87** [github/hub#2787]
We have repositories where developers are accessing and creating their own branches.

But we want to apply a rule, where developers can create a fixed/standard or defined naming convention, not like their own branch names.

They shouldnt not create any branch names other than what we have defined.

Can someone please suggest me how can we achieve this.

Thanks in Advance.

**Comment by mislav** [comment]
Hi, your question is a more general question about version control, while this issue tracker is for discussing features and bugs of a command-line tool called "hub" which doesn't aim to solve this question.

My personal opinion is that your team should come up with your own standard and stick to it!
