### ISSUE TITLE
instrumentation tests uses: reactivecircus/android-emulator-runner@v2 failing - Error: Timeout waiting for emulator to boot.

### ISSUE THREAD

**Issue by gsubu-kroger** [github/hub#2788]
This is error is happening both repo's CI when run the reactivecircus/android-emulator-runner@v2 job

dyld: lazy symbol binding failed: Symbol not found: _preadv
84 Referenced from: /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64-headless
85 Expected in: /usr/lib/libSystem.B.dylib
86
87dyld: Symbol not found: _preadv
88 Referenced from: /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64-headless
89 Expected in: /usr/lib/libSystem.B.dylib

https://github.com/google/android-fhir/runs/2888614202?check_suite_focus=true

https://github.com/ReactiveCircus/streamlined/runs/2890357179?check_suite_focus=true

We have several internal company repos that is running the android instrumented tests using reactivecircus/android-emulator-runne is also failing with the same error - This started happening today - June 22 2021

I think this is github macos-latest runner issue - please help!

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
