### ISSUE TITLE
upload-manifest-file- error while uploading any js or image file

### ISSUE THREAD

**Issue by HussainMadarwala53** [github/hub#2789]
**Command attempted:**

![error](https://user-images.githubusercontent.com/70691828/123074843-4c191700-d435-11eb-891c-a2a68be45c8f.PNG)

**What happened:**
while uploading any file on GitHub it throws me this error.

**More info:**

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
