### ISSUE TITLE
github let's you overwrite on protected branch when freshly pulled repo clone

### ISSUE THREAD

**Issue by ideepika** [github/hub#2793]
this is pretty dangerous bug as it can wipe out the code if mistakenly someone force pushes in main branch, request you to please look into the issue on priority.

I fresh cloned a repo I am a contributor to and forgot set up fork remote to push on, instead I pushed mistakenly set my remote also to point to origin/master... 
```
❯ git remote add ideepika https://github.com/ceph/ceph-build.git
❯ git push ideepika -f
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.05 KiB | 1.05 MiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/ceph/ceph-build.git
   9afd68cf..33e4b91f  master -> master
```
This should have been rejected since the branch is protected, but it got bypassed somehow 
Since the branch was a protected branch this should have been rejected, but it still got force pushed, and when I tried to amend by repushing the original state ... I get 

```
❯ git push origin master -f
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch
To github.com:ceph/ceph-build.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:ceph/ceph-build.git'
```

**Command attempted:**

**What happened:**

**More info:**

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the platform. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the platform, please go to https://github.com/contact or visit https://github.community. Thank you!
