### ISSUE TITLE
Getting Error in React-native-image-picker

### ISSUE THREAD

**Issue by bhojaniasgar** [github/hub#2798]
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[8], "react-native-image-picker").ImagePicker.showImagePicker')

Note:- This project is in TypeScript 

Below is mY Code : 
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Image,
  Alert,
} from 'react-native';
import {ImagePicker} from 'react-native-image-picker';

const options = {
  title: 'Select Image ',
  takePhotoButtonTitle: 'Camera',
  chooseFromLibraryButtonTitle: 'Gallery',
};

export default class ImagePick extends React.Component<any> {
  constructor(props) {
    super(props);
    this.state = {
      imageSource: null,
      pic: null,
    };
  }

  myfun = () => {
    //alert('clicked');

    ImagePicker.showImagePicker(options, response => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('Image Picker Error: ', response.error);
      } else {
        let source = {uri: response.uri};

        // You can also display the image using data:
        // let source = { uri: 'data:image/jpeg;base64,' + response.data };

        this.setState({
          imageSource: source,
          pic: response.data,
        });
      }
    });
  };

  render() {
    return (
      <View style={styles.vwPadding}>
        <Image
          source={this.state.imageSource}
          style={{width: '100%', height: 300, margin: 10}}
        />

        <TouchableOpacity
          style={{backgroundColor: 'green', margin: 10, padding: 10}}
          onPress={this.myfun}>
          <Text style={{color: '#fff'}}>Select Image</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  vwPadding: {
    flex: 1,
  },
});

**Comment by maifeeulasad** [comment]
How is this issue even related to [gh/github/hub](https://github.com/github/hub)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
