### ISSUE TITLE
Changing the file name case sensitivity is not recognized

### ISSUE THREAD

**Issue by asalha** [github/hub#2799]
**Command attempted:**

I use Github desktop version 2.9.0

**What happened:**
I had a file called SignupAddressScreen.tsx in a React Native project. I changed the file name to SignUpAddressScreen.tsx. In the repo, the file name is still SignupAddressScreen.tsx and every time I work on a different machine, make a pull of the latest code, the file that I receive is SignupAddressScreen.tsx. So when I run the app, I always get the error SignUpAddressScreen.tsx is not found. When I go and change the file name from SignupAddressScreen.tsx to SignUpAddressScreen.tsx everything works fine.

**More info:**

**Comment by BLasan** [comment]
@asalha Is this still valid?

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
