### ISSUE TITLE
Brightness of the Qfield-App

### ISSUE THREAD

**Issue by JannikBUND** [github/hub#2801]
**Command attempted:**

**What happened:**

The brightness of the device toggles down every time you open the Qfield-App. It is not on every device we use in our office. Whe all even use the same device with the same software. So what is the Problem?
**More info:**

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
