### ISSUE TITLE
Discord music bot error in discord.py

### ISSUE THREAD

**Issue by Rborphukan** [github/hub#2806]
I got a AttributeError while i was making a discord music bot using discord.py
It happens when i send a url to the bot in discord
The error was "discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: play() missing 1 required positional argument: 'source' "
and here was the code

[https://replit.com/@RBthecoder/Uniscian#music.py](url)

**Comment by kkrypt0nn** [comment]
This issue has nothing to do with GitHub Hub.

**Comment by Rborphukan** [comment]
sorry this was the code [https://replit.com/@RBthecoder/Uniscian](url)

**Comment by kkrypt0nn** [comment]
Your issue has nothing to do with GitHub Hub...

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
