### ISSUE TITLE
Parent-child relationship should trump chronological order

### ISSUE THREAD

**Issue by bradyt** [github/hub#2824]
Github displays commits in chronological order, which may not make a lot of sense if a child commit has commit and author timestamps older than its parents.

I would also be curious how Github displays graphs with more than one initial commit, or more than one [connected component](https://en.wikipedia.org/wiki/Component_(graph_theory)).

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!

**Comment by bradyt** [comment]
Oops, my mistake, thank you for clarifying.
