### ISSUE TITLE
Clicking "Add your review" from a PR, will break some CSS

### ISSUE THREAD

**Issue by TheDutchCoder** [github/hub#2826]
**Command attempted:**
Clicking "Add your Review" from a PR

**What happened:**
Next page shows full width, some CSS (or markup) seems to be missing/broken. It's also missing all the repo nav.

**More info:**
PR:
![image](https://user-images.githubusercontent.com/1668207/130792112-d7c41af4-29c4-4580-8ab9-01971cc6584b.png)

After clicking "Add your Review":
![image](https://user-images.githubusercontent.com/1668207/130792191-9830a3ee-0e71-47ac-9a5a-9995d62c410c.png)

After hard refresh:
![image](https://user-images.githubusercontent.com/1668207/130792238-e7aefc1e-44e4-4eb8-a97c-30448e0027d6.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
