### ISSUE TITLE
Is there a javascript wrapper for this for Node.js ?

### ISSUE THREAD

**Issue by fab1o** [github/hub#2832]
**The problem I'm trying to solve:**

Looking for a npm package to use this tool programmatically 

**How I imagine hub could expose this functionality:**

```js
import hub from 'hub';

hub.pullRequest({
   browse: true,
   message: 'a message'
   base: 'master'
});

**Comment by mislav** [comment]
Sorry, there is no JS wrapper for this tool that I know of.
