### ISSUE TITLE
hub does not allow to update labels with space 

### ISSUE THREAD

**Issue by gagandeepsingh-dev** [github/hub#2838]
**Command attempted:**

hub issue update 2 -l bug,documentation,enhancement,good goissue
**What happened:**

The label which got added was good and goissue was missed.
hub cli is not allowing to set labels with space for example labels such as good first issue cannot be set using the hub cli
**More info:**

git version 2.30.1 (Apple Git-130)
hub version refs/heads/master

**Comment by gagandeepsingh-dev** [comment]
https://github.com/github/hub/pull/2839

**Comment by gagandeepsingh-dev** [comment]
Workaround : hub issue update 2 -l "bug,documentation,enhancement,good goissue"

If you encode the above in double quotes it works

**Comment by gagandeepsingh-dev** [comment]
@defunkt @evanphx @mojodna @schacon

**Comment by evanphx** [comment]
@gagandeepsingh-dev it's incredibly rude to tag random people.

**Comment by gagandeepsingh-dev** [comment]
> @gagandeepsingh-dev it's incredibly rude to tag random people.

I apologize for the distress I may have caused you.
