### ISSUE TITLE
PR count issue on projects 

### ISSUE THREAD

**Issue by BekzodbekTurgunov** [github/hub#2848]
![image](https://user-images.githubusercontent.com/48333057/136643945-cf811e5b-853a-45e1-8473-10cc7353ac3e.png)

the above money request count remains unchanged after multiple pull requests are confirmed.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
