### ISSUE TITLE
I'm able to edit someone else's comment on my PR

### ISSUE THREAD

**Issue by lgodz15** [github/hub#2852]
**What happened:**
When clicking into the 3-dot menu on a comment on my PR, I had the option to edit the comment, which I didn't write. This **feels** like it's a bug, as I don't remember being able to do that in the past.

**More info:**

https://user-images.githubusercontent.com/14898887/137210236-ab80dc47-185d-4980-9133-d4106da0109e.mov

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
