### ISSUE TITLE
Non ergonomic back navigation on mobile: critical 

### ISSUE THREAD

**Issue by LifeIsStrange** [github/hub#2853]
When I explore issues about a projet on my phone browser (Chrome, Android) if I am e.g in the middle of the list of issues I click on one, I navigate back to explore other, the back navigation instead of making me at my previous position) in front of the issue I clicked on, which is ergonomic and standard practice) I am teleported at the top on the issue list, again and again which make me continuously have to scroll back to my previous position to click on the next issue.

This is **awful** UX experience, does anyone use github at github?...

That same issue apply to the navigation of **PRs** and of **commits....**
I feel like this is a regression and wasn't the case 1-2 years ago.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
