### ISSUE TITLE
Commits are not being listed in the contribtion graph

### ISSUE THREAD

**Issue by Jassi10000** [github/hub#2854]
**Command attempted:**

git add .
git commit -m "........................" 
git push origin [branch_name]

**What happened:**

My commits are not showing on the github contribution graph.  Only contributions like opening issues , reviewing or making PRs only these things are being counted , why not commits ??????

**More info:**

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
