### ISSUE TITLE
merge pull request into multiple branches

### ISSUE THREAD

**Issue by sandeepgajula0103** [github/hub#2855]
I have 6 branches and these 6 branches have same code so whenever I change the code or add anything one of the branches, I want to affect the changes into remaining branches with single Pull Request

is there anyway for this?

**Comment by mislav** [comment]
Hi, your question is more of a usage question about git/GitHub in general and less about the tool in this repository, which is called `hub`. As such, you are asking in the wrong place.

I would suggest that you look into GitHub Actions. With Actions, you could react to all pushes to a specific branch and have the commits copied to your 6 other branches.
