### ISSUE TITLE
impoverishment of the building's autogen into the suburbs and countryside with MSFS 2020 Google Map replacement 

### ISSUE THREAD

**Issue by fmariaderose** [github/hub#2867]
Flying over Addis Abeba I noticed this phenomenon.
![I7-2021-nov-17-042](https://user-images.githubusercontent.com/92817513/142176202-1247b270-fb92-4a70-a462-d67a2d25de7c.jpg)
![I7-2021-nov-16-030](https://user-images.githubusercontent.com/92817513/142176335-9603146d-7ba1-4714-b4fb-ff2f4585235c.jpg)
![I7-2021-nov-16-029](https://user-images.githubusercontent.com/92817513/142176406-fe1326fc-f54a-4d3b-a8be-8ccde5e12633.jpg)
![I7-2021-nov-16-028](https://user-images.githubusercontent.com/92817513/142176425-8ba65870-07dc-41b5-b03e-a2932473c5ce.jpg)
![I7-2021-nov-16-024](https://user-images.githubusercontent.com/92817513/142176545-a54ed5b0-0d7a-4c5b-93ab-14fa212c2a00.jpg)
![I7-2021-nov-16-016](https://user-images.githubusercontent.com/92817513/142177125-4e9599e2-efc0-4ab1-af9b-187ec7fbbef0.jpg)

![I7-2021-nov-16-015](https://user-images.githubusercontent.com/92817513/142177161-921f3ebe-e47b-4115-b45f-d18f81063c75.jpg)

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
