### ISSUE TITLE
Intermittent wrong language stats for empty repo

### ISSUE THREAD

**Issue by pereriksson** [github/hub#2876]
Intermittently, empty repositories show a language stats for JavaScript and CSS. The screenshot below is an empty repo with a README.md that contains a headline with no code.

<img width="538" alt="Screenshot 2021-11-30 at 14 13 03" src="https://user-images.githubusercontent.com/2284872/144053687-91af380c-be3c-4a38-b907-59321c56cb40.png">
.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
