### ISSUE TITLE
Pull requests without forkiing

### ISSUE THREAD

**Issue by rubstudent** [github/hub#2901]
**The problem I'm trying to solve:**
I can't contribute to projects by cloning them to my local file system and then making a pull request to the original project, i have to fork my project first which clutters my github, takes time and makes me want to contribute less - even easy fixes - for open source projects.

**How I imagine hub could expose this functionality:**
Github should make it possible that i can just do a Pull request with the changed files without having to fork the repo into my user account. It will be stale anyway. Ill contribute something and then either delete it or forget about it. Just make it possible that i can suggest a specific file change to a project without having to fork it on github. As far as im aware this should also be supported by the git protocol and not cause any trouble. It could even be through the web editor.

I just want to contribute to community projects easily without having to fork each one of them.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the platform. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community.

I get what you're suggesting, but for now, forking is a prerequisite for submitting pull requests to projects that you don't have write access to.
