### ISSUE TITLE
Custom patch based PR ?

### ISSUE THREAD

**Issue by eltomjan** [github/hub#2908]
It is hard to review too big or complex pullrequest sometimes - it would be great to be able to filter out all simple changes like renames, format changes, etc. somehow and focus review on remaining more signficant changes.

It would also be great to have for example PRs based on user editable patch file.
Imagine you pick some PR changes as a patch file and then:
- reorder or split particular file diffs or change blocks as you want (in logical order ?)
- add unchanged block containing related info like declarations
Include change blocks, files and needed context of your wish.

Also when working with code it may be handy to have such a file as single base or few windows with ability to auto-update all changed files.
Start your work based on this PR structure and not on lot of particular files changed in random or alpha order, where you end now.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
