### ISSUE TITLE
Repository deleted and remade still had files, etc. from deleted repository

### ISSUE THREAD

**Issue by cfranz1598** [github/hub#2911]
**Command attempted:**
git push -u origin master

**What happened:**
There are more files in the github repository then in the original local repository (listed towards the bottom of this).  

See also:  https://github.com/cfranz1598  which has two public and one private repository.  The private repository ([Space-invaders_old](https://github.com/cfranz1598/Space-invaders_old)) contains a bunch of files I didn't want as part of the repository.  So I renamed 'Space-invaders' to 'Space-invaders_old' via the github online so as not to lose the audit trail.... and created [Space-Invaders](https://github.com/cfranz1598/Space-Invaders).  Note that name difference with the capitol 'I'.

There is a repository [Space-Invaders](https://github.com/cfranz1598/Space-Invaders) which appears to contains files from a previous repository a similar name. One of the files which should >not< be there is:
[Space-Invaders](https://github.com/cfranz1598/Space-Invaders)/[code](https://github.com/cfranz1598/Space-Invaders/tree/master/code)/[images](https://github.com/cfranz1598/Space-Invaders/tree/master/code/images)/bg0.png

It is certainly not in the list below.  <sigh>

Now understand, when I create the newest 'Space-Invaders' repository on github via the github web online, I also started from scratch locally.  I deleted the local .git directory ('Space-Invaders/.git) and ran the following commands from the 'Space-Invaders' directory on my machine:
git init
git add README.md
git add LICENSE
git add .
git commit -m "v1.0.0 first commit"
git branch -M master
git remote add origin https://github.com/cfranz1598/Space-Invaders.git
git push -u origin master

I'm sure that in one way or another this is my fault, but I'll be dipped if I know how.  I deleted 'https://github.com/cfranz1598/Space-Invaders' via the online process, and then recreated it so that I could upload the 'corrected' repository (see below).

**More info:**
The local repository contains the following and that's all the push should have 'pushed' ...
pi@busterpi:~/Space-invaders/NewCode $ git rev-list --objects --all
63630bdcdc25fa1e5f96ed5153e7c62404a7c633
3f4d4d0aafab7a211f6d3823d882962ba1f0002d 
9ba21dbd0f682e3aed4eacbbb1bca8a740b01f0b audio
e971b84038e4054d8f5d57aa9bb07e97bb4072e2 audio/attributions.txt
0d514fd3433c56ca7512bf06a10345307bb0d30e audio/explosion.wav
15fd2801b4092f737fb8baedf3678201d38d3faf audio/laser.wav
0310c3d8459770808f11e52d90532d625e52c37d audio/music.wav
f149a6cd8416670cbaf07faacc2a6f99f1ee897a code
6ddd21be7cda4318202794ff4ce9c06f983c2e3d code/__pycache__
b90df74f5a2dd9561462a3118630aaad7bd21684 code/__pycache__/alien.cpython-39.pyc
57331dcd9b14e6aa0296d02cbfdad4f4fe88b033 code/__pycache__/laser.cpython-39.pyc
c935fac95eca6a6632fca72a299082b3b0c01eec code/__pycache__/obstacle.cpython-39.pyc
c6b28094ad47a0b259cad2b8938edcd28772ae29 code/__pycache__/player.cpython-39.pyc
7c75df889fb407ee1a58c506e1fed4a652bc48b5 code/alien.py
0f50dcca302640ae2672c35dd615ce79957a5901 code/laser.py
cfac14302610cfedd916251f564d0d120e5686b1 code/main.py
78d4ece1a4f843f2cf2c015463232cfdf82bfc0e code/obstacle.py
495ca29109409452629fb26b58a91c2b411a53b9 code/player.py
16435e08e88a31d1c6b7eaba3e823ea8f87fd9dc font
14449ba90aa0ccf38a6fb9649a4c5e30ef8d909b font/Pixeled.ttf
ebb0a6aad05c1df283ec7f1961db26de24c50d47 graphics
cbbf8239249555dac5d67e2bd67456ead0c41111 graphics/extra.png
6f2f4f2f09eb8a4ee20bd285ea992dc41db6f3eb graphics/green.png
347069d1ebfe88f65e2f1d07f233f1399e78bb68 graphics/player.png
04efa8a377786abb020df45d2c47130399264cf4 graphics/red.png
1c3d48d163ee5ef2062ad03352190994799e0755 graphics/tv.png
4055b3dbff7c41d32667ae8864f29cb24088fe4b graphics/yellow.png

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
