### ISSUE TITLE
Is there a way to get the current github username?

### ISSUE THREAD

**Issue by fab1o** [github/hub#2923]
Is there a way to get the current github username?

The goal is to pass this info to `--assign` in pull request.

I tried using the name from `git config user.name` and email from `git config user.email` but they don't work, get error:
```sh
Error updating issue: Unprocessable Entity (HTTP 422)
Invalid value for "assignees"
```

**Feature Request**
Would be nice if `hub pull-request` used the current user as default for `--assign` or gave us the option to tell it to use it

**Comment by mislav** [comment]
You can do:
```sh
gh api user | jq -r '.login'
```
In practice:
```sh
hub pull-request --assign "$(gh api user | jq -r '.login')"
```

**Comment by fab1o** [comment]
Is there an easier way? I need to install 2 applications to run this plus have it setup/logged in. Since this is going to be an automation tool, I didn't want to have more pre-requirements. Is there a way for **hub** to accomplish that?

**Comment by fab1o** [comment]
Thank you! But is there an easier way? I need to install 2 applications to run this plus have it setup/logged in. Since this is going to be an automation tool, I didn't want to have more pre-requirements. Is there a way for hub to accomplish that?

**Comment by mislav** [comment]
@fab1o No, currently there isn't a straightforward command to retrieve your username.

However, you can switch to GitHub CLI, where you can do `gh pr create --assignee "@me"`

**Comment by yaronuliel** [comment]
@mislav 
`gh api user -q ".login"` will do the same without requiring `jq` to be installed

**Comment by rockdaboot** [comment]
@yaronuliel's solution is what I prefer. Just to mention it, two solutions without the `gh` tool (pretty hacky, though):
```
ssh -T git@github.com 2>&1|sed -r 's/.* (.*)! .*/\1/g'
```
```
ssh -T git@github.com 2>&1|cut -d'!' -f1|cut -d' ' -f2
```
