### ISSUE TITLE
Dedicated section for project's system requirements.

### ISSUE THREAD

**Issue by FranksRobins** [github/hub#2928]
Hi there Github team. Would it be possible to add a "**_resource/system/hardware requirements_**" section in the menu on the right along with **About**, **Topics**, **Resources**, etc? right under **Languages** where you could see the cpu, ram , storage, network recommendations from the official project page? It's not always easy to find those informations while they are often very critical. Instead of relying on the projects' official website (if they happen to have one and if they happen to have taken the time to create a web page or section on their website for that), maybe proposing the developers to mark it down on their project's page would be an easy go-to resource and would promote a good culture for the sake of documentation. It would also be really easy for the project's teams to get this important step done without having to plan for an integration on their site. At the same time, if they do not have this information, it could promote the importance of benchmarking of software solutions. Would be even better if this information could be gathered from the API. I think this simple add-on would bring a lot value to Github.

Thanks in advance for your time.

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
