### ISSUE TITLE
Xcode not installing in MAC OS Monterey

### ISSUE THREAD

**Issue by inn-sharmila-varatharajan** [github/hub#2936]
I am trying to install xcode 13.3 for mac os monterey from apple store even i have 50gb of storage not enough disk space error is appearing. i have cleared all bin,cache files and  i got 60gb even i am getting same issue. 

I have tried the following steps.

1.I tried to install via a terminal its installing version 12 and while opening again showing a error message upgrade to a latest version.
2. I have cleared all factory settings after downloading its keep on rotating and not installing  and again showing an download symbol.  I cant able to install xcode. 

Please give a suggestion for the above issue.

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
