### ISSUE TITLE
`hub clone $org/$repo` failing after GitHub deprecates `git://` URLs

### ISSUE THREAD

**Issue by bobwhitelock** [github/hub#2937]
## Command attempted/what happened

Commands like this started failing for me today:

```
$ hub clone github/hub
Cloning into 'hub'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

It seems like GitHub has deprecated using `git://` URLs, and this change has fully rolled out as of yesterday - from that link given in the error above:

> March 15, 2022 | Changes made permanent.We’ll permanently stop accepting DSA keys. RSA keys uploaded after the cut-off point above will work only with SHA-2 signatures (but again, RSA keys uploaded before this date will continue to work with SHA-1). The deprecated MACs, ciphers, and unencrypted Git protocol will be permanently disabled.

---

This looks like the relevant section of the `hub` code where these `git://` URLs are used as the default in this situation: https://github.com/github/hub/blob/af7150924e85073225020f75134841cd889b5e7e/github/project.go#L80

## Workaround

You can work around this by either cloning with a full, non-`git://` URL:
 
```
$ hub clone https://github.com/github/hub
Cloning into 'hub'...
remote: Enumerating objects: 20316, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 20316 (delta 4), reused 11 (delta 2), pack-reused 20300
Receiving objects: 100% (20316/20316), 7.08 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (13286/13286), done.
```

Or by setting this config value so `hub` uses a different protocol by default:

```
$ git config --global hub.protocol https  # Or `ssh` if you prefer that.
$ hub clone github/hub
Cloning into 'hub'...
remote: Enumerating objects: 20316, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 20316 (delta 4), reused 11 (delta 2), pack-reused 20300
Receiving objects: 100% (20316/20316), 7.08 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (13286/13286), done.
```

So this is easy to work around, just a bit confusing when it first happens, and no longer seems like useful default behaviour.

## More info

```
$ hub --version
git version 2.35.1
hub version 2.14.2
$ uname -o 
GNU/Linux
$ uname -r
5.15.22-1-lts
```

**Comment by mislav** [comment]
Great point. The workaround you've discovered is the correct one:
```
git config --global hub.protocol https  # Or `ssh` if you prefer that.
```
And I agree that hub should change its default protocol.

**Comment by dsyer** [comment]
It's a workaround still IMO because when I clone a repo that I own (and therefore have write access) I want to use ssh. Hub would do that automatically if the global protocol wasn't set. Now I have to faff around changing the remote url for every project I clone or create. Please can we fix this?

**Comment by mislav** [comment]
@dsyer If you prefer SSH then please use `git config --global hub.protocol ssh`.
