### ISSUE TITLE
Insights reports "Looks like something went wrong!"

### ISSUE THREAD

**Issue by Notaduck** [github/hub#2953]
I have a private repository in a organisation https://github.com/org/repo_name/network/dependencies and it is not possible to get access to the "Insights" tab for some reason.

![Screenshot 2022-04-05 at 09 03 45](https://user-images.githubusercontent.com/9454064/161697510-4bb2a818-9f10-429d-b82d-a78ce7eba052.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!
