### ISSUE TITLE
Pull Request to have assignee to current github username

### ISSUE THREAD

**Issue by fab1o** [github/hub#2955]
Wondering if we could have the pull request command assign the current username as the author of the pull request, like when with `hub clone` it uses the current username

```
[USER/]REPOSITORY
USER defaults to your own GitHub username.
```

Essentially this is what I was trying to accomplish:
https://github.com/github/hub/issues/2923

**Comment by mislav** [comment]
Sorry, there isn't a straightforward way to self-assign using hub https://github.com/github/hub/issues/2923#issuecomment-1092749045

I recommend using `gh` for greater flexibility.
