### ISSUE TITLE
Repositories page design issue in mobile view

### ISSUE THREAD

**Issue by pragnesh123-cmd** [github/hub#2974]
Hello GitHub,
Here is a screenslot you can see red line arrow 

![Screenshot_20220524-181144](https://user-images.githubusercontent.com/65768699/170404087-5fce5963-3db6-4066-90fa-8d8a871d4b97.jpg)
![Screenshot_20220524-181120](https://user-images.githubusercontent.com/65768699/170404095-2ad2235f-1239-43ac-abe4-35cd98f3fa56.jpg)

Thanks,
Pragnesh Patel

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/contact or visit https://github.community. Thank you!

**Comment by pragnesh123-cmd** [comment]
ok @mislav thank you
