### ISSUE TITLE
Shell not working...windows 7

### ISSUE THREAD

**Issue by AndrewDonelson** [github/hub#298]
I have a desktop and laptop, both running window 7 home premium. Desktop github works flawlessly GUI and Shell. However on the notebook the shell (either bash or powershell) has never worked. Github has auto updated 4X and i have uninstalled and reinstalled 3X. There are no options on install, no user interaction needed. If I type git from cmd prompt is get the message git is not a reconized internal/external blah, blah. If i run powershell it runs but when I try and run git is get this error:

The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spellin
g of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
- git <<<<
  - CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundExc

if i run a shell script it but opens a blank window, closes, and repeats indefiniately.

My path is this:

PATH=C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program File
s (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Window
s;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Progra
m Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common
 Files\Roxio Shared\12.0\DLLShared\;C:\Program Files (x86)\Windows Live\Shared;C
:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static

I see powershell but nothing for git/github.

I cant even find the installation folder. The icon link is to:

C:\users\mcx\desktop

which is the icon, not the application folder.

I am not running cygwin or anything else. But for some reason github for windows does not install correctly on this notebook/windows combination.

Help? I have not figured this out in 4 months. :(

**Comment by siims-biz** [comment]
I did have the more or less same issue.
There was a Git Shell icon on my desktop, but it did not launch the shell.
What helped was a double click on GitHubSetup.exe
After that the shell icon was working again
