### ISSUE TITLE
Uncaught TypeError: Q4[v39999.Y(...)] is not a function

### ISSUE THREAD

**Issue by nayeem81127** [github/hub#2982]
v39999.Y = function () {
  return typeof v39999.t.v === "function"
    ? v39999.t.v.apply(v39999.t, arguments)
    : v39999.t.v;
};

setTile = function (P4, Q4, B4) {
  var S4 = 1194701741;
  if (v39999.f(20, 346638) !== S4) {
    var i4, j4;
    i4 = v39999.Z3(Q4[v39999.u(18)]);
    Q4[v39999.Y(58)](function (A4) {          <------ error on Q4[v39999.Y(58)](function (A4) {})
      var g4 = 1542393705;
      if (v39999.m(20, 254240) === g4) {
        if (+A4[v39999.Y(18)] != v39999.o(18))
          i4 -= A4[v39999.Y(45)][v39999.Y(78)];
      } else {
        if (v39999.K3(~A4[v39999.Y(18)], v39999.u(18)))
          i4 %= A4[v39999.R(78)][v39999.Y(18)];
      }
    });
}
}

Hello any body help me out on this issue i'm enable to resolve issue  
error on Q4[v39999.Y(58)](function (A4) {})

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
