### ISSUE TITLE
How can I pay a bounty for an issue ?

### ISSUE THREAD

**Issue by shodanx2** [github/hub#2989]
**The problem I'm trying to solve:**

I want to put money on an issue to motivate its resolving 

**How I imagine hub could expose this functionality:**

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/github/feedback or contact Support directly at https://github.com/contact. Alternatively, you could visit or ask in https://github.community. Thank you!
