### ISSUE TITLE
Pull request comments can be edited by other users!

### ISSUE THREAD

**Issue by MrXavier** [github/hub#2994]
_I created this issue here because I don't know what is the repository for Pull Request comments in Github organization. Since this bug is critical I will posted here. Sorry for the mistaken and please indicate where should I created it._

Pull request comments can be edited by other users in Pull Requests in Github!

![Screenshot 2022-08-10 at 16 32 35](https://user-images.githubusercontent.com/7959331/187091510-86993153-bfef-445c-aaa7-ef692841c622.png)

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/github/feedback or contact Support directly at https://github.com/contact. Alternatively, you could visit or ask in https://github.community. Thank you!
