### ISSUE TITLE
Error creating pull request: Unprocessable Entity (HTTP 422) in github actions

### ISSUE THREAD

**Issue by Shayam-S3** [github/hub#2996]
I am trying to create a GitHub action to automate PR creation and I got the below error

From https://github.com/Shayam-S3/MyProject
 * [new branch]      PreProd    -> PreProd
 * [new branch]      PreProd    -> origin/PreProd
* Master                 7bcfc5b [origin/Master] adtest
  PreProd                3f6c249 Update main.yml
  remotes/origin/Master  7bcfc5b adtest
  remotes/origin/PreProd 3f6c249 Update main.yml
hub pull-request   -b PreProd   -h Master   --no-edit   -m "Pulling refs/heads/Master into main" -m "👑 *An automated PR*" -r "kingdonb" -d   || true
Error creating pull request: Unprocessable Entity (HTTP 422)

and this is yml file
<img width="784" alt="Screenshot 2022-08-11 at 10 28 44 PM" src="https://user-images.githubusercontent.com/110990967/184191276-c205bd55-1e37-47eb-b0ff-6a08b4898547.png">

<img width="1055" alt="Screenshot 2022-08-11 at 10 24 17 PM" src="https://user-images.githubusercontent.com/110990967/184190920-a7fe9f97-6d96-4e84-829f-e9df7b12c8ba.png">
r

**Comment by rgugliel-da** [comment]
Maybe I am saying something very dumb but it seems that you are trying to create a draft pull requests (flag `-d`) and your repo does not allow it.

**Comment by Shayam-S3** [comment]
Now I am able to create the PR the problem is with the secret token
