### ISSUE TITLE
<!-- MODIFIED_CONTENT_LINKING_COMMENT -->

### ISSUE THREAD

**Issue by nona2512** [github/hub#3007]
## Automatically generated comment ℹ️
**This comment is automatically generated and will be overwritten every time changes are committed to this branch.**

The table contains an overview of files in the `content` directory that have been changed in this pull request. It's provided to make it easy to review your changes on the staging site. Please note that changes to the `data` directory will not show up in this table.

---

### Content directory changes
_You may find it useful to copy this table into the pull request summary. There you can edit it to share links to important articles or changes and to give a high-level overview of how the changes in your pull request support the overall goals of the pull request._
| **Source** | **Preview** | **Production** | **What Changed** |
|:----------- |:----------- |:----------- |:----------- |
| Removed: [`issues/planning-and-tracking-with-projects/customizing-views-in-your-project/customizing-a-view.md`](https://github.com/github/docs/blob/85c646005f551ec27e1fa05f637afa6a301a191e/content%2Fissues%2Fplanning-and-tracking-with-projects%2Fcustomizing-views-in-your-project%2Fcustomizing-a-view.md) | n/a | [fpt](https://docs.github.com/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/customizing-a-view)<br>[ghec](https://docs.github.com/enterprise-cloud@latest/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/customizing-a-view)<br> | removed |

---
fpt: Free, Pro, Team
ghec: GitHub Enterprise Cloud
ghes: GitHub Enterprise Server
ghae: GitHub AE

_Originally posted by @github-actions[bot] in https://github.com/github/docs/issues/20407#issuecomment-1236355793_

**Comment by nona2524** [comment]
https://github.com/github/docs/pull/20407#issuecomment-1236355793
