### ISSUE TITLE
Issue(Bug) on git profile not showing (2020,2021,2022) proper blue button on 1920px-929px  display

### ISSUE THREAD

**Issue by iamatulbansal** [github/hub#3008]
**Command attempted:**

**What happened:**

Please watch this short  videos, i have explain issue using cursur
[finding bug on github ui.webm](https://user-images.githubusercontent.com/86524139/189530490-01933584-7634-47ad-9528-31c908b0e83d.webm)
Screenshot---->
![Screenshot 2022-09-11 190820](https://user-images.githubusercontent.com/86524139/189530612-6b2f989d-4e7f-404e-a66f-bc179a2866fa.png)

**More info:**

My OS is windows 11 x64-bit

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please go to https://github.com/github/feedback or contact Support directly at https://github.com/contact. Alternatively, you could visit or ask in https://github.community. Thank you!
