### ISSUE TITLE
Error generated from Azure firewall policy rule collection group reports incorrect grammar.

### ISSUE THREAD

**Issue by AdilKhan1117** [github/hub#3010]
This bug is being reported for the 'azurerm_firewall_policy_rule_collection_group. 

1. Upon trying to use Dynamic blocks with 'each.value.rules/.
2. The following error is generated by Terraform module
    'A reference to "each.value" has been used in a context in which it unavailable, such as when the configuration no longer contains the value its "for_each" expression. Remove this reference to each.value in your configuration to work around this error. 

3. There is a grammatical error, the 'it' after in a context in which, is incorrect, it should be "is unavailable".

Please could this be updated?

Thanks

**Comment by mislav** [comment]
This issue tracker is for a command-line tool called "hub" which is written in Go, and has nothing to do with Azure firewall or Terraform. Your question seems unrelated to this project, and you should find a more appropriate forum to ask it in. Thank you.
