### ISSUE TITLE
Msfs_mouse_yoke-0.3c 

### ISSUE THREAD

**Issue by isiqhawe** [github/hub#3029]
Hi! @matiaspedelhez

Microsoft Flight Simulator **(XboxGames)** Msfs_mouse_yoke-0.3c **Wow! PERFECT.**
Microsoft Flight Simulator **(Steam)** Msfs_mouse_yoke-0.3c **FAIL.**

1. I uninstalled Microsoft Flight Simulator on XboxGames. 
2. I installed Microsoft Flight Simulator on Steam. 
3. Cmd opens msfs_mouse_yoke-0.3c and closes after 1  

[20221224T0415114592.log](https://github.com/github/hub/files/10298158/20221224T0415114592.log)

**Comment by isiqhawe** [comment]
Solved =]

I installed the ViGEmBus Setup 1.17.333 
https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

[20221224T1119293203.log](https://github.com/github/hub/files/10298730/20221224T1119293203.log)

**Comment by mislav** [comment]
Hi, this doesn't seem at all related to the project contained in this repository.
