### ISSUE TITLE
Feature request : list pull requests

### ISSUE THREAD

**Issue by DjebbZ** [github/hub#335]
First of all thanks for the project. I just discovered it and I already aliased `hub` as `git` :)

I understand that hub is made for general/not too evolved git flow with github. Is listing pull requests (or issues) outside the scope of hub ? I would love to have a command like `git/hub pull-request --list` and have the shell display all opened PR/issues with their number and title. So I could just `git/hub browse USER/REPO issues/ISSUE#` right away and go to the PR/issue page.

Seems useful to me, what do you think ?

**Comment by raboof** [comment]
Getting this feature in is now tracked in #1303
