### ISSUE TITLE
Permit the assigning of a user

### ISSUE THREAD

**Issue by frankshearar** [github/hub#371]
Often I want to create an issue and assign it to someone. At the moment that means that I develop some branch, turn it into a PR with hub, go to the issue on GitHub, and assign the issue.

Having something like `hub pull-request <stuff> -u frankshearar` would make this workflow much smoother.

**Comment by mmikulicic** [comment]
Should this be reopened ? As far as I understood #393 was trashed because the ruby impl has been replaced by the Go implementation, but I don't see any other tracking issue.

**Comment by mislav** [comment]
@mmikulicic This tracking issue was never closed.

**Comment by mmikulicic** [comment]
@mislav oops, I guess I got misled by the red "Closed" badge but that was about a related PR.

**Comment by brianjmurrell** [comment]
Is there any way to set a default value for the assignee when opening a PR with `hub`?

**Comment by mislav** [comment]
@brianjmurrell Right now no, but might be possible in a future major release.
