### ISSUE TITLE
GIT env variable needs to be unset

### ISSUE THREAD

**Issue by docwhat** [github/hub#408]
After using `ENV['GIT']` it needs to unset the `GIT` environment variable.

This will:

* Prevent infinite recursion if someone tries `env GIT=hub hub` (or if they have git aliased to hub: `env GIT=hub git`).
* Allow chaining to another wrapper that uses `GIT` to determine the next git executable to run.

Ciao!

**Comment by mislav** [comment]
Update: hub is not implemented in Ruby and doesn't set or read the "GIT" environment variable. This shouldn't be an issue anymore!
