### ISSUE TITLE
Error creating pull request: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by gpszymczak** [github/hub#413]
$ hub pull_request -i 836
github.com username: myusername
github.com password for myusername (never stored): 
Error creating pull request: Not Found (HTTP 404)
Are you sure that github.com/myorg/myrepo exists?

This repo exists and all other commands work except pull-request.
Only for this command hub asks me for username/password

**Comment by eliasbagley** [comment]
This started happening to me after upgrading to el captian. My ~/.config/hub looks like:

```
---
github.com:
- oauth_token: <token>
  user: <username>
```

and when I try `hub pull-request -b dev`

I get the following error:

```
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/<username>/<organization_name> exists?
```

Why is the above url `github.com/<username>/<organization_name>`? I would expect it to just be `github.com/<organization_name>`

**Comment by mislav** [comment]
> Why is the above url `github.com/<username>/<organization_name>`?

@eliasbagley That sounds like a separate problem. Could you open a separate issue and give us more detail? `git remote -v` output is always helpful (you can anonymize certain values, but make sure that the formatting stays intact). Before trying to reproduce, make sure that you're running the latest hub version.

**Comment by MaxInMoon** [comment]
for me this problem occured after transfert project from my account to an organization, and I fixed the error by replacing the good repo url in `myrepo/.git/config` and restarting GithubDesktop app

**Comment by onodera-punpun** [comment]
This just happened to me, tried to make a pull request (2 times), both immediately after 404'd:

https://github.com/zyedidia/micro/issues/884
https://github.com/zyedidia/micro/issues/883

**Comment by justineyster** [comment]
Sharing a solution to this problem that worked for me. My Personal Access Token didn't have the proper permissions. I originally creating it with no permissions. Adjusting the permissions fixed this problem. Also, I'm just exporting `GITHUB_TOKEN=...` instead of creating `~/.config/hub`.

**Comment by navigaid** [comment]
For me renaming the github remote to origin solved the problem.

**Comment by IslamAzab** [comment]
As far as I have seen and understand, token set at `GITHUB_TOKEN=...` has higher precedence than `~/.config/hub`.

**Comment by adesawcen** [comment]
> I had the same problem, but I just created the ~/.config/hub file with:
> 
> ```
> --- 
> github.com: 
> - oauth_token: <my-token-created-on-github>
>   user: <my-github-user>
> ```
> 
> Changed the permissions of the file to make sure it was secure:
> 
> ```shell
> $ chmod go-r ~/.config/hub
> ```
> 
> and now works fine.

this solution fixed my Windows environment too

**Comment by Nitrodist** [comment]
This process really still sucks. I am getting this error:

```
 $ hub pull-request
github.com username: Nitrodist
github.com password for Nitrodist (never stored):
Error creating pull request: Not Found (HTTP 404)
Not Found
```

**Comment by alias-mac** [comment]
@Nitrodist you can always try/switch to https://cli.github.com which is the official CLI now supported by GH.

**Comment by jcward** [comment]
@alias-mac the docs on the PR creation (https://cli.github.com/manual/gh_pr_create) don't mention anything about converting an issue to a PR. Am I missing something?

**Comment by hackaprende** [comment]
How do I get the oauth-token?

> > I had the same problem, but I just created the ~/.config/hub file with:
> > ```
> > --- 
> > github.com: 
> > - oauth_token: <my-token-created-on-github>
> >   user: <my-github-user>
> > ```
> > 
> > 
> > Changed the permissions of the file to make sure it was secure:
> > ```
> > $ chmod go-r ~/.config/hub
> > ```
> > 
> > 
> > and now works fine.
> 
> this solution fixed my Windows environment too

Where do I get the oauth_token?

**Comment by zachary95** [comment]
I just had this issue and I solved it by not using the new fine-grained tokens but the classic Personal Access Token. Just give it the `repo` scope and that should be enough.

https://github.com/settings/tokens
