### ISSUE TITLE
pull-request without fork

### ISSUE THREAD

**Issue by robsonpeixoto** [github/hub#424]
Should be possible create a pull-request without a new fork

**Comment by skywinder** [comment]
@mislav Hi. I read the #158 and commit message 06999d9, but didn't find answer to the question: is it possible to "pull-request without fork"?

**Comment by mislav** [comment]
@skywinder It's only possible to open a pull request without a fork if you have push access to the original repository. Then you can simply push to a new branch in that repo and use `hub pull-request`.

In other cases, you must create a fork with `hub fork` and push to the new remote `git push -u skywinder HEAD` and open a pull request `hub pull-request`.

**Comment by skywinder** [comment]
@mislav  Thanks for explanation!

**Comment by pannous** [comment]
so as a one liner:
`alias github-pull-request="hub fork;git push -u $GIT_USER HEAD;hub pull-request"`
