### ISSUE TITLE
Underscore "_" in search do not work.

### ISSUE THREAD

**Issue by valllabh** [github/hub#434]
Try searching "register" in any repository
https://github.com/WordPress/WordPress/search?q=register&type=Code

There would be many results, this works fine.

Now search "register_"
https://github.com/WordPress/WordPress/search?q=register_&type=Code

No Result!!!

**Comment by jeffhammond** [comment]
@valllabh What's odd is that it works from of the time, e.g. https://github.com/search?q=register_&ref=searchresults&type=Code&utf8=%E2%9C%93.

Sorry for posting this here, but this is the top Google search hit associated with this topic and nothing else is as close to as relevant.  Perhaps [support@github.com](support@github.com) should use Github issues for tracking...

**Comment by Rushabh5000** [comment]
Modify your search like this:

register\_

This is one of the ways in which Oracle supports escape characters. Here you define the escape character with the escape keyword. For details see [this link on Oracle Docs.](https://docs.oracle.com/cd/B10501_01/text.920/a96518/cqspcl.htm)


https://github.com/WordPress/WordPress/search?q=register%5C_&type=Code
