### ISSUE TITLE
Authentication fails if two-factor auth is required

### ISSUE THREAD

**Issue by wichert** [github/hub#435]
I tried to use hub to create a pull request, but got an error:

```
$ hub pull-request -i 350
github.com username: wichert
github.com password for wichert (never stored): stty: standard input: unable to perform all requested operations

Error creating pull request: Unauthorized (HTTP 401)
```

This is most likely because I have github configured to require two-factor authentication. And indeed in the [security history](https://github.com/settings/security) I see this:

![image](https://f.cloud.github.com/assets/199657/1591737/553a3d72-52ac-11e3-97c0-248a95c8798c.png)

**Comment by lawipac** [comment]
still not solved, today I tried to install package using composer, but no-sms received.

**Comment by mislav** [comment]
@lawipac Composer has had 2FA support for many months now. However, this project is not Composer nor related to it at all. So, it's not an appropriate place to rant about your troubles with using Composer. If you need to report a bug to them, go to their issue tracker.

**Comment by rschuster3** [comment]
In case Google search brings anyone else to this thread: I had this issue today with not being able to login via Git Shell until I disabled 2FA. A coworker suggested using a personal access token for specific apps to prevent this from happening in the future. https://help.github.com/articles/creating-an-access-token-for-command-line-use/

Does that sound about right?

**Comment by mislav** [comment]
@rschuster3 Were you using hub or just plain git push/pull/clone? Where did you put the token?

**Comment by rschuster3** [comment]
Just plain git push/pull/clone. I haven't made the token yet (since I was able to authenticate after I disabled 2FA) but it's on my to-do list for today.

**Comment by fslone-nomi** [comment]
just did it myself. Create the token and enter it just as you would your password when signing in via Git Bash and you're good to go.

**Comment by rschuster3** [comment]
All righty, I'll go ahead and set it up now. The shell is oddly asking me to authenticate again for a push I want to make. I say "oddly" because I'm not asked to authenticate normally. Will post here again if I have issues with the token. Thanks!

**Comment by fslone-nomi** [comment]
might want to look into caching you credentials to help with that

https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by lrn2prgrm** [comment]
The [link](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) provided by @rschuster3 works perfectly for my git kraken pulls issues after setting up 2 factor.
