### ISSUE TITLE
Templatize pull-request message/title

### ISSUE THREAD

**Issue by ajf** [github/hub#446]
It would be nice to be able to specify a `-t` argument to `pull-request` that takes a file name.  Hub could then use this file to pre-populate the pull-request message in the case of 1 or more commits.

When making pull-requests, we have a few standard formats that we'd like people to use, and this would make it easier for them.

**Comment by rtuin** [comment]
I know this is an old issue, but having the option to configure a template would improve the workflow when creating pull-requests.
Judging by the current code there is no option for this yet. Correct? Is this on the roadmap, or can I help, perhaps?

**Comment by mislav** [comment]
Internally we do use a template I think. We would just need to make this configurable so that you can specify a file to read the template from.

**Comment by rjmunro** [comment]
`git commit` uses `-F` to specify the filename and `-e` or `--edit` to say it should be edited, which achieves the same result. It would be better to support the same options.
