### ISSUE TITLE
Separate documentation pages

### ISSUE THREAD

**Issue by hkdobrev** [github/hub#448]
I would like `hub` to have separate documentation pages (a.k.a. man pages) for each `hub` command. Just like `git` does.

When one types `hub help browse` the whole `hub` documentation pops up and the user needs to find the description and available arguments for the desired command.

Someone might even use a `hub` command without knowing he's using `hub`. In this case when he types `git help browse`, he will see some documentation which is not directly related.

**Comment by mislav** [comment]
This was done in https://github.com/github/hub/pull/1087 and will be part of 2.3 release!
