### ISSUE TITLE
Obtaining authentication from environment

### ISSUE THREAD

**Issue by pwaller** [github/hub#463]
I don't want to have a `.config/hub` file lying around on remote systems where I use hub. I'd prefer to communicate my password through the environment (since I can use ssh SendEnv, etc).

I've tried using GITHUB_USER and GITHUB_PASSWORD with a token generated from https://github.com/settings/applications, but when I try to send a pull request I get "404 not found". It works if I send a pull request by entering my credentials and using `.config/hub`. Any ideas?

**Comment by pwaller** [comment]
Tidying up my personal issues list, so closing this. Please create a new issue if you're still interested in tracking it.

**Comment by mislav** [comment]
I would appreciate if you didn't close an old ticket when the issue is still unsolved. Forcing us to open another issue means that we lose the conversation thread as well as everyone who was subscribed to the updates for this issue.

**Comment by xakraz** [comment]
:+1: also for ```GITHUB_TOKEN```

**Comment by parkr** [comment]
1c6d4b8cf51fe810fba51e55e485aab4b34ab9f0 c23823db7e07cc81fd3d6a7ec84d4367cc38e218 9e6b7cb1e33dc0a51a706fa57cf0f08a85d0b3b7 (merge commit: 2548707d68032d09b8d3af946668efc4d9a60be3)

**Comment by parkr** [comment]
Thanks for picking this up, @mislav!

**Comment by corysimmons** [comment]
I'm not sure this is fixed. I had Hub installed from a while back and just went to try it out again and kept getting 401 errors. Apparently I had deleted my old token. I created a new one and added it, but I'm not sure what permissions that token needs, and it seems like bad design to make the user have to track down all this stuff.

Is it possible to test if the token is good and if it isn't generate/store a new one? It would've saved me a 10 minute headache. :^)

**Comment by mislav** [comment]
@corysimmons No updates yet. Pull requests welcome!

**Comment by corysimmons** [comment]
I would but I don't know Go at all. Planning on learning it in the next few months. Will get back to you then. ;^)

**Comment by danielcompton** [comment]
I had the same issue today. 

```sh
~/D/j/karma (master) $ hub fork
Error creating fork: Unauthorized (HTTP 401)
Bad credentials
```

A few things could make this easier to debug/fix:

* Say where the bad credentials came from (`~/.config/hub`)
* Say which user Hub was attempting to authenticate as
* Include in the log message that this is a Hub error, not a Git error (maybe?)
* Tell people that they can clear credentials and reauthenticate by deleting `~/.config/hub` (or whatever is the correct way of doing this)

**Comment by mislav** [comment]
@corysimmons I didn't know Go at all as well until @jingweno (then just a fan) rewrote all of hub in Go and I've accepted it as a contribution :wink: 

@danielcompton Those are all great suggestions. I would like to implement some of your ideas together with a specialized command to handle (re)authentication. Then, the error message could suggest that you try to reauthenticate to obtain a fresh token.

**Comment by corysimmons** [comment]
lol what kind of person submits a PR with an entire project rewritten in another language? What kind of person accepts that? You guys are crazy, or talented, or both. :dancers:

**Comment by mislav** [comment]
> lol what kind of person submits a PR with an entire project rewritten in another language? What kind of person accepts that?

Yeah it's pretty crazy, I know. :smile: The [Go version was faster](https://github.com/github/hub/releases/tag/v2.2.0) (I plateaued in terms of how fast I can make Ruby implementation be) and easier to distribute via prebuilt binaries.

**Comment by corysimmons** [comment]
Looks great. I'm excited to learn it. =)

**Comment by jingweno** [comment]
@calebthompson It's pretty crazy :). I documented [why I did that](https://owenou.com/2013/12/22/fast-github-command-line-client-written-in-go). And @mislav helped a lot for the migration.

**Comment by calebthompson** [comment]
Uh, hi. @corysimmons maybe?

**Comment by corysimmons** [comment]
@jingweno Yeah, read it the other day. Seems amazing.

@calebthompson Yeah I think he meant to ping me. =)

**Comment by FranciscoBorges** [comment]
So originally the argument for not using OSX Keychain was that hub was not compiled. Hub now is written in Go and distributed in compiled form, would it be too difficult to just add Keychain support?

FWIW, I would be using 'hub' in a GitHub Enterprise environment where I must work with tokens, i.e. authenticating with user/pass directly with the GitHub server is never going to work.

**Comment by mislav** [comment]
@FranciscoBorges I'm thinking of adding support for git credential helper, and then you could configure hub to use `git-credential-osxkeychain` (ships with git) to store credentials in macOS Keychain. Would that be an acceptable solution? https://github.com/github/hub/issues/1217

**Comment by supermarin** [comment]
That sounds good to me

**Comment by sj26** [comment]
I made a reeeeeally rough version of this that works in the positive case when a GitHub personal token has already been saved in the git credential helper (I use osxkeychain).

**Comment by maxkomarychev** [comment]
Here's how I managed to marry hub with osx keychain, perhaps will be useful for someone.

I created shell alias for `hub` that reads token from keychain and provides it as a env variable for `hub` command.

1. create token with necessary permissions (https://github.com/github/hub/blob/master/share/man/man1/hub.1.md#github-oauth-authentication)
2. copy the token
3. add token into keychain: `security add-generic-password -a <your username> -s <service name> -w`, for instance: `security add-generic-password -a johndoe -s hub -w` (you will be prompted twice for the token, just hit cmd+v and hit enter)
4. open `~/.bash_profile` with your favorite editor
5. add alias: `alias ghub='GITHUB_TOKEN=$(security find-generic-password -s <service> -a <account> -w) hub'`
6. reload your shell config: `source ~/.bash_profile`
7. now you can use `hub` through alias `ghub` and it will be authenticated :)

**Comment by jsravn** [comment]
I wonder why hub can't simply read a gpg encrypted file and prompt for the password when opening? Would you be open to a PR to do that? hub is the only tool I use which stores a sensitive key in plaintext format with no encryption. I don't use OS X but I imagine Keychain can handle gpg too.

**Comment by mislav** [comment]
> I wonder why hub can't simply read a gpg encrypted file and prompt for the password when opening? Would you be open to a PR to do that?

@jsravn That would indeed be more secure, but hub will not aim to cover the implementation details of different secure stores. I would rather than we support a single protocol such as git "askpass" or credential helper. Then people can set up their own executable to handle storing credentials in any way that they prefer.

Yes I would be open to PRs that improve security! ✨
