### ISSUE TITLE
hub checkout pull request when fork is deleted

### ISSUE THREAD

**Issue by ivantsepp** [github/hub#473]
Recently I tried to checkout a pull request and the fork was deleted:

```
jekyll[master] $ hub checkout https://github.com/jekyll/jekyll/pull/1869
Error: troyswanson's fork is not available anymore
```

I recently saw a [talk](http://www.youtube.com/watch?v=p50xsL-iVgU) and found out that Github stashes the pull requests on the repo so that I could do this instead:

```
jekyll[master] $ git fetch origin pull/1869/head:so-long-excerpt
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 1), reused 6 (delta 1)
Unpacking objects: 100% (12/12), done.
From https://github.com/mojombo/jekyll
 * [new ref]         refs/pull/1869/head -> so-long-excerpt
```

Maybe we could change hub's checkout command so that if fork doesn't exist, it'll take the above route to fetch the pull request. Not sure how to reveal the two different paths of "checkout" to the user.

**Comment by mislav** [comment]
hub in master branch now checks out `refs/pull/XY/head`, making it possible to checkout PRs whose fork got deleted. This was the behavior for a while now; I just forgot to mark this as fixed.
