### ISSUE TITLE
hub + gh = GitHub CLI

### ISSUE THREAD

**Issue by mislav** [github/hub#475]
@technoweenie had this idea (backed by @calavera) that we adopt the awesome work on the Go port of hub (by @jingweno) as the official GitHub thing and call it “GitHub CLI”.

I :+1: this. My Ruby implementation of `context.rb` is getting unwieldy and in hub v1.11 I feel I've reached the limit of how much I can speed up hub exection. I can't make it much faster than 50 ms due to Ruby interpreter slowness. Go port can execute in under 10 ms, and it's not even specially optimized yet. Go port can also be distributed as a pre-compiled binary, skipping the need to install Ruby, which can be especially tricky and error-prone for Windows users.

I've merged [jingweno/gh](https://github.com/jingweno/gh) with hub and pushed that to the "gh" branch here. It's all still rough, but it's a good start. More than half of the Cucumber suite in `features/` already passes. The plan is that the next major release of hub will be Go-powered and our Ruby implementation gone by that point.

Some open questions:
1. [x] The project is publically going to be called “GitHub CLI”, but how do we call the executable? Ideally users would alias it as `git`, so it doesn't matter. We can keep it as `hub` for compatibility, or we could name it `gh` for shortness.
2. [x] The next release will be a major release, so we can afford breaking API changes, but how much backwards compatibility do we want to keep? I say as much as possible, sans stuff that is currently deprecated and which we'll drop. That means we should support:
   - Existing commands. I'm open to breaking & improving `hub browse`, though.
   - YAML configuration in `~/.config/hub`, although we should save the OAuth token elsewhere.
   - `hub.protocol` & `hub.host` git config options. But we could move the values to YAML config.
3. [x] Version number of the next release? I suggest the obvious v2.0.0.

/cc @defunkt since hub was originally his baby

**Comment by ferenczy** [comment]
I'm just wondering one thing: why is the `hub` executable so huge now (9.5 MB both Linux and Windows builds of version 2.2.1)?

Until now, I have been using the previous version written in Ruby (1.x) and for example version 1.12.2 had 84 kB. That's quite corresponding with what it does. But 9.5 MB is extremely huge. Why is that? Does it contain the Go interpreter? But even the whole Go interpreter can't be so huge, I guess.

Thank you :)

**Comment by methane** [comment]
You're right.
While Go is not an interpreted language, executable contains runtime (GC, scheduler) and large part of standard library.
It makes deploy very easy.  One binary contains all.

**Comment by mislav** [comment]
@methane is correct. We don't believe that people are so low on disk space that a 10MB binary would be a problem.

@ferenczy Ruby implementation was small but it was much slower and required Ruby on the system. The new binaries may be distributed without any extra dependencies to install.

**Comment by ferenczy** [comment]
Thank you guys. But still it seems way too much to me. It's caused by a library(ies) included most probably. Whole Python interpreter is up 2 MB. [According what I have googled](https://code.google.com/p/go/issues/detail?id=6853), simple "Hello world" binary in Go is also up to 2 MB (depending on a version of compiler).

**Comment by jingweno** [comment]
@ferenczy I wouldn't worry too much about the binary size. With the [download speed](http://www.netindex.com/download/allcountries/) nowadays, it takes less than 100 ms to download `hub`. There're [benefits](http://owenou.com/2013/12/22/fast-github-command-line-client-written-in-go.html) to write `hub` in Go, e.g., low memory usage, faster speed, easier to install etc.
