### ISSUE TITLE
Use "-p" for ssh access by default / doc

### ISSUE THREAD

**Issue by blueyed** [github/hub#49]
Is there any reason you do not want "-p" to be the default, with e.g. `hub clone`?

Using "-p" allows you to easily push, which this won't work with a http clone/push url.

I suggest using another option to disable ssh instead.

Also, "-p" is not documented anywhere, except for the examples and in the source itself, as far as I can see.

**Comment by udiboy1209** [comment]
I'm reviving a long settled matter I guess, but I would appreciate some config option to make ssh accesses / remote urls default. Maybe make `git config --global hub.protocol ssh` work. I am behind a firewall which blocks `git://` url port and so I have currently settled to using `https` urls. But I would prefer ssh as it provides better speed.

**Comment by mislav** [comment]
> Maybe make `git config --global hub.protocol ssh` work.

It works since 352ade68c089bf2aa3e511629968894d5fc63a18. Grab one of the 2.3.0-pre builds from the Releases section!

**Comment by udiboy1209** [comment]
Thats great! Thanks @mislav!
