### ISSUE TITLE
Error creating pull request: Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by pwaller** [github/hub#491]
With apologies to @mislav, I'm reviving #83, #413, #412, #435.

I'm reviving it because this has broken my (and others in my org) ability to use hub at all for months and I wasn't aware of the workarounds available in the above linked issues. I had assumed something had broken in my environment.

It broke for me because as a security precaution I clobbered all of my existing OAUTH tokens, which were originally generated by signing in at the command line. I expected the previous process (enter credentials at the command line) to work, but it doesn't any more, with no explanation as to why.

I did try to generate a ["personal access token"](https://github.com/settings/applications) and enter it when hub prompted me for a password but of course that didn't work. I expected it to work because of the description "They can be used instead of a password for Git over HTTPS, or can be used to authenticate to the API over Basic Authentication". But it doesn't.

The current experience is: `hub pull-request`, enter credentials, enter message, wait a few seconds, etc.

```
Error creating pull request: Unauthorized (HTTP 401)
```

Please close this issue once it is fully resolved such that the user experience at the command line is not broken, otherwise it's hard to teach newbies to use hub. One has to know that having 2FA enabled means you have to generate a token and edit a config file which is not at all apparent from the UI.

**Comment by viktornordling** [comment]
> ```yaml
> github.com:
> - user: pwaller
> - oauth_token: ACCESS_TOKEN
> ```

This led me astray. Should be:

```
 github.com:
 - user: pwaller
   oauth_token: ACCESS_TOKEN
```

Hopefully this helps someone, five years later! 😂

**Comment by hackaprende** [comment]
> @pwaller I'm sorry you had troubles authenticating. Let's start from the beginning: what is the outcome that you get when hub asks you for your GH credentials? It should ask you for username, password (your actual GH password; never stored), and 2FA code if you have that enabled. Does it ask you for all three, and fails after that? Is the error message that you pasted the full error output?
> 
> After you entered your actual GH credentials + 2FA code, even if the `pull-request` operation ultimately failed, can you check did hub manage to create a token for itself? It should be visible under [Personal access tokens](https://github.com/settings/applications), and its name should simply be "hub" with "repo" scope.
> 
> Ultimately, if you're still blocked on this, here is how you can provide auth info to hub manually:
> 
> 1. Create a Personal Access Token (like you did already). This acts as an OAuth token
> 2. Save the following information in `~/.config/hub`:
>    ```yaml
>    github.com:
>    - user: pwaller
>      oauth_token: ACCESS_TOKEN
>    ```

How do I create the Personal Access Token?
