### ISSUE TITLE
Feature request: optional organization argument to `fork`, etc.

### ISSUE THREAD

**Issue by geoff-codes** [github/hub#505]
Currently, `hub fork` and `hub pull-request` only will create forks in [user]/[repo].

I'd really like to be able to (optionally) fork the project under an [organization]/[repo].

There are a number of reasons why this would make sense, but here's mine: I always put projects for which I'm submitting PRs into an organization I've created [for this particular purpose](https://github.com/pullreq) since, well, [some people aren't so good](https://github.com/brianmario/charlock_holmes/pull/55#issuecomment-30437830) at following up on PRs in a timely manner; and I prefer not to clutter up "my" repos with a bunch of forks which need to remain for an indeterminate length of time.

I'd hack on this myself, but for the "hub's gonna go go" business.

**Comment by loupgaroublond** [comment]
+1 but this seems like a bug, not a feature

**Comment by sr105** [comment]
:+1:

**Comment by patcon** [comment]
:+1:

cc: @mrjcleaver

**Comment by geoff-codes** [comment]
Counting the dup and the naked +1, I believe that makes a full :raised_hands:

@rtomayko? @mislav? @bueller?

Or, I could stfu and go get me some effective golang, which is probably what I should be doing anyway.

**Comment by mislav** [comment]
@geoff-codes Here is [the line where forking happens](https://github.com/github/hub/blob/0900df0104e2422180b6377e471b2a320730f13c/commands/fork.go#L66). If this feature was to happen, then we should add a configuration option that accepts a name of an org that affects the fork operation.

**Comment by zerothi** [comment]
:+1: this feature would be awesome.

Having a fork of a project as a separate code and still being able to do PR across would be very useful.

**Comment by olalonde** [comment]
:+1:

**Comment by sjmulder** [comment]
Is anyone working on this? If not I might take a stab at it.

**Comment by mislav** [comment]
@sjmulder You're welcome to take a stab at it!
