### ISSUE TITLE
hub browse: improve support for opening a commit

### ISSUE THREAD

**Issue by blueyed** [github/hub#516]
I would like to open a specific commit using `hub browse`.

I have tried `hub browse $COMMIT`, but that tried to open the non-existing repo.

Probably a special syntax would be useful, e.g. `hub browse @$COMMIT`.

**Comment by yonilevy** [comment]
Any progress on making it easier than typing `git browse -- commit/$COMMIT`? I find I need this functionality quite a lot (this and hub pull-request are the only hub features I use). If you'd be willing to put that into hub, I'd love to submit a PR.

**Comment by mislav** [comment]
I'm interested in making it easier to browse specific commits/directories/branches/issues but I'm not sure what a good command syntax would be. I wouldn't like to change the argument format to `hub browse` to avoid breaking backwards compatibility. Maybe `hub open <arg>` and determine what the argument is by matching it to existing commit SHAs/branches? Anyway check out above linked issues for more context/discussions.

**Comment by yonilevy** [comment]
I read the linked issues, and I agree with you completely that using the `browse` verb isn't optimal for this, I wouldn't want to have to use a flag such as `-b` and you have backwards compatibility to consider, understood. I really like the `open` verb, in fact, I have a bash alias for this command and it's named `hubopen`.

I can try and create a PR with the behaviour you've described above, the matching can simply be done using `git rev-parse`, so it also supports stuff like `hub open HEAD^^^`. WDYT?

**Comment by shime** [comment]
I've also just tried 
```
hub browse $COMMIT
```
expecting it to open a specific commit. I don't like the idea of introducing another command that does the same thing as `browse`. Maybe some sort of mechanism for recognizing specific commits/directories/branches/issues can be added to `browse`, while still preserving backwards compatibility?

**Comment by sjackman** [comment]
I also tried `hub browse 1234567` without luck. I'd really to like to see this feature, and also `hub browse '#123'` to open a PR.
