### ISSUE TITLE
changing username on github does not register on `hub`

### ISSUE THREAD

**Issue by jbernsie** [github/hub#521]
i recently changed my github username (about a month ago if not more) and now when using hub on the command-line i still have to use my old username to do anything, apart from cloning, when using my current username it just returns a 404

**Comment by mislav** [comment]
@bernsie Does your issue still persist?

**Comment by axhamre** [comment]
Deleting `~/.config/hub` worked fine for me. This info could perhaps be in the docs?

**Comment by jbernsie** [comment]
> Deleting `~/.config/hub` worked fine for me. This info could perhaps be in the docs?

Probably not a horrible idea

**Comment by mislav** [comment]
This is still a bug; follow https://github.com/github/hub/issues/1944 for future updates
