### ISSUE TITLE
On the deprecation of issue to pull request conversion

### ISSUE THREAD

**Issue by cbeams** [github/hub#532]
I recently updated `hub`, and was dismayed to see this new warning introduced in 4f70dd126f46dec14fc341c97c18efae417743c7:

```
$ git pull-request -i 321
Warning: Issue to pull request conversion is deprecated and might not work in the future.
https://github.com/spring-io/sagan/pull/319
```

My team and I use issue-to-pull request conversion as a core part of our workflow. So useful is this feature that we [call it out](https://github.com/spring-io/sagan/blob/master/CONTRIBUTING.md#use-hub-for-pull-requests) in our contributor guidelines, and incite developers to install `hub` on the merits of this functionality alone.

Issue to pull-request conversion is a great way to evolve all the way from a question to a discussion to a committed contribution, keeping everything in context in a single issue. It would be a shame to see it go. If anything, I'd hoped that this workflow might be further promoted to first class status in the web UI as well.

Can you expand on why this is being deprecated? I realize that `hub` is not responsible for this change, but is rather a decision being made at the API level. Who can I lobby to reconsider that change?

**Comment by alexchandel** [comment]
I get the error:
```
Error creating pull request: Unprocessable Entity (HTTP 422)
Not allowed to change field "issue"
```
when trying to do this. How do I force hub to use the v3 API? I do not want to waste another issue no, since a single issue was created to update a URL, and a single commit is required to do so.

**Comment by mislav** [comment]
@alexchandel hub uses and will continue to use the v3 API. I sounds like you worked around your issue. The initial validation failure that you've got might have been a misleading message; sorry about that.

**Comment by scott-s4a** [comment]
I have my main repo  and I forked it and brought it locally and then created a branch… no problems making changes locally and then committing to my own fork at github, but then I want to issue a pull request from command line for my forked branch to my main repo - getting errors on command line - every thing I have looked at online suggests that it should work - what am I missing?

git remote -v 

origin   https://github.com/MYFORKEDREPO/my.git (fetch)
origin   https://github.com/MYFORKEDREPO/my.git (push)
remote    https://github.com/MAINREPO/main.git (fetch)
remote   https://github.com/MAINREPO/main.git (push)

git pull-request –m "Testing pull-request" –b MAINREPO:master -h MYFORKEDREPO:mybranch
