### ISSUE TITLE
-bash: hub: command not found

### ISSUE THREAD

**Issue by erwanjegouzo** [github/hub#533]
After running boxen, I followed the recommendation by deleting my homebrew instal.
Then, I nuked boxen and I'm now getting this error when running git:

```
-bash: hub: command not found
```

I haven't had any luck and couldn't find anything online. Would you happen to know how to fix this? Shall I rather create an issue on Boxen's repo?

**Comment by tam-vo** [comment]
I have same problem with this, after install via hub, invoke `hub version` but return `hub: command not found`

**Comment by tam-vo** [comment]
Not sure why but I found the binary under `/usr/local/bin` and this path is in my `$PATH` as well, but not sure why it said not found
