### ISSUE TITLE
Cannot get past authentication

### ISSUE THREAD

**Issue by dideler** [github/hub#579]
A few days ago I noticed I had two hub tokens in my [GitHub applications  panel](https://github.com/settings/applications). I deleted the one that said it hasn't been used recently.

When I try to authenticate via hub now, it fails.

```
$ git pull-request
github.com username: dideler
github.com password for dideler (never stored): 
two-factor authentication code: <temporary code from Google Authenticator>
Error creating pull request: Unauthorized (HTTP 401)
```

Maybe a fresh install will help. So first I tried re-installing hub from its repo, but when I ran `rake install` I got

```
$ rake install
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/share/man/man1/hub.1
/home/dennis/github/hub/Rakefile:124:in `block in <top (required)>'
Tasks: TOP => install
(See full trace by running task with --trace)
```

So I tried `sudo rake install` and that didn't complain.

I remove any hub applications from my GitHub applications panel, so hub can generate a new personal access token.

I removed `~/.config/hub` so hub can recreate it (just in case it doesn't prompt or overwrite).

But I still get `Error creating pull request: Unauthorized (HTTP 401)`. I'm pretty sure my password is correct, and I'm not entering an outdated 2FA code.

Also note that I use hub on two different computers. I don't know if that affects anything.

**Comment by ragunathjawahar** [comment]
Saved my day too! Thanks.
