### ISSUE TITLE
Config Issues (host, protocol, ssh...)

### ISSUE THREAD

**Issue by KaiSforza** [github/hub#599]
Hello,

I started using hub as a way to get around using a browser, and I must say that it works great. However, using hub at work has resulted in my finding that there are some configuration options that seem to do one thing but don't do that at all.

### ``hub.protocol``
This can be set to ``https`` to force ``https`` cloning instead of git/ssh. The assumption that I made was that setting it to ``ssh`` would force ``ssh`` connections, and not use ``git://``, however setting ``hub.protocol`` to ``ssh`` does not do this. If there was a way to force all repositories to be thought of as private, that would also work. Having to clone with ``-p`` gets pretty tedious after a while.

### ``hub.host``
Yes, I know that this is only for telling hub what hosts to treat as ``github.com``, but possibly add a ``hub.defaulthost`` that says "Instead of using regular github, default to using ``github.internal.foo`` as the URL. We can do this with exports, but then it is only in the shell environment.

I'm going to look into getting these set up on my own, but I have yet to really work with ruby, and what I make may look like complete and utter crap.

-- 
Thanks,
KaiSforza

**Comment by janl** [comment]
has this landed anywhere, yet? :)

**Comment by janl** [comment]
It appears that at least since 47a9aa9e, private repos automatically get the git@ urls.

My `brew install hub --HEAD` from December didn’t include this, but a current one does, yay :)

**Comment by KaiSforza** [comment]
Any progress on this for non-private repositories?

**Comment by KaiSforza** [comment]
I decided to make progress on it. See #865

**Comment by KaiSforza** [comment]
Fixed in #865

**Comment by brandonblack** [comment]
@KaiSforza thanks for sorting this out!

**Comment by rjbell4** [comment]
What about the default git host part of this?  The question was asked:
> However that would mean that every time you git create or git clone owner/repo, it would use your Enterprise instance by default. You sure you would be OK with that?
My answer in an unqualified "yes".  Our users will be contributing to our GitHub Enterprise instance 99% of the time, and any interaction with github.com will be very rare.  I'd like to be able to config the default host through the Git configuration, instead of through their environment.

**Comment by rjbell4** [comment]
For the part that pertains to the default GitHub host, I have created PR #1184
