### ISSUE TITLE
Confusing 401 from all hub extensions that require write access to Github APIs

### ISSUE THREAD

**Issue by dsyer** [github/hub#609]
This was bugging me for months, and finally I twigged that the [OAuth token](https://github.com/github/hub#github-oauth-authentication) was stale. So I deleted `~/.config/hub` and everything is now fine. But I shouldn't have had to know how to do that should I? Hub should prompt for authentication if it has a bad token. At the least we could put something more prominent in the README.

**Comment by matschaffer** [comment]
:+1: to this issue. I hit this error and had no idea how to re-auth myself:

```
❯ hub pull-request
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
```

**Comment by sjackman** [comment]
:+1:

**Comment by mizzao** [comment]
Yep, I also had to remove `~/.config/hub` when seeing this error.

**Comment by mislav** [comment]
This will be improved once #225 ships in a future release. Please subscribe to that thread for updates.
