### ISSUE TITLE
Add labels to pull requests

### ISSUE THREAD

**Issue by joaquinrulin** [github/hub#610]
It would be nice to allow tag pull requests with labels.

**Comment by Jaecen** [comment]
:+1: 

Assigning Milestones to a PR would be nice too.

**Comment by weapp** [comment]
:+1:

**Comment by walterdolce** [comment]
+100 :+1:

**Comment by goldhoorn** [comment]
Woahh i need it just tried to use a label but din't work so +1000

**Comment by MrGossett** [comment]
:+1:

**Comment by prophile** [comment]
:+1:

**Comment by joaquinrulin** [comment]
According to the [API specs](https://developer.github.com/v3/pulls/#create-a-pull-request), this is not supported :disappointed: 
Will have to wait for this to be implemented in the API.

**Comment by mislav** [comment]
> According to the API specs, this is not supported

I'm pretty sure [Add labels to an issue](https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue) should work with pull requests, too

**Comment by overture8** [comment]
:+1:

**Comment by zakgrant** [comment]
yes please... :+1:

**Comment by nlutsenko** [comment]
:+1: Yes, please.

**Comment by mislav** [comment]
This was added to master branch in #968 and is going to be a part of the next release!

**Comment by walterdolce** [comment]
Wooo! :tada:

**Comment by prophile** [comment]
Boss :+1:
