### ISSUE TITLE
Bash auto-complete on OSX

### ISSUE THREAD

**Issue by aik099** [github/hub#614]
Try typing this on OSX: `hub pull` and then TAB. The `pull-request` isn't available as possible option. When on Linux it works flawlessly.

The pull request functionality works, it's just auto-complete that doesn't work for it.

**Comment by danielgomezrico** [comment]
This is not working for me, tried adding: 
```
if [ -f $(brew --prefix)/etc/hub.bash_completion.d ]; then
    . $(brew --prefix)/etc/hub.bash_completion.d/hub.bash_completion.sh
fi
```
to my `.bash_profile` but still not working.

- git version 2.6.4 (Apple Git-63)
- hub version 2.2.2
- Homebrew 0.9.5 (git revision 09f9; last commit 2016-01-15)

how can I do the setup?

**Comment by mislav** [comment]
@danielgomezrico Did you load git's own bash completion script before loading hub's? I don't know exactly where it is for Apple Git-63, but it should be somewhere on the system.

**Comment by danielgomezrico** [comment]
@mislav you mean using something like this? https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

No, I tried tag with git command but theres no autocomplete for it neither.

**Comment by mislav** [comment]
@danielgomezrico Well, the way to load hub's completion is to first load git's own completion (it should complete git commands in the terminal), then when you verify that works, load hub's completion and restart the shell again.

**Comment by ushuz** [comment]
I installed both Git and Hub through Homebrew. The auto completion worked just fine until recently. `hub [TAB]` only gives me `git`'s command but not `hub`'s. I'm not sure the cause, the Apple Git,  Homebrew Git and Hub had all been upgraded in the meantime.

```
$ /usr/local/bin/hub --version
git version 2.18.0
hub version 2.5.0

$ /usr/bin/git --version
git version 2.15.1 (Apple Git-101)
```

**Comment by mislav** [comment]
@ushuz See https://github.com/github/hub/issues/1792#issuecomment-403413131
