### ISSUE TITLE
Permission denied @ rb_sysopen - /usr/local/bin/hub when installing

### ISSUE THREAD

**Issue by AlexVPopov** [github/hub#627]
I am trying to install Hub on LInux Mint 17 (14.04) with ruby 2.1.2. I followed the install instructions and `bundle` passes, but `rake install` gives:

```bash
rake aborted!
Permission denied @ rb_sysopen - /usr/local/bin/hub
/home/sopharma/Code/hub/Rakefile:121:in `block in <top (required)>'
Tasks: TOP => install
(See full trace by running task with --trace)
```

Any help would be appreciated.

**Comment by mislav** [comment]
New versions of hub are no longer implemented in Ruby and don't have `rake install` task anymore. Instead, each prebuilt release will come with an installer script. See #922
