### ISSUE TITLE
`hub fork` fails when GHE returns 404

### ISSUE THREAD

**Issue by nikreiman** [github/hub#660]
When I try to fork a repo which is located on a GHE server, I get an error message "No decoder found for format  (text/html; charset=utf-8)". I've built hub from source from master, and its version reports `git version 1.9.1` (repo hash is 456adff).

Updates from https://github.com/github/hub/issues/660#issuecomment-60888761: while the authentication problem was fixed in https://github.com/github/hub/pull/669, GHE returns 404 for `hub fork`:

``` sh
master u=!po-test> HUB_VERBOSE=1 hub fork
> GET https://ghe.mycompany.net/api/v3/repos/nik/test
> Authorization: token [REDACTED]
< HTTP 404
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> POST https://ghe.mycompany.net/api/v3/repos/po/test/forks
> Authorization: token [REDACTED]
< HTTP 404
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
master u=!po-test> git remote -v show
origin  git@ghe.mycompany.net:po/test.git (fetch)
origin  git@ghe.mycompany.net:po/test.git (push)
master u=!po-test> hub --version
git version 1.9.1
hub version 2.2.0-preview1
```

**Comment by mislav** [comment]
@nikreiman Is this still an issue. Is it possible that you've upgraded your Enterprise instance since then?

**Comment by nikreiman** [comment]
@mislav I'm not sure, I gave up on hub some time ago, and I also no longer work at the company with GHE.

**Comment by mislav** [comment]
Closing due to stale
