### ISSUE TITLE
[FR] $GITHUB path for cloning repos?

### ISSUE THREAD

**Issue by nathany** [github/hub#689]
Is there a way to set the path to the root of all local GitHub code and have it automagically clone to there?

This is what I'd like to do. Set a path with some environment variable:

```
export $GITHUBPATH=$HOME/src/github.com
```

Run hub clone:

```
hub clone oreillymedia/HTMLBook
```

And have hub put the code into `~/src/github.com/oreillymedia/HTMLBook`, creating the necessary directories. This could even work regardless of my current working directory.

Of course this in inspired by `go get`, but without being specific to Go, or even requiring that Go be installed.

What do you think?

**Comment by weberc2** [comment]
I'd like to +1 this feature request--it would be very useful to Go developers and anyone else who prefers this structure. If `$GITHUBPATH` is unset, it could do the normal git behavior (cloning into $PWD/project) thereby not affecting users who don't want this feature.

What's the roadmap for CLI extensibility? Is this feature being tracked somewhere?

**Comment by mislav** [comment]
We had it planned in our minds but [now I've added it to our roadmap](https://trello.com/b/5MKBrz9K/github-cli). It might take a while to develop. Suggestions how users could technically hook into hub and define their own behaviors is welcome. Ideally they shouldn't be required to write Go code.

**Comment by nathany** [comment]
Did something like this ever happen? All the linked issues are closed.

@homburg suggested I use https://github.com/homburg/git-get
