### ISSUE TITLE
Autocomplete branch names

### ISSUE THREAD

**Issue by Linuus** [github/hub#707]
Hi

I'm using zsh with oh-my-zsh. I can do this `git branch -d fix/<press-tab>` to make it autocomplete the branch name. However, if I add the hub alias this breaks.

Is this a known issue?

**Comment by prior** [comment]
+1

**Comment by mislav** [comment]
Closing in favor of the above suggested workaround. We have a number of zsh and oh-my-zsh issues open already and we'll work on getting completion scripts better in the future. Right now zsh script is a bit of a mess. Please subscribe to #788 for updates.
