### ISSUE TITLE
hub pull-request does not populate list of changes

### ISSUE THREAD

**Issue by skrobul** [github/hub#730]
My workflow is relatively common - one 'main' repo on the organization account, several contributors with their public forks of the repo. I am usually working on the features in separate branches that I push into my public fork, then using `hub` I open pull requests.

Unfortunately for some time now, `hub` does not pre-populate pull request message with list of commits. This was very useful functionality, without it I have to open separate terminal window with `git log` just to see what has been changed in this particular feature branch. It could be something with my configuration, but I am having difficulties trying to find what's wrong. Is this common issue?

My setup:
* `upstream` remote represents main organization repository
* `origin` remote represents my individual repository

After I push all my commits to `origin/feature-branch` and issue `hub pull-request`, my editor opens and displays following pre-populated message:

```
# Requesting a pull to upstream:master from skrobul:feature-branch
#
# Write a message for this pull request. The first block
# of text is the title and the rest is description.
```

Please note that it kind of works, I can write my own message and submit pull request without problem, it's just the list of commits that is missing from the message. Correct me if I'm wrong, but [it looks like `hub` should insert](https://github.com/github/hub/blob/af9163b699b34ffa167ef99853ff2f7374d7b01a/commands/pull_request.go#L228) commented list of commits.

```
$ hub --version
git version 2.1.3
hub version 2.2.0-preview1
```

```
$ git remote show origin
* remote origin
  Fetch URL: git@github.mycompany.com:skrobul/salt-marek.git
  Push  URL: git@github.mycompany.com:skrobul/salt-marek.git
  HEAD branch: master
  Remote branches:
    master                                     tracked
    feature-branch                             tracked
  Local branches configured for 'git pull':
    master                 merges with remote master
  Local refs configured for 'git push':
    master                       pushes to master                       (fast-forwardable)
    feature-branch                  pushes to feature-branch                  (up to date)
```

```
$ git remote show upstream
* remote upstream
  Fetch URL: git@github.mycompany.com:myorg/salt-master.git
  Push  URL: git@github.mycompany.com:myorg/salt-master.git
  HEAD branch: master
  Remote branches:
    master                                           tracked
    refs/remotes/origin/feature-branch               stale (use 'git remote prune' to remove)
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

Any ideas how to fix/troubleshoot this?

**Comment by hisavali** [comment]
@skrobul Did you managed to pre-populate message? May I request you to provide gist of it?

**Comment by skrobul** [comment]
@hisavali yes, after I swapped `origin` with `feature` remote, the commit messages get prepopulated as expected. I don't have any specific example on hand, but the message was essentially the commented output of `git log`

**Comment by mislav** [comment]
@skrobul I'm glad you solved it and thanks for the update. Our branch detection isn't perfect right now. We'll work on improving it in future releases. In the meantime, I'm closing this because we're aware of this issue through other reports. #928 #877 #789 #461
