### ISSUE TITLE
Installation from the source throws command not found exception

### ISSUE THREAD

**Issue by geekgugi** [github/hub#731]
When trying to install from source, the command

```
$>./script/build 
```
throws an error ./script/build: line 34: go: command not found.

If this is because of any dependency, then corresponding dependency has to be mentioned in installation document.

**Comment by mislav** [comment]
Our [CONTRIBUTING](https://github.com/github/hub/blob/b64cc38f43d4599c927f5067639659a4640a152c/CONTRIBUTING.md) document states upfront that you need Go 1.4 or newer.
