### ISSUE TITLE
FR: customizable remote names when hub fork a repo

### ISSUE THREAD

**Issue by yegle** [github/hub#754]
`hub fork` works a little bit counter-intuitive to me.

The following is the manual way to fork a repo before I know this great tool `hub`

1. Go to https://github.com/github/hub, fork to my github
2. On my workstation, `git clone git@github.com:yegle/hub`
3. Optionally I'll create an `upstream` referring to `https://github.com/github/hub`

But `hub fork` will use `origin` to refer to the ORIGINAL repo while manual forking will have `origin` refer to your forked repo. I'd suggest use `upstream` or any customizable name to refer to the ORIGINAL repo, while still use `origin` to refer to your forked repo.

Possibly related issue: #697 and #720

**Comment by brock** [comment]
:+1: 
Similar to the discussion here https://github.com/isaacs/github/issues/280

I'd love it if `hub fork` cloned my fork, set my forks remote as "origin" and set the original project as "upstream" as is outlined in the Github documentation here: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by kbrock** [comment]
:+1: this matches my workflow to a T.

**Comment by mislav** [comment]
Closing in favor of the longer discussion in #762. We'll try to make this configurable in the future.
