### ISSUE TITLE
hub does not support the `-c` flag

### ISSUE THREAD

**Issue by georgebrock** [github/hub#756]
The `-c` flag can be used to override configuration options for a given command, e.g.:

```
$ git -c core.editor=/usr/bin/emacs commit
```

Passing the `-c` flag to a `hub` command causes the regular Git binary to execute the command instead of the `hub` binary:

```
$ hub pull-request
Aborted: head branch is the same as base ("master")
(use `-h <branch>` to specify an explicit pull request head)
$ hub -c core.editor=/usr/bin/emacs pull-request
git: 'pull-request' is not a git command. See 'git --help'.
```

(This is causing problems for `gitsh` users who want to use `gitsh` with `hub`: https://github.com/thoughtbot/gitsh/issues/206)

**Comment by jingweno** [comment]
Good find! This is indeed a problem that we don't [consider the `-c` global flags](https://github.com/github/hub/blob/master/commands/args.go#L183-L199).

**Comment by jingweno** [comment]
It's fixed in https://github.com/github/hub/pull/764

**Comment by georgebrock** [comment]
Thanks for fixing this, @jingweno

**Comment by mislav** [comment]
Nice work, thanks!
