### ISSUE TITLE
How to install zsh completetion

### ISSUE THREAD

**Issue by bolasblack** [github/hub#757]
I source the file `etc/hub.zsh_completion` but it print some error:

```
_default:compcall:12: can only be called from completion function
_arguments:comparguments:312: can only be called from completion function
_default:compcall:12: can only be called from completion function
```

**Comment by jingweno** [comment]
Did I miss anything, the line number doesn't match the ones from https://github.com/github/hub/blob/master/etc/hub.zsh_completion?

**Comment by bolasblack** [comment]
Now the error has changed:

```
> /tmp $ source hub.zsh
_arguments:comparguments:312: can only be called from completion function
_default:compcall:12: can only be called from completion function
```

**Comment by blueyed** [comment]
@bolasblack 
It's not meant to be sourced.

You need to copy / symlink it as _hub into your $fpath.
While at it, you might be interested in checking out an improved version from my PR #788.

**Comment by bolasblack** [comment]
@blueyed Thanks for your reply.

I use `wget` to download the `hub.zsh_completion`, renamed as `_hub`, then execute command `fpath=(/tmp $fpath)` and `autoload _hub`.

But when I use `hub creat<tab>`, there is no complete list appear.

Does any step I lost?

**Comment by blueyed** [comment]
@bolasblack 
Instead of `autoload _hub` try calling `compinit`.
Also see `which _hub` then after you've attempted to complete, and make sure that it's the correct one.

**Comment by bolasblack** [comment]
@blueyed It's not work for me :(

```bash
> /tmp $ ls /tmp/functions
_hub
> /tmp $ fpath=(/tmp/functions $fpath)
> /tmp $ compinit
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y%                                                                                                                                      > /tmp $ which _hub
_hub () {
        # undefined
        builtin autoload -XUz
}
> /tmp $ compinit _hub
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y%                                                                                                                                      > /tmp $ which _hub
_hub () {
        # undefined
        builtin autoload -XUz
}
> /tmp $
```

My `$fpath` is:

```
/Users/user/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting.git/
/Users/user/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/colored-man
/Users/user/dotfiles/zshfiles/functions/
/usr/local/share/zsh/site-functions 
/usr/local/Cellar/zsh/5.0.7/share/zsh/functions
```

The first and second entry is added by [antigen](https://github.com/zsh-users/antigen)

**Comment by blueyed** [comment]
@bolasblack 
After `compinit`, the completion should be available.
You have not tried `hub crea<tab>` afterwards, do you?

btw: you should create a custom `functions` dir somewhere in your home dir, add that one to $fpath, and then compinit is usually called in your zshrc anyway, isn't it?

**Comment by bolasblack** [comment]
@blueyed Excuse me, I didn't tried……

After I tried, I found `which _hub` became

```bash
_hub () {
        service=git
        _git
}
```

But it didn't complete `hub creat<tab>` yet……

This is my .zshrc:

```bash
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

#source ~/dotfiles/zshfiles/zshrc
#antigen bundle github/hub etc/hub.zsh_completion

# _hub file puted in ~/.zsh-functions
fpath=($HOME/.zsh-functions/ $fpath)

autoload -U compinit && compinit

PATH="/usr/local/bin:/usr/local/sbin:$PATH"
PATH="$HOME/.rbenv/bin:$PATH"
PATH="$PATH:$HOME/Library/Python/2.7/bin:$HOME/pebble-dev/PebbleSDK/bin"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
if which hub   > /dev/null; then eval "$(hub alias -s)"; fi

export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer/"
export PHANTOMJS_BIN=/usr/local/bin/phantomjs
export RBENV_VERSION=""
```

**Comment by blueyed** [comment]
We're getting closer.. ;)

> But it didn't complete `hub creat<tab>` yet

Does it do anything? Some error?

Does the completion for `git` still work?

You are not using `antigen` currently, but only put `_hub` into the `$fpath`, correct?

> After I tried, I found which _hub became
> _hub () {
        service=git
        _git
}

This should only happen after it has been invoked once.

Initially it should be:

    _hub () {
        # undefined
        builtin autoload -XUz
    }

And then after `hub <tab>`, it should get loaded.

What is the output for `which _git`?

**Comment by bolasblack** [comment]
@blueyed I'm so thanks for your kind...

When I testing, I will comment antigen and open a new shell.

`hub creat<tab>` print nothing, but the `git` completion is still work.

I use homebrew installed git and hub, I found there are `_git` and `_hub` in `/usr/local/share/zsh/site-functions/` just now. But after I deleted `/usr/local/share/zsh/site-functions/_hub`, the completion still not work and print nothing.

Then I move `$HOME/.zsh-functions/_hub` to `/usr/local/share/zsh/site-functions/_hub` , but nothing changed :(

About `_git`:

```bash
c4605% which _git
_git () {
        # undefined
        builtin autoload -XUz
}
c4605% which _git
_git () {
        local _ret=1
        local cur cword prev
        cur=${words[CURRENT]}
        prev=${words[CURRENT-1]}
        let cword=CURRENT-1
        if (( $+functions[__${service}_zsh_main] ))
        then
                __${service}_zsh_main
        else
                emulate ksh -c __${service}_main
        fi
        let _ret && _default && _ret=0
        return _ret
}
c4605%
```

**Comment by blueyed** [comment]
You appear to be using the git completion distributed with Git (contrib/completion/git-completion.zsh), and not the one from Zsh.

What is the output from

    for f in $fpath; do echo $f; ls -l $f/_git 2>/dev/null; done

I think the current problem is that the new, simplified completion from my PR is not working with the completion distributed with Git, but I wonder why and where you are getting it from.
Have you installed it manually, e.g. also by putting it in `$HOME/.zsh-functions/`?

(It would work prpobably, if you used the `_hub` file from hub's master (and not my PR): https://github.com/github/hub/blob/master/etc/hub.zsh_completion - but only do so after )

**Comment by bolasblack** [comment]
@blueyed The result of command:

```bash
% for f in $fpath; do echo $f; ls -l $f/_git 2>/dev/null; done
/usr/local/share/zsh/site-functions
lrwxr-xr-x 1 c4605 wheel 55 Feb  4 17:21 /usr/local/share/zsh/site-functions/_git -> ../../../Cellar/git/2.2.2/share/zsh/site-functions/_git
/usr/local/Cellar/zsh/5.0.7/share/zsh/functions
-rw-r--r-- 1 c4605 wheel 299400 Dec 21 22:41 /usr/local/Cellar/zsh/5.0.7/share/zsh/functions/_git
```

The `_hub` file is download from your PR, and now I have puted it in `/usr/local/share/zsh/site-functions/`, this folder is also in `$fpath`.

I tried the `hub.zsh_completion` from hub's master, it works.

Then I tried your file again, still not work for me :(

I think we can move our talk to your PR #788 now, I can test your file if you need, how about you think?
