### ISSUE TITLE
The "hub co" for pull request on renamed repo fails

### ISSUE THREAD

**Issue by aik099** [github/hub#768]
There 2 repos:
* https://github.com/Behat/docs
* https://github.com/minkphp/docs

If you try to fork both of them into same account you run into naming conflict and are forced to fork either of repos under different name.

For example try:

1. clone https://github.com/minkphp/docs repo
2. do `hub co https://github.com/minkphp/docs/pull/45`

It fails with this error:
```
fatal: Couldn't find remote ref refs/heads/session
error: Could not fetch stof
```
This is because attempt is made to to read `docs/session` ref from `Behat/docs` fork.

I think that we shouldn't assume that every forked repo is named the same and use GitHub API for detecting actual fork name for every user.

**Comment by aik099** [comment]
Currently I was able to mediate that problem by editing path to a remote after the error was shown and then repeating the command.

**Comment by jingweno** [comment]
> fatal: Couldn't find remote ref refs/heads/session
> error: Could not fetch stof

I looked at the [PR](https://github.com/minkphp/docs/pull/45) you want to checkout and it's to merge `minkphp:master` from `stof:session`. However, the https://github.com/stof/docs repo doesn't have the branch `session`. That's why your fetch failed.

> I think that we shouldn't assume that every forked repo is named the same and use GitHub API for detecting actual fork name for every user.

We're using the GitHub API for actual fork name, e.g. the Go implementation https://github.com/github/hub/blob/master/commands/checkout.go#L69.

**Comment by aik099** [comment]
> I looked at the PR you want to checkout and it's to merge minkphp:master from stof:session. However, the https://github.com/stof/docs repo doesn't have the branch session. That's why your fetch failed.

Of course it doesn't. It's because `https://github.com/stof/docs` is fork from `https://github.com/Behat/docs `, but I'm executing that command on `https://github.com/minkphp/docs` clone and expecting that repo fork to be found through that PR.

**Comment by mislav** [comment]
@aik099: This might be a GitHub bug. Thanks for reporting.

It might be that stof first opened the PR, then renamed his `docs` repo to be named `mink-docs`. That made the information about the fork name in the PR stale. We'll have to solve it on GitHub's end.

In the meantime, here's how to checkout any PR without using hub:

```bash
git fetch origin "+refs/pull/${num}/head:refs/pr/${num}"
git checkout -b "$branch" "pr/${num}"
```

**Comment by mislav** [comment]
@jingweno Actually, only the `label` property of the PR is stale. We should be using the `head.repo` property instead.

```json
{
  "url": "https://api.github.com/repos/minkphp/docs/pulls/45",
  "number": 45,
  "state": "open",
  "title": "Rewrite the session chapter",
  "user": {
    "login": "stof",
    "id": 439401,
  },
  "merge_commit_sha": "a684b5a5a8a9d7583e08f0aed5710a6f375ff67e",
  "head": {
    "label": "stof:session",
    "ref": "session",
    "sha": "296d69704b039e1bb5c2f1ce061005c63dbed7ce",
    "user": {
      "login": "stof",
      "id": 439401,
    },
    "repo": {
      "id": 28839329,
      "name": "mink-docs",
      "full_name": "stof/mink-docs",
      "owner": {
        "login": "stof",
      },
      "private": false,
      "html_url": "https://github.com/stof/mink-docs",
      "fork": true,
    }
  },
  "base": {
    "label": "minkphp:master",
    "ref": "master",
    "sha": "afed839c6a7805c2835cbd8ad4299240105eeee4",
    "user": {
      "login": "minkphp",
      "id": 10380339,
    },
    "repo": {
      "id": 2093133,
      "name": "docs",
      "full_name": "minkphp/docs",
    }
  }
}
```

**Comment by aik099** [comment]
Thanks for looking into that.

It's actually the first time I had this issue because usually all repos have unique names (even without user/organization name).

**Comment by mislav** [comment]
@jingweno Oops, sorry, it's kinda late and I'm not thinking straight. The `label` property is alright and the complete API response looks correct. There's no GitHub bug here.

It might be a hub bug then? The `stof/mink-docs` repo indeed has the "session" branch.

@aik099 How do you think the `Behat/docs` repo comes into play here? When you `git config remote.stof.url` after the failed checkout, which URL does it display?

**Comment by aik099** [comment]
As you know when you fork a repo, then GitHub replaces user/organization name of original repo with yours to create new repo name. I guess @stof originally forked `Behat/docs` repo into `stof/docs` repo.

Then after some time when he decided to fork `minkphp/docs` the GitHub was confused and asked (I'm just guessing here) for Stof to pick up a new name for his fork because `stof/docs` is already taken by another repo (fork or not).

By the way you can see in GitHub API output that `stof/docs` is never mentioned there, so it's Hub's wild guess that fork name is `stof/docs` by combining part before `:` from `head.label` with original (non-forked) repo name :wink:

**Comment by stof** [comment]
I guess that hub does not read the ``repo`` section at all.

Btw, hub could decide to fetch the ``refs/pull/45/head`` reference from the origin repo, which would allow to get the code of a PR even when the source repo has been deleted from github. This would avoid having to know the name of the fork repo altogether

**Comment by aik099** [comment]
Name of the fork is still needed because Hub creates remote with username of whoever created a fork and pulls branches for each pull request into it.

**Comment by stof** [comment]
Well, read my comment again: I'm saying it is not necessary to access the content of pull requests (and it limits it to PRs where the source repo has not been deleted)

**Comment by aik099** [comment]
> and it limits it to PRs where the source repo has not been deleted

Are you sure, that even though forked repo is deleted or branch, which was PR source was deleted the GitHub still retains changes made in that PR when it wasn't merged yet?

**Comment by aik099** [comment]
If source repo is deleted, then you can't use Hub in general by the way, because you clone source repo (not own fork) and use `hub` command on it.

**Comment by stof** [comment]
@aik099 I'm talking about the source of the PR, not about the upstream repo. The target repo of a PR keeps the reference even when the source is deleted

**Comment by jingweno** [comment]
@mislav I saw [a spec that deliberately prefers `label` over `repo`](https://github.com/github/hub/blob/master/features/merge.feature#L67-L83). Is it still true, considering we'd want to prefer `repo` over `label` in this case. There's [another one](https://github.com/github/hub/blob/master/features/merge.feature#L85-L98) having the same expectation.

**Comment by aik099** [comment]
The second one looks like what we need, but it applies only on `hub merge` command, but I was using `hub co` command.

**Comment by jingweno** [comment]
@aik099 The second one prefers `label` over `repo` though, which causes the problems you met. From @mislav JSON blob, the `label` is `stof:session` while the `repo` is `stof/mink-docs`. My intuition is we should use `repo` instead but need to confirm if the spec is still valid and what problem it tries to solve.

**Comment by jingweno** [comment]
Ah, I think I know why. The [changes are only in `git-merge` but not in `git-checkout`](https://github.com/github/hub/commit/e723fd3bc37637704d5b8bc15c7d1428af6cb457). I'll provide a fix.

**Comment by mislav** [comment]
Thanks for your patience @aik099 @stof :bow:

**Comment by aik099** [comment]
Thanks.
