### ISSUE TITLE
Fork command on GitHub Enterprise prompts with incorrect hostname

### ISSUE THREAD

**Issue by mislav** [github/hub#769]
While in a repo hosted on `ghe.io` (GitHub Enterprise instance):

```
$ git fork
github.com username: mislav
ghe.io password for mislav (never stored):
```

Although the 2nd prompt was correct, the first prompts for `github.com` username which is definitely wrong since no git remotes in my local repo point to to `github.com`.

**Comment by jingweno** [comment]
Good find. Fixed in https://github.com/github/hub/pull/770
