### ISSUE TITLE
zsh tab-completion doesn't work

### ISSUE THREAD

**Issue by dlion** [github/hub#771]
>\> source hub.zsh_completion 
> _call_function:27: compstate: assignment to invalid subscript range

My version of zsh is
> zsh 5.0.2 (x86_64-slackware-linux-gnu)

and my git/hub version are
> git version 1.8.4
> hub version 2.2.0-rc1

Thank you

**Comment by nbraud** [comment]
Works here on zsh 5.0.5.
You might want to try upgrading your zsh and see if this fixes the issue.

**Comment by blueyed** [comment]
@dlion 
It's not meant to be sourced.
You need to copy / symlink it as `_hub` into your `$fpath`.
While at it, you might be interested in checking out an improved version from my PR #788.

**Comment by lorenzhs** [comment]
It would be great if that were documented in the README, I was wondering the same thing.

**Comment by blueyed** [comment]
@lorenzhs 
Do you feel like providing a PR to fix / address this?
Also, have you tried my PR (#788)?

**Comment by nunoh** [comment]
I have the exact same issue. A small explanation follows.

I had git autocompletion working. I added `eval "$(hub alias -s)"` to my `.zshrc` and even though doing something like `git browse` does work (writing all the characters that is) if I try something like `git s<tab>` I get the standard zsh file completion rather than git/hub specific. Also, in my `$fpath` I have the an `_hub` symlink. Any ideas what I might be missing?

I am using version zsh 5.0.7 and hub 2.2.0-g3ea5a9a.

**Comment by blueyed** [comment]
> if I try something like git s<tab> I get the standard zsh file completion rather than git/hub specific

Do you get this completion without the `hub=git` alias?
Do you have the `COMPLETE_ALIASES` zsh option set? (should not be set)

**Comment by nunoh** [comment]
If I remove the `eval "$(hub alias -s)"` from my `.zshrc` then I have git autocompletion working ok. 
And no, I don't have that option set. Any idea?

**Comment by blueyed** [comment]
@nunoh 
`hub alias -s` is only `alias git=hub`, right?
You could try the _complete_debug widget (`^X?`), which should provide you with debugging output for completion.
Apart from that, my PR at #788 might also help.

**Comment by nunoh** [comment]
@blueyed 
I have only `alias git=hub` as alias. I ended up solving this issue in a different way, by copying the `_hub` completion file into a predefined folder in the `$fpath`. Thanks for your help anyway :bow:

**Comment by blueyed** [comment]
I think this issue can be closed: the completion script was not installed correctly in this case.

I'll leave another link to my pending PR to improve the Zsh completion: https://github.com/github/hub/pull/788 :)

**Comment by a-x-** [comment]
> It would be great if that were documented in the README, I was wondering the same thing.

**Comment by mislav** [comment]
Closing as user config error. Thanks everyone!
