### ISSUE TITLE
user: Current not implemented on linux/386

### ISSUE THREAD

**Issue by cebe** [github/hub#775]
Not sure what exaclty is missing here, but `hub am` is not working:

```
$ hub --version
git version 1.7.10.4
hub version 2.2.0-rc1
$ hub am -3 https://github.com/yiisoft/yii2/pull/6964
github.com username: cebe
github.com password for cebe (never stored): 
user: Current not implemented on linux/386
```

**Comment by cebe** [comment]
Seems to be the same with other commands:

```
$ hub checkout https://github.com/yiisoft/yii2/pull/6964
github.com username: cebe
github.com password for cebe (never stored): 
user: Current not implemented on linux/386
```

**Comment by mislav** [comment]
Seems like we're relying on some Go feature that is not sufficiently cross-platform. Could you tell us which Linux distro you're using?

**Comment by cebe** [comment]
Oh, looks like I was running a i386 binary on a amd64 system...

**Comment by mislav** [comment]
Weird that that the i386 binary even worked this far!

**Comment by jingweno** [comment]
`user.Current` uses cgo and it's [platform specific](https://github.com/golang/go/blob/439b32936367c3efd0dadab48dd51202e1a510f1/src/os/user/lookup_stubs.go#L19).

**Comment by cebe** [comment]
I have run it on a Debian system with multi arch support. So that's maybe the reason why it worked until that point. amd64 is the native arch, i386 is additional.
