### ISSUE TITLE
Default directory for installation

### ISSUE THREAD

**Issue by weberc2** [github/hub#783]
I organize my GitHub repositories in a `github.com/` folder (basically because I use Go a lot, but also because it's proven organizationally useful), so this repo would be located at `github.com/github/hub`. It would be nice if there were a `$HUB_DEFAULT_DIR` environment variable, which, when set, would allow `hub clone` to clone into that directory in the prescribed manner (in other words, `hub clone github/hub` would clone into `github.com/github/hub`, creating the directories as needed). When unset, the normal 'clone into $PWD/hub' behavior would be expected.

I can implement this feature if others think it useful (and will probably do so anyway on my private fork).

**Comment by hkdobrev** [comment]
I think this is duplicate of #689, #612, #328 and #322.

**Comment by weberc2** [comment]
After skimming those links, it looks like this is a duplicate of #689, but #612, #328, and #322 seem to be different (clone into $PWD/user/project instead of $GITHUB_ROOT/user/project). Thanks for pointing this out.
