### ISSUE TITLE
Wrong head for pull requests

### ISSUE THREAD

**Issue by kirelagin** [github/hub#789]
I’m trying to follow the example from the hub page and something goes wrong:

~~~~
› git clone valis/hoq
Cloning into 'hoq'...
<...>
Checking connectivity... done.

› cd hoq

› git checkout -b typo
Switched to a new branch 'typo'

<fix fix fix>

› git commit -a
[typo 479d82b] Fix typo

› git fork
Updating kirelagin
From git://github.com/valis/hoq
 * [new branch]      master     -> kirelagin/master
new remote: kirelagin

› git push kirelagin typo
Counting objects: 6, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 512 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To git@github.com:kirelagin/hoq.git
 * [new branch]      typo -> typo

› HUB_VERBOSE=1 git pull-request                
> POST https://api.github.com/repos/valis/hoq/pulls
> Authorization: token [REDACTED]
{"base":"master","head":"valis:typo","title":"Fix arrow","body":"x_x"}

< HTTP 422
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"missing_field","field":"head_sha"},{"resource":"PullRequest","code":"missing_field","field":"base_sha"},{"resource":"PullRequest","code":"custom","message":"No commits between valis:master and valis:typo"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}                       
Error creating pull request: Unprocessable Entity (HTTP 422)                                                                                                                                      
Missing filed: "head_sha"                                                                                                                                                                         
Missing filed: "base_sha"                                                                                                                                                                         
No commits between valis:master and valis:typo
~~~~

If I set the topic branch to track the relevant branch in my repo (`git push -u kirelagin typo), everything works as expected.

**Comment by woneill** [comment]
I ran into the same issue but my workaround was to specify the head as owner:branch. In your example, it'd be `git pull-request -h kirelagin:typo`

**Comment by kirelagin** [comment]
Yes, this works too for sure.
But I believe there should be a slash: `git pull-request -h kirelagin/typo` because that’s just the ordinary remote/branch syntax.

**Comment by mislav** [comment]
Thanks for the detailed steps to reproduce! BTW, what is your `git config push.default`

**Comment by kirelagin** [comment]
~~~~
› git config push.default
upstream
~~~~

**Comment by mislav** [comment]
Yeah, that might be what caused the bug. When someone has `upstream` setting configured for push, hub will expect upstream configuration to also be present for a branch, otherwise it will assume that the local branch wasn't yet pushed anywhere.

However since it's easy to forget the `git push -u` flag, this should be sorted once and for all.

**Comment by kirelagin** [comment]
I don’t think that hub should take `push.default` into account in this case…
And, anyway, hub’s current behaviour doesn’t make any sense.

**Comment by ElijahLynn** [comment]
Related issue #189.

**Comment by MasterRoot24** [comment]
I just got this issue as well, but `git config push.default` is set to `simple` 😕

**Comment by mislav** [comment]
This is caused by the same issue as described in https://github.com/github/hub/issues/877. Please follow other issue for updates. Thanks!
