### ISSUE TITLE
Create chocolatey package (Windows package manager)

### ISSUE THREAD

**Issue by twsouthwick** [github/hub#794]
Chocolatey is becoming a common way on windows to distribute packages (and will even be supported in Windows 10 with [OneGet](https://github.com/OneGet/oneget)).  I have created a [package](https://github.com/twsouthwick/github-cli-nuget) for hub and was wondering if there is any issue with me releasing it on the official [Chocolatey feed](https://chocolatey.org/).  I remember seeing somewhere that the preferred name will be something like 'github-cli' - if that is not the case, let me know and I'll change it for this.

Currently, I just did it for 2.x release (since it is standalone and the future of the product).  I can also do it for 1.x (which will also install ruby if it is not currently installed).

**Comment by twsouthwick** [comment]
I forgot to mention, that this package does not actually include the distributables; instead, it tells Chocolatey where to download them from.  It points to the links on the [release page](https://github.com/github/hub/releases), downloads it and extracts it.  Chocolatey determines 32-bit or 64-bit.

**Comment by mislav** [comment]
Interesting. Thanks for doing this. I have nothing against making hub easier to install on Windows, of course. And right now, we still call it "hub" until we make this an offical GitHub CLI tool.

You should feel free to publish it on their feed if you are going to commit to maintaing the listing for a while.

**Comment by twsouthwick** [comment]
Will do! So, I'll list it as "Hub" right now.

**Comment by jingweno** [comment]
Shall we update the README so that people are aware of a Chocolatey feed? I agree with @mislav that we rename the feed to "hub" for now.

**Comment by mislav** [comment]
On Sun, Feb 8, 2015 at 7:48 AM, Jingwen Owen Ou <notifications@github.com>
wrote:

> Shall we update the README so that people are aware of a Chocolatey feed?


Maybe after this percolates for a while. I'm usually wary about giving
exposure to package managers I'm not familiar with.

**Comment by twsouthwick** [comment]
I've published it as ['hub'](https://chocolatey.org/packages/github-hub/2.2.0) on the chocolatey feed.  It may take a couple days for it to pass through the approval process.

**Comment by mislav** [comment]
Hi @twsouthwick did the package ever reach approval?

**Comment by twsouthwick** [comment]
I got an email that it is approved - took a while! I see that a 2.2 release is now available - I'll update it for that.

**Comment by TheDoctorsLife** [comment]
Looking at the link he last provided, yes it did.
"This package was approved by moderator ferventcoder on 12/28/2015."

**Comment by mislav** [comment]
@twsouthwick How would I go about pushing updates to chocolatey feed? The last package for hub there is severely out of date by now.
