### ISSUE TITLE
Make Go requirement more explicit

### ISSUE THREAD

**Issue by eksperimental** [github/hub#795]
Hi,
I am having same issue as in #710.

I see in #712  that 1.3 is the minimum requirment for go.
I visited https://hub.github.com/ and it doens't saying anything in the frontpage about the a required version.

Also, the build script, you should check what version i'm running, to prevent having an error message that doesn't say anything about my Go version being too old.

thanks.

**Comment by jingweno** [comment]
We have a [bootstrap script](https://github.com/github/hub/blob/master/script/bootstrap) to check for environment. However the versions are not update-to-date and I've a [PR](https://github.com/github/hub/blob/master/script/bootstrap) to fix it. I'll add the line `script/bootstrap` before [`script/build`](https://github.com/github/hub/blob/gh-pages/index.html#L133) on our GitHub pages to clarify more.

**Comment by mislav** [comment]
Closing since we've updated our `bootstrap` script and instructions.
