### ISSUE TITLE
One Command test outputs text to stdout

### ISSUE THREAD

**Issue by mislav** [github/hub#801]
[This specific commands test](https://github.com/github/hub/blob/1409606542e9140324d8b9c113bdb095355f8b4b/commands/commands_test.go#L133-141) outputs `usage: foo` to stdout. This output is only visible if some other test in "commands" package fails.

Ideally, tests should output nothing to stdout, as all their output should be captured and asserted.

**Comment by filescoded** [comment]
Duplicate of #

**Comment by KHOENIX** [comment]
Leave a comment
