### ISSUE TITLE
pull-request from file on windows does not parse title, body correctly

### ISSUE THREAD

**Issue by jtrinklein** [github/hub#805]
When creating a pull request on windows using `hub pull-request -F pull.txt` where pull.txt is:
```
my pull title

my description

another line
```
will create a pull request with the title `my pull title my description another line` and with no body.

The root cause comes from readMsg function in [utils.go](https://github.com/github/hub/blob/master/commands/utils.go#L97) where the input file is split on `"\n\n"` to obtain title and body.

In windows this separator should be `"\r\n\r\n"`

**Comment by mislav** [comment]
Good catch. I think we should support both LF (unix-style) and CRLF (windows-style) line endings. I see no harm of even doing it on all platforms unconditionally. We could run any input through a filter that replaced every `\r\n` with `\n` before we do anything else.

@jingweno thoughts?

**Comment by jingweno** [comment]
We could try [`Scanner.Scan`](http://golang.org/pkg/bufio/#Scanner) from `bufio` which should deal with [line endings](http://golang.org/pkg/bufio/#ScanLines) in a cross platform way.
