### ISSUE TITLE
Can't merge pull requests

### ISSUE THREAD

**Issue by smockle** [github/hub#816]
Here are the steps I usually use to create and merge pull requests using hub: https://gist.github.com/smockle/af53148e4adfd2730256.

Those steps worked fine until a couple days ago. Then every time I ran `hub merge <pull_request_url>` I'd get
```
remote: Repository not found.
fatal: repository 'https://github.com/<name_of_feature_branch>/<name_of_repo>.git/' not found
```

I'm running git version 2.3.0 and hub version 2.2.0.

Here is my `~/.gitconfig`: https://github.com/smockle/dotfiles/blob/master/.gitconfig

I can merge the pull requests I create with `hub pull-request -m <message>` fine using the GitHub website. But I can't merge using `hub merge <pull_request_url>`.

**Comment by smockle** [comment]
I just reproduced this with a new repo:
```
clay$ mkdir foo
clay$ cd foo
clay$ git init .
Initialized empty Git repository in /Users/clay/Projects/foo/.git/
clay$ git create
Updating origin
created repository: smockle/foo
clay$ git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)
clay$ git branch
clay$ echo "hello world" > README.md
clay$ ls
README.md
clay$ git add .
clay$ git commit -am "Initial commit"
[master (root-commit) 84a8643] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
clay$ git status
On branch master
nothing to commit, working directory clean
clay$ git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

clay$ git push --set-upstream origin master
git cCounting objects: 3, done.
Writing objects: 100% (3/3), 226 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
o -To https://github.com/smockle/foo.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
bclay$ git co -b feature_readme
Switched to a new branch 'feature_readme'
clay$ echo "xyzzy" > README.md
clay$ more README.md 
xyzzy
clay$ git statu
git: 'statu' is not a git command. See 'git --help'.

Did you mean one of these?
	status
	stage
	stash
clay$ git statsu
WARNING: You called a Git command named 'statsu', which does not exist.
Continuing under the assumption that you meant 'status'
On branch feature_readme
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
clay$ git commit -am "Update README.md"
[feature_readme 14e1166] Update README.md
 1 file changed, 1 insertion(+), 1 deletion(-)
clay$ git push
fatal: The current branch feature_readme has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature_readme

clay$ git push --set-upstream origin feature_readme 
Counting objects: 3, done.
Writing objects: 100% (3/3), 256 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/smockle/foo.git
 * [new branch]      feature_readme -> feature_readme
Branch feature_readme set up to track remote branch feature_readme from origin.
clay$ git pr -m "Update README.md"
https://github.com/smockle/foo/pull/1
clay$ git co master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
clay$ git pull
Already up-to-date.
clay$ git merge https://github.com/smockle/foo/pull/1
remote: Repository not found.
fatal: repository 'https://github.com/feature_readme/foo.git/' not found
clay$ 
```

**Comment by mislav** [comment]
@smockle Thanks for the report. I can't reproduce this, however. If you can reliably reproduce this, it would be helpful if you could paste the output of this as a Gist:

```
HUB_VERBOSE=1 hub merge https://github.com/smockle/foo/pull/1
```

@jingweno This might be a bug in [`parseUserBranchFromPR`](https://github.com/github/hub/blob/e359d0918580acedcc7c6fe9f15e46c570582537/commands/utils.go#L44-45) when the "label" field contains no `:` character, just the branch name. From your code, it seems that you're treating this single component as a user name, when from the API docs it seems it should be treated as a branch name. I'll open a PR with a potential fix.

**Comment by smockle** [comment]
@mislav Thanks for looking into this! I just successfully merged the PR I'd created the other day. Then I created a new repo and PR following the same steps above, and that merge worked perfectly as well. I'm sorry, I'm not sure what would have changed. Should I close this issue?

**Comment by mislav** [comment]
Leave it open for now. It might be inconsistent results returned from GitHub API.

**Comment by lionfish7699** [comment]
（全体)
registという単語はないので、registration_dateとかcreate_dateとかに。
regist_addressとかはそもそもaddressでいいような。

**Comment by lionfish7699** [comment]
(company)
address_01とかだとどこまでかわからなくなりそうなので
名前つけたいですね。
もし郵便番号から住所ひく機能つけるなら市区町村まで引けるので
prefecture,city,address(建物名を含むそれ以下）ってかんじがいいかなぁ。
addressをさらにbuilding(null可）と分割してもいいかも。
