### ISSUE TITLE
Make "git push" work with 2FA

### ISSUE THREAD

**Issue by jkeiser** [github/hub#822]
I have hub installed, but when I run `git push` from a repository, I get this (and I'm pretty sure it's 2FA):

```
jkeiser@Ettores-MBP ~/s/chef-provisioning-aws> set -x GIT_TRACE 1
jkeiser@Ettores-MBP ~/s/chef-provisioning-aws> git push
Username for 'https://github.com': jkeiser
Password for 'https://jkeiser@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/chef/chef-provisioning-aws.git/'
```

I am entering the correct password (I know this because if I curl --user jkeiser https://api.github.com/orgs and enter the same password, I get back this:

```ruby
{
  "message": "Must specify two-factor authentication OTP code.",
  "documentation_url": "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}
```

I'd like for it to work.  I'd LOVE for it to work by fixing `git credential`, because I'm using that from a Ruby library, but that's not this bug :)

**Comment by mislav** [comment]
When you do `git push`, it's just regular git protocol stuff and hub doesn't do anything extra. I see you set up your repository clone URL over HTTPS, so that means you want username/password authentication instead of public key authentication via SSH. Of course, when you have 2FA enabled, your GitHub username & password is not enough to authenticate. You need to generate a Personal Access Token to use as "password" for your account for git push operations. Refer to GitHub help documentation for tips how to set this up.

I agree that this is what hub could help you do the first time when you set it up. Maybe in a future release it will help you set up your credential helper if you haven't done so yourself. Follow #464 for updates.

**Comment by j3pic** [comment]
Too bad Google leads here instead of to the "GitHub help and documentation" you mentioned. >:(

**Comment by stek29** [comment]
@j3pic https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by ashander** [comment]
Yes, but: hub does interact with 2FA when running `hub create` so it's disconcerting that it does not do the same when running `hub push`

**Comment by j3pic** [comment]
I'm not running `hub`. I'm using plain old `git`. In any case, my company's
DevOps team fixed my inability to push on our end.

**Comment by abrambailey** [comment]
> @j3pic https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

It would be nice if that link included a shortcut to where to create your keys. 

- For **public repositories**, [create a token](https://github.com/settings/tokens/new?scopes=notifications&description=Notifier%20for%20GitHub%20extension) with the notifications permission and specify it.
- If you want notifications for **private repositories**, you'll need to [create a token with the notifications and repo permissions](https://github.com/settings/tokens/new?scopes=notifications,repo&description=Notifier%20for%20GitHub%20extension).

**Comment by giovanib02** [comment]
You have to generate an **access token** and use the **access token** instead the password. 
For example:
$ git clone https://github.com/username/repo.git
Username: your_username
Password: your_token

Doc: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line

**Comment by hubyhuby** [comment]
Yes please make it SIMPLE to commit with 2 factor. It s nice to add more security, but if is getting more complicated less people will adopt it... 

Maybe I could receive a SMS when I am pushing, just like It does when I have login on the web interface of github ?

**Comment by SRGOM** [comment]
Too many check boxes, I want to just do a `git push`, which one should i check?

**Comment by erayerdin** [comment]
It would also be better if someone could mention exactly _which scopes_ I need for 2FA.

**Comment by GabrielBB** [comment]
So annoying. Github forced me to enable 2FA to be able to publish a Github Action

**Comment by taranu** [comment]
"Invalid username or password" is not an accurate or helpful error message.

**Comment by tengerye** [comment]
Token is too long to remember. It is quite trouble to push the codes now.

**Comment by fabiocaccamo** [comment]
@tengerye I agree, I think that a solution here could be to accept also the password followed by OTP (Google Authenticator).

**Comment by jmeile** [comment]
I'm under Windows and was experiencing this isssue as well. I tried the "Personal Access Token" and it worked; however, I found it a little bit complicated. Then I found a Credential Catcher helper app for windows:
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases

It first ask for your user and password, then the authentication token. The app creates automatically a "Personal Access Token" for you. Then it will use it each time that you push your code.

**Comment by onichandame** [comment]
I am having the same issue as well. It would be nice if a more convenient workflow of `git push` is available when 2FA is enabled.

Perhaps the first push fails but an SMS is sent at this time. Then the second push could use the SMS code as the password? Sounds a little bit hacky though.

**Comment by BenWhiteJam** [comment]
+1

**Comment by arendu** [comment]
+1

**Comment by cadaats** [comment]
As someone said, it should ask for 2FA after password to keep it simple like when logging into web.

**Comment by fabiocaccamo** [comment]
I think that this issue should be reopened.

**Comment by marcusluis** [comment]
+1

**Comment by khiav223577** [comment]
+1

**Comment by GaryPWhite** [comment]
This is not an intuitive workflow for authentication. We don't need an access token to log in online, why would I expect it to be different from the command line?

Not to mention the error message `remote: Invalid username or password. fatal: Authentication failed ` gives no indication of the actual problem.

**Comment by sightseeer** [comment]
It is so annoying. I have now tokens, ssh keys, passwords, googleauthenticatorpasswords and everything but I cant push anything now. It worked like a charm until I changed repository for another project and this is taking even more time thant the time I spent on the project itself.
Why is it so complicated to make an inital commit on an empty reposiitory????

**Comment by juanmirocks** [comment]
Not to mention that creating a "Personal Access Token" (which are essentially a password as GitHub tells in the [docs](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)), essentially **defeats the purpose of 2FA**.

In other words: why should we have 2FA for the web, but no 2FA for the command line?

**Comment by supersonnic** [comment]
You can switch to SSH authentication as opposed to HTTPS and use a ssh key to bypass having to type access token. Just follow these steps (linux).
1. Create a ssh key pair: https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
2. Make sure the keys pair has correct permissions:
sudo chmod 600 ~/.ssh/id_rsa
sudo chmod 644 ~/.ssh/id_rsa.pub
3. Add the public key to your github account: https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account
4. Test the connection: https://docs.github.com/en/github/authenticating-to-github/testing-your-ssh-connection
5. Update the repository's authentication method to ssh: https://docs.github.com/en/github/using-git/changing-a-remotes-url#switching-remote-urls-from-https-to-ssh
5. You can now use 'git push' and never have to enter access token or username.

**Comment by achilleslinux** [comment]
For solving this issue, You can also use clone using SSH 
![image](https://user-images.githubusercontent.com/12483219/89552257-8d0e3a00-d829-11ea-844d-31666c2cfe6b.png)

**Comment by etlfg** [comment]
> You can switch to SSH authentication as opposed to HTTPS and use a ssh key to bypass having to type access token. Just follow these steps (linux).
> 
> ...
> 
>     6. You can now use 'git push' and never have to enter access token or username.

F*ck*ng corporate proxy :disappointed:

**Comment by mislav** [comment]
Hi everyone, this turned to be a more general thread about authenticating git with GitHub in different environments and as such I don't feel like it belongs here in the hub repo, even though various google searches seem to lead here. Thank you to everyone who contributed their workarounds and advice! 🙇 

Hub does not handle _anything_ about git authentication, so setting this up is left as an exercise to the user based on their environment, network, corporate restrictions, and other factors. No one solution will fit everyone's case.

Most people will be able to solve their 2FA-related issues around git push/pull by following the instructions on https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
