### ISSUE TITLE
hub browse . unintuitive

### ISSUE THREAD

**Issue by raine** [github/hub#823]
Not sure if it's just me but if I often type `hub browse .` with the intent of opening current repo, while it opens my own profile. I think `.` should stand for current directory, i.e. the repo.

Thoughts?

**Comment by mislav** [comment]
The first argument to `hub browse` is either the repository name or the `owner/repository` combo. None of them are directories, and therefore it doesn't make sense to support `.` (a current directory reference on unix systems) as the first argument.

We'll work on improving `hub browse` in the future and make it easier to browse individual files and directories. The name of the command might change as well as the syntax. Stay tuned for future releases. But for now, it will stay as-is.

**Comment by raine** [comment]
Thanks for the explanation.
