### ISSUE TITLE
Zsh auto completion for pull request not populating

### ISSUE THREAD

**Issue by devshorts** [github/hub#825]
It looks from the hub completion file that once you get to `hub pull-request` you should get completion for other parameters like `-m` and `-h` but I don't seem to get anything. No errors, just no further completions.

```
$ zsh --version
zsh --version
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
```

```
$ hub --version
hub --version
git version 2.3.0
hub version 2.2.0-g217f4b5
```

I get other auto completes, so the completion is mostly working but pull request would be awesome to get fully working :)

**Comment by mislav** [comment]
Sorry that our completion is a mess right now. We will be working on making it better.

In the meantime you could share whether you use any zsh configuration packages such as oh-my-zsh, and if so which plugins do you load from it. The completions and aliases from these projects can negatively affect hub's own completions.

I trust that you've installed hub via Homebrew?

**Comment by devshorts** [comment]
I installed head from homebrew after removing my previous Hub. I'm acutally leveraging the vanilla install of yadr so it has a buttload of other completions.

However I did a check to see if there were any `hub*` completion files and there is only one, and I made sure to overwrite it from the provided hub completion file in the repo so ¯\_(ツ)_/¯

**Comment by blueyed** [comment]
There is currently just no support for this in the Zsh completion.
It provides the description, but no completions.

Any improvements to this should be based upon my simplification from https://github.com/github/hub/pull/788.

**Comment by mislav** [comment]
Sorry you had issues, @devshorts. Closing in favor of the referenced PR to improve zsh. It's a dup of our other zsh issues.
