### ISSUE TITLE
HTTP 401 while using 'create' action

### ISSUE THREAD

**Issue by berinle** [github/hub#83]
I am constantly hitting a HTTP 401 when trying to use 

hub create

on my newly created project. Isn't the create action meant to auto create the project on github?

Steps:
~: mkdir -p helloworld  
~: cd helloworld 
helloworld: echo 'trying out hub gem' > README
helloworld: hub init -g
Initialized empty Git repository in /Users/berinle/helloworld/.git/
helloworld(master) ✗: hub add .
helloworld(master) ✗: hub commit -m "first commit"
[master (root-commit) b770670] first commit
 1 files changed, 1 insertions(+), 0 deletions(-)
 create mode 100644 README
helloworld(master): hub create
error creating repository: Unauthorized (HTTP 401)
helloworld(master): 

Please advice

**Comment by matthewgoodwin** [comment]
So im getting this error as well.. I have had no problems with hub create until now. now I get:
```Error creating repository: Unauthorized (HTTP 401)
Bad credentials```
I have a very old version of hub, but I do have a `./config/hub` file. 
I do not have 2FA setup, I have one set of SSH keys and one Personal access token.. 
I have upgraded to OSSierra and everytime I upgrade my mac, something changes.. It does not even ask me for authentication or passwords anymore.. 
Im a noob and I dont have much experience troubleshooting git, so please help

**Comment by mislav** [comment]
@matthewgoodwin It might be that your token stored in `~/.config/hub` is outdated. Here's how to fix that:

1. First upgrade to at least hub 2.2.9 or one of the latest prereleases. You can either use `brew install hub` or download one of the precompiled binaries from the Releases section.
2. Unless you have some GitHub Enterprise configuration in your `~/.config/hub` file, delete that whole file. That will force re-authentication.
3. Run `hub create` again. This will ask you for your GitHub username and your real password. Then it will save a new token in `~/.config/hub` and hub should never ask you for the password again.

**Comment by matthewgoodwin** [comment]
@mislav Thanks for the timely response! I dont have a Github enterprise config to my knowledge. but I also cant seen whats inside this folder as my zsh is denying permission to access this files content..
`zsh: permission denied: .config/hub`

**Comment by mislav** [comment]
@matthewgoodwin I can't imagine why you don't have permissions to view files in `~/.config`, but it doesn't matter. If that file is the only one in that directory (you can check with `sudo ls ~/.config`), then simply delete it `sudo rm -rf ~/.config` and run `hub create` to reauthenticate.

**Comment by matthewgoodwin** [comment]
I dont want to delete all of the .config files.. 
my config directory contains my 
git heroku and hub
will this be an issue? should I only remove the hub directory?

**Comment by mislav** [comment]
If there are other files in there. you can remove just the `~/.config/hub` file, of course.

**Comment by matthewgoodwin** [comment]
after updating my hub, I actually noticed that I have another `heroku` dir installed in `usr/local` while `git` and `hub` were also installed in the same directory of my `usr/local/Cellar`, so I dont think I need anything in the `.config` dir. Im not certain why I have multiple directories in various places? thanks Ill do some investigating and clean up here!! thanks @mislav

**Comment by matthewgoodwin** [comment]
all good here, thanks again @mislav !

**Comment by tjddbs0401** [comment]
I have the same problem here.
I have
- git version 2.25.1
- hub version 2.14.2
But everytime I try to create one it shows
```
$ hub create
github.com username: tjddbs0401
github.com password for tjddbs0401 (never stored): 
Error creating repository: Unauthorized (HTTP 401)
Bad credentials
```
@mislav

**Comment by mislav** [comment]
@tjddbs0401 I'm sorry, I don't have an idea what could be going wrong there. It seems like you are not entering the right password for your GitHub account. You can try generating and pasting a Personal Access Token instead to see if that helps.

**Comment by raelgc** [comment]
For people coming from Google search: if you just updated your GitHub token, then you need to edit your `~./config/hub` file and update the `oauth_token` value.
