### ISSUE TITLE
Hub doesn't respect environment variables in configured editor

### ISSUE THREAD

**Issue by untitaker** [github/hub#835]
For reasons beyond me I had this line in my `gitconfig`:

    [core]
        editor = $EDITOR

With this value, I can edit commit messages just fine, but hub's `pull-request` command chokes on this:

    error using text editor for pull request message

If I remove that configuration value, everything works fine. The older versions written in Ruby didn't have this issue.

Kind-of related to https://github.com/github/hub/issues/721

**Comment by raphaelschaad** [comment]
+1, but in my case removing core.editor doesn't fix this (new) problem.

**Comment by untitaker** [comment]
Maybe GIT_EDITOR or EDITOR contain unresolved variable names?

**Comment by raphaelschaad** [comment]
Mine is set to: https://github.com/raphaelschaad/dotfiles/blob/master/.profile#L43

**Comment by untitaker** [comment]
Maybe hub can't deal with command args either.

**Comment by raphaelschaad** [comment]
@mblair any ideas?

**Comment by mislav** [comment]
@untitaker Thanks for reporting. It's likely that we don't support environment variables there. We'll try to match git, though.

**Comment by deuxshaish** [comment]
I've read elsewhere people got around this by quoting the string variables. See https://github.com/github/hub/issues/721

**Comment by svnpenn** [comment]
https://github.com/github/hub/issues/1354
