### ISSUE TITLE
Password entry only allows 11 characters

### ISSUE THREAD

**Issue by twsouthwick** [github/hub#836]
I had a password that was 13 characters and it would only take the first 11.  Once I changed my password to 11 characters long, it would take it and I could authenticate into GitHub.  Since GitHub allows more than 11 characters, it seems like this is a bug with Hub.

**Comment by mislav** [comment]
This should have been fixed with ed77befece7c9b55730023544ec81b0b88649a20. Rebuild from master to try it out. Will be included in the next bugfix release. Thanks!
