### ISSUE TITLE
Unable to fork

### ISSUE THREAD

**Issue by kaihendry** [github/hub#838]
hi, i'm trying to make a quick pull request on a repo, but I fail to fork it... http://ix.io/gPd what am I doing wrong ? hub version 2.2.0

**Comment by nathanhaigh** [comment]
`bug fork` doesn't work like that. I understand why you might think it should, but it doesn't.

```bash
# Firstly, you have to create a local clone of the repo you want to for:
$ cd /tmp
$ git clone git@github.com:hackerspacesg/hackerspace.sg.git
# Now ask for a fork to be made on GitHub, under your namespace, of this local repo
$ cd hackerspace.sg
$ hub fork
```
This repo should now be in your under your namespace at this URL https://github.com/kaihendry/hackerspace.sg

During the `hub fork` the repo under your namespace will have been added as a remote:

```bash
$ git remote -v
kaihendry     git@github.com:kaihendry/hackerspace.sg.git (fetch)
kaihendry     git@github.com:kaihendry/hackerspace.sg.git (push)
origin  git@github.com:hackerspacesg/hackerspace.sg.git (fetch)
origin  git@github.com:hackerspacesg/hackerspace.sg.git (push)
```

So to push changes to your repo, don't forget to specify your personal remote:
```bash
$ touch test
$ git add test
$ git commit -m "Added test file"
$ git push
ERROR: Permission to hackerspacesg/hackerspace.sg.git denied to kaihendry.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ git push kaihendry
Counting objects: 8, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 277 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To git@github.com:kaihendry/hackerspace.sg.git
   1c51d98..214c792  master -> master
```
Alternatively, to allow you to do a simple `git push`, you'll first have to push and set the upstream target:
```bash
git push --set-upstream kaihendry master

# Now you can do:
touch test2
git add test2
git commit -m ""Added test2 file
git push
```

**Comment by kaihendry** [comment]
Is there some canonical walkthrough of the exact steps from, clone to fork to pull request from the cli?

**Comment by mislav** [comment]
Thanks @nathanhaigh for jumping in.

@kaihendry: The [hub.github.com](https://hub.github.com/) site has some documentation about how to use hub for a workflow of contributing to a project (cloning, forking, sending a pull request). Other than that, there is no extensive usage documentation, sorry. There is only reference documentation for each command in the man page (also linked one the above site).

**Comment by mislav** [comment]
Closing because the above should have cleared it up. If something's still unclear, please ask!
