### ISSUE TITLE
Capturing output of `hub pull-request` using VIM

### ISSUE THREAD

**Issue by ianks** [github/hub#842]
I would like to be able to capture the output of `hub pull-request` so I can open the link it return in a browser. Something like:

`open $(hub pull-request)`

The problem is that in this case, the VIM output is directing to the pipe now, which it does not like:

`Vim: Warning: Output is not to a terminal`

Theoretically, hub's output location should be separate from VIM's, so VIM can still write to a file/buffer.

**Comment by dragon788** [comment]
Are you trying to use open as a parser to find a link in the pull request?

In order to output to vim for it to open you need to use something like this:

    my_command_with_output | vim -

The minus tells Vim to use stdin which will come from the pipe.

**Comment by ianks** [comment]
I realize this; I was referring to the case when I run `hub pull-request` and hub automatically opens a buffer in $EDITOR to write the message for the pull request.

**Comment by dragon788** [comment]
Ahhh, so instead of passing in a message or file or attaching an issue you want to know the URL before adding a message?

**Comment by ianks** [comment]
No. I want to create a pull-request, then immediately have it open in the browser after it is created.

**Comment by dragon788** [comment]
Partially able to replicate this, doing:
 ```git pull-request -m "" -b master```
*Should* simply return the URL, or allow you to redirect it to a file, or pipe it to a process etc. I was able to get it to > to a file, bit I did still get the VIM warning and had to C^c to get out of it, definitely a glitch.

But passing in non-whitespace to the -m command DOES work:
```links $(git pull-request -m "MergeMe" -b master)```
Works like a charm. Is this what you were looking for, since typically you can't or shouldn't have a null merge message anyways?

**Comment by ianks** [comment]
I like to edit my pull request messages in Vim. Does the passing in the
message allow me to do that or does it just post it?

**Comment by mislav** [comment]
Yes, `pull-request` outputting to stdout while at the same time using Vim wasn't a very good idea. Your options are described here: https://github.com/github/hub/issues/606#issuecomment-51403295

But if all you want to do is open the new pull request in the browser, you probably just want to use the `hub pull-request -o` option.
