### ISSUE TITLE
Using `git init -g` before commands that use the GitHub API result in broken remote URLs

### ISSUE THREAD

**Issue by alykhank** [github/hub#862]
Using `git init -g` before any command that needs to access the API will not prompt for GitHub credentials but will instead set up broken remotes like `git@github.com:/REPOSITORY.git` and `https://github.com//REPOSITORY.git`.

**Comment by mislav** [comment]
I see what you mean. `git init -g` should prompt for authentication info like other commands. Thanks for reporting!
