### ISSUE TITLE
zsh completion grouping + no command descriptions

### ISSUE THREAD

**Issue by OliverJAsh** [github/hub#863]
![image](https://cloud.githubusercontent.com/assets/921609/7050379/f25367b6-de18-11e4-8978-68ba73cfbe7c.png)

What determines whether a command is `common` or not? (I use `git pull-request` frequently but it is not classified as `common`.) Apparently this is not a zsh thing. zsh is not displaying command descriptions for commands not in `common`.

**Comment by mislav** [comment]
Not sure where the grouping to "common/all commands" happens, but I think that it's [not in our script](https://github.com/github/hub/blob/master/etc/hub.zsh_completion) since we don't have a mention of "common" there. Most likely this is a feature of whatever `_git` completion script you have installed.

**Comment by blueyed** [comment]
Yes, it's probably from Git's zsh completion.

For me it looks like this:

    % git pu<tab>
     -- alias --
    publish  -- alias for '!legit publish "$@"'
     -- main porcelain command --
    pull  -- fetch from and merge with another repository or local branch
    push  -- update remote refs along with associated objects
     -- hub command --
    pull-request  -- open a pull request on GitHub

I am using the Git completion from Zsh, and the simplified wrapper for `hub` from https://github.com/github/hub/pull/788.

I think this issue can be closed, because it's not about hub.

**Comment by OliverJAsh** [comment]
If I use git without hub, this is what my completion looks like:

```
$ /usr/local/bin/git pu<tab>
---- common commands
pull  -- fetch from and merge with another repository or a local branch
push  -- update remote refs along with associated objects
```

Am I using an old version of Zsh tab completion for Git? Not sure how to check.

**Comment by blueyed** [comment]
Not sure either.  `git/hub <C-x> h` might be handy, also `whence -f _hub` / `whence -f _git`.
Recently Zsh has gained `whence -v`, which should show you the path where a function is coming from.

#788 has also more information, which might help you to resolve this.
E.g. using homebrew can be problematic.

You could also grep for "common commands" in the right place(s) etc.

**Comment by OliverJAsh** [comment]
@blueyed What version of Git are you running? I don't see any mention of `main porcelain commands` in `/usr/local/share/zsh/site-functions/_git` (Git 2.4.1).

**Comment by blueyed** [comment]
@OliverJAsh 
It is coming from Zsh's git completion:

    Completion/Unix/Command/_git
    44:# Main Porcelain Commands
    5235:      _describe -t main-porcelain-commands 'main porcelain command' main_porcelain_commands && ret=0

I recommend using Zsh's completion for Git, and not the one shipped with Git.

**Comment by OliverJAsh** [comment]
Good advice, thanks.
