### ISSUE TITLE
[feature] Support installation of executable as "git"

### ISSUE THREAD

**Issue by frozencemetery** [github/hub#864]
Currently, if one installs hub in the path as git (e.g., install hub at **/usr/local/bin/git** while git itself is at **/usr/bin/git**), invocations of `git` will forkbomb, since hub tries to exec `git` based on path, which resolves hub first.

The cleanest solution from a user perspective would I think be to detect this type of case and work around it.  However, looking at the `Cmd` API, it's not clear how this would work.  An easier solution I think would be to hardcode the path to `git` at compile-time and do the detection there (`which -a git` will give *all* possible `git` executables, and that could be queried for e.g., version; then take the first one that's not hub).

Thanks!

**Comment by mislav** [comment]
This was brought up before. I guess you want to avoid setting an `alias` in your shell, right? I've proposed a workaround here: https://github.com/github/hub/issues/559#issuecomment-41793847

I'm not interested in officially supporting this use-case within hub, though.
