### ISSUE TITLE
`git clone resque` fails

### ISSUE THREAD

**Issue by Coaxial** [github/hub#868]
```
$ git clone resque
Cloning into 'resque'...
fatal: remote error:
  Repository not found.
```

However,
```
$ git clone resque/resque
Cloning into 'resque'...
remote: Counting objects: 10977, done.
remote: Total 10977 (delta 0), reused 0 (delta 0), pack-reused 10977
Receiving objects: 100% (10977/10977), 3.21 MiB | 2.17 MiB/s, done.
Resolving deltas: 100% (4726/4726), done.
Checking connectivity... done.
```

I have installed `hub` via homebrew and aliased with `eval "$(hub alias -s)"` in my `.bash_profile`

```
$ hub version
git version 2.3.5
hub version 2.2.1
```

**Comment by mislav** [comment]
`git clone resque` is not designed to work. A `owner/repo` pair must have `owner/` component. Otherwise it doesn't know what to clone.

**Comment by Coaxial** [comment]
I guess I got confused because of that part of the doc: https://github.com/github/hub/blob/master/README.md#git-clone

```
$ git clone resque
> git clone git@github.com/YOUR_USER/resque.git
```

**Comment by waterlink** [comment]
And actually example in the doc looks weird, it should be:

```
$ git clone resque
> git clone git@github.com:YOUR_USER/resque.git
```

Notice `:` (semicolon) before `YOUR_USER`

**Comment by mislav** [comment]
> I see it, this syntax only works for your own repos

@Coaxial Yeah. I guess the error message could be better in this case.

@waterlink Seems like the docs might have a typo?

**Comment by waterlink** [comment]
@mislav that is exactly what I'm trying to point out :-)
