### ISSUE TITLE
Don't abort due to empty pull request title if a commit has a message

### ISSUE THREAD

**Issue by smockle** [github/hub#869]
If a pull request is created without a message (`hub pull-request`), my editor opens. If I close the editor without typing a PR title, I get "Aborting due to empty pull request title".

If the PR has just one commit, and that commit has a commit message, could hub use that commit message as the PR title, rather than aborting? I think this is what the GitHub web interface does.

**Comment by mislav** [comment]
If the PR has just one commit, then that commit subject + commit message will be pre-filled in the text editor. So even if you don't type anything, there should be a default title.

And if you don't fill in a title in other cases, the pull request won't be submitted because PRs can't have empty titles.

**Comment by smockle** [comment]
I just tested with a new repo, and you're exactly right. The commit message is pre-filled in my editor. Not sure how I missed this before, but I'm closing the issue because all appear to be working as designed. Sorry about that! Thank you for the quick follow-up!

**Comment by hkdobrev** [comment]
@smockle If you've tried to create a previous pull request with more than commit and then aborted it, the pull request message is kept in `.git/PULLREQ_EDITMSG`. This file is then re-used for subsequent pull requests if present. This might have fooled you into thinking the single commit message is not being used. It's similar to how Git keeps commit messages in `.git/COMMIT_EDITMSG`.

**Comment by timfong888** [comment]
When I open the editor with `hub pull-request` and then `:w` and `:q` I get an error: `Aborting due to empty pull request title` even though there is a block of text....
