### ISSUE TITLE
Readme suggestion - Linux install

### ISSUE THREAD

**Issue by cbeland** [github/hub#873]
I know "yum install hub" works on Fedora; I hope "apt-get install hub" works on Ubuntu. We have users at our company on Linux, and it would be nice to point them at the same setup instructions (the readme for this repo) as everyone else.

**Comment by jingweno** [comment]
We don't provide official recipes for yum or apt-get yet - we only have pre-built binaries for Linux for now. But I would like to see this going.

**Comment by cbeland** [comment]
You don't want to document how to install the distribution-provided binaries?

**Comment by mislav** [comment]
We're not aware that hub is listed in any official distros yet, and we won't provide instructions that use 3rd-party sources or require that users maintain their own package recipes.

**Comment by cbeland** [comment]
I'm not sure what you mean by third-party and official distro...hub is packaged by the Fedora Project themselves in Fedora 21.

**Comment by mislav** [comment]
Ah, we didn't know that. Which version do they package?

**Comment by jrobeson** [comment]
the hub package for Fedora 21 is still only at 1.12.1

**Comment by mislav** [comment]
This will be solved with the download script suggested in #987.

In the meantime, users should download pre-build binaries from https://github.com/github/hub/releases/tag/v2.2.1
