### ISSUE TITLE
Hub remote parsing is incomplete

### ISSUE THREAD

**Issue by frozencemetery** [github/hub#876]
For instance:

```
rharwood@thriss:~/python-gssapi$ git remote -v
frozencemetery	git+ssh://git@github.com/frozencemetery/python-gssapi (fetch)
frozencemetery	git+ssh://git@github.com/frozencemetery/python-gssapi (push)
origin	git+ssh://git@github.com/pythongssapi/python-gssapi (fetch)
origin	git+ssh://git@github.com/pythongssapi/python-gssapi (push)
sross	git+ssh://git@github.com/DirectXMan12/python-gssapi (fetch)
sross	git+ssh://git@github.com/DirectXMan12/python-gssapi (push)
rharwood@thriss:~/python-gssapi$ git pull-request
Aborted: the origin remote doesn't point to a GitHub repository.
rharwood@thriss:~/python-gssapi$ git fetch origin
rharwood@thriss:~/python-gssapi$ echo $?
0
rharwood@thriss:~/python-gssapi$ 
```

Clearly origin does point to a Github repo, so something has gone wrong here.

**Comment by mislav** [comment]
I don't think we recognize the `git+ssh` scheme. How did you end up with it, as opposed to `git@github.com:frozencemetery/python-gssapi` syntax? If it's a valid scheme, we should definitely support it. In the meantime, it will help to change the URL syntax.

**Comment by frozencemetery** [comment]
It's a valid scheme as per [git source](https://github.com/git/git/blob/master/transport.c#L963).  I tend to use it because I don't want to keep track of the implicit part of, e.g., `git@github.com:frozencemetery/python-gssapi`, which is admittedly not the best reason, but it is accepted by get.

**Comment by retronym** [comment]
Perhaps relatedly, I recently upgraded to `hub` 2.2.1 and found that it no longer seems to handle my remote configuration:

```
% git remote -v | grep origin
origin	git://github.com/scala/scala.git (fetch)
origin	no_push_for_you (push)
ticket/9285 ~/code/scala3 git pull-request -b 2.11.x
Aborted: the origin remote doesn't point to a GitHub repository.
```

I use separate pull/push URLs in this way to ensure that changes are only made through pull requests.

**Comment by hakatashi** [comment]
I'm also experiencing the issue when I'm explicitly pointing port number for ssh

```
[~/dotfiles (master)]$ git remote -v
origin  ssh://git@github.com:22/hakatashi/dotfiles.git (fetch)
origin  ssh://git@github.com:22/hakatashi/dotfiles.git (push)
[~/dotfiles (master)]$ git fork
Error: repository under 'origin' remote is not a GitHub project
```

**Comment by erikwebb** [comment]
I also run into the problem that @retronym describes where the push remote is empty to avoid accidental pushes.

**Comment by roberthbailey** [comment]
A number of folks working on [kubernetes](https://github.com/kubernetes/kubernetes/) have run into this recently as well, since many of us set our remote push to a safety value to prevent accidentally clobbering upstream (which has happened before).

**Comment by mislav** [comment]
Thanks everyone for reporting! It seems that there are a number of remote parsing bugs in hub right now. I'll see what we can do about these. In the meantime, PRs welcome :)
