### ISSUE TITLE
hub pull-request after 404 uses old name of repository

### ISSUE THREAD

**Issue by betelgeuse** [github/hub#878]
```
$ hub pull-request -b org:master
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/org/old_name exists?
```

Here old_name repository has been renamed in github. Hub should rather have the new name in the error message.

**Comment by mislav** [comment]
Thanks for reporting! We'll look into it. In the meantime, is it an option that you edit `.git/config` for this repo and correct the URL for the remote to contain the new name?

Similar issue about renamed repos, although it might not be the same bug: #768

**Comment by betelgeuse** [comment]
@mislav the URL is correct in ```.git/config``` so that is not the cause

**Comment by betelgeuse** [comment]
```
$ git config remote.org.url
git@github.com:org/new_name.git
```

**Comment by mislav** [comment]
It's pretty bizarre then that the error message contains old_name. Is the same error every time?

**Comment by betelgeuse** [comment]
It might be related to github server issues in some way:

```
$ ./script/pull_request_current 
Counting objects: 167, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (132/132), done.
Writing objects: 100% (167/167), 21.04 KiB | 0 bytes/s, done.
Total 167 (delta 136), reused 54 (delta 34)
To git@github.com:betelgeuse/app.git
 * [new branch]      missing_coverage -> missing_coverage
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/org/new_name exists?
 $ ./script/pull_request_current 
Everything up-to-date
https://github.com/org/app/pull/xxx
```

**Comment by mislav** [comment]
Sorry, what does `script/pull_request_current` do? Did you have different outcomes when you ran it the 2nd time?

**Comment by betelgeuse** [comment]
```bash
branch=$(git rev-parse --abbrev-ref HEAD)
git push myfork ${branch}
hub pull-request -b org:master -h $(id -un):${branch}
```

I did have two different outcomes (both are recorded in my previous comments).

**Comment by mislav** [comment]
Do you still have this problem, @betelgeuse? It might have been a GitHub API issue back then.

**Comment by mislav** [comment]
@betelgeuse The [2.2.4 release significantly improves](https://github.com/github/hub/releases/tag/v2.2.4) support for renamed repositories and HTTP redirects from API. This shouldn't be an issue for you anymore. Please report back if you upgraded but you still have problems. Thanks!
