### ISSUE TITLE
Clear instructions for `hub pull-request`

### ISSUE THREAD

**Issue by danmbox** [github/hub#880]
Please provide complete instructions for creating a pull request, including all steps that make a difference, with sample arguments: `hub clone`, `hub fork`, creating the feature branch with `git checkout -b` and pushing it correctly (I see there's https://github.com/github/hub/issues/877). I've had trouble creating pull requests from the command line so I'm not sure what combination of commands actually works.

**Comment by mislav** [comment]
Good idea. Ideally this information should be in help text presented by `hub help pull-request`.

**Comment by Haroenv** [comment]
or `hub pull-request -h`

**Comment by sinisterstuf** [comment]
This issue seems related to #2281 and unless we want to keep this as an ideation thread, it can probably be considered closed by 4813e85.

**Comment by mislav** [comment]
Thanks @sinisterstuf. Also the steps are covered in https://hub.github.com/#contributor
