### ISSUE TITLE
hub pull-request has trouble understanding editor variable

### ISSUE THREAD

**Issue by ElDeveloper** [github/hub#881]
My `~/.gitconfig` has the following in it (among many other things):

```gitconfig
[core]
    editor = vim -u ~/.vimrc-mutt +startinsert
```

However, this makes `hub pull-request` fail with the following message:

```
error using text editor for pull request message
```

It works just fine when I change it to:

```gitconfig
[core]
    editor = vim
```

**Comment by mislav** [comment]
Thanks for letting us know! We'll look into it. In the meantime you could try setting `GIT_EDITOR=vim hub pull-request` whenever you're making a PR, so you don't have to constantly change your original `~/.gitconfig`.

**Comment by mislav** [comment]
Hi, I can't reproduce this. Can you confirm that you're using latest release hub 2.2.1? If not, please update.

Also, which platform are you on?

**Comment by ElDeveloper** [comment]
I was able to confirm this is no longer a problem with 2.2.1, must have been a problem with `1.12.4`.

**Comment by mislav** [comment]
Thank you!

**Comment by Coaxial** [comment]
I just ran into this issue, this is my .gitconfig:

```
[core]
  editor = $(which vim)
```

And I'm getting the same error message when running `git pull-request`: `error using text editor for pull request message`

`git commit` opens vim just fine.

```
$ hub version
git version 2.6.4
hub version 2.2.2
```

**Comment by dougludlow** [comment]
I got this error on Windows 10.

```bash
> hub version
git version 1.9.5.msysgit.0
hub version 2.2.3
```

But I found I was missing the `core.editor` setting. So I ran `git config --global core.editor vim` and was good to go.

**Comment by scottbasgaard** [comment]
Thanks @dougludlow

**Comment by dougludlow** [comment]
@scottbasgaard :thumbsup:

**Comment by shawwn** [comment]
I'm getting problems with ```hub.protocol=https
core.editor=gvim --remote-wait```

`hub pull-request` doesn't seem happy about that `core.editor` setting.
