### ISSUE TITLE
hub issue only shows the first 30 open issues

### ISSUE THREAD

**Issue by samdeane** [github/hub#883]
I know that it's listed as "beta", and I'm guessing that it's doing some sort of paging and only showing the first page, but it's a bit of a pain that the `hub issue` command only seems to display the first 30 newest open issues.

**Comment by mislav** [comment]
Yes, the command is still in heavy beta and isn't ready for consumption. Adding proper pagination is definitely on our roadmap, though.

Closing in the meantime to help clear out our issue backlog.
