### ISSUE TITLE
go 1.4 or 1.2 required?

### ISSUE THREAD

**Issue by tfarina** [github/hub#885]
https://github.com/github/hub/blob/master/script/bootstrap#L12 indicates you need 1.2 while https://github.com/github/hub/blob/master/README.md#source indicates 1.4.

**Comment by jingweno** [comment]
There's a PR for this: https://github.com/github/hub/pull/799

**Comment by mislav** [comment]
Fixed in 12c13bb9a4d6cecc436dd3fbbb5835366ab0befa

**Comment by tfarina** [comment]
Thank you.
