### ISSUE TITLE
Add ability to move issues from one repository to another

### ISSUE THREAD

**Issue by mnquintana** [github/hub#886]
It would be awesome if hub added the ability to move issues from one repo to another, adding references to the original issue, preserving comments, and closing the original issue (basically https://github.com/google/github-issue-mover baked into hub).

**Comment by mislav** [comment]
Hi, that wouldn't be a bad feature! However we don't offer any issue management right now, and when we do in the future, we probably won't support this feature because it would be so complex to create and maintain. I would stick to using the above referenced tool instead.

**Comment by linas** [comment]
Seems to be a duplicate of https://github.com/holman/ama/issues/413 -- it really really would be nice to have this. The github-issue-mover is inadequate, it fails to preserve metadata.

**Comment by linas** [comment]
See also that fount of knowledge: http://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo -- its a rather common request, it seems.

**Comment by danielgary** [comment]
Just FYI, we developed a Chrome Extension for this.
Extension link: https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf
Source code available: https://github.com/gatewayapps/kamino

**Comment by janicecmt** [comment]
It's grayed out when I try to use it. Do you need to be a repo admin?

**Comment by rahuldeo2047** [comment]
@janicecmt : Yes it grays even if you created a repo.

**Comment by Matt-Hill-Harness** [comment]
The 2 tools listed above seem like they may represent a security risk.
Can someone comment on how secure each of the options are, if your code is private?

**Comment by l00mi** [comment]
This is coming up for us as an important missing feature over and over all this years, especially as now with _projects_ you clearly started doing _issue management_. It is now end of 2017, could you consider reevaluating this Issue @mislav ?

**Comment by cmawhorter** [comment]
It should also be noted that issue mover can only move issues one at a time.  ...which is sad for me when I created 15 issues on the wrong repo in my late night bug testing.

**Comment by bitcrazed** [comment]
I sincerely hope @Mislav @Haacked and other GitHubbers take pity on us mere mortals and reconsider their position on this increasingly vital ask. 

GH Issues are the lifeblood of many of our projects and it's increasingly essential that we be able to move issues from one repo to another, preserving as much info/data as possible, esp. the OP and tags.

Please, PLEASE, PRETTY PLEASE???
![PRETTY PLEASE](http://78.media.tumblr.com/7108d89a2c47a989b3f3c1d337888f69/tumblr_mys49gm9Gj1t3drueo1_400.gif)

**Comment by demisjohn** [comment]
Every couple of years I run into the problem where I need to migrate one or all issues between repos, and since 2013 when I first tried, there still is no proper built-in solution for this!  I can't be the only person that finds this to be a nearly crippling omission.
`Issues` are such a vital feature when in comes to tracking problems, solutions and research into solutions.  In addition, the GitHub implementation of Issues is rather nicely done, with much attention to labels, colors, aesthetic - Losing/risking any of that data is a massive loss.

I think this topic should be reevaluated.

**Comment by deltacat** [comment]
Yes, please, this is a very useful feature.

**Comment by matthewc02** [comment]
yes please

**Comment by matthewmccullough** [comment]
Today, [GitHub shipped issue transfers as a public beta on GitHub.com](https://blog.github.com/changelog/2018-10-30-issue-transfer/). This allows a repository administrator to transfer an issue to another repository where the user also has repository administration privileges. [Help Docs have the details](https://help.github.com/articles/transferring-an-issue-to-another-repository/).
