### ISSUE TITLE
Custom command to manage collaborators

### ISSUE THREAD

**Issue by pravj** [github/hub#887]
Hi @mislav,

May I know, is this a right thing for hub to support an addition custom command to manage collaborators to a repository?

As I can see, in the custom commands section, hub tries to minimize the use of web interface. So, collaborator management would be a better thing to add there, as I keep using that(web interface) often and doesn't like it.

We can have such a working for it:
```ruby
hub collaborators [-l] [-a USER] [-r USER] [-c USER]

-l          list collaborators
-a USER     add a collaborator
-r USER     remove a collaborator
-c USER     check if a USER is collaborator
```

Can I hear something back from you?

**Comment by sindresorhus** [comment]
:+1: In the meantime I'm using [`github-add-collab`](https://github.com/kevva/github-add-collab) to quickly add collaborators.

**Comment by mislav** [comment]
No, right now we're not interested in supporting this feature mostly because it would add to the things we need to maintain. We want to instead support more actions related to the git and issues/PRs workflows.

**Comment by srafi1** [comment]
@mislav Are there any plans to add this kind of functionality now or is this project still focused on issue/PR workflows?

**Comment by mislav** [comment]
@srafi1 I still don't think this is a good fit for hub, but you may be able to script adding collabs to a repo [using `hub api`](https://hub.github.com/hub-api.1.html) 

You're welcome to share some code in a gist if you ever come up with a working script! 👍

**Comment by srafi1** [comment]
Looks like this isn't too difficult using `hub api` with some json parsing using `jq`:

List collaborators: `hub api repos/:user/:repo/collaborators | jq ".[].login"`
Add collaborator: `hub api -X PUT repos/:user/:repo/collaborators/:new_collaborator`
Remove collaborator: `hub api -X DELETE repos/:user/:repo/collaborators/:collaborator`
Verify collaborator: `hub api repos/:user/:repo/collaborators/:collaborator -i  | grep "Status: 204"  && echo yes || echo no`

I can put this in a script in a bit.

**Comment by srafi1** [comment]
Here's the completed script: https://github.com/srafi1/dotfiles/blob/master/scripts/hub-collab
(refrains from using `jq` because it's not a builtin command)

**Comment by mislav** [comment]
@srafi1 This is great! Thank you for sharing

You are welcome to contribute such scripts to [hub-api-utils](https://github.com/mislav/hub-api-utils)
