### ISSUE TITLE
hub am is stripping square brackets 

### ISSUE THREAD

**Issue by amuraru** [github/hub#888]
when the commit title for a PR is containing square brackets, e.g `[JIRA-NNNN] - My patch for this jira`, `hub am` will strip `[JIRA-NNNN]`.
Is this intended?

**Comment by jingweno** [comment]
I'm not aware of any code to trim out commit title. All `hub` does is to [download the patch to a temporary file](https://github.com/github/hub/blob/master/commands/apply.go#L62-L106) and let `git-apply` deal with the rest.

Also I think there might be some misunderstanding of how `git-apply` works. `git-apply` is from git and it shouldn't have anything to deal with the title for a PR which is a GitHub feature.

**Comment by mislav** [comment]
Yes, hub only downloads the patch and applies it. It doesn't change the patch in any way. The problem must lie elsewhere.

I'll close this report for now, but if you have further info or maybe steps to reproduce, please reopen this. Thanks!
