### ISSUE TITLE
hub create unexpected behaviour existing repository

### ISSUE THREAD

**Issue by soniah** [github/hub#891]
If I have an existing repository with existing remotes, **hub create** has unexpected behaviour -- if my existing remotes are called *foo* and I'm in the directory *bar* when I run ```hub create```, a repository called *bar* is created, not the expected *foo*. For example

```
% git remote -v
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (fetch)
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (push)
origin

% pwd
/Users/sonia/git/haskell-prj-apr/chap02

% hub create
fatal: remote origin already exists. # a separate issue has been logged for this
```
In this example a repository called **chap02** is created, rather than the expected **haskell-prj-apr** given by the existing remote.

**Comment by jingweno** [comment]
> if my existing remotes are called foo and I'm in the directory bar when I run hub create, a repository called bar is created, not the expected foo

That's expected behavior. If you don't specify a repo to create, `hub` will use your current folder name. Details usage: https://github.com/github/hub#git-create. I agree though the doc could be improved since it says:

```
$ git create
[ repo created on GitHub ]
> git remote add origin git@github.com:YOUR_USER/CURRENT_REPO.git
```

It will prob. make it more obvious if we change `CURRENT_REPO` to `CURRENT_DIR`.

**Comment by mislav** [comment]
Thanks for explaining this @jingweno. Agreed that this is expected behavior.
