### ISSUE TITLE
hub browse: opens origin, not YOUR_USER

### ISSUE THREAD

**Issue by blueyed** [github/hub#896]
From the man page:

    git browse
       $ git browse
       > open https://github.com/YOUR_USER/CURRENT_REPO

However, when I'm on a `feature@my-user-name`, `hub browse` will open `https://github.com/origin-of-fork/reponame`.

I would have expected it to open the branch `feature` on my fork instead.

The remotes for this case:

    blueyed	git@github.com:blueyed/jedi-vim.git (fetch)
    blueyed	git@github.com:blueyed/jedi-vim.git (push)
    origin	https://github.com/davidhalter/jedi-vim.git (fetch)
    origin	ssh://git@github.com/davidhalter/jedi-vim.git (push)

The current branch: 'improve-buffer-switching', which tracks 'blueyed/improve-buffer-switching'.

**Comment by mislav** [comment]
Hi, thanks for reporting and sorry for the late reply. What is your `git config push.default`? Thanks

**Comment by blueyed** [comment]
`simple`

    git version 2.5.3.dirty
    hub version 1.12.2

**Comment by mislav** [comment]
Thanks for the info! I think I may have experienced something like this myself but wasn't able to reproduce. I'll try to track this down.

**Comment by mislav** [comment]
I've been able to confirm this and working on a fix.

**Comment by DieterReuter** [comment]
@mislav any progress on this issues?

**Comment by jasonkarns** [comment]
same issue for me

```
$ git config push.default
upstream
$ hub --version
git version 2.7.0
hub version 2.2.0-rc1-g4b725ef
```

I have the 'main' remote configured named `upstream` and my fork named as `origin` if that matters.

**Comment by mislav** [comment]
Sorry about the wait. I had a fix locally, but since then switched computers and lost the code due to never pushing the WIP branch.

I'll try to reproduce my fix. This is bugging me as well.
