### ISSUE TITLE
New command/option to open an existing pull request

### ISSUE THREAD

**Issue by blueyed** [github/hub#897]
I would like to have a command to open/browse an existing pull request.

Since `pull-request` is able to see if there's a pull-request already (at least when it tries to create one), this should be possible.

It should default to the current branch with its tracking remote/repo.

Related issue: https://github.com/github/hub/issues/880 - which is about displaying the URL to a pull request.

**Comment by parkr** [comment]
`hub browse` gets you most of the way there.

**Comment by blueyed** [comment]
Yes, it helps in general.

But given https://github.com/github/hub/issues/896 you won't be on your fork / the branch necessarily.

(I assume that you mean that the branch is opened and you can click the link to the PR?!)

**Comment by dwijnand** [comment]
```bash
git config --global alias.pr-open \
  '!open $(hub pr list -f %U -h dwijnand:$(git rev-parse --abbrev-ref HEAD))'
```

to add a `pr-open` alias to your `~/.gitconfig`

Replace **dwijnand** with your username, and `open` if not on macOS.

**Comment by jasonkuhrt** [comment]
Suggest command name/structure:

```
$ git pr browse <#>
```

**Comment by mislav** [comment]
`hub pr show` has now landed in master https://github.com/github/hub/pull/2141

**Comment by dentuzhik** [comment]
This is amazing, thank you 🥇 
That time when issue hangs in your subscription for more than two years and then it finally pays off 💃

**Comment by mislav** [comment]
@dentuzhik You're welcome! Credit goes to @ashemesh @hmemcpy who eventually made contributions towards the feature ❤️

**Comment by hmemcpy** [comment]
Thanks very much for pushing it through! 🎉
