### ISSUE TITLE
git clone foo.bundle foo erroneously tries to clone from GitHub

### ISSUE THREAD

**Issue by exalted** [github/hub#898]
Hi,

with `hub` is aliased to `git` using `eval "$(hub alias -s)”`, when I try to `git clone foo.bundle foo` (where `foo.bundle` is a git bundle created via `git bundle create`), `hub` erroneously tries to clone a repository  from GitHub (i.e., `https://github.com/<username>/foo`).

An example output of the error would be:

```
Cloning into ‘foo'...
remote: Repository not found.
fatal: repository 'https://github.com/<username>/foo.bundle.git/' not found
```

As a workaround I used `command git clone foo.bundle foo` instead.

**Comment by mislav** [comment]
Thanks for the report! It seems that we're not detecting bundle files on disk properly. We're probably only detecting local git directories instead. I'll see what we can do about this.

**Comment by exalted** [comment]
:bow:

**Comment by exalted** [comment]
@mislav truth to be told, it’s not a huge deal for me either. I noticed and quickly reported back then. In case it doesn’t sense much to fix, maybe a reminder to user could be enough. I don’t know.

**Comment by mislav** [comment]
It shouldn't be too hard for us to fix.

**Comment by exalted** [comment]
:+1:


--
Ali

**Comment by aschrab** [comment]
I just experienced a similar issue trying to fetch from a bundle file, using a full path to the bundle.

```
$ g fetch /Volumes/aschrab/ui.bundle
github.com username: ^Czsh: exit 2     hub fetch /Volumes/aschrab/ui.bundle

$ file /Volumes/aschrab/ui.bundle
/Volumes/aschrab/ui.bundle: Git bundle

$ /usr/local/bin/git fetch /Volumes/aschrab/ui.bundle
Receiving objects: 100% (101/101), 789.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), completed with 28 local objects.
From /Volumes/aschrab/ui.bundle
 * branch            HEAD       -> FETCH_HEAD

$ hub --version
git version 2.6.2
hub version 2.2.2
```

Now that I've figured out what's going on it shouldn't be a huge deal to work around the problem. But it was certainly annoying while initially determining where that prompt was coming from.

**Comment by exalted** [comment]
:clap:
