### ISSUE TITLE
hub clone pull request: Bad credentials

### ISSUE THREAD

**Issue by sjackman** [github/hub#899]
This repository is public. Why do I get an error of `Bad credentials`?

```
❯❯❯ hub checkout https://github.com/Homebrew/homebrew-science/pull/2248
Error getting pull request: Unauthorized (HTTP 401)
Bad credentials
```

**Comment by mislav** [comment]
Perhaps you changed your GitHub password so now the cached OAuth token is expired? Or you might have revoked hub's token from the web site?

If `~/.config/hub` doesn't contain any extra configuration you want to keep, you might just delete the whole file and let hub re-authenticate with GitHub.

**Comment by sjackman** [comment]
That worked! Thanks. Perhaps `hub` could give that recommendation to the user when it gets a `HTTP 401` error.

**Comment by mislav** [comment]
Good idea: #609
