### ISSUE TITLE
PR base fork does not find all forked repos

### ISSUE THREAD

**Issue by arve0** [github/hub#900]
When creating a new PR, I'm unable to find one of the forked repos: https://github.com/cowlicks/scikit-image/

Steps to reproduce:
![skjermbilde 2015-05-16 kl 12 18 34](https://cloud.githubusercontent.com/assets/4810521/7665737/d5973506-fbc5-11e4-9844-6175e1636fde.png)

![skjermbilde 2015-05-16 kl 12 19 23](https://cloud.githubusercontent.com/assets/4810521/7665739/d7b7c6e8-fbc5-11e4-931e-ba778c9ec98a.png)

Expected:
cowlicks/scikit-image should appear in base-fork.

**Comment by mislav** [comment]
It seems that you're reporting an issue on GitHub.com site, not with the "hub" command-line tool for git. Instead, you should be reporting site issues to support@github.com. However, we know about the site issue, so you don't need to report it again. I can't promise you when it will be fixed, though.

Thanks for reporting!
