### ISSUE TITLE
Using HTTP in github enterprise

### ISSUE THREAD

**Issue by shacka** [github/hub#902]
I'm trying to use hub with our instance of github enterprise, but we don't use HTTPS (I know it's a bad idea) and I can't tell hub to use HTTP instead. So far I wasn't able to find any evidence that this is configurable. Is there a plan to support this?

**Comment by mislav** [comment]
This was made possible in 7944d63edb1373fbbfa806bc108508b7906c8210

You will need to edit your `~/.config/hub` to add the "protocol: http" option.

**Comment by Xobb** [comment]
Well, this is not working. 

    cat ~/.config/hub
    protocol: http

doesn't d the job

**Comment by mislav** [comment]
@Xobb Please read the full commit message that I've linked above.
