### ISSUE TITLE
Is there a whoami or comparable command?

### ISSUE THREAD

**Issue by ehd** [github/hub#903]
Hey,

I'm building a cli tool for automating the setup of new projects. Before calling `hub create $name` to create a github repostiory, the tool should check whether the person using the tool has already authenticated themselves on github. I'm doing the same for travis and heroku using their cli tools:

```
$ travis whoami
You are ehd (Stephan Seidt)

$ echo $?
0

$ heroku auth:whoami
user@example.com

$ echo $?
0
```

They both have a `whoami` command that also returns the proper exit code depending on the auth status: 0 if you're authenticated, 1 if you're not.

Is there such a command in `hub`, and if not, would it be useful to have it? Is there maybe a workaround to achieve a similar result?

**Comment by mislav** [comment]
Yes this is planned: #225

Sadly, right now there are no workarounds. You can try to parse the YAML from `~/.config/hub` and check the username for "github.com". If the file exists and has that configuration, that means this GitHub user has authenticated.

**Comment by ehd** [comment]
@mislav Thanks for pointing me to the other issue & recommending a solution!
