### ISSUE TITLE
Getting zsh completions to work when hub is installed with brew

### ISSUE THREAD

**Issue by le0nik** [github/hub#904]
It's not a question. I figured it out myself and would like to provide a pointer for those, who might encounter the same problem.

If you install hub with homebrew, it adds completions to '/usr/local/share/zsh/site-functions'. But fpath doesn't have this directory by default! It has 'usr/share/zsh/site-functions'.

So all you have to do is add `fpath=(/usr/local/share/zsh/site-functions $fpath)` at the top of your `.zshrc` file. Then completions are going to work.

**Comment by mislav** [comment]
Thanks for sharing!

**Comment by jvanbaarsen** [comment]
@le0nik Somehow when I try this I get the following error when opening a new zsh session:

```
zsh:12: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
```

Is something outdated on my system?

**Comment by nicolasbrugneaux** [comment]
Thanks @le0nik!!!!

**Comment by bravely** [comment]
@jvanbaarsen Got the same thing. Find any solution?
