### ISSUE TITLE
Unable to inspect in appium inspector and the appium get crashing , while launching the appium inspector

### ISSUE THREAD

**Issue by valarmathivrv** [github/hub#907]
1.I have installed appium 1.3.7 version in mac machine.
2. I have started appium server for android app in android device.  In android device, the app get installed and opened successfully.
3.I have clicked the show inspector button and then I can able to see the inspector screen and then my appium inspector get crashed. 
4. I have attached the screen shot below for reference.

![063933c4-ef1b-11e4-9bb8-488bdae8d661](https://cloud.githubusercontent.com/assets/9842215/7763747/5ab1e302-0063-11e5-9a71-f7b46f29241c.png)

**Comment by mislav** [comment]
Hi, it seems like you have a problem with something called "appium". This is an issue tracker for a project called "hub", which is a command-line tool for git version control.

Maybe you want to [open an issue in the appium](https://github.com/appium/appium/issues) project instead? You might also want to search their existing issues for similar reports. Thanks
