### ISSUE TITLE
vagrant ssh-config doesn't work when the VM is halted

### ISSUE THREAD

**Issue by peckpeck** [github/hub#910]
It annoys me since I'd like to prepare my ssh configuration for another usage.

**Comment by peckpeck** [comment]
PR https://github.com/mitchellh/vagrant/pull/5759

**Comment by mislav** [comment]
How is this a problem with "hub" project?

**Comment by peckpeck** [comment]
Oops, very sorry, EWRONGPROJECT
I made a mistake when opening the issue
