### ISSUE TITLE
pull-request should support -e (--edit) when using -F

### ISSUE THREAD

**Issue by rjmunro** [github/hub#914]
So that you can supply a file to base the PR on, but still allow the user to edit it before submitting the PR.

It should work the same as the `--edit` option in `git commit`.

We have a file in our repository called `PR-TEMPLATE.md` that has a checklikst of things that all pull request comments should have before they are merged. It would be nice to do `hub pull-request -eF PR-TEMPLATE.md` then get an editor to write my PR with the template in place.

**Comment by mislav** [comment]
Good idea! Already on our roadmap: #446
