### ISSUE TITLE
hub fork does not take the correct base url 

### ISSUE THREAD

**Issue by nbessi** [github/hub#915]
Hello, 

With a clone of the project https://github.com/OCA/OCB when you do a hub fork it does not set you the correct remote it puts the original repo url and not my fork. It is maybe du to the fact that the repo is allready a fork of https://github.com/odoo/odoo

It is quite a dangerous situation we have here.

Regards 

Nicolas

**Comment by mislav** [comment]
Hi @nbessi, sorry you had trouble and sorry for the late reply.

I'm trying to understand what happened here. You cloned `OCA/OCB`, then did `hub fork`, and then the git remote wasn't set properly? Which remote wasn't correct, "origin" or "nbessi"? What did you expect would happen instead?

**Comment by mislav** [comment]
Closing this due to being stale.
