### ISSUE TITLE
hub compare should have API similar to pull-request

### ISSUE THREAD

**Issue by cabello** [github/hub#917]
This is a feature request and not a bug.

This is my current workflow given I start on master branch:
```bash
git co -b new_feature
# commit
# commit
# commit
git push -u origin new_feature
hub pull-request
```

---

But sometimes I am working on sub-branches so I do:
```
hub pull-request -b bigger_release
```
In order to create a pull request that the base is not the master branch.

---

And also sometimes I am not ready to create a pull request but either compare, with the current API I do:
```
hub compare bigger_release..smaller_improvement
```

It would be amazing to have an API similar to `pull-request`:
```
hub compare -b bigger_release
```

**Comment by mislav** [comment]
That's… actually not a bad idea. We'll think about it.

**Comment by mislav** [comment]
Added in #936

**Comment by cabello** [comment]
Thanks! :heart:
