### ISSUE TITLE
`hub help browse` doesn't show any help text

### ISSUE THREAD

**Issue by hasit** [github/hub#918]
Hello.

My output for `hub help browse` is as follows:

```
$ hub help browse
No manual entry for gitbrowse
```

I started looking commands/browse.go and what I found different in commands/browse.go from any other command, say commands/compare.go, is that it has GitExtension set to true. Is that what is creating the problem here? How can I help solve it?

Thank you.

**Comment by hkdobrev** [comment]
@hasit Have a look at a related issue - https://github.com/github/hub/issues/448. It won't solve your problems, but it could be a duplicate.

**Comment by mislav** [comment]
Good catch, @hasit! I'm pretty sure that the `GitExtension` thing was a typo. I flipped the value and now the help text is shown.
