### ISSUE TITLE
git compare hangs after launching tab in Firefox

### ISSUE THREAD

**Issue by Jonnymcc** [github/hub#926]
When I run `git compare` on the command line, git hangs with the following error...
`(process:9116): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed`

This probably is not a bug in hub, but I wanted to double check that the expected behavior would be that a tab opens in the browser and the terminal returns to the command prompt. Instead I end up having to ctrl-c to exit the process.

I am running Ubuntu 14.04 and here is my git and hub versions...
```
git version 2.4.3
hub version 2.2.0-40-g5209bbf
```

**Comment by mislav** [comment]
Thanks for reporting. What is the output of:

```
browser="$(which xdg-open cygstart x-www-browser firefox opera mozilla netscape | head -1)"
echo $browser
"$browser" https://github.com
```

**Comment by Jonnymcc** [comment]
The output is
`(process:10324): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed`

but the command `"$browser" https://github.com` does return to the command prompt.

**Comment by mislav** [comment]
What is the output of `echo`?

**Comment by Jonnymcc** [comment]
/usr/bin/xdg-open

**Comment by mislav** [comment]
Might it be an issue with `xdg-open` on your system?

**Comment by mislav** [comment]
I think this is a problem with `xdg-open` on your system and not hub. Let us know if you think we can do something to avoid this.
