### ISSUE TITLE
pull request not using upstream branch as HEAD

### ISSUE THREAD

**Issue by OliverJAsh** [github/hub#928]
Given:

```
[remote "origin"]
	url = https://github.com/systemjs/systemjs.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "OliverJAsh"]
	url = https://github.com/OliverJAsh/systemjs.git
	fetch = +refs/heads/*:refs/remotes/OliverJAsh/*
[branch "oja-patch-1"]
	remote = OliverJAsh
	merge = refs/heads/oja-patch-1
```

If I'm on branch `oja-patch-1` and I `hub pull-request`:

```
# Requesting a pull to systemjs:master from systemjs:oja-patch-1
```

How come the head is not automatically setting to OliverJAsh/oja-patch-1, when that is the upstream branch?

**Comment by mislav** [comment]
Does `origin/oja-patch-1` exists as a remote branch in addition to existing in your fork? That might explain why it picked the wrong repo.

What is your `hub version` and `git config push.default`? Thanks

**Comment by OliverJAsh** [comment]
No, it only exists in my fork.

git version 2.4.3
hub version 2.2.1

**Comment by mislav** [comment]
Thanks. And `git config push.default`?

**Comment by OliverJAsh** [comment]
current

**Comment by edude03** [comment]
I think I'm experiencing the same issue,

Using:
```
git version 2.4.2
hub version 2.2.1-gb0f092a
git config push.default simple
```

when I: 
```
git clone git@github.com:mycompany/myproject.git
git checkout -b myfeature
[do and commit work]
git push -u origin myfeature
hub pull-request
```

it defaults to
```
requesting a pull to edude03:master from edude03:myfeature
```

whereas I'd expect (and what I'd consider to be the correct behaviour)

```
requesting a pull to mycompany/myproject:master from mycompany/myproject:myfeature
```

I can make it work by doing 

```
hub pull-request -b mycompany/myproject:master -h mycompany/myproject:myfeature
```

However that is pretty inconvenient.

**Comment by mislav** [comment]
Thanks for all the info. I don't know what's going on. I need to investigate.

**Comment by terminalmage** [comment]
@mislav There seem to be two separate issues here. The first is that the upstream branch is not being used as the head branch. The second is that, even when I manually specify the head branch (via ``-h terminalmage:issue27703``), the username is incorrectly identified in the comment lines in the editor when you are prompted to add a message for the pull request:

```
# Requesting a pull to saltstack:2015.8 from saltstack:issue27703
```

**Comment by mislav** [comment]
@terminalmage Thanks for letting me know about the 2nd issue. Is only the comment wrong, and the PR does indeed get opened with `terminalmage:issue27703` as the head? Or does the PR get opened with the wrong head?

**Comment by terminalmage** [comment]
The comment is the only thing that is wrong, the pull request is still opened with the correct branch. I also noticed something: This only seems to happen when I forget to use ``-h`` (which happens often since I'm not used to having to use it), then back out of the pull request without editing the message, followed by running ``hub pull-request`` *with* ``-h``. This suggests that the ``PULLREQ_EDITMSG`` created by hub is being reused in these cases, instead of recreated with the correct details.

**Comment by mislav** [comment]
> This suggests that the PULLREQ_EDITMSG created by hub is being reused in these cases, instead of recreated with the correct details.

Yes, you are right. We do save a failed pull request message in case you want to re-use it without retyping everything. This one line needs to be updated, though, even if the rest of the text remains the same.

**Comment by terminalmage** [comment]
@mislav Thanks for confirming. Should I file a new issue for that since it is a different bug than the one reported?

**Comment by mislav** [comment]
No, it's something that I'm aware of. Thanks!

**Comment by OliverJAsh** [comment]
Any ideas what's going on here? Still bothering me!

**Comment by terminalmage** [comment]
@OliverJAsh What version? I'm no longer seeing this on hub 2.2.3.

```
% hub --version
git version 2.9.0
hub version 2.2.3
```

**Comment by OliverJAsh** [comment]
$ hub --version
git version 2.9.2
hub version 2.2.3

**Comment by terminalmage** [comment]
Hmm, so I *just* upgraded to Git 2.9.0 a day ago, and I'm seeing this problem again. This may have regressed due to changes in Git itself.

@mislav can you have another look?

**Comment by terminalmage** [comment]
To clarify, this was working for me with hub 2.2.3 with a range of different Git versions, from at least 2.4 or so through 2.8, but now it's broken again.

**Comment by mislav** [comment]
This is caused by the same issue as described in https://github.com/github/hub/issues/877. Trying to fix soon. Please follow other issue for updates.

**Comment by terminalmage** [comment]
@mislav Thanks for the update, I've subscribed to updates for #877.
