### ISSUE TITLE
hub authentication failing

### ISSUE THREAD

**Issue by jsh** [github/hub#931]
In general, I can do anything with hub that doesn't require I enter a password.

I've disabled 2-factor authentication, but that doesn't help, so I assume I'm doing something wrong.
This problem occurs whether I paste the password or type it in. The same password does log me in successfully.

I started to ask GitHub support, but decided to start here first, because I thought I might get better help. If that was wrong, I apologize.

$ git init foo1; cd $_; > README; git add $_; git commit -m'initial'
$ uname -a
$ hub --version
git version 2.4.4
hub version 2.2.1
$ hub create -d'my test repo'
github.com username: jsh
github.com password for jsh (never stored): 
Error creating repository: Unauthorized (HTTP 401)
Bad credentials

**Comment by mislav** [comment]
Sorry you're having trouble. Are you entering your real GitHub password? Entering an OAuth token won't work.

Also, are you on Windows by any chance? We had a bug on Windows password prompt which will be fixed in 2.2.2

**Comment by jsh** [comment]
Mislav,

Thanks!

I'm entering my real GitHub password. I did at least try an OAuth token,
but it gave me a different error. I actually tried several things that
didn't work, and then decided it'd be quicker to ask what I was doing
wrong. :-)

I forgot to include system info. My apologies. Here 'tis:

$ uname -a
Linux jhaemer-ThinkPad-T440 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18
00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty

Everything's pretty up-to-date, and I'm pleased as punch to do any
experiments you suggest. I'm assuming it's me, though in the trivial sense.
(I.e., "I'm doing something bone-headed," not "The software has a flag that
says, 'Don't work if it's Jeff Haemer.' ")

On Mon, Jun 22, 2015 at 10:26 AM, Mislav Marohnić <notifications@github.com>
wrote:

> Sorry you're having trouble. Are you entering your real GitHub password?
> Entering an OAuth token won't work.
>
> Also, are you on Windows by any chance? We had a bug on Windows password
> prompt which will be fixed in 2.2.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hub/issues/931#issuecomment-114171003>.
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by jsh** [comment]
Mislav,

Same results from a newly-created, cloud VM, running CentOS 7.1.1503,
created with Google Compute Engine. Stock git (1.8.3.1). Hub from latest
release tarball (
https://github.com/github/hub/releases/download/v2.2.1/hub-linux-amd64-2.2.1.tar.gz).
"git clone" , from GitHub, is working fine from the same box, as is "git
push" .

So, it's wasn't my laptop/environment/distro.  Heck.

On Mon, Jun 22, 2015 at 10:50 AM, Jeffrey S. Haemer <
jeffrey.haemer@gmail.com> wrote:

> Mislav,
>
> Thanks!
>
> I'm entering my real GitHub password. I did at least try an OAuth token,
> but it gave me a different error. I actually tried several things that
> didn't work, and then decided it'd be quicker to ask what I was doing
> wrong. :-)
>
> I forgot to include system info. My apologies. Here 'tis:
>
> $ uname -a
> Linux jhaemer-ThinkPad-T440 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18
> 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 14.04.2 LTS
> Release: 14.04
> Codename: trusty
>
> Everything's pretty up-to-date, and I'm pleased as punch to do any
> experiments you suggest. I'm assuming it's me, though in the trivial sense.
> (I.e., "I'm doing something bone-headed," not "The software has a flag that
> says, 'Don't work if it's Jeff Haemer.' ")
>
> On Mon, Jun 22, 2015 at 10:26 AM, Mislav Marohnić <
> notifications@github.com> wrote:
>
>> Sorry you're having trouble. Are you entering your real GitHub password?
>> Entering an OAuth token won't work.
>>
>> Also, are you on Windows by any chance? We had a bug on Windows password
>> prompt which will be fixed in 2.2.2
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/github/hub/issues/931#issuecomment-114171003>.
>>
>
>
>
> --
> Jeffrey Haemer <jeffrey.haemer@gmail.com>
> 720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
> http://www.youtube.com/user/goyishekop [vlog]
> *פרייהייט? דאס איז יאַנג דינען וואָרט.*
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by mislav** [comment]
It doesn't look like you're doing anything wrong. You can trigger an HTTP debugging mode with:

```
HUB_VERBOSE=1 hub create -d 'my test repo'
```

which will show HTTP requests as they're being made, and there should be an `Authorization` header being sent, but its contents will be redacted for security purposes (so you don't accidentally paste someone your credentials). You can check that out to see if anything interesting is going on.

That said, I have no idea why you aren't able to log in using your valid username and GitHub password.

**Comment by mislav** [comment]
You can try authenticating with `curl` to check your credentials: Try:

```
curl -u jsh https://api.github.com/user
```

It will prompt you for GitHub password and, if entered correctly, should perform a GitHub API request. If that works, then something is broken in hub.

**Comment by jsh** [comment]
Ah. That's a clue.

{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

Let me poke for a few minutes -- see if I can change my password and get it
to work or something.



On Mon, Jun 22, 2015 at 12:39 PM, Mislav Marohnić <notifications@github.com>
wrote:

> You can try authenticating with curl to check your credentials: Try:
>
> curl -u jsh https://api.github.com/user
>
> It will prompt you for GitHub password and, if entered correctly, should
> perform a GitHub API request. If that works, then something is broken in
> hub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hub/issues/931#issuecomment-114211573>.
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by jsh** [comment]
Mislav,

Eureka. That was the clue that solved it. The password being auto-filled in
when I logged in wasn't the one in LastPass, it was one that my browser had
cached.

When I use the browser-cached password, all works perfectly.

Thank you very much!

On Mon, Jun 22, 2015 at 12:45 PM, Jeffrey S. Haemer <
jeffrey.haemer@gmail.com> wrote:

> Ah. That's a clue.
>
> {
>   "message": "Bad credentials",
>   "documentation_url": "https://developer.github.com/v3"
> }
>
> Let me poke for a few minutes -- see if I can change my password and get
> it to work or something.
>
>
>
> On Mon, Jun 22, 2015 at 12:39 PM, Mislav Marohnić <
> notifications@github.com> wrote:
>
>> You can try authenticating with curl to check your credentials: Try:
>>
>> curl -u jsh https://api.github.com/user
>>
>> It will prompt you for GitHub password and, if entered correctly, should
>> perform a GitHub API request. If that works, then something is broken in
>> hub.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/github/hub/issues/931#issuecomment-114211573>.
>>
>
>
>
> --
> Jeffrey Haemer <jeffrey.haemer@gmail.com>
> 720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
> http://www.youtube.com/user/goyishekop [vlog]
> *פרייהייט? דאס איז יאַנג דינען וואָרט.*
>



-- 
Jeffrey Haemer <jeffrey.haemer@gmail.com>
720-837-8908 [cell], http://seejeffrun.blogspot.com [blog],
http://www.youtube.com/user/goyishekop [vlog]
*פרייהייט? דאס איז יאַנג דינען וואָרט.*

**Comment by mislav** [comment]
No problem! Glad you figured it out.
