### ISSUE TITLE
remote add protocol incorrect?

### ISSUE THREAD

**Issue by Jonnymcc** [github/hub#934]
When I ran `git remote add NAME` it added a remote like
`NAME    git://github.com/NAME/MY-REPO.git`

When I tried `git fetch` I got
```
fatal: remote error: 
  Repository not found.
```

Should the protocol be `git@github.com:` because that is what works for me with all my remotes.

**Comment by Jonnymcc** [comment]
Nevermind, had not read the docs thoroughly. Shouldn't the default be the ssh protocol though?

https://github.com/github/hub#https-instead-of-git-protocol

**Comment by mislav** [comment]
Sorry you had trouble. Yeah, SSH might be a good default for people like you, but not for all. This is why the question of a good default is so complex. We are considering defaulting to HTTPS protocol in future releases, for simplicity in the long run. You will still be able to choose a protocol explicitly in configuration.

**Comment by LCLYcityhub** [comment]
Help me about the Vpn with android device samsung galaxy mega
