### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by brandondrew** [github/hub#935]
I'd like to know what advantage there is to putting

    eval "$(hub alias -s)"

in my `.zshrc` file, instead of just a plain ol'

    alias git=hub

It *appears* to be the case—and I may be missing something, but that's where the documentation would be helpful—that `hub alias -s` simply executes `alias git=hub`, so why not just add the simpler and more direct version to my config file, instead of the very indirect version?

**Comment by mislav** [comment]
The `hub alias -s` expression may contain more configuration in the future than just alias. Having people add that into their shell means that we can update the `hub alias` output in the future to configure shell completion scripts for hub, for example. We're still working on improving bash and zsh completion scripts.

I hope that answers your question!
