### ISSUE TITLE
Feature: Allow a configuration setting to set a markdown template for pull requests

### ISSUE THREAD

**Issue by dhilton** [github/hub#937]
It would be great if on a global basis, I could set a text based template for pull requests, so that when I issue a pull request it gives me a set of headings to fill in, ensuring that I meet the given style for PR's.

References: 

http://www.annashipman.co.uk/jfdi/good-pull-requests.html
https://github.com/alphagov/styleguides/blob/master/pull-requests.md

Happy to take a first stab at this improvement if committers like the cut of it's jib.

**Comment by hasit** [comment]
I can see this being very useful. Some projects can provide templates if they are strict about their format and hub can read it from .git or a special directory inside.
:+1:

**Comment by mislav** [comment]
Note that the `--edit` option was proposed to be added to `hub pull-request` that will allow passing of filename and editing it in text editor in the same step.

**Comment by dhilton** [comment]
@mislav - I'll have a crack at adding tests to #924 - that looks ok as long as we can cleanly rebase against current master.

**Comment by paul** [comment]
I'm also :+1: on this feature request. Git already has a template system for commit messages ( https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template ), so something similar for pull request templates would be extremely helpful.
