### ISSUE TITLE
Shortcut to open issue or PR from the command line

### ISSUE THREAD

**Issue by icyflame** [github/hub#938]
Currently, to open some issue or PR of the current repo : -

```shell
hub browse -- issues/2
```

Instead of this, make it so that, 

```shell
hub browse #2
```

will open the issue (or PR) in the browser.

(This can be done with a bash alias, but it would be great if `hub` had the functionality baked in!)

**Comment by mislav** [comment]
This is planned! #897

Note that we won't be able to literally use `#2` syntax because `#` is a comment character in shell script. Bash will ignore anything after it.

**Comment by icyflame** [comment]
Yeah, sure. Not hash probably, but some character to make it easier! I am glad it is planned!
