### ISSUE TITLE
Change remote description after initial creation

### ISSUE THREAD

**Issue by IngwiePhoenix** [github/hub#939]
Imagine you have forgotten to add a `-d description` during the creation process and you want to add one. It seems that re-running the creation does not automatically update the description.

Is this meant to be that way and what is the proper way to update a description from the command line?

**Comment by mislav** [comment]
No, there is no way right now to update the description. There might be in the future, although this isn't on our roadmap right now. Re-running the creation is a no-op if the repo already exists.

To edit the description, use `hub browse` and edit it from the web interface.
