### ISSUE TITLE
Provide --no-interactive option for scripts

### ISSUE THREAD

**Issue by rjmunro** [github/hub#940]
I have a script in my project that calls `hub pr` to make a PR with certain options pre-set. If this script is run by someone who hasn't used hub before, it just hangs as hub is waiting for them in input their login information, but my script is capturing hub's output.

Some commands have a `--no-interactive` option which you can use in a script file. When they encounter something to ask the user, they fail, rather than cause the parent script to hang. Could this be added to hub?

**Comment by mislav** [comment]
Once we have #225, my idea was to turn the interactive prompt for authentication off. This will help with scripts. Instead, all authentication will have to be explicitly initiated by the user.

**Comment by mislav** [comment]
Closing as this will be part of the feature I referenced in the above issue.
