### ISSUE TITLE
Show all build statuses with `ci-status`

### ISSUE THREAD

**Issue by teoljungberg** [github/hub#943]
If a repository has multiple CI's setup, `ci-status -v` will only show the first one in the list. I would expect it to list all CI's

Tested against version `2.2.1`

**Comment by mislav** [comment]
Good idea. `ci-status` was designed before GitHub had multiple CI status support. Now we have to rethink it.

**Comment by paradox460** [comment]
:+1:

**Comment by teoljungberg** [comment]
Is this something we that is being considered?

**Comment by mislav** [comment]
I definitely want to solve this soon.

**Comment by teoljungberg** [comment]
This morning I noticed that this is working now. Thank you so much!
