### ISSUE TITLE
Use **GITHUB_TOKEN** environment variable to save the token

### ISSUE THREAD

**Issue by stevemao** [github/hub#948]
This module looks for **GITHUB_USER** and **GITHUB_PASSWORD** environment variables and get a token then store in "~/.config/hub". Why not just look for **GITHUB_TOKEN** environment variable straight away? If not found try to fallback to use username and password to get the token then store in **GITHUB_TOKEN**?

**Comment by mislav** [comment]
Planned! https://github.com/github/hub/issues/463#issuecomment-32387755

Thanks for the suggestion.
