### ISSUE TITLE
Ability to block operations on github webhooks response

### ISSUE THREAD

**Issue by mvallebr** [github/hub#949]
Webhooks allow us to triggers external services when operations occur, which is an awesome feature by itself, but it could be even more useful if depending on the result of the execution, we could block a pull request to be created, or a push to be made, etc. 

This would allow us users to have full control on the workflow followed by the team, which could be really useful for continuous integration, for instance. I would love to stop pull requests from being created if my validation service returns "not ok", for instance.

**Comment by mislav** [comment]
Hi, it seems like you have a suggestion for improving GitHub platform itself, not this tool specifically (hub a CLI tool that wraps git). Maybe you should write to support@github.com instead?
