### ISSUE TITLE
Unable to launch pull-request from command line - error occurs

### ISSUE THREAD

**Issue by jake223** [github/hub#954]
I try to do a pull-request from the command line, and the following happens:

    [~/workspace/mafia-app/mafia]$ hub pull-request             [techdebtfixes][ruby-2.1.3]
    /usr/local/bin/hub:1179:in `==': undefined method `name_with_owner' for nil:NilClass (NoMethodError)
	from /usr/local/bin/hub:1763:in `pull_request'
	from /usr/local/bin/hub:1640:in `run'
	from /usr/local/bin/hub:2579:in `initialize'
	from /usr/local/bin/hub:2583:in `new'
	from /usr/local/bin/hub:2583:in `execute'
	from /usr/local/bin/hub:2634:in `<main>'

I haven't logged into `hub` before, the first time I ran this it prompted for my login information and when I gave it it errored. Now it errors immediately (presumably it's storing some session token). I'm on OS X Yosemite (10.10.2), and I have ruby version 2.1.3.

**Comment by mislav** [comment]
You might be using an old, buggy version of hub back when it was still implemented in Ruby. How about giving latest hub v2.2 a go? You can download a precompiled binary, it will execute faster than ever, and you won't need Ruby as a dependency.

**Comment by jake223** [comment]
As it turns out I am using an old, buggy version of hub. My homebrew configuration was very old, and for some reason I had some local unstaged files that prevented git from updating the package list properly. I now am running the latest and don't have this issue any more.
