### ISSUE TITLE
If it's wrapper, why ask for my username and password?

### ISSUE THREAD

**Issue by parnmatt** [github/hub#955]
Surely if it is a wrapper, it should be using `git` for all the things git itself can do.

    hub clone -p REPO        --->        git clone git@github.com:USERNAME/REPO

In this case, it is clear it needs the username, but it should run the command after getting the username, as `git` itself will check SSH keys, and if there isn't any, ask for authentication.

To speed things up, couldn't there be a section in the `.gitconfig` file?

    [github]
        username = USERNAME

Your email address that GitHub can authenticate with and know who you are should be under

    [user]
        email = EMAIL

anyway, so it should use that by default and let `git` deal with authentication.

Now, it's been a while since I used GitHub without SSH keys, so I cannot remember if it authenticates using your username, email you signed up with, or any valid email you have GitHub configured to know as you; or all.

If just the username, than above is fine. If any email you have GitHub configured with, above should also be fine, as `user.email` contains that. If it has to be the email you signed up with, then another field `hub.email` should be used if different than `user.email`, defaulting back on `user.email` if the field doesn't exist. If all, well above is fine.

**Comment by waterlink** [comment]
AFAIK, `hub` is not just wrapper: `hub` uses Github API to do additional stuff, that `git` can't do (like forking, creating issue, pull request, etc). To use Github API you need to authenticate an Oauth(2) app (which `hub` is) and to do that it needs to ask you once for your username/email and password (and possible 2FA if you have one enabled). After that it just stores access token on your machine to use it with Github API.

**Comment by parnmatt** [comment]
Ok that makes sense for API calls. However I'm a little surprised that it's using an API call to clone a repo.

**Comment by mislav** [comment]
> However I'm a little surprised that it's using an API call to clone a repo.

It uses the API call to check if a repo is private or public and make decisions about clone protocol based on that. In the future, we might also scan your orgs to see if `<REPO>` is to be cloned from your own account (if it exists) or from one of the orgs that you belong to.
