### ISSUE TITLE
Error on page hub.github.com

### ISSUE THREAD

**Issue by a-x-** [github/hub#956]
```sh
# open the GitHub compare view between two releases
git compare v0.9..v1.0
```

but must be `git compare v0.9...v1.0` (3 dots)

**Comment by parkr** [comment]
This looks like it's handled: https://github.com/github/hub/blob/1e8f4f4f83c8dc3058ccf0a9d082d553796dc210/features/compare.feature#L66-L69

**Comment by a-x-** [comment]
❯ hub version                                                                                                                                                                           
git version 2.3.2
hub version 2.2.0-rc1-38-g1409606

**Comment by a-x-** [comment]
```sh
git compare images-desktop/v1.42.0..images-desktop/v1.42.2
# opens https://github.<enterprise>/<path>/compare/images-desktop/v1.42.0..images-desktop/v1.42.2

git compare images-desktop/v1.42.0...images-desktop/v1.42.2
# opens https://github.<enterprise>/<path>/compare/images-desktop/v1.42.0...images-desktop/v1.42.2
# and its correct address
```

**Comment by mislav** [comment]
@a-x- The two dots `..` are converted into three dots `...` only for simple expressions. Yours has slashes, so you need to use `...`. We avoid parsing complex expressions in order to not mangle any of its content. This is by design. Sorry that you tripped up on it.

**Comment by a-x-** [comment]
ok
btw, slash here is simply part of branch

**Comment by mislav** [comment]
Yeah, I understand. But it's better that you pass triple dot yourself when building out compare ranges between branches that have special characters.

**Comment by a-x-** [comment]
ok
