### ISSUE TITLE
Checking out pull request creates new remote

### ISSUE THREAD

**Issue by codeinabox** [github/hub#957]
I've noticed that when I do `hub checkout https://github.com/SomeOrganisationPLC/some-repo/pull/40` it creates a new called "SomeOrganisationPLC" for example. How can I can control this behaviour as it seems to interfere with my origin remote?

**Comment by mislav** [comment]
Hey, sorry that you had trouble. We're in the process of changing the commands that create remotes behind-the-scenes to not do that anymore. I also don't like extra remotes piling up in the background that I need to clean up later. This is already on the roadmap!

**Comment by tflhyl** [comment]
Hi may i know if there is workaround for this?
