### ISSUE TITLE
Allow assigning a pull-request to a person upon creation

### ISSUE THREAD

**Issue by jake223** [github/hub#960]
I like to use `hub pull-request` to create a pull request, but I still have to open the GitHub website in order to assign a person to that pull request. If I could do so with a flag to `pull-request`  that would be excellent, and I wouldn't have to use the web interface at all for my pull requests.

**Comment by nlutsenko** [comment]
:+1: Would love to have this, pretty please.

**Comment by jake223** [comment]
This seems to exist already with "-a USER"??? I guess I filed this issue when I was using an old version of hub by mistake.
