### ISSUE TITLE
URL for commands is incorrectly calculated.

### ISSUE THREAD

**Issue by jtnord** [github/hub#962]
For some repositories the URL for the repository is incorrectly calculated, causing hub commands to fail.

```
C:\work\cloudbees-documentation>hub pull-request -m "some message"
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/jtnord/cloudbees exists?
                                    ^^^^^^^^^
```
```
C:\work\cloudbees-documentation>git remote -v
jtnord  git@github.com:/jtnord/cloudbees-documentation.git (fetch)
jtnord  git@github.com:/jtnord/cloudbees-documentation.git (push)
origin  git@github.com:/cloudbees/cloudbees-documentation.git (fetch)
origin  git@github.com:/cloudbees/cloudbees-documentation.git (push)

C:\work\cloudbees-documentation>git fetch origin

C:\work\cloudbees-documentation>git fetch jtnord
```

`hub browse` opens a browser at `https://github.com/jtnord/cloudbees` not `https://github.com/cloudbees/cloudbees-documentation`

It appears as though in this case hub has stripped the "-documentation" from the calculated URL and is using the fork rather than the origin repo.

```
C:\work\cloudbees-documentation>hub --version
git version 1.9.5.msysgit.0
hub version 2.2.1
```

**Comment by jtnord** [comment]
If it makes a difference this repository contains submodules.

**Comment by mislav** [comment]
We expect the SSH URL format to be like `git@github.com:cloudbees/cloudbees-documentation.git` (notice the absence of the initial slash). Can you change your URLs and see if this makes a difference?

We can fix this in code (I already started making a test), but until the next bugfix release simply removing the initial slash might be a good workaround for you. Please report back.

**Comment by jtnord** [comment]
removing the leading slash causes this to work. (tested with `hub browse`)

**Comment by mislav** [comment]
Thanks. May I ask how you ended up with the initial slash? Was it some program that pasted you the URL? I'm trying to see how many people are potentially affected.

Until next bugfix release, please don't use the slash. Git's own push/pull should behave just the same.

**Comment by jtnord** [comment]
> May I ask how you ended up with the initial slash?

the URL came from a `.gitmodules` file.  where it came from in that file I can only speculate as finger trouble.

**Comment by mislav** [comment]
I see. Since this is only a one-time occurrence and not a widespread problem, I'll just close it as solved. If this happens again, we can reevaluate whether this needs working around in hub.
