### ISSUE TITLE
`hub create` or `git create`?

### ISSUE THREAD

**Issue by kenorb** [github/hub#966]
When I run `hub help create` it shows the following syntax:

> usage: git create [-p] [-d DESCRIPTION] [-h HOMEPAGE] [NAME]

However when run: `git create` it show the error:

> git: 'create' is not a git command. See 'git --help'.

What's the correct syntax? Should the syntax be: `hub create` instead?

**Comment by parkr** [comment]
@kenorb It requires that you alias `hub` to `git`: `alias git="hub"`. Then it should work. It'd be nice to see these help pieces use `os.Args[0]` to reduce this confusion.

**Comment by mislav** [comment]
@parkr Thanks for the answer. It would be nice, except we can't detect if a program was aliased in the first place. `Args[0]` would report "hub" in both cases.

**Comment by kenorb** [comment]
Seems `type` command can detect whether command is aliased or not, not sure how to check in Python.
