### ISSUE TITLE
Import repository from CLI.

### ISSUE THREAD

**Issue by kenorb** [github/hub#967]
Is there any command-line functionality to import external repository into GitHub using command-line interface as equivalent to https://import.github.com/new ? Like: `hub import`?

**Comment by mislav** [comment]
Sorry, we have no plans to implement this functionality. I don't think it's even available from the GitHub API, which we would need if we were to implement the `import` CLI command.

Are you often importing repositories? I feel like it's best to do it from the web interface, especially because you will ever do it once for each project.

**Comment by kenorb** [comment]
Doesn't affect me much. However I believe a lot of developers will need that this year more than usual, as on August 25th Google Code goes [read-only](https://code.google.com/p/support/wiki/ReadOnlyTransition), therefore importing each repository of interest manually it's a bit pain.
As workaround this may help: [Importing a Git repository using the command line](https://help.github.com/articles/importing-a-git-repository-using-the-command-line/), but the instructions are not completely command-line however first step can be replaced by using `hub create`.

**Comment by hkdobrev** [comment]
I think an alias which performs `git clone`, `git create` (via `hub`), `git push` would be enough. Not sure if `git create` would add the needed remote automatically, but `git remote add` could always be used. The alias can use the current directory or cloned repo name for the GitHub repo to be created.

**Comment by mislav** [comment]
@kenorb I think importing using those instructions is fine, and I don't have motivation to encapsulate this as a new `import` command. Hopefully, each user will just have to import one or a handful of repos this way, and then won't need to import anything again. So I don't think this command would see a lot of usage.
