### ISSUE TITLE
Always start powerShell

### ISSUE THREAD

**Issue by pumpi** [github/hub#971]
I can change the option to any shel but it always start powerShell i test this on an Win7 an an Win10 PC same problems

**Comment by mislav** [comment]
I'm sorry; what is your exact problem?

**Comment by pumpi** [comment]
I like the Git Bash. After the last Update i can change the options to any other but wenn i launch the icon i always get the powerShell

![gitshell](https://cloud.githubusercontent.com/assets/412142/9130524/e4ade3d2-3ce3-11e5-8767-49ee42c8140f.png)

**Comment by mislav** [comment]
Ah I see. You want to report a problem with GitHub for Windows desktop client. This is the wrong issue tracker to do that. This project is called "hub" and is a simple command-line wrapper around `git` and is a completely separate project than GiHub for Windows.

You should submit your problem (together with screenshot) to support@github.com

Sorry that I can't help more! Good luck.
