### ISSUE TITLE
Error when source .zshrc or open new zsh session?

### ISSUE THREAD

**Issue by geekplux** [github/hub#972]
I get following erros, when I source the .zshrc or open a new zsh session after installed hub by brew on my Macbook. 

```shell
zsh:12: command not found: ___main
_default:compcall:12: can only be called from completion function
```

However, it was normal after I `brew uninstall hub`...
So I am a little confused, and have to open a issue to consult you. 囧

**Comment by mislav** [comment]
Sorry about that. Which zsh version are you using? `zsh --version`

How is your zsh set up? See your `.zshrc` and `.zshenv`. Are you using oh-my-zsh or Prezto?

**Comment by geekplux** [comment]
Sorry I didn't express clearly.

- version: zsh 5.0.7 (x86_64-apple-darwin14.0.0)
- by `brew`
- using `oh-my-zsh`

thank you.

**Comment by ianp** [comment]
I had a similar problem but was able to fix it by not loading the git and github plugins in Oh-my-zsh. In your `.zshrc` file

```sh
# change this line (line 36 for me)
plugins=(git github lein osx svn)
# to this
plugins=(lein osx svn)
```

**Comment by geekplux** [comment]
@ianp thank you!

**Comment by mislav** [comment]
We have some problems with our zsh completion script; I'm sorry. See #771

We'll try to work on it.
