### ISSUE TITLE
Allow --ff with merge

### ISSUE THREAD

**Issue by CraigyDavi** [github/hub#973]
At the moment when you try and merge a pull request using --ff (not --ff-only) it adds the --no-ff argument to the end.
There should be a check [here](https://github.com/github/hub/blob/master/commands/merge.go#L80)(?) which makes sure --no-ff is not added when using --ff.

This is so people can merge pull requests using fast-forward and also do so recursively using hub!

**Comment by mislav** [comment]
Good catch. Maybe you could make a pull request that adds the check?

**Comment by CraigyDavi** [comment]
I'm new to go, but I'll give it a go! (no pun intended)
