### ISSUE TITLE
inappropriate ioctl for device running `hub pull-request`

### ISSUE THREAD

**Issue by zmerlynn** [github/hub#976]
We have [a script](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/cherry_pick_pull.sh) in the Kubernetes repo that makes use of the hub command to try to generate automated pull requests that are essentially cherry-picks of other pull requests from the `master` branch. We've had a couple of users now complain about the following stack trace:
```
To git@github.com:dchen1107/kubernetes-1.git
 + 3a1ff78...f78c9f7 automated-cherry-pick-of-#12541-upstream-release-1.0-1439397110 -> automated-cherry-pick-of-#12541-upstream-release-1.0 (forced update)
+++ Creating a pull request on github
github.com password for dchen1107 (never stored): inappropriate ioctl for device

goroutine 1 [running]:
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getch(0x4c208000100)
	/usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/nix.go:13 +0x74
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.getPasswd(0x0, 0x0, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:18 +0x11f
github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass.GetPasswd(0x0, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/Godeps/_workspace/src/github.com/howeyc/gopass/pass.go:37 +0x3e
github.com/github/hub/github.(*Config).PromptForPassword(0x4c20801d740, 0x4c2080a420a, 0xa, 0x7fffeb086ceb, 0x9, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/github/config.go:123 +0x1eb
github.com/github/hub/github.(*Config).PromptForHost(0x4c20801d740, 0x4c2080a420a, 0xa, 0x0, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/github/config.go:61 +0xfe
github.com/github/hub/commands.pullRequest(0xa88840, 0x4c208068090)
	/usr/local/src/goproj/src/github.com/github/hub/commands/pull_request.go:93 +0x11e
github.com/github/hub/commands.(*Command).Call(0xa88840, 0x4c208068090, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/commands/commands.go:47 +0x184
github.com/github/hub/commands.(*Runner).Call(0x4c208028880, 0xa88840, 0x4c208068090, 0x0, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/commands/runner.go:93 +0x54
github.com/github/hub/commands.(*Runner).Execute(0x4c208028880, 0x0, 0x0, 0x0)
	/usr/local/src/goproj/src/github.com/github/hub/commands/runner.go:85 +0x215
main.main()
	/usr/local/src/goproj/src/github.com/github/hub/main.go:12 +0x40
```

Obviously could be a further downstream issue in https://github.com/howeyc/gopass, but I thought I'd start with a bug here.

cc @dchen1107 @brendandburns

**Comment by mislav** [comment]
Thanks for letting us know. Was the script output attached to a terminal at the time?

Ideally, the user should already be logged in with hub before using hub through any automated scripts. We will provide a dedicated command to authenticate. We will also probably make it so that commands that require authentication fail instead of prompting for credentials automatically.

**Comment by zmerlynn** [comment]
Is there an easy check I can do in that script that they're auth'd correctly as a preflight check? We already validate `hub` is installed.

The script is feeding in a message via `-F-`, so normal terminal access might be an issue. I could do a tmpfile dance instead, hm.

**Comment by mislav** [comment]
Right now the only way to find out is checking the oauth token in `~/.config/hub`. It's not pretty, but it's a pretty solid way to check.

**Comment by yujuhong** [comment]
> We will provide a dedicated command to authenticate. We will also probably make it so that commands that require authentication fail instead of prompting for credentials interactively.

Both would be nice. I ran into the same problem and had to run `hub pull-request` manually to store the oauth token in ~/.config/hub.

**Comment by mislav** [comment]
I'm gonna close this in favor of #225 which describes a need for a dedicated command to do authentication. Scripts will be able to check whether the user has authenticated, and commands will fail non-interactively if authentication is necessary (instead of prompting).
