### ISSUE TITLE
git help hub looks up the wrong manpage

### ISSUE THREAD

**Issue by nilbus** [github/hub#977]
I have the hub manpage installed (`man hub` works fine). However `git help hub` fails, trying to look up the wrong manpage:

    $ git help hub
    No manual entry for github

**Comment by mislav** [comment]
Thanks for reporting. I think `git help` assumes that there will be a `github` man page for the `git-hub` command that it thinks you're trying to get documentation for.

We should fix this by either intercepting the `git help` command in hub to display the correct man page, or by symlinking our `hub` man page as `github` as well.
