### ISSUE TITLE
Use latest commit message as the pull request title and body defaults

### ISSUE THREAD

**Issue by cirosantilli** [github/hub#980]
Just fill in the editor with the last commit message when running `hub pull-request`.

The first line will be the title, and the rest of the commit message the body.

**Comment by mislav** [comment]
We do that when we detect that the branch has only 1 commit. This matches what the GitHub web UI will do when opening a pull request as well.

We don't want to do it when there are more than 1 commit, though. What we do instead is preserve all commit messages commented out in the template to edit prior to submitting a pull request. If you want to keep any of those messages, you can just uncomment them.
