### ISSUE TITLE
`create organization/name` failing

### ISSUE THREAD

**Issue by ariscn** [github/hub#983]
```
$ hub create org/name
Error creating repository: Unprocessable Entity (HTTP 422)
You need admin access to the organization before adding a repository to it.

$ hub create -p org/name
Error creating repository: Unprocessable Entity (HTTP 422)
You need admin access to the organization before adding a repository to it.
```

I can `hub clone` our private repos, and create new repos for my org via Github's website without error, so the error above is misleading, or a bug.

**Comment by mislav** [comment]
Thanks for reporting. This may be a GitHub API error. Do you still have this problem? If so, let me know so I can find out what's happening.

**Comment by mislav** [comment]
Closing due to lack of info. Please check your org permissions!
