### ISSUE TITLE
background ssh connection

### ISSUE THREAD

**Issue by ccding** [github/hub#984]
After running the hub command, there is an ssh connection running in the background forever. The process is `ssh: /tmp/git@github.com:22 [mux]'

What's the purpose for this? and how to avoid this?

**Comment by mislav** [comment]
Hi, sorry for the late reply. I don't think this is related to hub. It might be that some other repo was cloning something over SSH protocol (`git@github.com:...` git remotes). In any case, the process shouldn't be lingering too long. Are you seeing this problem still? What is your `hub --version`? Thanks!

**Comment by ccding** [comment]
Sorry for the mis-report. I figured it out that it was caused by the "TCPKeepAlive=yes" setting in my ssh configuration file.

**Comment by mislav** [comment]
Alright thank you for the update!
