### ISSUE TITLE
Clone all repos from a github organization

### ISSUE THREAD

**Issue by danilosampaio** [github/hub#986]
It would be very usefull if a could clone all repos from a github organization, all at once:

`hub clone acme/*`

is there a way to achive this?
Thanks. :wink:

**Comment by mislav** [comment]
No, sorry. The only way to achieve this right now would be to write a script that fetches all of the organization's repos from our API, then iterates through that list and clones each one. But I see no need for such a command in our library and therefore we won't be building it right now.
