### ISSUE TITLE
Cross-platform download script

### ISSUE THREAD

**Issue by totten** [github/hub#987]
Background: I work on a mid-size open-source project. Whenever we get together for coding events, there are always several folks who have partially setup a dev env -- but could use a dozen more tools (including `hub`). It helps to have a script which fetches those tools. Our current script works on Linux/OSX (and partially on Windows), but it only downloads hub 1.x. (When they're available, the ruby commands seem to be standardized enough). 

The hub 2.x binaries are cool because they don't have as many prerequisites and are pretty self-contained, but the install steps aren't as standardized. (You have to figure which binary to get.) It would be awesome to have a small wrapper script which could check `uname` and download the proper binary, as in:

```
$ curl http://hub.github.com/installer | sh -
$ ./hub help
```

If bash isn't quite good enough, one could get a similar benefit by publishing shims on a couple developer networks (e.g. npmjs, rubygems, or getcomposer), e.g.

```
$ npm install -g hub-cli
```

**Comment by mislav** [comment]
That's a good idea! I'd love to make installation easier. I will think about how to create this script.

**Comment by hediet** [comment]
I would love to have `hub` on `npm`. It should be very easy to publish the binaries to `npm`.
If nothing is against it, I would just do it on my own.

**Comment by ssbarnea** [comment]
Can we revive this? Unless you are on MacOS installing the tool is a PITA. As all platforms that matter do also have python, you could also use pip for installing it.

Also there is the option to create a bash script that detects platform and use it to install it, aka `curl-pipe-bash` installer.

**Comment by totten** [comment]
This looks like a relevant PR: #1585 (The commit is automatically cross-referenced above, but the PR is not.)
