### ISSUE TITLE
Hub authentication failure.

### ISSUE THREAD

**Issue by radicaled** [github/hub#988]
Fresh install on Ubuntu x64; have Hub working just fine on OS X Yosemite. Removed sensitive information with `[REDACTED]`.

```
$ HUB_VERBOSE=1 hub pull-request
github.com username: radicaled
github.com password for radicaled (never stored): 
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
{"scopes":["repo"],"note":"hub for arron@XXXG-SHENLONG","note_url":"http://hub.github.com/"}

< HTTP 201
< Location: https://api.github.com/authorizations/[REDACTED]
{"id":"[REDACTED]","url":"https://api.github.com/authorizations/[REDACTED]","app":{"name":"hub for arron@XXXG-SHENLONG (API)","url":"http://hub.github.com/","client_id":"00000000000000000000"},"token":"[REDACTED]","hashed_token":"[REDACTED]","token_last_eight":"[REDACTED]","note":"hub for arron@XXXG-SHENLONG","note_url":"http://hub.github.com/","created_at":"2015-09-01T23:54:46Z","updated_at":"2015-09-01T23:54:46Z","scopes":["repo"],"fingerprint":null}
> GET https://api.github.com/user
> Authorization: token [REDACTED]
< HTTP 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
Error getting current user: Unauthorized (HTTP 401)
Bad credentials
```
The token shows up under "Personal Access Tokens" in the settings page on Github, indicating it's been successfully created.

**Comment by radicaled** [comment]
Also, manually setting up `~/.config/hub` with the oauth token provided by the request works fine.

**Comment by mislav** [comment]
@radicaled That is really weird; sorry you had trouble. It tried to use just-created token but got a 401? What is your `hub --version`? Can you reproduce this by temporarily renaming your `~/.config/hub`.

**Comment by radicaled** [comment]
Temporarily renaming `~/.config/hub` results in another `~/.config/hub` being created with identical contents as soon as I perform any hub command. Is there a backup config file or something I should be aware of?

**Comment by mislav** [comment]
No, there isn't a backup config file. When you renamed your `~/.config/hub` to something else, hub should have asked you for authentication info again after you tried some hub command, correct? Did the authentication go OK? Did you receive any more 401 errors? When the new `~/.config/hub` was written to disk, it probably has a new OAuth token, but the rest will be identical. If everything worked, then your original issue was due to the server and just temporary.

**Comment by radicaled** [comment]
I'm unable to reproduce -- must have just been a temporary server issue, like you thought.

Sorry!
